import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {Collection} from 'discord.js';
import {DiscordChairismsCoordinator} from '../../dist/apps/bot/src/discord/chairisms-coordinator.js';
import {DiscordChairismPublication} from '../../dist/apps/bot/src/discord/chairisms-publication.js';
import {renderChairism} from '../../dist/packages/features-chairisms/src/render.js';
import {renderChairismBrowser} from '../../dist/packages/features-chairisms/src/presentation.js';
const guildId='111111111111111111',channelId='222222222222222222',userId='333333333333333333',messageId='444444444444444444';
function interaction(extra={}){return{guildId,guild:{},channelId,user:{id:userId},id:'interaction',deferred:false,replied:false,replies:[],isButton:()=>false,isChatInputCommand:()=>false,isMessageContextMenuCommand:()=>true,targetMessage:{channelId},targetId:messageId,deferReply:async function(){this.deferred=true;},editReply:async function(p){this.replies.push(p);this.replied=true;},reply:async function(p){this.replies.push(p);},followUp:async function(p){this.replies.push(p);},...extra};}
test('Both entry routes acknowledge before gates and show only real source choices',async()=>{for(const context of [false,true])for(const hasReply of [false,true])for(const hasImage of [false,true]){const i=interaction(context?{}:{isChatInputCommand:()=>true,isMessageContextMenuCommand:()=>false,commandName:'quote',options:{getSubcommand:()=> 'message',getString:()=>`https://discord.com/channels/${guildId}/${channelId}/${messageId}`}});const c=new DiscordChairismsCoordinator({inspectMessage:async()=>({reference:{channelId,messageId},hasReply,hasImage})},{},{},{get:async()=>{assert.equal(i.deferred,true);return true;}},async()=>true);await c.handle(i);assert.equal(i.replies[0].content,'');assert.deepEqual(i.replies[0].components[0].components.map(b=>b.data.label),['This Message',...(hasReply?['Reply']:[]),...(hasImage?['Image']:[]),...(hasReply&&hasImage?['Both']:[])]);}});
test('Browser keeps public references in artwork and functional links without a duplicated transcript',async()=>{const i=interaction({isChatInputCommand:()=>true,isMessageContextMenuCommand:()=>false,commandName:'chairisms',options:{getSubcommand:()=> 'recent'}});const rows=Array.from({length:10},(_,n)=>({chairismId:n+1,outputChannelId:channelId,outputMessageId:messageId,sourceUserId:userId,createdAt:'2026-09-26T00:00:00Z'}));await new DiscordChairismsCoordinator({assertCanBrowse:async()=>{}},{},{list:async()=>rows},{get:async()=>true},async()=>true).handle(i);const p=i.replies[0];assert.equal(p.content,'');assert.deepEqual(p.embeds,[]);assert.equal(p.components.length,3);assert.equal(p.components[0].components[0].data.label,'Chairism #1');assert.match(p.components[0].components[0].data.url,/discord.com\/channels/);});
test('Published quote recovery finds new private attachment identity and legacy footer without resending',async()=>{for(const legacy of [false,true]){const jobId='private-job-id',key='chairism:'+jobId,filename='preserved-'+createHash('sha256').update(key).digest('hex').slice(0,24)+'.png';let complete,finalized=0;const channel={messages:{fetch:async()=>new Collection([['saved',{id:'saved',author:{id:'bot'},embeds:legacy?[{footer:{text:key}}]:[],attachments:new Collection(legacy?[]:[['file',{name:filename}]])}]])}};const repo={job:async()=>({guildId,payload:{context:{guildId},outputChannelId:channelId}}),delivery:()=>({read:async()=>({state:'SENDING'}),complete:async id=>{complete=id;}}),finalize:async()=>{finalized++;return{};}};await new DiscordChairismPublication({user:{id:'bot'}},repo,{output:async()=>channel},{get:async()=>true}).deliver(jobId);assert.equal(complete,'saved');assert.equal(finalized,1);}});
test('Premium quote retains image without cropping and reply context in wide artwork',()=>{const q={userId,displayName:'Jordan',text:'A server moment.',timestamp:'2026-09-26T00:00:00Z'};const svg=renderChairism({quote:q,reply:{...q,displayName:'Other member',text:'Original context'},imageDataUri:'data:image/png;base64,YQ=='});assert.match(svg,/width="1200"/);assert.match(svg,/IN REPLY TO/);assert.match(svg,/preserveAspectRatio="xMidYMid meet"/);assert.match(svg,/Poppins/);assert.match(svg,/Cinzel/);assert.doesNotMatch(svg,/chairism:|userId|private-job/);assert.match(renderChairismBrowser([],'recent'),/Right-click a message/);});
test('New publication has only artwork, no raw recovery marker or duplicated title',async()=>{let sent;const snapshot={quote:{userId,displayName:'Jordan',text:'A server moment.',timestamp:'2026-09-26T00:00:00Z'}},channel={id:channelId,send:async p=>{sent=p;return{id:'saved'};}};const repo={job:async()=>({guildId,payload:{context:{guildId},outputChannelId:channelId,snapshot}}),delivery:()=>({read:async()=>({state:'PENDING'}),claim:async()=>true,complete:async()=>{}}),finalize:async()=>({})};await new DiscordChairismPublication({user:{id:'bot'}},repo,{output:async()=>channel,revalidate:async()=>{}},{get:async()=>true}).deliver('private-job-id');const embed=sent.embeds[0].toJSON();assert.equal(embed.footer,undefined);assert.equal(embed.author,undefined);assert.equal(embed.title,undefined);assert.match(sent.files[0].name,/^preserved-[a-f0-9]{24}\.png$/);assert.doesNotMatch(JSON.stringify(embed),/private-job-id|chairism:/);});
test('Owner browser pagination updates its existing private window',async()=>{let updates=0;const i=interaction({isButton:()=>true,isMessageContextMenuCommand:()=>false,customId:`chairism:browse:${userId}:recent:2:0`,deferUpdate:async function(){updates++;this.deferred=true;},deferReply:async()=>{throw Error('should update');}});await new DiscordChairismsCoordinator({assertCanBrowse:async()=>{}},{},{list:async()=>[]},{get:async()=>true},async()=>true).handle(i);assert.equal(updates,1);assert.equal(i.replies.length,1);assert.equal(i.replies[0].content,'');});
test('Short image and reply quotes stay landscape rather than stacking narrow towers',()=>{const q={userId,displayName:'Jordan',text:'Short moment',timestamp:'2026-09-26T00:00:00Z'};for(const extra of [{reply:q},{imageDataUri:'data:image/png;base64,YQ=='}]){const svg=renderChairism({quote:q,...extra});assert.ok(Number(svg.match(/<svg[^>]*height="(\d+)"/)[1])<750);assert.match(svg,/x="610" y="174"/);}});

test('same author in quote and reply has distinct portrait clip paths',()=>{const quote={userId:'333333333333333333',displayName:'Jordan',avatarDataUri:'data:image/png;base64,YQ==',text:'One moment.',timestamp:'2026-09-26T12:00:00Z'};const svg=renderChairism({quote,reply:quote});const ids=[...svg.matchAll(/<clipPath id="(portrait-[^"]+)"/g)].map(x=>x[1]);assert.equal(ids.length,2);assert.equal(new Set(ids).size,2);});
