import test from 'node:test';
import assert from 'node:assert/strict';
import {DiscordChairismsCoordinator} from '../../dist/apps/bot/src/discord/chairisms-coordinator.js';
import {renderChairism} from '../../dist/packages/features-chairisms/src/render.js';
const ids={guild:'111111111111111111',channel:'222222222222222222',user:'333333333333333333',message:'444444444444444444'};
function interaction(overrides={}){const replies=[];return{replies,guildId:ids.guild,guild:{},channelId:ids.channel,user:{id:ids.user},id:'request',deferred:false,replied:false,isButton:()=>false,isChatInputCommand:()=>true,isMessageContextMenuCommand:()=>false,commandName:'quote',options:{getSubcommand:()=> 'text',getString:()=> 'My own words.'},deferReply:async function(){this.deferred=true;},editReply:async function(p){replies.push(p);this.replied=true;},reply:async p=>replies.push(p),followUp:async p=>replies.push(p),...overrides};}
test('Chairisms disabled gate prevents security lookup and publication',async()=>{let calls=0;const boundary=new Proxy({}, {get:()=>async()=>{calls++;}}),i=interaction();await new DiscordChairismsCoordinator(boundary,boundary,boundary,{get:async()=>false},async()=>true).handle(i);assert.equal(calls,0);assert.match(i.replies[0].content,/not enabled/);});
test('Self-authored quote uses self capture and reports success only after confirmed publication',async()=>{const i=interaction(),seen=[];const security={captureSelf:async(c,text)=>{seen.push([c.userId,text]);return{quote:{userId:c.userId,displayName:'Member',text,timestamp:'2026-09-25T12:00:00Z'}};}};const publisher={publish:async(c,s)=>{assert.equal(s.quote.userId,c.userId);return{chairismId:1,outputMessageId:ids.message,outputChannelId:ids.channel};}};await new DiscordChairismsCoordinator(security,publisher,{}, {get:async()=>true},async()=>true).handle(i);assert.deepEqual(seen,[[ids.user,'My own words.']]);assert.match(i.replies[0].content,/Chairism created:/);assert.deepEqual(i.replies[0].allowedMentions,{parse:[]});});
test('Publication failure never claims that a Chairism was created',async()=>{const i=interaction();await new DiscordChairismsCoordinator({captureSelf:async()=>({})},{publish:async()=>{throw Error('transport');}}, {},{get:async()=>true},async()=>true).handle(i);assert.ok(!i.replies.some(p=>p.content?.startsWith('Chairism created:')));assert.match(i.replies[0].content,/could not be completed/);});
test('Quote rendering inherits the approved frame and escapes member text',()=>{const svg=renderChairism({quote:{userId:ids.user,displayName:'Member <name>',text:'<script>not code</script>',timestamp:'2026-09-25T12:00:00Z'}},{number:7});assert.match(svg,/font-family="Inter"/);assert.match(svg,/Space Grotesk/);assert.match(svg,/data:image\/png;base64/);assert.match(svg,/&lt;script&gt;/);assert.ok(!svg.includes('<script>'));assert.match(svg,/Chairism #7/);});
test('Source selector exposes only available options and selected source is recaptured before publish',async()=>{let captures=0,published=0;const security={inspectMessage:async()=>({reference:{channelId:ids.channel,messageId:ids.message},hasReply:true,hasImage:true}),captureMessage:async(c,ref,options)=>{captures++;assert.deepEqual(options,{includeReply:true,includeImage:true});assert.equal(ref.messageId,ids.message);return{quote:{userId:ids.user,displayName:'Member',text:'A chair.',timestamp:'2026-09-25T12:00:00Z'}};}};const publisher={publish:async()=>{published++;return{chairismId:1,outputMessageId:ids.message,outputChannelId:ids.channel};}},coordinator=new DiscordChairismsCoordinator(security,publisher,{}, {get:async()=>true},async()=>true),source=interaction({isChatInputCommand:()=>false,isMessageContextMenuCommand:()=>true,targetMessage:{channelId:ids.channel},targetId:ids.message});await coordinator.handle(source);assert.equal(captures,0);assert.equal(published,0);assert.equal(source.replies[0].components[0].components.length,4);const button=interaction({isButton:()=>true,customId:`chairism:publish_both:${ids.user}:${ids.channel}:${ids.message}`});await coordinator.handle(button);assert.equal(captures,1);assert.equal(published,1);});
test('Another member cannot reuse source or pagination controls',async()=>{let calls=0;const boundary=new Proxy({}, {get:()=>async()=>{calls++;}}),i=interaction({isButton:()=>true,customId:`chairism:this:555555555555555555:${ids.channel}:${ids.message}`});await new DiscordChairismsCoordinator(boundary,boundary,boundary,{get:async()=>true},async()=>true).handle(i);assert.equal(calls,0);assert.match(i.replies[0].content,/own Chairism controls/);});
import {ChannelType,PermissionFlagsBits,PermissionsBitField,Collection} from 'discord.js';
import {DiscordChairismSecurity,safeChairismMediaUrl,fetchChairismMedia,publicQuoteText} from '../../dist/apps/bot/src/discord/chairisms-security.js';
const output='666666666666666666',base='777777777777777777',bot='888888888888888888',avatar='data:image/png;base64,YQ==';
function fixture(){
 const context={guildId:ids.guild,channelId:ids.channel,userId:ids.user,requestKey:'source'},ref={channelId:ids.channel,messageId:ids.message},values={'channels.chairisms_channel':output,'roles.member_access':base,'chairisms.excluded_channel_ids':[]};
 const role={id:base,permissions:new PermissionsBitField(0n)},member={id:ids.user,user:{bot:false},displayName:'Actual member',isCommunicationDisabled:()=>false,displayAvatarURL:()=>`https://cdn.discordapp.com/avatars/${ids.user}/abc.png`};
 const channels=new Map(),messages=new Map(),fresh=[];const guild={id:ids.guild,roles:{fetch:async()=>new Collection([[base,role]])},members:{fetch:async options=>({...member,id:options.user})},channels:{fetch:async(id,options)=>{fresh.push(options.force);return channels.get(id);}}};
 const message={id:ids.message,guildId:ids.guild,channelId:ids.channel,guild,content:'Actual message',createdAt:new Date('2026-09-25T12:00:00Z'),author:{id:ids.user,bot:false,username:'member'},attachments:new Collection(),system:false};messages.set(ids.message,message);
 for(const id of [ids.channel,output])channels.set(id,{id,guildId:ids.guild,type:ChannelType.GuildText,permissionsFor:()=>new PermissionsBitField(PermissionFlagsBits.ViewChannel|PermissionFlagsBits.ReadMessageHistory|PermissionFlagsBits.SendMessages|PermissionFlagsBits.AttachFiles|PermissionFlagsBits.EmbedLinks),messages:{fetch:async o=>{const m=messages.get(o.message);if(!m)throw Error('not found');return m;}}});
 const security=new DiscordChairismSecurity({user:{id:bot},guilds:{fetch:async()=>guild}},{get:async(g,k)=>values[k]??null},async()=>true,async()=>avatar);return{security,context,ref,values,channels,messages,message,role,fresh};
}
test('Normal member-access role is public despite everyone onboarding gate; all accesses fetch fresh',async()=>{const f=fixture();const inspection=await f.security.inspectMessage(f.context,f.ref);assert.equal(inspection.hasReply,false);assert.ok(f.fresh.every(Boolean));const snapshot=await f.security.captureMessage(f.context,f.ref,{includeReply:false,includeImage:false});assert.equal(snapshot.quote.text,'Actual message');assert.equal(snapshot.quote.displayName,'Actual member');assert.equal(snapshot.sourceChannelLabel,undefined);});
test('Private/staff/evidence/quarantine/DM/cross-server/bot/system/deleted sources fail closed',async()=>{for(const change of [f=>{f.channels.get(ids.channel).permissionsFor=subject=>new PermissionsBitField(subject.id===base?0n:PermissionFlagsBits.Administrator);},f=>{f.values['channels.staff_log']=ids.channel;},f=>{f.values['chairisms.excluded_channel_ids']=[ids.channel];},f=>{f.channels.get(ids.channel).type=ChannelType.PrivateThread;},f=>{f.message.guildId='999999999999999999';},f=>{f.message.author.bot=true;},f=>{f.message.system=true;},f=>{f.messages.clear();},f=>{f.values['roles.throne']=base;}]){const f=fixture();change(f);await assert.rejects(f.security.inspectMessage(f.context,f.ref));}});
test('Replies and image are opt-in and independently revalidated; source edits are rejected',async()=>{const f=fixture(),replyId='999999999999999999';f.message.reference={guildId:ids.guild,channelId:ids.channel,messageId:replyId};f.messages.set(replyId,{...f.message,id:replyId,content:'Reply words'});const simple=await f.security.captureMessage(f.context,f.ref,{includeReply:false,includeImage:false});assert.equal(simple.reply,undefined);const reply=await f.security.captureMessage(f.context,f.ref,{includeReply:true,includeImage:false});assert.equal(reply.reply.text,'Reply words');f.messages.delete(replyId);await assert.rejects(f.security.revalidate(f.context,reply));await f.security.revalidate(f.context,simple);f.message.content='Edited';await assert.rejects(f.security.revalidate(f.context,simple));});
test('Image metadata is insufficient to bypass media allowlists/size limits; network redirects and content type are constrained',async()=>{assert.equal(safeChairismMediaUrl(`https://cdn.discordapp.com/attachments/${ids.channel}/${ids.message}/photo.png?ex=123`,'attachment'),true);for(const url of ['https://127.0.0.1/x.png','https://cdn.discordapp.com.evil.test/x.png',`https://cdn.discordapp.com/attachments/${ids.channel}/${ids.message}/x.svg`,`https://user:pass@cdn.discordapp.com/attachments/${ids.channel}/${ids.message}/x.png`])assert.equal(safeChairismMediaUrl(url,'attachment'),false);let called=0;await assert.rejects(fetchChairismMedia('http://localhost/a.png','attachment',async()=>{called++;}));assert.equal(called,0);await assert.rejects(fetchChairismMedia(`https://cdn.discordapp.com/attachments/${ids.channel}/${ids.message}/x.png`,'attachment',async(url,options)=>{assert.equal(options.redirect,'error');return new Response('bad',{headers:{'content-type':'text/html'}});}));});
test('Private channel mentions and message links never disclose names/identifiers in quote text',()=>{assert.equal(publicQuoteText(`Look <#${ids.channel}> https://discord.com/channels/${ids.guild}/${ids.channel}/${ids.message}`),'Look #channel [message link]');});
test('Privacy activity/roast preferences are unrelated to public Chairisms and self text attribution is fixed',async()=>{const f=fixture();f.values['privacy.activity']=false;f.values['privacy.roast']=false;const self=await f.security.captureSelf(f.context,'My words');assert.equal(self.quote.userId,ids.user);await f.security.assertCanBrowse(f.context,[ids.user]);});
test('Media reader rejects oversized streams even with missing content length',async()=>{let requests=0;await assert.rejects(fetchChairismMedia(`https://cdn.discordapp.com/attachments/${ids.channel}/${ids.message}/x.png`,'attachment',async()=>{requests++;return new Response(new Uint8Array(5_000_001),{headers:{'content-type':'image/png'}});}));assert.equal(requests,1);});
test('Image selection is explicit and missing/deleted chosen image blocks pending publication',async()=>{const f=fixture();f.message.attachments.set(ids.message,{id:ids.message,size:100,contentType:'image/png',url:`https://cdn.discordapp.com/attachments/${ids.channel}/${ids.message}/photo.png`});const snapshot=await f.security.captureMessage(f.context,f.ref,{includeReply:false,includeImage:true});assert.equal(snapshot.imageDataUri,avatar);f.message.attachments.clear();await assert.rejects(f.security.revalidate(f.context,snapshot));});
import {DiscordChairismPublication} from '../../dist/apps/bot/src/discord/chairisms-publication.js';
test('Browsing filters inaccessible/missing public outputs before page or random selection and never reads source content',async()=>{const context={guildId:ids.guild,channelId:ids.channel,userId:ids.user,requestKey:'browse'},rows=Array.from({length:12},(_,n)=>({id:12-n,sourceUserId:ids.user,createdAt:new Date('2026-09-25T12:00:00Z')}));const repo={metadata:async()=>rows,publishedOutput:async(g,id)=>id===12?undefined:{chairismId:id,outputChannelId:output,outputMessageId:String(id)}},security={assertCanBrowse:async()=>{},canBrowseOutput:async(c,ch,msg)=>msg!=='11'};const browser=new DiscordChairismPublication({},repo,security,{});const recent=await browser.list(context,{mode:'recent'});assert.equal(recent.length,10);assert.deepEqual(recent.map(x=>x.chairismId),[10,9,8,7,6,5,4,3,2,1]);for(let n=0;n<10;n++){const random=await browser.list(context,{mode:'random'});assert.equal(random.length,1);assert.ok(random[0].chairismId>=1&&random[0].chairismId<=10);}});

test('Chairism wide names wrap completely and long wide quote lines stay inside the frame',()=>{const q={userId:ids.user,displayName:'W'.repeat(100),text:'W'.repeat(1200),timestamp:'2026-09-25T12:00:00Z',avatarDataUri:'data:image/png;base64,YQ=='};const svg=renderChairism({quote:q});assert.equal([...svg.matchAll(/<text x="830"[^>]*font-size="30"[^>]*>(W+)<\/text>/g)].map(x=>x[1]).join(''),q.displayName);assert.doesNotMatch(svg,/W{45}/);const quoteText=[...svg.matchAll(/<text x="830"[^>]*font-size="(?!30")\d+"[^>]*>(W+)<\/text>/g)].map(x=>x[1]).join('');assert.equal(quoteText,q.text);assert.ok(Number(svg.match(/height="(\d+)"/)[1])>1000);});

test('Chairism quote and author are centered within their own area beside the profile image',()=>{const svg=renderChairism({quote:{userId:ids.user,displayName:'Al',text:'A chair.',timestamp:'2026-09-25T12:00:00Z'}});assert.match(svg,/<text x="830"[^>]*text-anchor="middle"[^>]*>A chair\.<\/text>/);assert.match(svg,/<text x="830"[^>]*text-anchor="middle"[^>]*>Al<\/text>/);assert.match(svg,/portrait-chairism/);assert.doesNotMatch(svg,/THE MOMENT/);});
test('Chairism unavailable notice includes a branded runtime attachment',async()=>{const i=interaction();await new DiscordChairismsCoordinator({}, {}, {}, {get:async()=>false},async()=>true).handle(i);assert.ok(i.replies[0].files[0].attachment.length>1000);});

test('all four modes require confirmation and carry layout/reply/image choices without early publication',async()=>{
 for(const mode of ['short','long','reply','image']){let calls=0,captured;const security={inspectMessage:async()=>({reference:{channelId:ids.channel,messageId:ids.message},hasReply:true,hasImage:true}),captureMessage:async(c,ref,opts)=>{captured=opts;return{quote:{userId:ids.user,displayName:'Member',text:'Words',timestamp:'2026-09-25T12:00:00Z'}};}};
 const publication={publish:async(c,s)=>{calls++;assert.equal(c.requestKey,'confirmation:confirmation');if(mode==='short'||mode==='long')assert.equal(s.layout,mode);return{chairismId:1,outputChannelId:ids.channel,outputMessageId:ids.message};}};
 const coordinator=new DiscordChairismsCoordinator(security,publication,{}, {get:async()=>true},async()=>true);
 const selected=interaction({isButton:()=>true,customId:'chairism:'+mode+':'+ids.user+':'+ids.channel+':'+ids.message});await coordinator.handle(selected);assert.equal(calls,0);
 const confirm=selected.replies[0].components[0].components[0].data.custom_id;
 await coordinator.handle(interaction({isButton:()=>true,customId:confirm,message:{id:'confirmation'}}));assert.equal(calls,1);assert.deepEqual(captured,{includeReply:mode==='reply',includeImage:mode==='image'});
 }
});
