import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {alwaysRegisteredCommand,chairismRegistrationEnabled,validateRegisteredCommands} from '../../dist/apps/bot/src/command-registration.js';
test('member DM preference remains a registered slash command without optional feature flags',()=>{assert.equal(alwaysRegisteredCommand({name:'dms',type:1}),true);assert.equal(alwaysRegisteredCommand({name:'dms',type:3}),false);assert.equal(alwaysRegisteredCommand({name:'roles',type:1}),false);});
test('Chairisms flag alone selects exact context and slash commands from production artifact',()=>{const commands=JSON.parse(fs.readFileSync('dist/generated/discord/application_commands.json','utf8'));assert.deepEqual(commands.filter(c=>chairismRegistrationEnabled(c,true)).map(c=>[c.name,c.type]).sort(),[['Create Chairism',3],['chairisms',1],['quote',1]]);assert.equal(commands.filter(c=>chairismRegistrationEnabled(c,false)).length,0);assert.equal(chairismRegistrationEnabled({name:'Create Chairism',type:1},true),false);});
test('registration verifies names and types, independent of Discord response order and IDs',()=>{const expected=[{name:'quote',type:1},{name:'Create Chairism',type:3}];validateRegisteredCommands(expected,[{name:'Create Chairism',type:3,id:'1'},{name:'quote',type:1,id:'2'}]);for(const bad of [null,[],[{name:'quote',type:1}],[{name:'quote',type:1},{name:'Create Chairism',type:1}],[{name:'quote',type:1},{name:'Wrong name',type:3}]])assert.throws(()=>validateRegisteredCommands(expected,bad),{code:'COMMAND_REGISTRATION_MISMATCH'});});
test('the registry hides an entirely Throne-only command from ordinary member discovery',()=>{const commands=JSON.parse(fs.readFileSync('generated/discord/application_commands.json','utf8'));assert.equal(commands.find(c=>c.name==='panic')?.default_member_permissions,'0');assert.equal(commands.find(c=>c.name==='help')?.default_member_permissions,undefined);});
test('migration remains one-shot and both release approvals remain mandatory',()=>{const cfg=JSON.parse(fs.readFileSync('railway/migration.json','utf8'));assert.equal(cfg.deploy.restartPolicyType,'NEVER');assert.equal(cfg.deploy.numReplicas,1);assert.equal(cfg.deploy.startCommand,'node scripts/migrate-production.mjs');assert.equal(cfg.deploy.cronSchedule,undefined);const script=fs.readFileSync('scripts/migrate-production.mjs','utf8');assert.match(script,/built!==process.env.AJ_MIGRATION_RELEASE/);const runtime=fs.readFileSync('packages/core/src/runtime-environment.ts','utf8');assert.match(runtime,/AJ_PRODUCTION_MIGRATIONS_APPROVED/);});
