import test from 'node:test';
import assert from 'node:assert/strict';
import {renderCommunity,renderCommunityNotice,superlativeReviewFixture,communityTranscript} from '../../dist/packages/features-community/src/render.js';
const poll={...superlativeReviewFixture(),kind:'poll',state:'OPEN',phase:'open',title:'Which lounge night?',choices:[{id:'1',label:'Games'},{id:'2',label:'Music'}],categories:[],results:undefined};
test('Community surfaces use wide restrained amber lounge plates without changing transcripts',()=>{for(const kind of ['poll','suggest','ama','giveaway','superlatives']){const v=kind==='superlatives'?superlativeReviewFixture():{...poll,kind,fee:'0',winnerCount:1,entryCount:0};const svg=renderCommunity(v);assert.match(svg,/<svg[^>]*width="1200"/);assert.match(svg,/#F5BC60/);assert.match(svg,/#443322/);assert.match(svg,/Cinzel/);assert.match(svg,/Poppins/);assert.equal(renderCommunity(v),svg);assert.ok(communityTranscript(v).length>0);}});
test('Community hidden votes and anonymous identities remain absent from artwork',()=>{const svg=renderCommunity({...poll,anonymous:true,submitterName:'Hidden author',ownerId:'private-owner',hidden:true});assert.doesNotMatch(svg,/Hidden author|private-owner/);assert.match(svg,/Results stay hidden until close/);assert.doesNotMatch(svg,/0 votes/);});
test('Community result and pending fulfillment semantics remain accurate',()=>{const v={...poll,kind:'giveaway',state:'CLOSED',title:'Community gift',fee:'0',winnerCount:3,entryCount:1,winners:[{id:'a',name:'Alex'}],choices:[],status:'FULFILLMENT_PENDING'};const svg=renderCommunity(v);assert.match(svg,/1 winner · 1 entry/);assert.match(svg,/Alex/);assert.doesNotMatch(svg,/rewards recorded/);assert.match(svg,/organizer fulfillment pending/i);});

test("Community private notices share amber materials and escape member input",()=>{const svg=renderCommunityNotice("Vote saved","A <chair> & a voice");assert.match(svg,/#F5BC60/);assert.match(svg,/A &lt;chair&gt; &amp; a voice/);assert.match(svg,/<svg[^>]*width="1200"/);});
