import test from 'node:test';import assert from 'node:assert/strict';
import {DiscordCommunityCoordinator} from '../../dist/apps/bot/src/discord/community-coordinator.js';
import {renderCommunity,communityTranscript,superlativeReviewFixture} from '../../dist/packages/features-community/src/render.js';
const forbidden=new Proxy({},{get:()=>()=>{throw Error('Repository must not be accessed');}}),config=overrides=>({get:async(_g,k)=>({'features.community':true,'channels.bot_channel':'bot',...overrides})[k]});
const interaction=(patch={})=>({guildId:'g',guild:{ownerId:'owner',members:{fetch:async()=>({id:'u',user:{bot:false},displayName:'Member',isCommunicationDisabled:()=>false,permissionsIn:()=>({has:()=>true}),roles:{cache:new Map()}})}},channelId:'bot',user:{id:'u'},id:'request',commandName:'poll',calls:[],options:{getString:()=>null},isChatInputCommand:()=>true,isButton:()=>false,isStringSelectMenu:()=>false,isUserSelectMenu:()=>false,isModalSubmit:()=>false,reply:async function(p){this.calls.push(p);this.replied=true;},followUp:async function(p){this.calls.push(p);},...patch});
test('community gates flag, configured channel and fresh member restrictions before repository reads',async()=>{for(const[o,eligible,pattern]of [[{'features.community':false},true,/not enabled/],[{'channels.bot_channel':'elsewhere'},true,/bot channel/],[{},false,/eligible member/]]){const i=interaction();await new DiscordCommunityCoordinator(forbidden,config(o),async()=>eligible).handle(i);assert.match(i.calls[0].content,pattern);}});
const view={...superlativeReviewFixture(),id:'round',guildId:'g',channelId:'bot',messageId:'original',kind:'poll',state:'OPEN',phase:'open',title:'A <chair> & a voice',choices:[{id:'1',label:'First'},{id:'2',label:'Second'}],categories:[],season:undefined};
test('forged original messages and cross-server controls reject without mutation',async()=>{for(const[patch,v,pattern]of [[{message:{id:'forged'}},view,/original community/],[{message:{id:'original'}},{...view,guildId:'other'},/original server/]]){const i=interaction({isChatInputCommand:()=>false,isButton:()=>true,customId:'community:vote:round',...patch}),repo={publicView:async()=>v};await new DiscordCommunityCoordinator(repo,config({}),async()=>true).handle(i);assert.match(i.calls[0].content,pattern);}});
test('paid confirmation is bound to member and exact visible fee',async()=>{const i=interaction({isChatInputCommand:()=>false,isButton:()=>true,customId:'community:confirm_entry:round:100:someone-else',message:{id:'private'}});await new DiscordCommunityCoordinator({publicView:async()=>({...view,kind:'giveaway',fee:'100'})},config({}),async()=>true).handle(i);assert.match(i.calls[0].content,/own choices/);const open=interaction({isChatInputCommand:()=>false,isButton:()=>true,customId:'community:enter:round',message:{id:'original'}});await new DiscordCommunityCoordinator({publicView:async()=>({...view,kind:'giveaway',fee:'100'})},config({}),async()=>true).handle(open);assert.match(open.calls[0].content,/100 Ottomans/);assert.match(open.calls[0].components[0].toJSON().components[0].custom_id,/:100:u$/);});
test('AMA answer control checks shared community.manage before opening a modal',async()=>{const i=interaction({isChatInputCommand:()=>false,isButton:()=>true,customId:'community:answer:round',message:{id:'original'}});await new DiscordCommunityCoordinator({publicView:async()=>({...view,kind:'ama'})},config({}),async()=>true).handle(i);assert.match(i.calls[0].content,/Chaise Lounge or Throne/);});
test('runtime Superlative card uses approved deterministic shell and real winner fields',()=>{const v=superlativeReviewFixture(),a=renderCommunity(v),b=renderCommunity(v);assert.equal(a,b);assert.match(a,/Morgan/);assert.match(a,/Permanent season badge/);assert.match(a,/Space Grotesk/);assert.match(a,/Inter/);assert.doesNotMatch(a,/Poppins|Cinzel/);assert.match(communityTranscript(v),/Season 1/);assert.match(renderCommunity(view),/A &lt;chair&gt; &amp; a voice/);});
test('long unbroken member text wraps inside the card and remains complete in Details',()=>{const title='x'.repeat(300),v={...view,title},svg=renderCommunity(v);assert.doesNotMatch(svg,new RegExp('x{40}'));assert.ok(communityTranscript(v).includes(title));});
test('single Superlative winner is prominent while long names remain available in Details',()=>{const fixture=superlativeReviewFixture(),svg=renderCommunity(fixture),winner=svg.match(/font-size="(\d+)"[^>]*>Morgan<\/text>/);assert.ok(winner&&Number(winner[1])>=36);assert.match(svg,/SEASON BADGE EARNED/);assert.match(svg,/The winner</);const name='A'.repeat(80),long={...fixture,categories:[{...fixture.categories[0],winner:{id:'long',name}}]},longSvg=renderCommunity(long);assert.doesNotMatch(longSvg,/A{27}/);assert.equal([...longSvg.matchAll(/font-size="28"[^>]*>(A+)<\/text>/g)].map(m=>m[1]).join(''),name);assert.ok(communityTranscript(long).includes(name));});
test('closed result payload has no repeat entry or rematch controls and suppresses mentions',async()=>{const payload=await new DiscordCommunityCoordinator(forbidden,config({}),async()=>true).payload(superlativeReviewFixture()),labels=payload.components.flatMap(r=>r.toJSON().components.map(c=>c.label));assert.deepEqual(labels,['Details']);assert.deepEqual(payload.allowedMentions,{parse:[]});assert.equal(payload.embeds[0].toJSON().author.name,'Angrier Jordan');});
test('different version publication jobs share the initial durable delivery claim before message linking',async()=>{let state='PENDING',sent=0,linked=null;const deliveryIds=[],delivery={read:async()=>({state,...(linked?{messageId:linked}:{})}),claim:async()=>{if(state!=='PENDING')return false;state='SENDING';return true;},complete:async id=>{state='SENT';linked=id;}},repo={deliveryJob:async()=>({sessionId:'round',guildId:'g',channelId:'bot'}),publicView:async()=>({...view,messageId:linked}),initialPublication:async()=>({id:'initial-job'}),delivery:id=>{deliveryIds.push(id);return delivery;},linkMessage:async(_id,_g,id)=>{linked=id;}},channel={isSendable:()=>true,messages:{fetch:async()=>({find:()=>undefined})},send:async()=>{sent++;await new Promise(resolve=>setTimeout(resolve,10));return{id:'sent'};}},client={channels:{fetch:async()=>channel},user:{id:'bot'}},coordinator=new DiscordCommunityCoordinator(repo,config({}),async()=>true);coordinator.payload=async()=>({content:'Post'});const results=await Promise.allSettled([coordinator.publish(client,'version-0'),coordinator.publish(client,'version-1')]);assert.equal(sent,1);assert.ok(results.some(x=>x.status==='fulfilled'));assert.deepEqual(new Set(deliveryIds),new Set(['initial-job']));assert.equal(linked,'sent');});

test('disabled Community recovery retains pending jobs without settlement or Discord publication',async()=>{let advanced=0,published=0,reads=0;const repo={deliveryJob:async()=>({guildId:'g',sessionId:'pending'}),publicView:async()=>{reads++;return view;},advance:async()=>{advanced++;},active:async()=>[{id:'pending',guildId:'g',expiresAt:new Date(0),data:{round:0}}]},client={channels:{fetch:async()=>{published++;throw Error('Must not fetch Discord');}}},coordinator=new DiscordCommunityCoordinator(repo,config({'features.community':false}),async()=>true);await assert.rejects(coordinator.publish(client,'pending'),{code:'COMMUNITY_DISABLED'});await assert.rejects(coordinator.advance(client,'g','pending',0),{code:'COMMUNITY_DISABLED'});await coordinator.sweep(client);assert.equal(advanced,0);assert.equal(published,0);assert.equal(reads,0);});
test('closed empty seasons and giveaways never claim nonexistent awards or maximum winner counts',()=>{const season={...superlativeReviewFixture(),categories:[{id:'1',name:'An empty category',finalists:[]}]};assert.match(renderCommunity(season),/No nominations · no badges awarded/);assert.doesNotMatch(renderCommunity(season),/Permanent season badges awarded/);assert.match(renderCommunity(season),/No winners/);const giveaway={...view,kind:'giveaway',state:'CLOSED',phase:'closed',title:'Giveaway',choices:[],winnerCount:5,entryCount:1,fee:'0',winners:[{id:'member',name:'Member'}],prize:{kind:'custom',label:'Gift'},status:'FULFILLMENT_PENDING'};assert.match(communityTranscript(giveaway),/1 winner · 1 entry/);assert.match([...renderCommunity(giveaway).matchAll(/<text[^>]*>([^<]*)<\/text>/g)].map(m=>m[1]).join(' '),/organizer fulfillment pending/i);assert.doesNotMatch(renderCommunity(giveaway),/rewards recorded/);assert.match(renderCommunity({...giveaway,entryCount:0,winners:[],status:'COMPLETED'}),/No entries · no prizes awarded/);});
test('wide-glyph Community text is bounded at its actual font size and retained in Details',()=>{const title='W'.repeat(200),svg=renderCommunity({...view,title});assert.doesNotMatch(svg,/W{30}/);assert.ok(communityTranscript({...view,title}).includes(title));});

test('declined and fulfillment-pending statuses use approved attention color instead of success',()=>{for(const status of ['DECLINED','FULFILLMENT_PENDING','REVIEWING'])assert.match(renderCommunity({...view,status}),new RegExp('fill=\"#FFE29A\"[^>]*>'+status.replaceAll('_',' ')+'<'));});

test('Community private ballot and financial confirmation use actual branded runtime attachments',async()=>{for(const[action,v]of [['vote',view],['enter',{...view,kind:'giveaway',fee:'12345678901234567890'}]]){const i=interaction({isChatInputCommand:()=>false,isButton:()=>true,customId:'community:'+action+':round',message:{id:'original'}});await new DiscordCommunityCoordinator({publicView:async()=>v},config({}),async()=>true).handle(i);assert.ok(i.calls[0].files[0].attachment.length>1000);assert.ok(i.calls[0].components.length);}});
test('Anonymous Community content never fetches member art; public finalists do',async()=>{const seen=[],client={guilds:{fetch:async()=>({members:{fetch:async({user})=>{seen.push(user);return {displayName:'Public member',user:{},displayAvatarURL:()=>''};}}})}};const c=new DiscordCommunityCoordinator(forbidden,config({}),async()=>true);await c.payload({...view,anonymous:true,ownerId:'private-author',submitterName:'Hidden name'},client);assert.deepEqual(seen,[]);await c.payload({...superlativeReviewFixture(),phase:'voting',state:'OPEN',categories:[{id:'1',name:'Best storyteller',finalists:[{id:'first',name:'Al'},{id:'second',name:'Bea'}]}]},client);assert.deepEqual(seen,['first','second']);});
test('Centered Community layouts grow with multiple members and remain compact for short state',()=>{const fixture=superlativeReviewFixture(),one=renderCommunity(fixture),two=renderCommunity({...fixture,categories:[...fixture.categories,{id:'2',name:'Best storyteller',finalists:[],winner:{id:'second',name:'Alex'}}]});assert.ok(Number(two.match(/height="(\d+)"/)[1])>Number(one.match(/height="(\d+)"/)[1]));assert.ok([...one.matchAll(/<text[^>]*>/g)].every(m=>m[0].includes('text-anchor="middle"')));const empty=renderCommunity({...view,choices:[],title:'Hi'});assert.ok(Number(empty.match(/height="(\d+)"/)[1])<1200);});
