import test from 'node:test';import assert from 'node:assert/strict';import {Collection} from 'discord.js';import {createHash} from 'node:crypto';import {DiscordCommunityCoordinator} from '../../dist/apps/bot/src/discord/community-coordinator.js';import {superlativeReviewFixture} from '../../dist/packages/features-community/src/render.js';import {renderSpotlight} from '../../dist/packages/features-profiles/src/render.js';
const view={...superlativeReviewFixture(),id:'round',guildId:'g',channelId:'c',messageId:'m',ownerId:'u',kind:'poll',state:'OPEN',phase:'open',categories:[],choices:[{id:'1',label:'Tea'}],hidden:true,anonymous:true};
function setup(action,privateMessage=false){const events=[],i={guildId:'g',channelId:'c',guild:{ownerId:'u',members:{fetch:async()=>({user:{bot:false},displayName:'Member',roles:{cache:new Map()},permissionsIn:()=>({has:()=>true}),isCommunicationDisabled:()=>false})}},user:{id:'u'},id:'request',customId:'community:'+action+':round',message:{id:privateMessage?'private':'m',flags:{has:()=>privateMessage}},values:['1'],isChatInputCommand:()=>false,isModalSubmit:()=>false,isButton:()=>!privateMessage,isStringSelectMenu:()=>privateMessage,isUserSelectMenu:()=>false,deferUpdate:async()=>{events.push('ack');i.deferred=true;},deferReply:async()=>{events.push('ack');i.deferred=true;},editReply:async p=>events.push(p),followUp:async p=>events.push(p),deleteReply:async()=>events.push('delete')};const config={get:async(g,k)=>{events.push('config');return {'features.community':true,'channels.bot_channel':'c'}[k];}};return {i,events,config};}
test('public close acknowledges before reads and succeeds without a private card',async()=>{const {i,events,config}=setup('close');const c=new DiscordCommunityCoordinator({publicView:async()=>view,closePoll:async()=>events.push('close')},config,async()=>true);c.refresh=async()=>events.push('refresh');await c.handle(i);assert.equal(events[0],'ack');assert.ok(events.includes('close'));assert.ok(events.includes('refresh'));assert.equal(events.filter(x=>typeof x==='object').length,0);});
test('private ballot saves in place and clears its image and controls',async()=>{const {i,events,config}=setup('vote_pick',true);const c=new DiscordCommunityCoordinator({publicView:async()=>view,vote:async()=>events.push('vote')},config,async()=>true);c.refresh=async()=>{};await c.handle(i);const result=events.find(x=>typeof x==='object');assert.equal(events[0],'ack');assert.ok(events.includes('vote'));assert.deepEqual(result.files,[]);assert.deepEqual(result.components,[]);assert.deepEqual(result.attachments,[]);});
test('public payload carries no raw markers or duplicate transcript',async()=>{const c=new DiscordCommunityCoordinator({}, {get:async()=>true},async()=>true),p=await c.payload(view),embed=p.embeds[0].toJSON();assert.equal(embed.footer,undefined);assert.equal(embed.description,undefined);assert.equal(embed.title,undefined);assert.ok(!JSON.stringify(embed).includes('community:'));});
test('unchanged publication skips fetch/render/edit after one successful edit',async()=>{let edits=0,fetches=0;const c=new DiscordCommunityCoordinator({publicView:async()=>view},{get:async()=>true},async()=>true);c.payload=async()=>({});const message={author:{id:'bot'},edit:async()=>{edits++;}};const channel={isTextBased:()=>true,messages:{fetch:async()=>message}};const client={user:{id:'bot'},channels:{fetch:async()=>{fetches++;return channel;}}};await c.refresh(client,'round');await c.refresh(client,'round');assert.equal(edits,1);assert.equal(fetches,1);});
test('delivery recovery finds hidden attachment identity without visible footer',async()=>{let sent=0,linked;const filename='community-'+createHash('sha256').update('round').digest('hex').slice(0,24)+'.png';const repo={deliveryJob:async()=>({sessionId:'round',guildId:'g',channelId:'c'}),publicView:async()=>({...view,messageId:null}),initialPublication:async()=>({id:'job'}),delivery:()=>({read:async()=>({state:'SENDING'}),claim:async()=>false,complete:async id=>{linked=id;}}),linkMessage:async(g,c,id)=>{linked=id;}};const coordinator=new DiscordCommunityCoordinator(repo,{get:async()=>true},async()=>true);await coordinator.publish({user:{id:'bot'},channels:{fetch:async()=>({isSendable:()=>true,messages:{fetch:async()=>new Collection([['existing',{id:'existing',author:{id:'bot'},embeds:[],attachments:new Collection([['a',{name:filename}]])}]])},send:async()=>{sent++;}})}},'job');assert.equal(sent,0);assert.equal(linked,'existing');});
test('Spotlight uses wide amber award columns and permanent honor text without changing totals',()=>{const svg=renderSpotlight({weekStart:'2026-09-20',weekEnd:'2026-09-27',activeMembers:3,messages:24,words:120,voiceSeconds:600,categories:['Messages','Words','Voice'].map(title=>({title,winners:[{name:'Jordan',avatarData:'',total:'24',lifetimeWins:2,status:'NEW WINNER',tripleThreat:true}]}))});for(const str of ['width="1200"','Poppins','Cinzel','#F59E0B','TRIPLE THREAT','2 lifetime wins','600 voice seconds'])assert.ok(svg.includes(str),str);});

import {DiscordProfilesCoordinator} from '../../dist/apps/bot/src/discord/profiles-coordinator.js';
test('Spotlight reconciliation preserves existing award announcement without visible marker',async()=>{let sent=0,delivered;const week='2026-09-20',filename='weekly-honors-'+createHash('sha256').update('spotlight:'+week).digest('hex').slice(0,24)+'.png';const repo={announcement:async()=>({deliveryState:'SENDING',snapshot:{winners:[],tripleThreat:[],activeMembers:0,totals:{}}}),awardDetails:async()=>[],delivered:async(g,w,id)=>{delivered=id;},claimAnnouncement:async()=>false};const c=new DiscordProfilesCoordinator(repo,{get:async(g,k)=>k==='features.spotlight'?true:'c'},async()=>true);const message={id:'prior',author:{id:'bot'},embeds:[],attachments:new Collection([['a',{name:filename}]])};await c.announce({user:{id:'bot'},channels:{fetch:async()=>({isTextBased:()=>true,send:async()=>{sent++;},messages:{fetch:async()=>new Collection([['prior',message]])}})}},'g',week);assert.equal(sent,0);assert.equal(delivered,'prior');});
