import test from 'node:test';
import assert from 'node:assert/strict';
import {DiscordCrimeCoordinator} from '../../dist/apps/bot/src/discord/crime-coordinator.js';
import {renderCrime,crimeDescription} from '../../dist/packages/features-crime/src/render.js';
const fixture={id:'fixture',guildId:'g',channelId:'bot',state:'CLOSED',version:2,createdAt:new Date(),robber:{userId:'r',name:'Jordan'},victim:{userId:'v',name:'Morgan'},success:true,stolen:'100',returned:true,reports:2,caught:true,bail:'340',sentenceId:'sentence',fightBackEndsAt:new Date().toISOString(),reportEndsAt:new Date().toISOString()};
test('Crime arrest/mugshot uses approved frame and exposes no stored outcome rolls',()=>{const svg=renderCrime({...fixture,catchRoll:'SECRET_ROLL'});assert.match(svg,/Under Arrest/);assert.match(svg,/MEMBER IN CUSTODY/);assert.match(svg,/Space Grotesk/);assert.match(svg,/font-family="Inter"/);assert.match(svg,/data:image\/png;base64/);assert.ok(!svg.includes('SECRET_ROLL'));assert.match(crimeDescription(fixture),/100 stolen Ottomans returned/);});
test('Committed public incident sends reconcile uncertainty through shared DeliveryEngine without duplicate posts',async()=>{let state='PENDING',messageId,sends=0,published,linked;const delivery={read:async()=>({state,messageId}),claim:async()=>{if(state!=='PENDING')return false;state='SENDING';return true;},complete:async id=>{state='SENT';messageId=id;}},repo={publication:async()=>({guildId:'g',channelId:'bot',sessionId:'fixture'}),delivery:()=>delivery,publicView:async()=>fixture,linkMessage:async(id,g,msg)=>{linked=msg;}},channel={isSendable:()=>true,messages:{fetch:async()=>({find:fn=>published&&fn(published)?published:undefined})},send:async payload=>{sends++;published={id:'public-message',author:{id:'bot'},embeds:payload.embeds.map(e=>e.data)};throw Error('Uncertain network acknowledgement');}},client={user:{id:'bot'},channels:{fetch:async()=>channel}},coordinator=new DiscordCrimeCoordinator(repo,{},async()=>true);await assert.rejects(()=>coordinator.deliver(client,'job'));assert.equal(sends,1);assert.equal(state,'SENDING');assert.equal(await coordinator.deliver(client,'job'),'public-message');assert.equal(sends,1);assert.equal(linked,'public-message');assert.equal(state,'SENT');});
test('Crime feature/channel/eligibility guards prevent repository mutation',async()=>{let calls=0;const repo=new Proxy({}, {get:()=>()=>{calls++;throw Error('No repository calls allowed');}}),sent=[],i={guildId:'g',guild:{id:'g',members:{fetch:async()=>({user:{bot:false},isCommunicationDisabled:()=>false,permissionsIn:()=>({has:()=>true})})}},channelId:'bot',user:{id:'u'},commandName:'crime',options:{getSubcommand:()=> 'rob'},isChatInputCommand:()=>true,reply:async p=>sent.push(p)};await new DiscordCrimeCoordinator(repo,{get:async()=>false},async()=>true).handle(i);assert.match(sent.pop().content,/not enabled/);await new DiscordCrimeCoordinator(repo,{get:async(g,k)=>k==='features.crime'?true:'wrong'},async()=>true).handle(i);assert.match(sent.pop().content,/bot channel/);await new DiscordCrimeCoordinator(repo,{get:async(g,k)=>k==='features.crime'?true:'bot'},async()=>false).handle(i);assert.match(sent.pop().content,/eligible/);assert.equal(calls,0);});
test('Self-bail selector bypasses only crime jail and is actor-bound/private',async()=>{let jailedCalls=0;const repo={isJailed:async()=>{jailedCalls++;return true;}},sent=[],i={guildId:'g',guild:{id:'g',members:{fetch:async()=>({user:{bot:false},isCommunicationDisabled:()=>false,permissionsIn:()=>({has:()=>true})})}},channelId:'bot',user:{id:'jailed'},commandName:'crime',options:{getSubcommand:()=> 'bail'},isChatInputCommand:()=>true,reply:async p=>sent.push(p)};await new DiscordCrimeCoordinator(repo,{get:async(g,k)=>k==='channels.bot_channel'?'bot':false},async()=>true).handle(i);assert.equal(jailedCalls,0);assert.equal(sent[0].ephemeral,true);assert.deepEqual(sent[0].allowedMentions,{parse:[]});assert.equal(sent[0].components[1].components[0].data.custom_id,'crime:bailself:jailed');sent.length=0;await new DiscordCrimeCoordinator(repo,{get:async(g,k)=>k==='channels.bot_channel'?'bot':true},async()=>false).handle(i);assert.match(sent[0].content,/eligible/);});

test('Crime centers long names, large bail and warning copy inside its adaptive panel',()=>{const v={...fixture,robber:{...fixture.robber,name:'W'.repeat(32)},bail:'9223372036854775807'},svg=renderCrime(v),height=Number(svg.match(/height="(\d+)"/)[1]);assert.match(svg,/9223372036854775807/);assert.match([...svg.matchAll(/<text[^>]*>(.*?)<\/text>/g)].map(m=>m[1]).join(' '),/moderation Hotseat/);assert.doesNotMatch(svg,/W{33}/);for(const match of svg.matchAll(/<text([^>]+)>/g)){assert.match(match[1],/text-anchor="middle"/);assert.ok(Number(match[1].match(/y="([\d.]+)"/)[1])<height-12);}assert.match(svg,/portrait-crime-r/);});
