import test from 'node:test';
import assert from 'node:assert/strict';
import {resolve} from 'node:path';
import {pathToFileURL} from 'node:url';
const build=process.env.FAMILY_TEST_BUILD??'dist';
const {renderFamily,familyDescription,familyTitle}=await import(pathToFileURL(resolve(build,'packages/features-family/src/render.js')));
const {PrismaFamilyRepository}=await import(pathToFileURL(resolve(build,'packages/features-family/src/prisma-repository.js')));
const {DiscordFamilyCoordinator}=await import(pathToFileURL(resolve(build,'apps/bot/src/discord/family-coordinator.js')));
const base={id:'f',guildId:'g',channelId:'bots',messageId:'message',ownerId:'a',state:'CLOSED',createdAt:new Date('2026-09-25T12:00:00Z'),expiresAt:null};
const readDb=tx=>({$transaction:async(fn,options)=>{assert.deepEqual(options,{isolationLevel:'RepeatableRead'});return fn(tx);}});
const config={get:async()=>true},coordinator=new DiscordFamilyCoordinator({},config,async()=>true);
test('family proposal projection reads typed inventory quantity and final reservation outcomes',async()=>{for(const state of ['RESERVED','SETTLED','REFUNDED']){const escrow={guildId:'g',kind:'ITEM',ownerUserId:'a',itemRef:'family.ring',itemQuantity:2,amount:null,walletAmount:0n,bankAmount:0n,state};let query;const db={gameSession:{findUnique:async()=>({...base,type:'family_marriage',data:{kind:'marriage'},votes:[]})},escrow:{findMany:async q=>{query=q;return[escrow];}}};const v=await new PrismaFamilyRepository(readDb(db),'s'.repeat(32),async()=>true).publicView('f');assert.deepEqual(v.data.itemEscrow,[{itemId:'family.ring',quantity:2,state}]);assert.deepEqual(query.where,{guildId:'g',referenceType:'family_proposal',referenceId:'f'});assert.match(familyDescription(v),state==='RESERVED'?/2 × Ring: reserved/:state==='SETTLED'?/2 × Ring: consumed/:/2 × Ring: returned/);}});
test('ambiguous monetary proposal escrow fails its member-facing projection',async()=>{const db={gameSession:{findUnique:async()=>({...base,type:'family_marriage',data:{kind:'marriage'},votes:[]})},escrow:{findMany:async()=>[{kind:'OTTOMANS',amount:1n,itemQuantity:null}]}};await assert.rejects(new PrismaFamilyRepository(readDb(db),'s'.repeat(32),async()=>true).publicView('f'),{code:'ESCROW_ASSET_CONTRACT'});});
test('pending and canceled estate surfaces never claim final execution or transferred assets',()=>{for(const state of ['OPEN','CANCELLED']){const v={...base,state,type:'family_estate',data:{kind:'estate',result:state==='OPEN'?'Estate grace period':'Estate canceled after return'}};assert.notEqual(familyTitle(v),'An Estate, Settled');assert.doesNotMatch(familyDescription(v),/Execution is final|transferred|No eligible heir/);assert.match(familyDescription(v),/not executed|No estate transfer has been executed/);}});
test('completed heirless estate explicitly distinguishes removed funds from inherited funds',()=>{const v={...base,type:'family_estate',data:{kind:'estate',executed:true,amount:'12345678901234567890',assetsTransferred:0,result:'Estate funds removed; eligible items auctioned.'}};assert.match(familyDescription(v),/12,345,678,901,234,567,890 Ottomans removed from circulation/);assert.match(familyDescription(v),/0 eligible inventory entries assigned to estate auctions/);});
test('declined or expired adoption has no success claim or actionable controls',async()=>{const v={...base,state:'CANCELLED',type:'family_adoption',data:{kind:'adoption',result:'Adoption declined'}};assert.match(familyDescription(v),/No adoption link was created/);assert.doesNotMatch(familyDescription(v),/tree has been updated/);assert.deepEqual((await coordinator.payload(v)).components.flatMap(r=>r.toJSON().components).map(b=>b.label),['View Family']);});
test('pending and closed proposals retain their real enabled/disabled controls',async()=>{const v={...base,state:'DRAFT',type:'family_marriage',data:{kind:'marriage',proposalItem:'family.ring',result:'Proposal pending',itemEscrow:[{itemId:'family.ring',quantity:1,state:'RESERVED'}]}};const pending=await coordinator.payload(v);assert.deepEqual(pending.components.flatMap(r=>r.toJSON().components).map(b=>b.label),['Accept','Decline','View Family']);const canceled=await coordinator.payload({...v,state:'CANCELLED',data:{...v.data,result:'Proposal expired',itemEscrow:[{itemId:'family.ring',quantity:1,state:'REFUNDED'}]}});assert.deepEqual(canceled.components.flatMap(r=>r.toJSON().components).map(b=>b.label),['View Family']);assert.equal(canceled.embeds[0].toJSON().description,undefined);});
test('dense marriage state keeps the full financial details and first-child bonus without vertical clipping',()=>{const v={...base,type:'family_marriage',data:{kind:'marriage',members:[{userId:'a',name:'W'.repeat(32),avatar:''},{userId:'b',name:'Long Member Name With Many Words',avatar:''}],proposalItem:'family.ring',compatibility:88,success:83,marriedAt:base.createdAt.toISOString(),blessingConsumed:true,spouseCounts:{a:2,b:1},voteResult:{up:99,down:1,total:100,approval:99},firstChildBonus:true,itemEscrow:[{itemId:'family.ring',quantity:1,state:'SETTLED'},{itemId:'family.blessing',quantity:1,state:'SETTLED'}],result:'Married'}};const svg=renderFamily(v);assert.match(svg,/First child slot/);assert.doesNotMatch(svg,/Full event details/);const height=Number(svg.match(/height="(\d+)"/)[1]);assert.ok(height>810);for(const match of svg.matchAll(/<text[^>]* y="(\d+)"/g))assert.ok(Number(match[1])<height-12);assert.match(familyDescription(v),new RegExp('W'.repeat(32)));});
test('auction final projection includes the persisted winning member without exposing sealed bids',async()=>{let requested=false;const winner={userId:'winner',name:'The Winning Chair',avatar:''};const db={gameSession:{findUnique:async()=>({...base,type:'family_auction',data:{kind:'auction',winnerId:'winner',amount:'125',members:[{userId:'seller',name:'Seller',avatar:''}]},votes:[]})},gameParticipant:{findUnique:async q=>{assert.deepEqual(q.where,{sessionId_userId:{sessionId:'f',userId:'winner'}});requested=true;return{data:winner};}}};const view=await new PrismaFamilyRepository(readDb(db),'s'.repeat(32),async()=>true).publicView('f');assert.equal(requested,true);assert.deepEqual(view.data.members[1],winner);assert.equal('bids' in view.data,false);assert.match(familyDescription(view),/Winning member: The Winning Chair/);});
test('family tree paginates complete relationships without a text attachment',async()=>{const ids=Array.from({length:20},(_,i)=>'member-'+i),tree={members:ids,marriages:ids.slice(1).map((id,i)=>({id:'pair'+i,userA:ids[i],userB:id})),adoptions:[],record:null},c=new DiscordFamilyCoordinator({tree:async()=>tree},config,async()=>true),guild={id:'g',members:{fetch:async id=>({displayName:id})}};for(let page=0;page<19;page++){const p=await c.treePayload(guild,ids[0],ids[0],page);assert.equal(p.files.length,1);assert.equal(p.files[0].name,'family-tree.png');assert.equal(p.content,'');assert.equal(p.embeds[0].toJSON().footer,undefined);assert.ok(p.files[0].description.includes(ids[page+1]));}});
test('Family delivery replay and uncertain-send recovery never resend a member announcement',async()=>{for(const state of ['SENT','SENDING'])for(const recovered of [true,false]){let sends=0,linked,completed;const delivery={read:async()=>({state,...(state==='SENT'?{messageId:'original'}:{})}),claim:async()=>{throw Error('Must not claim replay');},complete:async id=>{completed=id;}},repo={publication:async()=>({guildId:'g',channelId:'bots',sessionId:'f'}),delivery:()=>delivery,linkMessage:async(g,id,message)=>{linked=message;}},message={id:'original',author:{id:'bot'},embeds:[{footer:{text:'family:f'}}]},channel={isSendable:()=>true,messages:{fetch:async()=>({find:predicate=>recovered&&predicate(message)?message:undefined})},send:async()=>{sends++;return{id:'duplicate'};}},client={user:{id:'bot'},channels:{fetch:async()=>channel}},c=new DiscordFamilyCoordinator(repo,config,async()=>true);if(state==='SENDING'&&!recovered)await assert.rejects(c.publish(client,'job'),{code:'DELIVERY_UNCERTAIN'});else{await c.publish(client,'job');assert.equal(linked,'original');}assert.equal(sends,0);if(state==='SENDING'&&recovered)assert.equal(completed,'original');}});


test('short family result uses a compact centered window without fixed empty space',()=>{const v={...base,type:'family_ended',data:{kind:'ended',result:'A member became independent.'}},svg=renderFamily(v),height=Number(svg.match(/height="(\d+)"/)[1]);assert.ok(height<400);for(const match of svg.matchAll(/<text([^>]+)>/g))assert.match(match[1],/text-anchor="middle"/);});
test('Family runtime portrait refresh adds the public heir without changing persisted projection',async()=>{const v={...base,type:'family_estate',data:{kind:'estate',heirId:'heir',amount:'25',executed:true}},saved=structuredClone(v),seen=[];const member={displayName:'Current Heir',displayAvatarURL:()=>'',user:{}},client={guilds:{fetch:async id=>({members:{fetch:async q=>{seen.push([id,q.user,q.force]);return member;}}})}};const payload=await coordinator.payload(v,client);assert.deepEqual(v,saved);assert.deepEqual(seen,[['g','heir',true]]);assert.ok(payload.files[0].attachment.length>0);});
