import test from 'node:test';
import assert from 'node:assert/strict';
import {renderCasinoResult} from '../../dist/packages/features-casino/src/render.js';
import {renderSpotlight,renderRecords} from '../../dist/packages/features-profiles/src/render.js';
const avatar='data:image/png;base64,iVBORw0KGgo=';
test('settled award renderer escapes identity and preserves exact large payout',()=>{const input={title:'Chair Pot Jackpot',subtitle:'Settled',memberName:'<Alex & Sam>',amount:'9007199254740993',amountLabel:'Won',details:[{label:'Settlement',value:'Paid & recorded'}]};const svg=renderCasinoResult(input);assert.ok(svg.includes('9007199254740993</text>'));assert.ok(svg.includes('>Ottomans</text>'));assert.match(svg,/&lt;Alex &amp; Sam&gt;/);assert.match(svg,/Cinzel/);assert.equal(svg,renderCasinoResult(input));});
test('Spotlight retains co-winners, empty categories, permanent honor and exact totals',()=>{const winner={name:'Jordan',avatarData:avatar,total:'2048',lifetimeWins:4,status:'Returning winner',tripleThreat:true};const svg=renderSpotlight({weekStart:'2026-09-14',weekEnd:'2026-09-21',activeMembers:42,messages:1234,words:9876,voiceSeconds:7654,categories:[{title:'The Loudest Chair',winners:[winner,{...winner,name:'Alex',tripleThreat:false}]},{title:'Voice of the Lounge',winners:[]}]});assert.match(svg,/width="440"/);assert.match(svg,/Jordan/);assert.match(svg,/Alex/);assert.equal((svg.match(/TRIPLE THREAT/g)||[]).length,1);assert.match(svg,/No qualifying winner/);assert.match(svg,/7654 qualifying voice seconds/);assert.doesNotMatch(svg,/Poppins|Cinzel/);const fallback=renderSpotlight({categories:[{title:'Test',winners:[{...winner,avatarData:'https://invalid.test/a.png'}]}]});assert.doesNotMatch(fallback,/href="https:/);assert.match(fallback,/>JO<\/text>/);});
test('records render actual holder/value and a truthful empty state',()=>{const svg=renderRecords({scope:'All time',records:[{title:'Biggest Win',memberName:'Alex <chair>',amount:'123456',achievedAt:'Sep 25, 2026'}]});assert.match(svg,/Alex &lt;chair&gt;/);assert.match(svg,/123456/);assert.match(svg,/Sep 25, 2026/);assert.match(renderRecords({scope:'All time',records:[]}),/No records yet/);});
import {DiscordCasinoCoordinator} from '../../dist/apps/bot/src/discord/casino-coordinator.js';
test('settled runtime payload attaches saved-result card and retains replay and rules without visible markers',async()=>{const values={'casino.min_bet':1,'casino.max_bet':10000,'casino.chair_pot_contribution_percent':1,'casino.chair_symbols':[],'casino.slots_wagers':[10],'casino.roulette_choices':['red'],'casino.dice_choices':['high']};const repo={get:async()=>({guildId:'g',ownerUserId:'member',state:'CLOSED',version:1,data:{game:'roulette',stake:'1000',selection:'number:17',symbols:['17'],payout:'36000',outcome:'WIN'}})};const result=await new DiscordCasinoCoordinator(repo,{}, {get:async(_g,key)=>values[key]},async()=>true).roundPayload('saved-round');assert.deepEqual(result.embeds,[]);assert.ok(result.components.some(c=>c.toJSON().type===12));assert.equal(result.files[0].attachment.subarray(1,4).toString(),'PNG');assert.deepEqual(result.components.at(-1).components.map(c=>c.data.label),['Play Again','Rules']);assert.doesNotMatch(JSON.stringify(result.components.slice(0,-1)),/casino:saved-round/);});

test('long names and maximum BIGINT payouts remain complete at readable font sizes',()=>{const name='W'.repeat(32),amount='9223372036854775807';const svg=renderCasinoResult({title:'Chair Pot Jackpot',subtitle:'Settled',memberName:name,amount,amountLabel:'Won',details:[]});assert.match(svg,new RegExp('font-size="35"[^>]*>'+amount));assert.doesNotMatch(svg,new RegExp('>'+name+'<'));const record=renderRecords({scope:'All time',records:[{title:'Biggest Casino Win',memberName:name,amount,achievedAt:'Sep 25, 2026'}]});assert.doesNotMatch(record,new RegExp('>'+name+'<'));assert.match(record,new RegExp(amount));});
