
const textOf=p=>p.content??p.components?.map(c=>c.toJSON?.()??c).filter(c=>c.type===10).map(c=>c.content).join('\n')??'';
const rowsOf=p=>p.components.filter(c=>c.toJSON().type===1);
import test from 'node:test';
import assert from 'node:assert/strict';
import {Collection,PermissionFlagsBits} from 'discord.js';
import {DiscordIntroductionsCoordinator,introductionDeliveryUrl,introductionDeliveryKey} from '../../dist/apps/bot/src/discord/introductions-coordinator.js';
import {renderIntroduction} from '../../dist/packages/features-introductions/src/render.js';
const g='111111111111111111',u='222222222222222222',ch='333333333333333333',message='444444444444444444',bot='555555555555555555';
function interaction(overrides={}){const replies=[];return{replies,guildId:g,guild:{members:{fetch:async()=>({user:{bot:false},isCommunicationDisabled:()=>false,permissionsIn:()=>({has:flag=>flag===PermissionFlagsBits.ViewChannel})})}},channelId:ch,user:{id:u},id:'request',deferred:false,replied:false,isButton:()=>false,isChatInputCommand:()=>true,isModalSubmit:()=>false,commandName:'introduce',deferUpdate:async function(){this.deferred=true;this.updated=true;},deferReply:async function(){this.deferred=true;},editReply:async function(p){replies.push(p);this.replied=true;},reply:async p=>replies.push(p),followUp:async p=>replies.push(p),...overrides};}
const settings={get:async(g,key)=>key==='features.introductions'?true:key==='channels.introduction_channel'?ch:null};
const form={id:'f',title:'Your introduction',version:1,prompts:[{id:'name',sortOrder:0,label:'What should we call you?',cardLabel:'Name',placeholder:null,required:true,minLength:null,maxLength:80,inputStyle:'short',enabled:true,showOnCard:true,deletedAt:null}]};
const draft={form,config:{guildId:g,introductionChannelId:ch,panelMessageId:'panel',headerText:'PULL UP A CHAIR',footerText:'Welcome',showAvatar:false,showDisplayName:true,showJoinDate:false,allowAdminIntroConfig:false,version:1},answers:{name:'Member'},page:0,baseRevision:0,previewedVersion:0};
function repo(){return{configure:async()=>{},configuration:async()=>({form,config:draft.config}),start:async()=>({id:'draft'}),view:async()=>({id:'draft',version:0,data:draft}),submission:async()=>null};}
test('Disabled introductions do not touch persisted drafts or Discord membership',async()=>{let calls=0;const boundary=new Proxy({}, {get:()=>async()=>{calls++;}}),i=interaction();await new DiscordIntroductionsCoordinator(boundary,{get:async()=>false},async()=>true,async()=>false).handle(i);assert.equal(calls,0);assert.match(textOf(i.replies[0]),/not enabled/);});
test('Wrong-channel introductions return a private jump link without creating a draft',async()=>{const r=repo();let starts=0;r.start=async()=>{starts++;};const i=interaction({channelId:'666666666666666666'});await new DiscordIntroductionsCoordinator(r,settings,async()=>true,async()=>false).handle(i);assert.equal(starts,0);assert.match(textOf(i.replies[0]),new RegExp(`discord.com/channels/${g}/${ch}`));assert.equal(i.deferred,true);});
test('Bare introduce opens private Create/Preview controls without publishing and does not require SendMessages',async()=>{const i=interaction();await new DiscordIntroductionsCoordinator(repo(),settings,async()=>true,async()=>false).handle(i);assert.equal(i.deferred,true);assert.match(textOf(i.replies[0]),/Private form/);const controls=rowsOf(i.replies[0])[0].components.map(b=>b.data.label);assert.deepEqual(controls,['Create Introduction','Edit My Introduction','Preview']);assert.deepEqual(i.replies[0].allowedMentions,{parse:[]});});
test('Introduction modal pre-fills saved fields and retains page/version in its control',async()=>{let modal;const i=interaction({isChatInputCommand:()=>false,isButton:()=>true,customId:'intro:page:draft:0:0',showModal:async m=>{modal=m;}});await new DiscordIntroductionsCoordinator(repo(),settings,async()=>true,async()=>false).handle(i);assert.equal(modal.data.custom_id,'intro:save:draft:0:0');assert.equal(modal.components[0].components[0].data.value,'Member');assert.equal(i.replies.length,0);});
test('Unauthorized intro-config never exports configuration',async()=>{const i=interaction({commandName:'intro-config'});await new DiscordIntroductionsCoordinator(repo(),settings,async()=>true,async()=>false).handle(i);assert.match(textOf(i.replies[0]),/authorized admin/);assert.ok(!i.replies[0].files.some(f=>f.name==='introduction-configuration.json'));});
test('A failed publication never claims that an introduction was published',async()=>{const r=repo();r.enqueue=async()=>{throw Error('Database unavailable');};const i=interaction({isChatInputCommand:()=>false,isButton:()=>true,customId:'intro:publish:draft:0:0'});await new DiscordIntroductionsCoordinator(r,settings,async()=>true,async()=>false).handle(i);assert.ok(i.replies.every(p=>!textOf(p).startsWith('Your introduction is published:')));});
function publicationFixture({prior=message,fetchError,sendError,editError,recover=false}={}){let state='PENDING',confirmed,sends=0,edits=0,finalizations=0;const existing={id:message,author:{id:bot},embeds:[],edit:async()=>{edits++;if(recover)existing.embeds=[{url:introductionDeliveryUrl('intro:job')}];if(editError)throw editError;existing.embeds=[{url:introductionDeliveryUrl('intro:job')}];}},channel={isSendable:()=>true,messages:{fetch:async query=>{if(typeof query==='object')return new Collection();if(fetchError)throw fetchError;return existing;}},send:async()=>{sends++;if(sendError)throw sendError;return{id:message};}},client={user:{id:bot},guilds:{fetch:async()=>({members:{fetch:async()=>({isCommunicationDisabled:()=>false,permissionsIn:()=>({has:()=>true})})}})},channels:{fetch:async()=>channel}},r={job:async()=>({guildId:g,payload:{userId:u,sessionId:'draft',channelId:ch,revision:2,draft,priorMessageId:prior,priorChannelId:prior?ch:null,deliveryState:state}}),delivery:()=>({read:async()=>({state,...(confirmed?{messageId:confirmed}:{})}),claim:async()=>{if(state!=='PENDING')return false;state='SENDING';return true;},complete:async id=>{confirmed=id;state='SENT';}}),finalize:async()=>{assert.equal(state,'SENT');finalizations++;return{messageId:confirmed,channelId:ch};}};const coordinator=new DiscordIntroductionsCoordinator(r,settings,async()=>true,async()=>false);coordinator.sweep=async()=>{};coordinator.cardPayload=async()=>({embeds:[],files:[],allowedMentions:{parse:[]}});return{coordinator,client,counters:()=>({state,sends,edits,finalizations})};}
test('Introduction edit updates the saved bot message rather than creating a duplicate',async()=>{const f=publicationFixture();await f.coordinator.publish(f.client,'job');assert.deepEqual(f.counters(),{state:'SENT',sends:0,edits:1,finalizations:1});});
test('Only a definite Unknown Message response authorizes an introduction replacement',async()=>{const missing=publicationFixture({fetchError:{code:10008}});await missing.coordinator.publish(missing.client,'job');assert.equal(missing.counters().sends,1);const unavailable=publicationFixture({fetchError:{code:50013}});await assert.rejects(unavailable.coordinator.publish(unavailable.client,'job'));assert.equal(unavailable.counters().sends,0);assert.equal(unavailable.counters().finalizations,0);});
test('An uncertain introduction edit remains unconfirmed and a retry cannot send a replacement',async()=>{const f=publicationFixture({editError:Error('Discord response lost')});await assert.rejects(f.coordinator.publish(f.client,'job'));await assert.rejects(f.coordinator.publish(f.client,'job'),{code:'DELIVERY_UNCERTAIN'});assert.deepEqual(f.counters(),{state:'SENDING',sends:0,edits:1,finalizations:0});});
test('Introduction renderer inherits the approved theme, escapes answers and uses deterministic portraits',()=>{const svg=renderIntroduction('Name\n<script> @everyone','Member',undefined,true,0,1);assert.match(svg,/Cinzel/);assert.match(svg,/font-family="Poppins"/);assert.match(svg,/width="1200"/);assert.match(svg,/portrait-intro/);assert.match(svg,/&lt;script&gt;/);assert.doesNotMatch(svg,/<script>/);});

test('Publish confirmation reuses the private window and has no large image',async()=>{const r=repo();r.enqueue=async()=>({jobId:'job'});r.submission=async()=>({outputChannelId:ch,outputMessageId:message});const c=new DiscordIntroductionsCoordinator(r,settings,async()=>true,async()=>false);c.publish=async()=>{};const i=interaction({isChatInputCommand:()=>false,isButton:()=>true,customId:'intro:publish:draft:0:0'});await c.handle(i);assert.equal(i.updated,true);assert.equal(i.replies.length,1);assert.deepEqual(i.replies[0].files,[]);assert.deepEqual(i.replies[0].embeds,[]);});
test('Introduction payload omits visible internal IDs and blank rows',async()=>{const r=repo(),c=new DiscordIntroductionsCoordinator(r,settings,async()=>true,async()=>false),client={guilds:{fetch:async()=>({members:{fetch:async()=>({displayName:'Member'})}})}};const payload=await c.cardPayload(client,g,u,draft,'intro-preview:private-record');assert.deepEqual(payload.embeds,[]);assert.ok(payload.files[0].name.startsWith(introductionDeliveryKey('intro-preview:private-record')+'-'));assert.doesNotMatch(JSON.stringify(payload.components.map(c=>c.toJSON())),/intro-preview|private-record/);});
test('Command acknowledgement happens before configuration reads',async()=>{const i=interaction(),config={get:async(_g,key)=>{assert.equal(i.deferred,true);return settings.get(_g,key);}};await new DiscordIntroductionsCoordinator(repo(),config,async()=>true,async()=>false).handle(i);assert.equal(i.replies.length,1);});

test('Lost response recovers a matching hidden delivery URL without another edit or post',async()=>{const f=publicationFixture({editError:Error('Response lost'),recover:true});await assert.rejects(f.coordinator.publish(f.client,'job'));await f.coordinator.publish(f.client,'job');assert.deepEqual(f.counters(),{state:'SENT',sends:0,edits:1,finalizations:1});});

test('changed private hub artwork gets a new hashed attachment while retaining the same window',async()=>{const r=repo(),c=new DiscordIntroductionsCoordinator(r,settings,async()=>true,async()=>false),first=interaction();await c.handle(first);const before=first.replies[0].files.map(f=>f.name);r.submission=async()=>({outputMessageId:message});const later=interaction({isChatInputCommand:()=>false,isButton:()=>true,customId:'intro:back:draft:0:0',message:{attachments:new Collection(before.map((name,n)=>[String(n),{id:String(n),name}]))}});await c.handle(later);assert.equal(later.updated,true);assert.ok(later.replies[0].files.length);assert.ok(later.replies[0].files.every(f=>!before.includes(f.name)));});

test('confirmed publication immediately requests panel reconciliation',async()=>{const f=publicationFixture({prior:null});let sweeps=0;f.coordinator.sweep=async()=>{sweeps++;assert.equal(f.counters().finalizations,1);};await f.coordinator.publish(f.client,'job');assert.equal(sweeps,1);});
