import test from 'node:test';
import assert from 'node:assert/strict';
import {DiscordItemsCoordinator} from '../../dist/apps/bot/src/discord/items-coordinator.js';
import {collectionCards,craftingCards,inventoryCard,itemPage} from '../../dist/apps/bot/src/discord/item-view-models.js';
const config={get:async(_g,k)=>k==='features.items'?true:k==='channels.bot_channel'?'bot':k==='shop.personalized_bonus_slots'?2:k.includes('floor')?35:k.includes('ceiling')?70:k.includes('percent')?50:k.endsWith('_min')?10:k.endsWith('_max')?30:25};
function state(){const catalog=Array.from({length:9},(_,n)=>({id:'item'+n,name:'Item '+n,type:n===0?'tool':'material',rarity:'Rare',buyPrice:100n,enabled:true,giftable:true,metadata:{essential:true}}));return{guildId:'g',catalog,recipes:[],collections:[],members:[{userId:'member',wallet:2000n,bank:0n,stacks:catalog.slice(1).map((x,n)=>({id:'stack'+n,userId:'member',itemId:x.id,quantity:n+1,locked:false,acquiredAt:new Date(0)})),tools:[{id:'tool',catalogItemId:'item0',slot:'workshop_tool',equipped:true,durability:40,maxDurability:100,locked:false}],chairs:[],recipes:[],discoveries:[],categoryLocks:[],progress:{rank:'Apprentice',skillPoints:4,attempts:1,successes:0},achievements:[]}]};}
function interaction(commandName='inventory',customId,values=[]){const calls=[];return{calls,id:'r',guildId:'g',guild:{members:{fetch:async()=>({user:{bot:false}})}},channelId:'bot',user:{id:'member'},commandName,customId,values,deferred:false,replied:false,isChatInputCommand:()=>!customId,isButton:()=>!!customId&&!values.length,isStringSelectMenu:()=>values.length>0,isModalSubmit:()=>false,deferReply:async function(){this.deferred=true;},editReply:async p=>calls.push(p),reply:async p=>calls.push(p),followUp:async p=>calls.push(p)};}
const repo=s=>({read:async()=>structuredClone(s),transact:async()=>{throw new Error('Presentation must not mutate');}});
const menus=i=>i.calls[0].components.map(x=>x.toJSON()).flatMap(x=>x.components).filter(x=>x.options);
test('inventory categories reflect owned types and selection filters inspect choices',async()=>{const s=state(),c=new DiscordItemsCoordinator(repo(s),config,async()=>true),i=interaction();await c.handle(i);assert.deepEqual(menus(i)[0].options.map(x=>x.value),['all','material','tool']);assert.equal(menus(i)[1].options.length,4);const filtered=interaction('', 'items:browsecategory:member',['tool']);await c.handle(filtered);assert.deepEqual(menus(filtered)[1].options.map(x=>x.value),['tool']);assert.match(filtered.calls[0].files[0].description,/Equipped.*40\/100/);assert.match(filtered.calls[0].files[0].description,/ID: tool/);});
test('empty inventory has only All and no fabricated categories or inspect options',async()=>{const s=state();s.members[0].stacks=[];s.members[0].tools=[];const i=interaction();await new DiscordItemsCoordinator(repo(s),config,async()=>true).handle(i);assert.deepEqual(menus(i)[0].options.map(x=>x.value),['all']);assert.equal(menus(i).length,1);});
test('shop pagination exposes exactly the products represented on each four-card page',async()=>{const c=new DiscordItemsCoordinator(repo(state()),config,async()=>true),first=interaction('shop'),next=interaction('','items:shoppage:member:1'),last=interaction('','items:shoppage:member:2');await c.handle(first);await c.handle(next);await c.handle(last);assert.deepEqual(menus(first)[0].options.map(x=>x.value),['item0','item1','item2','item3']);assert.deepEqual(menus(next)[0].options.map(x=>x.value),['item4','item5','item6','item7']);assert.deepEqual(menus(last)[0].options.map(x=>x.value),['item8']);assert.ok(next.calls[0].files[0].attachment.length>0);});
test('shop cards expire after one minute without changing the shop response',async()=>{const i=interaction('shop'),timers=[];let deleted=0;i.deleteReply=async()=>{deleted++;};const c=new DiscordItemsCoordinator(repo(state()),config,async()=>true,(work,delayMs)=>{timers.push({work,delayMs});});await c.handle(i);assert.equal(timers.length,1);assert.equal(timers[0].delayMs,60_000);await timers[0].work();assert.equal(deleted,1);assert.ok(i.calls[0].files[0].attachment.length>0);});
test('hidden collection names stay hidden until discovered while ordinary pieces show progress',()=>{const s=state();s.collections=[{id:'a',name:'Five Seats',hidden:false,itemIds:['item1','item2']},{id:'b',name:'Secret',hidden:true,itemIds:['item3','item4']}];s.members[0].discoveries=['item1'];assert.deepEqual(collectionCards(s,'member').map(x=>[x.name,x.badge]),[['Item 1','Discovered'],['Item 2','Undiscovered']]);s.members[0].discoveries.push('item3');assert.equal(collectionCards(s,'member').at(-1).name,'Undiscovered piece');});
test('craft cards use learned enabled recipes and owned versus required counts without mutations',()=>{const s=state();s.recipes=[{id:'r',name:'Chair',enabled:true,inputs:{item1:4},outputItemId:'item2'},{id:'secret',name:'Unknown',enabled:true,inputs:{},outputItemId:'item3'}];s.members[0].recipes=['r'];const before=structuredClone(s),cards=craftingCards(s,'member');assert.equal(cards.length,1);assert.match(cards[0].card.detail,/Item 1: 1\/4/);assert.deepEqual(s,before);assert.equal(itemPage(Array.from({length:17}),99).items.length,1);});
test('async view rejection is handled privately rather than escaping the interaction handler',async()=>{const i=interaction('shop');await new DiscordItemsCoordinator({read:async()=>{throw new Error('broken read');}},config,async()=>true).handle(i);assert.equal(i.calls.length,1);assert.match(i.calls[0].content,/failed/);});
