import test from 'node:test';import assert from 'node:assert/strict';import {EventEmitter} from 'node:events';
import {LavalinkConnection} from '../../dist/apps/bot/src/music/lavalink-connection.js';
class Socket extends EventEmitter{closed=false;terminated=false;close(){this.closed=true;this.emit('close');}terminate(){this.terminated=true;this.emit('close');}}
const tick=()=>new Promise(resolve=>setImmediate(resolve));
function fixture(overrides={}){const socket=new Socket(),events=[],failures=[],requests=[],factory=[];const options={endpoint:'https://node.example',password:'fixture-private-password',botId:'111111111111111111',fetch:async(url,init)=>{requests.push({url,init});return Response.json({resuming:false,timeout:60});},resolveCatalogSource:async()=>({uri:'https://audio.example/owned.mp3'}),isCurrent:async()=>true,socketFactory:(url,headers)=>{factory.push({url,headers});return socket;},onEvent:async(e,c)=>events.push({e,c}),onUnavailable:code=>failures.push(code),handshakeTimeoutMs:1000,...overrides};return{socket,events,failures,requests,factory,connection:new LavalinkConnection(options)};}
const ready=socket=>socket.emit('message',JSON.stringify({op:'ready',sessionId:'private-session',resumed:false}));
test('connection sends private headers only to the validated node and awaits session setup',async()=>{const f=fixture(),started=f.connection.start();assert.equal(f.connection.ready,false);ready(f.socket);await started;assert.equal(f.connection.ready,true);assert.equal(f.factory[0].url,'wss://node.example/v4/websocket');assert.equal(f.factory[0].headers.Authorization,'fixture-private-password');assert.ok(!JSON.stringify(f.connection).includes('private'));assert.deepEqual(JSON.parse(f.requests[0].init.body),{resuming:false,timeout:60});f.connection.close();assert.equal(f.socket.closed,true);assert.equal(f.connection.ready,false);assert.deepEqual(f.failures,[]);});
test('operator URL is validated before a socket can disclose authentication',()=>{let called=false;assert.throws(()=>fixture({endpoint:'https://member:secret@untrusted.example',socketFactory:()=>{called=true;return new Socket();}}));assert.equal(called,false);});
test('events are ordered and expose neither raw provider messages nor the ready session ID',async()=>{const f=fixture(),started=f.connection.start();ready(f.socket);await started;for(const generation of [1,2])f.socket.emit('message',JSON.stringify({op:'event',type:'TrackStartEvent',guildId:'222222222222222222',track:{encoded:'private-audio-encoding',userData:{ajMusic:{entryId:'track',generation}}},secret:'hidden'}));await f.connection.drain();assert.deepEqual(f.events.map(r=>r.e.generation),[1,2]);assert.ok(f.events[0].c.sequence<f.events[1].c.sequence);const text=JSON.stringify(f.events);assert.ok(!text.includes('private-audio'));assert.ok(!text.includes('private-session'));assert.ok(!text.includes('hidden'));f.connection.close();});
test('duplicate ready frames fail closed even while first session setup is awaiting a response',async()=>{let finish;const f=fixture({fetch:()=>new Promise(resolve=>{finish=resolve;})}),started=f.connection.start();ready(f.socket);await tick();ready(f.socket);await assert.rejects(started,{code:'LAVALINK_UNEXPECTED_SESSION'});finish(Response.json({resuming:false,timeout:60}));await f.connection.drain();assert.equal(f.connection.ready,false);assert.equal(f.socket.terminated,true);});
test('pre-ready timeout and socket failures return fixed diagnostics without raw error details',async()=>{const f=fixture({handshakeTimeoutMs:10});await assert.rejects(f.connection.start(),{code:'LAVALINK_READY_TIMEOUT'});assert.deepEqual(f.failures,['LAVALINK_READY_TIMEOUT']);const g=fixture(),started=g.connection.start();g.socket.emit('error',new Error('private URI should not escape'));await assert.rejects(started,error=>!error.message.includes('private URI'));assert.deepEqual(g.failures,['LAVALINK_CONNECTION']);});
test('explicit close cancels pending handshake and no reconnect occurs automatically',async()=>{const f=fixture(),started=f.connection.start();f.connection.close();await assert.rejects(started,{code:'LAVALINK_CLOSED'});assert.equal(f.factory.length,1);assert.throws(()=>f.connection.start());assert.deepEqual(f.failures,[]);});
test('failed event persistence stops further events without disclosing callback errors',async()=>{let calls=0;const f=fixture({onEvent:async()=>{calls++;throw Error('secret callback content');}}),started=f.connection.start();ready(f.socket);await started;const msg=JSON.stringify({op:'event',type:'TrackStartEvent',guildId:'222222222222222222',track:{userData:{ajMusic:{entryId:'track',generation:1}}}});f.socket.emit('message',msg);f.socket.emit('message',msg);await f.connection.drain();assert.equal(calls,1);assert.equal(f.connection.ready,false);assert.deepEqual(f.failures,['LAVALINK_EVENT_HANDLING']);});
