import test from 'node:test';import assert from 'node:assert/strict';
import {COMMANDS} from '../../dist/packages/contracts/src/generated/commands.js';
import {hasAuthoredLesson,lessonCopy} from '../../dist/packages/features-learning/src/tutorial-content.js';
import {learningWindow} from '../../dist/packages/features-learning/src/visual.js';
test('every selectable lesson has authored teaching content, including roles',()=>{const selected=COMMANDS.filter(hasAuthoredLesson);assert.ok(selected.find(c=>c.id==='roles'));for(const c of selected){const copy=lessonCopy(c);assert.doesNotMatch(copy.purpose,/not been authored|placeholder|Quick reference for/);assert.ok(copy.steps.length);assert.ok(copy.example.startsWith(c.registered));}assert.equal(hasAuthoredLesson({id:'unwritten',registered:'/unwritten',options:[]}),false);});
test('learning art is wide, readable and escapes member-facing prose',()=>{const svg=learningWindow('Help','PURPOSE\nRead <safe> & clear.');assert.match(svg,/width="1200"/);assert.match(svg,/Poppins/);assert.match(svg,/Cinzel/);assert.match(svg,/#592A39/);assert.match(svg,/&lt;safe&gt; &amp;/);});

test('directory uses category columns, lessons use plates, and recap counts own tiles',()=>{assert.match(learningWindow('Your command directory','START\n/rules  ·  /roles\n\nLEARN\n/help'),/data-layout="directory-column"/);assert.match(learningWindow('/roles · Your lesson','PURPOSE\nChoose cosmetic roles.'),/data-section="plate"/);const recap=learningWindow('Chat activity snapshot','CHAT COUNTS · 1h\n42 member messages\n306 words');assert.equal((recap.match(/data-layout="count-tile"/g)||[]).length,2);assert.match(recap,/font-size="76"/);assert.match(recap,/<image href="data:image/);});

test('directory renders actual registry commands joined by coordinator separators into separate rows',()=>{const commands=COMMANDS.filter(c=>c.type==='slash'&&c.module==='tutorial').slice(0,3);assert.ok(commands.length);const copy='TUTORIAL\n'+commands.map(c=>c.registered).join('  ·  ')+'\n\nSearch with /help command. Page 1 of 1',svg=learningWindow('Your command directory',copy);for(const c of commands)assert.ok(svg.includes('>'+c.registered+'</text>'));assert.equal(svg.includes('  ·  '),false);assert.match(svg,/data-layout="directory-column"/);});
