import test from 'node:test';import assert from 'node:assert/strict';
import {COMMANDS} from '../../dist/packages/contracts/src/generated/commands.js';
import {helpDirectoryPages} from '../../dist/apps/bot/src/discord/learning-coordinator.js';
import {learningWindow} from '../../dist/packages/features-learning/src/visual.js';
const commands=COMMANDS.filter(c=>c.type==='slash'||c.registered.startsWith('!'));
test('Help keeps every eligible command exactly once in permission-filterable categories',()=>{const pages=helpDirectoryPages(commands),categories=pages.flat(),listed=categories.flatMap(g=>g.commands).filter(c=>c.id);assert.deepEqual(listed.map(c=>c.id).sort(),commands.map(c=>c.id).sort());assert.ok(categories.some(g=>g.label==='Roles'));assert.ok(categories.some(g=>g.label==='Economy'));assert.ok(categories.some(g=>g.label==='EAJ Music'));assert.ok(categories.some(g=>g.label==='Fight'));assert.ok(categories.some(g=>g.label==='Special Commands'));for(const module of new Set(commands.map(c=>c.module)))assert.equal(categories.filter(group=>group.commands.some(c=>c.module===module)).length,1);});
test('Help grouping preserves filtered input and removes empty topic pages',()=>{const allowed=commands.filter(c=>c.module==='music'&&c.permissions.includes('member'));const pages=helpDirectoryPages(allowed);assert.equal(pages.length,1);assert.deepEqual(pages.flat().flatMap(g=>g.commands).map(c=>c.id).sort(),allowed.map(c=>c.id).sort());assert.deepEqual(helpDirectoryPages([]),[[]]);});
test('Category cards keep compact command text and use a category accent',()=>{const music=helpDirectoryPages(commands).flat().find(g=>g.label==='EAJ Music'),copy=music.commands.map(c=>c.registered+' — '+c.description).join('\n'),svg=learningWindow('Help · EAJ Music',copy);assert.match(svg,/width="1200"/);assert.match(svg,/#B66AE3|#00B8B0|#D3A94D|#6E9FE8/);for(const c of music.commands)assert.ok(svg.includes(c.registered),c.registered);assert.ok(Number(/height="(\d+)"/.exec(svg)[1])<1200);});

test('lesson navigation separates reset actions and exposes paths on completion',async()=>{
 const {DiscordLearningCoordinator}=await import('../../dist/apps/bot/src/discord/learning-coordinator.js');
 const saved=[],config={get:async(_g,key)=>key.startsWith('roles.')?null:true,definition:()=>({})},guild={ownerId:'owner',members:{fetch:async()=>({permissions:{has:()=>false},roles:{cache:new Map()}})}},i={guildId:'server',guild,user:{id:'member'},customId:'learn:tutorial:member:step:roles:3',id:'interaction',calls:[],deferred:false,isChatInputCommand:()=>false,isStringSelectMenu:()=>false,deferUpdate:async function(){this.deferred=true;},editReply:async function(payload){this.calls.push(payload);}};
 await new DiscordLearningCoordinator({tutorialStep:async(...args)=>saved.push(args)},config,async()=>true).handle(i);
 const rows=i.calls[0].components.filter(row=>row.toJSON().type===1).map(row=>row.toJSON().components);assert.deepEqual(rows[0].map(c=>c.label),['Back','Next','Practice','Learning Paths']);assert.deepEqual(rows[1].map(c=>c.label),['Progress','Restart','Exit Tutorial']);assert.equal(rows[0][1].disabled,true);assert.equal(rows[1][1].style,4);assert.equal(saved[0][3],3);assert.doesNotMatch(i.calls[0].files[0].toJSON().description,/undefined/);
});
