import test from 'node:test';
import assert from 'node:assert/strict';
import {DiscordModerationCoordinator} from '../../dist/apps/bot/src/discord/moderation-coordinator.js';
import {ModerationService,InMemoryModerationRepository,PrismaModerationRepository} from '../../dist/packages/features-moderation/src/index.js';
import {AuditService,InMemoryAuditSink} from '../../dist/packages/core/src/index.js';
async function fixture(status='ACTIVE',seconds=60){
 let now=new Date('2026-09-26T12:00:00Z');const repo=new InMemoryModerationRepository(),service=new ModerationService(repo,new AuditService(new InMemoryAuditSink()),{now:()=>new Date(now)});
 const c=await service.prepare({guildId:'g',subjectUserId:'u',actorUserId:'staff',actionType:'BAN',reason:'Test',...(seconds?{durationSeconds:seconds}:{})});await service.finalize(c.id,'ACTIVE');
 await service.scheduleTemporaryCase(c,'u',60,'moderation.temp_ban_expire');
 if(status==='APPEALED'||status==='UPHELD'||status==='MODIFIED'){const a=await service.requestReview(c.id,'u');if(status!=='APPEALED')await service.resolveAppeal({appealId:a.appealId,reviewerUserId:'other',outcome:status,reason:'Reviewed'});}
 if(status==='REVERSED')await service.reverse(c.id,'other','Reverse');
 let unbans=0;const server={bans:{fetch:async()=>({})},members:{unban:async()=>{unbans++;}}},client={guilds:{cache:new Map([['g',server]])}},coordinator=new DiscordModerationCoordinator(service,{});
 return {repo,service,c,server,client,setTime:s=>{now=new Date('2026-09-26T12:00:00Z');now.setSeconds(s);},run:()=>coordinator.handleExpiryJob(client,'moderation.temp_ban_expire',{caseId:c.id,userId:'u'}),get unbans(){return unbans;}};
}
for(const status of ['ACTIVE','APPEALED','UPHELD','MODIFIED'])test(`${status} temporary ban expires once at deadline and retains history`,async()=>{const f=await fixture(status);const history=await f.repo.listCaseEvents(f.c.id);f.setTime(59);await f.run();assert.equal(f.unbans,0);f.setTime(60);await f.run();await f.run();assert.equal(f.unbans,1);assert.equal((await f.service.requireCase(f.c.id)).status,'EXPIRED');const after=await f.repo.listCaseEvents(f.c.id);assert.deepEqual(after.slice(0,history.length),history);assert.equal(after.length,history.length+1);});
for(const seconds of [30,120])test(`MODIFIED expiry uses replacement deadline ${seconds}s`,async()=>{const f=await fixture('MODIFIED');await f.service.modifyCaseFromAppeal(f.c.id,'other','New duration',seconds);await f.service.scheduleTemporaryCase(f.c,'u',seconds,'moderation.temp_ban_expire');f.setTime(seconds===120?60:29);await f.run();assert.equal(f.unbans,0);f.setTime(seconds);await f.run();assert.equal(f.unbans,1);});
for(const state of ['REVERSED','CANCELLED','PERMANENT','MODIFIED_PERMANENT'])test(`${state} cannot auto-unban`,async()=>{const f=await fixture(state==='REVERSED'?state:'ACTIVE',state==='PERMANENT'?0:60);if(state==='CANCELLED')f.repo.expiryJobs.get(f.c.id).status='CANCELLED';if(state==='MODIFIED_PERMANENT')await f.service.modifyCaseFromAppeal(f.c.id,'other','Permanent',null);f.setTime(120);await f.run();assert.equal(f.unbans,0);assert.notEqual((await f.service.requireCase(f.c.id)).status,'EXPIRED');});
test('unavailable guild and API failure remain retryable',async()=>{const f=await fixture();f.setTime(60);f.client.guilds.cache.clear();await assert.rejects(f.run,/available/);f.client.guilds.cache.set('g',f.server);f.server.bans.fetch=async()=>{throw new Error('API unavailable');};await assert.rejects(f.run,/API unavailable/);assert.equal((await f.service.requireCase(f.c.id)).status,'ACTIVE');assert.equal(f.unbans,0);});
test('unknown ban finishes case without duplicate unban',async()=>{const f=await fixture('UPHELD');f.setTime(60);f.server.bans.fetch=async()=>{throw {code:10026};};await f.run();assert.equal(f.unbans,0);assert.equal((await f.service.requireCase(f.c.id)).status,'EXPIRED');});
test('Prisma reschedule revokes stale lease while retaining execution key',async()=>{let args;const repo=new PrismaModerationRepository({scheduledJob:{upsert:async a=>{args=a;}}});await repo.upsertExpiryJob({guildId:'g',caseId:1,jobType:'moderation.temp_ban_expire',dueAt:new Date(),userId:'u'});assert.equal(args.where.executionKey,'moderation.temp_ban_expire:1');assert.equal(args.update.leaseToken,null);assert.equal(args.update.leaseUntil,null);assert.equal(args.update.retryAt,null);assert.equal(args.update.status,'PENDING');});
for(const status of ['ACTIVE','APPEALED','UPHELD','MODIFIED','REVERSED'])test(`Prisma expiry transition ${status}`,async()=>{let updates=0,events=0;const c={id:1,guildId:'g',actionType:'BAN',durationSeconds:60,status,createdAt:new Date(),updatedAt:new Date()};const tx={moderationCase:{findUnique:async()=>c,update:async a=>{updates++;return {...c,...a.data};}},moderationCaseEvent:{create:async()=>{events++;}}};const repo=new PrismaModerationRepository({$transaction:async fn=>fn(tx)});await repo.expireCase({caseId:1,reason:'Expired',now:new Date()});assert.equal(updates,status==='REVERSED'?0:1);assert.equal(events,updates);});
test('reschedule during Discord lookup prevents stale unban',async()=>{const f=await fixture('MODIFIED');f.setTime(60);f.server.bans.fetch=async()=>{await f.service.scheduleTemporaryCase(f.c,'u',120,'moderation.temp_ban_expire');return {};};await f.run();assert.equal(f.unbans,0);assert.equal((await f.service.requireCase(f.c.id)).status,'MODIFIED');});
