import test from 'node:test';import assert from 'node:assert/strict';
import {MusicRuntime} from '../../dist/apps/bot/src/music/music-runtime.js';
const g='111111111111111111',channel='222222222222222222';
function fixture(){const state={guildId:g,voiceChannelId:channel,textChannelId:channel,revision:2,generation:3,current:{id:'entry',requesterUserId:'member',track:{provider:'youtube',reference:'public',title:'Track',artist:'Artist',album:null,durationMs:100000,artworkUrl:null,seekable:true}},queue:[],history:[],desiredStatus:'PLAYING',observedStatus:'RECOVERING',observedGeneration:3,positionMs:0,observedAt:null,volume:50,loop:'off',autoplay:false,queueMaxTracks:100,skipVotes:{generation:3,voterIds:[]},lastError:null};const mutations=[],calls=[];let lease=true,enabled=true,observation={guildId:g,paused:false,connected:true,positionMs:100,at:2000,track:{entryId:'entry',generation:3}};const repo={read:async()=>({state:structuredClone(state),controllerMessageId:null}),intent:async()=>({obsolete:false,state:structuredClone(state)}),ownsIntentLease:async()=>lease,applyTransportEvent:async(r,e)=>{mutations.push({r,e});return{ignored:false,needsControllerRefresh:true};},recover:async(...args)=>calls.push(['recover',...args]),reserveController:async()=>calls.push(['reserve'])};const options={repository:repo,socketEpoch:'epoch',synchronize:async()=>{calls.push(['sync']);},readPlayer:async()=>{calls.push(['read']);return observation;},enabled:async()=>enabled,refreshController:async()=>calls.push(['refresh']),now:()=>1000};const runtime=new MusicRuntime(options);return{runtime,options,repo,state,mutations,calls,setLease:v=>lease=v,setEnabled:v=>enabled=v,setObservation:v=>observation=v};}
const job={id:'job',guildId:g,jobType:'music.reconcile',executionKey:'intent',dueAt:new Date(),status:'RUNNING',attempts:1,leaseToken:'lease'};
const start={kind:'trackStart',guildId:g,entryId:'entry',generation:3};
test('Playback trace requires a current correlated and persisted TrackStart event',async t=>{
 const traces=[];t.mock.method(console,'info',message=>traces.push(message));const f=fixture();
 await f.runtime.reconcile(job);await f.runtime.event(start,{socketEpoch:'old',sequence:1});await f.runtime.event({...start,generation:2},{socketEpoch:'epoch',sequence:2});assert.deepEqual(traces,[]);
 f.repo.applyTransportEvent=async()=>({ignored:true,needsControllerRefresh:false});await f.runtime.event(start,{socketEpoch:'epoch',sequence:3});assert.deepEqual(traces,[]);
 f.repo.applyTransportEvent=async()=>({ignored:false,needsControllerRefresh:false});await f.runtime.event(start,{socketEpoch:'epoch',sequence:4});assert.deepEqual(traces,['Music trace: playback.started '+JSON.stringify({guildId:g,channelId:channel})]);
});
test('no active job grants mutation authority; reconciliation requires the shared live lease',async()=>{const f=fixture();assert.equal(await f.runtime.isCurrent({guildId:g,revision:2,generation:3}),false);f.setLease(false);await assert.rejects(f.runtime.reconcile(job),{code:'MUSIC_LEASE'});assert.deepEqual(f.calls,[]);});
test('REST acknowledgement and connected telemetry alone cannot manufacture playback history',async()=>{const f=fixture();await f.runtime.reconcile(job);assert.ok(f.calls.some(c=>c[0]==='sync'));assert.deepEqual(f.mutations,[]);await f.runtime.event({kind:'playerUpdate',guildId:g,positionMs:100,at:2000,connected:true},{socketEpoch:'epoch',sequence:1});assert.deepEqual(f.mutations,[]);});
test('correlated start establishes binding; pause telemetry is read and applied separately',async()=>{const f=fixture();f.setObservation({guildId:g,paused:true,connected:true,positionMs:100,at:2000,track:{entryId:'entry',generation:3}});await f.runtime.event(start,{socketEpoch:'epoch',sequence:1});assert.equal(f.mutations[0].e.kind,'track-start');assert.equal(f.mutations[1].e.status,'PAUSED');assert.notEqual(f.mutations[0].r.socketEpoch,f.mutations[1].r.socketEpoch);});
test('old sockets, wrong recordings and old generations are ignored',async()=>{const f=fixture();await f.runtime.event(start,{socketEpoch:'old',sequence:1});await f.runtime.event({...start,entryId:'other'},{socketEpoch:'epoch',sequence:2});await f.runtime.event({...start,generation:2},{socketEpoch:'epoch',sequence:3});assert.deepEqual(f.mutations,[]);});
test('mismatched player telemetry cannot overwrite the bound selected recording',async()=>{const f=fixture();f.setObservation({guildId:g,paused:false,connected:true,positionMs:100,at:2000,track:{entryId:'other',generation:3}});await f.runtime.event(start,{socketEpoch:'epoch',sequence:1});assert.equal(f.mutations.length,1);assert.equal(f.mutations[0].e.kind,'track-start');});
test('events wait behind reconciliation and cannot race its external effects',async()=>{const f=fixture();let release,entered;const started=new Promise(r=>entered=r);f.options.synchronize=async()=>{entered();await new Promise(r=>release=r);};const reconcile=f.runtime.reconcile(job);await started;const event=f.runtime.event(start,{socketEpoch:'epoch',sequence:1});await new Promise(r=>setImmediate(r));assert.equal(f.mutations.length,0);release();await reconcile;await event;assert.equal(f.mutations[0].e.kind,'track-start');});
test('recovery retires bindings and writes one epoch-keyed recovery request without asserting audio',async()=>{const f=fixture();await f.runtime.recover(g);assert.deepEqual(f.calls,[['recover',g,'node-epoch']]);assert.deepEqual(f.mutations,[]);});
test('disabled or closed runtime performs no event writes or transport mutations',async()=>{const f=fixture();f.setEnabled(false);await f.runtime.event(start,{socketEpoch:'epoch',sequence:1});await assert.rejects(f.runtime.reconcile(job),{code:'MUSIC_DISABLED'});f.setEnabled(true);f.runtime.close();await f.runtime.event(start,{socketEpoch:'epoch',sequence:2});assert.deepEqual(f.calls,[]);assert.deepEqual(f.mutations,[]);});
test('disconnect becomes observed only after the voice boundary confirms gateway departure',async()=>{const f=fixture();f.state.current=null;f.state.desiredStatus='DISCONNECTED';await f.runtime.reconcile(job);assert.equal(f.mutations.length,0);f.options.synchronize=async()=>({accepted:true,changed:true,voiceDisconnected:true});await f.runtime.reconcile(job);assert.equal(f.mutations[0].e.status,'DISCONNECTED');});
