import test from 'node:test';
import assert from 'node:assert/strict';
import {ChannelType,Collection,MessageFlags,PermissionFlagsBits,CommandInteractionOptionResolver} from 'discord.js';
import {readFileSync} from 'node:fs';
import sharp from 'sharp';
import {DomainError} from '../../dist/packages/core/src/errors.js';
import {DiscordMusicCoordinator} from '../../dist/apps/bot/src/discord/music-coordinator.js';
import {AuthorizedMusicCatalog} from '../../dist/packages/features-music/src/catalog.js';
import {MusicResolutionService} from '../../dist/packages/features-music/src/resolution.js';
import {createMusicState,enqueueMusic,controlMusic} from '../../dist/packages/features-music/src/domain.js';
const g='111111111111111111',vc='222222222222222222',u='333333333333333333',bot='444444444444444444',message='555555555555555555';
const actor={guildId:g,userId:u,voiceChannelId:vc,textChannelId:vc,eligible:true,isDj:true},policy={queueMaxTracks:10,defaultVolume:65,defaultLoop:'off',defaultAutoplay:false};
function catalog(){return new AuthorizedMusicCatalog([{id:'chair-song',title:'Chair Song',artist:'Test Artist',durationMs:120000,authorizedAudioUri:'https://audio.example.test/song.mp3?signature=fixture-private-secret',format:'mp3',provenance:{kind:'owner-supplied',reference:'fixture-private-proof'},externalMetadataLinks:['https://www.youtube.com/watch?v=abcDEF123_-'],enabled:true,availability:'available',seekable:true}]);}
function fixture(options={}){
 const calls={members:[],voices:[],enqueue:[],control:[],skip:[],catalog:0},members=new Collection(),voices=new Collection();
 function member(id){return{id,user:{id,bot:false},displayName:id===u?'Member':'Listener',isCommunicationDisabled:()=>false,permissionsIn:()=>({has:bits=>(bits&(PermissionFlagsBits.ViewChannel|PermissionFlagsBits.Connect))===bits})};}
 members.set(u,member(u));voices.set(u,{id:u,channelId:vc,selfDeaf:false,serverDeaf:false});
 const channel={id:vc,name:'The Lounge',type:ChannelType.GuildVoice},channels=new Collection([[vc,channel]]),guild={id:g,channels:{cache:channels,fetch:async(id,opts)=>{assert.equal(opts.force,true);return channels.get(id);}},members:{cache:members,fetch:async params=>{assert.equal(params.force,true);calls.members.push(params.user);return members.get(params.user);}},voiceStates:{cache:voices,fetch:async(id,opts)=>{assert.equal(opts.force,true);calls.voices.push(id);return voices.get(id)??{id,channelId:null};}}};
 const values={'music.enabled':true,'music.queue_max_tracks':10,'music.default_volume':65,'music.loop_default':'off','music.autoplay_default':false,...options.values};
 let state=options.state??createMusicState(g,actor,policy).state;const repo={read:async()=>({state,controllerMessageId:message}),enqueue:async(request,entries,p,confirm)=>{calls.enqueue.push({request,entries,confirm});state=enqueueMusic(state,request.actor,entries,p).state;return{jobId:'intent'};},control:async(request,revision,operation)=>{calls.control.push({request,revision,operation});assert.equal(revision,state.revision);state=controlMusic(state,request.actor,operation).state;return{jobId:'intent'};},skip:async(request,generation,ids)=>{calls.skip.push({request,generation,ids});return{skipped:false,votes:1,needed:2};},requestCatalogEnqueue:async(request,ids,source,p)=>{const entries=ids.map((id,n)=>({id:request.requestKey+'-'+n,requesterUserId:request.actor.userId,track:source.resolve(id).track.metadata}));return{kind:'applied',count:entries.length,skippedCount:0,result:await repo.enqueue(request,entries,p)};},historyPage:async()=>({items:[],hasOlder:false,hasNewer:false}),playlistPage:async()=>({items:[],total:0,page:0,pages:1}),...options.repo};
 const access=options.access??(async()=>({eligible:true,isDj:true})),coordinator=new DiscordMusicCoordinator(repo,{get:async(_,key)=>values[key]},async()=>{calls.catalog++;return options.loadCatalog?options.loadCatalog():catalog();},access,()=>1000,options.service,options.autocompleteTimer,options.prepareVoice,options.presentPlayer);
 function interaction(overrides={}){const replies=[],responses=[];return{replies,responses,id:'999999999999999999',guildId:g,guild,channelId:vc,user:{id:u},client:{user:{id:bot}},commandName:'play',deferred:false,replied:false,responded:false,message:{id:message,author:{id:bot},flags:{has:flag=>flag===MessageFlags.Ephemeral}},options:{getString:(key)=>key==='query'?'catalog:chair-song':null,getInteger:()=>null,getBoolean:()=>null,getSubcommand:()=> 'nowplaying',getFocused:()=> 'chair'},isChatInputCommand:()=>true,isButton:()=>false,isStringSelectMenu:()=>false,deferReply:async function(input){assert.equal(input.ephemeral,!(this.isChatInputCommand()&&this.commandName==='play'));this.deferred=true;},deferUpdate:async function(){this.deferred=true;this.updated=true;},followUp:async function(payload){assert.equal(payload.ephemeral,true);replies.push(payload);},deleteReply:async function(){this.deleted=true;},editReply:async function(payload){this.replied=true;replies.push(payload);},reply:async payload=>replies.push(payload),respond:async function(input){this.responded=true;responses.push(input);},...overrides};}
 return{calls,members,voices,guild,channel,coordinator,interaction,state:()=>state};
}
const playingState=()=>{const track=catalog().resolve('catalog:chair-song').track.metadata;return enqueueMusic(createMusicState(g,actor,policy).state,actor,[{id:'a',requesterUserId:u,track}],policy).state;};

test('Recording choice preview stays near square while every native selection remains available',async()=>{
 const choices=Array.from({length:25},(_,n)=>({provider:'youtube',reference:'https://www.youtube.com/watch?v='+String(n).padStart(11,'0'),title:'Recording '+(n+1),artist:'Artist',album:null,durationMs:120000,artworkUrl:null,seekable:true}));
 const f=fixture({service:{search:async()=>choices},repo:{openMusicSearch:async()=>({kind:'resolution-choice',sessionId:'selection',version:4,title:'Choose the exact recording',choices})}}),i=f.interaction({options:{getString:()=> 'recording'}});
 await f.coordinator.handle(i);const reply=i.replies.at(-1),picker=reply.components[0].components[0].toJSON(),image=await sharp(reply.files[0].attachment).metadata();
 assert.equal(picker.options.length,25);assert.equal(picker.options[24].label,'Recording 25');assert.equal(picker.options[24].value,'24');assert.equal(picker.custom_id,`music:resolvepick:${u}:selection:4`);
 assert.match(reply.files[0].description,/25 choices · First 2 shown; all choices in menu/);assert.equal(image.width,440);assert.ok(image.height<=540,`Selection preview should avoid a tall feed thumbnail, got ${image.height}px`);assert.ok(image.width/image.height>=.8);assert.equal(f.calls.enqueue.length,0);
});

test('Catalog choices preserve all native options while using the same two-row preview',async()=>{
 const tracks=Array.from({length:8},(_,n)=>({id:'catalog-'+n,metadata:{title:'Recording '+n,artist:'Artist'}}));
 const f=fixture({loadCatalog:async()=>({search:()=>tracks})}),i=f.interaction({options:{getString:()=> 'recording'}});await f.coordinator.handle(i);
 const reply=i.replies.at(-1),picker=reply.components[0].components[0].toJSON(),image=await sharp(reply.files[0].attachment).metadata();
 assert.equal(picker.options.length,8);assert.equal(picker.options[7].value,'catalog:catalog-7');assert.match(reply.files[0].description,/8 results · First 2 shown; all results in menu/);assert.equal(image.width,440);assert.ok(image.height<=540);assert.equal(f.calls.enqueue.length,0);
});

test('Player native buttons use practical playback, queue and settings rows with unchanged authority IDs',async()=>{
 for(const paused of [false,true]){const state=playingState();if(paused)state.desiredStatus='PAUSED';const f=fixture({state}),payload=await f.coordinator.payload(state,{ownerId:u}),rows=payload.components.map(row=>row.toJSON());
  assert.deepEqual(rows.map(row=>row.components.map(button=>button.label)),[['Previous',paused?'Resume':'Pause','Skip','Stop'],['Queue','Shuffle','Loop'],['Volume','Autoplay','Refresh']]);
  assert.deepEqual(rows.map(row=>row.components.length),[4,3,3]);assert.ok(rows.every(row=>row.type===1));const buttons=rows.flatMap(row=>row.components);assert.equal(new Set(buttons.map(button=>button.custom_id)).size,10);
  for(const button of buttons)assert.ok(button.custom_id.startsWith(`music:control:${g}:${state.revision}:${state.generation}:`)&&button.custom_id.endsWith(':'+u));
  assert.equal(buttons.find(button=>button.label==='Stop').style,4);assert.equal(buttons.find(button=>button.label===(paused?'Resume':'Pause')).style,1);
 }
});

test('Registered /play autocomplete option reaches resolution and queue through the real Discord option resolver',async()=>{
 const registration=JSON.parse(readFileSync(new URL('../../generated/discord/application_commands.json',import.meta.url),'utf8')).find(command=>command.name==='play');
 const option=registration.options.find(option=>option.autocomplete);assert.equal(option.name,'query');
 const selected='https://www.youtube.com/watch?v=aaaaaaaaaaa',track={provider:'youtube',reference:selected,title:'Selected recording',artist:'Artist',album:null,durationMs:100000,artworkUrl:null,seekable:true},calls=[];
 const service=new MusicResolutionService({search:async()=>{throw Error('Selected URL must not rerun text search');},resolve:async(reference)=>{calls.push(['resolve',reference]);return{tracks:[track],truncated:false};}});
 const f=fixture({state:playingState(),service,repo:{requestResolvedTracks:async(request,tracks,resolver)=>{assert.equal(resolver,service);assert.equal(request.actor.guildId,g);assert.equal(request.actor.voiceChannelId,vc);assert.equal(request.actor.textChannelId,vc);calls.push(['queue',tracks[0].reference]);return{kind:'applied',count:1,skippedCount:0,result:{jobId:'persisted-job'}};}}});
 const options=new CommandInteractionOptionResolver({},[{name:option.name,type:option.type,value:selected}],{});
 assert.throws(()=>options.getString('query_or_link',true),{code:'CommandInteractionOptionNotFound'});
 const i=f.interaction({options});await f.coordinator.handle(i);
 assert.deepEqual(calls,[['resolve',selected],['queue',selected]]);assert.ok(i.replies.length);assert.ok(!i.replies.some(reply=>/could not be completed|Music unavailable/.test(reply.content??'')));
});

test('Discord Unknown Voice State asks member to join without searching or enqueueing',async()=>{let searches=0;const f=fixture({service:{search:async()=>{searches++;return[];}}});f.guild.voiceStates.fetch=async()=>{throw Object.assign(Error('private provider details'),{code:10065});};const i=f.interaction();await f.coordinator.handle(i);assert.match(i.replies[0].content,/Join this voice channel/);assert.doesNotMatch(i.replies[0].content,/private/);await f.coordinator.autocomplete(f.interaction());assert.equal(searches,0);assert.equal(f.calls.enqueue.length,0);});

const flushAutocomplete=async()=>{for(let n=0;n<30;n++)await Promise.resolve();};
function autocompleteClock(){let now=0,sequence=0;const pending=new Map();return{get now(){return now;},get pending(){return pending.size;},schedule(callback,delay){const id=++sequence;pending.set(id,{at:now+delay,callback});return()=>pending.delete(id);},async advance(to){assert.ok(to>=now);await flushAutocomplete();for(;;){const next=[...pending.entries()].filter(([,job])=>job.at<=to).sort((a,b)=>a[1].at-b[1].at||a[0]-b[0])[0];if(!next)break;now=next[1].at;pending.delete(next[0]);next[1].callback();await flushAutocomplete();}now=to;await flushAutocomplete();}};}
function deferredAutocomplete(){let resolve,reject;const promise=new Promise((yes,no)=>{resolve=yes;reject=no;});return{promise,resolve,reject};}
const autocompleteTrack={provider:'youtube',reference:'https://www.youtube.com/watch?v=aaaaaaaaaaa',title:'A Room',artist:'An Artist',album:null,durationMs:100000,artworkUrl:null,seekable:true};

test('Autocomplete deadline includes slow authorization and never discovers after the cutoff',async()=>{const clock=autocompleteClock(),access=deferredAutocomplete();let searches=0;const f=fixture({autocompleteTimer:clock.schedule,access:()=>access.promise,service:{search:async()=>{searches++;return[autocompleteTrack];}}}),i=f.interaction(),run=f.coordinator.autocomplete(i);await clock.advance(2250);await run;assert.deepEqual(i.responses,[[]]);assert.equal(searches,0);assert.equal(clock.pending,0);access.resolve({eligible:true,isDj:true});await flushAutocomplete();assert.equal(searches,0);assert.equal(i.responses.length,1);});
test('Autocomplete retains validated earlier provider results within the original entry deadline',async()=>{const clock=autocompleteClock(),access=deferredAutocomplete(),signals=[],sources=[];const service=new MusicResolutionService({search:async(source,_query,_limit,signal)=>{sources.push(source);signals.push(signal);if(sources.length===1)return[autocompleteTrack];return new Promise((_,reject)=>signal.addEventListener('abort',()=>reject(signal.reason),{once:true}));},resolve:async()=>({tracks:[],truncated:false})});const f=fixture({autocompleteTimer:clock.schedule,access:()=>access.promise,service}),i=f.interaction(),run=f.coordinator.autocomplete(i);await clock.advance(1000);access.resolve({eligible:true,isDj:true});await flushAutocomplete();assert.equal(sources.length,2);await clock.advance(2199);assert.equal(i.responses.length,0);await clock.advance(2200);await run;assert.deepEqual(i.responses,[[{name:'A Room — An Artist',value:autocompleteTrack.reference}]]);assert.equal(signals[0],signals[1]);assert.equal(signals[0].reason.name,'TimeoutError');assert.equal(clock.pending,0);});
test('Autocomplete hard cutoff bounds lazy startup that ignores cancellation and discards its late result',async()=>{const clock=autocompleteClock(),startup=deferredAutocomplete();let signal;const f=fixture({autocompleteTimer:clock.schedule,service:{search:async(_query,_limit,currentSignal)=>{signal=currentSignal;await startup.promise;return[autocompleteTrack];}}}),i=f.interaction(),run=f.coordinator.autocomplete(i);await clock.advance(2200);assert.equal(signal.aborted,true);assert.equal(i.responses.length,0);await clock.advance(2250);await run;assert.deepEqual(i.responses,[[]]);startup.resolve();await flushAutocomplete();assert.deepEqual(i.responses,[[]]);assert.equal(clock.pending,0);});
test('Autocomplete consumes late provider rejection without a second response',async()=>{const clock=autocompleteClock(),pending=deferredAutocomplete(),f=fixture({autocompleteTimer:clock.schedule,service:{search:()=>pending.promise}}),i=f.interaction(),run=f.coordinator.autocomplete(i);await clock.advance(2250);await run;pending.reject(new Error('private provider failure'));await flushAutocomplete();assert.deepEqual(i.responses,[[]]);});
test('Autocomplete catalog initialization shares the same deadline and cannot send late choices',async()=>{const clock=autocompleteClock(),pending=deferredAutocomplete(),f=fixture({autocompleteTimer:clock.schedule,loadCatalog:()=>pending.promise}),i=f.interaction(),run=f.coordinator.autocomplete(i);await clock.advance(2250);await run;assert.equal(f.calls.catalog,1);assert.deepEqual(i.responses,[[]]);pending.resolve(catalog());await flushAutocomplete();assert.deepEqual(i.responses,[[]]);});
test('Autocomplete never retries an ambiguous failed response and clears deadline timers',async()=>{const clock=autocompleteClock();let attempts=0;const f=fixture({autocompleteTimer:clock.schedule,service:{search:async()=>[autocompleteTrack]}}),i=f.interaction({respond:async()=>{attempts++;throw new Error('response uncertain');}});await f.coordinator.autocomplete(i);assert.equal(attempts,1);assert.equal(clock.pending,0);await clock.advance(2500);assert.equal(attempts,1);});
test('Autocomplete denies access before provider discovery and skips an already answered interaction',async()=>{const clock=autocompleteClock();let searches=0;const f=fixture({autocompleteTimer:clock.schedule,access:async()=>({eligible:false,isDj:false}),service:{search:async()=>{searches++;return[autocompleteTrack];}}}),i=f.interaction();await f.coordinator.autocomplete(i);assert.deepEqual(i.responses,[[]]);assert.equal(searches,0);assert.equal(clock.pending,0);const answered=f.interaction({responded:true});await f.coordinator.autocomplete(answered);assert.deepEqual(answered.responses,[]);assert.equal(clock.pending,0);});

test('multi-source autocomplete uses provider results without opening the optional private catalog',async()=>{const publicTrack={provider:'youtube',reference:'https://www.youtube.com/watch?v=aaaaaaaaaaa',title:'A Room',artist:'An Artist',album:null,durationMs:100000,artworkUrl:null,seekable:true};const f=fixture({service:{search:async()=>[publicTrack]}}),i=f.interaction();await f.coordinator.autocomplete(i);assert.equal(f.calls.catalog,0);assert.equal(i.responses[0][0].value,publicTrack.reference);});
test('multi-source text search stores durable member-owned choices instead of enqueueing a first result',async()=>{let owner;const track={provider:'youtube',reference:'https://www.youtube.com/watch?v=aaaaaaaaaaa',title:'A Room',artist:'An Artist',album:null,durationMs:100000,artworkUrl:null,seekable:true};const f=fixture({service:{search:async()=>[track]},repo:{openMusicSearch:async request=>{owner=request.actor.userId;return{kind:'resolution-choice',sessionId:'durable-search',version:0,title:'Choose',choices:[track]};}}}),i=f.interaction({options:{getString:()=> 'a song'}});await f.coordinator.handle(i);assert.equal(owner,u);assert.equal(f.calls.catalog,0);assert.equal(f.calls.enqueue.length,0);assert.ok(i.replies.at(-1).components.length);});
test('multi-source URL uses resolved metadata and the guarded selection repository',async()=>{let selection;const track={provider:'spotify',reference:'https://open.spotify.com/track/1234567890123456789012',title:'Requested identity',artist:'Artist',album:null,durationMs:100000,artworkUrl:null,seekable:true};const service={resolveReference:async()=>({tracks:[track],truncated:false})};const f=fixture({service,repo:{requestResolvedTracks:async(request,tracks)=>{selection=tracks;return{kind:'applied',count:1,skippedCount:0,result:{}};}}}),i=f.interaction({options:{getString:()=>track.reference}});await f.coordinator.handle(i);assert.deepEqual(selection,[track]);assert.equal(f.calls.catalog,0);});
test('Disabled music fails before member, catalog, queue or provider operations',async()=>{const f=fixture({values:{'music.enabled':false}}),i=f.interaction();await f.coordinator.handle(i);assert.match(i.replies[0].content,/not enabled/);assert.deepEqual(f.calls.members,[]);assert.equal(f.calls.catalog,0);assert.equal(f.calls.enqueue.length,0);});
test('Music rejects normal text channels and members whose fresh voice state moved away',async()=>{const f=fixture(),i=f.interaction();f.channel.type=ChannelType.GuildText;await f.coordinator.handle(i);assert.match(i.replies[0].content,/embedded text chat/);assert.equal(f.calls.enqueue.length,0);f.channel.type=ChannelType.GuildVoice;f.voices.set(u,{id:u,channelId:'different'});const moved=f.interaction();await f.coordinator.handle(moved);assert.match(moved.replies[0].content,/Join this voice channel/);assert.equal(f.calls.enqueue.length,0);});
test('Autocomplete projects only authorized public catalog labels and stable IDs after fresh access checks',async()=>{const f=fixture(),i=f.interaction();await f.coordinator.autocomplete(i);assert.deepEqual(i.responses,[[{name:'Chair Song — Test Artist',value:'catalog:chair-song'}]]);assert.deepEqual(f.calls.members,[u]);assert.deepEqual(f.calls.voices,[u]);assert.doesNotMatch(JSON.stringify(i.responses),/fixture-private|audio\.example/);});
test('Unavailable or restricted autocomplete returns no discoverable catalog results',async()=>{const f=fixture({access:async()=>({eligible:false,isDj:false})}),i=f.interaction();await f.coordinator.autocomplete(i);assert.deepEqual(i.responses,[[]]);assert.equal(f.calls.catalog,0);});
test('Typed search presents an explicit recording choice and never silently enqueues the first result',async()=>{const f=fixture(),i=f.interaction({options:{getString:()=> 'chair'}});await f.coordinator.handle(i);assert.equal(f.calls.enqueue.length,0);assert.match(i.replies[0].content,/do not start playback automatically/);const picker=i.replies[0].components[0].components[0];assert.equal(picker.data.custom_id,'music:pick:'+u);assert.equal(picker.options[0].data.value,'catalog:chair-song');});
test('Selected catalog recording queues only metadata and reports pending transport rather than playback success',async()=>{const f=fixture(),i=f.interaction({isChatInputCommand:()=>false,isStringSelectMenu:()=>true,customId:'music:pick:'+u,values:['catalog:chair-song']});await f.coordinator.handle(i);assert.equal(f.calls.enqueue.length,1);const saved=f.calls.enqueue[0];assert.equal(saved.entries[0].track.reference,'catalog:chair-song');assert.equal(saved.entries[0].requesterUserId,u);assert.doesNotMatch(JSON.stringify(saved),/fixture-private|audio\.example/);assert.match(i.replies[0].content,/saved queue/);assert.match(i.replies[0].content,/only after transport confirmation/);assert.equal(f.state().observedStatus,'DISCONNECTED');assert.deepEqual(i.replies[0].files,[]);assert.match(i.replies[0].content,/Open the Jukebox/);});
test('A different member cannot reuse another member’s search selection',async()=>{const f=fixture(),i=f.interaction({isChatInputCommand:()=>false,isStringSelectMenu:()=>true,customId:'music:pick:other',values:['catalog:chair-song']});await f.coordinator.handle(i);assert.match(i.replies[0].content,/own current music search/);assert.equal(f.calls.enqueue.length,0);});
test('External links queue only an exact catalog match and otherwise render a branded unavailable result',async()=>{const f=fixture(),i=f.interaction({options:{getString:()=> 'https://youtu.be/abcDEF123_-'}});await f.coordinator.handle(i);assert.equal(f.calls.enqueue.length,1);const other=fixture(),unknown=other.interaction({options:{getString:()=> 'https://www.youtube.com/watch?v=another1234'}});await other.coordinator.handle(unknown);assert.equal(other.calls.enqueue.length,0);assert.match(unknown.replies[0].content,/no exact authorized catalog match/);assert.ok(unknown.replies[0].files[0].attachment.length>1000);});
test('Duplicate selection presents the repository durable confirmation with owner-bound controls',async()=>{const f=fixture({repo:{requestCatalogEnqueue:async()=>({kind:'confirmation',sessionId:'durable-session',action:'enqueue',count:1,skippedCount:0,expiresAt:'2030-01-01'})}}),i=f.interaction();await f.coordinator.handle(i);assert.match(i.replies[0].content,/including duplicates/);assert.equal(f.calls.enqueue.length,0);assert.deepEqual(i.replies[0].components[0].components.map(b=>b.data.custom_id),['music:confirm:'+u+':durable-session','music:cancel:'+u+':durable-session']);});
test('Generated typed control options use the current persisted revision and requester permission is rechecked',async()=>{const f=fixture({state:playingState()}),i=f.interaction({commandName:'music',options:{getSubcommand:()=> 'seek',getString:key=>key==='time'?'1:05':null}});await f.coordinator.handle(i);assert.equal(f.calls.control[0].operation.positionMs,65000);assert.equal(f.calls.control[0].revision,1);const restricted=fixture({state:{...playingState(),current:{...playingState().current,requesterUserId:'other'}},access:async()=>({eligible:true,isDj:false})}),other=restricted.interaction({commandName:'music',options:{getSubcommand:()=> 'replay'}});await restricted.coordinator.handle(other);assert.match(other.replies[0].content,/requester or a DJ/);});
test('Skip filters bots, deafened, departed and restricted listeners from fresh eligible audience',async()=>{const f=fixture({state:playingState(),access:async(_g,m)=>({eligible:m.id!=='restricted',isDj:false})});for(const id of ['listener','deaf','departed','restricted','bot']){f.members.set(id,{id,user:{bot:id==='bot'},displayName:id,isCommunicationDisabled:()=>false,permissionsIn:()=>({has:()=>true})});f.voices.set(id,{id,channelId:vc,selfDeaf:id==='deaf',serverDeaf:false});}const original=f.guild.voiceStates.fetch;f.guild.voiceStates.fetch=async(id,options)=>id==='departed'?{id,channelId:'other'}:original(id,options);const i=f.interaction({commandName:'music',options:{getSubcommand:()=> 'skip'}});await f.coordinator.handle(i);assert.deepEqual(f.calls.skip[0].ids.sort(),[u,'listener'].sort());assert.equal(f.calls.skip[0].generation,1);assert.match(i.replies[0].content,/Vote Skip: 1\/2/);});
test('Public controls require the saved authoritative bot post; stale revisions cannot mutate current state',async()=>{const f=fixture({state:playingState()}),base={isChatInputCommand:()=>false,isButton:()=>true,customId:`music:control:${g}:0:1:pause:public`,message:{id:message,author:{id:bot},flags:{has:()=>false}}};const stale=f.interaction(base);await f.coordinator.handle(stale);assert.match(stale.replies[0].content,/player changed/);assert.equal(f.calls.control.length,0);const forged=f.interaction({...base,customId:`music:control:${g}:1:1:pause:public`,message:{...base.message,id:'not-current'}});await f.coordinator.handle(forged);assert.match(forged.replies[0].content,/authoritative music controller/);assert.equal(f.calls.control.length,0);});
test('Controller payload uses approved runtime renderer and canonical native controls with generation fencing',async()=>{const f=fixture({state:playingState()}),payload=await f.coordinator.payload(f.state(),{voiceChannelName:'The Lounge',requesterName:'Member'});assert.ok(payload.files[0].attachment.length>1000);assert.deepEqual(payload.allowedMentions,{parse:[]});const buttons=payload.components.flatMap(row=>row.components);for(const name of ['Previous','Pause','Skip','Stop','Shuffle','Loop','Queue','Volume'])assert.ok(buttons.some(b=>b.data.label===name));assert.ok(buttons.every(b=>b.data.custom_id.includes(`:${g}:1:1:`)));});
test('Read-only history does not invent played entries',async()=>{const f=fixture({state:playingState()}),history=f.interaction({commandName:'music',options:{getSubcommand:()=> 'history'}});await f.coordinator.handle(history);assert.match(history.replies[0].content,/No playback has been confirmed/);});
test('Confirmation reloads catalog and current access; another owner cannot consume it',async()=>{const called=[],f=fixture({repo:{confirmSelection:async(req,id,source,p)=>{called.push({req,id,reference:source.resolve('catalog:chair-song').track.metadata.reference});return{kind:'cancelled'};}}});const button={isButton:()=>true,customId:`music:confirm:${u}:saved-session`},i=f.interaction(button);await f.coordinator.handle(i);assert.equal(called.length,1);assert.equal(f.calls.catalog,1);assert.equal(called[0].id,'saved-session');assert.match(i.replies[0].content,/cancelled/);const other=f.interaction({...button,customId:'music:confirm:other:saved-session'});await f.coordinator.handle(other);assert.equal(called.length,1);assert.match(other.replies[0].content,/own private music controls/);f.voices.set(u,{id:u,channelId:'left'});await f.coordinator.handle(f.interaction(button));assert.equal(called.length,1);});
test('Queue pagination shows global positions beyond twenty and owner-bound navigation',async()=>{const state=playingState();state.queue=Array.from({length:35},(_,n)=>({id:'q-'+n,requesterUserId:u,track:{...state.current.track,title:'Queue track '+(n+1)}}));const f=fixture({state}),i=f.interaction({isButton:()=>true,customId:`music:page:${u}:queue:2`});await f.coordinator.handle(i);assert.match(i.replies[0].content,/21\. Queue track 21/);assert.match(i.replies[0].content,/30\. Queue track 30/);assert.doesNotMatch(i.replies[0].content,/31\. Queue track/);assert.equal(i.replies[0].components[0].components[1].data.custom_id,`music:page:${u}:queue:3`);});
test('Playlist commands use exact scoped lookup, revision fencing and shared deletion confirmation',async()=>{const calls=[],playlist={id:'saved-list',name:'Collection',revision:7,tracks:[]};const f=fixture({repo:{playlistByName:async(req,name)=>{calls.push(['lookup',name]);return playlist;},requestPlaylistDelete:async(req,id,revision)=>{calls.push(['delete',id,revision]);return{kind:'confirmation',action:'playlist-delete',sessionId:'delete-session',count:0,skippedCount:0,expiresAt:'2030-01-01'};},editPlaylist:async(req,id,revision,change)=>{calls.push(['edit',id,revision,change]);},readPlaylist:async()=>playlist}});await f.coordinator.handle(f.interaction({commandName:'playlist',options:{getSubcommand:()=> 'remove',getString:()=> 'Collection',getInteger:()=>3}}));assert.deepEqual(calls[1],['edit','saved-list',7,{kind:'remove',position:3}]);const deletion=f.interaction({commandName:'playlist',options:{getSubcommand:()=> 'delete',getString:()=> 'Collection'}});await f.coordinator.handle(deletion);assert.deepEqual(calls.at(-1),['delete','saved-list',7]);assert.match(deletion.replies[0].content,/already queued remain queued/);assert.equal(deletion.replies[0].components[0].components[0].data.label,'Delete playlist');});
test('Playlist search selection binds owner, playlist identity and revision without automatic first match',async()=>{const calls=[],f=fixture({repo:{playlistByName:async()=>({id:'saved-list',revision:7}),requestPlaylistAdd:async(req,id,revision,ids)=>{calls.push({id,revision,ids});return{kind:'applied',count:1,skippedCount:0,result:{playlistId:id,deleted:false}};}}}),search=f.interaction({commandName:'playlist',options:{getSubcommand:()=> 'add',getString:key=>key==='name'?'Collection':'chair'}});await f.coordinator.handle(search);const id=search.replies[0].components[0].components[0].data.custom_id;assert.equal(id,`music:addpick:${u}:saved-list:7`);assert.equal(calls.length,0);const selected=f.interaction({isStringSelectMenu:()=>true,customId:id,values:['catalog:chair-song']});await f.coordinator.handle(selected);assert.deepEqual(calls,[{id:'saved-list',revision:7,ids:['catalog:chair-song']}]);assert.match(selected.replies[0].content,/saved playlist/);});
test('History navigation uses scoped opaque anchors and displays only confirmed entries',async()=>{const calls=[],f=fixture({repo:{historyPage:async(req,id,direction)=>{calls.push({id,direction});return{items:[{id:'history-anchor',metadata:{title:'Actually played',artist:'Artist'}}],hasOlder:true,hasNewer:true};}}}),i=f.interaction({isButton:()=>true,customId:`music:page:${u}:history:older:previous-anchor`});await f.coordinator.handle(i);assert.deepEqual(calls,[{id:'previous-anchor',direction:'older'}]);assert.match(i.replies[0].content,/Actually played/);assert.deepEqual(i.replies[0].components[0].components.map(b=>b.data.label),['Newer','Older','Latest']);});

test('Explicit SoundCloud autocomplete preserves its canonical URL and never searches another source',async()=>{
 const url='https://soundcloud.com/kr3ture/watch-it-grow';let searches=0;const f=fixture({service:{search:async()=>{searches++;throw Error('must not search URLs');}}});
 const i=f.interaction({options:{getFocused:()=>url}});await f.coordinator.autocomplete(i);assert.equal(searches,0);assert.equal(i.responses[0].length,1);assert.equal(i.responses[0][0].value,url);assert.match(i.responses[0][0].name,/soundcloud/);
 for(const value of ['https://soundcloud.com/','https://secret.invalid/track','https://soundcloud.com/artist/song?secret_token=private']){const bad=f.interaction({options:{getFocused:()=>value}});await f.coordinator.autocomplete(bad);assert.deepEqual(bad.responses,[[]]);}assert.equal(searches,0);
});
test('Explicit SoundCloud execution retains source and requested identity through durable queue admission',async()=>{
 const url='https://soundcloud.com/kr3ture/watch-it-grow',track={provider:'soundcloud',reference:url,title:'Watch It Grow',artist:'KR3TURE',album:null,durationMs:209868,artworkUrl:null,seekable:true};let admitted;
 const service=new MusicResolutionService({search:async()=>{throw Error('no search');},resolve:async ref=>{assert.equal(ref,url);return{tracks:[track],truncated:false};}});
 const f=fixture({service,repo:{requestResolvedTracks:async(request,tracks)=>{admitted=tracks;return{kind:'applied',count:1,skippedCount:0,result:{jobId:'intent'}};}}});const i=f.interaction({options:{getString:()=>url}});await f.coordinator.handle(i);assert.deepEqual(admitted,[track]);assert.match(i.replies[0].content,/shared Jukebox/);
});
test('Default active player uses the approved wider-aspect compact frame without losing native controls',async()=>{
 const f=fixture({state:playingState()}),payload=await f.coordinator.payload(f.state()),image=await sharp(payload.files[0].attachment).metadata();assert.equal(image.width,440);assert.ok(image.height<600);assert.equal(payload.components.length,3);assert.deepEqual(payload.components.map(row=>row.components.length),[4,3,3]);
});


test('validated URL and text /play requests prepare voice before provider work or rendering',async()=>{
 for(const query of ['https://soundcloud.com/kr3ture/watch-it-grow','watch it grow']){
  const order=[],track={provider:'soundcloud',reference:'https://soundcloud.com/kr3ture/watch-it-grow',title:'Watch It Grow',artist:'KR3TURE',album:null,durationMs:209868,artworkUrl:null,seekable:true};
  const f=fixture({prepareVoice:async(request)=>{assert.equal(request.actor.voiceChannelId,vc);order.push('voice');},service:{resolveReference:async value=>{assert.equal(value,query);order.push('resolve');return{tracks:[track],truncated:false};},search:async value=>{assert.equal(value,query);order.push('search');return[track];}},repo:{requestResolvedTracks:async(_request,tracks)=>{assert.equal(tracks[0].provider,'soundcloud');order.push('queue');return{kind:'applied',count:1,skippedCount:0,result:{}};},openMusicSearch:async(_request,choices)=>{order.push('selection');return{kind:'resolution-choice',sessionId:'selection',version:1,title:'Choose the exact recording',choices};}}});
  const i=f.interaction({options:{getString:()=>query}});await f.coordinator.handle(i);assert.deepEqual(order,query.startsWith('https:')?['voice','resolve','queue']:['voice','search','selection']);assert.ok(i.replies.length);
 }
});

test('invalid voice context never initiates early join; resolution failure still follows an attempted join',async()=>{
 let joined=0;const prepareVoice=async()=>{joined++;};const invalid=fixture({prepareVoice,values:{'music.enabled':false}});await invalid.coordinator.handle(invalid.interaction());assert.equal(joined,0);
 const f=fixture({prepareVoice,service:{resolveReference:async()=>{throw new DomainError('MUSIC_UNAVAILABLE','This reference is unavailable.');}}}),i=f.interaction({options:{getString:()=> 'https://soundcloud.com/kr3ture/watch-it-grow'}});await f.coordinator.handle(i);assert.equal(joined,1);assert.match(i.replies[0].content,/reference is unavailable/);assert.equal(f.calls.enqueue.length,0);
});

test('queue and long unavailable notices retain complete readable content with wide bounded artwork',async()=>{
 const state=playingState();state.queue=Array.from({length:10},(_,n)=>({...state.current,id:'queued-'+n,track:{...state.current.track,title:'Queued recording '+n}}));const f=fixture({state}),i=f.interaction({commandName:'music',options:{getSubcommand:()=> 'queue'}});await f.coordinator.handle(i);
 const payload=i.replies[0],dimensions=await sharp(payload.files[0].attachment).metadata();assert.equal(dimensions.width,440);assert.ok(dimensions.height<=540);assert.match(payload.content,/10\. Queued recording 9/);
 const message='Track cannot be played. '.repeat(30),bad=fixture({service:{search:async()=>{throw new DomainError('MUSIC_UNAVAILABLE',message);}}}),failure=bad.interaction({options:{getString:()=> 'a recording'}});await bad.coordinator.handle(failure);assert.equal(failure.replies[0].content,message);const errorDimensions=await sharp(failure.replies[0].files[0].attachment).metadata();assert.equal(errorDimensions.width,440);assert.ok(errorDimensions.height<=540);
});

test('Public /play acknowledges before access and returns only a link to the shared player',async()=>{
 let acknowledged=false,presented=0;const f=fixture({access:async()=>{assert.equal(acknowledged,true);return{eligible:true,isDj:true};},presentPlayer:async()=>{presented++;assert.equal(f.calls.enqueue.length,1);}}),i=f.interaction({deferReply:async function(options){assert.equal(options.ephemeral,false);acknowledged=true;this.deferred=true;}});
 await f.coordinator.handle(i);assert.equal(presented,1);assert.equal(i.replies[0].files.length,0);assert.equal(i.replies[0].components.length,0);assert.match(i.replies[0].content,/Open the Jukebox/);
});
test('Current public controls persist before immediate player work and never emit another player',async()=>{
 for(const action of ['pause','resume','stop','previous','shuffle','loop','autoplay']){let presented=0;const state=playingState();if(action==='resume')state.desiredStatus='PAUSED';if(action==='previous')state.history=[{...state.current,id:'previous'}];const f=fixture({state,presentPlayer:async()=>{presented++;assert.equal(f.calls.control.length,1);}}),i=f.interaction({isChatInputCommand:()=>false,isButton:()=>true,customId:`music:control:${g}:${state.revision}:${state.generation}:${action}:public`,message:{id:message,author:{id:bot},flags:{has:()=>false}}});await f.coordinator.handle(i);assert.equal(f.calls.control.length,1,action);assert.equal(presented,1,action);assert.equal(i.updated,true);assert.deepEqual(i.replies,[]);}
});
test('Retired private player controls and stale skip generations never mutate the active player',async()=>{
 for(const action of ['pause','skip','stop','nowplaying']){const state=playingState(),f=fixture({state}),i=f.interaction({isChatInputCommand:()=>false,isButton:()=>true,customId:`music:control:${g}:${state.revision}:${state.generation}:${action}:${u}`});await f.coordinator.handle(i);assert.equal(f.calls.control.length,0);assert.equal(f.calls.skip.length,0);assert.match(i.replies[0].content,/authoritative/);}
 const state=playingState(),f=fixture({state}),i=f.interaction({isChatInputCommand:()=>false,isButton:()=>true,customId:`music:control:${g}:${state.revision}:0:skip:public`,message:{id:message,author:{id:bot},flags:{has:()=>false}}});await f.coordinator.handle(i);assert.equal(f.calls.skip.length,0);assert.match(i.replies[0].content,/player changed/);
});
test('Private volume choices remain owner revision generation and authoritative message bound',async()=>{
 for(const marker of [message,'replaced']){const state=playingState(),f=fixture({state}),i=f.interaction({isChatInputCommand:()=>false,isButton:()=>true,customId:`music:control:${g}:${state.revision}:${state.generation}:volume_80:${u}:m=${marker}`});await f.coordinator.handle(i);assert.equal(f.calls.control.length,marker===message?1:0);if(marker===message)assert.equal(f.calls.control[0].operation.percent,80);}
});
test('Owner-bound public recording selection remains usable only by the initiating member',async()=>{
 for(const owner of [u,'other']){let selected=0;const f=fixture({service:{},repo:{chooseResolvedTrack:async()=>{selected++;return{kind:'cancelled'};}}}),i=f.interaction({isChatInputCommand:()=>false,isStringSelectMenu:()=>true,customId:`music:resolvepick:${owner}:selection:0`,values:['0'],message:{id:message,author:{id:bot},flags:{has:()=>false}}});await f.coordinator.handle(i);assert.equal(selected,owner===u?1:0);}
});

for(const action of ['pause','resume','skip','stop'])test('Silent '+action+' acknowledges before access and refreshes only the shared player',async()=>{
 const state=playingState();if(action==='resume')state.desiredStatus='PAUSED';let acknowledged=false,refreshed=0;
 const f=fixture({state,access:async()=>{assert.equal(acknowledged,true);return{eligible:true,isDj:true};},repo:{skip:async()=>({skipped:true})},presentPlayer:async()=>{refreshed++;}});
 const i=f.interaction({isChatInputCommand:()=>false,isButton:()=>true,customId:`music:control:${g}:${action==='skip'?state.revision-1:state.revision}:${state.generation}:${action}:public`,message:{id:message,author:{id:bot},flags:{has:()=>false}},deferUpdate:async function(){acknowledged=true;this.deferred=true;}});
 await f.coordinator.handle(i);assert.equal(refreshed,1);assert.deepEqual(i.replies,[]);assert.notEqual(i.deleted,true);
});
test('Confirmed duplicate addition consumes its confirmation without another success card',async()=>{
 for(const resolved of [true,false]){let applied=0,refreshed=0;const result={kind:'applied',count:1,skippedCount:0,result:{jobId:'intent'}};
 const f=fixture({service:{},repo:{confirmResolvedSelection:async()=>{applied++;return result;},confirmSelection:async()=>{applied++;return result;}},presentPlayer:async()=>{refreshed++;}}),i=f.interaction({isChatInputCommand:()=>false,isButton:()=>true,customId:resolved?`music:resolveconfirm:${u}:selection:1`:`music:confirm:${u}:selection`});
 await f.coordinator.handle(i);assert.equal(applied,1);assert.equal(refreshed,1);assert.equal(i.deleted,true);assert.deepEqual(i.replies,[]);
 }
});
test('Genuine silent-control errors are private and never replace the public player',async()=>{
 const state=playingState(),f=fixture({state,repo:{control:async()=>{throw new DomainError('MUSIC_DJ','DJ authority required.');}}}),i=f.interaction({isChatInputCommand:()=>false,isButton:()=>true,customId:`music:control:${g}:${state.revision}:${state.generation}:stop:public`,message:{id:message,author:{id:bot},flags:{has:()=>false}},editReply:async()=>assert.fail('Must not overwrite public player')});
 await f.coordinator.handle(i);assert.equal(i.replies.length,1);assert.equal(i.replies[0].ephemeral,true);assert.match(i.replies[0].content,/DJ authority/);
});
test('/music nowplaying opens the existing authoritative Jukebox without sending another player',async()=>{
 const f=fixture({state:playingState()}),i=f.interaction({commandName:'music'});await f.coordinator.handle(i);assert.match(i.replies[0].content,new RegExp(message));assert.match(i.replies[0].content,/Open the Jukebox/);assert.deepEqual(i.replies[0].files,[]);assert.deepEqual(i.replies[0].components,[]);
});
