import test from 'node:test';
import assert from 'node:assert/strict';
import {ChannelType,Collection,MessageFlags,PermissionFlagsBits} from 'discord.js';
import {DomainError} from '../../dist/packages/core/src/errors.js';
import {DiscordMusicCoordinator} from '../../dist/apps/bot/src/discord/music-coordinator.js';
import {AuthorizedMusicCatalog} from '../../dist/packages/features-music/src/catalog.js';
import {createMusicState,enqueueMusic,controlMusic} from '../../dist/packages/features-music/src/domain.js';
const g='111111111111111111',vc='222222222222222222',u='333333333333333333',bot='444444444444444444',message='555555555555555555';
const actor={guildId:g,userId:u,voiceChannelId:vc,textChannelId:vc,eligible:true,isDj:true},policy={queueMaxTracks:10,defaultVolume:65,defaultLoop:'off',defaultAutoplay:false};
function catalog(){return new AuthorizedMusicCatalog([{id:'chair-song',title:'Chair Song',artist:'Test Artist',durationMs:120000,authorizedAudioUri:'https://audio.example.test/song.mp3?signature=fixture-private-secret',format:'mp3',provenance:{kind:'owner-supplied',reference:'fixture-private-proof'},externalMetadataLinks:['https://www.youtube.com/watch?v=abcDEF123_-'],enabled:true,availability:'available',seekable:true}]);}
function fixture(options={}){
 const calls={members:[],voices:[],enqueue:[],control:[],skip:[],catalog:0},members=new Collection(),voices=new Collection();
 function member(id){return{id,user:{id,bot:false},displayName:id===u?'Member':'Listener',isCommunicationDisabled:()=>false,permissionsIn:()=>({has:bits=>(bits&(PermissionFlagsBits.ViewChannel|PermissionFlagsBits.Connect))===bits})};}
 members.set(u,member(u));voices.set(u,{id:u,channelId:vc,selfDeaf:false,serverDeaf:false});
 const channel={id:vc,name:'The Lounge',type:ChannelType.GuildVoice},channels=new Collection([[vc,channel]]),guild={id:g,channels:{cache:channels,fetch:async(id,opts)=>{assert.equal(opts.force,true);return channels.get(id);}},members:{cache:members,fetch:async params=>{assert.equal(params.force,true);calls.members.push(params.user);return members.get(params.user);}},voiceStates:{cache:voices,fetch:async(id,opts)=>{assert.equal(opts.force,true);calls.voices.push(id);return voices.get(id)??{id,channelId:null};}}};
 const values={'music.enabled':true,'music.queue_max_tracks':10,'music.default_volume':65,'music.loop_default':'off','music.autoplay_default':false,...options.values};
 let state=options.state??createMusicState(g,actor,policy).state;const repo={read:async()=>({state,controllerMessageId:message}),enqueue:async(request,entries,p,confirm)=>{calls.enqueue.push({request,entries,confirm});state=enqueueMusic(state,request.actor,entries,p).state;return{jobId:'intent'};},control:async(request,revision,operation)=>{calls.control.push({request,revision,operation});assert.equal(revision,state.revision);state=controlMusic(state,request.actor,operation).state;return{jobId:'intent'};},skip:async(request,generation,ids)=>{calls.skip.push({request,generation,ids});return{skipped:false,votes:1,needed:2};},confirmedHistory:async()=>[],playlists:async()=>[],...options.repo};
 const access=options.access??(async()=>({eligible:true,isDj:true})),coordinator=new DiscordMusicCoordinator(repo,{get:async(_,key)=>values[key]},async()=>{calls.catalog++;return catalog();},access,()=>1000);
 function interaction(overrides={}){const replies=[],responses=[];return{replies,responses,id:'999999999999999999',guildId:g,guild,channelId:vc,user:{id:u},client:{user:{id:bot}},commandName:'play',deferred:false,replied:false,responded:false,message:{id:message,author:{id:bot},flags:{has:flag=>flag===MessageFlags.Ephemeral}},options:{getString:(key)=>key==='query_or_link'?'catalog:chair-song':null,getInteger:()=>null,getBoolean:()=>null,getSubcommand:()=> 'nowplaying',getFocused:()=> 'chair'},isChatInputCommand:()=>true,isButton:()=>false,isStringSelectMenu:()=>false,deferReply:async function(input){assert.equal(input.ephemeral,true);this.deferred=true;},editReply:async function(payload){this.replied=true;replies.push(payload);},reply:async payload=>replies.push(payload),respond:async function(input){this.responded=true;responses.push(input);},...overrides};}
 return{calls,members,voices,guild,channel,coordinator,interaction,state:()=>state};
}
const playingState=()=>{const track=catalog().resolve('catalog:chair-song').track.metadata;return enqueueMusic(createMusicState(g,actor,policy).state,actor,[{id:'a',requesterUserId:u,track}],policy).state;};
test('Disabled music fails before member, catalog, queue or provider operations',async()=>{const f=fixture({values:{'music.enabled':false}}),i=f.interaction();await f.coordinator.handle(i);assert.match(i.replies[0].content,/not enabled/);assert.deepEqual(f.calls.members,[]);assert.equal(f.calls.catalog,0);assert.equal(f.calls.enqueue.length,0);});
test('Music rejects normal text channels and members whose fresh voice state moved away',async()=>{const f=fixture(),i=f.interaction();f.channel.type=ChannelType.GuildText;await f.coordinator.handle(i);assert.match(i.replies[0].content,/embedded text chat/);assert.equal(f.calls.enqueue.length,0);f.channel.type=ChannelType.GuildVoice;f.voices.set(u,{id:u,channelId:'different'});const moved=f.interaction();await f.coordinator.handle(moved);assert.match(moved.replies[0].content,/Join this voice channel/);assert.equal(f.calls.enqueue.length,0);});
test('Autocomplete projects only authorized public catalog labels and stable IDs after fresh access checks',async()=>{const f=fixture(),i=f.interaction();await f.coordinator.autocomplete(i);assert.deepEqual(i.responses,[[{name:'Chair Song — Test Artist',value:'catalog:chair-song'}]]);assert.deepEqual(f.calls.members,[u]);assert.deepEqual(f.calls.voices,[u]);assert.doesNotMatch(JSON.stringify(i.responses),/fixture-private|audio\.example/);});
test('Unavailable or restricted autocomplete returns no discoverable catalog results',async()=>{const f=fixture({access:async()=>({eligible:false,isDj:false})}),i=f.interaction();await f.coordinator.autocomplete(i);assert.deepEqual(i.responses,[[]]);assert.equal(f.calls.catalog,0);});
test('Typed search presents an explicit recording choice and never silently enqueues the first result',async()=>{const f=fixture(),i=f.interaction({options:{getString:()=> 'chair'}});await f.coordinator.handle(i);assert.equal(f.calls.enqueue.length,0);assert.match(i.replies[0].content,/do not start playback automatically/);const picker=i.replies[0].components[0].components[0];assert.equal(picker.data.custom_id,'music:pick:'+u);assert.equal(picker.options[0].data.value,'catalog:chair-song');});
test('Selected catalog recording queues only metadata and reports pending transport rather than playback success',async()=>{const f=fixture(),i=f.interaction({isChatInputCommand:()=>false,isStringSelectMenu:()=>true,customId:'music:pick:'+u,values:['catalog:chair-song']});await f.coordinator.handle(i);assert.equal(f.calls.enqueue.length,1);const saved=f.calls.enqueue[0];assert.equal(saved.entries[0].track.reference,'catalog:chair-song');assert.equal(saved.entries[0].requesterUserId,u);assert.doesNotMatch(JSON.stringify(saved),/fixture-private|audio\.example/);assert.match(i.replies[0].content,/saved queue/);assert.match(i.replies[0].content,/only after transport confirmation/);assert.equal(f.state().observedStatus,'DISCONNECTED');assert.equal(i.replies[0].files[0].name,'music-controller.png');});
test('A different member cannot reuse another member’s search selection',async()=>{const f=fixture(),i=f.interaction({isChatInputCommand:()=>false,isStringSelectMenu:()=>true,customId:'music:pick:other',values:['catalog:chair-song']});await f.coordinator.handle(i);assert.match(i.replies[0].content,/own current music search/);assert.equal(f.calls.enqueue.length,0);});
test('External links queue only an exact catalog match and otherwise render a branded unavailable result',async()=>{const f=fixture(),i=f.interaction({options:{getString:()=> 'https://youtu.be/abcDEF123_-'}});await f.coordinator.handle(i);assert.equal(f.calls.enqueue.length,1);const other=fixture(),unknown=other.interaction({options:{getString:()=> 'https://www.youtube.com/watch?v=another1234'}});await other.coordinator.handle(unknown);assert.equal(other.calls.enqueue.length,0);assert.match(unknown.replies[0].content,/no exact authorized catalog match/);assert.ok(unknown.replies[0].files[0].attachment.length>1000);});
test('Duplicate confirmation remains explicitly gated without a second queue mutation or in-memory confirmation',async()=>{const f=fixture({repo:{enqueue:async()=>{throw new DomainError('MUSIC_DUPLICATE','Duplicate.');}}}),i=f.interaction();await f.coordinator.handle(i);assert.match(i.replies[0].content,/Duplicate confirmation is not available yet/);assert.match(i.replies[0].content,/no additional track/);assert.deepEqual(i.replies[0].components,[]);});
test('Generated typed control options use the current persisted revision and requester permission is rechecked',async()=>{const f=fixture({state:playingState()}),i=f.interaction({commandName:'music',options:{getSubcommand:()=> 'seek',getString:key=>key==='time'?'1:05':null}});await f.coordinator.handle(i);assert.equal(f.calls.control[0].operation.positionMs,65000);assert.equal(f.calls.control[0].revision,1);const restricted=fixture({state:{...playingState(),current:{...playingState().current,requesterUserId:'other'}},access:async()=>({eligible:true,isDj:false})}),other=restricted.interaction({commandName:'music',options:{getSubcommand:()=> 'replay'}});await restricted.coordinator.handle(other);assert.match(other.replies[0].content,/requester or a DJ/);});
test('Skip filters bots, deafened, departed and restricted listeners from fresh eligible audience',async()=>{const f=fixture({state:playingState(),access:async(_g,m)=>({eligible:m.id!=='restricted',isDj:false})});for(const id of ['listener','deaf','departed','restricted','bot']){f.members.set(id,{id,user:{bot:id==='bot'},displayName:id,isCommunicationDisabled:()=>false,permissionsIn:()=>({has:()=>true})});f.voices.set(id,{id,channelId:vc,selfDeaf:id==='deaf',serverDeaf:false});}const original=f.guild.voiceStates.fetch;f.guild.voiceStates.fetch=async(id,options)=>id==='departed'?{id,channelId:'other'}:original(id,options);const i=f.interaction({commandName:'music',options:{getSubcommand:()=> 'skip'}});await f.coordinator.handle(i);assert.deepEqual(f.calls.skip[0].ids.sort(),[u,'listener'].sort());assert.equal(f.calls.skip[0].generation,1);assert.match(i.replies[0].content,/Vote Skip: 1\/2/);});
test('Public controls require the saved authoritative bot post; stale revisions cannot mutate current state',async()=>{const f=fixture({state:playingState()}),base={isChatInputCommand:()=>false,isButton:()=>true,customId:`music:control:${g}:0:1:pause:public`,message:{id:message,author:{id:bot},flags:{has:()=>false}}};const stale=f.interaction(base);await f.coordinator.handle(stale);assert.match(stale.replies[0].content,/player changed/);assert.equal(f.calls.control.length,0);const forged=f.interaction({...base,customId:`music:control:${g}:1:1:pause:public`,message:{...base.message,id:'not-current'}});await f.coordinator.handle(forged);assert.match(forged.replies[0].content,/authoritative music controller/);assert.equal(f.calls.control.length,0);});
test('Controller payload uses approved runtime renderer and canonical native controls with generation fencing',async()=>{const f=fixture({state:playingState()}),payload=await f.coordinator.payload(f.state(),{voiceChannelName:'The Lounge',requesterName:'Member'});assert.ok(payload.files[0].attachment.length>1000);assert.deepEqual(payload.allowedMentions,{parse:[]});const buttons=payload.components.flatMap(row=>row.components);for(const name of ['Previous','Pause','Skip','Stop','Shuffle','Loop','Queue','Volume'])assert.ok(buttons.some(b=>b.data.label===name));assert.ok(buttons.every(b=>b.data.custom_id.includes(`:${g}:1:1:`)));});
test('Read-only history does not invent played entries and unavailable playlist mutations preserve saved data',async()=>{const f=fixture({state:playingState()}),history=f.interaction({commandName:'music',options:{getSubcommand:()=> 'history'}});await f.coordinator.handle(history);assert.match(history.replies[0].content,/No playback has been confirmed/);const playlist=f.interaction({commandName:'playlist',options:{getSubcommand:()=> 'delete'}});await f.coordinator.handle(playlist);assert.match(playlist.replies[0].content,/saved playlists are unchanged/);});
