import test from 'node:test';
import assert from 'node:assert/strict';
import {MusicApplication} from '../../dist/apps/bot/src/music/music-application.js';
import {DomainError} from '../../dist/packages/core/src/errors.js';
import {AuthorizedMusicCatalog} from '../../dist/packages/features-music/src/catalog.js';
import {createMusicState,enqueueMusic,recoverMusic,applyMusicRecommendation,controlMusic,voteMusicSkip} from '../../dist/packages/features-music/src/domain.js';
const guildId='111111111111111111',channel='222222222222222222',botId='333333333333333333';
const policy={queueMaxTracks:10,defaultVolume:65,defaultLoop:'off',defaultAutoplay:false};
const track=(id='aaaaaaaaaaa',title='First Song')=>({provider:'youtube',reference:'https://www.youtube.com/watch?v='+id,title,artist:'The Artist',album:null,durationMs:100000,artworkUrl:null,seekable:true});
const flush=async()=>{for(let n=0;n<12;n++)await new Promise(resolve=>setImmediate(resolve));};
function fixture(options={}){
 const calls=[],nodes=[],timers=new Map();let timerId=0,enabled=true,lease=true,refreshFails=false,patchFails=false,voiceChannel=channel,startFails=options.startFails??0,catalogReads=0,searchHook,voiceHook,configHook;
 const actor={guildId,userId:'member',voiceChannelId:channel,textChannelId:channel,eligible:true,isDj:true};let state=createMusicState(guildId,actor,policy).state;
 if(options.playing!==false)state=enqueueMusic(state,actor,[{id:'entry-a',requesterUserId:'member',track:track()}],policy).state;
 if(options.autoplay){state.current=null;state.queue=[];state.desiredStatus='IDLE';state.autoplay=true;state.history=[{id:'old',requesterUserId:'member',track:track()}];}
 let effects=options.autoplay?[{kind:'recommend',after:track()}]:[];
 const publication={ensure:async()=>{calls.push(['publication-ensure']);},publish:async(_client,id)=>{if(!enabled&&!options.allowDisabledPublication)throw Object.assign(Error('Disabled'),{code:'MUSIC_DISABLED'});calls.push(['publish',id]);},cleanup:async(_client,id)=>calls.push(['cleanup',id]),refresh:async(_client,g)=>{calls.push(['publication-refresh',g]);if(options.publicationFails)throw Error('publication failed');}};
 const repo={join:async(request)=>{calls.push(['join-intent',request.requestKey]);},read:async()=>({state:structuredClone(state),controllerMessageId:null}),recover:async(g,key)=>{calls.push(['recover',key]);state=recoverMusic(state).state;},intent:async()=>({obsolete:false,state:structuredClone(state),payload:{revision:state.revision,generation:state.generation,effects}}),ownsIntentLease:async()=>lease,reserveController:async()=>calls.push(['reserve']),requestControllerRefresh:async()=>{calls.push(['refresh-intent']);if(refreshFails)throw Error('database unavailable');},applyTransportEvent:async(request,event)=>{calls.push(['observation',request,event]);return{ignored:false,needsControllerRefresh:true};},recommendation:async(g,key,generation,entry)=>{calls.push(['recommendation',key,entry]);state=applyMusicRecommendation(state,generation,entry).state;}};
 const guild={voiceStates:{fetch:async(id,options)=>{assert.equal(id,botId);assert.equal(options.force,true);await voiceHook?.();return{channelId:voiceChannel};}}};
 const client={user:{id:botId},guilds:{fetch:async request=>{assert.equal(request.guild,guildId);assert.equal(request.force,true);return guild;}}};
 const app=new MusicApplication({client,db:{},config:{get:async(_guild,key)=>{const snapshot=enabled;await configHook?.();return key==='music.enabled'?snapshot:({'music.queue_max_tracks':10,'music.default_volume':65,'music.loop_default':'off','music.autoplay_default':false})[key];}},guildId,wakeMusic:async()=>{calls.push(['wake-worker']);await options.onWake?.();},endpoint:'https://node.example.test/',password:'fixture-private-password',allowInsecureHttp:false,metadataSources:['spotify'],directAudio:options.directAudio??false,access:async()=>({eligible:true,isDj:true})},{repository:repo,publication,now:()=>10000,timers:{set:(callback,delay)=>{const id=++timerId;timers.set(id,{callback,delay});return id;},clear:id=>timers.delete(id)},loadCatalog:async()=>{catalogReads++;if(options.catalogFails)throw Error('private catalog path');return new AuthorizedMusicCatalog([{id:'direct',title:'Direct Song',artist:'Artist',durationMs:100000,authorizedAudioUri:'https://audio.example.test/song.mp3?signature=private-audio',format:'mp3',provenance:{kind:'owner-supplied',reference:'private-proof'},enabled:true,availability:'available'}]);},createGateway:()=>({snapshot:()=>({epoch:'gateway',sequence:0}),subscribe:()=>()=>{},send:async()=>{},shutdown:()=>calls.push(['gateway-close'])}),createVoice:()=>({join:async()=>{calls.push(['voice-join']);return{consume:async work=>work({token:'private-voice-token',sessionId:'private-session',channelId:channel,endpoint:'voice.discord.media'})};},disconnect:async()=>calls.push(['voice-disconnect']),shutdown:()=>calls.push(['voice-close'])}),createNode:nodeOptions=>{
  const number=nodes.length+1;let ready=false;
  const rest={search:async()=>{calls.push(['search',number]);await searchHook?.();return options.recommendations??[track('bbbbbbbbbbb','Second Song')];},resolve:async reference=>({tracks:[track()],truncated:false}),loadPlayableTrack:async metadata=>{calls.push(['resolve-playable',number,metadata.reference]);return{node:number,reference:metadata.reference};},loadCatalogTrack:async id=>{calls.push(['resolve-catalog',number,id]);await nodeOptions.resolveCatalogSource(id);return{node:number,id};},updatePlayer:async(_fence,patch)=>{calls.push(['patch',number,patch]);if(patchFails)throw Error('private HTTP response');return{accepted:true};},destroyPlayer:async()=>({accepted:true}),readPlayer:async()=>({guildId,paused:false,connected:true,positionMs:0,at:10000,track:state.current?{entryId:state.current.id,generation:state.generation}:null})};
  const node={nodeOptions,number,socketEpoch:'node_'+number,get ready(){return ready;},start:async()=>{calls.push(['node-start',number]);if(options.startGate)await options.startGate;if(startFails-->0)throw Error('private node detail');ready=true;},client:()=>rest,close:()=>{calls.push(['node-close',number]);ready=false;}};nodes.push(node);return node;
 }});
 const job=()=>({id:'job-'+state.revision,guildId,jobType:'music.reconcile',executionKey:'job',dueAt:new Date(),status:'RUNNING',attempts:1,leaseToken:'lease'});
 return{app,calls,nodes,timers,repo,job,state:()=>state,setEnabled:value=>enabled=value,setConfigHook:value=>configHook=value,setLease:value=>lease=value,setRefreshFails:value=>refreshFails=value,setPatchFails:value=>patchFails=value,setVoice:value=>voiceChannel=value,setVoiceHook:value=>voiceHook=value,setEffects:value=>effects=value,setSearchHook:value=>searchHook=value,catalogReads:()=>catalogReads,mutate:work=>work(state),async fireTimer(){const first=timers.entries().next().value;assert.ok(first,'A bounded retry must be scheduled.');timers.delete(first[0]);first[1].callback();await flush();return first[1].delay;}};
}
test('concurrent starts share one fresh multi-source session and never require the optional catalog',async()=>{const f=fixture({catalogFails:true});try{await Promise.all([f.app.start(),f.app.start(),f.app.start()]);assert.equal(f.nodes.length,1);assert.equal(f.calls.filter(c=>c[0]==='recover').length,1);assert.equal(f.app.ready,true);assert.equal(f.catalogReads(),0);assert.equal(f.nodes[0].nodeOptions.sourcePolicy.mode,'multi-source');assert.equal(f.nodes[0].nodeOptions.sourcePolicy.catalog,false);assert.equal('resolveCatalogSource'in f.nodes[0].nodeOptions,false);assert.doesNotMatch(JSON.stringify(f.app),/private|password|token/);}finally{f.app.close();}});
test('disabled application starts no node and publication jobs cannot bypass guild/feature scope',async()=>{const f=fixture();f.setEnabled(false);await assert.rejects(f.app.start(),{code:'MUSIC_DISABLED'});await assert.rejects(f.app.publish(f.job()),{code:'MUSIC_DISABLED'});await f.app.cleanup(f.job());assert.ok(f.calls.some(c=>c[0]==='cleanup'));f.setEnabled(true);await assert.rejects(f.app.refresh({...f.job(),guildId:'other'}),{code:'MUSIC_DISABLED'});assert.equal(f.nodes.length,0);f.app.close();});
test('disabled Music still delegates receipt reconciliation and obsolete cleanup without opening audio',async()=>{const f=fixture({allowDisabledPublication:true});f.setEnabled(false);await f.app.publish(f.job());await f.app.cleanup(f.job());assert.deepEqual(f.calls.map(c=>c[0]),['publish','cleanup']);assert.equal(f.nodes.length,0);await assert.rejects(f.app.publish({...f.job(),guildId:'other'}),{code:'MUSIC_DISABLED'});f.app.close();await assert.rejects(f.app.cleanup(f.job()),{code:'MUSIC_DISABLED'});});
test('source handles are freshly resolved after node failure and stale callbacks cannot retire a newer session',async()=>{const f=fixture();try{await f.app.start();await f.app.reconcile(f.job());await f.app.reconcile(f.job());assert.equal(f.calls.filter(c=>c[0]==='resolve-playable').length,1);const old=f.nodes[0];old.nodeOptions.onUnavailable('NODE_LOST');assert.equal(f.app.ready,false);assert.equal(await f.fireTimer(),1000);assert.equal(f.nodes.length,2);assert.equal(f.app.ready,true);await f.app.reconcile(f.job());assert.deepEqual(f.calls.filter(c=>c[0]==='resolve-playable').map(c=>c[1]),[1,2]);const observations=f.calls.filter(c=>c[0]==='observation').length;await old.nodeOptions.onEvent({kind:'trackStart',guildId,entryId:'entry-a',generation:f.state().generation},{socketEpoch:old.socketEpoch,sequence:99});old.nodeOptions.onUnavailable('STALE_CLOSE');assert.equal(f.app.ready,true);assert.equal(f.calls.filter(c=>c[0]==='observation').length,observations);assert.equal(f.calls.filter(c=>c[0]==='recover').length,2);}finally{f.app.close();}});
test('uncertain player writes retire the whole node session instead of retrying its encoded handle',async()=>{const f=fixture();try{await f.app.start();f.setPatchFails(true);await assert.rejects(f.app.reconcile(f.job()),{code:'MUSIC_SYNC_RECOVERY_REQUIRED'});assert.equal(f.app.ready,false);assert.equal(f.calls.filter(c=>c[0]==='patch').length,1);f.setPatchFails(false);await f.fireTimer();await f.app.reconcile(f.job());assert.deepEqual(f.calls.filter(c=>c[0]==='resolve-playable').map(c=>c[1]),[1,2]);}finally{f.app.close();}});
test('startup failure is sanitized and reconnect backoff creates a new session',async()=>{const f=fixture({startFails:1});try{await assert.rejects(f.app.start(),error=>error.code==='MUSIC_NODE'&&!error.message.includes('private'));assert.equal(f.app.ready,false);assert.equal(await f.fireTimer(),1000);assert.equal(f.app.ready,true);assert.equal(f.nodes.length,2);f.nodes[1].nodeOptions.onUnavailable('FLAP');assert.equal(await f.fireTimer(),2000);}finally{f.app.close();}});
test('shutdown during initialization never becomes ready, reconnects, or sends playback afterward',async()=>{let release;const gate=new Promise(resolve=>release=resolve),f=fixture({startGate:gate}),starting=f.app.start();await flush();assert.equal(f.nodes.length,1);f.app.close();release();await assert.rejects(starting,{code:'MUSIC_NODE'});assert.equal(f.app.ready,false);assert.equal(f.timers.size,0);assert.equal(f.calls.some(c=>c[0]==='patch'),false);await assert.rejects(f.app.start(),{code:'MUSIC_CLOSED'});});
test('controller refresh persistence failure retries presentation without destroying healthy audio',async()=>{const f=fixture({publicationFails:true});try{await f.app.start();f.setRefreshFails(true);await f.nodes[0].nodeOptions.onEvent({kind:'trackStart',guildId,entryId:'entry-a',generation:f.state().generation},{socketEpoch:'node_1',sequence:1});assert.equal(f.app.ready,true);assert.equal(f.calls.some(c=>c[0]==='publication-refresh'),false);assert.equal(f.calls.some(c=>c[0]==='node-close'),false);f.setRefreshFails(false);assert.equal(await f.fireTimer(),5000);assert.equal(await f.fireTimer(),5000);assert.ok(f.calls.filter(c=>c[0]==='refresh-intent').length>=2);await assert.rejects(f.app.refresh({...f.job(),jobType:'music.controller.refresh'}),/publication failed/);assert.equal(f.app.ready,true);}finally{f.app.close();}});
test('optional direct audio loads only on demand and passes a stable catalog ID to the transport',async()=>{const f=fixture({directAudio:true});try{f.mutate(state=>{state.current.track={...state.current.track,provider:'authorized_catalog',reference:'catalog:direct'};});await f.app.start();assert.equal(f.catalogReads(),0);await f.app.reconcile(f.job());assert.equal(f.catalogReads(),1);assert.deepEqual(f.calls.find(c=>c[0]==='resolve-catalog').slice(1),[1,'direct']);}finally{f.app.close();}});
test('listener departure refreshes presentation; bot departure or move fails closed without an invented idle timer',async()=>{for(const departure of [null,'444444444444444444']){const f=fixture();try{await f.app.start();await f.app.voiceChanged(guildId,'listener');assert.equal(f.app.ready,true);assert.equal(f.calls.some(c=>c[0]==='refresh-intent'),true);f.setVoice(departure);await f.app.voiceChanged(guildId,botId);assert.equal(f.app.ready,false);assert.equal(f.calls.find(c=>c[0]==='observation')[2].status,'FAILED');assert.equal(f.state().current.id,'entry-a');assert.equal(f.timers.size,0);await assert.rejects(f.app.reconcile(f.job()),{code:'MUSIC_VOICE_REMOVED'});f.mutate(state=>state.revision++);f.setEffects([{kind:'connect',voiceChannelId:channel}]);f.setVoice(channel);await f.app.reconcile(f.job());assert.equal(f.app.ready,true);}finally{f.app.close();}}});
test('concurrent relocation or stale observation cannot retire the healthy current session',async()=>{const f=fixture();try{await f.app.start();const moved='444444444444444444';f.setVoice(moved);f.setVoiceHook(()=>f.mutate(state=>{state.voiceChannelId=moved;state.textChannelId=moved;state.revision++;}));await f.app.voiceChanged(guildId,botId);assert.equal(f.app.ready,true);assert.equal(f.calls.some(c=>c[0]==='observation'),false);f.setVoiceHook(undefined);f.setVoice(null);f.repo.applyTransportEvent=async()=>{throw new DomainError('MUSIC_STALE','Concurrent player change.');};await f.app.voiceChanged(guildId,botId);assert.equal(f.app.ready,true);assert.equal(f.calls.some(c=>c[0]==='node-close'),false);assert.deepEqual([...f.timers.values()].map(timer=>timer.delay),[5000]);}finally{f.app.close();}});
test('autoplay accepts only bounded filtered recommendations and persists them as generation-fenced system entries',async()=>{const f=fixture({autoplay:true,recommendations:[track(),{...track('ccccccccccc','Unrelated Song'),artist:'Another Artist'},track('bbbbbbbbbbb','Second Song')]});try{await f.app.start();await f.app.reconcile(f.job());const recommendation=f.calls.find(c=>c[0]==='recommendation');assert.ok(recommendation);assert.equal(recommendation[2].requesterUserId,null);assert.equal(recommendation[2].track.title,'Second Song');assert.equal(f.state().current.track.title,'Second Song');assert.equal(f.calls.filter(c=>c[0]==='recommendation').length,1);}finally{f.app.close();}});
test('a concurrent member request or lost lease prevents a late autoplay candidate from entering the queue',async()=>{for(const mode of ['member','lease']){const f=fixture({autoplay:true});try{await f.app.start();let changed=false;f.setSearchHook(async()=>{if(changed)return;changed=true;if(mode==='member')f.mutate(state=>{state.revision++;state.generation++;state.current={id:'member-request',requesterUserId:'member',track:track('ddddddddddd','Member Song')};state.desiredStatus='PLAYING';});else f.setLease(false);});if(mode==='lease')await assert.rejects(f.app.reconcile(f.job()),{code:'MUSIC_LEASE'});else await f.app.reconcile(f.job());assert.equal(f.calls.some(c=>c[0]==='recommendation'),false);}finally{f.app.close();}}});
test('disabling active Music retires transport within the bounded check and re-enable creates a fresh recoverable session',async()=>{const f=fixture();try{await f.app.start();await f.app.reconcile(f.job());f.setEnabled(false);assert.equal(await f.fireTimer(),5000);assert.equal(f.app.ready,false);assert.equal(f.nodes[0].ready,false);assert.equal(f.timers.size,0);assert.equal(f.state().current.id,'entry-a');await assert.rejects(f.app.start(),{code:'MUSIC_DISABLED'});assert.equal(f.nodes.length,1);assert.equal(f.timers.size,0);f.setEnabled(true);await f.app.start();await f.app.reconcile(f.job());assert.equal(f.app.ready,true);assert.equal(f.nodes.length,2);assert.deepEqual(f.calls.filter(c=>c[0]==='resolve-playable').map(c=>c[1]),[1,2]);}finally{f.app.close();assert.equal(f.timers.size,0);}});
test('an old pending disabled-state check cannot retire its replacement node; config-read failure fails closed',async()=>{const f=fixture();try{await f.app.start();f.setEnabled(false);let release;const gate=new Promise(resolve=>release=resolve);f.setConfigHook(()=>gate);await f.fireTimer();f.nodes[0].nodeOptions.onUnavailable('CONNECTION_LOST');f.setConfigHook(undefined);f.setEnabled(true);await f.app.start();release();await flush();assert.equal(f.app.ready,true);assert.equal(f.nodes.length,2);f.setConfigHook(()=>Promise.reject(Error('private configuration diagnostic')));await f.fireTimer();assert.equal(f.app.ready,false);assert.equal(f.timers.size,0);}finally{f.app.close();}});

test('Unknown bot voice state retires the accepted cursor and explicit join establishes a fresh voice payload',async()=>{
 const f=fixture();try{await f.app.start();await f.app.reconcile(f.job());assert.equal(f.calls.filter(c=>c[0]==='voice-join').length,1);
 f.setVoiceHook(()=>{throw Object.assign(Error('private'),{code:10065});});await f.app.voiceChanged(guildId,botId);assert.equal(f.app.ready,false);assert.equal(f.calls.find(c=>c[0]==='observation')[2].status,'FAILED');await assert.rejects(f.app.reconcile(f.job()),{code:'MUSIC_VOICE_REMOVED'});
 f.setVoiceHook(undefined);f.setVoice(channel);f.mutate(state=>state.revision++);f.setEffects([{kind:'connect',voiceChannelId:channel}]);await f.app.reconcile(f.job());assert.equal(f.app.ready,true);assert.equal(f.calls.filter(c=>c[0]==='voice-join').length,2);
 }finally{f.app.close();}
});
test('Other voice API failures do not fabricate a confirmed departure',async()=>{const f=fixture();try{await f.app.start();f.setVoiceHook(()=>{throw Object.assign(Error('unavailable'),{code:50013});});await assert.rejects(f.app.voiceChanged(guildId,botId),{code:50013});assert.equal(f.app.ready,true);assert.equal(f.calls.some(c=>c[0]==='observation'),false);}finally{f.app.close();}});


test('production composition persists a distinct voice intent and wakes the worker before resolving /play',async()=>{
 const f=fixture({playing:false}),member={user:{id:'member',bot:false},isCommunicationDisabled:()=>false,permissionsIn:()=>({has:()=>true})},replies=[];
 const interaction={id:'request',guildId,channelId:channel,user:{id:'member'},guild:{channels:{fetch:async()=>({id:channel,type:2})},members:{fetch:async()=>member},voiceStates:{fetch:async()=>({channelId:channel})}},deferReply:async()=>{},editReply:async payload=>replies.push(payload),reply:async payload=>replies.push(payload),isChatInputCommand:()=>true,isStringSelectMenu:()=>false,isButton:()=>false,commandName:'play',options:{getString:()=>{f.calls.push(['read-query']);return'https://soundcloud.com/kr3ture/watch-it-grow';}}};
 try{await f.app.coordinator.handle(interaction);assert.ok(f.calls.findIndex(c=>c[0]==='recover')<f.calls.findIndex(c=>c[0]==='join-intent'),'fresh node recovery must finish before the immediate join intent is persisted');assert.deepEqual(f.calls.filter(c=>['join-intent','wake-worker','read-query'].includes(c[0])),[['join-intent','request:voice'],['wake-worker'],['read-query']]);}finally{f.app.close();}
});

test('Coordinator Pause Resume Skip Stop wake leased transport and repaint the shared player',async()=>{
 for(const action of ['pause','resume','skip','stop']){const options={},f=fixture(options),replies=[];try{
  await f.app.start();if(action==='resume')f.mutate(state=>{state.desiredStatus='PAUSED';});if(action==='skip')f.mutate(state=>{state.queue=[{id:'entry-b',requesterUserId:'member',track:track('bbbbbbbbbbb','Second Song')}];});await f.app.reconcile(f.job());f.calls.length=0;
  f.repo.control=async(request,revision,operation)=>{assert.equal(revision,f.state().revision);const transition=controlMusic(f.state(),request.actor,operation);f.mutate(state=>Object.assign(state,transition.state));f.calls.push(['saved-control',operation.kind]);};
  f.repo.skip=async(request,generation,listeners)=>{assert.equal(generation,f.state().generation);const transition=voteMusicSkip(f.state(),request.actor,listeners);f.mutate(state=>Object.assign(state,transition.state));f.calls.push(['saved-control','skip']);return transition;};
  options.onWake=()=>f.app.reconcile(f.job());const read=f.repo.read;f.repo.read=async()=>({...await read(),controllerMessageId:'555555555555555555'});
  const member={id:'member',user:{id:'member',bot:false},isCommunicationDisabled:()=>false,permissionsIn:()=>({has:()=>true})};let acknowledged=false;
  const interaction={id:'control-'+action,guildId,channelId:channel,user:{id:'member'},guild:{channels:{fetch:async()=>{assert.equal(acknowledged,true);return{id:channel,type:2};}},members:{fetch:async()=>member},voiceStates:{cache:new Map([['member',{id:'member',channelId:channel}]]),fetch:async()=>({channelId:channel})}},deferred:false,deferReply:async function(input){assert.equal(input.ephemeral,true);acknowledged=true;this.deferred=true;},editReply:async payload=>replies.push(payload),isChatInputCommand:()=>false,isStringSelectMenu:()=>false,isButton:()=>true,customId:'music:control:'+guildId+':'+f.state().revision+':'+f.state().generation+':'+action+':public:p=publication',client:{user:{id:botId}},message:{id:'555555555555555555',author:{id:botId},flags:{has:()=>false}},commandName:'music',options:{getSubcommand:()=>action}};
  await f.app.coordinator.handle(interaction);assert.ok(f.calls.find(c=>c[0]==='saved-control'),action);assert.ok(f.calls.find(c=>c[0]==='wake-worker'),action);assert.ok(f.calls.find(c=>c[0]==='publication-ensure'),action);
  const patch=f.calls.find(c=>c[0]==='patch')?.[2];if(action==='pause'||action==='resume')assert.equal(patch.paused,action==='pause');if(action==='skip')assert.equal(patch.entryId,'entry-b');if(action==='stop'){assert.equal(f.state().current,null);assert.ok(patch?.track===null||f.calls.some(c=>c[0]==='voice-disconnect'));}assert.equal(replies.at(-1).files.length,0);
 }finally{f.app.close();}}
});
