import test from 'node:test';import assert from 'node:assert/strict';
import {MusicRuntime} from '../../dist/apps/bot/src/music/music-runtime.js';
const g='111111111111111111',channel='222222222222222222';
function fixture(){const state={guildId:g,voiceChannelId:channel,textChannelId:channel,revision:2,generation:3,current:{id:'entry',requesterUserId:'member',track:{provider:'youtube',reference:'public',title:'Track',artist:'Artist',album:null,durationMs:100000,artworkUrl:null,seekable:true}},queue:[],history:[],desiredStatus:'PLAYING',observedStatus:'RECOVERING',observedGeneration:3,positionMs:0,observedAt:null,volume:50,loop:'off',autoplay:false,queueMaxTracks:100,skipVotes:{generation:3,voterIds:[]},lastError:null};const mutations=[],calls=[];let lease=true,enabled=true,observation={guildId:g,paused:false,connected:true,positionMs:100,at:2000,track:{entryId:'entry',generation:3}};const repo={read:async()=>({state:structuredClone(state),controllerMessageId:null}),intent:async()=>({obsolete:false,state:structuredClone(state)}),ownsIntentLease:async()=>lease,applyTransportEvent:async(r,e)=>{mutations.push({r,e});return{ignored:false,needsControllerRefresh:true};},recover:async(...args)=>calls.push(['recover',...args]),reserveController:async()=>calls.push(['reserve'])};const options={repository:repo,socketEpoch:'epoch',synchronize:async()=>{calls.push(['sync']);},readPlayer:async()=>{calls.push(['read']);return observation;},enabled:async()=>enabled,refreshController:async()=>calls.push(['refresh']),now:()=>1000};const runtime=new MusicRuntime(options);return{runtime,options,repo,state,mutations,calls,setLease:v=>lease=v,setEnabled:v=>enabled=v,setObservation:v=>observation=v};}
const job={id:'job',guildId:g,jobType:'music.reconcile',executionKey:'intent',dueAt:new Date(),status:'RUNNING',attempts:1,leaseToken:'lease'};
const start={kind:'trackStart',guildId:g,entryId:'entry',generation:3};
test('Playback trace requires a current correlated and persisted TrackStart event',async t=>{
 const traces=[];t.mock.method(console,'info',message=>traces.push(message));const f=fixture();
 await f.runtime.reconcile(job);assert.match(traces.shift(),/transport.wait/);await f.runtime.event(start,{socketEpoch:'old',sequence:1});await f.runtime.event({...start,generation:2},{socketEpoch:'epoch',sequence:2});assert.deepEqual(traces,[]);
 f.repo.applyTransportEvent=async()=>({ignored:true,needsControllerRefresh:false});await f.runtime.event(start,{socketEpoch:'epoch',sequence:3});assert.deepEqual(traces,[]);
 f.repo.applyTransportEvent=async()=>({ignored:false,needsControllerRefresh:false});await f.runtime.event(start,{socketEpoch:'epoch',sequence:4});assert.deepEqual(traces,['Music trace: playback.started '+JSON.stringify({guildId:g,channelId:channel})]);
});
test('Playback exception and end traces require accepted current persisted events',async t=>{
 const traces=[];t.mock.method(console,'info',message=>traces.push(message));const f=fixture(),exception={...start,kind:'trackException',error:'PLAYABLE_SOURCE_FAILED'},ended={...start,kind:'trackEnd',reason:'loadFailed'};
 await f.runtime.event({...exception,generation:2},{socketEpoch:'epoch',sequence:1});assert.deepEqual(traces,[]);
 f.repo.applyTransportEvent=async()=>({ignored:true,needsControllerRefresh:false});await f.runtime.event(exception,{socketEpoch:'epoch',sequence:2});await f.runtime.event(ended,{socketEpoch:'epoch',sequence:3});assert.deepEqual(traces,[]);
 f.repo.applyTransportEvent=async()=>({ignored:false,needsControllerRefresh:false});await f.runtime.event(exception,{socketEpoch:'epoch',sequence:4});await f.runtime.event(ended,{socketEpoch:'epoch',sequence:5});assert.deepEqual(traces.map(line=>line.split(' ')[2]),['playback.exception','playback.ended']);assert.ok(traces.every(line=>line.endsWith(JSON.stringify({guildId:g,channelId:channel}))));
});
test('Player read diagnostics deduplicate the same failure and fence and reset after a successful read',async t=>{
 const traces=[];t.mock.method(console,'info',message=>{if(message.includes('player.read.failure'))traces.push(message);});const f=fixture(),successful=f.options.readPlayer,fail=async()=>{throw Error('SECRET_TOKEN https://private-player');};f.options.readPlayer=fail;
 await f.runtime.reconcile(job);await f.runtime.reconcile(job);assert.equal(traces.length,1);
 f.state.revision++;await f.runtime.reconcile(job);assert.equal(traces.length,2);
 f.options.readPlayer=successful;await f.runtime.reconcile(job);f.options.readPlayer=fail;await f.runtime.reconcile(job);assert.equal(traces.length,3);assert.ok(traces.every(line=>line.includes('player.read.failure')));assert.doesNotMatch(traces.join('\n'),/SECRET|private-player|https:|token|sessionId/);
 f.runtime.close();await assert.rejects(f.runtime.reconcile(job),{code:'MUSIC_DISABLED'});assert.equal(traces.length,3);
});
test('no active job grants mutation authority; reconciliation requires the shared live lease',async()=>{const f=fixture();assert.equal(await f.runtime.isCurrent({guildId:g,revision:2,generation:3}),false);f.setLease(false);await assert.rejects(f.runtime.reconcile(job),{code:'MUSIC_LEASE'});assert.deepEqual(f.calls,[]);});
test('REST acknowledgement and connected telemetry alone cannot manufacture playback history',async()=>{const f=fixture();await f.runtime.reconcile(job);assert.ok(f.calls.some(c=>c[0]==='sync'));assert.deepEqual(f.mutations,[]);await f.runtime.event({kind:'playerUpdate',guildId:g,positionMs:100,at:2000,connected:true},{socketEpoch:'epoch',sequence:1});assert.deepEqual(f.mutations,[]);});
test('correlated start establishes binding; pause telemetry is read and applied separately',async()=>{const f=fixture();f.setObservation({guildId:g,paused:true,connected:true,positionMs:100,at:2000,track:{entryId:'entry',generation:3}});await f.runtime.event(start,{socketEpoch:'epoch',sequence:1});assert.equal(f.mutations[0].e.kind,'track-start');assert.equal(f.mutations[1].e.status,'PAUSED');assert.notEqual(f.mutations[0].r.socketEpoch,f.mutations[1].r.socketEpoch);});
test('old sockets, wrong recordings and old generations are ignored',async()=>{const f=fixture();await f.runtime.event(start,{socketEpoch:'old',sequence:1});await f.runtime.event({...start,entryId:'other'},{socketEpoch:'epoch',sequence:2});await f.runtime.event({...start,generation:2},{socketEpoch:'epoch',sequence:3});assert.deepEqual(f.mutations,[]);});
test('mismatched player telemetry cannot overwrite the bound selected recording',async()=>{const f=fixture();f.setObservation({guildId:g,paused:false,connected:true,positionMs:100,at:2000,track:{entryId:'other',generation:3}});await f.runtime.event(start,{socketEpoch:'epoch',sequence:1});assert.equal(f.mutations.length,1);assert.equal(f.mutations[0].e.kind,'track-start');});
test('events wait behind reconciliation and cannot race its external effects',async()=>{const f=fixture();let release,entered;const started=new Promise(r=>entered=r);f.options.synchronize=async()=>{entered();await new Promise(r=>release=r);};const reconcile=f.runtime.reconcile(job);await started;const event=f.runtime.event(start,{socketEpoch:'epoch',sequence:1});await new Promise(r=>setImmediate(r));assert.equal(f.mutations.length,0);release();await reconcile;await event;assert.equal(f.mutations[0].e.kind,'track-start');});
test('recovery retires bindings and writes one epoch-keyed recovery request without asserting audio',async()=>{const f=fixture();await f.runtime.recover(g);assert.deepEqual(f.calls,[['recover',g,'node-epoch',true]]);assert.deepEqual(f.mutations,[]);});
test('disabled or closed runtime performs no event writes or transport mutations',async()=>{const f=fixture();f.setEnabled(false);await f.runtime.event(start,{socketEpoch:'epoch',sequence:1});await assert.rejects(f.runtime.reconcile(job),{code:'MUSIC_DISABLED'});f.setEnabled(true);f.runtime.close();await f.runtime.event(start,{socketEpoch:'epoch',sequence:2});assert.deepEqual(f.calls,[]);assert.deepEqual(f.mutations,[]);});
test('disconnect becomes observed only after the voice boundary confirms gateway departure',async()=>{const f=fixture();f.state.current=null;f.state.desiredStatus='DISCONNECTED';await f.runtime.reconcile(job);assert.equal(f.mutations.length,0);f.options.synchronize=async()=>({accepted:true,changed:true,voiceDisconnected:true});await f.runtime.reconcile(job);assert.equal(f.mutations[0].e.status,'DISCONNECTED');});

test('Departure inspection waits for in-flight reconciliation instead of losing the gateway update',async()=>{
 const f=fixture();let release,entered;const ready=new Promise(r=>{entered=r;});f.options.synchronize=async()=>{entered();await new Promise(r=>{release=r;});};const work=f.runtime.reconcile(job);await ready;let inspected=false;const after=f.runtime.afterCurrentWork(g,async()=>{inspected=true;assert.equal(await f.runtime.isCurrent({guildId:g,revision:2,generation:3}),false);});await Promise.resolve();assert.equal(inspected,false);release();await work;await after;assert.equal(inspected,true);f.runtime.close();
});

test('Progress refreshes coalesce to fifteen seconds while explicit Refresh reads latest telemetry',async()=>{
 const f=fixture();let now=1000;f.options.now=()=>now;await f.runtime.event(start,{socketEpoch:'epoch',sequence:1});f.calls.length=0;
 const update=sequence=>f.runtime.event({kind:'playerUpdate',guildId:g,positionMs:now,at:now,connected:true},{socketEpoch:'epoch',sequence});
 await update(2);now=5000;await update(3);now=15999;await update(4);assert.equal(f.calls.filter(c=>c[0]==='refresh').length,1);now=16000;await update(5);assert.equal(f.calls.filter(c=>c[0]==='refresh').length,2);
 const reads=f.calls.filter(c=>c[0]==='read').length;await f.runtime.refresh(g);assert.equal(f.calls.filter(c=>c[0]==='read').length,reads+1);f.runtime.close();await f.runtime.refresh(g);assert.equal(f.calls.filter(c=>c[0]==='read').length,reads+1);
});
