import test from 'node:test';import assert from 'node:assert/strict';
import {MusicPlayerSynchronizer} from '../../dist/apps/bot/src/music/player-synchronizer.js';
const state=()=>({guildId:'111111111111111111',voiceChannelId:'222222222222222222',textChannelId:'222222222222222222',revision:1,generation:1,current:{id:'entry-1',requesterUserId:'333333333333333333',track:{provider:'youtube',reference:'https://www.youtube.com/watch?v=aaaaaaaaaaa',title:'Fixture',artist:'Artist',album:null,durationMs:180000,artworkUrl:null,seekable:true}},queue:[],history:[],desiredStatus:'PLAYING',observedStatus:'RECOVERING',observedGeneration:1,positionMs:0,observedAt:null,volume:50,loop:'off',autoplay:false,queueMaxTracks:100,skipVotes:{generation:1,voterIds:[]},lastError:null});
test('Player write traces report acknowledgement separately from playback and redact failures',async t=>{
 const traces=[];t.mock.method(console,'info',message=>traces.push(message));const ready=setup();await ready.sync.synchronize(state());
 assert.deepEqual(traces.map(line=>line.split(' ')[2]),['track.load.start','track.load.success','track.handoff','player.update.start','player.update.success']);traces.length=0;
 const failed=setup({client:{updatePlayer:async()=>{throw new TypeError('private-token private-session encoded-track https://private-audio');}}});await assert.rejects(failed.sync.synchronize(state()),{code:'MUSIC_SYNC_RECOVERY_REQUIRED'});
 assert.deepEqual(traces.map(line=>line.split(' ')[2]),['track.load.start','track.load.success','track.handoff','player.update.start','player.update.failure']);assert.doesNotMatch(traces.join('\n'),/private-|encoded-track|https:|playback.started|sessionId|token|endpoint/);
});
test('Source load failure emits a sanitized stage before any voice or player write',async t=>{
 const traces=[];t.mock.method(console,'info',message=>traces.push(message));const f=setup({resolve:async()=>{throw Error('SECRET_ENCODED https://private-stream?token=SECRET');}});
 await assert.rejects(f.sync.synchronize(state()),{code:'MUSIC_SYNC_UNAVAILABLE'});assert.deepEqual(f.calls,[]);assert.deepEqual(traces.map(line=>line.split(' ')[2]),['track.load.start','track.load.failure']);assert.doesNotMatch(traces.join('\n'),/SECRET|private-stream|https:|token|sessionId/);
});
function setup(overrides={}){const calls=[];const client={updatePlayer:async(f,p)=>{calls.push(['patch',structuredClone(f),p]);return{accepted:true};},destroyPlayer:async()=>{calls.push(['destroy']);return{accepted:true};},...overrides.client};const voice={join:async()=>{calls.push(['join']);return{consume:async fn=>fn({token:'private-token',sessionId:'private-session',endpoint:'fixture.discord.media',channelId:state().voiceChannelId})};},disconnect:async()=>{calls.push(['disconnect']);},...overrides.voice};const resolve=overrides.resolve??(async track=>{calls.push(['resolve',track.reference]);return Object.freeze({});});return{calls,sync:new MusicPlayerSynchronizer(client,voice,overrides.current??(async()=>true),resolve)};}
test('fresh session resolves a fresh opaque capability and returns acknowledgement only',async()=>{const f=setup();assert.deepEqual(await f.sync.synchronize(state()),{accepted:true,changed:true});assert.deepEqual(f.calls.map(c=>c[0]),['resolve','join','patch']);assert.equal(f.calls[2][2].entryId,'entry-1');assert.ok(!JSON.stringify(f.sync).includes('private'));});
test('queue and telemetry revisions never restart or seek the current track',async()=>{const f=setup(),s=state();await f.sync.synchronize(s);f.calls.length=0;s.revision++;s.positionMs=30000;s.queue.push({...s.current,id:'queued'});assert.deepEqual(await f.sync.synchronize(s),{accepted:true,changed:false});assert.deepEqual(f.calls,[]);});
test('pause and volume patch only changed controls; replay generation resolves anew',async()=>{const f=setup(),s=state();await f.sync.synchronize(s);f.calls.length=0;s.revision++;s.desiredStatus='PAUSED';s.volume=30;await f.sync.synchronize(s);assert.deepEqual(f.calls[0][2],{paused:true,volume:30});f.calls.length=0;s.revision++;s.generation++;s.positionMs=45000;await f.sync.synchronize(s);assert.deepEqual(f.calls.map(c=>c[0]),['resolve','patch']);assert.equal(f.calls[1][2].position,45000);});
test('idle clears track; disconnect deletes existing node player before voice leave',async()=>{const f=setup(),s=state();await f.sync.synchronize(s);f.calls.length=0;s.revision++;s.generation++;s.current=null;s.desiredStatus='IDLE';await f.sync.synchronize(s);assert.equal(f.calls[0][2].track,null);f.calls.length=0;s.revision++;s.generation++;s.desiredStatus='DISCONNECTED';await f.sync.synchronize(s);assert.deepEqual(f.calls.map(c=>c[0]),['destroy','disconnect']);});
test('source failure before a write permits fresh resolution without poisoning the session',async()=>{let attempts=0;const f=setup({resolve:async()=>{if(++attempts===1)throw Error('secret stream URI');return{};}});await assert.rejects(f.sync.synchronize(state()),{code:'MUSIC_SYNC_UNAVAILABLE'});assert.equal((await f.sync.synchronize(state())).accepted,true);assert.equal(attempts,2);});
test('uncertain write never retries against the same session or leaks its underlying error',async()=>{const f=setup({client:{updatePlayer:async()=>{throw Error('private-token');}}});await assert.rejects(f.sync.synchronize(state()),e=>e.code==='MUSIC_SYNC_RECOVERY_REQUIRED'&&!e.message.includes('private-token'));f.calls.length=0;await assert.rejects(f.sync.synchronize({...state(),revision:2}),{code:'MUSIC_SYNC_RECOVERY_REQUIRED'});assert.deepEqual(f.calls,[]);});
test('fresh fence checks prevent stale resolver results from reaching voice or player mutation',async()=>{let current=true;const f=setup({current:async()=>current,resolve:async()=>{current=false;return{};}});await assert.rejects(f.sync.synchronize(state()),{code:'MUSIC_SYNC_STALE'});assert.deepEqual(f.calls,[]);});
test('shutdown stops new work and a new session re-resolves instead of reusing prior capabilities',async()=>{const first=setup();await first.sync.synchronize(state());first.sync.close();await assert.rejects(first.sync.synchronize(state()),{code:'MUSIC_SYNC_CLOSED'});const second=setup();await second.sync.synchronize({...state(),generation:2,revision:2});assert.equal(second.calls[0][0],'resolve');});
