import test from 'node:test';
import assert from 'node:assert/strict';
import {Collection,PermissionFlagsBits} from 'discord.js';
import {notificationRole,notificationMessage,normalizeNotificationTrigger} from '../../dist/apps/bot/src/discord/notification-roles.js';
import {DiscordSpecialCoordinator} from '../../dist/apps/bot/src/discord/special-coordinator.js';
import {DiscordEventsCoordinator} from '../../dist/apps/bot/src/discord/events-coordinator.js';
const g='111111111111111111',roleId='222222222222222222',main='333333333333333333',memberId='444444444444444444',bot='555555555555555555',triggerId='666666666666666666';
const safeRole={id:roleId,mentionable:true,managed:false,permissions:{bitfield:0n}};
const defaults={'features.special_commands':true,'special_commands.enabled':true,'features.line':true,'features.race':true,'channels.main_chat':main,'channels.games_channel':main,'channels.bot_channel':main,'special_commands.custom_commands':[],'special_commands.access_roles':{'!line':[],'!race':[],'!vc':[],'!chess':[]},'special_commands.builtin_role_map':{'!line':roleId,'!race':roleId,'!vc':roleId,'!chess':roleId},'special_commands.builtin_response_pools':{'!line':['Gather once.'],'!vc':['Voice invitation.'],'!chess':['Chess invitation.']}};
const config=(patch={})=>({get:async(_g,key)=>({...defaults,...patch})[key]??null});
function guildFixture(role=safeRole,canMention=false){const calls=[];return{calls,id:g,roles:{fetch:async(id,options)=>{calls.push(['role',id,options]);return role;}},members:{fetchMe:async options=>{calls.push(['bot',options]);return{id:bot};}},channels:{fetch:async(id,options)=>{calls.push(['channel',id,options]);return{permissionsFor:()=>({has:permission=>{assert.equal(permission,PermissionFlagsBits.MentionEveryone);return canMention;}})};}}};}
const texts=payload=>{const visit=components=>components.flatMap(raw=>{const c=raw.toJSON?.()??raw;return[...(c.type===10?[c.content]:[]),...(c.components?visit(c.components):[])];});return visit(payload.components??[]).join('\n');};

test('built-in VC and Chess case aliases leave Line, Race and custom matching untouched',()=>{for(const v of ['!VC','!vc','!vC'])assert.equal(normalizeNotificationTrigger(v),'!vc');for(const v of ['!Chess','!CHESS','!chess'])assert.equal(normalizeNotificationTrigger(v),'!chess');for(const v of ['!Line','!RACE','!Custom','!VC extra'])assert.equal(normalizeNotificationTrigger(v),v);});
test('role lookup bypasses cache and globally mentionable opt-in roles need no elevated mention permission',async()=>{const guild=guildFixture();assert.equal(await notificationRole(guild,main,roleId,config()),roleId);assert.deepEqual(guild.calls,[['role',roleId,{force:true}]]);});
test('nonmentionable roles use actual fresh channel permission without mutating role or channel',async()=>{for(const permission of [true,false]){const guild=guildFixture({...safeRole,mentionable:false},permission);if(permission)assert.equal(await notificationRole(guild,main,roleId,config()),roleId);else await assert.rejects(notificationRole(guild,main,roleId,config()),{code:'NOTIFICATION_PERMISSION'});assert.deepEqual(guild.calls,[['role',roleId,{force:true}],['bot',{force:true}],['channel',main,{force:true}]]);}});
test('missing, managed, permission-bearing, everyone and mapped protected roles fail closed',async()=>{for(const [role,patch,id,code]of [[null,{},roleId,'NOTIFICATION_ROLE'],[{...safeRole,managed:true},{},roleId,'NOTIFICATION_ROLE_UNSAFE'],[{...safeRole,permissions:{bitfield:8n}},{},roleId,'NOTIFICATION_ROLE_UNSAFE'],[{...safeRole,id:g},{},g,'NOTIFICATION_ROLE_UNSAFE'],[safeRole,{'roles.throne':roleId},roleId,'NOTIFICATION_ROLE_UNSAFE'],[safeRole,{'roles.member_access':roleId},roleId,'NOTIFICATION_ROLE_UNSAFE']])await assert.rejects(notificationRole(guildFixture(role),main,id,config(patch)),{code});});
test('unmapped notifications remain optional without Discord role calls',async()=>{const guild=guildFixture();assert.equal(await notificationRole(guild,main,null,config()),undefined);assert.deepEqual(guild.calls,[]);assert.deepEqual(notificationMessage(undefined,'Gather.'),{callout:'Gather.',allowedMentions:{parse:[],roles:[],users:[],repliedUser:false}});});
test('outgoing callout contains exactly one authorized native role mention and no injected mentions',()=>{const result=notificationMessage(roleId,`Hello <@&${roleId}> <@&777777777777777777> <@444444444444444444> @everyone @here`);assert.deepEqual(result.callout.match(/<@&\d+>/g),[`<@&${roleId}>`]);assert.doesNotMatch(result.callout,/@everyone|@here|<@444444444444444444>/);assert.deepEqual(result.allowedMentions,{parse:[],roles:[roleId],users:[],repliedUser:false});});
test('canonical VC and Chess triggers resolve existing lowercase mappings, without accepting uppercase custom triggers',async()=>{for(const trigger of ['!VC','!Chess']){let queued,deleted=0;const guild=guildFixture();guild.members.fetch=async()=>({roles:{cache:new Map()},displayName:'Member'});const repo={queueCallout:async(c,content,notification)=>{queued={c,content,notification};return{jobId:'job'};}},c=new DiscordSpecialCoordinator(repo,config(),async()=>true);c.deliver=async()=>{};await c.message({id:triggerId,content:trigger,author:{id:memberId,bot:false},guildId:g,guild,channelId:main,delete:async()=>{deleted++;},channel:{isSendable:()=>true}});assert.equal(deleted,1);assert.equal(queued.notification,roleId);assert.match(queued.content,trigger==='!VC'?/Voice/:/Chess/);}
 let touched=false;await new DiscordSpecialCoordinator({},config(),async()=>true).message({content:'!Custom',author:{bot:false},guildId:g,guild:{},delete:async()=>{touched=true;}});assert.equal(touched,false);
});
test('configured notification permission failure precedes the durable send claim',async()=>{let claims=0,sends=0;const guild=guildFixture({...safeRole,mentionable:false}),repo={callout:async()=>({payload:{guildId:g,channelId:main,content:'Gather.',notificationRoleId:roleId}}),delivery:()=>({read:async()=>({state:'PENDING'}),claim:async()=>{claims++;return true;}})},client={guilds:{fetch:async()=>guild},channels:{fetch:async()=>({isSendable:()=>true,messages:{},send:async()=>{sends++;}})}};await assert.rejects(new DiscordSpecialCoordinator(repo,config(),async()=>true).deliver(client,'job'),{code:'NOTIFICATION_PERMISSION'});assert.equal(claims,0);assert.equal(sends,0);});
test('Line creation sends one real TextDisplay role mention and readiness updates remove ping permission',async()=>{
 let state={state:'PENDING'},sends=0,sent,edits=[];let view={id:'line-session',guildId:g,channelId:main,messageId:'published',ownerId:memberId,state:'OPEN',expiresAt:new Date(0),extensionUsed:false,members:[{userId:memberId,name:'Member',status:'ready'}],remainingMs:0,elapsedMs:0};
 const repo={callout:async()=>({payload:{guildId:g,channelId:main,sessionId:view.id,notificationRoleId:roleId,content:'Gather once.'}}),publicView:async()=>view,delivery:()=>({read:async()=>state,claim:async()=>{state={state:'SENDING'};return true;},complete:async messageId=>{state={state:'SENT',messageId};}}),linkMessage:async()=>{}};
 const guild=guildFixture(),channel={isSendable:()=>true,isTextBased:()=>true,messages:{fetch:async()=>({author:{id:bot},edit:async p=>edits.push(p)})},send:async p=>{sent=p;sends++;return{id:'published'};}},client={user:{id:bot},guilds:{fetch:async()=>guild},channels:{fetch:async()=>channel}},c=new DiscordSpecialCoordinator(repo,config(),async()=>true);
 await c.deliver(client,'job');await c.deliver(client,'job');assert.equal(sends,1);assert.match(texts(sent),new RegExp('^<@&'+roleId+'>\\n\\*\\*LINE READINESS · \\d\\d:\\d\\d remaining'));assert.deepEqual(sent.allowedMentions.roles,[roleId]);view={...view,state:'CLOSED'};await c.refresh(client,view.id);assert.equal(edits.length,1);assert.equal(texts(edits[0]),'');assert.deepEqual(edits[0].allowedMentions,{parse:[]});
});
test('Race creation deduplicates concurrent trigger/replay and only creation authorizes its native role mention',async()=>{
 let linked=null,sends=0,starts=0;const payloads=[];const member={id:memberId,displayName:'Member',displayAvatarURL:()=>undefined,roles:{cache:new Map()}},guild=guildFixture();guild.members.fetch=async()=>member;
 const view={id:'race-session',guildId:g,channelId:main,state:'OPEN',expiresAt:new Date(0),racers:[{userId:memberId,name:'Member',chair:1}],pool:'0',extensionUsed:false};
 const repo={startRace:async()=>{starts++;return{sessionId:view.id};},publicView:async()=>({...view,messageId:linked}),linkMessage:async(_id,_g,messageId)=>{linked=messageId;}},channel={isSendable:()=>true,send:async p=>{sends++;payloads.push(p);return{id:'published'};}},message={id:triggerId,content:'!race',author:{id:memberId,bot:false},guildId:g,guild,channelId:main,channel,delete:async()=>{}},c=new DiscordEventsCoordinator(repo,config(),async()=>true);
 await Promise.all([c.message(message),c.message(message)]);assert.equal(starts,1);assert.equal(sends,1);await c.message(message);assert.equal(sends,1);assert.match(texts(payloads[0]),new RegExp('^<@&'+roleId+'>\\n\\*\\*RACE WAITING ROOM'));assert.deepEqual(payloads[0].allowedMentions.roles,[roleId]);assert.equal(payloads[0].nonce,triggerId);assert.equal(payloads[0].enforceNonce,true);const edit=await c.payload({...view,state:'CANCELLED'});assert.equal(texts(edit),'');assert.deepEqual(edit.allowedMentions,{parse:[]});
});


test('recovery and completed callouts do not require permission for a second notification',async()=>{for(const initial of ['SENT','SENDING']){let state={state:initial,messageId:initial==='SENT'?'published':undefined},sends=0;const existing={id:'published',author:{id:bot},embeds:[{footer:{text:'special:job'}}],components:[]},repo={callout:async()=>({payload:{guildId:g,channelId:main,notificationRoleId:roleId,content:'Already delivered.'}}),delivery:()=>({read:async()=>state,complete:async messageId=>{state={state:'SENT',messageId};}})},client={user:{id:bot},guilds:{fetch:async()=>{throw Error('No new mention permission needed');}},channels:{fetch:async()=>({isSendable:()=>true,messages:{fetch:async()=>new Collection([['published',existing]])},send:async()=>{sends++;}})}};await new DiscordSpecialCoordinator(repo,config(),async()=>true).deliver(client,'job');assert.equal(sends,0);assert.equal(state.state,'SENT');}});


test('each built-in Special trigger persists only its own mapped notification role',async()=>{const map={'!line':'700000000000000001','!race':'700000000000000002','!vc':'700000000000000003','!chess':'700000000000000004'};for(const trigger of ['!line','!VC','!Chess']){let captured,starts=0,callouts=0;const guild=guildFixture();guild.roles.fetch=async id=>({...safeRole,id});guild.members.fetch=async()=>({roles:{cache:new Map()},displayName:'Member'});const repo={start:async(_c,_name,p)=>{starts++;captured=p.notificationRoleId;return{sessionId:'line',jobId:'job'};},queueCallout:async(_c,_text,role)=>{callouts++;captured=role;return{jobId:'job'};}},c=new DiscordSpecialCoordinator(repo,config({'special_commands.builtin_role_map':map}),async()=>true);c.deliver=async()=>{};await c.message({id:triggerId,content:trigger,author:{id:memberId,bot:false},guildId:g,guild,channelId:main,delete:async()=>{},channel:{isSendable:()=>true}});assert.equal(captured,map[normalizeNotificationTrigger(trigger)]);assert.equal(starts,trigger==='!line'?1:0);assert.equal(callouts,trigger==='!line'?0:1);}});
