import test from 'node:test';
import assert from 'node:assert/strict';
import {DiscordOnboardingCoordinator} from '../../dist/apps/bot/src/discord/onboarding-coordinator.js';
function fixture(overrides={}){
 const order=[],replies=[],cache=new Map(),guild={id:'g',roles:{cache:new Map()}},member={id:'u',guild,isCommunicationDisabled:()=>false,roles:{cache,add:async id=>{order.push('add:'+id);cache.set(id,{id});},remove:async id=>{order.push('remove:'+id);cache.delete(id);}}};guild.members={fetch:async()=>member};
 const plan={guildId:'g',userId:'u',grantMemberAccess:true,applyJailedRole:false,crimeCommandRestricted:false,deferredBecausePunished:false,rolesToRestore:[],punishmentIds:[],...overrides};
 const service={acknowledgeRules:async()=>{order.push('ack');return plan;},completeRoleRestore:async()=>{order.push('restore-complete');}};
 const flags={'features.learning':true,'features.lore':true,'roles.member_access':'access','roles.jailed':'jailed'},config={get:async(g,k)=>flags[k]??null};
 const learning={eligible:async()=>{order.push('eligibility');return true;},loreAvailable:async()=>true};
 const interaction={guildId:'g',guild,member:{},user:{id:'u'},deferReply:async p=>replies.push(p),editReply:async p=>{order.push('reply');replies.push(p);}};
 return{order,replies,member,plan,flags,learning,service,config,interaction,coordinator:()=>new DiscordOnboardingCoordinator(service,config,learning)};
}
const ids=f=>f.replies.at(-1).components.flatMap(row=>row.toJSON().components.map(button=>button.custom_id));
test('Rules acknowledgement offers private member-bound optional learning buttons after access restoration',async()=>{const f=fixture();await f.coordinator().handleRulesAck(f.interaction);assert.equal(f.replies[0].ephemeral,true);assert.deepEqual(ids(f),['learn:lore:u:toc','learn:tutorial:u:home']);assert.match(f.replies.at(-1).content,/`\/roles`/);assert.match(f.replies.at(-1).content,/`\/introduce`/);assert.match(f.replies.at(-1).content,/optional/i);assert.ok(f.order.indexOf('restore-complete')<f.order.indexOf('eligibility'));assert.ok(f.order.indexOf('eligibility')<f.order.indexOf('reply'));assert.deepEqual(f.replies.at(-1).allowedMentions,{parse:[]});});
test('Pending lore prose and disabled feature flags never advertise unavailable content',async()=>{const f=fixture();f.learning.loreAvailable=async()=>false;await f.coordinator().handleRulesAck(f.interaction);assert.deepEqual(ids(f),['learn:tutorial:u:home']);assert.doesNotMatch(f.replies.at(-1).content,/\/lore/);const disabled=fixture();disabled.flags['features.learning']=false;disabled.flags['features.lore']=false;await disabled.coordinator().handleRulesAck(disabled.interaction);assert.deepEqual(ids(disabled),[]);});
test('Crime/moderation restrictions and timeout suppress optional controls before eligibility lookup',async()=>{for(const plan of [{crimeCommandRestricted:true},{applyJailedRole:true,grantMemberAccess:false,deferredBecausePunished:true},{crimeCommandRestricted:true,applyJailedRole:true,grantMemberAccess:false,deferredBecausePunished:true}]){const f=fixture(plan);await f.coordinator().handleRulesAck(f.interaction);assert.deepEqual(ids(f),[]);assert.ok(!f.order.includes('eligibility'));}const timed=fixture();timed.member.isCommunicationDisabled=()=>true;await timed.coordinator().handleRulesAck(timed.interaction);assert.deepEqual(ids(timed),[]);});
test('Capability/runtime denial and absent callbacks fail closed without blocking rules acknowledgment',async()=>{for(const learning of [{},{eligible:async()=>false,loreAvailable:async()=>true},{eligible:async()=>{throw Error('Eligibility unavailable');},loreAvailable:async()=>true}]){const f=fixture();await new DiscordOnboardingCoordinator(f.service,f.config,learning).handleRulesAck(f.interaction);assert.deepEqual(ids(f),[]);assert.equal(f.member.roles.cache.has('access'),true);assert.match(f.replies.at(-1).content,/Rules acknowledged/);}});
test('Failed access restoration does not offer learning shortcuts',async()=>{const f=fixture(),add=f.member.roles.add;f.member.roles.add=async id=>{if(id==='access')throw Error('Permission denied');return add(id);};await f.coordinator().handleRulesAck(f.interaction);assert.deepEqual(ids(f),[]);assert.match(f.replies.at(-1).content,/could not be restored/);assert.ok(!f.order.includes('eligibility'));});
test('Unavailable lore readiness probe never interrupts the required rules gate',async()=>{const f=fixture();f.learning.loreAvailable=async()=>{throw Error('Content unavailable');};await f.coordinator().handleRulesAck(f.interaction);assert.deepEqual(ids(f),[]);assert.equal(f.member.roles.cache.has('access'),true);assert.match(f.replies.at(-1).content,/Rules acknowledged/);});
