import test from 'node:test';
import assert from 'node:assert/strict';
import {DiscordPartyCoordinator} from '../../dist/apps/bot/src/discord/party-coordinator.js';
import {renderParty,renderPartyDraft,partyTranscript} from '../../dist/packages/features-party/src/render.js';
const v={id:'internal-session',guildId:'server',channelId:'games',messageId:'message',ownerId:'chooser',state:'OPEN',version:0,expiresAt:new Date('2026-09-26T12:00:00Z'),extensionUsed:false,game:'wwyd',phase:'vote',category:'Casual',prompt:'An unexpected visitor arrives at the lounge.',options:[{id:'a',text:'Offer a seat'},{id:'b',text:'Ask their story'}],submissionCount:0,submissions:{},words:[],round:0};
const trio=[{userId:'member-secret-a',name:'Alex'},{userId:'member-secret-b',name:'Riley'},{userId:'member-secret-c',name:'Morgan'}];
test('Party premium family uses wide lounge frames and distinct games typography without leaking private drafts',()=>{for(const game of ['truthordare','wwyd','finishsentence','onewordstory','fmk']){const svg=renderParty({...v,game});assert.match(svg,/width="1200"/);assert.match(svg,/Poppins/);assert.match(svg,/Cinzel/);assert.match(svg,/#3B82F6/);}const draft=renderParty({...v,game:'fmk',state:'DRAFT',trio,assignments:{fuck:trio[0].userId}});assert.doesNotMatch(draft,/Alex|Riley|Morgan/);});
test('FMK supplies three equal portrait cards, per-member counters, chooser and integrated result',()=>{const svg=renderParty({...v,game:'fmk',phase:'done',state:'CLOSED',trio,assignments:{fuck:trio[0].userId,marry:trio[1].userId,kill:trio[2].userId},subjectCounters:Object.fromEntries(trio.map(m=>[m.userId,{fucked:2,married:4,killed:3}])),options:[{id:'agree',text:'Agree'},{id:'disagree',text:'Disagree'}],result:{label:'Audience agrees',totals:{agree:8,disagree:2},percentages:{agree:80,disagree:20},total:10,randomResolution:false}},{chooser:{name:'Jordan',avatarData:''}});for(const role of ['FUCK','MARRY','KILL'])assert.ok(svg.includes('>'+role+'<'));for(const m of trio)assert.ok(svg.includes('>'+m.name+'<'));assert.match(svg,/Chosen by Jordan/);assert.match(svg,/8 votes · 80%/);assert.match(svg,/2 votes · 20%/);assert.equal((svg.match(/width="360"/g)||[]).length,6);});
test('Private FMK uses the same three-card frame while public transcript omits member identifiers',()=>{const svg=renderPartyDraft({trio,fuck:trio[0].userId,marry:trio[1].userId});assert.match(svg,/PRIVATE ASSIGNMENT/);assert.match(svg,/Nothing is public|nothing is public/);for(const name of ['Alex','Riley','Morgan'])assert.ok(svg.includes('>'+name+'<'));const transcript=partyTranscript({...v,phase:'done',submissions:{'member-secret-a':{name:'Alex',text:'A surprising ending'}}});assert.match(transcript,/Alex: A surprising ending/);assert.doesNotMatch(transcript,/member-secret|internal-session/);});
test('Unchanged sweeps and hidden ballot revisions upload nothing; extensions only update controls and native time',async()=>{let view={...v},edits=[],renders=[];const coordinator=new DiscordPartyCoordinator({publicView:async()=>view},{},async()=>true);coordinator.payload=async(_v,_c,art)=>{renders.push(art);return art?{files:['image'],components:['controls']}:{components:['controls']};};const client={user:{id:'bot'},channels:{fetch:async()=>({isTextBased:()=>true,messages:{fetch:async()=>({author:{id:'bot'},edit:async p=>edits.push(p)})}})}};await coordinator.refresh(client,v.id);await coordinator.refresh(client,v.id);view={...view,version:25};await coordinator.refresh(client,v.id);assert.equal(edits.length,1);view={...view,extensionUsed:true,expiresAt:new Date(view.expiresAt.getTime()+30000)};await coordinator.refresh(client,v.id);assert.deepEqual(renders,[true,false]);assert.equal('files'in edits[1],false);view={...view,phase:'done',state:'CLOSED',result:{label:'Voting complete',total:1,totals:{a:1},percentages:{a:100}}};await coordinator.refresh(client,v.id);assert.deepEqual(renders,[true,false,true]);await coordinator.refresh(client,v.id);assert.deepEqual(renders,[true,false,true]);});
test('Party embeds hide internal footer markers and keep recovery-capable native IDs',async()=>{const payload=await new DiscordPartyCoordinator({},{},async()=>true).payload(v,undefined,false);assert.equal(payload.embeds[0].toJSON().footer,undefined);assert.equal(payload.embeds[0].toJSON().author,undefined);assert.equal(payload.embeds[0].toJSON().title,undefined);assert.equal(payload.embeds[0].toJSON().description,undefined);assert.match(payload.content,/^Closes <t:/);assert.equal('files'in payload,false);assert.ok(payload.components.flatMap(r=>r.toJSON().components).every(c=>c.custom_id.split(':')[2]===v.id));});

test('Party render memo retains closed frames and evicts old sessions at a bounded size',async()=>{const coordinator=new DiscordPartyCoordinator({publicView:async id=>({...v,id,state:'CLOSED'})},{},async()=>true),edits=[];coordinator.payload=async view=>({content:view.id});const client={user:{id:'bot'},channels:{fetch:async()=>({isTextBased:()=>true,messages:{fetch:async()=>({author:{id:'bot'},edit:async p=>edits.push(p)})}})}};for(let n=0;n<257;n++)await coordinator.refresh(client,'round-'+n);assert.equal(coordinator.presented.size,256);await coordinator.refresh(client,'round-256');assert.equal(edits.length,257);await coordinator.refresh(client,'round-0');assert.equal(edits.length,258);});

test('FMK uses supplied member profile images in all three private and public cards',()=>{const avatars=Object.fromEntries(trio.map((m,n)=>[m.userId,{name:m.name,avatarData:'data:image/png;base64,'+['AAAA','BBBB','CCCC'][n]}]));for(const svg of [renderPartyDraft({trio,fuck:trio[0].userId,marry:trio[1].userId},avatars),renderParty({...v,game:'fmk',trio,assignments:{fuck:trio[0].userId,marry:trio[1].userId,kill:trio[2].userId}},avatars)])for(const value of Object.values(avatars)){assert.ok(svg.includes('href="'+value.avatarData+'"'));}});
test('FMK public delivery retrieves each subject and chooser profile from Discord',async()=>{const seen=[],client={guilds:{fetch:async()=>({members:{fetch:async({user})=>{seen.push(user);return{displayName:'Current '+user,displayAvatarURL:()=>'',user:{}};}}})}},view={...v,game:'fmk',trio,assignments:{fuck:trio[0].userId,marry:trio[1].userId,kill:trio[2].userId}};await new DiscordPartyCoordinator({},{},async()=>true).payload(view,client);assert.deepEqual(seen.sort(),[...trio.map(m=>m.userId),'chooser'].sort());});
