import test from 'node:test';import assert from 'node:assert/strict';
import {DiscordPartyCoordinator} from '../../dist/apps/bot/src/discord/party-coordinator.js';
import {DiscordWyrCoordinator} from '../../dist/apps/bot/src/discord/wyr-coordinator.js';
import {renderParty} from '../../dist/packages/features-party/src/render.js';
const forbidden=new Proxy({},{get:()=>()=>{throw Error('Repository not authorized');}}),config=overrides=>({get:async(_g,k)=>({...{'features.party_games':true,'channels.games_channel':'games'},...overrides})[k]});
const i=()=>({guildId:'g',guild:{},channelId:'games',user:{id:'u'},id:'request',commandName:'wwyd',calls:[],options:{getString:()=>null},isChatInputCommand:()=>true,reply:async function(p){this.calls.push(p)},deferReply:async function(){this.deferred=true;},editReply:async function(p){this.calls.push(p)},isModalSubmit:()=>false,isButton:()=>false});
test('party and WYR guard flags, configured channel and containment before reads',async()=>{for(const C of [DiscordPartyCoordinator,DiscordWyrCoordinator])for(const[o,eligible,pattern]of [[{'features.party_games':false},true,/not enabled/],[{'channels.games_channel':'other'},true,/games channel/],[{},false,/restricted/]]){const x=i(),coordinator=new C(forbidden,config(o),async()=>eligible);await(C===DiscordPartyCoordinator?coordinator.handle(x):coordinator.handleSlash(x));assert.match(x.calls[0].content,pattern);}});
test('One Word Story uses either shared game channel and retains its dedicated channel',async()=>{
 const cfg=config({'channels.one_word_story_channel':'reading'}),starts=[],repo={start:async(_context,options)=>{starts.push(options.game);return{sessionId:'story'};}};
 const story={...i(),channelId:'reading',commandName:'onewordstory',options:{getInteger:()=>20}};
 await new DiscordPartyCoordinator(repo,cfg,async()=>true).handle(story);
 assert.deepEqual(starts,['onewordstory']);assert.match(story.calls[0].content,/ready/);
 const wrong={...i(),channelId:'other',commandName:'onewordstory',options:{getInteger:()=>20}};
 await new DiscordPartyCoordinator(forbidden,cfg,async()=>true).handle(wrong);
 assert.match(wrong.calls[0].content,/games channel/);
 const other={...i(),channelId:'reading',commandName:'wwyd'};
 await new DiscordPartyCoordinator(forbidden,cfg,async()=>true).handle(other);
 assert.match(other.calls[0].content,/games channel/);
});
const view={id:'round',guildId:'g',channelId:'games',messageId:'m',ownerId:'u',state:'OPEN',version:0,expiresAt:new Date('2026-09-25T12:01:00Z'),extensionUsed:false,game:'wwyd',phase:'vote',category:'Casual',prompt:'A <strange> choice & a chair',options:[{id:'a',text:'Option A'},{id:'b',text:'Option B'}],submissionCount:0,submissions:{},words:[],round:0};
test('party renderer uses saved escaped prompt without ballot counts or voter identities',()=>{const svg=renderParty(view);assert.match(svg,/A &lt;strange&gt; choice &amp; a chair/);assert.match(svg,/totals hidden/);assert.doesNotMatch(svg,/1 votes|voterUserId/);});
test('FMK public vote has Agree/Disagree and local Play Again, with no winner claim',async()=>{const v={...view,game:'fmk',options:[{id:'agree',text:'Agree'},{id:'disagree',text:'Disagree'}],trio:[{userId:'a',name:'A'},{userId:'b',name:'B'},{userId:'c',name:'C'}],assignments:{fuck:'a',marry:'b',kill:'c'},subjectCounters:{a:{fucked:1,married:0,killed:0},b:{fucked:0,married:1,killed:0},c:{fucked:0,married:0,killed:1}}};const payload=await new DiscordPartyCoordinator(forbidden,config({}),async()=>true).payload(v),labels=payload.components.flatMap(r=>(r.toJSON().components??[]).map(c=>c.label));assert.ok(labels.includes('Agree'));assert.ok(labels.includes('Disagree'));assert.ok(labels.includes('Play Again'));assert.match(renderParty(v),/Agree or Disagree/);assert.equal(payload.embeds.length,0);assert.deepEqual(payload.allowedMentions,{parse:[]});});
test('WYR stale cross-server message bindings reject before votes',async()=>{const x={...i(),customId:'wyr:vote:A:round',message:{id:'forged'},isButton:()=>true};const coordinator=new DiscordWyrCoordinator({get:async()=>({guildId:'g',channelId:'games',messageId:'original'})},config({}),async()=>true);await coordinator.handleButton(x);assert.match(x.calls[0].content,/original WYR message/);});

test('FMK final card reveals its own audience totals without naming voters or claiming a winner',async()=>{const v={...view,state:'CLOSED',game:'fmk',phase:'done',prompt:undefined,options:[{id:'agree',text:'Agree'},{id:'disagree',text:'Disagree'}],trio:[{userId:'a',name:'A'},{userId:'b',name:'B'},{userId:'c',name:'C'}],assignments:{fuck:'a',marry:'b',kill:'c'},result:{label:'Split Decision',total:2,totals:{agree:1,disagree:1},percentages:{agree:50,disagree:50},randomResolution:false}};const svg=renderParty(v);assert.match(svg,/Agree: 1 votes/);assert.match(svg,/Disagree: 1 votes/);assert.equal([...svg.matchAll(/1 votes · 50%/g)].length,2);const payload=await new DiscordPartyCoordinator(forbidden,config({}),async()=>true).payload(v);assert.match(svg,/Split Decision/);assert.equal(payload.embeds.length,0);assert.deepEqual(payload.allowedMentions,{parse:[]});});


test('party long public copy is centered and stays inside the adaptive attachment',()=>{const long='A very long member contribution. '.repeat(22),v={...view,state:'CLOSED',phase:'done',prompt:long,options:[{id:'a',text:long},{id:'b',text:'A'}],result:{label:'The lounge has chosen.',totals:{a:3,b:1},percentages:{a:75,b:25},total:4}};const svg=renderParty(v),height=Number(svg.match(/height="(\d+)"/)[1]);assert.ok(height>746);assert.doesNotMatch(svg,/Full text and choices/);for(const match of svg.matchAll(/<text([^>]+)>/g)){assert.match(match[1],/text-anchor="middle"/);const y=Number(match[1].match(/y="([\d.]+)"/)[1]);assert.ok(y<height-12);}assert.match(svg,/75%/);});
