import test from 'node:test';
import assert from 'node:assert/strict';
import {DiscordPvpCoordinator} from '../../dist/apps/bot/src/discord/pvp-coordinator.js';
import {renderPvp,renderPrivatePvp,renderPvpNotice} from '../../dist/packages/features-pvp/src/render.js';
const view={id:'internal-match',guildId:'guild',channelId:'games',messageId:'message',version:1,state:'LOCKED',game:'tictactoe',players:[{userId:'alice',name:'Alice'},{userId:'bob',name:'Bob'}],wager:'10',phase:'playing',turn:0,ready:[true,true],cells:Array(9).fill(0),shots:[[],[]],expiresAt:new Date('2030-01-01')};
const config={get:async(g,key)=>key==='features.pvp'?true:key==='channels.games_channel'?'games':1};
const guild={id:'guild',members:{fetch:async()=>({user:{bot:false},isCommunicationDisabled:()=>false,permissionsIn:()=>({has:()=>true})})}};
function interaction(action='move',version=1){const calls=[];const i={guildId:'guild',guild,channelId:'games',user:{id:'alice'},id:'request',customId:`pvp:${action}:internal-match:${version}:0`,deferred:false,replied:false,isChatInputCommand:()=>false,isButton:()=>true,isModalSubmit:()=>false,deferUpdate:async()=>{calls.push('ack');i.deferred=true;},deferReply:async()=>{calls.push('ack-private');i.deferred=true;},editReply:async p=>calls.push(p),followUp:async p=>calls.push(p),reply:async p=>calls.push(p),deleteReply:async()=>calls.push('delete')};return{i,calls};}
test('PvP premium frames are wide, deterministic, escaped and game-specific',()=>{for(const game of ['tictactoe','connectfour','battleship']){const v={...view,game,cells:Array(game==='connectfour'?42:9).fill(0)},svg=renderPvp(v);assert.match(svg,/width="1200"/);assert.match(svg,/Space Grotesk/);assert.match(svg,/Inter/);assert.match(svg,/#3B82F6/);assert.equal(svg,renderPvp(v));assert.ok(!svg.includes(view.id));}assert.match(renderPvp({...view,players:[{userId:'alice',name:'A < B & C'},view.players[1]]}),/A &lt; B &amp; C/);assert.match(renderPvpNotice('Rules','Your move.'),/width="1200"/);});
test('PvP public portraits accept bounded image data but never arbitrary image URLs',()=>{const svg=renderPvp(view,{alice:{name:'Alice',avatarData:'data:image/png;base64,AAAA'},bob:{name:'Bob',avatarData:'https://unsafe.invalid/avatar'}});assert.match(svg,/data:image\/png;base64,AAAA/);assert.ok(!svg.includes('unsafe.invalid'));assert.match(svg,/portrait0/);assert.match(svg,/portrait1/);});
test('Battleship public and private projections never render opponent fleet data',()=>{const v={id:'private-secret',game:'battleship',version:1,phase:'playing',seat:0,turn:0,fleet:[[0,1]],ownShots:[{cell:33,hit:true,sunk:false}],incomingShots:[],enemyFleet:'SECRET_ENEMY_FLEET'};const svg=renderPrivatePvp(v);assert.match(svg,/Your fleet/);assert.match(svg,/Your shots/);assert.match(svg,/D4/);assert.ok(!svg.includes('SECRET_ENEMY_FLEET'));assert.ok(!svg.includes('private-secret'));assert.ok(!renderPvp({...view,game:'battleship',enemyFleet:'SECRET_ENEMY_FLEET'}).includes('SECRET_ENEMY_FLEET'));});
test('Unchanged PvP refreshes avoid rendering and all Discord fetch/edit work',async()=>{let renders=0,fetches=0,edits=0,current=structuredClone(view);const coordinator=new DiscordPvpCoordinator({publicView:async()=>current},config,async()=>true);coordinator.payload=async()=>{renders++;return{};};const client={user:{id:'bot'},channels:{fetch:async()=>{fetches++;return{isTextBased:()=>true,messages:{fetch:async()=>({author:{id:'bot'},edit:async()=>{edits++;}})}};}}};await coordinator.refresh(client,view.id);await Promise.all([coordinator.refresh(client,view.id),coordinator.refresh(client,view.id)]);assert.deepEqual([renders,fetches,edits],[1,1,1]);current={...current,version:2,turn:1,cells:[1,...Array(8).fill(0)]};await coordinator.refresh(client,view.id);assert.deepEqual([renders,fetches,edits],[2,2,2]);});
test('Failed PvP publications are retried rather than marked as published',async()=>{let edits=0;const coordinator=new DiscordPvpCoordinator({publicView:async()=>view},config,async()=>true);coordinator.payload=async()=>({});const client={user:{id:'bot'},channels:{fetch:async()=>({isTextBased:()=>true,messages:{fetch:async()=>({author:{id:'bot'},edit:async()=>{if(++edits===1)throw Error('transient');}})}})}};await assert.rejects(coordinator.refresh(client,view.id));await coordinator.refresh(client,view.id);assert.equal(edits,2);});
test('PvP move acknowledges before config/member/database work and remains silent',async()=>{const {i,calls}=interaction();const coordinator=new DiscordPvpCoordinator({publicView:async()=>{calls.push('read');return view;},act:async()=>calls.push('act')},{get:async(g,k)=>{assert.equal(calls[0],'ack');return config.get(g,k);}},async()=>true);coordinator.refresh=async()=>calls.push('refresh');await coordinator.handle(i);assert.deepEqual(calls,['ack','read','act','refresh']);});
test('PvP stale revisions still reject safely after immediate acknowledgement',async()=>{const {i,calls}=interaction('move',0);let actions=0;const coordinator=new DiscordPvpCoordinator({publicView:async()=>view,act:async()=>actions++},config,async()=>true);await coordinator.handle(i);assert.equal(calls[0],'ack');assert.equal(actions,0);assert.equal(calls[1].ephemeral,true);assert.match(calls[1].content,/changed/);});
test('PvP payload has only a native relative deadline outside the artwork',async()=>{const coordinator=new DiscordPvpCoordinator({},config,async()=>true),payload=await coordinator.payload(view);assert.match(payload.content,/^Deadline <t:\d+:R>\.$/);assert.equal(payload.embeds[0].data.description,undefined);assert.equal(payload.embeds[0].data.footer,undefined);assert.equal(payload.embeds[0].data.title,undefined);assert.deepEqual(payload.allowedMentions,{parse:[]});assert.equal(payload.components.length,4);});
