import test from 'node:test';
import assert from 'node:assert/strict';
import {DiscordPvpCoordinator} from '../../dist/apps/bot/src/discord/pvp-coordinator.js';
import {renderPvp,renderPrivatePvp,pvpDescription} from '../../dist/packages/features-pvp/src/render.js';
const view={id:'m',guildId:'g',channelId:'games',version:1,state:'LOCKED',game:'battleship',players:[{userId:'a',name:'Alice'},{userId:'b',name:'Bob'}],wager:'10',phase:'playing',turn:0,ready:[true,true],cells:[],shots:[[],[]],expiresAt:new Date()};
test('PvP renders use approved window; public output has no hidden fleet content',()=>{const svg=renderPvp({...view,fleet:'SECRET_ENEMY_FLEET'});assert.match(svg,/Space Grotesk/);assert.match(svg,/font-family="Inter"/);assert.match(svg,/data:image\/png;base64/);assert.ok(!svg.includes('SECRET_ENEMY_FLEET'));assert.ok(!pvpDescription({...view,fleet:'SECRET_ENEMY_FLEET'}).includes('SECRET'));const privateSvg=renderPrivatePvp({id:'m',game:'battleship',version:1,phase:'playing',seat:0,turn:0,fleet:[[0,1]],ownShots:[],incomingShots:[],enemyFleet:'SECRET_ENEMY_FLEET'});assert.ok(!privateSvg.includes('SECRET_ENEMY_FLEET'));assert.match(privateSvg,/Your fleet/);});
test('PvP disabled, channel and restricted-member guards precede repository effects',async()=>{let calls=0;const repo=new Proxy({}, {get:()=>()=>{calls++;throw Error('Repository must not run');}}),sent=[],i={guildId:'g',guild:{id:'g',members:{fetch:async()=>({user:{bot:false},isCommunicationDisabled:()=>false,permissionsIn:()=>({has:()=>true})})}},channelId:'games',user:{id:'u'},reply:async p=>sent.push(p),isButton:()=>false,deferReply:async()=>{},editReply:async p=>sent.push(p),deferred:true,isChatInputCommand:()=>true};await new DiscordPvpCoordinator(repo,{get:async()=>false},async()=>true).handle(i);assert.match(sent.pop().content,/not enabled/);await new DiscordPvpCoordinator(repo,{get:async(g,key)=>key==='features.pvp'?true:'wrong'},async()=>true).handle(i);assert.match(sent.pop().content,/Gaming Chair/);await new DiscordPvpCoordinator(repo,{get:async(g,key)=>key==='features.pvp'?true:'games'},async()=>false).handle(i);assert.match(sent.pop().content,/eligible|unavailable/);assert.equal(calls,0);});
test('Battleship board responses are private and outsider requests never reach private projection',async()=>{const sent=[];let privateCalls=0;const repo={publicView:async()=>view,privateView:async()=>{privateCalls++;throw Error('not reached');}},config={get:async(g,key)=>key==='features.pvp'?true:key==='channels.games_channel'?'games':1},guild={id:'g',members:{fetch:async()=>({user:{bot:false},isCommunicationDisabled:()=>false,permissionsIn:()=>({has:()=>true})})}},i={guildId:'g',guild,channelId:'games',user:{id:'outsider'},id:'request',customId:'pvp:board:m:1',isChatInputCommand:()=>false,isButton:()=>true,deferred:true,deferReply:async p=>sent.push(p),editReply:async p=>sent.push(p),reply:async p=>sent.push(p)};await new DiscordPvpCoordinator(repo,config,async()=>true).handle(i);assert.equal(privateCalls,0);assert.equal(sent[0].ephemeral,true);assert.match(sent[1].content,/two named|unavailable/);});
test('Named member opens a private fleet reply with all mentions disabled',async()=>{const sent=[];const privateView={id:'m',game:'battleship',version:1,phase:'playing',seat:0,turn:0,fleet:[[0,1]],ownShots:[],incomingShots:[]},repo={publicView:async()=>view,privateView:async(c,id)=>{assert.equal(c.userId,'a');assert.equal(id,'m');return privateView;}},config={get:async(g,key)=>key==='features.pvp'?true:key==='channels.games_channel'?'games':1},guild={id:'g',members:{fetch:async()=>({user:{bot:false},isCommunicationDisabled:()=>false,permissionsIn:()=>({has:()=>true})})}},i={guildId:'g',guild,channelId:'games',user:{id:'a'},id:'request',customId:'pvp:board:m:1',isChatInputCommand:()=>false,isButton:()=>true,deferReply:async p=>sent.push(p),editReply:async p=>sent.push(p),reply:async p=>sent.push(p)};await new DiscordPvpCoordinator(repo,config,async()=>true).handle(i);assert.equal(sent.length,2);assert.equal(sent[0].ephemeral,true);assert.deepEqual(sent[1].allowedMentions,{parse:[]});assert.equal(sent[1].files[0].name,'pvp-private.png');assert.ok(sent[1].components[0].components.every(b=>b.data.custom_id.endsWith(':a')));});
