import test from 'node:test';
import assert from 'node:assert/strict';
import {PrismaSocialRepository} from '../../dist/packages/features-social/src/prisma-repository.js';
const g='111111111111111111',ch='222222222222222222',a='333333333333333333',b='444444444444444444',m='555555555555555555',policy={throttleSeconds:3,roastBackSeconds:900};
/** Transaction boundary fake exercises the repository and shared session/receipt engines, not a second implementation.
 * PostgreSQL isolation itself is covered by the workspace shared atomic-operation integration suite. */
function database(){
 let state={receipts:{},jobs:{},sessions:{},throttles:{},privacy:{},history:[],next:0},tail=Promise.resolve();
 const clone=v=>structuredClone(v),key=v=>Object.values(v).join(':'),get=(table,where)=>{const id=where.id??key(Object.values(where)[0]);return state[table][id]??null;};
 const matches=(row,where)=>Object.entries(where).every(([k,v])=>k==='payload'?JSON.stringify(row.payload)===JSON.stringify(v.equals):v===row[k]);
 const db={
  operationReceipt:{findUnique:async({where})=>clone(get('receipts',where)),create:async({data})=>{const id=key({guildId:data.guildId,key:data.key});state.receipts[id]=clone(data);return clone(data);}},
  economyActionThrottle:{findUnique:async({where})=>clone(get('throttles',where)),upsert:async({where,create,update})=>{const id=key(where.guildId_userId_action);state.throttles[id]={...(state.throttles[id]??create),...update};return clone(state.throttles[id]);}},
  profileState:{findUnique:async({where})=>clone(state.privacy[key(where.guildId_userId)]??null)},
  contentEntry:{findMany:async({where})=>[{id:where.game+'-'+where.category,game:where.game,category:where.category,payload:{text:where.game==='roast'?'A folding chair has more composure.':where.game==='haiku'?'Poetry entered the lounge.':'{actor} bonks {target}.'}}]},
  contentUseHistory:{create:async({data})=>{state.history.push(clone(data));return data;}},
  gameSession:{findUnique:async({where})=>clone(get('sessions',where)),create:async({data})=>{state.sessions[data.id]={...clone(data),messageId:null};return clone(state.sessions[data.id]);},updateMany:async({where,data})=>{let count=0;for(const row of Object.values(state.sessions))if(matches(row,where)){Object.assign(row,clone(data));count++;}return{count};}},
  scheduledJob:{findUniqueOrThrow:async({where})=>{const row=get('jobs',where);assert.ok(row);return clone(row);},create:async({data})=>{const id='job-'+(++state.next);state.jobs[id]={id,...clone(data)};return clone(state.jobs[id]);},update:async({where,data})=>{Object.assign(state.jobs[where.id],clone(data));return clone(state.jobs[where.id]);},updateMany:async({where,data})=>{let count=0;for(const row of Object.values(state.jobs))if(matches(row,where)){Object.assign(row,clone(data));count++;}return{count};}},
  $transaction:async(fn,options)=>{assert.equal(options.isolationLevel,'Serializable');const pending=tail.then(async()=>{const snapshot=clone(state);try{return await fn(db);}catch(e){state=snapshot;throw e;}});tail=pending.catch(()=>{});return pending;},
  state:()=>state,
 };
 return db;
}
const context=(userId=a,requestKey='request')=>({guildId:g,channelId:ch,userId,requestKey});
async function opened(db,repo){const result=await repo.queue(context(),'roast',b,policy);await repo.delivery(result.jobId).claim();await repo.delivery(result.jobId).complete(m);await repo.finalize(result.jobId,m);return result;}
test('Concurrent distinct social commands obey one persisted member throttle',async()=>{const db=database(),repo=new PrismaSocialRepository(db,()=>new Date('2026-09-25T12:00:00Z'),()=>0);const results=await Promise.allSettled([repo.queue(context(a,'one'),'hit',b,policy),repo.queue(context(a,'two'),'hit',b,policy)]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.equal(results.find(r=>r.status==='rejected').reason.code,'SOCIAL_THROTTLED');assert.equal(Object.keys(db.state().jobs).length,1);});
test('Request replay returns the same delivery and a mismatched action cannot reuse its receipt',async()=>{const db=database(),repo=new PrismaSocialRepository(db,()=>new Date('2026-09-25T12:00:00Z'),()=>0),first=await repo.queue(context(),'hit',b,policy);assert.deepEqual(await repo.queue(context(),'hit',b,policy),first);assert.equal(Object.keys(db.state().jobs).length,1);await assert.rejects(repo.queue(context(),'slap',b,policy),{code:'REPLAY_MISMATCH'});});
test('Roast Back activates only after confirmed Discord delivery and survives repository restart',async()=>{const db=database(),repo=new PrismaSocialRepository(db,()=>new Date('2026-09-25T12:00:00Z'),()=>0),result=await repo.queue(context(),'roast',b,policy);assert.equal(db.state().sessions[result.sessionId].state,'DRAFT');await assert.rejects(repo.finalize(result.jobId,m),{code:'SOCIAL_UNCONFIRMED'});await repo.delivery(result.jobId).claim();await repo.delivery(result.jobId).complete(m);const restarted=new PrismaSocialRepository(db,()=>new Date('2026-09-25T12:00:01Z'),()=>0);await restarted.finalize(result.jobId,m);assert.equal(db.state().sessions[result.sessionId].state,'OPEN');assert.equal((await restarted.retaliation(context(b),result.sessionId,m)).actorId,a);});
test('Two concurrent Roast Back clicks queue exactly one retaliation; no new retaliation chain is granted',async()=>{const db=database(),repo=new PrismaSocialRepository(db,()=>new Date('2026-09-25T12:00:00Z'),()=>0),base=await opened(db,repo),back={sessionId:base.sessionId,messageId:m};const result=await Promise.allSettled([repo.queue(context(b,'back-one'),'roast',a,policy,back),repo.queue(context(b,'back-two'),'roast',a,policy,back)]);assert.equal(result.filter(r=>r.status==='fulfilled').length,1);assert.equal(result.find(r=>r.status==='rejected').reason.code,'ROAST_USED');const won=result.find(r=>r.status==='fulfilled').value;assert.equal(won.sessionId,null);assert.equal(Object.keys(db.state().jobs).length,2);assert.equal(db.state().sessions[base.sessionId].state,'CLOSED');assert.deepEqual(await repo.queue(context(b,'back-one'),'roast',a,policy,back),won);});
test('Blocked roast target and changed original-actor opt-out reject without consuming the grant',async()=>{const db=database(),repo=new PrismaSocialRepository(db,()=>new Date('2026-09-25T12:00:00Z'),()=>0);db.state().privacy[g+':'+b]={roastEnabled:false};await assert.rejects(repo.queue(context(),'roast',b,policy),{code:'ROAST_PRIVACY'});assert.equal(Object.keys(db.state().jobs).length,0);db.state().privacy[g+':'+b]={roastEnabled:true};const base=await opened(db,repo);db.state().privacy[g+':'+a]={roastEnabled:false};await assert.rejects(repo.queue(context(b,'back'),'roast',a,policy,{sessionId:base.sessionId,messageId:m}),{code:'ROAST_PRIVACY'});assert.equal(db.state().sessions[base.sessionId].state,'OPEN');});
test('Forged member/message/channel and expired controls cannot bypass the social throttle',async()=>{const db=database(),repo=new PrismaSocialRepository(db,()=>new Date('2026-09-25T12:00:00Z'),()=>0),base=await opened(db,repo);for(const [c,target,message] of [[context(a,'bad-a'),a,m],[context(b,'bad-message'),a,'other'],[{...context(b,'bad-channel'),channelId:a},a,m],[context(b,'bad-target'),b,m]])await assert.rejects(repo.queue(c,'roast',target,policy,{sessionId:base.sessionId,messageId:message}),{code:'ROAST_CONTROL'});const restarted=new PrismaSocialRepository(db,()=>new Date('2026-09-25T13:00:00Z'),()=>0);await assert.rejects(restarted.queue(context(b,'expired'),'roast',a,policy,{sessionId:base.sessionId,messageId:m}),{code:'ROAST_USED'});});
test('Passive complaints share a persisted channel throttle and store no observed chat',async()=>{const db=database(),repo=new PrismaSocialRepository(db,()=>new Date('2026-09-25T12:00:00Z'),()=>0),first=await repo.queueHaiku(context(a,'haiku-one'),300);await assert.rejects(repo.queueHaiku(context(b,'haiku-two'),300),{code:'SOCIAL_THROTTLED'});assert.deepEqual(await repo.queueHaiku(context(a,'haiku-one'),300),first);const p=(await repo.job(first.jobId)).payload;assert.equal(p.content,'Poetry entered the lounge.');assert.equal(p.sourceContent,undefined);assert.equal(p.sessionId,null);});
test('Confirmed delivery is idempotent and uncertain delivery is never blindly reset',async()=>{const db=database(),repo=new PrismaSocialRepository(db,()=>new Date('2026-09-25T12:00:00Z'),()=>0),first=await repo.queue(context(),'roast',b,policy);assert.equal(await repo.delivery(first.jobId).claim(),true);assert.equal(await repo.delivery(first.jobId).claim(),false);await assert.rejects(repo.cancel(first.jobId),{code:'DELIVERY_UNCERTAIN'});await repo.delivery(first.jobId).complete(m);await repo.delivery(first.jobId).complete(m);await assert.rejects(repo.delivery(first.jobId).complete(a),{code:'DELIVERY_CONFLICT'});});
