import test from 'node:test';
import {DomainError} from '../../dist/packages/core/src/index.js';
import assert from 'node:assert/strict';
import {DiscordSocialCoordinator,registeredSocialActions,socialActionChoices} from '../../dist/apps/bot/src/discord/social-coordinator.js';
import {HAIKU_RESPONSE,NOTMAD_RESPONSE,sampleHaiku} from '../../dist/packages/features-social/src/domain.js';
import {renderSocialResponse} from '../../dist/packages/features-social/src/render.js';
const g='111111111111111111',ch='222222222222222222',a='333333333333333333',b='444444444444444444',bot='555555555555555555',msg='666666666666666666';
const values={'features.social':true,'features.haiku':true,'channels.main_chat':ch,'social.throttle_seconds':3,'social.roast_back_seconds':900,'haiku.response_probability':0,'haiku.channel_cooldown_seconds':300};
const config=(overrides={})=>({get:async(g,key)=>({...values,...overrides})[key]});
function fixture(sub='react',overrides={}){const replies=[],guild={id:g,ownerId:a,fetch:async function(){return this;},members:{fetch:async({user})=>({id:user,user:{id:user,bot:false}})}};return{replies,id:'request-1',guildId:g,channelId:ch,guild,user:{id:a},client:{user:{id:bot}},commandName:'social',isButton:()=>false,isChatInputCommand:()=>true,options:{getSubcommand:()=>sub,getString:()=> 'hit',getUser:()=>({id:b})},deferred:false,replied:false,publicDeferred:false,deferReply:async function(p){this.deferred=true;this.publicDeferred=!p.ephemeral;},editReply:async p=>{replies.push(p);},reply:async p=>{replies.push(p);},followUp:async p=>{replies.push(p);},deleteReply:async()=>{replies.push({deleted:true});},...overrides};}
test('Disabled social gate, wrong channel and restricted member never enqueue responses',async()=>{for(const [settings,channel,eligible] of [[{'features.social':false},ch,true],[{},'999999999999999999',true],[{},ch,false]]){let calls=0;const repo={queue:async()=>{calls++;}},i=fixture('react',{channelId:channel});await new DiscordSocialCoordinator(repo,config(settings),async()=>eligible).handle(i);assert.equal(calls,0);assert.ok(i.replies[0].content);}});
test('Haiku responds exactly without attachments, targets, statistics or variations',async()=>{const i=fixture('',{commandName:'haiku'}),repo={exact:async(c,kind)=>{assert.equal(kind,'haiku');return{content:HAIKU_RESPONSE};}};await new DiscordSocialCoordinator(repo,config(),async()=>true).handle(i);assert.equal(i.publicDeferred,true);assert.deepEqual(i.replies,[{content:HAIKU_RESPONSE,allowedMentions:{parse:[]}}]);});
test('Notmad checks fresh actual server ownership; role-like eligibility cannot grant access',async()=>{let calls=0;const repo={exact:async()=>{calls++;return{content:NOTMAD_RESPONSE};}},i=fixture('notmad');i.guild.ownerId=b;await new DiscordSocialCoordinator(repo,config(),async()=>true).handle(i);assert.equal(calls,0);assert.ok(i.replies.some(p=>p.ephemeral&&/server owner/.test(p.content)));const owner=fixture('notmad');await new DiscordSocialCoordinator(repo,config(),async()=>true).handle(owner);assert.equal(calls,1);assert.equal(owner.replies[0].content,NOTMAD_RESPONSE);});
test('Forged social action cannot enqueue even when autocomplete is bypassed',async()=>{let called=0;const i=fixture('react');i.options.getString=()=> 'run-code';await new DiscordSocialCoordinator({queue:async()=>{called++;}},config(),async()=>true).handle(i);assert.equal(called,0);assert.match(i.replies[0].content,/available social action/);});
test('Original target, server/channel/message and bot author are required for Roast Back',async()=>{let called=0;const i=fixture('',{isButton:()=>true,isChatInputCommand:()=>false,customId:'social:back:session',message:{id:msg,author:{id:a}}});await new DiscordSocialCoordinator({retaliation:async()=>{called++;}},config(),async()=>true).handle(i);assert.equal(called,0);assert.match(i.replies[0].content,/original Angrier Jordan/);});
test('Delivery failure never reports a successful post',async()=>{const i=fixture('roast'),coordinator=new DiscordSocialCoordinator({queue:async()=>({jobId:'j'})},config(),async()=>true);coordinator.deliver=async()=>{throw Error('network');};await coordinator.handle(i);assert.ok(!i.replies.some(p=>p.content?.startsWith('Posted:')));assert.match(i.replies[0].content,/could not be confirmed/);});
test('Autocomplete reads all retained action contracts and respects feature/channel restrictions',async()=>{assert.equal(registeredSocialActions().length,38);const replies=[],i={guildId:g,channelId:ch,user:{id:a},commandName:'social',options:{getSubcommand:()=> 'react',getFocused:detail=>detail?{name:'action',value:'chair'}:'chair'},respond:async x=>replies.push(x)};await new DiscordSocialCoordinator({},config(),async()=>true).autocomplete(i);assert.ok(replies[0].length>0);assert.ok(replies[0].every(c=>c.value.includes('chair')));await new DiscordSocialCoordinator({},config({'features.social':false}),async()=>true).autocomplete(i);assert.deepEqual(replies[1],[]);});
test('Action autocomplete searches intuitive aliases regardless of case, spacing or punctuation',()=>{for(const [query,action] of [['TYPE SHIT','ts'],['type-shit','ts'],['touch grass','touchgrass'],['touch--grass!','touchgrass'],['where is my vape','wheresmyvape']]){const choices=socialActionChoices(query);assert.equal(choices[0]?.value,action);assert.ok(choices.length<=25);assert.ok(choices.every(c=>c.name.length<=100));}assert.equal(socialActionChoices('not-a-real-social-action').length,0);});
test('Passive haiku never queues bots, system, webhooks, wrong channels or skipped samples',async()=>{let calls=0;const coordinator=new DiscordSocialCoordinator({queueHaiku:async()=>{calls++;}},config(),async()=>true),base={id:msg,content:'An old silent pond\nA frog jumps into the pond\nSplash silence again',author:{id:a,bot:false},guildId:g,guild:{id:g},channelId:ch};for(const change of [{},{author:{id:a,bot:true}},{system:true},{webhookId:'webhook'},{channelId:a}])await coordinator.message({...base,...change});assert.equal(calls,0);});
test('A changed roast opt-out suppresses a pending publication before delivery claim',async()=>{let sent=0,cancelled=0;const p={guildId:g,channelId:ch,actorId:a,targetId:b,action:'roast',content:'Authored roast',sessionId:'s',deliveryState:'PENDING'},repo={job:async()=>({payload:p}),roastAllowed:async()=>false,cancel:async()=>{cancelled++;}},client={guilds:{fetch:async()=>fixture().guild},channels:{fetch:async()=>{sent++;}}};const result=await new DiscordSocialCoordinator(repo,config(),async()=>true).deliver(client,'j');assert.equal(result,null);assert.equal(cancelled,1);assert.equal(sent,0);});
test('Already-cancelled jobs do not attempt publication',async()=>{const repo={job:async()=>({payload:{cancelled:true}})},coordinator=new DiscordSocialCoordinator(repo,config(),async()=>true);assert.equal(await coordinator.deliver({},'j'),null);});
test('Social cards use the approved branded frame and replace mentions with escaped member names',()=>{const svg=renderSocialResponse('roast',`<@${a}> → <@${b}>\nA chair waits.`,{[a]:'Member <one>',[b]:'Member two'});assert.match(svg,/Space Grotesk/);assert.match(svg,/font-family="Inter"/);assert.match(svg,/data:image\/png;base64/);assert.match(svg,/Member &lt;one&gt;/);assert.doesNotMatch(svg,/<@/);assert.ok([...svg.matchAll(/<text[^>]*>/g)].every(m=>m[0].includes('text-anchor="middle"')));});

test('Accepted passive haiku dispatches a reply with the configured ten-minute cooldown',async()=>{const queued=[],delivered=[];let id=1;while(!sampleHaiku(String(id),.8))id++;const coordinator=new DiscordSocialCoordinator({queueHaiku:async(c,seconds)=>{queued.push({c,seconds});return{jobId:'haiku-job'};}},config({'haiku.response_probability':.8,'haiku.channel_cooldown_seconds':600}),async()=>true);coordinator.deliver=async(client,job)=>{delivered.push(job);return'reply';};await coordinator.message({id:String(id),content:'An old silent pond\nA frog jumps into the pond\nSplash silence again',author:{id:a,bot:false},guildId:g,guild:{id:g},channelId:ch,client:{}});assert.equal(queued.length,1);assert.equal(queued[0].seconds,600);assert.equal(queued[0].c.requestKey,String(id));assert.deepEqual(delivered,['haiku-job']);});
test('Passive haiku cooldown suppression stays silent and does not dispatch a reply',async()=>{let id=1;while(!sampleHaiku(String(id),.8))id++;let deliveries=0;const coordinator=new DiscordSocialCoordinator({queueHaiku:async()=>{throw new DomainError('SOCIAL_THROTTLED','cooldown');}},config({'haiku.response_probability':.8,'haiku.channel_cooldown_seconds':600}),async()=>true);coordinator.deliver=async()=>{deliveries++;};await coordinator.message({id:String(id),content:'An old silent pond\nA frog jumps into the pond\nSplash silence again',author:{id:a,bot:false},guildId:g,guild:{id:g},channelId:ch});assert.equal(deliveries,0);});

test('Haiku scans main plus explicit additional channels and excludes all others',async()=>{let id=1;while(!sampleHaiku(String(id),.8))id++;const seen=[],coordinator=new DiscordSocialCoordinator({queueHaiku:async c=>{seen.push(c.channelId);return{jobId:'job'};}},config({'haiku.response_probability':.8,'haiku.additional_channel_ids':[b]}),async()=>true);coordinator.deliver=async()=> 'reply';for(const channelId of [ch,b,a])await coordinator.message({id:String(id),content:'An old silent pond\nA frog jumps into the pond\nSplash silence again',author:{id:a,bot:false},guildId:g,guild:{id:g},channelId,client:{}});assert.deepEqual(seen,[ch,b]);});
test('Haiku publication rechecks additional channel while ordinary social stays main-only',async()=>{const coordinator=new DiscordSocialCoordinator({},config({'haiku.additional_channel_ids':[b]}),async()=>true),client={guilds:{fetch:async()=>fixture().guild}},p={guildId:g,channelId:b,actorId:a,targetId:null};assert.equal(await coordinator.canPublish(client,{...p,action:'haiku.passive'}),true);assert.equal(await coordinator.canPublish(client,{...p,action:'hit'}),false);assert.equal(await coordinator.canPublish(client,{...p,channelId:a,action:'haiku.passive'}),false);});
