import test from 'node:test';
import assert from 'node:assert/strict';
import {DiscordSoloCoordinator} from '../../dist/apps/bot/src/discord/solo-coordinator.js';
import {createPuzzle,puzzleView} from '../../dist/packages/features-solo/src/domain.js';
import {renderPremiumSolo} from '../../dist/packages/features-solo/src/premium-render.js';
const view=(game='hangman')=>({id:'private-session',guildId:'g',channelId:'c',messageId:'m',ownerId:'u',version:0,state:'OPEN',paid:'0',expiresAt:new Date('2026-10-01T00:00:00Z'),puzzle:puzzleView(createPuzzle(game,game==='minesweeper'?{boardSize:5}:{},()=>0))});
test('All four premium Solo frames are wide, deterministic and secret-free',()=>{for(const game of ['hangman','wordscramble','mastermind','minesweeper']){const v=view(game),svg=renderPremiumSolo(v,game,{name:'A & B',avatarData:''});assert.equal(svg,renderPremiumSolo(v,game,{name:'A & B',avatarData:''}));assert.match(svg,/width="1200"/);assert.match(svg,/Space Grotesk/);assert.match(svg,/Inter/);assert.match(svg,/A &amp; B/);assert.match(svg,/Closes 00:00:00 UTC/);assert.doesNotMatch(svg,/private-session|Code: /);}});
test('zero-reward Solo presentation makes no payout promise',()=>{const active={...view(),reward:'0'},svg=renderPremiumSolo(active,'Hangman');assert.match(svg,/No payouts/);assert.doesNotMatch(svg,/Shared daily reward cap|Ottomans awarded/);const closed=renderPremiumSolo({...active,state:'CLOSED',puzzle:{...active.puzzle,outcome:'won'}},'Hangman');assert.match(closed,/JUST FOR FUN/);assert.doesNotMatch(closed,/Ottomans awarded/);});
test('Solo acknowledgements precede config, eligibility and repository work',async()=>{const order=[],i={guildId:'g',guild:{},channelId:'c',user:{id:'u'},isButton:()=>false,isModalSubmit:()=>false,isChatInputCommand:()=>true,deferred:false,replied:false,deferReply:async()=>{order.push('ack');i.deferred=true;},editReply:async()=>{order.push('error');}};await new DiscordSoloCoordinator({}, {get:async()=>{order.push('config');return false;}},async()=>{order.push('eligible');return true;}).handle(i);assert.equal(order[0],'ack');assert.equal(order.at(-1),'error');assert.ok(order.includes('config'));assert.ok(order.includes('eligible'));});
test('Solo recovery edits only changed snapshots and serializes competing refreshes',async()=>{const v=view();let edits=0,renders=0;const coordinator=new DiscordSoloCoordinator({view:async()=>v},{},async()=>true);coordinator.payload=async()=>{renders++;return{};};const client={user:{id:'bot'},channels:{fetch:async()=>({isTextBased:()=>true,messages:{fetch:async()=>({author:{id:'bot'},edit:async()=>{edits++;}})}})}};await Promise.all([coordinator.refresh(client,v.id),coordinator.refresh(client,v.id)]);assert.equal(edits,1);assert.equal(renders,1);v.version++;await coordinator.refresh(client,v.id);assert.equal(edits,2);});
test('Failed Solo edits remain retryable and a fresh process republishes once',async()=>{const v=view();let edits=0;const repo={view:async()=>v},client={user:{id:'bot'},channels:{fetch:async()=>({isTextBased:()=>true,messages:{fetch:async()=>({author:{id:'bot'},edit:async()=>{if(++edits===1)throw Error('network');}})}})}};const c=new DiscordSoloCoordinator(repo,{},async()=>true);c.payload=async()=>({});await assert.rejects(c.refresh(client,v.id));await c.refresh(client,v.id);assert.equal(edits,2);const restarted=new DiscordSoloCoordinator(repo,{},async()=>true);restarted.payload=async()=>({});await restarted.refresh(client,v.id);assert.equal(edits,3);});
test('Solo payload keeps controls and only native live deadline outside the artwork',async()=>{const v=view(),c=new DiscordSoloCoordinator({view:async()=>v},{},async()=>true);const p=await c.payload(v.id);const embed=p.embeds[0].toJSON();assert.equal(embed.footer,undefined);assert.equal(embed.title,undefined);assert.equal(embed.description,undefined);assert.match(p.content,/^Ends <t:/);assert.deepEqual(p.components[0].toJSON().components.map(b=>b.label),['Guess','Quit','Rules']);});

