import test from 'node:test';import assert from 'node:assert/strict';
import {DiscordSpecialCoordinator,specialDeliveryUrl} from '../../dist/apps/bot/src/discord/special-coordinator.js';
import {renderLine,lineSequence} from '../../dist/packages/features-special/src/render.js';
const controls=p=>p.components.flatMap(r=>r.toJSON().components??[]).filter(c=>c.type===1).flatMap(r=>r.components);
const forbidden=new Proxy({},{get:()=>()=>{throw new Error('Repository must not be reached.');}});
const settings={'features.special_commands':true,'special_commands.enabled':true,'features.line':true,'channels.main_chat':'main','special_commands.custom_commands':[],'special_commands.access_roles':{'!line':[],'!vc':[],'!chess':[]},'special_commands.builtin_role_map':{'!line':null,'!race':null,'!vc':null,'!chess':null},'special_commands.builtin_response_pools':{'!line':['Chairs, gather.'],'!vc':['Voice invitation.'],'!chess':['Chess challenge.']}};
const config=(overrides={})=>({get:async(_g,k)=>({...settings,...overrides})[k]});
const interaction=()=>({guildId:'g',guild:{},channelId:'main',user:{id:'host'},customId:'line:start:id',message:{id:'m'},calls:[],deferred:false,reply:async function(p){this.calls.push(p)},editReply:async function(p){this.calls.push(p)},deferReply:async function(){this.deferred=true},deferUpdate:async function(){this.deferred=true},followUp:async function(p){this.calls.push(p)}});
test('Line flag, eligibility and wrong channel reject controls before repository reads',async()=>{for(const[overrides,eligible,match]of [[{'features.line':false},true,/not enabled/],[{},false,/restricted/],[{'channels.main_chat':'elsewhere'},true,/main chat/]]){const i=interaction();await new DiscordSpecialCoordinator(forbidden,config(overrides),async()=>eligible).handle(i);assert.match(i.calls[0].content,match);}});
test('Unauthorized known triggers are silently deleted even outside main chat',async()=>{for(const channelId of ['main','other']){const calls=[],message={content:'!vc',author:{id:'member',bot:false},guildId:'g',guild:{members:{fetch:async()=>({roles:{cache:new Map()}})}},channelId,delete:async()=>calls.push('deleted')};await new DiscordSpecialCoordinator(forbidden,config({'special_commands.access_roles':{'!line':[],'!vc':['staff'],'!chess':[]}}),async()=>true).message(message);assert.deepEqual(calls,['deleted']);}});
test('Known disabled custom trigger deletes silently, Race stays with its native coordinator',async()=>{const calls=[],message={content:'!party',author:{id:'member',bot:false},guildId:'g',guild:{},channelId:'main',delete:async()=>calls.push('deleted')};await new DiscordSpecialCoordinator(forbidden,config({'special_commands.custom_commands':[{trigger:'!party',notificationRoleId:null,responsePool:['Gather.'],enabled:false,allowedRoleIds:[]}]}),async()=>true).message(message);assert.deepEqual(calls,['deleted']);message.content='!race';await new DiscordSpecialCoordinator(forbidden,config(),async()=>true).message(message);assert.deepEqual(calls,['deleted']);});
test('packaged authored fallback and authorized help contain enabled accessible commands only',async()=>{const coordinator=new DiscordSpecialCoordinator(forbidden,config({'special_commands.builtin_response_pools':{'!line':[],'!vc':[],'!chess':[]},'special_commands.access_roles':{'!line':[],'!vc':['staff'],'!chess':[]}}),async()=>true);const all=await coordinator.definitions('g');assert.ok(all.every(d=>d.responsePool.length>=3));assert.deepEqual((await coordinator.visibleCommands('g',new Set())).map(d=>d.trigger),['!line','!chess']);assert.deepEqual(await new DiscordSpecialCoordinator(forbidden,config({'features.special_commands':false}),async()=>true).visibleCommands('g',new Set()),[]);});
test('durable callout delivers once with only a safe opt-in role allowed to mention',async()=>{let state={state:'PENDING'},sends=0,sent;const roleId='123456789012345678',repo={callout:async()=>({payload:{guildId:'g',channelId:'main',content:'Hello @everyone <@123>',notificationRoleId:roleId,sessionId:null}}),delivery:()=>({read:async()=>state,claim:async()=>{state={state:'SENDING'};return true;},complete:async messageId=>{state={state:'SENT',messageId};}})};const role={id:roleId,mentionable:true,managed:false,permissions:{bitfield:0n}},channel={isSendable:()=>true,messages:{fetch:async()=>new Map()},send:async payload=>{sent=payload;sends++;return{id:'message'};}},client={channels:{fetch:async()=>channel},guilds:{fetch:async()=>({id:'g',roles:{fetch:async()=>role}})},user:{id:'bot'}},coordinator=new DiscordSpecialCoordinator(repo,config(),async()=>true);await coordinator.deliver(client,'job');await coordinator.deliver(client,'job');assert.equal(sends,1);assert.deepEqual(sent.allowedMentions,{parse:[],roles:[roleId],users:[],repliedUser:false});assert.equal(sent.embeds[0].toJSON().footer,undefined);assert.equal(sent.embeds[0].toJSON().url,specialDeliveryUrl('special:job'));assert.doesNotMatch(JSON.stringify(sent.embeds[0].toJSON()),/special:job/);assert.doesNotMatch(sent.content,/@everyone|<@123>/);});

const view={id:'id',guildId:'g',channelId:'main',messageId:'m',ownerId:'host',state:'OPEN',expiresAt:new Date('2026-09-25T12:00:30Z'),extensionUsed:false,members:[{userId:'host',name:'Host <&>',status:'ready'},{userId:'second',name:'Waiting',status:'waiting'}],remainingMs:30000,elapsedMs:0};
test('Runtime Line renderer uses escaped saved names, actual check-ins and exact remaining sequence',()=>{const svg=renderLine(view);assert.match(svg,/Host &lt;&amp;&gt;/);assert.match(svg,/One second/);assert.doesNotMatch(svg,/>Jordan</);assert.match(svg,/30 seconds/);assert.equal(svg,renderLine(view));const full=lineSequence({...view,state:'SETTLING'});assert.equal(full.frames.length,37);assert.equal(full.delays.reduce((a,b)=>a+b,0),10000);const resumed=lineSequence({...view,state:'SETTLING',elapsedMs:2400});assert.match(resumed.frames[0],/>3<\/text>/);assert.doesNotMatch(resumed.frames[0],/>5<\/text>/);assert.ok(full.frames.some(svg=>/>0<\/text>/.test(svg)));assert.match(full.frames.at(-1),/Line complete/);});
test('Line public controls preserve locked check-ins and have no replay',async()=>{const coordinator=new DiscordSpecialCoordinator(forbidden,config(),async()=>true);for(const state of ['OPEN','LOCKED','CLOSED','CANCELLED']){const payload=await coordinator.payload({...view,state});const labels=controls(payload).map(c=>c.label);assert.ok(labels.every(s=>!/Again|Rematch/.test(s)));if(state==='LOCKED'){assert.ok(labels.includes('Start Countdown'));assert.ok(labels.includes('Cancel Line'));assert.ok(!labels.includes('I’m In'));}if(['CLOSED','CANCELLED'].includes(state))assert.deepEqual(labels,['Check-ins']);assert.ok(payload.files[0].attachment.length>1000);}});
test('countdown rendering finishes before authoritative timer starts',async()=>{const calls=[];let state='OPEN';const repo={publicView:async()=>({...view,state}),previewCountdown:async()=>({version:3}),countdown:async()=>{assert.deepEqual(calls,['rendered']);calls.push('started');state='SETTLING';}};const coordinator=new DiscordSpecialCoordinator(repo,config(),async()=>true);coordinator.payload=async()=>{calls.push('rendered');return{embeds:[]};};const i=interaction();i.message.embeds=[];i.message.edit=async()=>calls.push('published');await coordinator.handle(i);assert.deepEqual(calls,['rendered','started','published']);});
test('restart refresh never publishes outdated countdown after rasterization crosses completion',async()=>{const calls=[];let reads=0,completed=false;const repo={publicView:async()=>{reads++;return{...view,state:completed?'CLOSED':'SETTLING',elapsedMs:reads===1?1000:10000};},complete:async()=>{completed=true;calls.push('completed');}};const coordinator=new DiscordSpecialCoordinator(repo,config(),async()=>true);coordinator.payload=async v=>({embeds:[],state:v.state});const message={author:{id:'bot'},embeds:[],edit:async payload=>calls.push(payload.state)},client={user:{id:'bot'},channels:{fetch:async()=>({isTextBased:()=>true,messages:{fetch:async()=>message}})}};await coordinator.refresh(client,'id');assert.deepEqual(calls,['completed','CLOSED']);});


test('wide Line frame is deterministic and unchanged readiness time does not reupload',async()=>{
 const svg=renderLine(view,0,'wide');assert.match(svg,/width="1200" height="640"/);const updated=renderLine({...view,remainingMs:40000},0,'wide');assert.notEqual(svg,updated);assert.match(svg,/READINESS OPEN/);assert.match(updated,/0:40/);assert.doesNotMatch(svg,/STARTS IN/);assert.match(svg,/Host &lt;&amp;&gt;/);
 let current=view,edits=0;const c=new DiscordSpecialCoordinator({publicView:async()=>current},config(),async()=>true);c.payload=async()=>({embeds:[]});
 const client={user:{id:'bot'},channels:{fetch:async()=>({isTextBased:()=>true,messages:{fetch:async()=>({author:{id:'bot'},attachments:new Map(),embeds:[{footer:{text:'special:legacy'}}],edit:async p=>{assert.deepEqual(p.embeds,[]);edits++;}})}})}};
 await c.refresh(client,'id');current={...view,remainingMs:40000};await c.refresh(client,'id');assert.equal(edits,1);current={...current,extensionUsed:true};await c.refresh(client,'id');assert.equal(edits,2);
 const remaining=lineSequence({...view,state:'SETTLING',elapsedMs:4900},'wide');assert.ok(remaining.frames[0].includes('data-countdown-number="1"'));assert.equal(remaining.delays.reduce((a,b)=>a+b,0),6000);
});
test('Line success is silent and genuine failures never overwrite the shared message',async()=>{
 for(const fail of [false,true]){const i=interaction();i.customId='line:extend:id';const c=new DiscordSpecialCoordinator({publicView:async()=>view,extend:async()=>{if(fail)throw Error('failure');}},config(),async()=>true);c.refresh=async()=>{};await c.handle(i);assert.equal(i.deferred,true);assert.equal(i.calls.length,fail?1:0);if(fail)assert.equal(i.calls[0].ephemeral,true);}
});
test('Line delivery recovery uses hidden control identity or legacy footer without duplicate sends',async()=>{
 for(const legacy of [false,true]){let linked,sends=0,state={state:'SENDING'};const repo={callout:async()=>({payload:{guildId:'g',channelId:'main',sessionId:'id',content:'Gather'}}),delivery:()=>({read:async()=>state,complete:async messageId=>{state={state:'SENT',messageId};}}),linkMessage:async(...args)=>{linked=args;}};
 const saved={id:'m',author:{id:'bot'},embeds:legacy?[{footer:{text:'special:job'}}]:[],components:legacy?[]:[{components:[{customId:'line:status:id'}]}]};
 const client={user:{id:'bot'},guilds:{fetch:async()=>({})},channels:{fetch:async()=>({isSendable:()=>true,messages:{fetch:async()=>({find:fn=>fn(saved)?saved:undefined})},send:async()=>{sends++;}})}};
 await new DiscordSpecialCoordinator(repo,config(),async()=>true).deliver(client,'job');assert.equal(sends,0);assert.deepEqual(linked,['id','g','m']);
 }
});

test('new Line publication has no visible delivery ID and keeps recoverable controls',async()=>{
 let state={state:'PENDING'},sent;const repo={callout:async()=>({payload:{guildId:'g',channelId:'main',sessionId:'id',content:'Gather'}}),publicView:async()=>view,delivery:()=>({read:async()=>state,claim:async()=>{state={state:'SENDING'};return true;},complete:async messageId=>{state={state:'SENT',messageId};}}),linkMessage:async()=>{}};
 const client={user:{id:'bot'},guilds:{fetch:async()=>({})},channels:{fetch:async()=>({isSendable:()=>true,messages:{fetch:async()=>({find:()=>undefined})},send:async p=>{sent=p;return{id:'m'};}})}};
 await new DiscordSpecialCoordinator(repo,config(),async()=>true).deliver(client,'internal-job');assert.deepEqual(sent.embeds,[]);assert.ok(!JSON.stringify(sent.components).includes('internal-job'));assert.ok(controls(sent)[0].custom_id.startsWith('line:ready:id'));
});

test('automatic readiness expiry renders before starting the saved countdown and publishes only once',async()=>{
 let current={...view,state:'LOCKED'},edits=0;const calls=[];const repo={publicView:async()=>current,lock:async()=>{calls.push('lock');current={...current,state:'SETTLING',elapsedMs:0,durationMs:9000};}};
 const c=new DiscordSpecialCoordinator(repo,config(),async()=>true);c.payload=async()=>{calls.push('render');return{};};const client={user:{id:'bot'},channels:{fetch:async()=>({isTextBased:()=>true,messages:{fetch:async()=>({author:{id:'bot'},attachments:{some:()=>false},edit:async()=>{edits++;}})}})}};
 await Promise.all([c.advance(client,'g','id',false),c.advance(client,'g','id',false)]);assert.deepEqual(calls,['render','lock']);assert.equal(edits,1);
});
test('restart adopts the existing countdown gallery without replacing or restarting its GIF',async()=>{
 const c=new DiscordSpecialCoordinator({publicView:async()=>({...view,state:'SETTLING',elapsedMs:2000,durationMs:9000})},config(),async()=>true);c.payload=async()=>{throw Error('must not rasterize or replay');};
 const client={user:{id:'bot'},channels:{fetch:async()=>({isTextBased:()=>true,messages:{fetch:async()=>({author:{id:'bot'},attachments:{some:fn=>fn({name:'line-live.gif'})},edit:async()=>{throw Error('must not edit');}})}})}};await c.refresh(client,'id');
});


test('direct notification uncertain recovery recognizes hashed URL and legacy footer without another ping',async()=>{for(const legacy of [false,true]){let state={state:'SENDING'},sends=0;const marker='special:internal-job',saved={id:'published',author:{id:'bot'},embeds:legacy?[{footer:{text:marker}}]:[{url:specialDeliveryUrl(marker)}],components:[]},repo={callout:async()=>({payload:{guildId:'g',channelId:'main',sessionId:null,notificationRoleId:null,content:'Gather.'}}),delivery:()=>({read:async()=>state,complete:async messageId=>{state={state:'SENT',messageId};}})},client={user:{id:'bot'},channels:{fetch:async()=>({isSendable:()=>true,messages:{fetch:async()=>({find:fn=>fn(saved)?saved:undefined})},send:async()=>{sends++;}})}};await new DiscordSpecialCoordinator(repo,config(),async()=>true).deliver(client,'internal-job');assert.equal(sends,0);assert.deepEqual(state,{state:'SENT',messageId:'published'});}});
