import test from 'node:test';
import assert from 'node:assert/strict';
import {renderWyrOpen,renderWyrResults} from '../../dist/packages/features-wyr/src/render.js';
import {DiscordWyrCoordinator} from '../../dist/apps/bot/src/discord/wyr-coordinator.js';
const s={id:'hidden-session',guildId:'g',channelId:'games',messageId:'message',state:'OPEN',expiresAt:new Date('2026-09-26T12:00:30Z'),data:{category:'Casual',question:'Choose your seat & your story',optionA:'A quiet library',optionB:'An unexpected adventure',durationSeconds:30,extensionSeconds:30},extensionUsed:false};
test('WYR has wide branded readable choices with stable artwork as clock ticks and votes change',()=>{const svg=renderWyrOpen(s,30);assert.match(svg,/width="1200"/);assert.match(svg,/Cinzel/);assert.match(svg,/Poppins/);assert.match(svg,/#3B82F6/);assert.match(svg,/&amp;/);assert.doesNotMatch(svg,/hidden-session/);assert.equal(svg,renderWyrOpen({...s,votes:[{userId:'secret',choice:'A'}]},1));});
test('WYR result handles zero, tie and majority without clipping long choices',()=>{for(const result of [{A:0,B:0,total:0,winner:'NONE'},{A:1,B:1,total:2,winner:'TIE'},{A:2,B:1,total:3,winner:'A'}]){const svg=renderWyrResults({...s,data:{...s.data,optionA:'A long but readable choice '.repeat(10)}},result),height=+svg.match(/<svg[^>]*height="(\d+)"/)[1];assert.match(svg,new RegExp(result.total+' total votes'));for(const t of svg.matchAll(/<text[^>]* y="(\d+)"/g))assert.ok(+t[1]<height);assert.doesNotMatch(svg,/NaN|undefined/);}});
test('WYR hidden voting acknowledges before config work and does not edit the public image',async()=>{const order=[],i={customId:'wyr:vote:A:hidden-session',guildId:'g',guild:{},channelId:'games',message:{id:'message'},user:{id:'voter'},deferReply:async()=>order.push('ack'),editReply:async()=>order.push('receipt'),client:{}};const c=new DiscordWyrCoordinator({get:async()=>s,vote:async()=>{order.push('vote');return s;}},{get:async(g,k)=>{order.push('config');return k==='features.party_games'?true:'games';}},async()=>true);await c.handleButton(i);assert.equal(order[0],'ack');assert.deepEqual(order.slice(-2),['vote','receipt']);});
test('WYR final edits serialize, skip repeated artwork and retain retry after failure',async()=>{const closed={...s,state:'CLOSED'},svg=renderWyrResults(closed,{A:1,B:0,total:1,winner:'A'});let edits=0,fail=true;const service={get:async()=>closed,close:async()=>({session:closed,svg})},client={user:{id:'bot'},guilds:{fetch:async()=>({channels:{fetch:async()=>({isTextBased:()=>true,messages:{fetch:async()=>({author:{id:'bot'},edit:async p=>{edits++;assert.equal(p.embeds[0].toJSON().footer,undefined);if(fail){fail=false;throw Error('delivery failed');}}})}})}})}};const c=new DiscordWyrCoordinator(service);await assert.rejects(c.advance(client,s.id));await Promise.all([c.advance(client,s.id),c.advance(client,s.id)]);assert.equal(edits,2);});
