import {DomainError} from '../../core/src/errors.js';
import type {ChairismReference,ChairismOptions,ChairismSnapshot} from './interfaces.js';
export const CHAIRISM_TEXT_LIMIT=1200;
export function validateChairismExcludedChannels(value:unknown):value is string[]{return Array.isArray(value)&&value.length<=100&&value.every(id=>typeof id==='string'&&/^\d{17,20}$/.test(id))&&new Set(value).size===value.length;}
export function normalizeQuoteText(value:string){const text=value.replace(/\r\n?/g,'\n').replace(/[\u0000-\u0008\u000b\u000c\u000e-\u001f\u007f]/g,'').trim();if(!text||[...text].length>CHAIRISM_TEXT_LIMIT||text.split('\n').length>30)throw new DomainError('CHAIRISM_TEXT',`Use 1–${CHAIRISM_TEXT_LIMIT} characters and at most 30 lines of quote text.`);return text;}
export function parseChairismLink(value:string,guildId:string):ChairismReference{let url:URL;try{url=new URL(value);}catch{throw new DomainError('CHAIRISM_LINK','Use a message link from this server.');}const match=url.pathname.match(/^\/channels\/(\d{17,20})\/(\d{17,20})\/(\d{17,20})$/);if(url.protocol!=='https:'||!['discord.com','www.discord.com','ptb.discord.com','canary.discord.com'].includes(url.hostname)||url.username||url.password||url.port||url.search||url.hash||!match||match[1]!==guildId)throw new DomainError('CHAIRISM_LINK','Use a message link from this server.');return{channelId:match[2]!,messageId:match[3]!};}
export function chairismOptions(mode:string):ChairismOptions{if(!['short','long','this','reply','image','both'].includes(mode))throw new DomainError('CHAIRISM_OPTION','Choose one of the available quote options.');return{includeReply:mode==='reply'||mode==='both',includeImage:mode==='image'||mode==='both'};}
export function quoteLines(value:string,width=43){const out:string[]=[];for(const paragraph of value.split('\n')){let line='';for(const token of paragraph.split(/\s+/).filter(Boolean)){let word=token;while([...word].length>width){if(line){out.push(line);line='';}out.push([...word].slice(0,width).join(''));word=[...word].slice(width).join('');}if([...line,...word].length+(line?1:0)>width){out.push(line);line='';}line+=(line?' ':'')+word;}out.push(line);}return out;}
/** Renderer accepts already-reviewed embedded bytes only; no remote URL fetch occurs here. */
export function isEmbeddedChairismImage(value:string){return /^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/]+={0,2}$/.test(value)&&value.length<=8_000_000;}
export function validateSnapshot(snapshot:ChairismSnapshot){for(const q of [snapshot.quote,...(snapshot.reply?[snapshot.reply]:[])]){normalizeQuoteText(q.text);if(!q.userId||!q.displayName.trim()||q.displayName.length>100||!Number.isFinite(Date.parse(q.timestamp)))throw new DomainError('CHAIRISM_SNAPSHOT','Quote metadata is invalid.');if(q.avatarDataUri&&!isEmbeddedChairismImage(q.avatarDataUri))throw new DomainError('CHAIRISM_MEDIA','Quote image data is invalid.');}if(snapshot.imageDataUri&&!isEmbeddedChairismImage(snapshot.imageDataUri))throw new DomainError('CHAIRISM_MEDIA','Quote image data is invalid.');}
export function chairismJump(guildId:string,channelId:string,messageId:string){if(![guildId,channelId,messageId].every(id=>/^\d{17,20}$/.test(id)))throw new DomainError('CHAIRISM_OUTPUT','Chairism publication did not return a valid destination.');return`https://discord.com/channels/${guildId}/${channelId}/${messageId}`;}
