import {shell,ink,text} from '../../features-events/src/visual.js';
import {centeredBlock,portrait} from '../../features-events/src/gate-b-visual.js';
export const CHAIRISMS_ACCENT='#F59E0B';
export function chairismPlate(y:number,height:number,x=30,width=1140){return `<rect x="${x}" y="${y}" width="${width}" height="${height}" rx="22" fill="url(#chairism-glass)" stroke="${CHAIRISMS_ACCENT}" stroke-opacity=".7" stroke-width="2"/><rect x="${x+8}" y="${y+8}" width="${width-16}" height="${height-16}" rx="16" fill="none" stroke="${ink.gold}" stroke-opacity=".25"/><path d="M${x+20} ${y+56}V${y+20}H${x+68}M${x+width-68} ${y+height-20}H${x+width-20}V${y+height-56}" fill="none" stroke="${ink.gold}" stroke-width="3"/><path d="M${x+80} ${y+9}H${x+width-80}" stroke="#FFE0A0" stroke-opacity=".5"/>`;}
export function chairismFrame(height:number,body:string){return shell(height,`<defs><linearGradient id="chairism-glass" x2="1" y2="1"><stop stop-color="#513824" stop-opacity=".97"/><stop offset=".35" stop-color="#25211F" stop-opacity=".96"/><stop offset="1" stop-color="#0B1220" stop-opacity=".98"/></linearGradient></defs><rect width="1200" height="${height}" fill="#342318" opacity=".32"/>${body}`,0,1200).replaceAll('Inter','Poppins').replaceAll('Space Grotesk','Cinzel').replace('stroke="#00D7CF"',`stroke="${CHAIRISMS_ACCENT}"`);}
export function chairismHeading(title:string){return chairismPlate(26,126)+text(600,65,'ANGRIER JORDAN · PRESERVED IN THE LOUNGE',20,ink.warm,'text-anchor="middle" letter-spacing="3" font-weight="700"')+text(600,122,title,42,ink.white,'text-anchor="middle" font-family="Cinzel" font-weight="700"');}
export function renderChairismNotice(message:string){const block=centeredBlock(message,220,{cx:600,width:1010,size:34,weight:600,lineHeight:48});const height=Math.max(145,block.height+70);return chairismFrame(180+height+30,chairismHeading('Chairisms')+chairismPlate(176,height)+block.svg);}
export function renderChairismBrowser(rows:readonly {chairismId:number;createdAt:string;name?:string;avatarData?:string}[],mode:string){let body=chairismHeading(mode==='random'?'A moment from the lounge':'The Chairisms archive');if(!rows.length)return chairismFrame(510,body+chairismPlate(180,290)+text(600,263,'Your lounge has stories worth keeping.',38,ink.white,'text-anchor="middle" font-weight="700"')+text(600,325,'No eligible Chairisms here yet.',30,ink.warm,'text-anchor="middle"')+text(600,399,'Right-click a message · Apps · Create Chairism',27,ink.white,'text-anchor="middle"'));
 for(let n=0;n<rows.length;n++){const row=rows[n]!,x=30+(n%2)*580,y=180+Math.floor(n/2)*168;body+=chairismPlate(y,152,x,560)+portrait('browser-'+row.chairismId,row.name??'Member',row.avatarData,x+70,y+36,70)+text(x+316,y+42,`Chairism #${row.chairismId}`,31,ink.white,'text-anchor="middle" font-weight="700"')+centeredBlock((row.name??'Community member').length>26?(row.name??'').slice(0,25)+'…':row.name??'Community member',y+80,{cx:x+316,width:420,size:24,weight:600}).svg+text(x+316,y+125,new Date(row.createdAt).toISOString().slice(0,10)+' · Open below',23,ink.warm,'text-anchor="middle"');}const bottom=180+Math.ceil(rows.length/2)*168;return chairismFrame(Math.max(400,bottom+60),body+text(600,bottom+25,'MEMBER VOICES · MOMENTS KEPT',20,ink.warm,'text-anchor="middle" letter-spacing="3"'));}
