import {shell,ink,text} from '../../features-events/src/visual.js';
import {portrait} from '../../features-events/src/gate-b-visual.js';
import {wrapText} from '../../renderer/src/text-layout.js';
export const CHAIRISMS_ACCENT='#F59E0B';
export function chairismTextBlock(value:string,x:number,y:number,options:{size?:number;color?:string;width?:number;weight?:number;lineHeight?:number}={}){
 const {size=32,color=ink.white,width=1000,weight=400,lineHeight=Math.ceil(size*1.25)}=options,rows=wrapText(value,width,size);
 return {svg:rows.map((row,n)=>text(x,y+n*lineHeight,row,size,color,`text-anchor="start" font-weight="${weight}"`)).join(''),height:rows.length*lineHeight};
}
export function chairismPlate(y:number,height:number,x=30,width=1140){return `<rect x="${x}" y="${y}" width="${width}" height="${height}" rx="22" fill="url(#chairism-glass)" stroke="${CHAIRISMS_ACCENT}" stroke-opacity=".7" stroke-width="2"/><rect x="${x+8}" y="${y+8}" width="${width-16}" height="${height-16}" rx="16" fill="none" stroke="${ink.gold}" stroke-opacity=".25"/><path d="M${x+20} ${y+56}V${y+20}H${x+68}M${x+width-68} ${y+height-20}H${x+width-20}V${y+height-56}" fill="none" stroke="${ink.gold}" stroke-width="3"/><path d="M${x+80} ${y+9}H${x+width-80}" stroke="#FFE0A0" stroke-opacity=".5"/>`;}
export function chairismFrame(height:number,body:string){return shell(height,`<defs><linearGradient id="chairism-glass" x2="1" y2="1"><stop stop-color="#513824" stop-opacity=".97"/><stop offset=".35" stop-color="#25211F" stop-opacity=".96"/><stop offset="1" stop-color="#0B1220" stop-opacity=".98"/></linearGradient></defs><rect width="1200" height="${height}" fill="#342318" opacity=".32"/>${body}`,0,1200).replace('stroke="#00D7CF"',`stroke="${CHAIRISMS_ACCENT}"`);}
export function chairismHeading(title:string){return chairismPlate(26,60)+text(78,67,title,32,ink.white,'text-anchor="start" font-family="Space Grotesk" font-weight="700"')+text(1122,64,'ANGRIER JORDAN',20,ink.warm,'text-anchor="end" letter-spacing="2"');}
export function renderChairismNotice(message:string){const block=chairismTextBlock(message,78,166,{width:1044,size:34,weight:500,lineHeight:44}),height=block.height+76;return chairismFrame(106+height+24,chairismHeading('Chairisms')+chairismPlate(106,height)+block.svg);}
export function renderChairismBrowser(rows:readonly {chairismId:number;createdAt:string;name?:string;avatarData?:string}[],mode:string){let body=chairismHeading(mode==='random'?'A moment from the lounge':'The Chairisms archive');if(!rows.length)return chairismFrame(362,body+chairismPlate(106,232)+text(78,170,'Your lounge has stories worth keeping.',36,ink.white,'text-anchor="start" font-weight="600"')+text(78,225,'No eligible Chairisms here yet.',28,ink.warm,'text-anchor="start"')+text(78,290,'Right-click a message · Apps · Create Chairism',26,ink.white,'text-anchor="start"'));
 for(let n=0;n<rows.length;n++){const row=rows[n]!,x=30+(n%2)*580,y=106+Math.floor(n/2)*168;body+=chairismPlate(y,152,x,560)+portrait('browser-'+row.chairismId,row.name??'Member',row.avatarData,x+70,y+36,70)+text(x+130,y+44,`Chairism #${row.chairismId}`,29,ink.white,'text-anchor="start" font-weight="600"')+chairismTextBlock((row.name??'Community member').length>26?(row.name??'').slice(0,25)+'…':row.name??'Community member',x+130,y+83,{width:386,size:24,weight:500}).svg+text(x+130,y+124,new Date(row.createdAt).toISOString().slice(0,10)+' · Open below',21,ink.warm,'text-anchor="start"');}const bottom=106+Math.ceil(rows.length/2)*168;return chairismFrame(bottom+56,body+text(78,bottom+22,'MEMBER VOICES · MOMENTS KEPT',20,ink.warm,'text-anchor="start" letter-spacing="2"'));}
