import {randomUUID} from 'node:crypto';
import {Prisma,type PrismaClient} from '@prisma/client';
import {AuditService,DomainError,SessionEngine,TimerEngine,VotingEngine,type Session,type LedgerEngine} from '../../core/src/index.js';
import {PrismaAtomicOperations,requestFingerprint} from '../../database/src/atomic-operations.js';
import {PrismaTransactionSessions} from '../../database/src/transaction-sessions.js';
import {PrismaWagerEscrow} from '../../database/src/wager-escrow.js';
import {PrismaJobDeliveryRepository} from '../../database/src/job-delivery.js';
import {grantCatalogReward} from '../../features-economy/src/catalog-grants.js';
import {COMMUNITY_KINDS,SUGGESTION_STATUSES,clean,choicesFrom,tally,tieOrder,validateRanking,parsePrize,type CommunityData,type CommunityKind,type CommunityMember,type Prize} from './domain.js';
export interface CommunityContext {guildId:string;channelId:string;userId:string;requestKey:string;manage?:boolean;}
export interface CommunityStart {kind:CommunityKind;text:string;name?:string;anonymous?:boolean;choices?:string;maxChoices?:number;minutes?:number;hidden?:boolean;ranked?:boolean;winnerCount?:number;fee?:number;maxFee?:number;}
const json=(v:unknown)=>JSON.parse(JSON.stringify(v)) as Prisma.InputJsonObject;
const type='community';
export class PrismaCommunityRepository {
 private atomic:PrismaAtomicOperations;
 constructor(private db:PrismaClient,private clock:()=>Date=()=>new Date()){this.atomic=new PrismaAtomicOperations(db);}
 async suggestionPanel(guildId:string){return this.db.suggestionPanel.findUnique({where:{guildId}});}
 async rememberSuggestionPanel(guildId:string,channelId:string,messageId:string){return this.db.suggestionPanel.upsert({where:{guildId},create:{guildId,channelId,messageId},update:{channelId,messageId}});}
 private admin(c:CommunityContext){if(!c.manage)throw new DomainError('COMMUNITY_ADMIN','This action requires Chaise Lounge or Throne.');}
 private async eligible(tx:Prisma.TransactionClient,guildId:string,userId:string){if(await tx.jailSentence.findFirst({where:{guildId,userId,active:true,OR:[{indefinite:true},{pausedAt:{not:null}},{endsAt:{gt:this.clock()}}]}}))throw new DomainError('COMMUNITY_RESTRICTED','Community actions are unavailable while restricted.');}
 async get(id:string){const s=await this.db.gameSession.findUnique({where:{id}});if(!s||s.type!==type)throw new DomainError('COMMUNITY_MISSING','This community post is unavailable.');return{...s,data:s.data as unknown as CommunityData};}
 async active(guildId?:string){return this.db.gameSession.findMany({where:{type,state:'OPEN',...(guildId?{guildId}:{})}});}
 async linkMessage(id:string,guildId:string,messageId:string){await this.db.gameSession.updateMany({where:{id,guildId,type,messageId:null},data:{messageId}});}
 delivery(id:string){return new PrismaJobDeliveryRepository(this.db,id);}
 async initialPublication(id:string){return this.db.scheduledJob.findUniqueOrThrow({where:{executionKey:`community:publish:${id}:0`}});}
 async deliveryJob(id:string){const job=await this.db.scheduledJob.findUniqueOrThrow({where:{id}});if(job.jobType!=='community.publish')throw new DomainError('COMMUNITY_JOB','Invalid publication.');return job.payload as {guildId:string;channelId:string;sessionId:string};}
 private async session(tx:Prisma.TransactionClient,c:Pick<CommunityContext,'guildId'|'channelId'>,id:string){const s=await new PrismaTransactionSessions(tx).get<CommunityData>(id);if(!s||s.type!==type||s.guildId!==c.guildId||s.channelId!==c.channelId)throw new DomainError('COMMUNITY_MISSING','Use this post’s original server and channel.');return s;}
 private live(s:Session<CommunityData>){if(s.state!=='OPEN'||s.data.phase==='closed')throw new DomainError('COMMUNITY_CLOSED','This post is closed.');if(s.expiresAt&&s.expiresAt<=this.clock())throw new DomainError('COMMUNITY_EXPIRED','This phase has ended.');}
 private async publish(tx:Prisma.TransactionClient,s:Session<CommunityData>){const job=await tx.scheduledJob.upsert({where:{executionKey:`community:publish:${s.id}:${s.version}`},create:{guildId:s.guildId,jobType:'community.publish',executionKey:`community:publish:${s.id}:${s.version}`,dueAt:this.clock(),payload:{guildId:s.guildId,channelId:s.channelId,sessionId:s.id,deliveryState:'PENDING'}},update:{}});return job.id;}
 private async schedule(tx:Prisma.TransactionClient,s:Session<CommunityData>){if(s.expiresAt)await tx.scheduledJob.upsert({where:{executionKey:`community:advance:${s.id}:${s.data.round}`},create:{guildId:s.guildId,jobType:'community.advance',executionKey:`community:advance:${s.id}:${s.data.round}`,dueAt:s.expiresAt,payload:{guildId:s.guildId,sessionId:s.id,round:s.data.round}},update:{}});}
 private async save(tx:Prisma.TransactionClient,s:Session<CommunityData>,data:CommunityData,state=s.state,expiresAt=s.expiresAt){const saved=await new SessionEngine(new PrismaTransactionSessions(tx)).transition<CommunityData>(s.id,[s.state],state,current=>({...current,data,...(expiresAt?{expiresAt}:{})}));await this.publish(tx,saved);return saved;}
 private async audit(tx:Prisma.TransactionClient,c:CommunityContext,id:string,action:string,after:unknown){await new AuditService({write:async e=>{await tx.auditEvent.create({data:{guildId:e.guildId,actorUserId:e.actorUserId!,source:e.source,action:e.action,targetType:'community',targetId:id,after:json(e.after),requestId:e.requestId,createdAt:e.createdAt}});}}).record({guildId:c.guildId,actorUserId:c.userId,source:'discord',action,after,requestId:c.requestKey,createdAt:this.clock()});}
 private async prize(tx:Prisma.TransactionClient,value:string):Promise<Prize>{const p=parsePrize(value);if(['item','tool','collectible'].includes(p.kind)){const item=await tx.catalogItem.findUnique({where:{id:p.value}});if(!item?.enabled||p.kind!=='item'&&item.type!==p.kind)throw new DomainError('GIVEAWAY_PRIZE','Choose an enabled catalog reward of this type.');p.label=item.name;p.catalog={id:item.id,type:item.type,metadata:item.metadata};if(item.type==='tool'){const m=item.metadata as {slot?:string;maxDurability?:number}|null;if(!m?.slot||!['fishing_rod','shovel','scavenging_tool','workshop_tool'].includes(m.slot)||!Number.isSafeInteger(m.maxDurability??100)||(m.maxDurability??100)<1)throw new DomainError('GIVEAWAY_PRIZE','Tool reward configuration is invalid.');}if(item.type==='recipe'){const recipeId=(item.metadata as {recipeId?:string}|null)?.recipeId;if(!recipeId||!await tx.recipe.findFirst({where:{id:recipeId,enabled:true}}))throw new DomainError('GIVEAWAY_PRIZE','Recipe reward configuration is invalid.');}}else if(p.kind==='recipe'){const recipe=await tx.recipe.findFirst({where:{id:p.value,enabled:true}});if(!recipe)throw new DomainError('GIVEAWAY_PRIZE','Choose an enabled recipe.');p.label=recipe.name;}return p;}
 async start(c:CommunityContext,o:CommunityStart){if(!COMMUNITY_KINDS.includes(o.kind))throw new DomainError('COMMUNITY_KIND','Choose a community tool.');if(['superlatives','giveaway'].includes(o.kind))this.admin(c);const id=randomUUID();return this.atomic.run(c.guildId,'community:start:'+c.requestKey,requestFingerprint({userId:c.userId,channelId:c.channelId,o}),async tx=>{
  await this.eligible(tx,c.guildId,c.userId);const now=this.clock(),d:CommunityData={kind:o.kind,title:clean(o.text),phase:'open',round:0,anonymous:o.anonymous??false,hidden:o.hidden??true,ranked:o.ranked??false,choices:[],seed:randomUUID(),categories:[],entryCount:0};let expiresAt:Date|undefined;
  if(o.kind==='poll'){d.title=clean(o.text,200);d.choices=choicesFrom(o.choices??'',o.maxChoices??20);if(o.minutes!==undefined){if(!Number.isInteger(o.minutes)||o.minutes<1||o.minutes>10080)throw new DomainError('POLL_DURATION','Use a duration from 1 minute to 7 days.');expiresAt=TimerEngine.create(now,o.minutes*60).expiresAt;}}
  if(o.kind==='superlatives'){const names=o.text.split('|').map(x=>clean(x,80));if(!names.length||names.length>20||new Set(names.map(x=>x.toLowerCase())).size!==names.length)throw new DomainError('SUPERLATIVE_CATEGORIES','Use 1–20 distinct category names separated by |.');if(await tx.superlativeSeason.findFirst({where:{guildId:c.guildId,status:{in:['NOMINATIONS','VOTING']}}}))throw new DomainError('SUPERLATIVE_ACTIVE','A season is already active.');const latest=await tx.superlativeSeason.findFirst({where:{guildId:c.guildId},orderBy:{seasonNumber:'desc'}});d.season=(latest?.seasonNumber??0)+1;d.phase='nominations';d.anonymous=true;d.hidden=true;d.title='Superlatives · Season '+d.season;d.categories=names.map((name,n)=>({id:String(n+1),name,finalists:[]}));expiresAt=TimerEngine.create(now,48*3600).expiresAt;await tx.superlativeSeason.create({data:{id,guildId:c.guildId,seasonNumber:d.season,status:'NOMINATIONS',config:json({categories:d.categories}),nominationEndsAt:expiresAt}});}
  if(o.kind==='suggest'||o.kind==='ama'){d.title=clean(o.text,1000);d.status='OPEN';d.hidden=false;d.submitterName=clean(o.name??'Member',80);d.choices=o.kind==='ama'?[{id:'up',label:'Upvote'}]:[{id:'up',label:'Support'},{id:'down',label:'Oppose'}];if(o.kind==='suggest')await tx.suggestion.create({data:{id,guildId:c.guildId,submitterUserId:c.userId,anonymous:d.anonymous,text:d.title}});else await tx.amaQuestion.create({data:{id,guildId:c.guildId,submitterUserId:c.userId,anonymous:d.anonymous,question:d.title}});}
  if(o.kind==='giveaway'){const minutes=o.minutes??0,count=o.winnerCount??0,fee=o.fee??0,maxFee=o.maxFee??0;if(!Number.isInteger(minutes)||minutes<60||minutes>10080||!Number.isInteger(count)||count<1||count>5||!Number.isSafeInteger(maxFee)||maxFee<0||maxFee>5000||!Number.isSafeInteger(fee)||fee<0||fee>maxFee)throw new DomainError('GIVEAWAY_LIMITS','Giveaways require 1–5 winners, 1 hour–7 days and an entry fee within the configured economy limit.');d.prize=await this.prize(tx,o.text);d.title='Giveaway · '+d.prize.label;d.winnerCount=count;d.fee=String(fee);d.hidden=false;expiresAt=TimerEngine.create(now,minutes*60).expiresAt;await tx.giveaway.create({data:{id,guildId:c.guildId,creatorUserId:c.userId,prize:JSON.stringify(d.prize),winnerCount:count,entryCost:BigInt(fee),endsAt:expiresAt}});}
  const s:Session<CommunityData>={id,guildId:c.guildId,channelId:c.channelId,ownerUserId:c.userId,type,state:'OPEN',data:d,...(expiresAt?{expiresAt}:{}),extensionUsed:false,version:0,createdAt:now,updatedAt:now};await new PrismaTransactionSessions(tx).create({...s,data:json(d)});await this.schedule(tx,s);if(['giveaway','superlatives'].includes(o.kind))await this.audit(tx,c,id,'community.create',{kind:o.kind});return{sessionId:id,jobId:await this.publish(tx,s)};
 });}
 async vote(c:CommunityContext,id:string,choices:string[],category='main'){return this.atomic.run(c.guildId,'community:vote:'+c.requestKey,requestFingerprint({id,user:c.userId,choices,category}),async tx=>{await this.eligible(tx,c.guildId,c.userId);const s=await this.session(tx,c,id);this.live(s);const d=s.data;if(!['poll','suggest','ama','superlatives'].includes(d.kind)||d.kind==='superlatives'&&d.phase!=='voting')throw new DomainError('COMMUNITY_VOTE','Voting is unavailable.');const eligible=d.kind==='superlatives'?d.categories.find(x=>x.id===category)?.finalists.map(x=>x.id)??[]:d.choices.map(x=>x.id);validateRanking(choices,eligible);if(!d.ranked&&choices.length!==1)throw new DomainError('COMMUNITY_BALLOT','Choose one option.');const questionKey=d.kind==='superlatives'?'category:'+category:'main',old=await tx.vote.findMany({where:{sessionId:id,questionKey}});const engine=new VotingEngine({anonymous:d.anonymous,editable:true,hiddenUntilClose:d.hidden,eligibleChoices:eligible});for(const x of old)engine.cast(x.voterUserId,d.ranked?(JSON.parse(x.choiceKey) as string[])[0]!:x.choiceKey,x.updatedAt,questionKey);for(const [n,x]of choices.entries())engine.cast(c.userId,x,this.clock(),questionKey+':'+n);const choiceKey=d.ranked?JSON.stringify(choices):choices[0]!;await tx.vote.upsert({where:{sessionId_voterUserId_questionKey:{sessionId:id,voterUserId:c.userId,questionKey}},create:{sessionId:id,voterUserId:c.userId,questionKey,choiceKey,anonymous:d.anonymous},update:{choiceKey,anonymous:d.anonymous}});if(d.kind==='ama')await tx.amaQuestion.update({where:{id},data:{upvotes:old.length+(old.some(x=>x.voterUserId===c.userId)?0:1)}});await this.save(tx,s,d);return{sessionId:id};});}
 async nominate(c:CommunityContext,id:string,category:string,member:CommunityMember){return this.atomic.run(c.guildId,'community:nominate:'+c.requestKey,requestFingerprint({id,user:c.userId,category,member}),async tx=>{await this.eligible(tx,c.guildId,c.userId);await this.eligible(tx,c.guildId,member.id);const s=await this.session(tx,c,id);this.live(s);if(s.data.kind!=='superlatives'||s.data.phase!=='nominations'||!s.data.categories.some(x=>x.id===category))throw new DomainError('SUPERLATIVE_PHASE','Nominations are unavailable.');if(member.id===c.userId)throw new DomainError('SUPERLATIVE_SELF','You cannot nominate yourself.');if(await tx.superlativeEntry.findFirst({where:{seasonId:id,categoryKey:category,nominatorUserId:c.userId}}))throw new DomainError('SUPERLATIVE_ONCE','You already nominated in this category.');await tx.superlativeEntry.create({data:{seasonId:id,categoryKey:category,nomineeUserId:member.id,nominatorUserId:c.userId}});await tx.gameParticipant.upsert({where:{sessionId_userId:{sessionId:id,userId:member.id}},create:{sessionId:id,userId:member.id,role:'nominee',data:{name:clean(member.name,80)}},update:{data:{name:clean(member.name,80)}}});await this.save(tx,s,{...s.data,entryCount:s.data.entryCount+1});return{sessionId:id};});}
 async enter(c:CommunityContext,id:string,name:string,expectedFee:string){return this.atomic.run(c.guildId,'community:enter:'+c.requestKey,requestFingerprint({id,user:c.userId,expectedFee}),async(tx,ledger)=>{await this.eligible(tx,c.guildId,c.userId);const s=await this.session(tx,c,id);this.live(s);if(s.data.kind!=='giveaway')throw new DomainError('GIVEAWAY_ONLY','This control is for giveaways.');if(expectedFee!==s.data.fee)throw new DomainError('GIVEAWAY_FEE','Review the current entry fee before confirming.');if(await tx.giveawayEntry.findUnique({where:{giveawayId_userId:{giveawayId:id,userId:c.userId}}}))return{sessionId:id,alreadyEntered:true};const amount=BigInt(s.data.fee!),escrow=amount>0n?await new PrismaWagerEscrow(tx,ledger).reserve({guildId:c.guildId,userId:c.userId,amount,referenceType:'giveaway',referenceId:id,key:'giveaway:entry:'+id+':'+c.userId}):null;await tx.giveawayEntry.create({data:{giveawayId:id,userId:c.userId,escrowId:escrow?.id??null}});await tx.gameParticipant.create({data:{sessionId:id,userId:c.userId,role:'entrant',data:{name:clean(name,80)}}});await this.save(tx,s,{...s.data,entryCount:s.data.entryCount+1});return{sessionId:id,alreadyEntered:false};});}
 async moderate(c:CommunityContext,id:string,status:string,answer?:string){this.admin(c);return this.atomic.run(c.guildId,'community:moderate:'+c.requestKey,requestFingerprint({id,user:c.userId,status,answer:answer??null}),async tx=>{const s=await this.session(tx,c,id),d={...s.data};if(d.kind==='suggest'){if(!SUGGESTION_STATUSES.includes(status as typeof SUGGESTION_STATUSES[number]))throw new DomainError('SUGGESTION_STATUS','Choose an available status.');d.status=status;await tx.suggestion.update({where:{id},data:{status}});}else if(d.kind==='ama'){this.live(s);if(!['ANSWERED','DECLINED'].includes(status))throw new DomainError('AMA_STATUS','Answer or decline this question.');d.status=status;d.phase='closed';if(status==='ANSWERED')d.answer=clean(answer??'',1500);await tx.amaQuestion.update({where:{id},data:{status,answer:d.answer??null,answeredByUserId:c.userId,answeredAt:this.clock()}});}else throw new DomainError('COMMUNITY_MODERATE','No status action is available.');await this.save(tx,s,d,d.kind==='ama'?'CLOSED':s.state);await this.audit(tx,c,id,'community.status',{status,...(d.answer?{answer:d.answer}:{})});return{sessionId:id};});}
 async closePoll(c:CommunityContext,id:string){return this.atomic.run(c.guildId,'community:close:'+c.requestKey,requestFingerprint({id,user:c.userId}),async(tx,ledger)=>{const s=await this.session(tx,c,id);if(s.data.kind!=='poll'||s.ownerUserId!==c.userId&&!c.manage)throw new DomainError('POLL_OWNER','Only the poll creator or community admin may close it.');if(s.state==='CLOSED')return{sessionId:id};await this.finish(tx,ledger,s);await this.audit(tx,c,id,'community.poll_close',{});return{sessionId:id};});}
 async advance(guildId:string,id:string,round:number){return this.atomic.run(guildId,`community:advance:${id}:${round}`,String(round),async(tx,ledger)=>{const s=await new PrismaTransactionSessions(tx).get<CommunityData>(id);if(!s||s.guildId!==guildId||s.type!==type)throw new DomainError('COMMUNITY_MISSING','Community post unavailable.');if(s.state!=='OPEN'||s.data.round!==round)return{sessionId:id};if(!s.expiresAt||s.expiresAt>this.clock())throw new DomainError('NOT_DUE','The phase remains open.');if(s.data.kind==='superlatives'&&s.data.phase==='nominations'){const d={...s.data,categories:s.data.categories.map(x=>({...x})),phase:'voting' as const,round:round+1},nominations=await tx.superlativeEntry.findMany({where:{seasonId:id}}),members=await tx.gameParticipant.findMany({where:{sessionId:id}});for(const cat of d.categories){const totals:Record<string,number>={};for(const n of nominations.filter(x=>x.categoryKey===cat.id))totals[n.nomineeUserId]=(totals[n.nomineeUserId]??0)+1;const ids=tieOrder(d.seed+cat.id,Object.keys(totals)).sort((a,b)=>totals[b]!-totals[a]!).slice(0,5);cat.finalists=ids.map(id=>({id,name:(members.find(m=>m.userId===id)?.data as {name?:string}|null)?.name??'Member'}));await tx.superlativeEntry.updateMany({where:{seasonId:id,categoryKey:cat.id,nomineeUserId:{in:ids}},data:{finalist:true}});}const due=TimerEngine.create(this.clock(),48*3600).expiresAt,saved=await this.save(tx,s,d,'OPEN',due);await tx.superlativeSeason.update({where:{id},data:{status:'VOTING',votingEndsAt:due}});await this.schedule(tx,saved);}else await this.finish(tx,ledger,s);return{sessionId:id};});}
 private async finish(tx:Prisma.TransactionClient,ledger:LedgerEngine,s:Session<CommunityData>){const d={...s.data,categories:s.data.categories.map(x=>({...x}))};if(d.kind==='poll'){const result=tally(d.choices.map(x=>x.id),await tx.vote.findMany({where:{sessionId:s.id,questionKey:'main'}}),d.ranked,d.seed);d.results=result.totals;if(result.winnerId)d.winnerId=result.winnerId;}
  if(d.kind==='superlatives'){for(const cat of d.categories){if(!cat.finalists.length)continue;const result=tally(cat.finalists.map(x=>x.id),await tx.vote.findMany({where:{sessionId:s.id,questionKey:'category:'+cat.id}}),false,d.seed+cat.id),winnerId=result.winnerId??tieOrder(d.seed+cat.id,cat.finalists.map(x=>x.id))[0]!;cat.winner=cat.finalists.find(x=>x.id===winnerId)!;for(const finalist of cat.finalists)await tx.superlativeEntry.updateMany({where:{seasonId:s.id,categoryKey:cat.id,nomineeUserId:finalist.id},data:{winner:finalist.id===winnerId,voteCount:result.totals[finalist.id]??0}});const achievementId=`superlative:${s.guildId}:${d.season}:${cat.id}`;await tx.member.upsert({where:{guildId_userId:{guildId:s.guildId,userId:winnerId}},create:{guildId:s.guildId,userId:winnerId},update:{}});await tx.achievement.upsert({where:{id:achievementId},create:{id:achievementId,name:`Season ${d.season} · ${cat.name}`,class:'legacy',criteria:{type:'superlative',seasonId:s.id,category:cat.id}},update:{}});await tx.memberAchievement.upsert({where:{guildId_userId_achievementId:{guildId:s.guildId,userId:winnerId,achievementId}},create:{guildId:s.guildId,userId:winnerId,achievementId,metadata:{seasonId:s.id,category:cat.name}},update:{}});}await tx.superlativeSeason.update({where:{id:s.id},data:{status:'CLOSED',config:json({categories:d.categories})}});}
  if(d.kind==='giveaway'){const entrants=await tx.gameParticipant.findMany({where:{sessionId:s.id,role:'entrant'}}),winners=tieOrder(d.seed,entrants.map(x=>x.userId)).slice(0,d.winnerCount);d.winners=winners.map(id=>({id,name:(entrants.find(x=>x.userId===id)?.data as {name?:string}|null)?.name??'Member'}));await new PrismaWagerEscrow(tx,ledger).settle(s.guildId,'giveaway',s.id,new Map(),'giveaway:fees:'+s.id);for(const userId of winners){await tx.member.upsert({where:{guildId_userId:{guildId:s.guildId,userId}},create:{guildId:s.guildId,userId},update:{}});const p=d.prize!;if(p.kind==='ottomans')await ledger.apply({guildId:s.guildId,idempotencyKey:`giveaway:prize:${s.id}:${userId}`,lines:[{userId,bucket:'wallet',amount:BigInt(p.value),reason:'Giveaway prize'},{bucket:'system',amount:-BigInt(p.value),reason:'Admin-created giveaway prize'}]});else if(p.catalog)await grantCatalogReward(tx,s.guildId,userId,p.catalog,1);else if(p.kind==='recipe')await tx.ownedRecipe.upsert({where:{guildId_userId_recipeId:{guildId:s.guildId,userId,recipeId:p.value}},create:{guildId:s.guildId,userId,recipeId:p.value},update:{}});}d.status=d.prize?.kind==='custom'&&winners.length?'FULFILLMENT_PENDING':'COMPLETED';await tx.giveaway.update({where:{id:s.id},data:{status:d.status}});}
  d.phase='closed';await this.save(tx,s,d,'CLOSED');
 }
 async fulfill(c:CommunityContext,id:string){this.admin(c);return this.atomic.run(c.guildId,'community:fulfill:'+c.requestKey,requestFingerprint({id,user:c.userId}),async tx=>{const s=await this.session(tx,c,id);if(s.data.kind!=='giveaway'||s.data.prize?.kind!=='custom'||s.data.status!=='FULFILLMENT_PENDING')throw new DomainError('GIVEAWAY_FULFILL','No custom reward is awaiting fulfillment.');await tx.giveaway.update({where:{id},data:{status:'COMPLETED'}});await this.save(tx,s,{...s.data,status:'COMPLETED'});await this.audit(tx,c,id,'community.giveaway_fulfilled',{winners:s.data.winners});return{sessionId:id};});}
 async publicView(id:string){const s=await this.get(id),d=s.data,declined=d.kind==='ama'&&d.status==='DECLINED',ballots=await this.db.vote.findMany({where:{sessionId:id,questionKey:'main'}}),visible=!d.hidden||s.state==='CLOSED',result=visible&&d.choices.length?tally(d.choices.map(x=>x.id),ballots,d.ranked,d.seed):undefined;return{id:s.id,guildId:s.guildId,channelId:s.channelId,messageId:s.messageId,ownerId:d.anonymous?null:s.ownerUserId,state:s.state,version:s.version,expiresAt:s.expiresAt,kind:d.kind,phase:d.phase,round:d.round,title:declined?'This question is no longer available.':d.title,anonymous:d.anonymous,hidden:d.hidden,ranked:d.ranked,choices:declined?[]:d.choices,categories:d.categories,season:d.season,status:d.status,submitterName:d.anonymous?undefined:d.submitterName,answer:d.answer,prize:d.prize?{kind:d.prize.kind,label:d.prize.label}:undefined,fee:d.fee,winnerCount:d.winnerCount,winners:d.winners,entryCount:d.entryCount,results:declined?undefined:d.results??result?.totals,winnerId:d.winnerId,...(!d.anonymous&&visible&&!declined?{ballots:ballots.map(x=>({memberId:x.voterUserId,choices:d.ranked?JSON.parse(x.choiceKey) as string[]:[x.choiceKey]}))}:{})};}
 async archive(guildId:string,kind:'suggest'|'ama',userId:string,manage:boolean,query='',sort='newest',page=0){if(!Number.isSafeInteger(page)||page<0||page>100000)throw new DomainError('COMMUNITY_PAGE','Choose an available archive page.');const rows=kind==='suggest'?await this.db.suggestion.findMany({where:{guildId,text:{contains:query,mode:'insensitive'}},orderBy:[{createdAt:'desc'},{id:'desc'}],skip:page*20,take:20}):await this.db.amaQuestion.findMany({where:{guildId,...(manage?{}:{OR:[{status:{not:'DECLINED'}},{submitterUserId:userId}]}),question:{contains:query,mode:'insensitive'}},orderBy:sort==='upvotes'?[{upvotes:'desc'},{createdAt:'desc'},{id:'desc'}]:[{createdAt:'desc'},{id:'desc'}],skip:page*20,take:20});return rows.map(row=>({id:row.id,text:'text'in row?row.text:row.question,status:row.status,submitter:row.anonymous?null:row.submitterUserId,...('upvotes'in row?{upvotes:row.upvotes}:{}),mine:row.submitterUserId===userId}));}
}
export type CommunityView=Awaited<ReturnType<PrismaCommunityRepository['publicView']>>;
