import {wrapText,truncateText} from '../../renderer/src/text-layout.js';
import {shell,heading,panel,text,ink,lines} from '../../features-events/src/visual.js';
import type {CommunityView} from './prisma-repository.js';
const wrap=(value:string,max:number)=>wrapText(value,max,1);
const giveawayCounts=(v:CommunityView)=>{const winners=v.state==='CLOSED'?v.winners?.length??0:v.winnerCount;return `${winners} ${winners===1?'winner':'winners'} · ${v.entryCount} ${v.entryCount===1?'entry':'entries'}`;};
export const COMMUNITY_TITLES={poll:'Community Poll',superlatives:'Superlatives',suggest:'Suggestion',ama:'Ask Me Anything',giveaway:'Giveaway'};
function singleSuperlativeWinner(v:CommunityView){const category=v.categories[0]!,winner=category.winner!,center='text-anchor="middle"',nameLength=Array.from(winner.name).length,size=nameLength<=16?46:nameLength<=30?36:28,nameLines=wrap(winner.name,340/size),visible=nameLines.slice(0,3);let body=text(220,176,`SEASON ${v.season} · WINNER`,12,ink.warm,center+' letter-spacing="2" font-family="Space Grotesk" font-weight="600"');body+='<path d="M48 195H392" stroke="'+ink.gold+'" stroke-opacity=".45"/>';const categoryLines=wrap(category.name,340/20);for(const[n,line]of categoryLines.slice(0,3).entries())body+=text(220,231+n*27,n===2&&categoryLines.length>3?truncateText(line+'…',340,20):line,20,ink.warm,center);const start=350-(visible.length-1)*(size+10)/2;for(const[n,line]of visible.entries())body+=text(220,start+n*(size+10),n===2&&nameLines.length>3?truncateText(line+'…',340,size):line,size,ink.white,center+' font-family="Space Grotesk" font-weight="700"');body+=text(220,422,'SUPERLATIVE HONOR',12,ink.emerald,center+' letter-spacing="1.8" font-family="Space Grotesk"');body+=panel(42,455,356,103,ink.gold)+text(220,487,'SEASON BADGE EARNED',12,ink.warm,center+' letter-spacing="1.5" font-family="Space Grotesk" font-weight="600"')+text(220,523,'Saved to the member’s profile',16,ink.white,center);if(nameLines.length>3)body+=text(32,594,'Use Details for the complete winner name.',12,ink.muted);else if(categoryLines.length>3)body+=text(32,594,'Use Details for the complete category name.',12,ink.muted);return body;}
export function communityTranscript(v:CommunityView){const out=[COMMUNITY_TITLES[v.kind],v.title];if(v.kind==='superlatives'){out.push(`Season ${v.season} · ${v.phase}`);for(const c of v.categories)out.push(c.name,c.winner?'Winner: '+c.winner.name:c.finalists.length?'Finalists: '+c.finalists.map(m=>m.name).join(', '):v.phase==='closed'?'No nominations received.':'Nominations open.');out.push('Permanent season badges · no Ottoman prizes.');}for(const c of v.choices)out.push(`${c.id}. ${c.label}${v.results?' · '+(v.results[c.id]??0)+' votes':''}`);if(v.kind==='giveaway'){out.push(`Prize per winner: ${v.prize?.label}`,giveawayCounts(v),`Entry: ${v.fee==='0'?'free':v.fee+' Ottomans · fees removed from circulation'}`);if(v.winners)out.push(v.winners.length?'Winners: '+v.winners.map(m=>m.name).join(', '):'No entries received.');if(v.status==='FULFILLMENT_PENDING')out.push('Custom reward fulfillment is pending with the organizer.');}if(v.status)out.push('Status: '+v.status);if(v.answer)out.push('Answer: '+v.answer);if(v.submitterName)out.push('Submitted by '+v.submitterName);if(v.ballots?.length)out.push('Named ballots:',...v.ballots.map(b=>b.memberId+': '+b.choices.map(id=>v.choices.find(c=>c.id===id)?.label??id).join(' > ')));return out.join('\n');}
/** A deterministic production layout using the frozen Gate A lounge shell and typography. */
export function renderCommunity(v:CommunityView){const singleWinner=v.kind==='superlatives'&&v.phase==='closed'&&v.categories.length===1&&Boolean(v.categories[0]?.winner);let body=heading('ANGRIER JORDAN · COMMUNITY',COMMUNITY_TITLES[v.kind],v.kind==='superlatives'?`Season ${v.season} · ${v.phase==='closed'?singleWinner?'The winner':v.categories.some(c=>c.winner)?'The winners':'No winners':v.phase}`:v.state==='CLOSED'?'The result is in':v.kind==='poll'&&v.ranked?'Rank your choices · best first':'A voice in the lounge');body+=panel(18,137,404,473);let y=168,clipped=false;const add=(value:string,color=ink.white,size=17)=>{for(const line of wrap(value,376/size)){if(y>572){clipped=true;return;}body+=text(32,y,line,size,color);y+=25;}y+=8;};
 if(singleWinner)body+=singleSuperlativeWinner(v);else if(v.kind==='superlatives'){for(const c of v.categories){add(c.name,ink.warm,19);add(c.winner?c.winner.name:c.finalists.length?c.finalists.map(x=>x.name).join(' · '):v.phase==='closed'?'No nominations received':'Nominate another member',c.winner?ink.emerald:ink.white,17);}}else{add(v.title,ink.warm,19);if(v.submitterName)add('By '+v.submitterName,ink.muted,14);for(const c of v.choices)add(`${c.id}. ${c.label}${v.results?' · '+(v.results[c.id]??0):''}`,ink.white,16);if(v.answer)add(v.answer,ink.emerald);if(v.kind==='giveaway'){add(giveawayCounts(v),ink.emerald);add(v.fee==='0'?'Free entry':v.fee+' Ottomans per entry',ink.white);for(const m of v.winners??[])add(m.name,ink.warm,20);if(v.status==='FULFILLMENT_PENDING')add('Organizer fulfillment pending',ink.muted,14);}if(v.status)add(v.status.replaceAll('_',' '),['DECLINED','FULFILLMENT_PENDING','REVIEWING'].includes(v.status)?ink.warm:ink.emerald,15);}
 if(clipped)body+=text(32,594,'Use Details for the complete post.',12,ink.muted);body+=panel(18,627,404,94,ink.gold);const label=v.kind==='superlatives'?v.phase==='closed'?singleWinner?'Permanent season badge awarded':v.categories.some(c=>c.winner)?'Permanent season badges awarded':'No nominations · no badges awarded':'Anonymous nominations and ballots':v.kind==='giveaway'?v.state==='CLOSED'?v.status==='FULFILLMENT_PENDING'?'Draw saved · organizer fulfillment pending':v.winners?.length?'Draw saved · rewards recorded':'No entries · no prizes awarded':'One entry per member · fees are removed':v.hidden&&v.state==='OPEN'?'Results stay hidden until close':v.anonymous?'Anonymous to members':'Member choices are recorded';for(const[n,line]of lines(label,45).slice(0,2).entries())body+=text(32,656+n*23,line,15,ink.warm);body+=text(32,705,v.kind==='superlatives'?v.phase==='closed'?`Season ${v.season} · No Ottoman prize`:'48 hours for nominations · 48 hours for voting':'Use the controls below.',12,ink.muted);return shell(741,body);}
export function superlativeReviewFixture():CommunityView{return{id:'superlative-review',guildId:'fixture',channelId:'fixture',messageId:'fixture',ownerId:null,state:'CLOSED',version:12,expiresAt:new Date('2026-09-25T12:00:00Z'),kind:'superlatives',phase:'closed',round:1,title:'Superlatives · Season 1',anonymous:true,hidden:true,ranked:false,choices:[],categories:[{id:'1',name:'Most Likely to Bring a Spare Chair',finalists:[{id:'fixture-winner',name:'Morgan'}],winner:{id:'fixture-winner',name:'Morgan'}}],season:1,status:undefined,submitterName:undefined,answer:undefined,prize:undefined,fee:undefined,winnerCount:undefined,winners:undefined,entryCount:7,results:undefined,winnerId:undefined};}
