import {readFileSync} from 'node:fs';
import type {RaceView} from './prisma-repository.js';
const escape=(s:string)=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const chairs=new Map<number,string>();
function chair(n:number){if(!chairs.has(n))chairs.set(n,'data:image/png;base64,'+readFileSync(new URL(`../../../production/atomic_assets/race_fight/race_chair_${n}.png`,import.meta.url)).toString('base64'));return chairs.get(n)!;}
/** This is the production SVG, not a separate review mockup. */
export function renderRace(view:RaceView,layout:'compact'|'wide'='compact'){
 const width=1000,height=200+view.racers.length*112,live=view.state==='LOCKED',closed=view.state==='CLOSED',cancelled=view.state==='CANCELLED';
 const label=cancelled?'RACE CANCELLED':closed?'FINISH LINE':live?'CHAIR RACE · LIVE':'TAKE YOUR PLACE';
 const status=cancelled?view.cancelReason??'All wagers refunded.':closed?`${view.racers.find(r=>r.userId===view.winnerId)?.name??'Winner'} takes the win` :live?'One sprint. Equal odds.':'Join Race · choose a racer · place your private wager';
 if(layout==='compact'){
  const h=170+view.racers.length*128;
  const rows=view.racers.map((r,index)=>{const y=134+index*128,p=view.motion?.rows.find(p=>p.userId===r.userId),progress=p?.progress??0,x=40+progress*3.2;return`<rect x="12" y="${y-20}" width="416" height="118" rx="12" fill="${index%2?'#142333':'#10202d'}"/><text x="24" y="${y+3}" font-size="18" font-weight="600" fill="#f1eee6">${escape(r.name.slice(0,23))}</text><text x="24" y="${y+28}" font-size="15" fill="#a8bac5">Chair ${r.chair}${p?' · Place '+p.place:''}</text><rect x="40" y="${y+82}" width="320" height="7" rx="3" fill="#304655"/><rect x="40" y="${y+82}" width="${progress*3.2}" height="7" rx="3" fill="#21c6a5"/><path d="M360 ${y+34}V${y+79}" stroke="#d9be7b" stroke-dasharray="4 4"/><image href="${chair(r.chair)}" x="${x-25}" y="${y+30}" width="50" height="50"/><text x="412" y="${y+67}" text-anchor="end" font-size="18" fill="#e2c786">${Math.floor(progress)}%</text>`;}).join('');
  const line1=closed?'Winner: '+(view.racers.find(r=>r.userId===view.winnerId)?.name??''):cancelled?'All wagers refunded.':live?'One sprint. Equal odds.':'Join · pick a racer · place your wager';
  const footer=closed?view.result?.refunded?'Full refunds · no rake':`Pool ${view.result?.pool??0} · Rake ${view.result?.rake??0}`:`Pool ${view.pool} Ottomans · 5% rake`;
  return`<svg xmlns="http://www.w3.org/2000/svg" width="440" height="${h}" viewBox="0 0 440 ${h}"><rect width="440" height="${h}" rx="16" fill="#091520"/><g font-family="Poppins"><text x="20" y="36" font-family="Cinzel" font-size="23" font-weight="700" fill="#e2c786">${label}</text><text x="20" y="68" font-size="17" fill="#e1e8ea">${escape(line1.slice(0,38))}</text><text x="20" y="94" font-size="15" fill="#a8bac5">${view.racers.length}/6 racers · ${live?'Betting locked':closed?'Final result':cancelled?'Event closed':'60 seconds + one host extension'}</text>${rows}<text x="20" y="${h-14}" font-size="16" fill="#a8bac5">${escape(footer)}</text></g></svg>`;
 }
 const rows=view.racers.map((r,index)=>{const y=150+index*112,motion=view.motion?.rows.find(p=>p.userId===r.userId),progress=motion?.progress??0,x=277+(progress/100)*560;return`<g><rect x="24" y="${y-28}" width="952" height="100" rx="14" fill="${index%2?'#142333':'#10202d'}"/><text x="42" y="${y}" fill="#f1eee6" font-size="21" font-weight="600">${escape(r.name.slice(0,18))}</text><text x="42" y="${y+30}" fill="#a8bac5" font-size="16">Chair ${r.chair}${motion?' · Place '+motion.place:''}</text><rect x="310" y="${y+38}" width="560" height="8" rx="4" fill="#304655"/><rect x="310" y="${y+38}" width="${560*progress/100}" height="8" rx="4" fill="#21c6a5"/><path d="M870 ${y-18}V${y+33}" stroke="#d9be7b" stroke-dasharray="5 5"/><image href="${chair(r.chair)}" x="${x}" y="${y-37}" width="66" height="66"/><text x="940" y="${y+10}" text-anchor="end" fill="#d9be7b" font-size="22" font-weight="600">${Math.floor(progress)}%</text></g>`;}).join('');
 const footer=closed?view.result?.refunded?'No winning wagers · full refunds':`Pool ${view.result?.pool??'0'} · Rake ${view.result?.rake??'0'} Ottomans`:`Pool ${view.pool} Ottomans · 5% rake · ${view.racers.length}/6 racers`;
 return`<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}"><rect width="1000" height="${height}" rx="20" fill="#091520"/><g font-family="Poppins"><text x="30" y="40" font-family="Cinzel" font-size="27" font-weight="700" fill="#e2c786">${label}</text><text x="30" y="78" font-size="20" fill="#e1e8ea">${escape(status.slice(0,80))}</text>${rows}<text x="30" y="${height-20}" font-size="18" fill="#a8bac5">${escape(footer)}</text></g></svg>`;
}
