import {readFileSync} from 'node:fs';
const theme=JSON.parse(readFileSync(new URL('../../../production/theme/events_v3.json',import.meta.url),'utf8')) as {palette:{midnight:string;navy:string;slate:string;teal:string;emerald:string;gold:string;warm:string;white:string;muted:string}};
export const ink=theme.palette;
export const esc=(s:string)=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const assets=new Map<string,string>();
export function imageAsset(file:string){if(!assets.has(file))assets.set(file,`data:image/${file.endsWith('.webp')?'webp':'png'};base64,`+readFileSync(new URL('../../../production/event_art/v3/'+file,import.meta.url)).toString('base64'));return assets.get(file)!;}
export function art(kind:'race_chair'|'robo_fighter',n:number){return imageAsset(`${kind}_${n}.png`);}
export function text(x:number,y:number,value:string,size=16,color:string=ink.white,extra=''){return `<text x="${x}" y="${y}" font-size="${size}" fill="${color}" ${extra}>${esc(value)}</text>`;}
export function lines(value:string,max=38){const result:string[]=[];let line='';for(const word of value.split(/\s+/)){if(line&&line.length+word.length+1>max){result.push(line);line='';}line+=(line?' ':'')+word;}if(line)result.push(line);return result;}
export function panel(x:number,y:number,width:number,height:number,accent=ink.teal){return `<rect x="${x}" y="${y+3}" width="${width}" height="${height}" rx="10" fill="#000" opacity=".4"/><rect x="${x}" y="${y}" width="${width}" height="${height}" rx="10" fill="url(#glass)" stroke="${accent}" stroke-opacity=".65"/><path d="M${x+12} ${y+1}H${x+width-12}" stroke="#DDFBF7" stroke-opacity=".15"/>`;}
export function shell(height:number,body:string,phase=0,width=440){return `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}"><defs><clipPath id="window"><rect x="1" y="1" width="${width-2}" height="${height-2}" rx="13"/></clipPath><linearGradient id="glass" x2="0" y2="1"><stop stop-color="#173239" stop-opacity=".9"/><stop offset=".45" stop-color="#102630" stop-opacity=".88"/><stop offset="1" stop-color="#06131c" stop-opacity=".96"/></linearGradient><linearGradient id="shade" x2="0" y2="1"><stop stop-color="#00111B" stop-opacity=".25"/><stop offset=".55" stop-color="#00111B" stop-opacity=".15"/><stop offset="1" stop-color="#00111B" stop-opacity=".7"/></linearGradient><linearGradient id="rail" x2="0" y2="1"><stop stop-color="#51F7DC"/><stop offset=".45" stop-color="#00C9B4"/><stop offset="1" stop-color="#007F7F"/></linearGradient><linearGradient id="gold" x2="0" y2="1"><stop stop-color="#FFE6A0"/><stop offset=".5" stop-color="#F4C542"/><stop offset="1" stop-color="#B88220"/></linearGradient><radialGradient id="lamp"><stop stop-color="#F4C542" stop-opacity=".34"/><stop offset="1" stop-color="#F4C542" stop-opacity="0"/></radialGradient><radialGradient id="aura"><stop stop-color="#10B981" stop-opacity=".22"/><stop offset="1" stop-color="#10B981" stop-opacity="0"/></radialGradient></defs><g clip-path="url(#window)"><rect width="${width}" height="${height}" fill="#03131D"/><image href="${imageAsset('lounge.png')}" width="${width}" height="${height}" preserveAspectRatio="xMidYMid slice"/><rect width="${width}" height="${height}" fill="url(#shade)"/><ellipse cx="${width-18}" cy="90" rx="115" ry="145" fill="url(#lamp)" opacity="${.25+.05*Math.cos(phase*2*Math.PI)}"/><g font-family="Inter">${body}</g></g><rect x="1" y="1" width="${width-2}" height="${height-2}" rx="13" fill="none" stroke="#00D7CF" stroke-width="1.3"/><rect x="5" y="5" width="${width-10}" height="${height-10}" rx="10" fill="none" stroke="#BDE6DC" stroke-opacity=".1"/><path d="M12 34V12H34M${width-34} ${height-12}H${width-12}V${height-34}" fill="none" stroke="#F4C542" stroke-opacity=".7"/></svg>`;}
export function heading(kicker:string,title:string,subtitle:string){return `<circle cx="36" cy="35" r="15" fill="#012c32" stroke="#00C8C6"/><path d="M29 42V27H42L39 32 42 36H29" fill="none" stroke="#6AF2DC" stroke-width="1.5"/>`+text(61,39,kicker,11,'#69EADD','letter-spacing="1.4" font-family="Space Grotesk" font-weight="600"')+text(22,84,title,32,ink.white,'font-family="Space Grotesk" font-weight="700"')+text(22,111,subtitle,15,ink.white);}
export function footer(y:number,pool:string,status:string){return panel(18,y-20,404,65,ink.slate)+text(32,y,'TOTAL POOL',10,'#91CEC8','letter-spacing="1.2" font-family="Space Grotesk"')+text(32,y+29,pool+' Ottomans',21,ink.white,'font-weight="600"')+text(405,y+27,status,11,ink.warm,'text-anchor="end"');}
export interface EventMotion {phase?:number;}
