import type { JailRepository } from './repository.js';
import type { JailCaseRecord,JailHistoryEntry,JailSentenceRecord } from './types.js';

interface JailRow {id:string;guildId:string;userId:string;type:string;caseId:number|null;reason:string;startedAt:Date;endsAt:Date;endedAt:Date|null;active:boolean;indefinite:boolean;restoration:unknown;pausedAt:Date|null;pausedRemainingSeconds:number|null;releaseReason:string|null;releasedByUserId:string|null;}
interface CaseRow {id:number;guildId:string;subjectUserId:string|null;actionType:string;reason:string;actorUserId:string|null;actorType:string;durationSeconds:number|null;status:string;metadata:unknown;createdAt:Date;}
interface AppealRow {id:string;caseId:number;requesterUserId:string;}
interface TxLike {
  member:{upsert(args:unknown):Promise<unknown>};
  moderationCase:{create(args:unknown):Promise<CaseRow>;findMany(args:unknown):Promise<CaseRow[]>;updateMany(args:unknown):Promise<{count:number}>};
  jailSentence:{create(args:unknown):Promise<JailRow>;findUnique(args:unknown):Promise<JailRow|null>;findFirst(args:unknown):Promise<JailRow|null>;findMany(args:unknown):Promise<JailRow[]>;update(args:unknown):Promise<JailRow>};
  appeal:{create(args:unknown):Promise<AppealRow>};
  scheduledJob:{upsert(args:unknown):Promise<unknown>;updateMany(args:unknown):Promise<{count:number}>};
}
export interface JailPrismaLike extends TxLike {$transaction<T>(fn:(tx:TxLike)=>Promise<T>):Promise<T>;}

const restoration=(value:unknown):{suspendedRoleIds:string[]}=>{if(!value||typeof value!=='object')return{suspendedRoleIds:[]};const raw=value as Record<string,unknown>;return{suspendedRoleIds:Array.isArray(raw.suspendedRoleIds)?raw.suspendedRoleIds.filter((x):x is string=>typeof x==='string'):[]};};
const sentence=(r:JailRow):JailSentenceRecord=>({id:r.id,guildId:r.guildId,userId:r.userId,type:r.type as JailSentenceRecord['type'],...(r.caseId===null?{}:{caseId:r.caseId}),reason:r.reason,startedAt:r.startedAt,endsAt:r.endsAt,...(r.endedAt?{endedAt:r.endedAt}:{}),active:r.active,indefinite:r.indefinite,restoration:restoration(r.restoration),...(r.pausedAt?{pausedAt:r.pausedAt}:{}),...(r.pausedRemainingSeconds===null?{}:{pausedRemainingSeconds:r.pausedRemainingSeconds}),...(r.releaseReason?{releaseReason:r.releaseReason}:{}),...(r.releasedByUserId?{releasedByUserId:r.releasedByUserId}:{})});
const caseRecord=(r:CaseRow):JailCaseRecord=>({id:r.id,guildId:r.guildId,...(r.subjectUserId?{subjectUserId:r.subjectUserId}:{}),actionType:r.actionType,reason:r.reason,...(r.actorUserId?{actorUserId:r.actorUserId}:{}),actorType:r.actorType,...(r.durationSeconds===null?{}:{durationSeconds:r.durationSeconds}),status:r.status,...(r.metadata&&typeof r.metadata==='object'?{metadata:r.metadata as Record<string,unknown>}:{}) ,createdAt:r.createdAt});

export class PrismaJailRepository implements JailRepository {
  constructor(private readonly db:JailPrismaLike){}
  async ensureMember(guildId:string,userId:string){await this.db.member.upsert({where:{guildId_userId:{guildId,userId}},update:{},create:{guildId,userId}});}
  async createModerationSentence(input:{guildId:string;userId:string;actorUserId:string;reason:string;startedAt:Date;endsAt:Date;indefinite:boolean;restoration:{suspendedRoleIds:string[]}}){return this.db.$transaction(async tx=>{await tx.member.upsert({where:{guildId_userId:{guildId:input.guildId,userId:input.userId}},update:{},create:{guildId:input.guildId,userId:input.userId}});const provisional=await tx.jailSentence.create({data:{guildId:input.guildId,userId:input.userId,type:'MODERATION',reason:input.reason,startedAt:input.startedAt,endsAt:input.endsAt,indefinite:input.indefinite,restoration:input.restoration,active:true}});const c=await tx.moderationCase.create({data:{guildId:input.guildId,subjectUserId:input.userId,actionType:'JAIL',reason:input.reason,actorUserId:input.actorUserId,actorType:'STAFF',durationSeconds:input.indefinite?null:Math.max(0,Math.round((input.endsAt.getTime()-input.startedAt.getTime())/1000)),status:'ACTIVE',metadata:{sentenceId:provisional.id}}});const updated=await tx.jailSentence.update({where:{id:provisional.id},data:{caseId:c.id}});return{sentence:sentence(updated),caseRecord:caseRecord(c)};});}
  async getSentence(id:string){const r=await this.db.jailSentence.findUnique({where:{id}});return r?sentence(r):null;}
  async getActiveModerationSentence(guildId:string,userId:string){const r=await this.db.jailSentence.findFirst({where:{guildId,userId,type:'MODERATION',active:true},orderBy:{startedAt:'desc'}});return r?sentence(r):null;}
  async listActiveSentences(guildId:string,userId?:string){const rows=await this.db.jailSentence.findMany({where:{guildId,active:true,...(userId?{userId}:{})},orderBy:{startedAt:'asc'}});return rows.map(sentence);}
  async listActiveModerationSentences(guildId?:string){const rows=await this.db.jailSentence.findMany({where:{type:'MODERATION',active:true,...(guildId?{guildId}:{})},orderBy:{startedAt:'asc'}});return rows.map(sentence);}
  async changeSentence(input:{sentenceId:string;actorUserId:string;actionType:'JAIL_EXTEND'|'JAIL_REDUCE';reason:string;now:Date;endsAt:Date;durationSeconds:number}){return this.db.$transaction(async tx=>{const current=await tx.jailSentence.findUnique({where:{id:input.sentenceId}});if(!current)throw new Error('Jail sentence not found.');const updated=await tx.jailSentence.update({where:{id:input.sentenceId},data:{endsAt:input.endsAt,...(current.pausedAt?{pausedRemainingSeconds:Math.max(1,Math.ceil((input.endsAt.getTime()-input.now.getTime())/1000))}:{})}});const c=await tx.moderationCase.create({data:{guildId:current.guildId,subjectUserId:current.userId,actionType:input.actionType,reason:input.reason,actorUserId:input.actorUserId,actorType:'STAFF',durationSeconds:input.durationSeconds,status:'ACTIVE',metadata:{sentenceId:current.id,rootCaseId:current.caseId}}});return{sentence:sentence(updated),caseRecord:caseRecord(c)};});}
  async releaseSentence(input:{sentenceId:string;actorUserId:string;reason:string;now:Date;actionType?:'JAIL_RELEASE'|'JAIL_EXPIRE'}){return this.db.$transaction(async tx=>{const current=await tx.jailSentence.findUnique({where:{id:input.sentenceId}});if(!current)throw new Error('Jail sentence not found.');const action=input.actionType??'JAIL_RELEASE';const updated=await tx.jailSentence.update({where:{id:input.sentenceId},data:{active:false,endedAt:input.now,releaseReason:input.reason,releasedByUserId:input.actorUserId,pausedAt:null,pausedRemainingSeconds:null}});if(current.caseId!==null)await tx.moderationCase.updateMany({where:{id:current.caseId},data:{status:'EXPIRED'}});const c=await tx.moderationCase.create({data:{guildId:current.guildId,subjectUserId:current.userId,actionType:action,reason:input.reason,actorUserId:action==='JAIL_EXPIRE'?null:input.actorUserId,actorType:action==='JAIL_EXPIRE'?'SYSTEM':'STAFF',status:'EXPIRED',metadata:{sentenceId:current.id,rootCaseId:current.caseId}}});return{sentence:sentence(updated),caseRecord:caseRecord(c)};});}
  async listHistory(guildId:string,userId:string,limit=20):Promise<JailHistoryEntry[]>{const rows=await this.db.jailSentence.findMany({where:{guildId,userId,type:'MODERATION'},orderBy:{startedAt:'desc'},take:limit});const out:JailHistoryEntry[]=[];for(const row of rows){const cases=await this.db.moderationCase.findMany({where:{guildId,subjectUserId:userId,OR:[{id:row.caseId??-1},{metadata:{path:['sentenceId'],equals:row.id}}]},orderBy:{createdAt:'asc'}});out.push({sentence:sentence(row),cases:cases.map(caseRecord)});}return out;}
  async requestReview(input:{sentenceId:string;userId:string;text?:string;now:Date}){const row=await this.db.jailSentence.findUnique({where:{id:input.sentenceId}});if(!row?.caseId)throw new Error('Jail sentence does not have a case.');const appeal=await this.db.appeal.create({data:{caseId:row.caseId,requesterUserId:input.userId,status:'PENDING',text:input.text??null,createdAt:input.now}});return{appealId:appeal.id,caseId:appeal.caseId};}
  async upsertExpiryJob(s:JailSentenceRecord){if(s.indefinite||s.pausedAt||!s.active){await this.cancelExpiryJob(s.id);return;}await this.db.scheduledJob.upsert({where:{executionKey:`jail-expire:${s.id}`},create:{guildId:s.guildId,jobType:'jail.expire',executionKey:`jail-expire:${s.id}`,dueAt:s.endsAt,status:'PENDING',payload:{sentenceId:s.id,userId:s.userId}},update:{guildId:s.guildId,dueAt:s.endsAt,status:'PENDING',payload:{sentenceId:s.id,userId:s.userId},lastError:null,completedAt:null}});}
  async cancelExpiryJob(sentenceId:string){await this.db.scheduledJob.updateMany({where:{executionKey:`jail-expire:${sentenceId}`,status:{in:['PENDING','FAILED','RUNNING']}},data:{status:'CANCELLED'}});}
}
