import {randomUUID} from 'node:crypto';
import {Prisma,type PrismaClient} from '@prisma/client';
import {DomainError,SessionEngine,type LedgerEngine,type Session} from '../../core/src/index.js';
import {PrismaAtomicOperations,requestFingerprint} from '../../database/src/atomic-operations.js';
import {PrismaTransactionSessions} from '../../database/src/transaction-sessions.js';
import {PrismaWagerEscrow} from '../../database/src/wager-escrow.js';
import {addPokerSeat,cancelPokerTable,createPokerTable,type PokerTable,startPokerTable,validateBuyIn} from './poker.js';
export interface PokerContext {guildId:string;channelId:string;userId:string;requestKey:string;}
const json=(v:unknown)=>JSON.parse(JSON.stringify(v)) as Prisma.InputJsonObject;
export class PrismaPokerRepository {
 private readonly atomic:PrismaAtomicOperations;
 constructor(private readonly db:PrismaClient){this.atomic=new PrismaAtomicOperations(db);}
 async get(id:string){const s=await new PrismaTransactionSessions(this.db).get<PokerTable>(id);if(!s||s.type!=='poker')throw new DomainError('POKER_MISSING','Poker table unavailable.');return{...s,data:s.data as PokerTable};}
 async start(c:PokerContext,variant:'holdem'|'omaha',name:string,buyIn:bigint){validateBuyIn(buyIn);const id=randomUUID();return this.atomic.run(c.guildId,'poker:start:'+c.requestKey,requestFingerprint({userId:c.userId,variant,buyIn}),async(tx,ledger)=>{const escrow=new PrismaWagerEscrow(tx,ledger);await escrow.reserve({guildId:c.guildId,userId:c.userId,amount:buyIn,referenceType:'poker',referenceId:id,key:'poker:buyin:'+id+':'+c.userId});const table=createPokerTable({id,guildId:c.guildId,channelId:c.channelId,hostId:c.userId,variant,hostName:name,hostBuyIn:buyIn,now:new Date()});const expiresAt=new Date(Date.now()+300000);const session=await new PrismaTransactionSessions(tx).create<PokerTable>({id,guildId:c.guildId,channelId:c.channelId,ownerUserId:c.userId,type:'poker',state:'OPEN',data:table,expiresAt,extensionUsed:false,version:0,createdAt:new Date(),updatedAt:new Date()});await tx.scheduledJob.create({data:{guildId:c.guildId,jobType:'poker.timeout',executionKey:`poker:timeout:${id}`,dueAt:expiresAt,payload:{guildId:c.guildId,sessionId:id}}});await tx.auditEvent.create({data:{guildId:c.guildId,actorUserId:c.userId,source:'discord',action:'poker.created',targetType:'poker',targetId:id,after:json({variant,buyIn:buyIn.toString()}),requestId:c.requestKey,createdAt:new Date()}});return{sessionId:session.id};});}
 async join(c:PokerContext,id:string,name:string,buyIn:bigint,bot=false){return this.atomic.run(c.guildId,'poker:join:'+c.requestKey,requestFingerprint({id,userId:c.userId,buyIn,bot}),async(tx,ledger)=>{const sessions=new PrismaTransactionSessions(tx),s=await sessions.get<PokerTable>(id);if(!s||s.type!=='poker'||s.guildId!==c.guildId)throw new DomainError('POKER_MISSING','Poker table unavailable.');if(s.state!=='OPEN')throw new DomainError('POKER_CLOSED','This table is no longer accepting seats.');const table=s.data as unknown as PokerTable;if(bot&&table.hostId!==c.userId)throw new DomainError('POKER_OWNER','Only the host may add a bot seat.');if(table.seats.some(x=>x.userId===c.userId&&!bot))return{sessionId:id,alreadyJoined:true};const seatId=bot?`bot-${table.seats.filter(x=>x.bot).length+1}`:c.userId;if(!bot)await new PrismaWagerEscrow(tx,ledger).reserve({guildId:c.guildId,userId:c.userId,amount:buyIn,referenceType:'poker',referenceId:id,key:'poker:buyin:'+id+':'+seatId});const next=addPokerSeat(table,{userId:seatId,name,bot,buyIn,joined:true});await new SessionEngine(sessions).transition<PokerTable>(id,['OPEN'],'OPEN',current=>({...current,data:next}));return{sessionId:id,alreadyJoined:false};});}
 async cancel(c:PokerContext,id:string){return this.atomic.run(c.guildId,'poker:cancel:'+c.requestKey,requestFingerprint({id,userId:c.userId}),async(tx,ledger)=>{const sessions=new PrismaTransactionSessions(tx),s=await sessions.get<PokerTable>(id);if(!s||s.type!=='poker'||s.ownerUserId!==c.userId)throw new DomainError('POKER_OWNER','Only the host may cancel this table.');if(s.state!=='OPEN')throw new DomainError('POKER_STARTED','Started tables cannot be cancelled.');const closed=cancelPokerTable(s.data as unknown as PokerTable);await new PrismaWagerEscrow(tx,ledger).refund(c.guildId,'poker',id,'poker:refund:'+id);await tx.auditEvent.create({data:{guildId:c.guildId,actorUserId:c.userId,source:'discord',action:'poker.cancel_refund',targetType:'poker',targetId:id,after:json({refunded:true}),requestId:c.requestKey,createdAt:new Date()}});await tx.scheduledJob.updateMany({where:{executionKey:`poker:timeout:${id}`,status:{in:['PENDING','FAILED','RUNNING']}},data:{status:'CANCELLED'}});await new SessionEngine(sessions).transition<PokerTable>(id,['OPEN'],'CLOSED',current=>({...current,data:closed}));return{sessionId:id,refunded:true};});}
 async timeout(guildId:string,id:string){return this.atomic.run(guildId,'poker:timeout:'+id,id,async(tx,ledger)=>{const sessions=new PrismaTransactionSessions(tx),s=await sessions.get<PokerTable>(id);if(!s||s.type!=='poker')throw new DomainError('POKER_MISSING','Poker table unavailable.');if(s.state!=='OPEN')return{sessionId:id,refunded:false};if(!s.expiresAt||s.expiresAt>new Date())throw new DomainError('NOT_DUE','Poker entry remains open.');await new PrismaWagerEscrow(tx,ledger).settle(guildId,'poker',id,new Map(),'poker:timeout-refund:'+id);await tx.auditEvent.create({data:{guildId,actorUserId:null,source:'scheduler',action:'poker.timeout_refund',targetType:'poker',targetId:id,after:json({refunded:true}),requestId:'poker:timeout:'+id,createdAt:new Date()}});await new SessionEngine(sessions).transition<PokerTable>(id,['OPEN'],'CLOSED',current=>({...current,data:cancelPokerTable(current.data as unknown as PokerTable)}));return{sessionId:id,refunded:true};});}
 async startPlaying(c:PokerContext,id:string){return this.atomic.run(c.guildId,'poker:start:'+c.requestKey,requestFingerprint({id,userId:c.userId}),async tx=>{const sessions=new PrismaTransactionSessions(tx),s=await sessions.get<PokerTable>(id);if(!s||s.type!=='poker'||s.ownerUserId!==c.userId)throw new DomainError('POKER_OWNER','Only the host may start this table.');const started=startPokerTable(s.data as unknown as PokerTable);await new SessionEngine(sessions).transition<PokerTable>(id,['OPEN'],'OPEN',current=>({...current,data:started}));return{sessionId:id};});}
}
