import {randomUUID} from 'node:crypto';
import {Prisma,type PrismaClient} from '@prisma/client';
import {DomainError,SessionEngine,type LedgerEngine} from '../../core/src/index.js';
import {PrismaAtomicOperations,requestFingerprint} from '../../database/src/atomic-operations.js';
import {PrismaTransactionSessions} from '../../database/src/transaction-sessions.js';
import {PrismaWagerEscrow} from '../../database/src/wager-escrow.js';
import {addPokerSeat,carryTournamentStacks,cancelPokerTable,createPokerTable,pokerAction,privatePokerView,publicPokerView,startPokerHand,startPokerTable,timeoutPokerAction,type PokerAction,type PokerHand,type PokerTable,validateBuyIn} from './poker.js';
export interface PokerContext {guildId:string;channelId:string;userId:string;requestKey:string;}
const json=(v:unknown)=>JSON.parse(JSON.stringify(v)) as Prisma.InputJsonObject;
const ACTION_TIMEOUT_MS=90_000;
const actionDue=()=>new Date(Date.now()+ACTION_TIMEOUT_MS);
export class PrismaPokerRepository {
 private readonly atomic:PrismaAtomicOperations;
 constructor(private readonly db:PrismaClient){this.atomic=new PrismaAtomicOperations(db);}
 async get(id:string){const s=await new PrismaTransactionSessions(this.db).get<PokerTable>(id);if(!s||s.type!=='poker')throw new DomainError('POKER_MISSING','Poker table unavailable.');return{...s,data:s.data as PokerTable};}
 async publicView(id:string){const table=(await this.get(id)).data;if(!table.activeHand)throw new DomainError('POKER_NOT_STARTED','This table has not started.');return publicPokerView(table.activeHand);}
 async privateView(id:string,userId:string){const table=(await this.get(id)).data;if(!table.activeHand)throw new DomainError('POKER_NOT_STARTED','This table has not started.');return privatePokerView(table.activeHand,userId);}
 async start(c:PokerContext,variant:'holdem'|'omaha',name:string,buyIn:bigint){validateBuyIn(buyIn);const id=randomUUID();return this.atomic.run(c.guildId,'poker:start:'+c.requestKey,requestFingerprint({userId:c.userId,variant,buyIn}),async(tx,ledger)=>{const escrow=new PrismaWagerEscrow(tx,ledger);await escrow.reserve({guildId:c.guildId,userId:c.userId,amount:buyIn,referenceType:'poker',referenceId:id,key:'poker:buyin:'+id+':'+c.userId});const table=createPokerTable({id,guildId:c.guildId,channelId:c.channelId,hostId:c.userId,variant,hostName:name,hostBuyIn:buyIn,now:new Date()});const expiresAt=new Date(Date.now()+300000);const session=await new PrismaTransactionSessions(tx).create<PokerTable>({id,guildId:c.guildId,channelId:c.channelId,ownerUserId:c.userId,type:'poker',state:'OPEN',data:table,expiresAt,extensionUsed:false,version:0,createdAt:new Date(),updatedAt:new Date()});await tx.scheduledJob.create({data:{guildId:c.guildId,jobType:'poker.timeout',executionKey:`poker:timeout:${id}`,dueAt:expiresAt,payload:{guildId:c.guildId,sessionId:id}}});await tx.auditEvent.create({data:{guildId:c.guildId,actorUserId:c.userId,source:'discord',action:'poker.created',targetType:'poker',targetId:id,after:json({variant,buyIn:buyIn.toString()}),requestId:c.requestKey,createdAt:new Date()}});return{sessionId:session.id};});}
 async join(c:PokerContext,id:string,name:string,buyIn:bigint,bot=false){return this.atomic.run(c.guildId,'poker:join:'+c.requestKey,requestFingerprint({id,userId:c.userId,buyIn,bot}),async(tx,ledger)=>{const sessions=new PrismaTransactionSessions(tx),s=await sessions.get<PokerTable>(id);if(!s||s.type!=='poker'||s.guildId!==c.guildId)throw new DomainError('POKER_MISSING','Poker table unavailable.');if(s.state!=='OPEN')throw new DomainError('POKER_CLOSED','This table is no longer accepting seats.');const table=s.data as unknown as PokerTable;if(bot&&table.hostId!==c.userId)throw new DomainError('POKER_OWNER','Only the host may add a bot seat.');if(table.seats.some(x=>x.userId===c.userId&&!bot))return{sessionId:id,alreadyJoined:true};const seatId=bot?`bot-${table.seats.filter(x=>x.bot).length+1}`:c.userId;if(!bot)await new PrismaWagerEscrow(tx,ledger).reserve({guildId:c.guildId,userId:c.userId,amount:buyIn,referenceType:'poker',referenceId:id,key:'poker:buyin:'+id+':'+seatId});const next=addPokerSeat(table,{userId:seatId,name,bot,buyIn,joined:true});await new SessionEngine(sessions).transition<PokerTable>(id,['OPEN'],'OPEN',current=>({...current,data:next}));return{sessionId:id,alreadyJoined:false};});}
 async cancel(c:PokerContext,id:string){return this.atomic.run(c.guildId,'poker:cancel:'+c.requestKey,requestFingerprint({id,userId:c.userId}),async(tx,ledger)=>{const sessions=new PrismaTransactionSessions(tx),s=await sessions.get<PokerTable>(id);if(!s||s.type!=='poker'||s.ownerUserId!==c.userId)throw new DomainError('POKER_OWNER','Only the host may cancel this table.');if(s.state!=='OPEN')throw new DomainError('POKER_STARTED','Started tables cannot be cancelled.');const closed=cancelPokerTable(s.data as unknown as PokerTable);await new PrismaWagerEscrow(tx,ledger).refund(c.guildId,'poker',id,'poker:refund:'+id);await tx.auditEvent.create({data:{guildId:c.guildId,actorUserId:c.userId,source:'discord',action:'poker.cancel_refund',targetType:'poker',targetId:id,after:json({refunded:true}),requestId:c.requestKey,createdAt:new Date()}});await tx.scheduledJob.updateMany({where:{executionKey:`poker:timeout:${id}`,status:{in:['PENDING','FAILED','RUNNING']}},data:{status:'CANCELLED'}});await new SessionEngine(sessions).transition<PokerTable>(id,['OPEN'],'CLOSED',current=>({...current,data:closed}));return{sessionId:id,refunded:true};});}
 async timeout(guildId:string,id:string){return this.atomic.run(guildId,'poker:timeout:'+id,id,async(tx,ledger)=>{const sessions=new PrismaTransactionSessions(tx),s=await sessions.get<PokerTable>(id);if(!s||s.type!=='poker')throw new DomainError('POKER_MISSING','Poker table unavailable.');if(s.state!=='OPEN')return{sessionId:id,refunded:false};if(!s.expiresAt||s.expiresAt>new Date())throw new DomainError('NOT_DUE','Poker entry remains open.');await new PrismaWagerEscrow(tx,ledger).refund(guildId,'poker',id,'poker:timeout-refund:'+id);await new SessionEngine(sessions).transition<PokerTable>(id,['OPEN'],'CLOSED',current=>({...current,data:cancelPokerTable(current.data as PokerTable)}));return{sessionId:id,refunded:true};});}
 async startPlaying(c:PokerContext,id:string){return this.atomic.run(c.guildId,'poker:start-playing:'+c.requestKey,requestFingerprint({id,userId:c.userId}),async(tx,_ledger)=>{const sessions=new PrismaTransactionSessions(tx),s=await sessions.get<PokerTable>(id);if(!s||s.type!=='poker'||s.ownerUserId!==c.userId)throw new DomainError('POKER_OWNER','Only the host may start this table.');const table=s.data as PokerTable;if(s.state==='LOCKED'&&table.activeHand)return{sessionId:id,handId:table.activeHand.handId,alreadyStarted:true};if(s.state!=='OPEN')throw new DomainError('POKER_START','This table cannot start again.');const started=startPokerTable(table),dueAt=actionDue(),hand=startPokerHand(started,randomUUID(),undefined,dueAt),next={...started,activeHand:hand,pot:hand.pot};await new SessionEngine(sessions).transition<PokerTable>(id,['OPEN'],'LOCKED',current=>({...current,data:next,expiresAt:dueAt}));await tx.scheduledJob.updateMany({where:{executionKey:`poker:timeout:${id}`,status:{in:['PENDING','FAILED','RUNNING']}},data:{status:'CANCELLED'}});await this.scheduleAction(tx,c.guildId,id,hand,dueAt);return{sessionId:id,handId:hand.handId,alreadyStarted:false};});}
 async act(c:PokerContext,id:string,action:PokerAction,amount?:bigint){return this.atomic.run(c.guildId,'poker:action:'+c.requestKey,requestFingerprint({id,userId:c.userId,action,amount}),async(tx,ledger)=>{const sessions=new PrismaTransactionSessions(tx),s=await sessions.get<PokerTable>(id);if(!s||s.type!=='poker'||s.guildId!==c.guildId||s.state!=='LOCKED')throw new DomainError('POKER_NOT_STARTED','This table is not playing.');const table=s.data as PokerTable,hand=table.activeHand;if(!hand)throw new DomainError('POKER_NOT_STARTED','This table has no active hand.');const dueAt=actionDue(),nextHand=pokerAction(hand,c.userId,action,amount,dueAt);if(!nextHand.settled){const next={...table,activeHand:nextHand,pot:nextHand.pot};await new SessionEngine(sessions).transition<PokerTable>(id,['LOCKED'],'LOCKED',current=>({...current,data:next,expiresAt:dueAt}));await this.scheduleAction(tx,c.guildId,id,nextHand,dueAt);return{sessionId:id,handId:nextHand.handId,settled:false};}const advanced=carryTournamentStacks({...table,activeHand:hand},nextHand);await new SessionEngine(sessions).transition<PokerTable>(id,['LOCKED'],advanced.state==='CLOSED'?'CLOSED':'LOCKED',current=>({...current,data:advanced,...(advanced.state==='CLOSED'?{}:{expiresAt:dueAt})}));if(advanced.state==='CLOSED')await this.settleHumanBuyIns(tx,ledger,c.guildId,id,advanced,nextHand);return{sessionId:id,handId:nextHand.handId,settled:true,sessionClosed:advanced.state==='CLOSED'};});}
 async recover(guildId:string){const rows=await this.db.gameSession.findMany({where:{guildId,type:'poker',state:'LOCKED'}});let recovered=0;for(const row of rows){const table=row.data as unknown as PokerTable,hand=table.activeHand;if(!hand||hand.settled)continue;const dueAt=hand.actionDeadline?new Date(hand.actionDeadline):new Date();await this.db.scheduledJob.upsert({where:{executionKey:`poker:action:${row.id}:${hand.handId}:${dueAt.getTime()}`},create:{guildId,jobType:'poker.action_timeout',executionKey:`poker:action:${row.id}:${hand.handId}:${dueAt.getTime()}`,dueAt,payload:{guildId,sessionId:row.id,handId:hand.handId}},update:{dueAt,status:'PENDING',payload:{guildId,sessionId:row.id,handId:hand.handId},lastError:null,completedAt:null}});recovered++;}return recovered;}
 async actionTimeout(guildId:string,id:string,handId:string){return this.atomic.run(guildId,`poker:action-timeout:${id}:${handId}`,handId,async(tx,ledger)=>{const sessions=new PrismaTransactionSessions(tx),s=await sessions.get<PokerTable>(id);if(!s||s.type!=='poker'||s.state!=='LOCKED')return{sessionId:id,changed:false};const table=s.data as PokerTable,hand=table.activeHand;if(!hand||hand.handId!==handId||hand.settled||!hand.actionDeadline||new Date(hand.actionDeadline)>new Date())return{sessionId:id,changed:false};const dueAt=actionDue(),nextHand=timeoutPokerAction(hand,dueAt);if(!nextHand.settled){const next={...table,activeHand:nextHand,pot:nextHand.pot};await new SessionEngine(sessions).transition<PokerTable>(id,['LOCKED'],'LOCKED',current=>({...current,data:next,expiresAt:dueAt}));await this.scheduleAction(tx,guildId,id,nextHand,dueAt);return{sessionId:id,changed:true,settled:false};}const advanced=carryTournamentStacks({...table,activeHand:hand},nextHand);await new SessionEngine(sessions).transition<PokerTable>(id,['LOCKED'],advanced.state==='CLOSED'?'CLOSED':'LOCKED',current=>({...current,data:advanced,...(advanced.state==='CLOSED'?{}:{expiresAt:dueAt})}));if(advanced.state==='CLOSED')await this.settleHumanBuyIns(tx,ledger,guildId,id,advanced,nextHand);return{sessionId:id,changed:true,settled:true,sessionClosed:advanced.state==='CLOSED'};});}
 private async scheduleAction(tx:Prisma.TransactionClient,guildId:string,id:string,hand:PokerHand,dueAt:Date){await tx.scheduledJob.upsert({where:{executionKey:`poker:action:${id}:${hand.handId}:${dueAt.getTime()}`},create:{guildId,jobType:'poker.action_timeout',executionKey:`poker:action:${id}:${hand.handId}:${dueAt.getTime()}`,dueAt,payload:{guildId,sessionId:id,handId:hand.handId}},update:{dueAt,payload:{guildId,sessionId:id,handId:hand.handId},status:'PENDING',lastError:null,completedAt:null}});}
 private async settleHumanBuyIns(tx:Prisma.TransactionClient,ledger:LedgerEngine,guildId:string,id:string,table:PokerTable,hand:PokerHand){const winners=table.seats.filter(seat=>!seat.bot&&BigInt(seat.chips)>0n).map(seat=>seat.userId);if(winners.length!==1)return;const rows=await tx.escrow.findMany({where:{guildId,referenceType:'poker',referenceId:id,state:'RESERVED'}});const total=rows.reduce((sum,row)=>sum+(row.amount??0n),0n);await new PrismaWagerEscrow(tx,ledger).settle(guildId,'poker',id,new Map([[winners[0]!,total]]),`poker:session-settlement:${id}`);}
}
