import {strict as assert} from 'node:assert';
import {test} from 'node:test';
import {addPokerSeat,advanceBlinds,advancePokerStreet,carryTournamentStacks,cancelPokerTable,createPokerTable,evaluatePokerHand,startPokerHand,startPokerTable,pokerAction,privatePokerView,publicPokerView,settlePokerHand,timeoutPokerAction,validateBuyIn,POKER_MAX_PLAYERS,pokerCardLabel} from './poker.js';
const base=()=>createPokerTable({id:'t',guildId:'g',channelId:'p',hostId:'h',variant:'holdem',hostName:'Host',hostBuyIn:500n,now:new Date('2026-01-01T00:00:00Z')});
test('poker buy-ins map only to approved chip stacks',()=>{assert.equal(validateBuyIn(500n),'5000');assert.equal(validateBuyIn(5000n),'50000');assert.throws(()=>validateBuyIn(600n),/buy-in/i);});
test('human invitees must explicitly join while bots may fill selected seats',()=>{const t=base();assert.throws(()=>addPokerSeat(t,{userId:'u',name:'Invitee',bot:false,buyIn:1000n}),/explicitly join/i);const joined=addPokerSeat(t,{userId:'u',name:'Invitee',bot:false,buyIn:1000n,joined:true});const withBot=addPokerSeat(joined,{userId:'b',name:'Dealer Bot',bot:true,buyIn:500n});assert.equal(withBot.seats.length,3);});
test('tournament table caps playing seats at four plus a non-playing dealer',()=>{let t=base();for(let n=1;n<POKER_MAX_PLAYERS;n++)t=addPokerSeat(t,{userId:'p'+n,name:'Player '+n,bot:n>1,buyIn:500n,joined:true});assert.equal(t.seats.length,POKER_MAX_PLAYERS);assert.throws(()=>addPokerSeat(t,{userId:'overflow',name:'Overflow',bot:true,buyIn:500n}),/four playing seats/i);});
test('private cards have readable rank and suit labels while public views contain no hole cards',()=>{assert.equal(pokerCardLabel(0),'A♣');assert.equal(pokerCardLabel(51),'K♠');let t=addPokerSeat(base(),{userId:'u',name:'User',bot:false,buyIn:500n,joined:true});t=startPokerTable(t);const hand=startPokerHand(t,'labels',()=>0),pub=publicPokerView(hand),priv=privatePokerView(hand,'h');assert.equal('holeCards' in pub,false);assert.equal(priv.holeCardLabels.length,2);});
test('settled hands carry stacks across tournament hands and close after the last elimination',()=>{let t=base();t=addPokerSeat(t,{userId:'u',name:'User',bot:false,buyIn:500n,joined:true});t=startPokerTable(t);const h=startPokerHand(t,'tournament',()=>0);const settled=settlePokerHand({...h,folded:['u'],pot:'100',committed:{h:'0',u:'100'}});const next=carryTournamentStacks({...t,activeHand:h},settled);assert.equal(next.state,'CLOSED');assert.equal(next.seats.find(s=>s.userId==='h')?.chips,'5100');assert.deepEqual(next.settledHandIds,['tournament']);assert.deepEqual(carryTournamentStacks(next,settled),next);});
test('table starts once with two to five seats and blind levels rise',()=>{let t=addPokerSeat(base(),{userId:'u',name:'Player',bot:false,buyIn:500n,joined:true});t=startPokerTable(t);assert.equal(t.state,'PLAYING');assert.equal(t.hand,1);t=advanceBlinds(t);assert.equal(t.bigBlind,'100');assert.throws(()=>startPokerTable(t),/again|start/i);});
test('pre-play cancellation is refundable and post-start cancellation is rejected',()=>{assert.equal(cancelPokerTable(base()).state,'CLOSED');let t=addPokerSeat(base(),{userId:'u',name:'Player',bot:false,buyIn:500n,joined:true});t=startPokerTable(t);assert.throws(()=>cancelPokerTable(t),/started/i);});
test('hand engine deals two cards, enforces turn/buttons, and settles a fold once',()=>{let t=addPokerSeat(base(),{userId:'u',name:'Player',bot:false,buyIn:500n,joined:true});t=startPokerTable(t);let h=startPokerHand(t,'h1',()=>0);assert.equal(h.hole.h!.length,2);assert.equal(h.hole.u!.length,2);assert.throws(()=>pokerAction(h,'h','check'),/turn/i);h=pokerAction(h,'u','fold');const settled=settlePokerHand(h);assert.deepEqual(settled.winnerIds,['h']);assert.equal(settlePokerHand(settled).handId,'h1');});
test('raise must meet minimum and call advances the action state',()=>{let t=addPokerSeat(base(),{userId:'u',name:'Player',bot:false,buyIn:500n,joined:true});t=startPokerTable(t);let h=startPokerHand(t,'h2',()=>0);assert.throws(()=>pokerAction(h,h.toAct,'raise',1n),/minimum/i);h=pokerAction(h,h.toAct,'call');assert.equal(h.pot,'0');});
test('public projection never exposes deck or hole cards; private projection is viewer-scoped',()=>{let t=addPokerSeat(base(),{userId:'u',name:'Player',bot:false,buyIn:500n,joined:true});t=startPokerTable(t);const h=startPokerHand(t,'private',()=>0),pub=publicPokerView(h),priv=privatePokerView(h,'h');assert.equal('holeCards' in pub,false);assert.equal('deck' in pub,false);assert.deepEqual(priv.holeCards,h.hole.h);assert.throws(()=>privatePokerView(h,'spectator'),/not seated/i);});
test('street progression reveals flop, turn and river without leaking cards',()=>{let t=addPokerSeat(base(),{userId:'u',name:'Player',bot:false,buyIn:500n,joined:true});t=startPokerTable(t);let h=startPokerHand(t,'streets',()=>0);h=advancePokerStreet(h);assert.equal(h.street,'flop');assert.equal(h.board.length,3);h=advancePokerStreet(h);assert.equal(h.street,'turn');assert.equal(h.board.length,4);h=advancePokerStreet(h);assert.equal(h.street,'river');assert.equal(h.board.length,5);assert.ok(evaluatePokerHand(h,'h').length>=2);});
test('timeout applies a safe check and replay of settled hand is idempotent',()=>{let t=addPokerSeat(base(),{userId:'u',name:'Player',bot:false,buyIn:500n,joined:true});t=startPokerTable(t);let h=startPokerHand(t,'timeout',()=>0);h=timeoutPokerAction(h);assert.equal(h.toAct,'h');const folded=pokerAction(h,'h','fold'),settled=settlePokerHand(folded);assert.deepEqual(settlePokerHand(settled),settled);});

test('start table is replay-safe once its durable active hand is attached',()=>{
 let t=addPokerSeat(base(),{userId:'u',name:'Player',bot:false,buyIn:500n,joined:true});t=startPokerTable(t);const hand=startPokerHand(t,'only-hand',()=>0);const replay=startPokerTable({...t,activeHand:hand});assert.equal(replay.activeHand?.handId,'only-hand');assert.equal(replay.hand,1);
});
test('Omaha deals four private cards and a timed call folds when checking is illegal',()=>{
 let t=createPokerTable({id:'o',guildId:'g',channelId:'p',hostId:'h',variant:'omaha',hostName:'Host',hostBuyIn:500n,now:new Date()});t=addPokerSeat(t,{userId:'u',name:'Player',bot:false,buyIn:500n,joined:true});t=startPokerTable(t);let hand=startPokerHand(t,'omaha',()=>0,new Date('2026-01-01T00:01:30Z'));assert.equal(hand.hole.h?.length,4);hand={...hand,currentBet:'50',committed:{...hand.committed,[hand.toAct]:'0'}};const next=timeoutPokerAction(hand);assert.ok(next.folded.includes(hand.toAct));
});
test('public state remains independent of bot seats and never projects private cards',()=>{
 let t=addPokerSeat(base(),{userId:'bot-1',name:'Dealer Bot',bot:true,buyIn:500n,joined:true});t=startPokerTable(t);const hand=startPokerHand(t,'bot-private',()=>0);const serialized=JSON.stringify(publicPokerView(hand));assert.equal(serialized.includes('deck'),false);assert.equal(serialized.includes('hole'),false);assert.equal(publicPokerView(hand).players.length,2);
});
