import type {LedgerAccount,LedgerLine,LedgerTransaction} from '../../core/src/index.js';
import {DomainError,spendableWallet} from '../../core/src/index.js';
import type {ActivityCommitInput,ActivityCommitResult,ActivityPayoutCommitInput,ActivityPayoutCommitResult,BankUpgradeCommitInput,ClaimCommitInput,ClaimCommitResult,EconomyRepository,StarterCommitResult} from './repository.js';
import type {CatalogItemRecord,EconomyAccountRecord,EconomyActivityEventRecord,EconomyActivityStatRecord,EconomyLedgerEntryRecord,EconomyTransactionRecord,InventoryEntryRecord,MemberClaimStateRecord,ToolRecord} from './types.js';
import {reconcileEconomy} from './economy-reconciliation.js';

const key=(g:string,u:string)=>`${g}:${u}`;
const invKey=(g:string,u:string,i:string)=>`${g}:${u}:${i}`;
const cloneAccount=(a:EconomyAccountRecord):EconomyAccountRecord=>({...a,...(a.starterGrantedAt?{starterGrantedAt:new Date(a.starterGrantedAt)}:{})});
const cloneState=(s:MemberClaimStateRecord):MemberClaimStateRecord=>({...s,...(s.dailyLastClaimAt?{dailyLastClaimAt:new Date(s.dailyLastClaimAt)}:{}),...(s.weeklyLastClaimAt?{weeklyLastClaimAt:new Date(s.weeklyLastClaimAt)}:{}),...(s.dailySpinLastAt?{dailySpinLastAt:new Date(s.dailySpinLastAt)}:{}),...(s.fortuneLastAt?{fortuneLastAt:new Date(s.fortuneLastAt)}:{}),updatedAt:new Date(s.updatedAt)});

export class InMemoryEconomyRepository implements EconomyRepository {
  readonly accounts=new Map<string,EconomyAccountRecord>();
  readonly transactions=new Map<string,EconomyTransactionRecord>();
  readonly entries:EconomyLedgerEntryRecord[]=[];
  readonly claimStates=new Map<string,MemberClaimStateRecord>();
  readonly catalog=new Map<string,CatalogItemRecord>();
  readonly inventoryEntries=new Map<string,InventoryEntryRecord>();
  readonly tools=new Map<string,ToolRecord>();
  readonly stats=new Map<string,EconomyActivityStatRecord>();
  readonly activityEvents=new Map<string,EconomyActivityEventRecord>();
  readonly throttles=new Map<string,Date>();
  readonly scheduledJobs=new Map<string,{guildId:string;dueAt:Date;cycleKey:string}>();
  readonly snapshots=new Map<string,import('./repository.js').EconomySnapshotRecord>();
  readonly policyProposals:import('./repository.js').EconomyPolicyProposal[]=[];
  readonly bankInterestTerms=new Map<string,import('./repository.js').BankInterestTermRecord>();
  readonly activityPayoutCounters=new Map<string,import('./repository.js').ActivityPayoutCounter>();
  private seq=0;

  constructor(items:readonly CatalogItemRecord[]=[]){for(const i of items)this.catalog.set(i.id,{...i,...(i.metadata?{metadata:structuredClone(i.metadata)}:{})});}
  async ensureMember(_g:string,_u:string){return;}
  private ensureAccount(guildId:string,userId:string){const k=key(guildId,userId);let a=this.accounts.get(k);if(!a){a={guildId,userId,wallet:0n,bank:0n,bankTier:1,version:0};this.accounts.set(k,a);}return a;}
  async getAccount(guildId:string,userId:string):Promise<LedgerAccount>{return cloneAccount(this.ensureAccount(guildId,userId));}
  async getEconomyAccount(guildId:string,userId:string){return cloneAccount(this.ensureAccount(guildId,userId));}
  async hasIdempotencyKey(k:string){return this.transactions.has(k);}
  async getTransactionByIdempotencyKey(k:string){const r=this.transactions.get(k);return r?{...r,...(r.metadata?{metadata:structuredClone(r.metadata)}:{}),createdAt:new Date(r.createdAt)}:null;}
  private transaction(guildId:string,idempotencyKey:string,kind:string,reason:string,metadata:Record<string,unknown>|undefined,now:Date){const r:EconomyTransactionRecord={id:`econ-tx-${++this.seq}`,guildId,idempotencyKey,kind,reason,...(metadata?{metadata:structuredClone(metadata)}:{}),createdAt:new Date(now)};this.transactions.set(idempotencyKey,r);return r;}
  private ledgerEntries(tx:EconomyTransactionRecord,lines:LedgerTransaction['lines'],now:Date){for(const l of lines)this.entries.push({id:`ledger-${++this.seq}`,guildId:tx.guildId,transactionId:tx.id,...(l.userId?{userId:l.userId}:{}),bucket:l.bucket,amount:l.amount,reason:l.reason,...(l.metadata?{metadata:structuredClone(l.metadata)}:{}),createdAt:new Date(now)});}
  async commit(tx:LedgerTransaction,expectedVersions:ReadonlyMap<string,number>){if(this.transactions.has(tx.idempotencyKey))return true;const now=new Date();const next=new Map<string,{wallet:bigint;bank:bigint;version:number}>();for(const [userId,version] of expectedVersions){const a=this.ensureAccount(tx.guildId,userId);if(a.version!==version)return false;const wd=tx.lines.filter(x=>x.userId===userId&&x.bucket==='wallet').reduce((n,x)=>n+x.amount,0n);const bd=tx.lines.filter(x=>x.userId===userId&&x.bucket==='bank').reduce((n,x)=>n+x.amount,0n);if(a.wallet+wd<0n||a.bank+bd<0n)throw new DomainError('NEGATIVE_BALANCE','Economy balance cannot go negative.');if(spendableWallet(a)+wd<0n)throw new DomainError('WALLET_FUNDS_HELD','These wallet funds are reserved until the active transaction resolves.');next.set(userId,{wallet:a.wallet+wd,bank:a.bank+bd,version:a.version+1});}const header=this.transaction(tx.guildId,tx.idempotencyKey,'LEDGER',tx.lines[0]?.reason??'Ledger transaction',undefined,now);for(const [userId,n] of next){const a=this.ensureAccount(tx.guildId,userId);a.wallet=n.wallet;a.bank=n.bank;a.version=n.version;}this.ledgerEntries(header,tx.lines,now);return true;}

  async grantStarter(input:{guildId:string;userId:string;amount:bigint;idempotencyKey:string;now:Date}):Promise<StarterCommitResult>{if(input.amount<0n)throw new DomainError('INVALID_REWARD','Starter grants cannot debit money.');const a=this.ensureAccount(input.guildId,input.userId);if(this.transactions.has(input.idempotencyKey))return{status:'duplicate',account:cloneAccount(a)};if(a.starterGrantedAt)return{status:'existing',account:cloneAccount(a)};const header=this.transaction(input.guildId,input.idempotencyKey,'STARTER','One-time starter balance',{amount:input.amount.toString()},input.now);a.wallet+=input.amount;a.version++;a.starterGrantedAt=new Date(input.now);if(input.amount)this.ledgerEntries(header,[{userId:input.userId,bucket:'wallet',amount:input.amount,reason:'One-time starter balance'},{bucket:'system',amount:-input.amount,reason:'One-time starter balance'}],input.now);return{status:'applied',account:cloneAccount(a)};}
  async listLedgerEntries(g:string,u:string,l:number){return this.entries.filter(x=>x.guildId===g&&x.userId===u).sort((a,b)=>b.createdAt.getTime()-a.createdAt.getTime()).slice(0,l).map(x=>({...x,...(x.metadata?{metadata:structuredClone(x.metadata)}:{}),createdAt:new Date(x.createdAt)}));}
  private state(g:string,u:string){const k=key(g,u);let s=this.claimStates.get(k);if(!s){s={guildId:g,userId:u,dailyStreak:0,updatedAt:new Date(0)};this.claimStates.set(k,s);}return s;}
  async getClaimState(g:string,u:string){return cloneState(this.state(g,u));}
  private grantInventory(g:string,u:string,itemId:string,quantity:number){const k=invKey(g,u,itemId);let r=this.inventoryEntries.get(k);if(!r){r={id:`inv-${++this.seq}`,guildId:g,userId:u,itemId,quantity:0,locked:false};this.inventoryEntries.set(k,r);}r.quantity+=quantity;return r;}
  async commitClaim(input:ClaimCommitInput):Promise<ClaimCommitResult>{if(input.walletReward<0n)throw new DomainError('INVALID_REWARD','Claim rewards cannot debit money.');const a=this.ensureAccount(input.guildId,input.userId),s=this.state(input.guildId,input.userId);if(this.transactions.has(input.idempotencyKey))return{status:'duplicate',account:cloneAccount(a),state:cloneState(s),inventory:[]};const used=s[input.claimField];if(used&&used>=input.cycleStart)return{status:'already_used',account:cloneAccount(a),state:cloneState(s),inventory:[]};const header=this.transaction(input.guildId,input.idempotencyKey,input.kind,input.reason,input.metadata,input.now);if(input.walletReward){a.wallet+=input.walletReward;a.version++;this.ledgerEntries(header,[{userId:input.userId,bucket:'wallet',amount:input.walletReward,reason:input.reason,...(input.metadata?{metadata:input.metadata}:{})},{bucket:'system',amount:-input.walletReward,reason:input.reason,...(input.metadata?{metadata:input.metadata}:{})}],input.now);}const inv:InventoryEntryRecord[]=[];for(const grant of input.items??[]){if(!this.catalog.get(grant.itemId)?.enabled)throw new DomainError('CATALOG_ITEM_UNAVAILABLE',`Catalog item ${grant.itemId} is unavailable.`);inv.push({...this.grantInventory(input.guildId,input.userId,grant.itemId,grant.quantity)});}s[input.claimField]=new Date(input.now) as any;if(input.dailyStreak!==undefined)s.dailyStreak=input.dailyStreak;s.updatedAt=new Date(input.now);return{status:'applied',account:cloneAccount(a),state:cloneState(s),inventory:inv.map(x=>({...x})),transaction:{...header}};}
  async listInventory(g:string,u:string){return [...this.inventoryEntries.values()].filter(x=>x.guildId===g&&x.userId===u&&x.quantity>0).map(x=>{const item=this.catalog.get(x.itemId);return {...x,...(item?{item:{...item}}:{})};}).sort((a,b)=>(a.item?.name??a.itemId).localeCompare(b.item?.name??b.itemId));}
  async getCatalogItem(id:string){const r=this.catalog.get(id);return r?{...r,...(r.metadata?{metadata:structuredClone(r.metadata)}:{})}:null;}
  async listCatalogItems(enabledOnly=true){return [...this.catalog.values()].filter(x=>!enabledOnly||x.enabled).map(x=>({...x,...(x.metadata?{metadata:structuredClone(x.metadata)}:{})}));}
  seedCatalog(item:CatalogItemRecord){this.catalog.set(item.id,{...item});}
  seedTool(tool:ToolRecord){this.tools.set(tool.id,{...tool});}
  async getEquippedUsableTool(g:string,u:string,slot:string){const r=[...this.tools.values()].filter(x=>x.guildId===g&&x.userId===u&&x.slot===slot&&x.equipped&&x.durability>0).sort((a,b)=>b.maxDurability-a.maxDurability||b.durability-a.durability)[0];return r?{...r,...(r.metadata?{metadata:structuredClone(r.metadata)}:{})}:null;}
  async commitActivity(input:ActivityCommitInput):Promise<ActivityCommitResult>{const a=this.ensureAccount(input.guildId,input.userId);const existing=this.activityEvents.get(input.idempotencyKey);if(existing)return{status:'duplicate',account:cloneAccount(a),event:{...existing,itemGrants:structuredClone(existing.itemGrants)}};const tk=`${input.guildId}:${input.userId}:${input.activity}`,next=this.throttles.get(tk);if(next&&next>input.now)return{status:'throttled',account:cloneAccount(a)};this.throttles.set(tk,new Date(input.now.getTime()+input.technicalThrottleMs));let actual=input.requestedDelta;if(actual<0n){const loss=(-actual)>(spendableWallet(a)+a.bank)?spendableWallet(a)+a.bank:-actual;actual=-loss;}const lines:LedgerLine[]=[];if(actual>0n){lines.push({userId:input.userId,bucket:'wallet',amount:actual,reason:input.reason,...(input.metadata?{metadata:input.metadata}:{})},{bucket:'system',amount:-actual,reason:input.reason,...(input.metadata?{metadata:input.metadata}:{})});a.wallet+=actual;a.version++;}else if(actual<0n){const loss=-actual,wd=spendableWallet(a)>=loss?loss:spendableWallet(a),bd=loss-wd;if(wd){lines.push({userId:input.userId,bucket:'wallet',amount:-wd,reason:input.reason,...(input.metadata?{metadata:input.metadata}:{})});a.wallet-=wd;}if(bd){lines.push({userId:input.userId,bucket:'bank',amount:-bd,reason:input.reason,...(input.metadata?{metadata:input.metadata}:{})});a.bank-=bd;}lines.push({bucket:'system',amount:loss,reason:input.reason,...(input.metadata?{metadata:input.metadata}:{})});a.version++;}const header=this.transaction(input.guildId,input.idempotencyKey,`GRIND_${input.activity.toUpperCase()}`,input.reason,input.metadata,input.now);if(lines.length)this.ledgerEntries(header,lines,input.now);const grants=[];for(const grant of input.items??[]){if(!this.catalog.get(grant.itemId)?.enabled)throw new DomainError('CATALOG_ITEM_UNAVAILABLE',`Catalog item ${grant.itemId} is unavailable.`);this.grantInventory(input.guildId,input.userId,grant.itemId,grant.quantity);grants.push({...grant});}let tool:ToolRecord|undefined,fallbackTool:ToolRecord|undefined;const damage=Math.max(0,input.toolDamage??0);if(input.toolInstanceId&&damage){const t=this.tools.get(input.toolInstanceId);if(t&&t.guildId===input.guildId&&t.userId===input.userId){t.durability=Math.max(0,t.durability-damage);if(t.durability===0){t.equipped=false;const f=[...this.tools.values()].filter(x=>x.guildId===t.guildId&&x.userId===t.userId&&x.slot===t.slot&&x.id!==t.id&&x.durability>0).sort((x,y)=>y.maxDurability-x.maxDurability||y.durability-x.durability)[0];if(f){for(const candidate of this.tools.values())if(candidate.guildId===f.guildId&&candidate.userId===f.userId&&candidate.slot===f.slot)candidate.equipped=candidate.id===f.id;fallbackTool={...f};}}tool={...t};}}
    const ev:EconomyActivityEventRecord={id:`activity-${++this.seq}`,guildId:input.guildId,userId:input.userId,activity:input.activity,outcome:input.outcome,ottomansDelta:actual,itemGrants:grants,toolDamage:damage,idempotencyKey:input.idempotencyKey,...(input.metadata?{metadata:structuredClone(input.metadata)}:{}),createdAt:new Date(input.now)};this.activityEvents.set(input.idempotencyKey,ev);const sk=tk;let st=this.stats.get(sk);if(!st){st={guildId:input.guildId,userId:input.userId,activity:input.activity,attempts:0,wins:0,zeroes:0,losses:0,fines:0,itemsFound:0,ottomansEarned:0n,ottomansLost:0n,updatedAt:new Date(input.now)};this.stats.set(sk,st);}st.attempts++;if(input.outcome==='win'||input.outcome==='mixed'||input.outcome==='item')st.wins++;if(input.outcome==='zero'||input.outcome==='tool_damage')st.zeroes++;if(input.outcome==='loss')st.losses++;if(input.outcome==='fine')st.fines++;st.itemsFound+=grants.reduce((n,x)=>n+x.quantity,0);if(actual>0n)st.ottomansEarned+=actual;else st.ottomansLost+=-actual;st.lastAttemptAt=new Date(input.now);st.updatedAt=new Date(input.now);return{status:'applied',account:cloneAccount(a),event:{...ev,itemGrants:structuredClone(ev.itemGrants)},...(tool?{tool}:{}),...(fallbackTool?{fallbackTool}:{})};}
  async getActivityStats(g:string,u:string){return [...this.stats.values()].filter(x=>x.guildId===g&&x.userId===u).map(x=>({...x,...(x.lastAttemptAt?{lastAttemptAt:new Date(x.lastAttemptAt)}:{}),updatedAt:new Date(x.updatedAt)}));}
  async commitBankUpgrade(input:BankUpgradeCommitInput){const a=this.ensureAccount(input.guildId,input.userId);if(this.transactions.has(input.idempotencyKey))return cloneAccount(a);if(a.bankTier!==input.currentRule.tier)throw new DomainError('BANK_TIER_CHANGED','Your bank tier changed; reopen /bank and try again.');if(input.currentRule.cap!==null&&a.bank<input.currentRule.cap)throw new DomainError('BANK_NOT_FULL','Your current bank tier must be full before upgrading.');const cost=input.currentRule.upgradeCost;if(spendableWallet(a)+a.bank<cost)throw new DomainError('INSUFFICIENT_FUNDS','You do not have enough Ottomans for the bank upgrade.');const wd=spendableWallet(a)>=cost?cost:spendableWallet(a),bd=cost-wd;const header=this.transaction(input.guildId,input.idempotencyKey,'BANK_UPGRADE',input.reason,{fromTier:a.bankTier,toTier:input.nextRule.tier,cost:cost.toString()},input.now);const lines:LedgerLine[]=[];if(wd){a.wallet-=wd;lines.push({userId:input.userId,bucket:'wallet',amount:-wd,reason:input.reason});}if(bd){a.bank-=bd;lines.push({userId:input.userId,bucket:'bank',amount:-bd,reason:input.reason});}if(cost)lines.push({bucket:'system',amount:cost,reason:input.reason});a.bankTier=input.nextRule.tier;a.version++;if(lines.length)this.ledgerEntries(header,lines,input.now);return cloneAccount(a);}
  async listAccountsAtTier(g:string,tier:number){return [...this.accounts.values()].filter(x=>x.guildId===g&&x.bankTier===tier).map(cloneAccount);}
  async listBankLedgerEntries(g:string,start:Date,end:Date){return this.entries.filter(x=>x.guildId===g&&x.bucket==='bank'&&x.createdAt>=start&&x.createdAt<end).map(x=>({...x,createdAt:new Date(x.createdAt)}));}
  async lockBankInterestTerm(input:import('./repository.js').BankInterestTermRecord){const key=`${input.guildId}:${input.cycleKey}`,existing=this.bankInterestTerms.get(key);if(existing)return{...existing};this.bankInterestTerms.set(key,{...input});return{...input};}
  async getActivityPayoutCounter(guildId:string,userId:string,cycleKey:string){const key=`${guildId}:${userId}:${cycleKey}`,existing=this.activityPayoutCounters.get(key);if(existing)return{...existing};const fresh={guildId,userId,cycleKey,chatPaidWindows:0,chatPaidAmount:0n,voiceQualifiedSeconds:0,voicePaidSeconds:0,voicePaidAmount:0n};this.activityPayoutCounters.set(key,fresh);return{...fresh};}
  async commitActivityPayout(input:ActivityPayoutCommitInput):Promise<ActivityPayoutCommitResult>{
    if(input.requestedReward<0n||input.dailyCap<0n)throw new DomainError('INVALID_ACTIVITY_PAYOUT','Activity payout values cannot be negative.');
    const a=this.ensureAccount(input.guildId,input.userId),counterKey=`${input.guildId}:${input.userId}:${input.cycleKey}`;
    let counter=this.activityPayoutCounters.get(counterKey);if(!counter){counter={guildId:input.guildId,userId:input.userId,cycleKey:input.cycleKey,chatPaidWindows:0,chatPaidAmount:0n,voiceQualifiedSeconds:0,voicePaidSeconds:0,voicePaidAmount:0n};this.activityPayoutCounters.set(counterKey,counter);}
    if(this.transactions.has(input.idempotencyKey))return{status:'duplicate',account:cloneAccount(a),counter,reward:0n};
    const paid=input.kind==='chat'?counter.chatPaidAmount:counter.voicePaidAmount;
    const reward=input.requestedReward>input.dailyCap-paid?input.dailyCap-paid:input.requestedReward;
    const header=this.transaction(input.guildId,input.idempotencyKey,`ACTIVITY_${input.kind.toUpperCase()}`,input.reason,input.metadata,input.now);
    if(input.kind==='chat'){counter.chatPaidWindows+=Math.max(0,Math.trunc(input.chatWindows??1));counter.chatPaidAmount+=reward;}else{counter.voiceQualifiedSeconds+=Math.max(0,Math.trunc(input.voiceQualifiedSeconds??0));counter.voicePaidSeconds+=Math.max(0,Math.trunc(input.voicePaidSeconds??0));counter.voicePaidAmount+=reward;}
    if(reward>0n){a.wallet+=reward;a.version++;this.ledgerEntries(header,[{userId:input.userId,bucket:'wallet',amount:reward,reason:input.reason,...(input.metadata?{metadata:input.metadata}:{})},{bucket:'system',amount:-reward,reason:input.reason,...(input.metadata?{metadata:input.metadata}:{})}],input.now);}
    return{status:reward>0n?'applied':'capped',account:cloneAccount(a),counter:{...counter},reward,transaction:{...header}};
  }
  async upsertBankInterestJob(input:{guildId:string;dueAt:Date;cycleKey:string}){this.scheduledJobs.set(input.guildId,{guildId:input.guildId,dueAt:new Date(input.dueAt),cycleKey:input.cycleKey});}
  async upsertEconomySnapshotJob(input:{guildId:string;dueAt:Date;cycleKey:string}){this.scheduledJobs.set(`snapshot:${input.guildId}`,{guildId:input.guildId,dueAt:new Date(input.dueAt),cycleKey:input.cycleKey});}
  async upsertEconomyPolicyJob(input:{guildId:string;dueAt:Date;cycleKey:string}){this.scheduledJobs.set(`policy:${input.guildId}`,{guildId:input.guildId,dueAt:new Date(input.dueAt),cycleKey:input.cycleKey});}
  async captureEconomySnapshot(input:{guildId:string;cycleKey:string}){const key=`${input.guildId}:${input.cycleKey}`,existing=this.snapshots.get(key);if(existing)return structuredClone(existing);const accounts=[...this.accounts.values()].filter(x=>x.guildId===input.guildId),reconciled=reconcileEconomy({accounts,escrow:[],pots:[]}),record={guildId:input.guildId,cycleKey:input.cycleKey,totalSupply:reconciled.totalSupply,eligibleMemberCount:accounts.length,metrics:{wallet:reconciled.memberWallet.toString(),bank:reconciled.memberBank.toString(),memberEscrow:reconciled.memberEscrow.toString(),communalPots:reconciled.communalPots.toString()}};this.snapshots.set(key,record);return structuredClone(record);}
  async listEconomySnapshots(guildId:string,limit:number){return [...this.snapshots.values()].filter(x=>x.guildId===guildId).sort((a,b)=>b.cycleKey.localeCompare(a.cycleKey)).slice(0,limit).map(x=>({...x,rawMedianWealth:BigInt(String(x.metrics.rawMedianWealth??0)),reconciliationValid:true,abnormalActivity:false}));}
  async saveEconomyPolicyProposal(input:import('./repository.js').EconomyPolicyProposal){if(!this.policyProposals.some(x=>x.guildId===input.guildId&&x.cycleKey===input.cycleKey))this.policyProposals.push(structuredClone(input));}
}
