import type {LedgerLine,LedgerTransaction} from '../../core/src/index.js';
import {DomainError} from '../../core/src/index.js';
import type {ActivityCommitInput,ActivityCommitResult,BankUpgradeCommitInput,ClaimCommitInput,ClaimCommitResult,EconomyRepository,StarterCommitResult} from './repository.js';
import type {CatalogItemRecord,EconomyAccountRecord,EconomyActivityEventRecord,EconomyActivityStatRecord,EconomyLedgerEntryRecord,EconomyTransactionRecord,InventoryEntryRecord,MemberClaimStateRecord,ToolRecord} from './types.js';

type AccountRow={id:string;guildId:string;userId:string;wallet:bigint;bank:bigint;bankTier:number;version:number;starterGrantedAt:Date|null};
type TxRow={id:string;guildId:string;idempotencyKey:string;kind:string;reason:string;metadata:unknown;createdAt:Date};
type EntryRow={id:string;guildId:string;transactionId:string;userId:string|null;bucket:string;amount:bigint;reason:string;metadata:unknown;createdAt:Date};
type ClaimRow={guildId:string;userId:string;dailyLastClaimAt:Date|null;dailyStreak:number;weeklyLastClaimAt:Date|null;dailySpinLastAt:Date|null;fortuneLastAt:Date|null;updatedAt:Date};
type CatalogRow={id:string;type:string;name:string;rarity:string;buyPrice:bigint|null;sellValue:bigint|null;giftable:boolean;enabled:boolean;metadata:unknown};
type InventoryRow={id:string;guildId:string;userId:string;itemId:string;quantity:number;locked:boolean;metadata:unknown};
type ToolRow={id:string;guildId:string;userId:string;catalogItemId:string;slot:string;durability:number;maxDurability:number;equipped:boolean;metadata:unknown};
type StatRow={guildId:string;userId:string;activity:string;attempts:number;wins:number;zeroes:number;losses:number;fines:number;itemsFound:number;ottomansEarned:bigint;ottomansLost:bigint;lastAttemptAt:Date|null;updatedAt:Date};
type ActivityRow={id:string;guildId:string;userId:string;activity:string;outcome:string;ottomansDelta:bigint;itemGrants:unknown;toolDamage:number;idempotencyKey:string;metadata:unknown;createdAt:Date};
type ThrottleRow={guildId:string;userId:string;action:string;nextAllowedAt:Date;updatedAt:Date};

interface DbLike {
  member:{upsert(args:any):Promise<any>};
  economyAccount:{upsert(args:any):Promise<AccountRow>;findUnique(args:any):Promise<AccountRow|null>;findMany(args:any):Promise<AccountRow[]>;update(args:any):Promise<AccountRow>;updateMany(args:any):Promise<{count:number}>};
  economyTransaction:{findUnique(args:any):Promise<TxRow|null>;create(args:any):Promise<TxRow>};
  ledgerEntry:{createMany(args:any):Promise<any>;findMany(args:any):Promise<EntryRow[]>};
  memberClaimState:{upsert(args:any):Promise<ClaimRow>;findUnique(args:any):Promise<ClaimRow|null>;updateMany(args:any):Promise<{count:number}>};
  catalogItem:{findUnique(args:any):Promise<CatalogRow|null>;findMany(args:any):Promise<CatalogRow[]>};
  inventoryEntry:{findMany(args:any):Promise<InventoryRow[]>;upsert(args:any):Promise<InventoryRow>};
  toolInstance:{findUnique(args:any):Promise<ToolRow|null>;findFirst(args:any):Promise<ToolRow|null>;findMany(args:any):Promise<ToolRow[]>;update(args:any):Promise<ToolRow>;updateMany(args:any):Promise<{count:number}>};
  economyActivityStat:{findMany(args:any):Promise<StatRow[]>;upsert(args:any):Promise<StatRow>};
  economyActivityEvent:{findUnique(args:any):Promise<ActivityRow|null>;create(args:any):Promise<ActivityRow>};
  economyActionThrottle:{findUnique(args:any):Promise<ThrottleRow|null>;create(args:any):Promise<ThrottleRow>;updateMany(args:any):Promise<{count:number}>};
  scheduledJob:{upsert(args:any):Promise<any>};
  $transaction<T>(fn:(tx:Omit<DbLike,'$transaction'>)=>Promise<T>):Promise<T>;
}

const obj=(v:unknown)=>v&&typeof v==='object'?v as Record<string,unknown>:undefined;
const account=(r:AccountRow):EconomyAccountRecord=>({guildId:r.guildId,userId:r.userId,wallet:r.wallet,bank:r.bank,bankTier:r.bankTier,version:r.version,...(r.starterGrantedAt?{starterGrantedAt:r.starterGrantedAt}:{})});
const txRec=(r:TxRow):EconomyTransactionRecord=>({id:r.id,guildId:r.guildId,idempotencyKey:r.idempotencyKey,kind:r.kind,reason:r.reason,...(obj(r.metadata)?{metadata:obj(r.metadata)!}:{}),createdAt:r.createdAt});
const entry=(r:EntryRow):EconomyLedgerEntryRecord=>({id:r.id,guildId:r.guildId,transactionId:r.transactionId,...(r.userId?{userId:r.userId}:{}),bucket:r.bucket as EconomyLedgerEntryRecord['bucket'],amount:r.amount,reason:r.reason,...(obj(r.metadata)?{metadata:obj(r.metadata)!}:{}),createdAt:r.createdAt});
const claim=(r:ClaimRow):MemberClaimStateRecord=>({guildId:r.guildId,userId:r.userId,dailyStreak:r.dailyStreak,...(r.dailyLastClaimAt?{dailyLastClaimAt:r.dailyLastClaimAt}:{}),...(r.weeklyLastClaimAt?{weeklyLastClaimAt:r.weeklyLastClaimAt}:{}),...(r.dailySpinLastAt?{dailySpinLastAt:r.dailySpinLastAt}:{}),...(r.fortuneLastAt?{fortuneLastAt:r.fortuneLastAt}:{}),updatedAt:r.updatedAt});
const catalog=(r:CatalogRow):CatalogItemRecord=>({id:r.id,type:r.type,name:r.name,rarity:r.rarity,...(r.buyPrice===null?{}:{buyPrice:r.buyPrice}),...(r.sellValue===null?{}:{sellValue:r.sellValue}),giftable:r.giftable,enabled:r.enabled,...(obj(r.metadata)?{metadata:obj(r.metadata)!}:{})});
const inventory=(r:InventoryRow,item?:CatalogItemRecord):InventoryEntryRecord=>({id:r.id,guildId:r.guildId,userId:r.userId,itemId:r.itemId,quantity:r.quantity,locked:r.locked,...(obj(r.metadata)?{metadata:obj(r.metadata)!}:{}),...(item?{item}:{})});
const tool=(r:ToolRow):ToolRecord=>({id:r.id,guildId:r.guildId,userId:r.userId,catalogItemId:r.catalogItemId,slot:r.slot,durability:r.durability,maxDurability:r.maxDurability,equipped:r.equipped,...(obj(r.metadata)?{metadata:obj(r.metadata)!}:{})});
const stat=(r:StatRow):EconomyActivityStatRecord=>({guildId:r.guildId,userId:r.userId,activity:r.activity as EconomyActivityStatRecord['activity'],attempts:r.attempts,wins:r.wins,zeroes:r.zeroes,losses:r.losses,fines:r.fines,itemsFound:r.itemsFound,ottomansEarned:r.ottomansEarned,ottomansLost:r.ottomansLost,...(r.lastAttemptAt?{lastAttemptAt:r.lastAttemptAt}:{}),updatedAt:r.updatedAt});
const activity=(r:ActivityRow):EconomyActivityEventRecord=>({id:r.id,guildId:r.guildId,userId:r.userId,activity:r.activity as EconomyActivityEventRecord['activity'],outcome:r.outcome as EconomyActivityEventRecord['outcome'],ottomansDelta:r.ottomansDelta,itemGrants:Array.isArray(r.itemGrants)?r.itemGrants as any:[],toolDamage:r.toolDamage,idempotencyKey:r.idempotencyKey,...(obj(r.metadata)?{metadata:obj(r.metadata)!}:{}),createdAt:r.createdAt});
const isUnique=(e:unknown)=>Boolean(e&&typeof e==='object'&&'code' in e&&(e as {code?:unknown}).code==='P2002');
class Conflict extends Error{}

export class PrismaEconomyRepository implements EconomyRepository {
  constructor(private readonly db:DbLike){}
  async ensureMember(g:string,u:string){await this.db.member.upsert({where:{guildId_userId:{guildId:g,userId:u}},update:{},create:{guildId:g,userId:u}});}
  private async ensureAccountOn(db:Omit<DbLike,'$transaction'>,g:string,u:string){await db.member.upsert({where:{guildId_userId:{guildId:g,userId:u}},update:{},create:{guildId:g,userId:u}});return db.economyAccount.upsert({where:{guildId_userId:{guildId:g,userId:u}},update:{},create:{guildId:g,userId:u}});}
  async getAccount(g:string,u:string){return account(await this.ensureAccountOn(this.db,g,u));}
  async getEconomyAccount(g:string,u:string){return account(await this.ensureAccountOn(this.db,g,u));}
  async hasIdempotencyKey(k:string){return Boolean(await this.db.economyTransaction.findUnique({where:{idempotencyKey:k}}));}
  async getTransactionByIdempotencyKey(k:string){const r=await this.db.economyTransaction.findUnique({where:{idempotencyKey:k}});return r?txRec(r):null;}

  private async addLedgerRows(db:Omit<DbLike,'$transaction'>,header:TxRow,lines:LedgerTransaction['lines'],now:Date){if(!lines.length)return;await db.ledgerEntry.createMany({data:lines.map(l=>({guildId:header.guildId,transactionId:header.id,userId:l.userId??null,bucket:l.bucket,amount:l.amount,reason:l.reason,metadata:l.metadata??null,createdAt:now}))});}
  async commit(input:LedgerTransaction,expectedVersions:ReadonlyMap<string,number>){try{return await this.db.$transaction(async db=>{if(await db.economyTransaction.findUnique({where:{idempotencyKey:input.idempotencyKey}}))return true;const header=await db.economyTransaction.create({data:{guildId:input.guildId,idempotencyKey:input.idempotencyKey,kind:'LEDGER',reason:input.lines[0]?.reason??'Ledger transaction',metadata:null}});for(const [userId,version] of expectedVersions){const wd=input.lines.filter(x=>x.userId===userId&&x.bucket==='wallet').reduce((n,x)=>n+x.amount,0n);const bd=input.lines.filter(x=>x.userId===userId&&x.bucket==='bank').reduce((n,x)=>n+x.amount,0n);const r=await db.economyAccount.updateMany({where:{guildId:input.guildId,userId,version},data:{wallet:{increment:wd},bank:{increment:bd},version:{increment:1}}});if(r.count!==1)throw new Conflict();}await this.addLedgerRows(db,header,input.lines,new Date());return true;});}catch(e){if(e instanceof Conflict)return false;if(isUnique(e)){if(await this.hasIdempotencyKey(input.idempotencyKey))return true;}throw e;}}

  async grantStarter(input:{guildId:string;userId:string;amount:bigint;idempotencyKey:string;now:Date}):Promise<StarterCommitResult>{try{return await this.db.$transaction(async db=>{const existingTx=await db.economyTransaction.findUnique({where:{idempotencyKey:input.idempotencyKey}});let a=await this.ensureAccountOn(db,input.guildId,input.userId);if(existingTx)return{status:'duplicate' as const,account:account(a)};if(a.starterGrantedAt)return{status:'existing' as const,account:account(a)};const header=await db.economyTransaction.create({data:{guildId:input.guildId,idempotencyKey:input.idempotencyKey,kind:'STARTER',reason:'One-time starter balance',metadata:{amount:input.amount.toString()},createdAt:input.now}});const updated=await db.economyAccount.updateMany({where:{guildId:input.guildId,userId:input.userId,starterGrantedAt:null,version:a.version},data:{wallet:{increment:input.amount},starterGrantedAt:input.now,version:{increment:1}}});if(updated.count!==1)throw new Conflict();a=(await db.economyAccount.findUnique({where:{guildId_userId:{guildId:input.guildId,userId:input.userId}}}))!;if(input.amount!==0n)await this.addLedgerRows(db,header,[{userId:input.userId,bucket:'wallet',amount:input.amount,reason:'One-time starter balance'},{bucket:'system',amount:-input.amount,reason:'One-time starter balance'}],input.now);return{status:'applied' as const,account:account(a)};});}catch(e){if(e instanceof Conflict){const a=await this.getEconomyAccount(input.guildId,input.userId);return{status:a.starterGrantedAt?'existing':'duplicate',account:a};}if(isUnique(e)){const a=await this.getEconomyAccount(input.guildId,input.userId);return{status:'duplicate',account:a};}throw e;}}
  async listLedgerEntries(g:string,u:string,l:number){return (await this.db.ledgerEntry.findMany({where:{guildId:g,userId:u},orderBy:{createdAt:'desc'},take:l})).map(entry);}
  async getClaimState(g:string,u:string){await this.ensureMember(g,u);const r=await this.db.memberClaimState.upsert({where:{guildId_userId:{guildId:g,userId:u}},update:{},create:{guildId:g,userId:u}});return claim(r);}

  async commitClaim(input:ClaimCommitInput):Promise<ClaimCommitResult>{try{return await this.db.$transaction(async db=>{const existing=await db.economyTransaction.findUnique({where:{idempotencyKey:input.idempotencyKey}});let a=await this.ensureAccountOn(db,input.guildId,input.userId);let state=await db.memberClaimState.upsert({where:{guildId_userId:{guildId:input.guildId,userId:input.userId}},update:{},create:{guildId:input.guildId,userId:input.userId}});if(existing)return{status:'duplicate' as const,account:account(a),state:claim(state),inventory:[]};const where:any={guildId:input.guildId,userId:input.userId,OR:[{[input.claimField]:null},{[input.claimField]:{lt:input.cycleStart}}]};const data:any={[input.claimField]:input.now};if(input.dailyStreak!==undefined)data.dailyStreak=input.dailyStreak;const claimed=await db.memberClaimState.updateMany({where,data});if(claimed.count!==1)return{status:'already_used' as const,account:account(a),state:claim(state),inventory:[]};const header=await db.economyTransaction.create({data:{guildId:input.guildId,idempotencyKey:input.idempotencyKey,kind:input.kind,reason:input.reason,metadata:input.metadata??null,createdAt:input.now}});if(input.walletReward!==0n){a=await db.economyAccount.update({where:{guildId_userId:{guildId:input.guildId,userId:input.userId}},data:{wallet:{increment:input.walletReward},version:{increment:1}}});await this.addLedgerRows(db,header,[{userId:input.userId,bucket:'wallet',amount:input.walletReward,reason:input.reason,...(input.metadata?{metadata:input.metadata}:{})},{bucket:'system',amount:-input.walletReward,reason:input.reason,...(input.metadata?{metadata:input.metadata}:{})}],input.now);}const granted:InventoryEntryRecord[]=[];for(const g of input.items??[]){const item=await db.catalogItem.findUnique({where:{id:g.itemId}});if(!item?.enabled)throw new DomainError('CATALOG_ITEM_UNAVAILABLE',`Catalog item ${g.itemId} is unavailable.`);const row=await db.inventoryEntry.upsert({where:{guildId_userId_itemId:{guildId:input.guildId,userId:input.userId,itemId:g.itemId}},create:{guildId:input.guildId,userId:input.userId,itemId:g.itemId,quantity:g.quantity,locked:false},update:{quantity:{increment:g.quantity}}});granted.push(inventory(row,catalog(item)));}state=(await db.memberClaimState.findUnique({where:{guildId_userId:{guildId:input.guildId,userId:input.userId}}}))!;return{status:'applied' as const,account:account(a),state:claim(state),inventory:granted,transaction:txRec(header)};});}catch(e){if(isUnique(e)){const state=await this.getClaimState(input.guildId,input.userId);return{status:'duplicate',account:await this.getEconomyAccount(input.guildId,input.userId),state,inventory:[]};}throw e;}}

  async listInventory(g:string,u:string){const rows=await this.db.inventoryEntry.findMany({where:{guildId:g,userId:u,quantity:{gt:0}},orderBy:{itemId:'asc'}});const ids=[...new Set(rows.map(x=>x.itemId))];const items=await this.db.catalogItem.findMany({where:{id:{in:ids}}});const by=new Map(items.map(x=>[x.id,catalog(x)]));return rows.map(x=>inventory(x,by.get(x.itemId))).sort((a,b)=>(a.item?.name??a.itemId).localeCompare(b.item?.name??b.itemId));}
  async getCatalogItem(id:string){const r=await this.db.catalogItem.findUnique({where:{id}});return r?catalog(r):null;}
  async listCatalogItems(enabledOnly=true){return (await this.db.catalogItem.findMany({where:enabledOnly?{enabled:true}:{},orderBy:[{rarity:'asc'},{name:'asc'}]})).map(catalog);}
  async getEquippedUsableTool(g:string,u:string,slot:string){const r=await this.db.toolInstance.findFirst({where:{guildId:g,userId:u,slot,equipped:true,durability:{gt:0}},orderBy:[{maxDurability:'desc'},{durability:'desc'}]});return r?tool(r):null;}

  private async claimThrottle(db:Omit<DbLike,'$transaction'>,input:ActivityCommitInput){const current=await db.economyActionThrottle.findUnique({where:{guildId_userId_action:{guildId:input.guildId,userId:input.userId,action:input.activity}}});const next=new Date(input.now.getTime()+input.technicalThrottleMs);if(current){if(current.nextAllowedAt>input.now)return false;const u=await db.economyActionThrottle.updateMany({where:{guildId:input.guildId,userId:input.userId,action:input.activity,nextAllowedAt:{lte:input.now}},data:{nextAllowedAt:next}});return u.count===1;}try{await db.economyActionThrottle.create({data:{guildId:input.guildId,userId:input.userId,action:input.activity,nextAllowedAt:next}});return true;}catch(e){if(isUnique(e))return false;throw e;}}
  async commitActivity(input:ActivityCommitInput):Promise<ActivityCommitResult>{try{return await this.db.$transaction(async db=>{const existing=await db.economyTransaction.findUnique({where:{idempotencyKey:input.idempotencyKey}});let a=await this.ensureAccountOn(db,input.guildId,input.userId);if(existing){const ev=await db.economyActivityEvent.findUnique({where:{idempotencyKey:input.idempotencyKey}});return{status:'duplicate' as const,account:account(a),...(ev?{event:activity(ev)}:{})};}if(!await this.claimThrottle(db,input))return{status:'throttled' as const,account:account(a)};let actual=input.requestedDelta;if(actual<0n){const available=a.wallet+a.bank;const requested=-actual;actual=-(requested>available?available:requested);}const header=await db.economyTransaction.create({data:{guildId:input.guildId,idempotencyKey:input.idempotencyKey,kind:`GRIND_${input.activity.toUpperCase()}`,reason:input.reason,metadata:input.metadata??null,createdAt:input.now}});const lines:LedgerLine[]=[];if(actual>0n){a=await db.economyAccount.update({where:{guildId_userId:{guildId:input.guildId,userId:input.userId}},data:{wallet:{increment:actual},version:{increment:1}}});lines.push({userId:input.userId,bucket:'wallet',amount:actual,reason:input.reason,...(input.metadata?{metadata:input.metadata}:{})},{bucket:'system',amount:-actual,reason:input.reason,...(input.metadata?{metadata:input.metadata}:{})});}else if(actual<0n){const loss=-actual,wd=a.wallet>=loss?loss:a.wallet,bd=loss-wd;const update:any={version:{increment:1}};if(wd)update.wallet={decrement:wd};if(bd)update.bank={decrement:bd};a=await db.economyAccount.update({where:{guildId_userId:{guildId:input.guildId,userId:input.userId}},data:update});if(wd)lines.push({userId:input.userId,bucket:'wallet',amount:-wd,reason:input.reason,...(input.metadata?{metadata:input.metadata}:{})});if(bd)lines.push({userId:input.userId,bucket:'bank',amount:-bd,reason:input.reason,...(input.metadata?{metadata:input.metadata}:{})});lines.push({bucket:'system',amount:loss,reason:input.reason,...(input.metadata?{metadata:input.metadata}:{})});}await this.addLedgerRows(db,header,lines,input.now);for(const g of input.items??[]){const item=await db.catalogItem.findUnique({where:{id:g.itemId}});if(!item?.enabled)throw new DomainError('CATALOG_ITEM_UNAVAILABLE',`Catalog item ${g.itemId} is unavailable.`);await db.inventoryEntry.upsert({where:{guildId_userId_itemId:{guildId:input.guildId,userId:input.userId,itemId:g.itemId}},create:{guildId:input.guildId,userId:input.userId,itemId:g.itemId,quantity:g.quantity,locked:false},update:{quantity:{increment:g.quantity}}});}
        let outTool:ToolRecord|undefined,fallbackTool:ToolRecord|undefined;const damage=Math.max(0,input.toolDamage??0);if(input.toolInstanceId&&damage){const current=await db.toolInstance.findUnique({where:{id:input.toolInstanceId}});if(current&&current.guildId===input.guildId&&current.userId===input.userId){const nextDurability=Math.max(0,current.durability-damage);const updated=await db.toolInstance.update({where:{id:current.id},data:{durability:nextDurability,...(nextDurability===0?{equipped:false}:{})}});outTool=tool(updated);if(nextDurability===0){const fallback=await db.toolInstance.findFirst({where:{guildId:current.guildId,userId:current.userId,slot:current.slot,id:{not:current.id},durability:{gt:0}},orderBy:[{maxDurability:'desc'},{durability:'desc'}]});if(fallback){await db.toolInstance.updateMany({where:{guildId:current.guildId,userId:current.userId,slot:current.slot},data:{equipped:false}});const equipped=await db.toolInstance.update({where:{id:fallback.id},data:{equipped:true}});fallbackTool=tool(equipped);}}}}
        const grants=(input.items??[]).map(x=>({itemId:x.itemId,quantity:x.quantity}));const ev=await db.economyActivityEvent.create({data:{guildId:input.guildId,userId:input.userId,activity:input.activity,outcome:input.outcome,ottomansDelta:actual,itemGrants:grants,toolDamage:damage,idempotencyKey:input.idempotencyKey,metadata:input.metadata??null,createdAt:input.now}});const earned=actual>0n?actual:0n,lost=actual<0n?-actual:0n;const counts={wins:['win','mixed','item'].includes(input.outcome)?1:0,zeroes:['zero','tool_damage'].includes(input.outcome)?1:0,losses:input.outcome==='loss'?1:0,fines:input.outcome==='fine'?1:0,itemsFound:grants.reduce((n,x)=>n+x.quantity,0)};await db.economyActivityStat.upsert({where:{guildId_userId_activity:{guildId:input.guildId,userId:input.userId,activity:input.activity}},create:{guildId:input.guildId,userId:input.userId,activity:input.activity,attempts:1,...counts,ottomansEarned:earned,ottomansLost:lost,lastAttemptAt:input.now},update:{attempts:{increment:1},wins:{increment:counts.wins},zeroes:{increment:counts.zeroes},losses:{increment:counts.losses},fines:{increment:counts.fines},itemsFound:{increment:counts.itemsFound},ottomansEarned:{increment:earned},ottomansLost:{increment:lost},lastAttemptAt:input.now}});return{status:'applied' as const,account:account(a),event:activity(ev),...(outTool?{tool:outTool}:{}),...(fallbackTool?{fallbackTool}:{})};});}catch(e){if(isUnique(e)){const ev=await this.db.economyActivityEvent.findUnique({where:{idempotencyKey:input.idempotencyKey}});if(ev)return{status:'duplicate',account:await this.getEconomyAccount(input.guildId,input.userId),event:activity(ev)};return{status:'throttled',account:await this.getEconomyAccount(input.guildId,input.userId)};}throw e;}}
  async getActivityStats(g:string,u:string){return (await this.db.economyActivityStat.findMany({where:{guildId:g,userId:u},orderBy:{activity:'asc'}})).map(stat);}

  async commitBankUpgrade(input:BankUpgradeCommitInput){try{return await this.db.$transaction(async db=>{if(await db.economyTransaction.findUnique({where:{idempotencyKey:input.idempotencyKey}}))return account(await this.ensureAccountOn(db,input.guildId,input.userId));const a=await this.ensureAccountOn(db,input.guildId,input.userId);if(a.bankTier!==input.currentRule.tier)throw new DomainError('BANK_TIER_CHANGED','Your bank tier changed; reopen /bank and try again.');if(input.currentRule.cap!==null&&a.bank<input.currentRule.cap)throw new DomainError('BANK_NOT_FULL','Your current bank tier must be full before upgrading.');const cost=input.currentRule.upgradeCost;if(a.wallet+a.bank<cost)throw new DomainError('INSUFFICIENT_FUNDS','You do not have enough Ottomans for the bank upgrade.');const wd=a.wallet>=cost?cost:a.wallet,bd=cost-wd;const header=await db.economyTransaction.create({data:{guildId:input.guildId,idempotencyKey:input.idempotencyKey,kind:'BANK_UPGRADE',reason:input.reason,metadata:{fromTier:a.bankTier,toTier:input.nextRule.tier,cost:cost.toString()},createdAt:input.now}});const data:any={bankTier:input.nextRule.tier,version:{increment:1}};if(wd)data.wallet={decrement:wd};if(bd)data.bank={decrement:bd};const changed=await db.economyAccount.updateMany({where:{guildId:input.guildId,userId:input.userId,version:a.version,bankTier:a.bankTier},data});if(changed.count!==1)throw new Conflict();const lines:LedgerLine[]=[];if(wd)lines.push({userId:input.userId,bucket:'wallet',amount:-wd,reason:input.reason});if(bd)lines.push({userId:input.userId,bucket:'bank',amount:-bd,reason:input.reason});if(cost)lines.push({bucket:'system',amount:cost,reason:input.reason});await this.addLedgerRows(db,header,lines,input.now);return account((await db.economyAccount.findUnique({where:{guildId_userId:{guildId:input.guildId,userId:input.userId}}}))!);});}catch(e){if(e instanceof Conflict)throw new DomainError('LEDGER_CONFLICT','Concurrent balance change; reopen /bank and try again.');if(isUnique(e))return this.getEconomyAccount(input.guildId,input.userId);throw e;}}
  async listAccountsAtTier(g:string,tier:number){return (await this.db.economyAccount.findMany({where:{guildId:g,bankTier:tier},orderBy:{userId:'asc'}})).map(account);}
  async upsertBankInterestJob(input:{guildId:string;dueAt:Date;cycleKey:string}){const executionKey=`economy.bank_interest_weekly:${input.guildId}:${input.cycleKey}`;await this.db.scheduledJob.upsert({where:{executionKey},create:{guildId:input.guildId,jobType:'economy.bank_interest_weekly',executionKey,dueAt:input.dueAt,status:'PENDING',payload:{guildId:input.guildId,cycleKey:input.cycleKey}},update:{dueAt:input.dueAt,status:'PENDING',payload:{guildId:input.guildId,cycleKey:input.cycleKey},lastError:null,completedAt:null}});}
}
