import type {AuditService,Clock,LedgerLine} from '../../core/src/index.js';
import {DomainError,LedgerEngine,spendableWallet} from '../../core/src/index.js';
import type {EconomyRepository} from './repository.js';
import {balancedSystemReward} from './repository.js';
import type {ActivityResult,BankTierRule,BankView,ClaimResult,DailyHubState,FortuneEntry,FortuneResult,GrindActivity,GrindOutcomeRule,GrindPolicy,InventoryEntryRecord,RandomSource,SpinResult,SpinReward,StatementView,WeeklyResult} from './types.js';
import {MathRandomSource} from './types.js';

const TZ='America/Denver';
const DAY=86_400_000;
const money=(n:bigint)=>n.toString();
const clampInt=(n:number,min:number,max:number)=>Math.max(min,Math.min(max,Math.trunc(n)));
const parts=(date:Date,timeZone=TZ)=>Object.fromEntries(new Intl.DateTimeFormat('en-US',{timeZone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',hourCycle:'h23',minute:'2-digit',second:'2-digit'}).formatToParts(date).filter(p=>p.type!=='literal').map(p=>[p.type,Number(p.value)])) as Record<'year'|'month'|'day'|'hour'|'minute'|'second',number>;
const offsetMs=(date:Date,timeZone=TZ)=>{const p=parts(date,timeZone);return Date.UTC(p.year,p.month-1,p.day,p.hour,p.minute,p.second)-Math.floor(date.getTime()/1000)*1000;};
export const zonedDateTimeToUtc=(year:number,month:number,day:number,hour:number,timeZone=TZ)=>{let guess=Date.UTC(year,month-1,day,hour,0,0);for(let i=0;i<3;i++)guess=Date.UTC(year,month-1,day,hour,0,0)-offsetMs(new Date(guess),timeZone);return new Date(guess);};
const localCalendarDate=(date:Date,timeZone=TZ)=>{const p=parts(date,timeZone);return{year:p.year,month:p.month,day:p.day,hour:p.hour};};
const addLocalDays=(y:number,m:number,d:number,delta:number)=>{const t=new Date(Date.UTC(y,m-1,d+delta));return{year:t.getUTCFullYear(),month:t.getUTCMonth()+1,day:t.getUTCDate()};};
const dateKey=(x:{year:number;month:number;day:number})=>`${x.year}-${String(x.month).padStart(2,'0')}-${String(x.day).padStart(2,'0')}`;
export const dailyCycle=(now:Date,resetHour=4,timeZone=TZ)=>{const p=localCalendarDate(now,timeZone);let d={year:p.year,month:p.month,day:p.day};if(p.hour<resetHour)d=addLocalDays(d.year,d.month,d.day,-1);const start=zonedDateTimeToUtc(d.year,d.month,d.day,resetHour,timeZone);const n=addLocalDays(d.year,d.month,d.day,1);return{key:dateKey(d),start,next:zonedDateTimeToUtc(n.year,n.month,n.day,resetHour,timeZone)};};
const dayIndex=(name:string)=>({SUNDAY:0,MONDAY:1,TUESDAY:2,WEDNESDAY:3,THURSDAY:4,FRIDAY:5,SATURDAY:6}[name.toUpperCase()]??1);
export const weeklyCycle=(now:Date,resetDay='MONDAY',resetHour=4,timeZone=TZ)=>{const p=localCalendarDate(now,timeZone);const currentDow=new Date(Date.UTC(p.year,p.month-1,p.day)).getUTCDay();const target=dayIndex(resetDay);let back=(currentDow-target+7)%7;if(back===0&&p.hour<resetHour)back=7;const d=addLocalDays(p.year,p.month,p.day,-back);const start=zonedDateTimeToUtc(d.year,d.month,d.day,resetHour,timeZone);const n=addLocalDays(d.year,d.month,d.day,7);return{key:dateKey(d),start,next:zonedDateTimeToUtc(n.year,n.month,n.day,resetHour,timeZone)};};
export const nextMondayBankInterest=(now:Date,timeZone=TZ)=>{const c=weeklyCycle(now,'MONDAY',4,timeZone);return c.next;};
/** Next durable EAJ 1.1 snapshot boundary: 4:00 AM Mountain, DST-safe. */
export const nextEconomySnapshot=(now:Date,timeZone=TZ)=>dailyCycle(now,4,timeZone).next;

const chooseWeighted=<T extends {weight:number}>(items:readonly T[],r:number):T=>{const valid=items.filter(x=>Number.isFinite(x.weight)&&x.weight>0);if(!valid.length)throw new DomainError('EMPTY_REWARD_TABLE','Reward table has no positive weights.');const total=valid.reduce((n,x)=>n+x.weight,0);let point=Math.max(0,Math.min(0.999999999,r))*total;for(const x of valid){point-=x.weight;if(point<0)return x;}return valid[valid.length-1]!;};
const randomBigInt=(min:bigint,max:bigint,r:number)=>{if(max<min)[min,max]=[max,min];const span=max-min+1n;const scaled=BigInt(Math.floor(Math.max(0,Math.min(0.999999999,r))*1_000_000));return min+(span*scaled/1_000_000n);};
const isSameOrAfter=(d:Date|undefined,start:Date)=>Boolean(d&&d>=start);

export class EconomyService {
  private readonly ledger:LedgerEngine;
  constructor(private readonly repository:EconomyRepository,private readonly audit:AuditService,private readonly clock:Clock,private readonly random:RandomSource=new MathRandomSource(),private readonly fortunes:readonly FortuneEntry[]=[]){this.ledger=new LedgerEngine(repository);}

  async bootstrap(guildId:string,userId:string,starterAmount:bigint,requestKey:string){if(starterAmount<0n||starterAmount>100_000n)throw new DomainError('INVALID_STARTER_AMOUNT','Starter amount must be between 0 and 100,000 Ottomans.');await this.repository.ensureMember(guildId,userId);return this.repository.grantStarter({guildId,userId,amount:starterAmount,idempotencyKey:`starter:${guildId}:${userId}:${requestKey}`,now:this.clock.now()});}
  async account(guildId:string,userId:string){await this.repository.ensureMember(guildId,userId);return this.repository.getEconomyAccount(guildId,userId);}
  async statement(guildId:string,userId:string,limit=12):Promise<StatementView>{const account=await this.account(guildId,userId);const entries=await this.repository.listLedgerEntries(guildId,userId,clampInt(limit,1,50));return{account,liquidNetWorth:account.wallet+account.bank,entries};}
  async inventory(guildId:string,userId:string):Promise<InventoryEntryRecord[]>{await this.repository.ensureMember(guildId,userId);return this.repository.listInventory(guildId,userId);}

  private async retryLedger(factory:()=>ReturnType<EconomyService['buildTransferTx']>,attempts=4){let last:unknown;for(let i=0;i<attempts;i++){try{return await this.ledger.apply(await factory());}catch(error){last=error;if(!(error instanceof DomainError)||error.code!=='LEDGER_CONFLICT')throw error;}}throw last;}
  private async buildTransferTx(guildId:string,fromUserId:string,toUserId:string,amount:bigint,idempotencyKey:string){const source=await this.repository.getEconomyAccount(guildId,fromUserId);const target=await this.repository.getEconomyAccount(guildId,toUserId);if(spendableWallet(source)+source.bank<amount)throw new DomainError('INSUFFICIENT_FUNDS','You do not have enough Ottomans.');const fromWallet=spendableWallet(source)>=amount?amount:spendableWallet(source);const fromBank=amount-fromWallet;const lines:LedgerLine[]=[];if(fromWallet)lines.push({userId:fromUserId,bucket:'wallet',amount:-fromWallet,reason:'Member transfer',metadata:{toUserId}});if(fromBank)lines.push({userId:fromUserId,bucket:'bank',amount:-fromBank,reason:'Member transfer',metadata:{toUserId}});lines.push({userId:toUserId,bucket:'wallet',amount,reason:'Member transfer',metadata:{fromUserId}});return{guildId,idempotencyKey,lines} as const;}
  async transfer(input:{guildId:string;fromUserId:string;toUserId:string;amount:bigint;idempotencyKey:string}){if(input.fromUserId===input.toUserId)throw new DomainError('SELF_TRANSFER','You cannot transfer Ottomans to yourself.');if(input.amount<=0n||input.amount>10_000_000n)throw new DomainError('INVALID_TRANSFER','Transfer amount must be between 1 and 10,000,000 Ottomans.');await Promise.all([this.repository.ensureMember(input.guildId,input.fromUserId),this.repository.ensureMember(input.guildId,input.toUserId)]);const status=await this.retryLedger(()=>this.buildTransferTx(input.guildId,input.fromUserId,input.toUserId,input.amount,input.idempotencyKey));return{status,from:await this.repository.getEconomyAccount(input.guildId,input.fromUserId),to:await this.repository.getEconomyAccount(input.guildId,input.toUserId)};}

  bankView(account:Awaited<ReturnType<EconomyService['account']>>,tiers:readonly BankTierRule[]):BankView{const ordered=this.validateBankTiers(tiers);const rule=ordered.find(x=>x.tier===account.bankTier)??ordered[0]!;const nextRule=ordered.find(x=>x.tier===account.bankTier+1);return{account,rule,...(nextRule?{nextRule}:{})};}
  async deposit(input:{guildId:string;userId:string;amount:bigint;idempotencyKey:string;tiers:readonly BankTierRule[]}){if(input.amount<=0n)throw new DomainError('INVALID_BANK_AMOUNT','Deposit must be greater than zero.');const tiers=this.validateBankTiers(input.tiers);const account=await this.account(input.guildId,input.userId);const rule=tiers.find(x=>x.tier===account.bankTier)!;if(spendableWallet(account)<input.amount)throw new DomainError('INSUFFICIENT_WALLET','Your wallet does not have enough Ottomans for that deposit.');if(rule.cap!==null&&account.bank+input.amount>rule.cap)throw new DomainError('BANK_CAP','That deposit would exceed your current bank tier capacity.');const tx={guildId:input.guildId,idempotencyKey:input.idempotencyKey,lines:[{userId:input.userId,bucket:'wallet' as const,amount:-input.amount,reason:'Bank deposit'},{userId:input.userId,bucket:'bank' as const,amount:input.amount,reason:'Bank deposit'}]};await this.ledger.apply(tx);return this.repository.getEconomyAccount(input.guildId,input.userId);}
  async withdraw(input:{guildId:string;userId:string;amount:bigint;idempotencyKey:string}){if(input.amount<=0n)throw new DomainError('INVALID_BANK_AMOUNT','Withdrawal must be greater than zero.');const account=await this.account(input.guildId,input.userId);if(account.bank<input.amount)throw new DomainError('INSUFFICIENT_BANK','Your bank does not have enough Ottomans for that withdrawal.');await this.ledger.apply({guildId:input.guildId,idempotencyKey:input.idempotencyKey,lines:[{userId:input.userId,bucket:'bank',amount:-input.amount,reason:'Bank withdrawal'},{userId:input.userId,bucket:'wallet',amount:input.amount,reason:'Bank withdrawal'}]});return this.repository.getEconomyAccount(input.guildId,input.userId);}
  async upgradeBank(input:{guildId:string;userId:string;idempotencyKey:string;tiers:readonly BankTierRule[]}){const tiers=this.validateBankTiers(input.tiers);const account=await this.account(input.guildId,input.userId);if(account.bankTier>=5)throw new DomainError('BANK_MAX_TIER','Your bank is already Tier 5.');const current=tiers.find(x=>x.tier===account.bankTier)!;const next=tiers.find(x=>x.tier===account.bankTier+1)!;if(current.cap!==null&&account.bank<current.cap)throw new DomainError('BANK_NOT_FULL','Your current bank tier must be full before you can upgrade it.');if(spendableWallet(account)+account.bank<current.upgradeCost)throw new DomainError('INSUFFICIENT_FUNDS','You do not have enough Ottomans for the bank upgrade.');const upgraded=await this.repository.commitBankUpgrade({guildId:input.guildId,userId:input.userId,idempotencyKey:input.idempotencyKey,currentRule:current,nextRule:next,reason:`Bank upgrade Tier ${current.tier} → Tier ${next.tier}`,now:this.clock.now()});await this.audit.record({guildId:input.guildId,actorUserId:input.userId,source:'discord',action:'economy.bank_upgrade',targetType:'member',targetId:input.userId,before:{tier:current.tier},after:{tier:next.tier,cost:money(current.upgradeCost)},requestId:input.idempotencyKey,createdAt:this.clock.now()});return upgraded;}
  validateBankTiers(tiers:readonly BankTierRule[]){if(tiers.length!==5)throw new DomainError('INVALID_BANK_TIERS','Bank configuration must define exactly five tiers.');const ordered=[...tiers].sort((a,b)=>a.tier-b.tier);for(let i=0;i<5;i++){const t=ordered[i]!;if(t.tier!==i+1||t.upgradeCost<0n||t.upgradeCost>10_000_000n)throw new DomainError('INVALID_BANK_TIERS','Bank tier configuration is invalid.');if(t.tier<5&&(t.cap===null||t.cap<=0n))throw new DomainError('INVALID_BANK_TIERS','Bank tiers 1–4 require positive capacity limits.');if(t.tier===5&&t.cap!==null)throw new DomainError('INVALID_BANK_TIERS','Tier 5 must be unlimited.');if(i>0&&t.cap!==null&&ordered[i-1]!.cap!==null&&t.cap!<=ordered[i-1]!.cap!)throw new DomainError('INVALID_BANK_TIERS','Bank capacities must increase by tier.');}return ordered;}

  async dailyHub(guildId:string,userId:string,resetHour=4):Promise<DailyHubState>{await this.repository.ensureMember(guildId,userId);const state=await this.repository.getClaimState(guildId,userId);const cycle=dailyCycle(this.clock.now(),resetHour);return{cycleKey:cycle.key,resetAt:cycle.next,dailyReady:!isSameOrAfter(state.dailyLastClaimAt,cycle.start),spinReady:!isSameOrAfter(state.dailySpinLastAt,cycle.start),fortuneReady:!isSameOrAfter(state.fortuneLastAt,cycle.start),streak:state.dailyStreak};}
  async claimDaily(input:{guildId:string;userId:string;idempotencyKey:string;baseReward?:bigint;minReward?:bigint;maxReward?:bigint;milestones:Readonly<Record<number,bigint>>;resetHour?:number}):Promise<ClaimResult>{const min=input.minReward??input.baseReward,max=input.maxReward??input.baseReward;if(min===undefined||max===undefined||min<0n||max<min||max>100_000n)throw new DomainError('INVALID_DAILY_REWARD','Daily reward is outside the supported bounds.');const now=this.clock.now();const cycle=dailyCycle(now,input.resetHour??4);const prev=dailyCycle(new Date(cycle.start.getTime()-1),input.resetHour??4);const state=await this.repository.getClaimState(input.guildId,input.userId);if(isSameOrAfter(state.dailyLastClaimAt,cycle.start))return{status:'already_used',account:await this.repository.getEconomyAccount(input.guildId,input.userId),reward:0n,bonus:0n,streak:state.dailyStreak,cycleKey:cycle.key};const continued=Boolean(state.dailyLastClaimAt&&state.dailyLastClaimAt>=prev.start&&state.dailyLastClaimAt<cycle.start);const streak=continued?state.dailyStreak+1:1;const bonus=input.milestones[streak]??0n;if(bonus<0n||bonus>1_000_000n)throw new DomainError('INVALID_DAILY_MILESTONE','Daily milestone reward is outside the supported bounds.');const base=randomBigInt(min,max,this.random.next()),reward=base+bonus;const out=await this.repository.commitClaim({guildId:input.guildId,userId:input.userId,claimField:'dailyLastClaimAt',cycleStart:cycle.start,now,idempotencyKey:input.idempotencyKey,kind:'DAILY_CLAIM',reason:'Daily claim',walletReward:reward,dailyStreak:streak,metadata:{cycleKey:cycle.key,base:money(base),minimum:money(min),maximum:money(max),bonus:money(bonus),streak}});return{status:out.status,account:out.account,reward:out.status==='applied'?reward:0n,bonus:out.status==='applied'?bonus:0n,streak:out.state.dailyStreak,cycleKey:cycle.key};}
  async spinDaily(input:{guildId:string;userId:string;idempotencyKey:string;table:readonly SpinReward[];resetHour?:number}):Promise<SpinResult>{const now=this.clock.now();const cycle=dailyCycle(now,input.resetHour??4);const state=await this.repository.getClaimState(input.guildId,input.userId);if(isSameOrAfter(state.dailySpinLastAt,cycle.start))return{status:'already_used',account:await this.repository.getEconomyAccount(input.guildId,input.userId),cycleKey:cycle.key};const reward=this.validateSpinReward(chooseWeighted(input.table,this.random.next()));const items=reward.kind==='item'&&reward.itemId?[{itemId:reward.itemId,quantity:reward.quantity??1}]:[];if(items.length){const item=await this.repository.getCatalogItem(items[0]!.itemId);if(!item?.enabled)throw new DomainError('SPIN_ITEM_UNAVAILABLE','The configured Daily Spin item is unavailable.');}const cash=reward.kind==='ottomans'?(reward.amount??0n):0n;const out=await this.repository.commitClaim({guildId:input.guildId,userId:input.userId,claimField:'dailySpinLastAt',cycleStart:cycle.start,now,idempotencyKey:input.idempotencyKey,kind:'DAILY_SPIN',reason:'Daily Spin',walletReward:cash,items,metadata:{cycleKey:cycle.key,reward:{kind:reward.kind,amount:money(cash),itemId:reward.itemId??null,quantity:reward.quantity??null,label:reward.label??null}}});return{status:out.status,account:out.account,cycleKey:cycle.key,...(out.status==='applied'?{reward,inventory:out.inventory}:{})};}
  private validateSpinReward(r:SpinReward){if(r.kind==='ottomans'){if(r.amount===undefined||r.amount<0n||r.amount>100_000n)throw new DomainError('INVALID_SPIN_REWARD','Daily Spin Ottoman reward is outside supported bounds.');}else{if(!r.itemId||!Number.isInteger(r.quantity??1)||(r.quantity??1)<1||(r.quantity??1)>10)throw new DomainError('INVALID_SPIN_REWARD','Daily Spin item reward is invalid.');}return r;}
  async fortuneDaily(input:{guildId:string;userId:string;idempotencyKey:string;resetHour?:number}):Promise<FortuneResult>{const now=this.clock.now();const cycle=dailyCycle(now,input.resetHour??4);const state=await this.repository.getClaimState(input.guildId,input.userId);if(isSameOrAfter(state.fortuneLastAt,cycle.start))return{status:'already_used',cycleKey:cycle.key};const enabled=this.fortunes.filter(x=>x.enabled!==false&&x.text.trim());if(!enabled.length)throw new DomainError('FORTUNE_BANK_EMPTY','No enabled fortunes are available.');const fortune=enabled[Math.floor(this.random.next()*enabled.length)%enabled.length]!;const out=await this.repository.commitClaim({guildId:input.guildId,userId:input.userId,claimField:'fortuneLastAt',cycleStart:cycle.start,now,idempotencyKey:input.idempotencyKey,kind:'DAILY_FORTUNE',reason:'Daily Fortune',walletReward:0n,metadata:{cycleKey:cycle.key,fortuneId:fortune.id}});return{status:out.status,cycleKey:cycle.key,...(out.status==='applied'?{fortune}:{})};}
  async weekly(input:{guildId:string;userId:string;idempotencyKey:string;reward?:bigint;minReward?:bigint;maxReward?:bigint;resetDay?:string;resetHour?:number}):Promise<WeeklyResult>{const min=input.minReward??input.reward,max=input.maxReward??input.reward;if(min===undefined||max===undefined||min<0n||max<min||max>500_000n)throw new DomainError('INVALID_WEEKLY_REWARD','Weekly reward is outside supported bounds.');const now=this.clock.now();const cycle=weeklyCycle(now,input.resetDay??'MONDAY',input.resetHour??4);const state=await this.repository.getClaimState(input.guildId,input.userId);if(isSameOrAfter(state.weeklyLastClaimAt,cycle.start))return{status:'already_used',account:await this.repository.getEconomyAccount(input.guildId,input.userId),reward:0n,cycleKey:cycle.key};const reward=randomBigInt(min,max,this.random.next());const out=await this.repository.commitClaim({guildId:input.guildId,userId:input.userId,claimField:'weeklyLastClaimAt',cycleStart:cycle.start,now,idempotencyKey:input.idempotencyKey,kind:'WEEKLY_CLAIM',reason:'Weekly claim',walletReward:reward,metadata:{cycleKey:cycle.key,reward:money(reward),minimum:money(min),maximum:money(max)}});return{status:out.status,account:out.account,reward:out.status==='applied'?reward:0n,cycleKey:cycle.key};}

  async grind(input:{guildId:string;userId:string;activity:GrindActivity;idempotencyKey:string;policy:GrindPolicy}):Promise<ActivityResult>{const policy=this.validateGrindPolicy(input.policy);const now=this.clock.now();await this.repository.ensureMember(input.guildId,input.userId);let tool=undefined as Awaited<ReturnType<EconomyRepository['getEquippedUsableTool']>>|undefined;if(input.activity!=='work'){const slot=input.activity==='fish'?'fishing_rod':input.activity==='dig'?'shovel':'scavenging_tool';tool=await this.repository.getEquippedUsableTool(input.guildId,input.userId,slot);if(!tool)throw new DomainError('TOOL_REQUIRED',`You need an equipped usable ${slot.replace(/_/g,' ')} before using /${input.activity}.`);}const rule=this.validateGrindOutcome(chooseWeighted(policy.outcomes,this.random.next()));if(input.activity==='work'&&rule.itemId)throw new DomainError('INVALID_WORK_REWARD','/work may award Ottomans or tool damage only; item drops are not allowed.');let delta=0n;if(rule.minOttomans!==undefined||rule.maxOttomans!==undefined){delta=randomBigInt(rule.minOttomans??0n,rule.maxOttomans??rule.minOttomans??0n,this.random.next());if(rule.outcome==='loss'||rule.outcome==='fine')delta=-delta;}const items=rule.itemId?[{itemId:rule.itemId,quantity:rule.quantity??1}]:[];if(items.length){const item=await this.repository.getCatalogItem(items[0]!.itemId);if(!item?.enabled)throw new DomainError('GRIND_ITEM_UNAVAILABLE',`Configured /${input.activity} item ${items[0]!.itemId} is unavailable.`);}const workTool=input.activity==='work'&&rule.outcome==='tool_damage'?await this.repository.getEquippedUsableTool(input.guildId,input.userId,'workshop_tool'):tool;const out=await this.repository.commitActivity({guildId:input.guildId,userId:input.userId,activity:input.activity,outcome:rule.outcome,idempotencyKey:input.idempotencyKey,reason:`/${input.activity} outcome: ${rule.outcome}`,now,technicalThrottleMs:policy.technicalThrottleMs,requestedDelta:delta,items,...(workTool?{toolInstanceId:workTool.id,toolDamage:rule.toolDamage??(input.activity==='work'?5:1)}:{}),metadata:{configuredDelta:money(delta)}});return out;}
  private validateGrindPolicy(p:GrindPolicy){if(!Number.isInteger(p.technicalThrottleMs)||p.technicalThrottleMs<250||p.technicalThrottleMs>5_000)throw new DomainError('INVALID_GRIND_POLICY','Technical grind throttle must be 250–5000ms.');if(!p.outcomes.length||p.outcomes.length>30)throw new DomainError('INVALID_GRIND_POLICY','Grind outcome table is invalid.');return p;}
  private validateGrindOutcome(r:GrindOutcomeRule){const min=r.minOttomans??0n,max=r.maxOttomans??min;if(min<0n||max<0n||min>10_000n||max>10_000n)throw new DomainError('INVALID_GRIND_REWARD','Grind Ottoman values must be 0–10,000.');if(r.quantity!==undefined&&(!Number.isInteger(r.quantity)||r.quantity<1||r.quantity>10))throw new DomainError('INVALID_GRIND_REWARD','Grind item quantity must be 1–10.');if(r.toolDamage!==undefined&&(!Number.isInteger(r.toolDamage)||r.toolDamage<0||r.toolDamage>25))throw new DomainError('INVALID_GRIND_REWARD','Tool damage must be 0–25.');return r;}

  async applyTier5Interest(input:{guildId:string;cycleKey:string;interestBps:number;maxPerMember:bigint}){const bps=clampInt(input.interestBps,0,500);if(bps!==input.interestBps)throw new DomainError('INVALID_BANK_INTEREST','Tier 5 weekly interest must be 0–500 basis points.');if(input.maxPerMember<0n||input.maxPerMember>1_000_000n)throw new DomainError('INVALID_BANK_INTEREST','Weekly interest cap is outside supported bounds.');const accounts=await this.repository.listAccountsAtTier(input.guildId,5);let credited=0n,members=0,duplicates=0;for(const a of accounts){const raw=a.bank*BigInt(bps)/10_000n;const amount=raw>input.maxPerMember?input.maxPerMember:raw;if(amount<=0n)continue;const key=`bank-interest:${input.guildId}:${input.cycleKey}:${a.userId}`;const status=await this.ledger.apply(balancedSystemReward(input.guildId,a.userId,amount,key,'Tier 5 weekly bank interest','bank',{cycleKey:input.cycleKey,bps}));if(status==='duplicate'){duplicates++;continue;}credited+=amount;members++;}return{members,credited,duplicates};}
  async scheduleNextBankInterest(guildId:string){const dueAt=nextMondayBankInterest(this.clock.now());const c=weeklyCycle(new Date(dueAt.getTime()+1000),'MONDAY',4);await this.repository.upsertBankInterestJob({guildId,dueAt,cycleKey:c.key});return dueAt;}
  async scheduleNextEconomySnapshot(guildId:string){const dueAt=nextEconomySnapshot(this.clock.now()),c=dailyCycle(new Date(dueAt.getTime()+1000));await this.repository.upsertEconomySnapshotJob({guildId,dueAt,cycleKey:c.key});return dueAt;}
  async scheduleNextEconomyPolicy(guildId:string){const dueAt=nextMondayBankInterest(this.clock.now()),c=weeklyCycle(new Date(dueAt.getTime()+1000),'MONDAY',4);await this.repository.upsertEconomyPolicyJob({guildId,dueAt,cycleKey:c.key});return dueAt;}
  async captureEconomySnapshot(guildId:string,cycleKey:string){const snapshot=await this.repository.captureEconomySnapshot({guildId,cycleKey});await this.scheduleNextEconomySnapshot(guildId);return snapshot;}
}
