import {createHash,randomInt} from 'node:crypto';
import {DomainError,VotingEngine,type Ballot} from '../../core/src/index.js';
export const PARTY_GAMES=['truthordare','wwyd','finishsentence','onewordstory','fmk'] as const;
export type PartyGame=typeof PARTY_GAMES[number];
export type PartyPhase='choose'|'answer'|'submissions'|'story'|'vote'|'runoff'|'done';
export interface PartyMember {userId:string;name:string;}
export interface PartyOption {id:string;text:string;userId?:string;}
export interface PartyData {game:PartyGame;phase:PartyPhase;category:string;seed:string;round:number;promptId?:string;prompt?:string;options:PartyOption[];target?:PartyMember;mode?:'truth'|'dare'|'random'|'custom';visibility?:'private'|'public';answer?:string;skipped?:boolean;submissions:Record<string,{name:string;text:string}>;words:{userId:string;name:string;word:string}[];targetLength?:number;trio?:PartyMember[];assignments?:{fuck:string;marry:string;kill:string};draftFuck?:string;draftMarry?:string;subjectCounters?:Record<string,{fucked:number;married:number;killed:number}>;result?:{totals:Record<string,number>;percentages:Record<string,number>;total:number;winnerId?:string;randomResolution:boolean;label:string};sourceId?:string;}
export function validateStoryLength(value:number){if(!Number.isInteger(value)||value<10||value>200)throw new DomainError('STORY_LENGTH','Choose a story length from 10 to 200 words.');return value;}
export function partyText(value:string,max=1000){const text=value.trim();if(!text||text.length>max||/[\u0000-\u0008\u000b\u000c\u000e-\u001f]/.test(text))throw new DomainError('PARTY_TEXT',`Enter 1–${max} characters.`);return text;}
export function storyWord(value:string){const word=partyText(value,40);if(/\s/u.test(word))throw new DomainError('ONE_WORD','Add exactly one word per turn.');return word;}
export function drawTrio(members:readonly PartyMember[],excluded:readonly string[]=[],rng:(max:number)=>number=randomInt){const pool=[...new Map(members.filter(m=>!excluded.includes(m.userId)).map(m=>[m.userId,m])).values()];if(pool.length<3)throw new DomainError('FMK_MEMBERS','Three different eligible current members are needed for a fresh trio.');const result:PartyMember[]=[];for(let n=0;n<3;n++)result.push(pool.splice(rng(pool.length),1)[0]!);return result;}
export function assignFmk(trio:readonly PartyMember[],fuck:string,marry:string){if(fuck===marry||!trio.some(m=>m.userId===fuck)||!trio.some(m=>m.userId===marry)||trio.length!==3)throw new DomainError('FMK_ASSIGNMENTS','Choose two different members from this trio.');return{fuck,marry,kill:trio.find(m=>m.userId!==fuck&&m.userId!==marry)!.userId};}
export function sharedVoting(options:readonly PartyOption[],ballots:readonly Ballot[]){const engine=new VotingEngine({anonymous:true,editable:true,hiddenUntilClose:true,eligibleChoices:options.map(o=>o.id)});for(const b of ballots)if(options.some(o=>o.id===b.choiceKey))engine.cast(b.voterUserId,b.choiceKey,b.updatedAt,b.questionKey);return engine;}
export function votingResult(data:PartyData,ballots:readonly Ballot[]){const totals=sharedVoting(data.options,ballots).results('round:'+data.round),total=Object.values(totals).reduce((a,b)=>a+b,0),percentages=Object.fromEntries(Object.entries(totals).map(([key,value])=>[key,total?Math.round(value/total*10000)/100:0])),maximum=Math.max(0,...Object.values(totals)),tied=Object.keys(totals).filter(id=>totals[id]===maximum);return{totals,total,percentages,tied};}
export function deterministicTie(seed:string,choices:readonly string[]){if(!choices.length)throw new DomainError('VOTING_CHOICES','No eligible choice remains.');const sorted=[...choices].sort(),value=createHash('sha256').update(seed+':'+sorted.join(',')).digest().readUInt32BE(0);return sorted[value%sorted.length]!;}
