import {randomUUID,randomInt} from 'node:crypto';
import {Prisma,type PrismaClient} from '@prisma/client';
import {DomainError,SessionEngine,TimerEngine,type Session} from '../../core/src/index.js';
import {PrismaAtomicOperations,requestFingerprint} from '../../database/src/atomic-operations.js';
import {PrismaTransactionSessions} from '../../database/src/transaction-sessions.js';
import {PrismaJobDeliveryRepository} from '../../database/src/job-delivery.js';
import {PARTY_GAMES,assignFmk,drawTrio,validateStoryLength,storyWord,partyText,sharedVoting,votingResult,deterministicTie,type PartyData,type PartyGame,type PartyMember,type PartyOption} from './domain.js';
const json=(v:unknown)=>JSON.parse(JSON.stringify(v)) as Prisma.InputJsonObject;
export const PUBLIC_PARTY_TYPES=['wyr','truthordare','wwyd','finishsentence','onewordstory'];
export interface PartyContext {guildId:string;channelId:string;userId:string;requestKey:string;}
export interface PartyStart {game:PartyGame;category?:string;target?:PartyMember;length?:number;mode?:'random'|'custom';customPrompt?:string;members?:PartyMember[];sourceId?:string;}
export class PrismaPartyRepository {
 private atomic:PrismaAtomicOperations;
 constructor(private db:PrismaClient,private clock:()=>Date=()=>new Date(),private rng:(max:number)=>number=randomInt){this.atomic=new PrismaAtomicOperations(db);}
 async get(id:string){const row=await this.db.gameSession.findUnique({where:{id},include:{votes:true}});if(!row||!PARTY_GAMES.includes(row.type as PartyGame))throw new DomainError('PARTY_MISSING','This party round is unavailable.');return{...row,data:row.data as unknown as PartyData};}
 async active(){return this.db.gameSession.findMany({where:{type:{in:[...PARTY_GAMES]},state:{in:['DRAFT','OPEN','LOCKED']}}});}
 async linkMessage(id:string,guildId:string,messageId:string){await this.db.gameSession.updateMany({where:{id,guildId,type:{in:[...PARTY_GAMES]},messageId:null},data:{messageId}});}
 delivery(id:string){return new PrismaJobDeliveryRepository(this.db,id);}
 async deliveryJob(id:string){const row=await this.db.scheduledJob.findUniqueOrThrow({where:{id}});if(row.jobType!=='party.publish')throw new DomainError('PARTY_JOB','Invalid party publication.');return row.payload as {guildId:string;channelId:string;sessionId:string};}
 private async session(tx:Prisma.TransactionClient,c:Pick<PartyContext,'guildId'|'channelId'>,id:string){const s=await new PrismaTransactionSessions(tx).get<PartyData>(id);if(!s||!PARTY_GAMES.includes(s.type as PartyGame)||s.guildId!==c.guildId||s.channelId!==c.channelId)throw new DomainError('PARTY_MISSING','Use this round’s original server and channel.');return s;}
 private owner(s:Session<PartyData>,userId:string){if(s.ownerUserId!==userId)throw new DomainError('HOST_ONLY','Only the host can do that.');}
 private live(s:Session<PartyData>,phases:PartyData['phase'][]){if(!['DRAFT','OPEN'].includes(s.state)||!phases.includes(s.data.phase))throw new DomainError('PARTY_PHASE','That action is no longer available.');if(s.expiresAt&&s.expiresAt<=this.clock())throw new DomainError('PARTY_EXPIRED','This phase has ended.');}
 private async save(tx:Prisma.TransactionClient,s:Session<PartyData>,data:PartyData,state=s.state,expiresAt=s.expiresAt){return new SessionEngine(new PrismaTransactionSessions(tx)).transition<PartyData>(s.id,[s.state],state,current=>({...current,data,...(expiresAt?{expiresAt}:{})}));}
 private async publish(tx:Prisma.TransactionClient,s:Session<PartyData>){const row=await tx.scheduledJob.create({data:{guildId:s.guildId,jobType:'party.publish',executionKey:'party:publish:'+s.id,dueAt:this.clock(),payload:{guildId:s.guildId,channelId:s.channelId,sessionId:s.id,deliveryState:'PENDING'}}});return row.id;}
 private async schedule(tx:Prisma.TransactionClient,s:Session<PartyData>,round:number,dueAt:Date){await tx.scheduledJob.create({data:{guildId:s.guildId,jobType:'party.advance',executionKey:`party:advance:${s.id}:${round}`,dueAt,payload:{guildId:s.guildId,sessionId:s.id,round}}});}
 private async prompt(tx:Prisma.TransactionClient,guildId:string,game:string,category:string,exclude?:string){const recent=await tx.contentUseHistory.findMany({where:{guildId,game,...(category==='Random'?{}:{category})},orderBy:{usedAt:'desc'},take:100});const base={game,enabled:true,...(category==='Random'?{}:{category})};let rows=await tx.contentEntry.findMany({where:{...base,id:{notIn:[...recent.map(r=>r.contentId),...(exclude?[exclude]:[])]}},orderBy:{id:'asc'}});if(!rows.length)rows=await tx.contentEntry.findMany({where:{...base,...(exclude?{id:{not:exclude}}:{})},orderBy:{id:'asc'}});if(!rows.length)throw new DomainError('PARTY_CONTENT','No fresh enabled authored prompt is available in this category.');const row=rows[this.rng(rows.length)]!,payload=row.payload as {text?:string;options?:PartyOption[]};if(typeof payload.text!=='string'||!payload.text.trim()||game==='wwyd'&&(!Array.isArray(payload.options)||payload.options.length<2||payload.options.length>5||new Set(payload.options.map(o=>o.id)).size!==payload.options.length||payload.options.some(o=>typeof o.id!=='string'||typeof o.text!=='string')))throw new DomainError('PARTY_CONTENT','This authored prompt is invalid.');await tx.contentUseHistory.create({data:{guildId,game,contentId:row.id,category:row.category}});await tx.contentEntry.update({where:{id:row.id},data:{useCount:{increment:1},lastUsedAt:this.clock()}});return{id:row.id,text:payload.text,options:payload.options??[],category:row.category??category};}
 async start(c:PartyContext,options:PartyStart){if(!PARTY_GAMES.includes(options.game))throw new DomainError('PARTY_GAME','Unknown party game.');const id=randomUUID();return this.atomic.run(c.guildId,'party:start:'+c.requestKey,requestFingerprint({userId:c.userId,channelId:c.channelId,game:options.game,sourceId:options.sourceId??null,target:options.target?.userId??null,length:options.length??50,category:options.category??'Casual',mode:options.mode??null,custom:options.customPrompt??null}),async tx=>{
  let source:Session<PartyData>|undefined;if(options.sourceId){source=await this.session(tx,c,options.sourceId);if(source.data.game!==options.game||!(options.game==='fmk'?Boolean(source.data.assignments):source.state==='CLOSED'))throw new DomainError('PARTY_REPLAY','Complete this round before playing again.');}
  if(options.game!=='fmk'&&await tx.gameSession.findFirst({where:{guildId:c.guildId,channelId:c.channelId,type:{in:PUBLIC_PARTY_TYPES},state:{in:['DRAFT','OPEN','LOCKED','SETTLING']}}}))throw new DomainError('PARTY_ACTIVE','A public party-game round is already active here.');
  const now=this.clock(),data:PartyData={game:options.game,phase:'choose',category:options.category??source?.data.category??'Casual',seed:randomUUID(),round:0,options:[],submissions:{},words:[],...(options.sourceId?{sourceId:options.sourceId}:{})};let expiresAt:Date|undefined,state:Session<PartyData>['state']='OPEN';
  if(options.game==='truthordare'){if(!options.target)throw new DomainError('PARTY_TARGET','Choose a current eligible target.');data.target=options.target;}
  if(options.game==='wwyd'){const p=await this.prompt(tx,c.guildId,'wwyd',data.category,source?.data.promptId);data.promptId=p.id;data.prompt=p.text;data.options=p.options;data.category=p.category;data.phase='vote';expiresAt=TimerEngine.create(now,60).expiresAt;}
  if(options.game==='finishsentence'&&options.mode){data.mode=options.mode;if(options.mode==='custom'){data.prompt=partyText(options.customPrompt??'',500);}else{const p=await this.prompt(tx,c.guildId,'finishsentence',data.category,source?.data.promptId);data.promptId=p.id;data.prompt=p.text;data.category=p.category;}data.phase='submissions';expiresAt=TimerEngine.create(now,60).expiresAt;}
  if(options.game==='onewordstory'){data.phase='story';data.targetLength=validateStoryLength(options.length??source?.data.targetLength??50);}
  if(options.game==='fmk'){state='DRAFT';data.trio=drawTrio(options.members??[],source?.data.trio?.map(m=>m.userId)??[],this.rng);}
  const s:Session<PartyData>={id,guildId:c.guildId,channelId:c.channelId,ownerUserId:c.userId,type:options.game,state,data,...(expiresAt?{expiresAt}:{}),extensionUsed:false,version:0,createdAt:now,updatedAt:now};await new PrismaTransactionSessions(tx).create({...s,data:json(data)});if(expiresAt)await this.schedule(tx,s,data.round,expiresAt);const jobId=state==='DRAFT'?null:await this.publish(tx,s);return{sessionId:id,jobId};
 });}
 async choosePrompt(c:PartyContext,id:string,mode:'truth'|'dare'|'random'|'custom',custom?:string){return this.atomic.run(c.guildId,'party:prompt:'+c.requestKey,requestFingerprint({id,userId:c.userId,mode,custom:custom??null}),async tx=>{const s=await this.session(tx,c,id);this.live(s,['choose']);const d={...s.data};if(d.game==='truthordare'){if(d.target?.userId!==c.userId)throw new DomainError('TARGET_ONLY','Only the named target can choose.');if(!['truth','dare'].includes(mode))throw new DomainError('PARTY_MODE','Choose Truth or Dare.');const p=await this.prompt(tx,c.guildId,mode,d.category,s.data.sourceId?(await this.session(tx,c,s.data.sourceId)).data.promptId:undefined);Object.assign(d,{mode,promptId:p.id,prompt:p.text,phase:'answer'});await this.save(tx,s,d);}
  else if(d.game==='finishsentence'){this.owner(s,c.userId);if(!['random','custom'].includes(mode))throw new DomainError('PARTY_MODE','Choose Random Prompt or Write My Own.');d.mode=mode;if(mode==='custom')d.prompt=partyText(custom??'',500);else{const previous=d.sourceId?(await this.session(tx,c,d.sourceId)).data.promptId:undefined;const p=await this.prompt(tx,c.guildId,'finishsentence',d.category,previous);Object.assign(d,{prompt:p.text,promptId:p.id,category:p.category});}d.phase='submissions';const expiresAt=TimerEngine.create(this.clock(),60).expiresAt;await this.save(tx,s,d,'OPEN',expiresAt);await this.schedule(tx,s,d.round,expiresAt);}else throw new DomainError('PARTY_MODE','No prompt choice is available.');return{sessionId:id};});}
 async answer(c:PartyContext,id:string,text:string,skip=false){return this.atomic.run(c.guildId,'party:answer:'+c.requestKey,requestFingerprint({id,userId:c.userId,text,skip}),async tx=>{const s=await this.session(tx,c,id);this.live(s,skip?['choose','answer']:['answer']);if(s.data.game!=='truthordare'||s.data.target?.userId!==c.userId)throw new DomainError('TARGET_ONLY','Only the named target may answer or skip.');await this.save(tx,s,{...s.data,phase:'done',...(skip?{skipped:true}:{answer:partyText(text)})},'CLOSED');await this.played(tx,s.guildId,c.userId,'truthordare');return{sessionId:id};});}
 async submit(c:PartyContext,id:string,name:string,text:string){return this.atomic.run(c.guildId,'party:submit:'+c.requestKey,requestFingerprint({id,userId:c.userId,text}),async tx=>{const s=await this.session(tx,c,id);this.live(s,['submissions']);if(s.data.game!=='finishsentence')throw new DomainError('PARTY_PHASE','Submissions are unavailable.');const submissions={...s.data.submissions,[c.userId]:{name:partyText(name,80),text:partyText(text)}};await this.save(tx,s,{...s.data,submissions});await tx.gameParticipant.upsert({where:{sessionId_userId:{sessionId:id,userId:c.userId}},create:{sessionId:id,userId:c.userId,role:'contestant'},update:{}});return{sessionId:id};});}
 async addWord(c:PartyContext,id:string,name:string,value:string){const word=storyWord(value);return this.atomic.run(c.guildId,'party:word:'+c.requestKey,requestFingerprint({id,userId:c.userId,word}),async tx=>{const s=await this.session(tx,c,id);this.live(s,['story']);if(s.data.game!=='onewordstory')throw new DomainError('PARTY_PHASE','Story turns are unavailable.');if(s.data.words.at(-1)?.userId===c.userId)throw new DomainError('STORY_TURN','Let another member add the next word.');const d={...s.data,words:[...s.data.words,{userId:c.userId,name:partyText(name,80),word}]};await tx.gameParticipant.upsert({where:{sessionId_userId:{sessionId:id,userId:c.userId}},create:{sessionId:id,userId:c.userId,role:'contestant'},update:{}});if(d.words.length===d.targetLength){d.options=[...new Map(d.words.map(w=>[w.userId,{id:w.userId,text:w.name,userId:w.userId}])).values()];d.phase='vote';d.round++;const due=TimerEngine.create(this.clock(),60).expiresAt;await this.save(tx,s,d,'OPEN',due);await this.schedule(tx,s,d.round,due);}else await this.save(tx,s,d);return{sessionId:id};});}
 async draftFmk(c:PartyContext,id:string,action:'fuck'|'marry',subjectId:string){return this.atomic.run(c.guildId,'party:fmk_draft:'+c.requestKey,requestFingerprint({id,userId:c.userId,action,subjectId}),async tx=>{const s=await this.session(tx,c,id);this.owner(s,c.userId);this.live(s,['choose']);if(s.data.game!=='fmk'||s.state!=='DRAFT'||!s.data.trio?.some(m=>m.userId===subjectId))throw new DomainError('FMK_SUBJECT','Choose a subject from your private trio.');const d={...s.data};if(action==='fuck'){d.draftFuck=subjectId;if(d.draftMarry===subjectId)delete d.draftMarry;}else{if(!d.draftFuck||d.draftFuck===subjectId)throw new DomainError('FMK_ASSIGNMENTS','Choose Fuck first, then a different member for Marry.');d.draftMarry=subjectId;}await this.save(tx,s,d);return{sessionId:id};});}
 async submitFmk(c:PartyContext,id:string,eligibleIds:readonly string[]){return this.atomic.run(c.guildId,'party:fmk_submit:'+c.requestKey,requestFingerprint({id,userId:c.userId}),async tx=>{const s=await this.session(tx,c,id);this.owner(s,c.userId);this.live(s,['choose']);const d={...s.data};if(d.game!=='fmk'||s.state!=='DRAFT'||!d.trio||!d.draftFuck||!d.draftMarry)throw new DomainError('FMK_ASSIGNMENTS','Finish your private choices before submitting.');if(d.trio.some(m=>!eligibleIds.includes(m.userId)))throw new DomainError('FMK_INELIGIBLE','A subject is no longer eligible. Start a fresh round.');d.assignments=assignFmk(d.trio,d.draftFuck,d.draftMarry);delete d.draftFuck;delete d.draftMarry;d.phase='vote';d.options=[{id:'agree',text:'Agree'},{id:'disagree',text:'Disagree'}];d.subjectCounters={};for(const[key,subject]of Object.entries(d.assignments)){const stat=await tx.memberGameStats.findUnique({where:{guildId_userId_gameKey:{guildId:c.guildId,userId:subject,gameKey:'fmk_subject'}}}),m=stat?.metadata as Record<string,number>|null,counters={fucked:m?.fucked??0,married:m?.married??0,killed:m?.killed??0};counters[key==='fuck'?'fucked':key==='marry'?'married':'killed']++;d.subjectCounters[subject]=counters;await tx.memberGameStats.upsert({where:{guildId_userId_gameKey:{guildId:c.guildId,userId:subject,gameKey:'fmk_subject'}},create:{guildId:c.guildId,userId:subject,gameKey:'fmk_subject',metadata:counters},update:{metadata:counters}});}await this.played(tx,c.guildId,c.userId,'fmk');const due=TimerEngine.create(this.clock(),60).expiresAt;const saved=await this.save(tx,s,d,'OPEN',due);await this.schedule(tx,saved,d.round,due);return{sessionId:id,jobId:await this.publish(tx,saved)};});}
 async privateFmk(c:PartyContext,id:string){const row=await this.get(id);if(row.guildId!==c.guildId||row.channelId!==c.channelId||row.ownerUserId!==c.userId||row.type!=='fmk')throw new DomainError('OWNER_ONLY','Open your own private FMK choices.');const trio=row.data.trio??[],stats=await this.db.memberGameStats.findMany({where:{guildId:c.guildId,userId:{in:trio.map(m=>m.userId)},gameKey:'fmk_subject'},select:{userId:true,metadata:true}}),subjectCounters=Object.fromEntries(trio.map(m=>{const raw=stats.find(s=>s.userId===m.userId)?.metadata as Record<string,unknown>|undefined;return[m.userId,{fucked:Number(raw?.fucked??0),married:Number(raw?.married??0),killed:Number(raw?.killed??0)}];}));return{id:row.id,state:row.state,trio,fuck:row.data.draftFuck,marry:row.data.draftMarry,subjectCounters};}
 async vote(c:PartyContext,id:string,choiceId:string){return this.atomic.run(c.guildId,'party:vote:'+c.requestKey,requestFingerprint({id,userId:c.userId,choiceId}),async tx=>{const s=await this.session(tx,c,id);this.live(s,['vote','runoff']);if(s.data.game==='fmk'&&s.ownerUserId===c.userId)throw new DomainError('FMK_CHOOSER_VOTE','The chooser cannot vote on their own FMK.');const option=s.data.options.find(o=>o.id===choiceId);if(option?.userId===c.userId)throw new DomainError('SELF_VOTE','Vote for another member.');const questionKey='round:'+s.data.round,rows=await tx.vote.findMany({where:{sessionId:id,questionKey}}),engine=sharedVoting(s.data.options,rows);engine.cast(c.userId,choiceId,this.clock(),questionKey);await tx.vote.upsert({where:{sessionId_voterUserId_questionKey:{sessionId:id,voterUserId:c.userId,questionKey}},create:{sessionId:id,voterUserId:c.userId,questionKey,choiceKey:choiceId,anonymous:true},update:{choiceKey:choiceId,anonymous:true}});await this.save(tx,s,s.data);return{sessionId:id};});}
 async extend(c:PartyContext,id:string){return this.atomic.run(c.guildId,'party:extend:'+c.requestKey,requestFingerprint({id,userId:c.userId}),async tx=>{const s=await this.session(tx,c,id);this.owner(s,c.userId);this.live(s,['vote','submissions']);if(!s.expiresAt||!(['fmk','wwyd'].includes(s.data.game)||s.data.game==='finishsentence'&&s.data.phase==='submissions'))throw new DomainError('PARTY_EXTENSION','This phase has no extension.');const timer=TimerEngine.extendOnce({openedAt:s.createdAt,expiresAt:s.expiresAt,extensionUsed:s.extensionUsed},30,this.clock());await new SessionEngine(new PrismaTransactionSessions(tx)).transition<PartyData>(id,['OPEN'],'OPEN',row=>({...row,extensionUsed:true,expiresAt:timer.expiresAt}));await tx.scheduledJob.update({where:{executionKey:`party:advance:${id}:${s.data.round}`},data:{dueAt:timer.expiresAt}});return{sessionId:id};});}
 private async played(tx:Prisma.TransactionClient,guildId:string,userId:string,gameKey:string,win=false){await tx.memberGameStats.upsert({where:{guildId_userId_gameKey:{guildId,userId,gameKey}},create:{guildId,userId,gameKey,plays:1,wins:win?1:0},update:{plays:{increment:1},...(win?{wins:{increment:1}}:{})}});}
 async advance(guildId:string,id:string,round:number){return this.atomic.run(guildId,`party:advance:${id}:${round}`,String(round),async tx=>{const s=await new PrismaTransactionSessions(tx).get<PartyData>(id);if(!s||s.guildId!==guildId||!PARTY_GAMES.includes(s.type as PartyGame))throw new DomainError('PARTY_MISSING','Round unavailable.');if(s.state==='CLOSED'||s.state==='CANCELLED'||s.data.round!==round)return{sessionId:id};if(!s.expiresAt||s.expiresAt>this.clock())throw new DomainError('NOT_DUE','The current phase remains open.');const d={...s.data};
  if(d.phase==='submissions'){d.options=Object.entries(d.submissions).map(([userId,v])=>({id:userId,userId,text:v.text}));if(d.options.length){d.phase='vote';d.round++;const due=TimerEngine.create(this.clock(),30).expiresAt;await this.save(tx,s,d,'OPEN',due);await this.schedule(tx,s,d.round,due);return{sessionId:id};}}
  const ballots=await tx.vote.findMany({where:{sessionId:id,questionKey:'round:'+d.round}}),result=votingResult(d,ballots),creative=['finishsentence','onewordstory'].includes(d.game);let winner:string|undefined,randomResolution=false,label=result.total?'Voting complete':'No votes cast';
  if(creative&&result.total&&result.tied.length>1&&d.phase!=='runoff'){d.options=d.options.filter(o=>result.tied.includes(o.id));d.phase='runoff';d.round++;const due=TimerEngine.create(this.clock(),30).expiresAt;await this.save(tx,s,d,'OPEN',due);await this.schedule(tx,s,d.round,due);return{sessionId:id};}
  if(creative&&(result.total||d.phase==='runoff'&&result.tied.length)){winner=result.tied.length===1?result.tied[0]:deterministicTie(d.seed,result.tied);randomResolution=result.tied.length>1;label=randomResolution?(result.total?'Runoff tied. Deterministic random selection resolved the tie.':'Runoff received no votes. Deterministic random selection resolved the tie.'):'Winner selected';if(winner)await this.played(tx,guildId,winner,'party_games',true);}
  if(creative)for(const userId of new Set([...Object.keys(d.submissions),...d.words.map(w=>w.userId)]))await this.played(tx,guildId,userId,d.game,userId===winner);
  if(d.game==='fmk'){label=result.total===0?'No audience votes':result.totals.agree===result.totals.disagree?'Split Decision':result.totals.agree!>result.totals.disagree!?'Audience agrees':'Audience disagrees';if(result.total){const stat=await tx.memberGameStats.findUniqueOrThrow({where:{guildId_userId_gameKey:{guildId,userId:s.ownerUserId!,gameKey:'fmk'}}}),m=(stat.metadata??{}) as Record<string,number>,agreement=result.percentages.agree!,count=(m.agreementRounds??0)+1,sum=(m.agreementSum??0)+agreement;await tx.memberGameStats.update({where:{guildId_userId_gameKey:{guildId,userId:s.ownerUserId!,gameKey:'fmk'}},data:{metadata:{agreementRounds:count,agreementSum:sum,averageAgreement:sum/count,highestAgreement:Math.max(m.highestAgreement??agreement,agreement),lowestAgreement:Math.min(m.lowestAgreement??agreement,agreement)}}});}}
  d.phase='done';d.result={totals:result.totals,percentages:result.percentages,total:result.total,...(winner?{winnerId:winner}:{}),randomResolution,label};await this.save(tx,s,d,'CLOSED');return{sessionId:id};
 });}
 async publicView(id:string){const row=await this.get(id),d=row.data,privateDraft=row.state==='DRAFT',submitting=d.phase==='submissions';return{id:row.id,guildId:row.guildId,channelId:row.channelId,messageId:row.messageId,ownerId:row.ownerUserId,state:row.state,version:row.version,expiresAt:row.expiresAt,extensionUsed:row.extensionUsed,game:d.game,phase:d.phase,category:d.category,prompt:privateDraft?undefined:d.prompt,options:privateDraft||submitting?[]:d.options,target:d.target,mode:d.mode,answer:d.answer,skipped:d.skipped,submissionCount:Object.keys(d.submissions).length,submissions:privateDraft||submitting?{}:d.submissions,words:d.words,targetLength:d.targetLength,...(!privateDraft&&d.assignments?{trio:d.trio,assignments:d.assignments,subjectCounters:d.subjectCounters}:{}),...(row.state==='CLOSED'?{result:d.result}:{}),round:d.round};}
}
export type PartyView=Awaited<ReturnType<PrismaPartyRepository['publicView']>>;
