import {readFileSync} from 'node:fs';
import {parseEnv} from 'node:util';
import {spawnSync} from 'node:child_process';
import {createRequire} from 'node:module';
import {randomUUID} from 'node:crypto';
import test from 'node:test';
import assert from 'node:assert/strict';
import {PrismaClient} from '@prisma/client';
import {PrismaChannelGamesRepository} from '../../.test-build/packages/features-channel-games/src/prisma-repository.js';
const require=createRequire(import.meta.url),schema='aj_channel_test_'+randomUUID().replaceAll('-',''),value=parseEnv(readFileSync(new URL('../../.env.test.local',import.meta.url),'utf8')).TEST_DATABASE_URL;
const url=new URL(value);url.searchParams.set('schema',schema);const db=new PrismaClient({datasourceUrl:url.toString()});
test('Channel-game PostgreSQL persistence, concurrency, restoration and automatic rounds',async t=>{
 let connected=false;try{try{await db.$connect();connected=true;}catch{assert.fail('Disposable test database connection failed; credentials withheld.');}
 const migration=spawnSync(process.execPath,[require.resolve('prisma/build/index.js'),'migrate','deploy','--schema','packages/database/prisma/schema.prisma'],{env:{...process.env,DATABASE_URL:url.toString()},encoding:'utf8'});assert.equal(migration.status,0,'Isolated migration must succeed.');await db.guild.create({data:{id:'channel',name:'Test Chairs'}});
 let repo=new PrismaChannelGamesRepository(db);const c=(id,userId='a',channelId='count')=>({guildId:'channel',channelId,userId,requestKey:id});
 await t.test('duplicate messages update exactly once after restart',async()=>{await Promise.all([repo.counting(c('1'),'1'),repo.counting(c('1'),'1')]);repo=new PrismaChannelGamesRepository(db);await repo.counting(c('1'),'1');assert.equal((await repo.get('channel','count','counting')).state.count,'1');await assert.rejects(()=>repo.counting(c('1'),'2'),{code:'REPLAY_MISMATCH'});});
 await t.test('same-number racing posts serialize into one valid turn then a visible reset',async()=>{await Promise.all([repo.counting(c('2a','b'),'2'),repo.counting(c('2b','c'),'2')]);const row=await repo.get('channel','count','counting');assert.equal(row.state.count,'0');assert.equal(row.state.restore.count,'2');assert.equal(await db.scheduledJob.count({where:{jobType:'channelgame.announce'}}),1);});
 await t.test('restore is staff-only, audited once and rejects stale controls',async()=>{const before=await repo.get('channel','count','counting');await assert.rejects(()=>repo.restore(c('restore-bad'),before.version,false),{code:'COUNTING_STAFF'});await Promise.all([repo.restore(c('restore'),before.version,true),repo.restore(c('restore'),before.version,true)]);assert.equal((await repo.get('channel','count','counting')).state.count,'2');assert.equal(await db.auditEvent.count({where:{action:'counting.restore'}}),1);await assert.rejects(()=>repo.restore(c('stale'),before.version,true),{code:'COUNTING_CHANGED'});});
 await t.test('milestone award and announcement are atomic and do not repeat on replay',async()=>{await db.channelGameState.update({where:{guildId_channelId_gameKey:{guildId:'channel',channelId:'count',gameKey:'counting'}},data:{state:{count:'99',lastUserId:'b',awardedThrough:'0'}}});await Promise.all([repo.counting(c('100'),'100'),repo.counting(c('100'),'100')]);assert.equal((await db.memberGameStats.findUnique({where:{guildId_userId_gameKey:{guildId:'channel',userId:'a',gameKey:'counting'}}})).wins,1);assert.equal((await repo.get('channel','count','counting')).state.count,'100');});
 await t.test('last-letter duplicate delivery cannot double-score or double-win',async()=>{await db.channelGameState.create({data:{guildId:'channel',channelId:'letter',gameKey:'last_letter',state:{round:3,lastWord:null,lastUserId:null,used:[],scores:{a:49}}}});await Promise.all([repo.letter(c('word','a','letter'),'chair',()=>true),repo.letter(c('word','a','letter'),'chair',()=>true)]);assert.equal((await db.memberGameStats.findUnique({where:{guildId_userId_gameKey:{guildId:'channel',userId:'a',gameKey:'last_letter'}}})).wins,1);const state=(await repo.get('channel','letter','last_letter')).state;assert.equal(state.round,4);assert.deepEqual(state.scores,{});assert.deepEqual(state.used,[]);});
 await t.test('last-letter penalties persist without breaking the valid chain',async()=>{await repo.letter(c('word2','b','letter'),'chair',()=>true);await repo.letter(c('word3','c','letter'),'apple',()=>true);const state=(await repo.get('channel','letter','last_letter')).state;assert.equal(state.lastWord,'chair');assert.equal(state.scores.c,-1);});
 }finally{assert.match(schema,/^aj_channel_test_[0-9a-f]{32}$/);try{if(connected)await db.$executeRawUnsafe(`DROP SCHEMA IF EXISTS "${schema}" CASCADE`);}finally{await db.$disconnect();}}
});
