import {PrismaEventsRepository} from '../../.test-build/packages/features-events/src/prisma-repository.js';
import {readFileSync} from 'node:fs';
import {parseEnv} from 'node:util';
import {spawnSync} from 'node:child_process';
import {createRequire} from 'node:module';
import {randomUUID} from 'node:crypto';
import test from 'node:test';
import assert from 'node:assert/strict';
import {PrismaClient} from '@prisma/client';
import {PrismaEconomyRepository} from '../../.test-build/packages/features-economy/src/prisma-repository.js';
import {PrismaAtomicOperations} from '../../.test-build/packages/database/src/atomic-operations.js';
const require=createRequire(import.meta.url),schema='aj_fight_test_'+randomUUID().replaceAll('-','');
const value=parseEnv(readFileSync(new URL('../../.env.test.local',import.meta.url),'utf8')).TEST_DATABASE_URL;
const url=new URL(value);url.searchParams.set('schema',schema);
const db=new PrismaClient({datasourceUrl:url.toString()});
const seeded=initial=>{let seed=initial;return max=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return Math.floor(seed/4294967296*max);};};
test('Phase 12 PostgreSQL Fight acceptance',async t=>{
 let connected=false,now=new Date('2026-09-25T18:00:00Z'),random=seeded(12345);
 try{
  await db.$connect();connected=true;const migration=spawnSync(process.execPath,[require.resolve('prisma/build/index.js'),'migrate','deploy','--schema','packages/database/prisma/schema.prisma'],{env:{...process.env,DATABASE_URL:url.toString()},encoding:'utf8'});assert.equal(migration.status,0,'Test schema migration must succeed.');await db.guild.create({data:{id:'fight',name:'Test Chairs'}});
  const economy=new PrismaEconomyRepository(db),atomic=new PrismaAtomicOperations(db);for(const userId of ['host','target','a','b'])await economy.grantStarter({guildId:'fight',userId,amount:10000n,idempotencyKey:'starter:'+userId,now});
  const repo=new PrismaEventsRepository(db,max=>random(max),()=>now),policy={minBet:10n,maxBet:1000n},fighters=[{userId:'host',name:'Jordan'},{userId:'target',name:'Alex'}],context=(requestKey,userId='host')=>({guildId:'fight',channelId:'main',userId,requestKey}),account=userId=>db.economyAccount.findUniqueOrThrow({where:{guildId_userId:{guildId:'fight',userId}}});let id,firstPlan;
  await t.test('required target starts immediately; duplicate invocation and shared channel exclusion are durable',async()=>{
   await assert.rejects(()=>repo.startFight(context('self'),[fighters[0],fighters[0]]),{code:'FIGHTERS'});const results=await Promise.all([repo.startFight(context('start'),fighters),repo.startFight(context('start'),fighters)]);id=results[0].sessionId;assert.equal(results[1].sessionId,id);const view=await repo.get(id);assert.equal(view.state,'OPEN');assert.equal(view.expiresAt.getTime(),now.getTime()+30000);assert.equal(view.data.racers.length,2);assert.notEqual(view.data.racers[0].chair,view.data.racers[1].chair);await assert.rejects(()=>repo.startRace(context('race'),fighters[0]),{code:'EVENT_ACTIVE'});await assert.rejects(()=>repo.join(context('join','a'),id,{userId:'a',name:'Third'}),{code:'FIGHT_JOIN'});
  });
  await t.test('only host extends betting once and selected fighter cannot switch after wagering',async()=>{
   await assert.rejects(()=>repo.extend(context('target-extend','target'),id),{code:'HOST_ONLY'});const results=await Promise.allSettled([repo.extend(context('extend1'),id),repo.extend(context('extend2'),id)]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.equal((await repo.get(id)).expiresAt.getTime(),now.getTime()+60000);
   await Promise.all([repo.bet(context('bet-a','a'),id,'host',100n,policy),repo.bet(context('bet-b','b'),id,'target',100n,policy)]);await assert.rejects(()=>repo.bet(context('switch','a'),id,'target',10n,policy),{code:'SELECTION_LOCKED'});
  });
  await t.test('concurrent betting close persists one approved combat plan and restart resumes the same beat',async()=>{
   const preparation=await repo.prepareClose('fight',id);assert.equal((await repo.get(id)).data.fightPlan,undefined);now=new Date(now.getTime()+60001);await Promise.all([repo.closeBetting('fight',id,preparation),repo.closeBetting('fight',id,preparation)]);assert.deepEqual((await repo.get(id)).data.fightPlan,preparation.data.fightPlan);const row=await repo.get(id);firstPlan=row.data.fightPlan;assert.ok(firstPlan.durationMs>=22000&&firstPlan.durationMs<=28000);assert.equal(row.state,'LOCKED');assert.equal(new Set(firstPlan.usedMoveIds).size,firstPlan.beats.length);now=new Date(now.getTime()+12000);const restarted=new PrismaEventsRepository(db,seeded(765),()=>now);assert.deepEqual((await restarted.publicView(id)).combat,(await repo.publicView(id)).combat);assert.equal((await restarted.publicView(id)).combat.winnerId,undefined);await assert.rejects(()=>repo.bet(context('late','a'),id,'host',10n,policy),{code:'BETTING_CLOSED'});
  });
  await t.test('concurrent settlement and restart pay the 95 percent pool once and record the correct fighter win',async()=>{
   now=new Date(now.getTime()+30000);await Promise.all(Array.from({length:4},()=>repo.settle('fight',id)));await new PrismaEventsRepository(db,seeded(55),()=>now).settle('fight',id);const row=await repo.get(id);assert.equal(row.state,'CLOSED');assert.equal(row.data.result.pool,'200');assert.equal(row.data.result.rake,'10');assert.equal(Object.values(row.data.result.payouts).reduce((n,v)=>n+BigInt(v),0n),190n);assert.equal((await account('a')).wallet+(await account('b')).wallet,19990n);assert.equal((await db.memberGameStats.findUniqueOrThrow({where:{guildId_userId_gameKey:{guildId:'fight',userId:firstPlan.winnerId,gameKey:'fight'}}})).wins,1);
  });
  await t.test('NO_WINNING_BETS_REFUND restores both buckets once and recent moves remain suppressed',async()=>{
   const balance=await account('a');await atomic.run('fight','bank','bank',async(tx,ledger)=>{const amount=balance.wallet-100n;await ledger.apply({guildId:'fight',idempotencyKey:'bank-move',lines:[{userId:'a',bucket:'wallet',amount:-amount,reason:'Test bank transfer'},{userId:'a',bucket:'bank',amount,reason:'Test bank transfer'}]});return{ok:true}});const before=await account('a');const second=(await repo.startFight(context('second'),fighters)).sessionId;await repo.bet(context('second-bet','a'),second,'target',500n,policy);let first=true;const rest=seeded(4567);random=max=>{if(first){first=false;assert.equal(max,2);return 0;}return rest(max);};now=new Date(now.getTime()+30001);await repo.closeBetting('fight',second);const plan=(await repo.get(second)).data.fightPlan;assert.equal(plan.winnerId,'host');assert.ok(plan.usedMoveIds.every(move=>!firstPlan.usedMoveIds.includes(move)));now=new Date(now.getTime()+30000);await Promise.all(Array.from({length:4},()=>repo.settle('fight',second)));await new PrismaEventsRepository(db,seeded(2),()=>now).settle('fight',second);const row=await repo.get(second),after=await account('a');assert.equal(row.data.result.settlement,'NO_WINNING_BETS_REFUND');assert.equal(row.data.result.rake,'0');assert.equal(after.wallet,before.wallet);assert.equal(after.bank,before.bank);assert.equal(row.state,'CLOSED');
  });
  await t.test('fighter departure during betting cancels and refunds once',async()=>{
   const third=(await repo.startFight(context('third'),fighters)).sessionId,before=await account('b');await repo.bet(context('third-bet','b'),third,'host',100n,policy);await Promise.all([repo.memberLeft('fight','target',now),repo.memberLeft('fight','target',now)]);assert.equal((await repo.get(third)).state,'CANCELLED');assert.equal((await account('b')).wallet,before.wallet);await repo.closeBetting('fight',third);assert.equal((await repo.get(third)).state,'CANCELLED');
  });
  await t.test('recorded fighter departure during combat prevents subsequent settlement and win credit',async()=>{
   now=new Date(now.getTime()+1000);const fourth=(await repo.startFight(context('fourth'),fighters)).sessionId;const before=await account('b');await repo.bet(context('fourth-bet','b'),fourth,'host',100n,policy);now=new Date(now.getTime()+30001);await repo.closeBetting('fight',fourth);await repo.memberLeft('fight','host',now);now=new Date(now.getTime()+30000);await Promise.all([repo.settle('fight',fourth),repo.memberLeft('fight','host',now)]);assert.equal((await repo.get(fourth)).state,'CANCELLED');assert.equal((await account('b')).wallet,before.wallet);const stats=await db.memberGameStats.findMany({where:{guildId:'fight',gameKey:'fight'}});assert.equal(stats.reduce((n,r)=>n+r.plays,0),4);
  });
  await t.test('simultaneous departure and settlement have one financial terminal outcome',async()=>{
   now=new Date(now.getTime()+1000);const fifth=(await repo.startFight(context('fifth'),fighters)).sessionId;const beforeA=await account('a'),beforeB=await account('b');await repo.bet(context('fifth-a','a'),fifth,'host',100n,policy);await repo.bet(context('fifth-b','b'),fifth,'target',100n,policy);now=new Date(now.getTime()+30001);await repo.closeBetting('fight',fifth);now=new Date(now.getTime()+30000);const race=await Promise.allSettled([repo.memberLeft('fight','target',now),repo.settle('fight',fifth)]);for(const result of race)if(result.status==='rejected')throw result.reason;await new PrismaEventsRepository(db,seeded(222),()=>now).settle('fight',fifth);const row=await repo.get(fifth);assert.ok(['CLOSED','CANCELLED'].includes(row.state));const total=(await account('a')).wallet+(await account('a')).bank+(await account('b')).wallet+(await account('b')).bank,before=beforeA.wallet+beforeA.bank+beforeB.wallet+beforeB.bank;assert.equal(total,before-(row.state==='CLOSED'?10n:0n));const escrows=await db.escrow.findMany({where:{referenceId:fifth}});assert.equal(escrows.length,2);assert.ok(escrows.every(e=>e.state===(row.state==='CLOSED'?'SETTLED':'REFUNDED')));
  });
  await t.test('all financial movements balance and no reserved event escrow remains',async()=>{const totals=new Map();for(const line of await db.ledgerEntry.findMany())totals.set(line.transactionId,(totals.get(line.transactionId)??0n)+line.amount);for(const n of totals.values())assert.equal(n,0n);assert.equal(await db.escrow.count({where:{state:'RESERVED'}}),0);assert.equal(await db.economyAccount.count({where:{OR:[{wallet:{lt:0n}},{bank:{lt:0n}}]}}),0);});
 }finally{assert.match(schema,/^aj_fight_test_[0-9a-f]{32}$/);try{if(connected)await db.$executeRawUnsafe('DROP SCHEMA IF EXISTS "'+schema+'" CASCADE');}finally{await db.$disconnect();}}
});
