import {readFileSync} from 'node:fs';
import {parseEnv} from 'node:util';
import {spawnSync} from 'node:child_process';
import {createRequire} from 'node:module';
import {randomUUID} from 'node:crypto';
import test from 'node:test';
import assert from 'node:assert/strict';
import {PrismaClient} from '@prisma/client';
import {PrismaIntroductionsRepository} from '../../.test-build/packages/features-introductions/src/prisma-repository.js';
import {promptPages} from '../../.test-build/packages/features-introductions/src/domain.js';
import {DeliveryEngine} from '../../.test-build/packages/core/src/delivery.js';
const require=createRequire(import.meta.url),schema='aj_introductions_test_'+randomUUID().replaceAll('-','');
const value=parseEnv(readFileSync(new URL('../../.env.test.local',import.meta.url),'utf8')).TEST_DATABASE_URL;
const url=new URL(value);url.searchParams.set('schema',schema);const db=new PrismaClient({datasourceUrl:url.toString()});
const g='111111111111111111',u='222222222222222222',ch='333333333333333333',message='444444444444444444';
test('Introduction expiry only: isolated PostgreSQL with injected clock',async t=>{let connected=false;try{
 await db.$connect();connected=true;const migration=spawnSync(process.execPath,[require.resolve('prisma/build/index.js'),'migrate','deploy','--schema','packages/database/prisma/schema.prisma'],{env:{...process.env,DATABASE_URL:url.toString()},encoding:'utf8'});assert.equal(migration.status,0,'Isolated schema migration must succeed');await db.guild.create({data:{id:g,name:'Expiry test'}});
 let now=new Date('2026-09-25T12:00:00Z');const repo=new PrismaIntroductionsRepository(db,()=>now),c={guildId:g,userId:u,channelId:ch,requestKey:'start'};await repo.configure(g,ch,null);
 const begin=async(user,key)=>repo.start({...c,userId:user,requestKey:key});const edit=async(user,id,key,text)=>{const ctx={...c,userId:user,requestKey:key},v=await repo.view(ctx,id);await repo.save(ctx,id,v.version,0,Object.fromEntries(promptPages(v.data.form)[0].map(p=>[p.id,text])));};
 const initial=await begin(u,'published-start');await edit(u,initial.id,'published-save','Published answer');await repo.preview({...c,requestKey:'published-preview'},initial.id);const pv=await repo.view(c,initial.id),pj=await repo.enqueue({...c,requestKey:'published-enqueue'},initial.id,pv.version);await repo.delivery(pj.jobId).claim();await repo.delivery(pj.jobId).complete(message);await repo.finalize(pj.jobId);const published=await repo.submission(g,u);
 const draft=await begin(u,'edit-start');const created=await repo.view(c,draft.id);now=new Date(now.getTime()+3600000);await edit(u,draft.id,'unpublished-save','Unpublished edits');const saved=await repo.view(c,draft.id);
 const other='555555555555555555',pending=await begin(other,'pending-start');await edit(other,pending.id,'pending-save','Pending answer');await repo.preview({...c,userId:other,requestKey:'pending-preview'},pending.id);const pendingView=await repo.view({...c,userId:other},pending.id);const pendingJob=await repo.enqueue({...c,userId:other,requestKey:'pending-enqueue'},pending.id,pendingView.version);const pendingBefore=await db.gameSession.findUniqueOrThrow({where:{id:pending.id}}),jobBefore=await db.scheduledJob.findUniqueOrThrow({where:{id:pendingJob.jobId}});
 await t.test('deadline remains creation plus exactly 24h despite edits',async()=>{assert.equal(created.expiresAt.getTime(),new Date('2026-09-26T12:00:00Z').getTime());assert.equal(saved.expiresAt.getTime(),created.expiresAt.getTime());now=new Date(saved.expiresAt.getTime()-1);await repo.view(c,draft.id);});
 await t.test('unusable exactly at expiresAt before sweep',async()=>{now=new Date(saved.expiresAt);await assert.rejects(repo.view(c,draft.id),{code:'INTRO_EXPIRED'});await assert.rejects(repo.save({...c,requestKey:'expired-save'},draft.id,saved.version,0,{}),{code:'INTRO_EXPIRED'});assert.equal((await db.gameSession.findUniqueOrThrow({where:{id:draft.id}})).state,'DRAFT');});
 now=new Date(pendingBefore.expiresAt.getTime()+1);await repo.expireDrafts();
 await t.test('sweep cancels expired draft, increments once and retains answers',async()=>{const after=await db.gameSession.findUniqueOrThrow({where:{id:draft.id}});assert.equal(after.state,'CANCELLED');assert.equal(after.version,saved.version+1);assert.deepEqual(after.data.answers,saved.data.answers);await repo.expireDrafts();assert.equal((await db.gameSession.findUniqueOrThrow({where:{id:draft.id}})).version,after.version);});
 await t.test('expired edits are not resumed; fresh draft uses published answers',async()=>{await assert.rejects(repo.view(c,draft.id),{code:'INTRO_EXPIRED'});const fresh=await begin(u,'fresh-after-expiry'),view=await repo.view(c,fresh.id);assert.notEqual(fresh.id,draft.id);assert.equal(view.state,'DRAFT');assert.deepEqual(view.data.answers,published.answers);assert.notDeepEqual(view.data.answers,saved.data.answers);assert.equal(view.expiresAt.getTime(),now.getTime()+86400000);});
 await t.test('published introduction is unchanged',async()=>assert.deepEqual(await repo.submission(g,u),published));
 await t.test('pending publication session and job survive expiry unchanged',async()=>{assert.equal(pendingBefore.state,'LOCKED');assert.ok(pendingBefore.expiresAt<now);assert.deepEqual(await db.gameSession.findUniqueOrThrow({where:{id:pending.id}}),pendingBefore);assert.deepEqual(await db.scheduledJob.findUniqueOrThrow({where:{id:pendingJob.jobId}}),jobBefore);});
 }finally{assert.match(schema,/^aj_introductions_test_[0-9a-f]{32}$/);try{if(connected)await db.$executeRawUnsafe('DROP SCHEMA IF EXISTS "'+schema+'" CASCADE');}finally{await db.$disconnect();}}});
