import {readFileSync} from 'node:fs';import {parseEnv} from 'node:util';import {spawnSync} from 'node:child_process';import {createRequire} from 'node:module';import {randomUUID} from 'node:crypto';import test from 'node:test';import assert from 'node:assert/strict';import {PrismaClient} from '@prisma/client';
import {PrismaPartyRepository} from '../../.test-build/packages/features-party/src/prisma-repository.js';
import {seedPartyContent} from '../../.test-build/packages/features-party/src/content.js';
import {PrismaWyrPromptRepository,PrismaWyrSessionRepository,WyrService} from '../../.test-build/packages/features-wyr/src/index.js';
const require=createRequire(import.meta.url),schema='aj_party_test_'+randomUUID().replaceAll('-',''),secret=parseEnv(readFileSync(new URL('../../.env.test.local',import.meta.url),'utf8')).TEST_DATABASE_URL;if(!secret)throw Error('Dedicated TEST_DATABASE_URL required.');const url=new URL(secret);url.searchParams.set('schema',schema);const db=new PrismaClient({datasourceUrl:url.toString()});
test('Phase16 shared Voting, party persistence, private FMK and WYR reconciliation',async t=>{let connected=false,now=new Date('2026-09-25T12:00:00Z');try{
 await db.$connect();connected=true;const migrated=spawnSync(process.execPath,[require.resolve('prisma/build/index.js'),'migrate','deploy','--schema','packages/database/prisma/schema.prisma'],{env:{...process.env,DATABASE_URL:url.toString()},encoding:'utf8'});assert.equal(migrated.status,0,'Disposable-schema migration must succeed.');await db.guild.create({data:{id:'party',name:'Test Chairs'}});await seedPartyContent(db);
 const repo=new PrismaPartyRepository(db,()=>now,()=>0),c=(requestKey,userId='host',channelId='games')=>({guildId:'party',channelId,userId,requestKey}),tick=ms=>{now=new Date(now.getTime()+ms);},wyr=new WyrService(new PrismaWyrPromptRepository(db,()=>0),new PrismaWyrSessionRepository(db),{now:()=>now},{next:()=>randomUUID()});let wwyd,finish,story,fmk;
 await t.test('authored seed covers every bank and never reenables dashboard-disabled content',async()=>{for(const[game,count]of [['truth',1500],['dare',1200],['wwyd',1500],['finishsentence',500],['wyr',2000]])assert.equal(await db.contentEntry.count({where:{game}}),count);await db.contentEntry.update({where:{id:'TRUTH-0001'},data:{enabled:false}});await seedPartyContent(db);assert.equal((await db.contentEntry.findUniqueOrThrow({where:{id:'TRUTH-0001'}})).enabled,false);});
 await t.test('concurrent starts share one public slot including existing WYR',async()=>{const results=await Promise.allSettled([repo.start(c('wwyd1'),{game:'wwyd'}),repo.start(c('wwyd2'),{game:'wwyd'})]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);wwyd=results.find(r=>r.status==='fulfilled').value.sessionId;await assert.rejects(()=>wyr.start({guildId:'party',channelId:'games',ownerUserId:'host',category:'Casual'}),{code:'P2002'});assert.equal(await db.scheduledJob.count({where:{executionKey:'party:publish:'+wwyd}}),1);});
 await t.test('server/channel binding, one host extension and anonymous editable vote survive concurrency',async()=>{await assert.rejects(()=>repo.vote(c('wrong-channel','a','other'),wwyd,'A'),{code:'PARTY_MISSING'});await assert.rejects(()=>repo.extend(c('not-host','a'),wwyd),{code:'HOST_ONLY'});const exts=await Promise.allSettled([repo.extend(c('ext1'),wwyd),repo.extend(c('ext2'),wwyd)]);assert.equal(exts.filter(r=>r.status==='fulfilled').length,1);await Promise.all([repo.vote(c('vote1','a'),wwyd,'A'),repo.vote(c('vote2','b'),wwyd,'B')]);await repo.vote(c('revote','a'),wwyd,'B');const publicView=await repo.publicView(wwyd);assert.equal(publicView.result,undefined);assert.equal('votes' in publicView,false);assert.equal(await db.vote.count({where:{sessionId:wwyd}}),2);tick(90000);await assert.rejects(()=>repo.vote(c('late','c'),wwyd,'A'),{code:'PARTY_EXPIRED'});await Promise.all([repo.advance('party',wwyd,0),new PrismaPartyRepository(db,()=>now).advance('party',wwyd,0)]);assert.equal((await repo.publicView(wwyd)).result.totals.B,2);});
 await t.test('finish submissions are private, replace one member entry, then freeze at deadline',async()=>{finish=(await repo.start(c('finish'),{game:'finishsentence',mode:'custom',customPrompt:'The lounge needs ____.'})).sessionId;await Promise.all([repo.submit(c('a1','a'),finish,'A','Coffee'),repo.submit(c('b1','b'),finish,'B','Chairs')]);await repo.submit(c('a2','a'),finish,'A','More coffee');const view=await repo.publicView(finish);assert.equal(view.submissionCount,2);assert.deepEqual(view.submissions,{});assert.deepEqual(view.options,[]);tick(60000);await assert.rejects(()=>repo.submit(c('late-submit','a'),finish,'A','Late'),{code:'PARTY_EXPIRED'});await repo.advance('party',finish,0);assert.equal((await repo.publicView(finish)).phase,'vote');assert.equal((await repo.publicView(finish)).expiresAt.getTime(),now.getTime()+30000);assert.equal((await repo.publicView(finish)).options.find(o=>o.id==='a').text,'More coffee');});
 await t.test('creative self-vote rejects; ties open persisted 30s runoff with old ballots intact',async()=>{await assert.rejects(()=>repo.vote(c('self','a'),finish,'a'),{code:'SELF_VOTE'});await repo.vote(c('fv1','v1'),finish,'a');await repo.vote(c('fv2','v2'),finish,'b');tick(60000);await repo.advance('party',finish,1);const runoff=await new PrismaPartyRepository(db,()=>now).publicView(finish);assert.equal(runoff.phase,'runoff');assert.equal(runoff.expiresAt.getTime(),now.getTime()+30000);assert.equal(runoff.result,undefined);assert.equal(await db.vote.count({where:{sessionId:finish,questionKey:'round:1'}}),2);});
 await t.test('second tie deterministically resolves once, increments specific and aggregate wins without money',async()=>{await repo.vote(c('rv1','v1'),finish,'a');await repo.vote(c('rv2','v2'),finish,'b');tick(30000);await Promise.all(Array.from({length:3},()=>repo.advance('party',finish,2)));const result=(await repo.publicView(finish)).result;assert.ok(['a','b'].includes(result.winnerId));assert.equal(result.randomResolution,true);assert.match(result.label,/random selection/);assert.equal((await db.memberGameStats.findUniqueOrThrow({where:{guildId_userId_gameKey:{guildId:'party',userId:result.winnerId,gameKey:'finishsentence'}}})).wins,1);assert.equal((await db.memberGameStats.findUniqueOrThrow({where:{guildId_userId_gameKey:{guildId:'party',userId:result.winnerId,gameKey:'party_games'}}})).wins,1);assert.equal(await db.economyTransaction.count(),0);assert.equal(await db.vote.count({where:{sessionId:finish}}),4);});
 await t.test('custom replay requires new prompt and old round stays intact',async()=>{await assert.rejects(()=>repo.start(c('bad-replay'),{game:'finishsentence',sourceId:finish,mode:'custom'}),{code:'PARTY_TEXT'});const next=(await repo.start(c('custom-replay'),{game:'finishsentence',sourceId:finish,mode:'custom',customPrompt:'A new prompt ____.'})).sessionId;assert.notEqual(next,finish);assert.equal((await repo.publicView(next)).prompt,'A new prompt ____.');tick(60000);await repo.advance('party',next,0);assert.equal((await repo.publicView(next)).state,'CLOSED');assert.equal((await repo.publicView(finish)).state,'CLOSED');});
 await t.test('Random prompt choice persists its source; an empty runoff resolves the existing positive-vote tie',async()=>{const id=(await repo.start(c('random-finish'),{game:'finishsentence'})).sessionId;await repo.choosePrompt(c('random-choice'),id,'random');assert.ok((await repo.get(id)).data.promptId);await repo.submit(c('random-a','ra'),id,'A','One');await repo.submit(c('random-b','rb'),id,'B','Two');tick(60000);await repo.advance('party',id,0);await repo.vote(c('random-v1','v1'),id,'ra');await repo.vote(c('random-v2','v2'),id,'rb');tick(60000);await repo.advance('party',id,1);tick(30000);await repo.advance('party',id,2);const v=await repo.publicView(id);assert.equal(v.result.total,0);assert.equal(v.result.randomResolution,true);assert.ok(['ra','rb'].includes(v.result.winnerId));assert.match(v.result.label,/no votes/);});
 await t.test('one word story serializes turns and opens exact60s member vote at target',async()=>{story=(await repo.start(c('story'),{game:'onewordstory',length:10})).sessionId;await repo.addWord(c('word0','a'),story,'A','Once');await assert.rejects(()=>repo.addWord(c('self-follow','a'),story,'A','again'),{code:'STORY_TURN'});await assert.rejects(()=>repo.addWord(c('two-words','b'),story,'B','two words'),{code:'ONE_WORD'});for(let n=1;n<10;n++)await repo.addWord(c('word'+n,n%2?'b':'a'),story,n%2?'B':'A','word'+n);const v=await new PrismaPartyRepository(db,()=>now).publicView(story);assert.equal(v.words.length,10);assert.equal(v.phase,'vote');assert.equal(v.expiresAt.getTime(),now.getTime()+60000);await assert.rejects(()=>repo.addWord(c('extra','c'),story,'C','extra'),{code:'PARTY_PHASE'});await repo.vote(c('story-vote','audience'),story,'a');tick(60000);await repo.advance('party',story,1);assert.equal((await repo.publicView(story)).result.winnerId,'a');});
 await t.test('Truth or Dare targets immediately without acceptance, named answer and fresh same-target replay',async()=>{const first=(await repo.start(c('truth'),{game:'truthordare',target:{userId:'target',name:'Target'}})).sessionId;await assert.rejects(()=>repo.choosePrompt(c('host-pick'),first,'truth'),{code:'TARGET_ONLY'});await repo.choosePrompt(c('target-pick','target'),first,'truth');const prompt=(await repo.get(first)).data.promptId;await repo.answer(c('answer','target'),first,'My named response.');assert.equal((await repo.publicView(first)).answer,'My named response.');const replay=(await repo.start(c('truth-replay'),{game:'truthordare',sourceId:first,target:{userId:'target',name:'Target'}})).sessionId;await repo.choosePrompt(c('repick','target'),replay,'truth');assert.notEqual((await repo.get(replay)).data.promptId,prompt);await repo.answer(c('skip','target'),replay,'',true);assert.equal((await repo.publicView(replay)).skipped,true);});
 await t.test('WYR, WWYD, Truth and Dare select a fresh random enabled category prompt in public and private sessions',async()=>{
  const high=new PrismaPartyRepository(db,()=>now,length=>length-1),highWyr=new WyrService(new PrismaWyrPromptRepository(db,()=>0.999999),new PrismaWyrSessionRepository(db),{now:()=>now},{next:()=>randomUUID()}),category='Casual';
  const eligible=async game=>db.contentEntry.findMany({where:{game,category,enabled:true},orderBy:{id:'asc'},select:{id:true}});
  for(const game of ['wyr','wwyd','truth','dare']){const rows=await eligible(game);assert.ok(rows.length>2);assert.notEqual(rows.at(-1).id,rows[0].id);}
  const disabledTruth=(await eligible('truth')).at(-1).id;await db.contentEntry.update({where:{id:disabledTruth},data:{enabled:false}});
  const disabledWyr=(await eligible('wyr')).at(-1).id;await db.contentEntry.update({where:{id:disabledWyr},data:{enabled:false}});
  const wwydPublic=await high.start(c('random-wwyd-public','host','random-wwyd-public'),{game:'wwyd',category,visibility:'public'}),publicId=(await high.get(wwydPublic.sessionId)).data.promptId;
  const wwydPrivate=await high.start(c('random-wwyd-private','host','random-wwyd-private'),{game:'wwyd',category,visibility:'private'}),privateId=(await high.get(wwydPrivate.sessionId)).data.promptId;
  assert.equal(publicId,(await eligible('wwyd')).at(-1).id);assert.notEqual(privateId,publicId);assert.equal((await high.publicView(wwydPrivate.sessionId)).visibility,'private');
  for(const mode of ['truth','dare']){const id=(await high.start(c('random-'+mode,'target','random-'+mode),{game:'truthordare',category,visibility:'private',target:{userId:'target',name:'Target'}})).sessionId;await high.choosePrompt(c('random-pick-'+mode,'target','random-'+mode),id,mode);const selected=(await high.get(id)).data.promptId;assert.equal(selected,(await eligible(mode)).at(-1).id);assert.notEqual(selected,(await eligible(mode))[0].id);if(mode==='truth')assert.notEqual(selected,disabledTruth);}
  const wyrPublic=await highWyr.start({guildId:'party',channelId:'random-wyr-public',ownerUserId:'host',category,visibility:'public'}),wyrPrivate=await highWyr.start({guildId:'party',channelId:'random-wyr-private',ownerUserId:'host',category,visibility:'private',enforceSinglePublicRound:false});
  assert.equal(wyrPublic.data.promptId,(await eligible('wyr')).at(-1).id);assert.notEqual(wyrPublic.data.promptId,disabledWyr);assert.notEqual(wyrPrivate.data.promptId,wyrPublic.data.promptId);assert.equal(wyrPrivate.data.visibility,'private');
 });
 await t.test('recent-use protection excludes the prior 100 where possible and safely falls back when exhausted',async()=>{
  const high=new PrismaPartyRepository(db,()=>now,length=>length-1),category='Friends',rows=await db.contentEntry.findMany({where:{game:'wwyd',category,enabled:true},orderBy:{id:'asc'},select:{id:true}});assert.ok(rows.length>101);
  await db.contentUseHistory.createMany({data:rows.slice(-100).map((row,index)=>({guildId:'party',game:'wwyd',category,contentId:row.id,usedAt:new Date(now.getTime()+index)}))});
  const protectedId=(await high.get((await high.start(c('recent-wwyd','host','recent-wwyd'),{game:'wwyd',category,visibility:'private'})).sessionId)).data.promptId;assert.ok(!rows.slice(-100).some(row=>row.id===protectedId));
  const wyrRows=await db.contentEntry.findMany({where:{game:'wyr',category,enabled:true},orderBy:{id:'asc'},select:{id:true}}),highWyr=new WyrService(new PrismaWyrPromptRepository(db,()=>0.999999),new PrismaWyrSessionRepository(db),{now:()=>now},{next:()=>randomUUID()});assert.ok(wyrRows.length>101);await db.contentUseHistory.createMany({data:wyrRows.slice(-100).map((row,index)=>({guildId:'party',game:'wyr',category,contentId:row.id,usedAt:new Date(now.getTime()+5_000+index)}))});
  const wyrProtected=await highWyr.start({guildId:'party',channelId:'recent-wyr',ownerUserId:'host',category,visibility:'private',enforceSinglePublicRound:false});assert.ok(!wyrRows.slice(-100).some(row=>row.id===wyrProtected.data.promptId));
  const dareRows=await db.contentEntry.findMany({where:{game:'dare',category,enabled:true},orderBy:{id:'asc'},select:{id:true}});await db.contentUseHistory.createMany({data:dareRows.map((row,index)=>({guildId:'party',game:'dare',category,contentId:row.id,usedAt:new Date(now.getTime()+10_000+index)}))});
  const fallback=(await high.start(c('exhaust-dare','target','exhaust-dare'),{game:'truthordare',category,visibility:'private',target:{userId:'target',name:'Target'}})).sessionId;await high.choosePrompt(c('exhaust-dare-pick','target','exhaust-dare'),fallback,'dare');assert.equal((await high.get(fallback)).data.promptId,dareRows.at(-1).id);
 });
 const members=Array.from({length:6},(_,n)=>({userId:'subject'+n,name:'Subject '+n}));
 await t.test('FMK random trio and assignments stay private until chooser submits',async()=>{fmk=(await repo.start(c('fmk'),{game:'fmk',members})).sessionId;const pub=await repo.publicView(fmk);assert.equal('trio' in pub,false);assert.equal('assignments' in pub,false);await assert.rejects(()=>repo.privateFmk(c('intruder','a'),fmk),{code:'OWNER_ONLY'});await repo.draftFmk(c('fuck'),fmk,'fuck','subject0');await repo.draftFmk(c('marry'),fmk,'marry','subject1');assert.equal('assignments' in await repo.publicView(fmk),false);await assert.rejects(()=>repo.submitFmk(c('stale-subject'),fmk,['subject0','subject1']),{code:'FMK_INELIGIBLE'});assert.equal(await db.memberGameStats.count({where:{gameKey:'fmk_subject'}}),0);});
 await t.test('concurrent FMK submit updates subject counters and chooser plays once',async()=>{await Promise.all([repo.submitFmk(c('fmk-submit'),fmk,members.map(m=>m.userId)),repo.submitFmk(c('fmk-submit'),fmk,members.map(m=>m.userId))]);const v=await repo.publicView(fmk);assert.equal(v.expiresAt.getTime(),now.getTime()+60000);assert.deepEqual(v.assignments,{fuck:'subject0',marry:'subject1',kill:'subject2'});assert.equal(v.subjectCounters.subject0.fucked,1);assert.equal((await repo.privateFmk(c('private-counters'),fmk)).subjectCounters.subject0.fucked,1);assert.equal((await db.memberGameStats.findUniqueOrThrow({where:{guildId_userId_gameKey:{guildId:'party',userId:'host',gameKey:'fmk'}}})).plays,1);assert.equal(await db.scheduledJob.count({where:{executionKey:'party:publish:'+fmk}}),1);});
 await t.test('FMK local vote excludes chooser, is editable, and replay preserves old vote while drawing fresh trio',async()=>{await assert.rejects(()=>repo.vote(c('chooser-vote'),fmk,'agree'),{code:'FMK_CHOOSER_VOTE'});await repo.vote(c('agree','a'),fmk,'disagree');await repo.vote(c('edit-agree','a'),fmk,'agree');await repo.vote(c('disagree','b'),fmk,'disagree');const replay=(await repo.start(c('fmk-replay'),{game:'fmk',sourceId:fmk,members})).sessionId;assert.deepEqual((await repo.privateFmk(c('view-replay'),replay)).trio.map(m=>m.userId),['subject3','subject4','subject5']);assert.equal((await repo.publicView(fmk)).state,'OPEN');assert.equal(await db.vote.count({where:{sessionId:fmk}}),2);await repo.extend(c('fmk-ext'),fmk);tick(90000);await Promise.all([repo.advance('party',fmk,0),repo.advance('party',fmk,0)]);const v=await repo.publicView(fmk);assert.equal(v.result.label,'Split Decision');assert.equal(v.result.winnerId,undefined);assert.deepEqual(v.result.percentages,{agree:50,disagree:50});const stats=await db.memberGameStats.findUniqueOrThrow({where:{guildId_userId_gameKey:{guildId:'party',userId:'host',gameKey:'fmk'}}});assert.equal(stats.wins,0);assert.equal(stats.metadata.averageAgreement,50);assert.equal((await repo.publicView(fmk)).subjectCounters.subject0.fucked,1);});
 await t.test('WYR uses same public slot, durable close timer, host authority, shared ballots and fresh prompt replay',async()=>{const w=await wyr.start({guildId:'party',channelId:'games',ownerUserId:'host',category:'Casual',messageId:'original-wyr-reply'});assert.equal((await wyr.get(w.id)).messageId,'original-wyr-reply');assert.equal(await db.scheduledJob.count({where:{executionKey:'wyr:publish:'+w.id}}),1);await assert.rejects(()=>repo.start(c('blocked-party'),{game:'wwyd'}),{code:'PARTY_ACTIVE'});await assert.rejects(()=>wyr.extend(w.id,'staff',true),{code:'NOT_ALLOWED'});await wyr.vote(w.id,'a','A');await wyr.vote(w.id,'a','B');assert.equal((await wyr.get(w.id)).votes.length,1);await wyr.extend(w.id,'host');assert.equal((await db.scheduledJob.findUniqueOrThrow({where:{executionKey:'wyr:close:'+w.id}})).dueAt.getTime(),now.getTime()+60000);await assert.rejects(()=>wyr.close(w.id),{code:'NOT_DUE'});tick(90000);await wyr.close(w.id);const replay=await wyr.replay(w.id,'a');assert.notEqual(replay.data.promptId,w.data.promptId);assert.equal((await wyr.get(w.id)).state,'CLOSED');});
 }finally{assert.match(schema,/^aj_party_test_[0-9a-f]{32}$/);try{if(connected)await db.$executeRawUnsafe('DROP SCHEMA IF EXISTS "'+schema+'" CASCADE');}finally{await db.$disconnect();}}});
