import {readFileSync} from 'node:fs';
import {parseEnv} from 'node:util';
import {spawnSync} from 'node:child_process';
import {createRequire} from 'node:module';
import {randomUUID} from 'node:crypto';
import test from 'node:test';
import assert from 'node:assert/strict';
import {PrismaClient} from '@prisma/client';
import {PrismaPvpRepository} from '../../.test-build/packages/features-pvp/src/prisma-repository.js';
import {autoFleet} from '../../.test-build/packages/features-pvp/src/domain.js';
const require=createRequire(import.meta.url),schema='aj_pvp_test_'+randomUUID().replaceAll('-','');
const value=parseEnv(readFileSync(new URL('../../.env.test.local',import.meta.url),'utf8')).TEST_DATABASE_URL;if(!value)throw Error('Dedicated test database setting missing.');
const url=new URL(value);url.searchParams.set('schema',schema);const db=new PrismaClient({datasourceUrl:url.toString()});
test('Phase15 PvP PostgreSQL atomic funding, moves, privacy and restart recovery',async t=>{let connected=false,now=new Date('2026-09-25T12:00:00Z');try{
 try{await db.$connect();}catch{throw Error('Dedicated PostgreSQL test connection unavailable.');}connected=true;const migration=spawnSync(process.execPath,[require.resolve('prisma/build/index.js'),'migrate','deploy','--schema','packages/database/prisma/schema.prisma'],{env:{...process.env,DATABASE_URL:url.toString()},encoding:'utf8'});assert.equal(migration.status,0,'Test schema migration must succeed.');await db.guild.create({data:{id:'pvp',name:'Test Chairs'}});
 for(const userId of ['a','b','c','poor']){await db.member.create({data:{guildId:'pvp',userId}});await db.economyAccount.create({data:{guildId:'pvp',userId,wallet:userId==='poor'?1n:40n,bank:userId==='poor'?0n:100n}});}
 let repo=new PrismaPvpRepository(db,()=>now,()=>0),sequence=0;const c=(userId,requestKey='request'+(++sequence),channelId='games')=>({guildId:'pvp',channelId,userId,requestKey}),policy={enabled:true,minWager:1n,maxWager:1000n},players=(a='a',b='b')=>[{userId:a,name:a},{userId:b,name:b}],challenge=async(game='tictactoe',stake=0n,a='a',b='b')=>(await repo.challenge(c(a),game,players(a,b),stake,policy)).sessionId,act=async(id,userId,action,requestKey)=>{const s=await repo.get(id);return repo.act(c(userId,requestKey),id,s.version,action,policy);};let id;
 await t.test('concurrent challenges share one member lock across all skill-game types',async()=>{const results=await Promise.allSettled([repo.challenge(c('a','start1'),'tictactoe',players(),0n,policy),repo.challenge(c('c','start2'),'battleship',players('c','b'),0n,policy)]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);const first=results[0].status==='fulfilled';id=results[first?0:1].value.sessionId;assert.equal((await repo.challenge(c(first?'a':'c',first?'start1':'start2'),first?'tictactoe':'battleship',players(first?'a':'c'),0n,policy)).sessionId,id);await act(id,first?'a':'c',{kind:'cancel'});});
 await t.test('two-minute expiry is restart-safe and never reserves a challenge stake',async()=>{id=await challenge('tictactoe',50n);assert.equal(await db.escrow.count({where:{referenceId:id}}),0);now=new Date(now.getTime()+120000);await assert.rejects(()=>repo.act(c('b'),id,0,{kind:'accept'},policy),{code:'PVP_EXPIRED'});repo=new PrismaPvpRepository(db,()=>now,()=>0);await Promise.all([repo.expire('pvp',id,0),repo.expire('pvp',id,0)]);assert.equal((await repo.get(id)).data.result,'expired');});
 await t.test('acceptance is target-only; insufficient second balance rolls back both reservations',async()=>{id=await challenge('tictactoe',50n,'a','poor');await assert.rejects(()=>repo.act(c('a'),id,0,{kind:'accept'},policy),{code:'PVP_ACCEPT'});await assert.rejects(()=>repo.act(c('poor'),id,0,{kind:'accept'},policy),{code:'INSUFFICIENT_FUNDS'});assert.equal(await db.escrow.count({where:{referenceId:id}}),0);assert.equal((await db.economyAccount.findUniqueOrThrow({where:{guildId_userId:{guildId:'pvp',userId:'a'}}})).wallet,40n);await act(id,'a',{kind:'cancel'});});
 await t.test('accept/cancel race cannot leave one funded side or an accepted cancelled match',async()=>{id=await challenge('tictactoe',50n);const results=await Promise.allSettled([repo.act(c('b','race-accept'),id,0,{kind:'accept'},policy),repo.act(c('a','race-cancel'),id,0,{kind:'cancel'},policy)]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);const saved=await repo.get(id);assert.equal(await db.escrow.count({where:{referenceId:id}}),saved.state==='LOCKED'?2:0);if(saved.state==='LOCKED')await act(id,'a',{kind:'forfeit',confirmed:true});});
 await t.test('matching wagers accept exactly once; wrong member/channel/version cannot move',async()=>{id=await challenge('tictactoe',10n);await Promise.all([repo.act(c('b','accept'),id,0,{kind:'accept'},policy),repo.act(c('b','accept'),id,0,{kind:'accept'},policy)]);assert.equal(await db.escrow.count({where:{referenceId:id}}),2);await assert.rejects(()=>repo.act(c('outsider'),id,1,{kind:'move',choice:0},policy),{code:'PVP_PLAYER'});await assert.rejects(()=>repo.act(c('a','wrong','other'),id,1,{kind:'move',choice:0},policy),{code:'PVP_MISSING'});await assert.rejects(()=>repo.act(c('a'),id,0,{kind:'move',choice:0},policy),{code:'PVP_CHANGED'});const moves=await Promise.allSettled([repo.act(c('a','move1'),id,1,{kind:'move',choice:0},policy),repo.act(c('a','move2'),id,1,{kind:'move',choice:1},policy)]);assert.equal(moves.filter(r=>r.status==='fulfilled').length,1);const winner=moves[0].status==='fulfilled'?0:1;await repo.act(c('a','move'+(winner+1)),id,1,{kind:'move',choice:winner},policy);await assert.rejects(()=>repo.act(c('a','move'+(winner+1)),id,1,{kind:'move',choice:8},policy),{code:'REPLAY_MISMATCH'});await assert.rejects(()=>act(id,'b',{kind:'forfeit',confirmed:false}),{code:'PVP_CONFIRM'});await act(id,'b',{kind:'forfeit',confirmed:true});const done=await repo.get(id);assert.equal(done.data.winnerId,'a');assert.equal(done.data.paid,'20');assert.equal(await db.economyTransaction.count({where:{idempotencyKey:'pvp:win:'+id+':payout'}}),1);});
 await t.test('draw refunds exact wallet/bank sources and concurrent final moves settle once',async()=>{const before=await db.economyAccount.findMany({where:{guildId:'pvp',userId:{in:['a','b']}},orderBy:{userId:'asc'}});id=await challenge('tictactoe',50n);await act(id,'b',{kind:'accept'});for(const cell of [0,1,2,4,3,5,7,6]){const s=await repo.get(id);await act(id,s.data.players[s.data.board.turn].userId,{kind:'move',choice:cell});}const v=(await repo.get(id)).version;const final=await Promise.allSettled([repo.act(c('a','draw1'),id,v,{kind:'move',choice:8},policy),repo.act(c('a','draw2'),id,v,{kind:'move',choice:8},policy)]);assert.equal(final.filter(r=>r.status==='fulfilled').length,1);assert.equal((await repo.get(id)).data.result,'draw');const after=await db.economyAccount.findMany({where:{guildId:'pvp',userId:{in:['a','b']}},orderBy:{userId:'asc'}});assert.deepEqual(after.map(r=>[r.wallet,r.bank]),before.map(r=>[r.wallet,r.bank]));assert.equal(await db.escrow.count({where:{referenceId:id,state:'REFUNDED'}}),2);});
  await t.test('replay creates a fresh unfunded same-opponent challenge and preserves old result',async()=>{const old=await repo.get(id),result=await repo.replay(c('b','replay'),id,policy);assert.notEqual(result.sessionId,id);assert.deepEqual((await repo.get(id)).data,old.data);assert.equal((await repo.replay(c('b','replay'),id,policy)).sessionId,result.sessionId);const next=await repo.get(result.sessionId);assert.deepEqual(next.data.players.map(p=>p.userId),['b','a']);assert.equal(await db.escrow.count({where:{referenceId:next.id}}),0);assert.equal(next.data.wager,'50');await act(next.id,'b',{kind:'cancel'});});
 await t.test('current wager limits gate acceptance/replay but do not strand an accepted match',async()=>{id=await challenge('tictactoe',10n);const lower={...policy,maxWager:5n};await assert.rejects(()=>repo.act(c('b'),id,0,{kind:'accept'},lower),{code:'PVP_WAGER'});assert.equal(await db.escrow.count({where:{referenceId:id}}),0);await act(id,'b',{kind:'accept'});await repo.act(c('a'),id,1,{kind:'forfeit',confirmed:true},lower);await assert.rejects(()=>repo.replay(c('b'),id,lower),{code:'PVP_WAGER'});});
 await t.test('Battleship fleets remain private across reload, versioned placement and public projections',async()=>{id=await challenge('battleship');await act(id,'b',{kind:'accept'});await assert.rejects(()=>act(id,'b',{kind:'place'}),{code:'PVP_TURN'});await act(id,'a',{kind:'place',fleet:autoFleet(()=>0)});await act(id,'b',{kind:'place',fleet:autoFleet(n=>n-1)});repo=new PrismaPvpRepository(db,()=>now,()=>0);const a=await repo.privateView(c('a'),id),b=await repo.privateView(c('b'),id),publicState=await repo.publicView(id);assert.equal(a.fleet.flat().length,17);assert.notDeepEqual(a.fleet,b.fleet);assert.equal(publicState.fleet,undefined);assert.ok(!JSON.stringify(publicState).includes('fleet'));assert.ok(!JSON.stringify((await repo.get(id)).data).includes('fleet'));await assert.rejects(()=>repo.privateView(c('outsider'),id),{code:'PVP_PLAYER'});await act(id,'a',{kind:'move',choice:b.fleet[0][0]});assert.equal((await repo.privateView(c('a'),id)).ownShots[0].hit,true);assert.deepEqual((await repo.privateView(c('a'),id)).fleet,a.fleet);await act(id,'b',{kind:'forfeit',confirmed:true});});
 await t.test('restart consumes only the current timeout and concurrent workers pay full pot once',async()=>{id=await challenge('connectfour',10n);await act(id,'b',{kind:'accept'});await act(id,'a',{kind:'move',choice:0});const saved=await repo.get(id);now=new Date(now.getTime()+300000);repo=new PrismaPvpRepository(db,()=>now);await repo.expire('pvp',id,1);assert.equal((await repo.get(id)).state,'LOCKED');await assert.rejects(()=>repo.act(c('b'),id,saved.version,{kind:'move',choice:1},policy),{code:'PVP_EXPIRED'});await Promise.all([repo.expire('pvp',id,saved.version),repo.expire('pvp',id,saved.version)]);const done=await repo.get(id);assert.equal(done.data.result,'timeout');assert.equal(done.data.winnerId,'a');assert.equal(done.data.paid,'20');assert.equal(await db.economyTransaction.count({where:{idempotencyKey:'pvp:win:'+id+':payout'}}),1);const combined=await db.memberGameStats.findUniqueOrThrow({where:{guildId_userId_gameKey:{guildId:'pvp',userId:'a',gameKey:'skill_games'}}});assert.ok(combined.wins>=3);});
 }finally{if(connected)await db.$executeRawUnsafe(`DROP SCHEMA IF EXISTS "${schema}" CASCADE`);await db.$disconnect();}});
