import {readFileSync} from 'node:fs';import {parseEnv} from 'node:util';import {spawnSync} from 'node:child_process';import {createRequire} from 'node:module';import {randomUUID} from 'node:crypto';import test from 'node:test';import assert from 'node:assert/strict';import {PrismaClient} from '@prisma/client';
import {PrismaSpecialRepository} from '../../.test-build/packages/features-special/src/prisma-repository.js';
import {DeliveryEngine} from '../../.test-build/packages/core/src/delivery.js';
const require=createRequire(import.meta.url),schema='aj_special_test_'+randomUUID().replaceAll('-',''),value=parseEnv(readFileSync(new URL('../../.env.test.local',import.meta.url),'utf8')).TEST_DATABASE_URL;
if(!value)throw new Error('TEST_DATABASE_URL is required in ignored .env.test.local.');const url=new URL(value);url.searchParams.set('schema',schema);const db=new PrismaClient({datasourceUrl:url.toString()});
test('Phase 13 PostgreSQL Line and Special Command persistence',async t=>{
 let connected=false,now=new Date('2026-09-25T12:00:00Z'),id;
 try{await db.$connect();connected=true;const migrated=spawnSync(process.execPath,[require.resolve('prisma/build/index.js'),'migrate','deploy','--schema','packages/database/prisma/schema.prisma'],{env:{...process.env,DATABASE_URL:url.toString()},encoding:'utf8'});assert.equal(migrated.status,0,'Disposable test-schema migration must succeed.');await db.guild.create({data:{id:'special',name:'Test Chairs'}});
 const repo=new PrismaSpecialRepository(db,()=>now,()=>0),c=(requestKey,userId='host',channelId='main')=>({guildId:'special',channelId,userId,requestKey});
 await t.test('one Line per channel under concurrent start, idempotent host ready, coexists with Race',async()=>{
  await db.gameSession.create({data:{guildId:'special',channelId:'main',type:'race',state:'OPEN',data:{}}});
  const attempts=await Promise.allSettled([repo.start(c('start1'),'Host'),repo.start(c('start2'),'Host')]);assert.equal(attempts.filter(r=>r.status==='fulfilled').length,1);const winner=attempts.find(r=>r.status==='fulfilled').value;id=winner.sessionId;const key=attempts[0].status==='fulfilled'?'start1':'start2';assert.equal((await repo.start(c(key),'Host')).sessionId,id);const saved=await repo.get(id);assert.deepEqual(saved.data.members,[{userId:'host',name:'Host',status:'ready'}]);assert.equal(saved.expiresAt.getTime(),now.getTime()+60000);
  await assert.rejects(()=>db.gameSession.create({data:{guildId:'special',channelId:'main',type:'line',state:'OPEN',data:{}}}),{code:'P2002'});
 });
 await t.test('no participant cap; concurrent unique check-ins and changed status are persisted',async()=>{
  for(let batch=0;batch<5;batch++)await Promise.all(Array.from({length:4},(_,i)=>{const userId='member'+(batch*4+i);return repo.checkIn(c('join:'+userId,userId),id,userId,'ready');}));
  await Promise.all([repo.checkIn(c('waiting','member1'),id,'Member One','waiting'),repo.checkIn(c('waiting','member1'),id,'Member One','waiting')]);const saved=await repo.get(id);assert.equal(saved.data.members.length,21);assert.equal(saved.data.members.filter(m=>m.userId==='member1').length,1);assert.equal(saved.data.members.find(m=>m.userId==='member1').status,'waiting');assert.equal(await db.gameParticipant.count({where:{sessionId:id}}),21);
 });
 await t.test('host-only extension used exactly once concurrently, never beyond90s',async()=>{await assert.rejects(()=>repo.extend(c('foreign','member1'),id),{code:'HOST_ONLY'});const attempts=await Promise.allSettled([repo.extend(c('ext1'),id),repo.extend(c('ext2'),id)]);assert.equal(attempts.filter(r=>r.status==='fulfilled').length,1);assert.equal((await repo.get(id)).expiresAt.getTime(),now.getTime()+90000);assert.equal((await db.scheduledJob.findUniqueOrThrow({where:{executionKey:'line:lock:'+id}})).dueAt.getTime(),now.getTime()+90000);});
 await t.test('late check-ins reject before scheduler runs; restart locks without deleting ready/waiting',async()=>{const before=(await repo.get(id)).data.members;now=new Date(now.getTime()+90000);assert.equal((await repo.publicView(id)).state,'LOCKED');await assert.rejects(()=>repo.checkIn(c('late','late'),id,'Late','ready'),{code:'LINE_LOCKED'});await Promise.all([repo.lock('special',id),new PrismaSpecialRepository(db,()=>now).lock('special',id)]);assert.equal((await repo.get(id)).state,'LOCKED');assert.deepEqual((await repo.get(id)).data.members,before);await assert.rejects(()=>repo.checkIn(c('change-late','member1'),id,'Member','ready'),{code:'LINE_LOCKED'});});
 await t.test('only host can start or cancel locked Line; authored shame survives restart',async()=>{await assert.rejects(()=>repo.countdown(c('foreign-start','member1'),id,true),{code:'HOST_ONLY'});await assert.rejects(()=>repo.cancel(c('foreign-cancel','member1'),id),{code:'HOST_ONLY'});const preview=await repo.previewCountdown(c('preview'),id,true);const attempts=await Promise.allSettled([repo.countdown(c('go1'),id,true,preview),repo.countdown(c('go2'),id,true,preview)]);assert.equal(attempts.filter(r=>r.status==='fulfilled').length,1);const saved=await repo.get(id);assert.equal(saved.state,'SETTLING');assert.equal(saved.data.shame.id,'LINE-SHAME-001');assert.match(saved.data.shame.text,/Member One/);assert.equal(saved.expiresAt.getTime(),now.getTime()+5800);const restarted=new PrismaSpecialRepository(db,()=>now);assert.deepEqual((await restarted.get(id)).data,saved.data);await assert.rejects(()=>repo.cancel(c('late-cancel'),id),{code:'LINE_STARTED'});await assert.rejects(()=>repo.start(c('active-countdown'),'Host'),{code:'LINE_ACTIVE'});});
 await t.test('authoritative countdown resumes exact phase and completes once after powder',async()=>{for(const[advance,number]of [[0,5],[1000,4],[1000,3],[1000,2],[1000,1]]){now=new Date(now.getTime()+advance);assert.equal((await new PrismaSpecialRepository(db,()=>now).publicView(id)).frame.number,number);}now=new Date(now.getTime()+1000);assert.equal((await repo.publicView(id)).frame.phase,'burst');await assert.rejects(()=>repo.complete('special',id),{code:'NOT_DUE'});now=new Date(now.getTime()+800);await Promise.all(Array.from({length:4},()=>repo.complete('special',id)));await new PrismaSpecialRepository(db,()=>now).complete('special',id);assert.equal((await repo.get(id)).state,'CLOSED');assert.equal(await db.operationReceipt.count({where:{guildId:'special',key:'line:complete:'+id}}),1);});
 await t.test('host can cancel locked Line and start a new Line, no replay interaction',async()=>{const next=(await repo.start(c('second'),'Host')).sessionId;now=new Date(now.getTime()+60000);await repo.lock('special',next);await Promise.all([repo.cancel(c('cancel1'),next),repo.cancel(c('cancel2'),next)]);assert.equal((await repo.get(next)).state,'CANCELLED');assert.equal((await repo.get(next)).data.members.length,1);});
 await t.test('pre-render snapshot rejects changed check-ins without starting a timer; early start works',async()=>{const next=(await repo.start(c('third'),'Host')).sessionId,preview=await repo.previewCountdown(c('preview3'),next,false);await repo.checkIn(c('new-member','new'),next,'New','waiting');await assert.rejects(()=>repo.countdown(c('stale-start'),next,false,preview),{code:'LINE_PREVIEW_CHANGED'});assert.equal((await repo.get(next)).state,'OPEN');assert.equal(await db.scheduledJob.count({where:{executionKey:'line:complete:'+next}}),0);await repo.countdown(c('early'),next,false,await repo.previewCountdown(c('preview4'),next,false));assert.equal((await repo.get(next)).state,'SETTLING');assert.equal((await repo.get(next)).data.shame,undefined);});
 await t.test('Line publication intent is atomic with session and shared delivery reconciles uncertain send',async()=>{const result=await repo.start(c('publication','host','other'),'Host',{content:'The Chairs are gathering.',notificationRoleId:null});assert.ok(result.jobId);const repeated=await repo.start(c('publication','host','other'),'Host',{content:'Different random selection',notificationRoleId:null});assert.equal(repeated.jobId,result.jobId);assert.equal((await repo.callout(result.jobId)).payload.content,'The Chairs are gathering.');let sends=0;const transport={send:async()=>{sends++;throw new Error('Uncertain network');},find:async()=> 'discord-message'};await assert.rejects(()=>new DeliveryEngine(repo.delivery(result.jobId)).deliver('marker',transport));assert.equal(await new DeliveryEngine(new PrismaSpecialRepository(db,()=>now).delivery(result.jobId)).deliver('marker',transport),'discord-message');assert.equal(sends,1);});
 await t.test('notification triggers have no cooldown, replay creates one durable job',async()=>{const first=await repo.queueCallout(c('vc1'),'Voice invitation.',null);const repeat=await repo.queueCallout(c('vc1'),'Another selected phrase.',null);const next=await repo.queueCallout(c('vc2'),'Voice invitation.',null);assert.equal(first.jobId,repeat.jobId);assert.notEqual(first.jobId,next.jobId);assert.equal((await repo.callout(first.jobId)).payload.content,'Voice invitation.');});
 }finally{assert.match(schema,/^aj_special_test_[0-9a-f]{32}$/);try{if(connected)await db.$executeRawUnsafe('DROP SCHEMA IF EXISTS "'+schema+'" CASCADE');}finally{await db.$disconnect();}}
});
