import {randomInt} from 'node:crypto';
import {DomainError} from '../../core/src/index.js';
export const CRIME_TIMING={robberCooldown:1800,victimProtection:3600,fightBack:60,reports:180,jail:86400,decay:3600} as const;
export function isCrimeBailRequest(commandName?:string,subcommand?:string,customId?:string){if(commandName==='crime'&&subcommand==='bail')return true;if(!customId)return false;const parts=customId.split(':');return parts[0]==='crime'&&((['bailpick','bailself'].includes(parts[1]??'')&&parts.length===3&&Boolean(parts[2]))||(parts[1]==='bailconfirm'&&parts.length===5&&parts.slice(2).every(Boolean)));}
export interface CrimePolicy {successBp:number;theftMinBp:number;theftMaxBp:number;fightBackBp:number;catchBaseBp:number;reportBp:number;catchCapBp:number;fightBackRiskBp:number;attemptHeat:number;successHeat:number;decayPerHour:number;bailBase:number;bailPerHeat:number;bailRandomMax:number;}
export const DEFAULT_CRIME_POLICY:CrimePolicy={successBp:4500,theftMinBp:1000,theftMaxBp:2500,fightBackBp:5000,catchBaseBp:1000,reportBp:1000,catchCapBp:8500,fightBackRiskBp:1500,attemptHeat:10,successHeat:10,decayPerHour:10,bailBase:100,bailPerHeat:2,bailRandomMax:100};
export type WantedLevel='CLEAN'|'SUSPICIOUS'|'WANTED'|'MOST_WANTED'|'PUBLIC_ENEMY';
export function validateCrimePolicy(p:CrimePolicy){for(const key of ['successBp','theftMinBp','theftMaxBp','fightBackBp','catchBaseBp','reportBp','catchCapBp','fightBackRiskBp'] as const)if(!Number.isInteger(p[key])||p[key]<0||p[key]>10000)throw new DomainError('CRIME_CONFIG','Crime probabilities must be whole basis points between 0 and 10000.');if(p.theftMinBp<1||p.theftMinBp>p.theftMaxBp||p.theftMaxBp>5000||p.catchBaseBp>p.catchCapBp)throw new DomainError('CRIME_CONFIG','Crime theft bounds or catch limits are invalid.');for(const key of ['attemptHeat','successHeat','decayPerHour'] as const)if(!Number.isInteger(p[key])||p[key]<1||p[key]>100)throw new DomainError('CRIME_CONFIG','Crime heat settings must be between 1 and 100.');for(const key of ['bailBase','bailPerHeat','bailRandomMax'] as const)if(!Number.isInteger(p[key])||p[key]<0||p[key]>1000000)throw new DomainError('CRIME_CONFIG','Crime bail settings are invalid.');return p;}
export function wantedLevel(heat:number):WantedLevel {return heat>=100?'PUBLIC_ENEMY':heat>=60?'MOST_WANTED':heat>=30?'WANTED':heat>=10?'SUSPICIOUS':'CLEAN';}
export function decayedHeat(heat:number,since:Date,now:Date,perHour=10){const steps=Math.max(0,Math.floor((now.getTime()-since.getTime())/(CRIME_TIMING.decay*1000)));return{heat:Math.max(0,heat-steps*perHour),at:new Date(since.getTime()+steps*CRIME_TIMING.decay*1000)};}
export function checkedRoll(max:number,rng:(max:number)=>number=randomInt){const value=rng(max);if(!Number.isInteger(value)||value<0||value>=max)throw new DomainError('CRIME_RANDOM','Crime outcome generation failed.');return value;}
export function theftAmount(wallet:bigint,available:bigint,bp:number){if(wallet<0n||available<0n||available>wallet||!Number.isInteger(bp)||bp<1||bp>5000)throw new DomainError('CRIME_AMOUNT','The theft amount is invalid.');const amount=wallet*BigInt(bp)/10000n;return amount>available?available:amount;}
export function catchRisk(p:CrimePolicy,heat:number,reports:number,foughtBack:boolean){return Math.min(p.catchCapBp,p.catchBaseBp+Math.min(100,Math.max(0,heat))*50+Math.max(0,reports)*p.reportBp+(foughtBack?p.fightBackRiskBp:0));}
export function bailAmount(heat:number,stolen:bigint,roll:number,p:CrimePolicy=DEFAULT_CRIME_POLICY){return BigInt(p.bailBase)+BigInt(Math.min(100,Math.max(0,heat))*p.bailPerHeat)+stolen+BigInt(roll%(p.bailRandomMax+1));}
