import {readFileSync} from 'node:fs';
import {wrapText} from '../../renderer/src/text-layout.js';
import type {CrimeView} from './prisma-repository.js';
const gold='#F2CF86',white='#EFF5F2',teal='#35D0BC',muted='#C3D4D4';
const esc=(s:string)=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
let room:string|undefined,chair:string|undefined;
const media=(file:string)=>'data:image/png;base64,'+readFileSync(new URL('../../../production/'+file,import.meta.url)).toString('base64');
const t=(x:number,y:number,s:string,size=27,color=white,heading=false)=>`<text x="${x}" y="${y}" text-anchor="middle" font-family="${heading?'Cinzel':'Poppins'}" font-size="${size}" font-weight="700" fill="${color}">${esc(s)}</text>`;
function block(s:string,x:number,y:number,w:number,size=26,color=white,heading=false){const lines=wrapText(s.replace(/\*\*/g,''),w,size),step=Math.ceil(size*1.5);return{svg:lines.map((l,n)=>t(x,y+n*step,l,size,color,heading)).join(''),height:lines.length*step};}
function panel(x:number,y:number,w:number,h:number,c=gold){return `<rect x="${x}" y="${y}" width="${w}" height="${h}" rx="20" fill="url(#glass)" stroke="${c}" stroke-width="2"/><path d="M${x+15} ${y+50}V${y+15}H${x+60}M${x+w-60} ${y+h-15}H${x+w-15}V${y+h-50}" fill="none" stroke="url(#brass)" stroke-width="3"/>`;}
const seat=(x:number,y:number,size:number)=>`<image href="${chair??=media('event_art/v3/race_chair_1.png')}" x="${x-size/2}" y="${y}" width="${size}" height="${size}"/>`;
function portrait(name:string,data:string|undefined,x:number,y:number,size:number,key:string){const safe=data&&/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/.test(data)&&data.length<=1_400_000;return `<defs><clipPath id="${key}"><rect x="${x-size/2+5}" y="${y+5}" width="${size-10}" height="${size-10}" rx="20"/></clipPath></defs><rect x="${x-size/2}" y="${y}" width="${size}" height="${size}" rx="22" fill="#102D38" stroke="url(#brass)" stroke-width="4"/>`+(safe?`<image href="${esc(data!)}" x="${x-size/2+5}" y="${y+5}" width="${size-10}" height="${size-10}" preserveAspectRatio="xMidYMid slice" clip-path="url(#${key})"/>`:seat(x,y+8,size-16));}
function header(title:string,subtitle:string){const h=block(title,600,105,1000,42,gold,true),s=block(subtitle,600,112+h.height,1050,23,muted);return{svg:t(600,45,'ANGRIER JORDAN · THE SHADOW LOUNGE',20,teal)+h.svg+s.svg,height:130+h.height+s.height};}
function frame(body:string,h:number){return `<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="${h+80}" viewBox="0 0 1200 ${h+80}"><defs><linearGradient id="glass" x2="0" y2="1"><stop stop-color="#193B45" stop-opacity=".96"/><stop offset="1" stop-color="#07121F" stop-opacity=".97"/></linearGradient><linearGradient id="brass"><stop stop-color="#856126"/><stop offset=".5" stop-color="#FFE4A2"/><stop offset="1" stop-color="#997632"/></linearGradient></defs><image href="${room??=media('event_art/v5/lounge-stage-runtime.png')}" width="1200" height="${h+80}" preserveAspectRatio="xMidYMid slice"/><rect width="1200" height="${h+80}" fill="#08111E" opacity=".53"/>${body}<path d="M60 ${h+15}H1140" stroke="url(#brass)" stroke-width="2"/>${t(600,h+52,'SIT. PLAY. BELONG.',20,gold)}<rect x="5" y="5" width="1190" height="${h+70}" rx="22" fill="none" stroke="${teal}" stroke-width="3"/><rect x="17" y="17" width="1166" height="${h+46}" rx="16" fill="none" stroke="url(#brass)" stroke-width="3"/></svg>`;}
export function renderCrimeNotice(input:{title:string;message:string;name?:string;avatar?:string;amount?:string}){const head=header(input.title,'CRIME · PRIVATE CONTROLS');let body=head.svg,y=head.height;
 if(input.name){const name=block(input.name,690,y+58,700,31,gold),h=Math.max(180,name.height+100);body+=panel(45,y,1110,h)+portrait(input.name,input.avatar,190,y+18,140,'subject')+name.svg+t(690,y+name.height+90,'MEMBER DETAILS',20,teal);y+=h+22;}
 if(input.amount){const a=block(input.amount+' Ottomans',600,y+62,1000,40,gold);body+=panel(45,y,1110,a.height+100,gold)+a.svg;y+=a.height+120;}
 const b=block(input.message,600,y+50,1000,27),h=Math.max(190,b.height+85);body+=panel(45,y,1110,h,teal)+b.svg;return frame(body,y+h+20);
}
export function renderCrimeWanted(input:{name:string;avatar?:string;level:string;heat:number;successfulRobs:number;failedRobs:number;decay:number}){
 const head=header('Wanted in the Lounge',input.level.replaceAll('_',' ')),color=input.heat>=60?'#ED8279':input.heat>=30?'#E8AE56':teal;let y=head.height,body=head.svg;
 const name=block(input.name,730,y+58,700,33,gold),hero=Math.max(275,name.height+200);body+=panel(45,y,1110,hero,color)+portrait(input.name,input.avatar,220,y+34,180,'wanted')+name.svg+t(730,y+name.height+107,input.heat+' / 100 HEAT',48,color)+`<rect x="420" y="${y+hero-55}" width="650" height="18" rx="9" fill="#06131F"/><rect x="420" y="${y+hero-55}" width="${650*Math.max(0,Math.min(100,input.heat))/100}" height="18" rx="9" fill="${color}"/>`;y+=hero+24;
 body+=panel(45,y,540,150,teal)+t(315,y+42,'SUCCESSFUL ROBBERIES',23,teal,true)+t(315,y+108,String(input.successfulRobs),46,gold)+panel(610,y,545,150,'#A88AEC')+t(882,y+42,'FAILED ATTEMPTS',23,'#B499E8',true)+t(882,y+108,String(input.failedRobs),46,gold);y+=174;
 const note=block('Heat decays '+input.decay+' per elapsed hour. Arrest resets Wanted to Clean. Robbery cooldown and victim protection remain separate.',600,y+42,1000,25,muted);body+=panel(45,y,1110,note.height+75)+note.svg;return frame(body,y+note.height+95);
}
export function renderCrimeIncident(v:CrimeView,robberAvatar?:string,victimAvatar?:string,now=new Date()){
 const released=v.caught&&v.jailActive===false,title=v.caught?(released?'Crime Sentence Closed':'Under Arrest'):!v.success?'Attempt Failed':v.returned?'Stolen Funds Returned':v.state==='OPEN'?'Robbery in the Lounge':'Incident Resolved',accent=v.caught?'#ED8279':v.returned?teal:gold,head=header(title,'WALLET ONLY · BANK PROTECTED');let y=head.height,body=head.svg;
 const people=[{role:'ROBBER',member:v.robber,avatar:robberAvatar},{role:'VICTIM',member:v.victim,avatar:victimAvatar}],names=people.map((p,n)=>block(p.member.name,322+n*556,y+238,465,31)),h=Math.max(290,...names.map(n=>n.height+265));
 people.forEach((p,n)=>body+=panel(45+n*556,y,530,h,n===0?accent:teal)+t(322+n*556,y+36,p.role,23,n===0?accent:teal,true)+portrait(p.member.name,p.avatar,322+n*556,y+57,140,'person'+n)+names[n]!.svg);y+=h+24;
 const amount=block(v.stolen+' Ottomans',600,y+69,1020,46,gold),status=v.returned?'RETURNED IN FULL':!v.success?'NO MONEY STOLEN':v.state==='OPEN'?'STOLEN PROCEEDS · TEMPORARILY HELD':'PROCEEDS RELEASED';body+=panel(45,y,1110,amount.height+115,accent)+amount.svg+t(600,y+amount.height+91,status,23,accent);y+=amount.height+139;
 const remaining=(until:string)=>Math.max(0,Math.ceil((new Date(until).getTime()-now.getTime())/1000)),open=v.state==='OPEN'&&v.success;
 const notes=v.caught?[released?'Crime sentence closed.':'Crime jail: 24 hours unless bailed.','Wanted reset: Clean. Bail: '+(v.bail??'0')+' Ottomans.','Paying bail never clears moderation Hotseat.']:open?['FIGHT BACK · Victim only · '+(v.fightBack?'Already used: '+v.fightBack:remaining(v.fightBackEndsAt)+' seconds remaining'),'911 · Other eligible witnesses · '+remaining(v.reportEndsAt)+' seconds remaining','Witness reports: '+v.reports+' · One report per witness','Successful Fight Back or arrest returns all stolen funds once.']:['Incident resolved · Witness reports: '+v.reports,'Fight Back: '+(v.fightBack??'Not used'),'30-minute robber cooldown · 60-minute victim protection'];
 const note=block(notes.join('\n'),600,y+45,1020,25,muted);body+=panel(45,y,1110,note.height+75,teal)+note.svg;return frame(body,y+note.height+95);
}
