import {shell,panel,ink} from '../../features-events/src/visual.js';
import {centeredHeading,centeredBlock,portrait} from '../../features-events/src/gate-b-visual.js';
import type {CrimeView} from './prisma-repository.js';
export const CRIME_RULES='Robbery risks only the victim’s Wallet; Bank is protected. Each robber waits 30 minutes between attempts, and every attempted victim receives 60 minutes of protection. The victim may Fight Back once within 60 seconds. Other eligible witnesses may report once each within 3 minutes; reports increase capped catch risk. Stolen proceeds appear in the robber’s Wallet but remain temporarily unavailable until restitution is resolved. Successful Fight Back or arrest returns all stolen funds once. Arrest resets Wanted and imposes 24 hours of crime jail. Self or another member may pay bail; bail never clears moderation Hotseat.';
export function crimeDescription(v:CrimeView){return v.caught&&v.jailActive===false?`${v.robber.name}'s crime sentence is closed. Any moderation Hotseat remains separate.`:v.caught?`${v.robber.name} arrested. ${v.returned?v.stolen+' stolen Ottomans returned.':'No stolen funds retained.'} Bail: ${v.bail} Ottomans. Crime jail: 24 hours unless bailed.`:!v.success?`${v.robber.name}'s robbery attempt against ${v.victim.name} failed.`:v.returned?`${v.victim.name} recovered all ${v.stolen} stolen Ottomans.`:`${v.robber.name} stole ${v.stolen} Wallet Ottomans from ${v.victim.name}.${v.state==='OPEN'?' Proceeds are held until the witness window closes.':''}`;}

export function renderCrime(v:CrimeView,avatarData?:string,victimAvatarData?:string){const released=v.jailActive===false,h=centeredHeading('CHAIRS · CRIME',v.caught?(released?'Crime Jail Closed':'Under Arrest'):v.success?'Robbery Incident':'Attempt Failed',v.caught?(released?'Crime sentence resolved':'Crime jail · 24 hours unless bailed'):'Wallet only · Bank remains protected');let body=h.svg,y=h.height;
 const section=(values:{value:string;size?:number;color?:string}[],portraits:{id:string;name:string;avatar?:string|undefined}[]=[])=>{const top=y;let content='';y+=24;for(const p of portraits){content+=portrait('crime-'+p.id,p.name,p.avatar??'',220,y,84);y+=107;const name=centeredBlock(p.name,y,{size:19,width:356,gap:14});content+=name.svg;y+=name.height;}for(const value of values){const b=centeredBlock(value.value,y,{size:value.size??16,color:value.color??ink.white,width:360,gap:10});content+=b.svg;y+=b.height;}y+=7;body+=panel(18,top,404,y-top,ink.gold)+content;y+=16;};
 if(v.caught){section([{value:released?'SENTENCE CLOSED':'MEMBER IN CUSTODY',size:12,color:ink.warm},{value:'Wanted reset: Clean',color:ink.teal},{value:'Crime sentence only',size:14},{value:'INCIDENT '+v.id.slice(0,8).toUpperCase(),size:11,color:ink.muted}],[{id:v.robber.userId,name:v.robber.name,avatar:avatarData}]);section([{value:released?'ORIGINAL BAIL':'BAIL',size:12,color:ink.warm},{value:(v.bail??'0')+' Ottomans',size:25},{value:v.returned?'Stolen funds returned in full':'No stolen funds retained',color:ink.teal},{value:'Paying bail does not clear moderation Hotseat.',size:14,color:ink.muted}]);}
 else{section([{value:'ROBBERY ATTEMPT',size:12,color:ink.warm}],[{id:v.robber.userId,name:v.robber.name,avatar:avatarData},{id:v.victim.userId,name:v.victim.name,avatar:victimAvatarData}]);section([{value:v.stolen+' Ottomans',size:25,color:ink.warm},{value:v.returned?'All stolen funds returned':v.success?'Restitution window':'No money was stolen',size:20,color:v.returned?ink.teal:ink.warm},{value:v.state==='OPEN'?'Fight Back: 60 seconds · Witnesses: 3 minutes':'Incident resolved',size:14,color:ink.muted},{value:'Witness reports: '+v.reports+(v.fightBack?' · Fight Back: '+v.fightBack:''),size:14,color:ink.muted},{value:'Bank protected · No extra Fight Back penalty',size:14},{value:v.success&&!v.returned&&v.state==='OPEN'?'Stolen proceeds are temporarily held.':'30-minute robber cooldown · 60-minute victim protection',size:13,color:ink.muted}]);}return shell(y+6,body);
}
