import {ActionRowBuilder,ButtonBuilder,ButtonStyle,EmbedBuilder,PermissionFlagsBits,type ButtonInteraction,type ChatInputCommandInteraction,type Client} from 'discord.js';
import {CHAIRMAN_CHANNEL_ID,ChairmateRepository, type LichessAdapter} from '../../../../packages/features-chairmate/src/index.js';
import {chessCardText} from '../../../../packages/features-chairmate/src/render.js';
type Interaction=ChatInputCommandInteraction|ButtonInteraction;
/** Discord boundary. Private URLs only ever occur in ephemeral Open My Game replies. */
export class DiscordChairmateCoordinator {
 private refreshing=false;
 constructor(private readonly repo:ChairmateRepository,private readonly lichess:LichessAdapter,private readonly eligible:(guildId:string,userId:string)=>Promise<boolean>){}
 private guard(i:Interaction){if(!i.guildId||!i.guild||i.channelId!==CHAIRMAN_CHANNEL_ID)throw new Error('Use /chess challenge only in ♟️-chairmate.');}
 private async member(i:Interaction,userId:string){const member=await i.guild!.members.fetch({user:userId,force:true});if(member.user.bot||member.isCommunicationDisabled()||!member.permissionsIn(i.channelId!).has(PermissionFlagsBits.ViewChannel|PermissionFlagsBits.SendMessages)||!await this.eligible(i.guildId!,userId))throw new Error('Both members must be eligible and able to use Chairmate.');return member;}
 async handle(i:Interaction){try{this.guard(i);if(i.isChatInputCommand()){
   await i.deferReply();const target=i.options.getUser('member',true),control=i.options.getString('time',true);if(target.id===i.user.id)throw new Error('Challenge another member.');const [challenger,opponent]=await Promise.all([this.member(i,i.user.id),this.member(i,target.id)]);const row=await this.repo.create({guildId:i.guildId!,channelId:i.channelId!,challengerUserId:i.user.id,opponentUserId:target.id,challengerName:challenger.displayName,opponentName:opponent.displayName,control,key:`discord:${i.id}`});const message=await i.editReply(this.payload(row));await this.repo.linkMessage(row.id,message.id);return;
  }
  const [,action,id]=i.customId.split(':');if(!id)throw new Error('Open the latest Chairmate card.');if(action==='open'){await i.deferReply({ephemeral:true});const row=await this.repo.get(id);if(row.status!=='ACTIVE')throw new Error('Your game is not ready yet.');const url=i.user.id===row.challengerUserId?(row.challengerColor==='white'?row.whiteUrl:row.blackUrl):i.user.id===row.opponentUserId?(row.opponentColor==='white'?row.whiteUrl:row.blackUrl):undefined;if(!url)throw new Error('Only the two named members can open this game.');await i.editReply({content:`Open your private Lichess board: ${url}`,allowedMentions:{parse:[]}});return;}
  if(action!=='accept'&&action!=='decline')throw new Error('Unknown Chairmate control.');await i.deferUpdate();const row=await this.repo.decide(id,i.user.id,action==='accept',this.lichess,i.id);await this.refresh(i.client,row.id);if(row.status==='CREATING')await i.followUp({ephemeral:true,content:'Your acceptance is saved. Creating the Lichess board now; the card will refresh automatically.'});
 }catch(error){const content=error instanceof Error?error.message:'Chairmate could not complete that action.';if(i.deferred||i.replied)await i.followUp({ephemeral:true,content}).catch(()=>undefined);else await i.reply({ephemeral:true,content}).catch(()=>undefined);}}
 private payload(row:Awaited<ReturnType<ChairmateRepository['get']>>){const open=row.status==='ACTIVE',pending=row.status==='PENDING';const status=pending?`Challenge pending · accept within <t:${Math.floor(row.expiresAt.getTime()/1000)}:R>.`:row.status==='ACTIVE'?'Game is live. Use Open My Game for your private board.':row.status==='DECLINED'?'Challenge declined.':row.status==='EXPIRED'?'Challenge expired.':row.status==='CREATING'?'Creating private Lichess boards…':row.status==='FINISHED'?'Match complete · the result card is posted below.':'Challenge cancelled.';const buttons=new ActionRowBuilder<ButtonBuilder>();if(pending)buttons.addComponents(new ButtonBuilder().setCustomId(`chess:accept:${row.id}`).setLabel('Accept').setStyle(ButtonStyle.Success),new ButtonBuilder().setCustomId(`chess:decline:${row.id}`).setLabel('Decline').setStyle(ButtonStyle.Danger));if(open)buttons.addComponents(new ButtonBuilder().setCustomId(`chess:open:${row.id}`).setLabel('Open My Game').setStyle(ButtonStyle.Primary));return {content:'',embeds:[new EmbedBuilder().setColor(0x16a085).setTitle('CHAIRMATE · LICHESS').setDescription(chessCardText({challenger:row.challengerName,opponent:row.opponentName,timeControl:row.timeControl,status,challengerColor:row.challengerColor??undefined,opponentColor:row.opponentColor??undefined}))],components:buttons.components.length?[buttons]:[],allowedMentions:{parse:[] as never[]}};}
 async refresh(client:Client,id:string){if(this.refreshing)return;this.refreshing=true;try{const row=await this.repo.get(id);if(!row.messageId)return;const channel=await client.channels.fetch(row.channelId);if(!channel?.isTextBased()||!('messages' in channel))return;const message=await channel.messages.fetch(row.messageId);if(message.author.id===client.user?.id)await message.edit(this.payload(row));}finally{this.refreshing=false;}}
 async sweep(client:Client){await this.repo.recover(this.lichess);for(const row of await this.repo.resultsToPost()){const channel=await client.channels.fetch(row.channelId);if(!channel?.isTextBased()||!('send' in channel))continue;await channel.send({embeds:[new EmbedBuilder().setColor(0xc9a227).setTitle('CHAIRMATE · RESULT').setDescription(chessCardText({challenger:row.challengerName,opponent:row.opponentName,timeControl:row.timeControl,status:'Final result',challengerColor:row.challengerColor??undefined,opponentColor:row.opponentColor??undefined,outcome:row.result??'Game complete.',replay:row.lichessGameUrl??undefined}))],allowedMentions:{parse:[]}});await this.repo.markResultPosted(row.id);await this.refresh(client,row.id);}}
}
