import {ActionRowBuilder,AttachmentBuilder,ButtonBuilder,ButtonStyle,EmbedBuilder,PermissionFlagsBits,type ButtonInteraction,type ChatInputCommandInteraction,type Client} from 'discord.js';
import {CHAIRMAN_CHANNEL_ID,ChairmateRepository, type LichessAdapter} from '../../../../packages/features-chairmate/src/index.js';
import {renderChairmateCard} from '../../../../packages/features-chairmate/src/render.js';
import {rasterizeSvg} from '../../../../packages/renderer/src/raster.js';
type Interaction=ChatInputCommandInteraction|ButtonInteraction;
/** Discord boundary. Private URLs only ever occur in ephemeral Open My Game replies. */
export class DiscordChairmateCoordinator {
 private refreshing=false;
 constructor(private readonly repo:ChairmateRepository,private readonly lichess:LichessAdapter,private readonly eligible:(guildId:string,userId:string)=>Promise<boolean>){}
 private guard(i:Interaction){if(!i.guildId||!i.guild||i.channelId!==CHAIRMAN_CHANNEL_ID)throw new Error('Use /chess challenge only in ♟️-chairmate.');}
 private async member(i:Interaction,userId:string){const member=await i.guild!.members.fetch({user:userId,force:true});if(member.user.bot||member.isCommunicationDisabled()||!member.permissionsIn(i.channelId!).has(PermissionFlagsBits.ViewChannel|PermissionFlagsBits.SendMessages)||!await this.eligible(i.guildId!,userId))throw new Error('Both members must be eligible and able to use Chairmate.');return member;}
 async handle(i:Interaction){try{this.guard(i);if(i.isChatInputCommand()){
   await i.deferReply();const target=i.options.getUser('member',true),control=i.options.getString('time',true);if(target.id===i.user.id)throw new Error('Challenge another member.');const [challenger,opponent]=await Promise.all([this.member(i,i.user.id),this.member(i,target.id)]);const row=await this.repo.create({guildId:i.guildId!,channelId:i.channelId!,challengerUserId:i.user.id,opponentUserId:target.id,challengerName:challenger.displayName,opponentName:opponent.displayName,control,key:`discord:${i.id}`});const message=await i.editReply(await this.payload(row));await this.repo.linkMessage(row.id,message.id);return;
  }
  const [,action,id]=i.customId.split(':');if(!id)throw new Error('Open the latest Chairmate card.');if(action==='open'){await i.deferReply({ephemeral:true});const row=await this.repo.get(id);if(row.status!=='ACTIVE')throw new Error('Your game is not ready yet.');const url=i.user.id===row.challengerUserId?(row.challengerColor==='white'?row.whiteUrl:row.blackUrl):i.user.id===row.opponentUserId?(row.opponentColor==='white'?row.whiteUrl:row.blackUrl):undefined;if(!url)throw new Error('Only the two named members can open this game.');await i.editReply({content:`Open your private Lichess board: ${url}`,allowedMentions:{parse:[]}});return;}
  if(action==='status'){await i.deferReply({ephemeral:true});const row=await this.repo.get(id);if(i.user.id!==row.opponentUserId)throw new Error('Only the nominated member can view Chairmate setup status.');const stored=row.lastProviderError??'',detail=/\((\d{3})\)/.exec(stored)?.[1],shape=stored.startsWith('Lichess challenge response missing private seats')?stored:undefined;await i.editReply({content:detail?`Lichess rejected board setup (HTTP ${detail}). No game link was stored.`:shape?`${shape} No game link was stored and Chairmate will not create a duplicate automatically.`:stored==='Lichess returned an incomplete guest-game response.'?'Lichess did not return both private player seats. No automatic retry will create a duplicate board.':'Lichess did not confirm board setup. No automatic retry will create a duplicate board.',allowedMentions:{parse:[]}});return;}
  if(action==='retry'){await i.deferUpdate();const row=await this.repo.retry(id,i.user.id,this.lichess,i.id);await this.refresh(i.client,row.id);if(row.status==='CREATING')await i.followUp({ephemeral:true,content:'Board setup is retrying safely.'});return;}
  if(action!=='accept'&&action!=='decline')throw new Error('Unknown Chairmate control.');await i.deferUpdate();const row=await this.repo.decide(id,i.user.id,action==='accept',this.lichess,i.id);await this.refresh(i.client,row.id);if(row.status==='CREATING')await i.followUp({ephemeral:true,content:'Your acceptance is saved. Creating the Lichess board now; the card will refresh automatically.'});
 }catch(error){const content=error instanceof Error?error.message:'Chairmate could not complete that action.';if(i.deferred||i.replied)await i.followUp({ephemeral:true,content}).catch(()=>undefined);else await i.reply({ephemeral:true,content}).catch(()=>undefined);}}
 private async payload(row:Awaited<ReturnType<ChairmateRepository['get']>>){const open=row.status==='ACTIVE',pending=row.status==='PENDING',retry=row.status==='ERROR'&&row.providerRetryAt!==null;const buttons=new ActionRowBuilder<ButtonBuilder>();if(pending)buttons.addComponents(new ButtonBuilder().setCustomId(`chess:accept:${row.id}`).setLabel('Accept').setStyle(ButtonStyle.Success),new ButtonBuilder().setCustomId(`chess:decline:${row.id}`).setLabel('Decline').setStyle(ButtonStyle.Danger));if(open)buttons.addComponents(new ButtonBuilder().setCustomId(`chess:open:${row.id}`).setLabel('Open My Game').setStyle(ButtonStyle.Primary));if(retry)buttons.addComponents(new ButtonBuilder().setCustomId(`chess:retry:${row.id}`).setLabel('Retry Board Setup').setStyle(ButtonStyle.Secondary));if(row.status==='ERROR')buttons.addComponents(new ButtonBuilder().setCustomId(`chess:status:${row.id}`).setLabel('Private Setup Status').setStyle(ButtonStyle.Secondary));const file='chairmate.png';return {content:'',embeds:[new EmbedBuilder().setColor(row.status==='ERROR'?0xf59e0b:0x0ea5a6).setImage(`attachment://${file}`)],files:[new AttachmentBuilder(await rasterizeSvg(renderChairmateCard({challenger:row.challengerName,opponent:row.opponentName,timeControl:row.timeControl,status:row.status,challengerColor:row.challengerColor??undefined,opponentColor:row.opponentColor??undefined})),{name:file,description:`Chairmate private match · ${row.challengerName} versus ${row.opponentName}`})],attachments:[],components:buttons.components.length?[buttons]:[],allowedMentions:{parse:[] as never[]}};}
 private async resultPayload(row:Awaited<ReturnType<ChairmateRepository['get']>>){const file='chairmate-result.png',replay=row.lichessGameUrl?new ActionRowBuilder<ButtonBuilder>().addComponents(new ButtonBuilder().setLabel('View Lichess Replay').setStyle(ButtonStyle.Link).setURL(row.lichessGameUrl)):undefined;return {content:'',embeds:[new EmbedBuilder().setColor(0x10b981).setImage(`attachment://${file}`)],files:[new AttachmentBuilder(await rasterizeSvg(renderChairmateCard({challenger:row.challengerName,opponent:row.opponentName,timeControl:row.timeControl,status:'FINISHED',challengerColor:row.challengerColor??undefined,opponentColor:row.opponentColor??undefined,outcome:row.result??'Game complete.'})),{name:file,description:`Chairmate result · ${row.challengerName} versus ${row.opponentName}`})],components:replay?[replay]:[],allowedMentions:{parse:[] as never[]}};}
 async refresh(client:Client,id:string){if(this.refreshing)return;this.refreshing=true;try{const row=await this.repo.get(id);if(!row.messageId)return;const channel=await client.channels.fetch(row.channelId);if(!channel?.isTextBased()||!('messages' in channel))return;const message=await channel.messages.fetch(row.messageId);if(message.author.id===client.user?.id)await message.edit(await this.payload(row));}finally{this.refreshing=false;}}
 async sweep(client:Client){const changed=await this.repo.recover(this.lichess);for(const id of changed)await this.refresh(client,id);for(const row of await this.repo.resultsToPost()){const channel=await client.channels.fetch(row.channelId);if(!channel?.isTextBased()||!('send' in channel))continue;await channel.send(await this.resultPayload(row));await this.repo.markResultPosted(row.id);await this.refresh(client,row.id);}}
}
