import {ActionRowBuilder,AttachmentBuilder,ButtonBuilder,ButtonStyle,EmbedBuilder,type ButtonInteraction,type Client,type Message} from 'discord.js';
import {DeliveryEngine,DomainError,PermissionEngine,type ConfigService,type StaffRole} from '../../../../packages/core/src/index.js';
import {CAPABILITY_MATRIX} from '../../../../packages/contracts/src/generated/capabilities.js';
import {PrismaChannelGamesRepository} from '../../../../packages/features-channel-games/src/prisma-repository.js';
import {recognizedWord} from '../../../../packages/features-channel-games/src/lexicon.js';
import {renderChannelGame} from '../../../../packages/features-channel-games/src/render.js';
import {rasterizeSvg} from '../../../../packages/renderer/src/raster.js';
export class DiscordChannelGamesCoordinator {
 constructor(private readonly repo:PrismaChannelGamesRepository,private readonly config:ConfigService,private readonly eligible:(g:string,u:string)=>Promise<boolean>){}
 async message(m:Message){if(!m.guildId||m.author.bot||!m.guild||await this.config.get(m.guildId,'features.channel_games')!==true)return;const [counting,letter]=await Promise.all(['channels.counting_channel','channels.last_letter_channel'].map(k=>this.config.get(m.guildId!,k)));if(m.channelId!==counting&&m.channelId!==letter)return;if(!await this.eligible(m.guildId,m.author.id))return;const member=await m.guild.members.fetch({user:m.author.id,force:true});if(member.isCommunicationDisabled())return;const c={guildId:m.guildId,channelId:m.channelId,userId:m.author.id,requestKey:m.id};const result=m.channelId===counting?await this.repo.counting(c,m.content):await this.repo.letter(c,m.content,recognizedWord);if(result&&'valid'in result&&result.valid)try{await m.react('✅');}catch{console.warn('Channel-game reaction unavailable; saved turn remains valid.');}}
 async handle(i:ButtonInteraction){try{if(!i.guildId||!i.guild||!i.channelId||await this.config.get(i.guildId,'features.channel_games')!==true)throw new DomainError('CHANNEL_DISABLED','Channel games are not enabled.');if(i.channelId!==await this.config.get(i.guildId,'channels.counting_channel'))throw new DomainError('COUNTING_CHANNEL','Use the original counting channel.');if(!await this.eligible(i.guildId,i.user.id))throw new DomainError('CHANNEL_RESTRICTED','You cannot use these controls right now.');const [prefix,action,raw]=i.customId.split(':'),version=Number(raw);if(prefix!=='channelgame'||action!=='restore'||!Number.isInteger(version))throw new DomainError('COUNTING_CONTROL','Use the current reset controls.');const member=await i.guild.members.fetch({user:i.user.id,force:true});let role:StaffRole='member';for(const candidate of ['recliner','chaise_lounge','throne'] as const){const id=await this.config.get(i.guildId,'roles.'+candidate);if(typeof id==='string'&&member.roles.cache.has(id))role=candidate;}if(i.guild.ownerId===i.user.id)role='throne';const allowed=new PermissionEngine(CAPABILITY_MATRIX.capabilities).can(role,'counting.restore');await i.deferReply({ephemeral:true});await this.repo.restore({guildId:i.guildId,channelId:i.channelId,userId:i.user.id,requestKey:i.id},version,allowed);await i.editReply({content:'Restored the last valid count and recorded the staff action.'});}catch(e){const content=e instanceof DomainError?e.message:'Counting could not be restored. Its saved state is unchanged.';if(i.deferred)await i.editReply({content});else await i.reply({ephemeral:true,content});}}
 async deliver(client:Client,id:string){const p=await this.repo.announcement(id),channel=await client.channels.fetch(p.channelId);if(!channel?.isSendable()||!('messages' in channel))throw new Error('Channel-game destination unavailable.');const deliveryUrl=`https://discord.com/channels/${p.guildId}/${p.channelId}?aj_delivery=${encodeURIComponent(id)}`;await new DeliveryEngine(this.repo.delivery(id)).deliver('channelgame:'+id,{find:async marker=>{const messages=await channel.messages.fetch({limit:100});return messages.find(m=>m.author.id===client.user?.id&&m.embeds.some(e=>e.url===deliveryUrl||e.footer?.text===marker))?.id??null;},send:async _marker=>{const embed=new EmbedBuilder().setAuthor({name:'Angrier Jordan'}).setTitle(p.title).setURL(deliveryUrl).setDescription(p.body).setColor(0x10B981).setFooter({text:'Chairs · Channel Games'});const files=p.art?[new AttachmentBuilder(await rasterizeSvg(renderChannelGame(p.title,'A community milestone','Keep the next round going.')),{name:'channel-game.png'})]:[];if(p.art)embed.setImage('attachment://channel-game.png');const components=p.version===undefined?[]:[new ActionRowBuilder<ButtonBuilder>().addComponents(new ButtonBuilder().setCustomId('channelgame:restore:'+p.version).setLabel('Restore intentional sabotage · Staff').setStyle(ButtonStyle.Secondary))];return(await channel.send({embeds:[embed],files,components,allowedMentions:{parse:[]}})).id;}});}
}
