import {ActionRowBuilder,AttachmentBuilder,ButtonBuilder,ButtonStyle,EmbedBuilder,ModalBuilder,PermissionFlagsBits,StringSelectMenuBuilder,TextInputBuilder,TextInputStyle,UserSelectMenuBuilder,type ButtonInteraction,type ChatInputCommandInteraction,type Client,type Guild,type ModalSubmitInteraction,type StringSelectMenuInteraction,type UserSelectMenuInteraction} from 'discord.js';
import {DeliveryEngine,DomainError,PermissionEngine,type ConfigService,type StaffRole} from '../../../../packages/core/src/index.js';
import {CAPABILITY_MATRIX} from '../../../../packages/contracts/src/generated/capabilities.js';
import {PrismaCommunityRepository,type CommunityContext,type CommunityStart,type CommunityView} from '../../../../packages/features-community/src/prisma-repository.js';
import {COMMUNITY_KINDS,SUGGESTION_STATUSES,type CommunityKind} from '../../../../packages/features-community/src/domain.js';
import {COMMUNITY_TITLES,communityTranscript,renderCommunity} from '../../../../packages/features-community/src/render.js';
import {rasterizeSvg} from '../../../../packages/renderer/src/raster.js';
type Interaction=ChatInputCommandInteraction|ButtonInteraction|ModalSubmitInteraction|StringSelectMenuInteraction|UserSelectMenuInteraction;
type Row=ActionRowBuilder<ButtonBuilder>|ActionRowBuilder<StringSelectMenuBuilder>|ActionRowBuilder<UserSelectMenuBuilder>;
export const COMMUNITY_COMMANDS=new Set<string>(COMMUNITY_KINDS);
export class DiscordCommunityCoordinator {
 private refreshes=new Map<string,Promise<void>>();private sweeping=false;
 constructor(private repo:PrismaCommunityRepository,private config:ConfigService,private eligible:(g:string,u:string)=>Promise<boolean>){}
 private async member(guild:Guild,id:string,channelId:string){const m=await guild.members.fetch({user:id,force:true});if(m.user.bot||m.isCommunicationDisabled()||!m.permissionsIn(channelId).has(PermissionFlagsBits.ViewChannel|PermissionFlagsBits.SendMessages)||!await this.eligible(guild.id,id))throw new DomainError('COMMUNITY_RESTRICTED','Choose a current eligible member with access to this channel.');return m;}
 private async context(i:Interaction):Promise<CommunityContext>{if(!i.guildId||!i.guild||!i.channelId)throw new DomainError('SERVER_ONLY','Use community tools in the server.');if(await this.config.get(i.guildId,'features.community')!==true)throw new DomainError('COMMUNITY_DISABLED','Community tools are not enabled yet.');if(i.channelId!==await this.config.get(i.guildId,'channels.bot_channel'))throw new DomainError('COMMUNITY_CHANNEL','Use the configured bot channel.');const member=await this.member(i.guild,i.user.id,i.channelId);let role:StaffRole='member';for(const candidate of ['recliner','chaise_lounge','throne'] as const){const id=await this.config.get(i.guildId,'roles.'+candidate);if(typeof id==='string'&&member.roles.cache.has(id))role=candidate;}if(i.guild.ownerId===i.user.id)role='throne';return{guildId:i.guildId,channelId:i.channelId,userId:i.user.id,requestKey:i.id,manage:new PermissionEngine(CAPABILITY_MATRIX.capabilities).can(role,'community.manage')};}
 private admin(c:CommunityContext){if(!c.manage)throw new DomainError('COMMUNITY_ADMIN','This action requires Chaise Lounge or Throne.');}
 private modal(id:string,action:string,title:string,label:string,max:number){return new ModalBuilder().setCustomId(`community:${action}:${id}`).setTitle(title).addComponents(new ActionRowBuilder<TextInputBuilder>().addComponents(new TextInputBuilder().setCustomId('value').setLabel(label).setStyle(TextInputStyle.Paragraph).setRequired(true).setMaxLength(max)));}
 private button(v:CommunityView,action:string,label:string,arg?:string){return new ButtonBuilder().setCustomId(`community:${action}:${v.id}${arg?':'+arg:''}`).setLabel(label).setStyle(ButtonStyle.Secondary);}
 async handle(i:Interaction){try{const c=await this.context(i);if(i.isChatInputCommand()){await this.command(i,c);return;}const[prefix,action,id,arg,owner]=i.customId.split(':');if(prefix!=='community'||!action||!id)throw new DomainError('COMMUNITY_CONTROL','Use the current community controls.');
  if(action==='archive'){if(id!==i.user.id||!i.isStringSelectMenu())throw new DomainError('COMMUNITY_OWNER','Open your own archive.');const v=await this.repo.publicView(i.values[0]!);if(v.guildId!==c.guildId)throw new DomainError('COMMUNITY_MISSING','This post is unavailable.');const rows:Row[]=c.manage&&v.kind==='suggest'?[this.statusPicker(v)]:c.manage&&v.kind==='ama'&&v.state==='OPEN'?[new ActionRowBuilder<ButtonBuilder>().addComponents(this.button(v,'answer','Answer'),this.button(v,'decline','Decline'))]:[];await i.reply({ephemeral:true,content:communityTranscript(v).slice(0,1900),components:rows,allowedMentions:{parse:[]}});return;}
  const v=await this.repo.publicView(id);if(v.guildId!==c.guildId||v.channelId!==c.channelId)throw new DomainError('COMMUNITY_MISSING','Use the post’s original server and channel.');const privateActions=['ranked_submit','vote_pick','category_nom','nominee','category_vote','season_vote','confirm_entry','status_pick','answer','answer_submit','decline','fulfill','status'].includes(action);if(!i.isModalSubmit()&&!privateActions&&i.message.id!==v.messageId)throw new DomainError('COMMUNITY_CONTROL','Use the original community post.');if(['nominee','season_vote'].includes(action)&&owner!==i.user.id||action==='confirm_entry'&&owner!==i.user.id)throw new DomainError('COMMUNITY_OWNER','Open your own choices.');
  if(action==='details'){await i.reply({ephemeral:true,files:[new AttachmentBuilder(Buffer.from(communityTranscript(v)),{name:'community-post.txt'})],allowedMentions:{parse:[]}});return;}
  if(action==='vote'&&i.isButton()){if(v.ranked){await i.showModal(this.modal(id,'ranked_submit','Rank this poll','Choice numbers, best first (for example 2,1,3)',100));return;}await i.reply({ephemeral:true,content:'Choose one option. You may revise your ballot until close.',components:[new ActionRowBuilder<StringSelectMenuBuilder>().addComponents(new StringSelectMenuBuilder().setCustomId('community:vote_pick:'+id).setPlaceholder('Your ballot').addOptions(v.choices.map(x=>({label:x.label,value:x.id}))))]});return;}
  if((action==='nominate'||action==='seasonvote')&&i.isButton()){await i.reply({ephemeral:true,content:'Choose a category.',components:[new ActionRowBuilder<StringSelectMenuBuilder>().addComponents(new StringSelectMenuBuilder().setCustomId(`community:${action==='nominate'?'category_nom':'category_vote'}:${id}`).setPlaceholder('Category').addOptions(v.categories.map(x=>({label:x.name,value:x.id}))))]});return;}
  if(action==='category_nom'&&i.isStringSelectMenu()){if(v.phase!=='nominations')throw new DomainError('SUPERLATIVE_PHASE','Nominations are closed.');await i.reply({ephemeral:true,content:'Nominate one other member. This choice cannot be changed.',components:[new ActionRowBuilder<UserSelectMenuBuilder>().addComponents(new UserSelectMenuBuilder().setCustomId(`community:nominee:${id}:${i.values[0]}:${c.userId}`).setPlaceholder('Nominee'))]});return;}
  if(action==='category_vote'&&i.isStringSelectMenu()){const cat=v.categories.find(x=>x.id===i.values[0]);if(!cat?.finalists.length)throw new DomainError('SUPERLATIVE_FINALISTS','No finalists were nominated in this category.');await i.reply({ephemeral:true,content:cat.name,components:[new ActionRowBuilder<StringSelectMenuBuilder>().addComponents(new StringSelectMenuBuilder().setCustomId(`community:season_vote:${id}:${cat.id}:${c.userId}`).setPlaceholder('Choose a finalist').addOptions(cat.finalists.map(x=>({label:x.name,value:x.id}))))]});return;}
  if(action==='enter'&&i.isButton()){await i.reply({ephemeral:true,content:v.fee==='0'?'Confirm your free entry?':`Enter for **${v.fee} Ottomans**? The entry fee is removed from circulation. One entry per member.`,components:[new ActionRowBuilder<ButtonBuilder>().addComponents(this.button(v,'confirm_entry','Confirm Entry',`${v.fee}:${c.userId}`))],allowedMentions:{parse:[]}});return;}
  if(action==='status'&&i.isButton()){this.admin(c);await i.reply({ephemeral:true,content:'Update the suggestion status.',components:[this.statusPicker(v)]});return;}
  if(action==='answer'&&i.isButton()){this.admin(c);await i.showModal(this.modal(id,'answer_submit','Answer AMA','Your public answer',1500));return;}
  await i.deferReply({ephemeral:true});if(action==='vote_pick'&&i.isStringSelectMenu())await this.repo.vote(c,id,i.values);else if(action==='ranked_submit'&&i.isModalSubmit())await this.repo.vote(c,id,i.fields.getTextInputValue('value').split(',').map(x=>x.trim()));else if(action==='season_vote'&&i.isStringSelectMenu())await this.repo.vote(c,id,i.values,arg);else if(action==='nominee'&&i.isUserSelectMenu()){const m=await this.member(i.guild!,i.values[0]!,c.channelId);await this.repo.nominate(c,id,arg!,{id:m.id,name:m.displayName});}else if(action==='confirm_entry'){const m=await this.member(i.guild!,c.userId,c.channelId);await this.repo.enter(c,id,m.displayName,arg!);}else if(action==='upvote')await this.repo.vote(c,id,['up']);else if(action==='close')await this.repo.closePoll(c,id);else if(action==='status_pick'&&i.isStringSelectMenu())await this.repo.moderate(c,id,i.values[0]!);else if(action==='answer_submit'&&i.isModalSubmit())await this.repo.moderate(c,id,'ANSWERED',i.fields.getTextInputValue('value'));else if(action==='decline')await this.repo.moderate(c,id,'DECLINED');else if(action==='fulfill')await this.repo.fulfill(c,id);else throw new DomainError('COMMUNITY_CONTROL','That control is unavailable.');await i.editReply({content:'Your action is saved.',allowedMentions:{parse:[]}});try{await this.refresh(i.client,id);}catch{await i.followUp({ephemeral:true,content:'The saved post update is queued for delivery.'});}
 }catch(e){const content=e instanceof DomainError?e.message:'The community action could not be completed or displayed. Saved entries and rewards remain recorded; check the post before retrying.';if(i.replied)await i.followUp({ephemeral:true,content});else if(i.deferred)await i.editReply({content});else await i.reply({ephemeral:true,content});}}
 private async command(i:ChatInputCommandInteraction,c:CommunityContext){const kind=i.commandName as CommunityKind;await i.deferReply({ephemeral:true});if(kind==='superlatives'&&!i.options.getString('categories')){const rows=(await this.repo.active(c.guildId)).filter(x=>(x.data as {kind:string}).kind==='superlatives');await i.editReply({content:rows.length?rows.map(x=>`Active season: https://discord.com/channels/${c.guildId}/${x.channelId}/${x.messageId??''}`).join('\n'):'No season is active. Community admins can start one with category names.'});return;}
  if(kind==='suggest'&&!i.options.getString('text')||kind==='ama'&&!i.options.getString('question')){const sort=kind==='ama'?i.options.getString('sort')??'newest':'newest';if(kind==='ama'&&sort==='upvotes')this.admin(c);const rows=await this.repo.archive(c.guildId,kind as 'suggest'|'ama',c.userId,Boolean(c.manage),kind==='suggest'?i.options.getString('search')??'':'',sort,(i.options.getInteger('page')??1)-1);await i.editReply({content:rows.length?rows.map(x=>`${x.status} · ${x.text.slice(0,70)}${'upvotes'in x?' · '+x.upvotes+' upvotes':''}${x.mine?' · Yours':''}`).join('\n').slice(0,1800):'No matching posts yet.',components:rows.length?[new ActionRowBuilder<StringSelectMenuBuilder>().addComponents(new StringSelectMenuBuilder().setCustomId('community:archive:'+c.userId).setPlaceholder('Open a post').addOptions(rows.map(x=>({label:x.text.slice(0,100),value:x.id,description:x.status}))))]:[],allowedMentions:{parse:[]}});return;}
  const o:CommunityStart={kind,text:kind==='poll'?i.options.getString('question',true):kind==='superlatives'?i.options.getString('categories',true):kind==='suggest'?i.options.getString('text',true):kind==='ama'?i.options.getString('question',true):i.options.getString('prize',true),name:(await this.member(i.guild!,c.userId,c.channelId)).displayName};if(['poll','suggest','ama'].includes(kind))o.anonymous=i.options.getBoolean('anonymous')??false;if(kind==='poll'){o.choices=i.options.getString('choices',true);o.maxChoices=Number(await this.config.get(c.guildId,'poll.max_choices'));o.hidden=i.options.getString('results')!=='live';o.ranked=i.options.getBoolean('ranked')??false;const minutes=i.options.getInteger('minutes');if(minutes!==null)o.minutes=minutes;}if(kind==='giveaway'){this.admin(c);o.minutes=i.options.getInteger('hours',true)*60;o.winnerCount=i.options.getInteger('winners',true);o.fee=i.options.getInteger('fee')??0;o.maxFee=Number(await this.config.get(c.guildId,'giveaway.max_entry_fee'));const min=Number(await this.config.get(c.guildId,'giveaway.min_duration_minutes')),max=Number(await this.config.get(c.guildId,'giveaway.max_duration_minutes')),winners=Number(await this.config.get(c.guildId,'giveaway.max_winners'));if(o.minutes<Math.max(60,min)||o.minutes>Math.min(10080,max)||o.winnerCount>Math.min(5,winners))throw new DomainError('GIVEAWAY_LIMITS','This giveaway exceeds the configured limits.');}const result=await this.repo.start(c,o);await this.publish(i.client,result.jobId);await i.editReply({content:'Your community post is ready in this channel.'});}
 private statusPicker(v:CommunityView){return new ActionRowBuilder<StringSelectMenuBuilder>().addComponents(new StringSelectMenuBuilder().setCustomId('community:status_pick:'+v.id).setPlaceholder('Suggestion status').addOptions(SUGGESTION_STATUSES.map(x=>({label:x,value:x}))));}
 async payload(v:CommunityView){const buttons:ButtonBuilder[]=[];if(v.state==='OPEN'){if(v.kind==='poll'||v.kind==='suggest')buttons.push(this.button(v,'vote','Vote'));if(v.kind==='poll')buttons.push(this.button(v,'close','Close Poll'));if(v.kind==='superlatives')buttons.push(this.button(v,v.phase==='nominations'?'nominate':'seasonvote',v.phase==='nominations'?'Nominate':'Vote'));if(v.kind==='giveaway')buttons.push(this.button(v,'enter',v.fee==='0'?'Enter Giveaway':'Enter · '+v.fee+' Ottomans'));if(v.kind==='ama')buttons.push(this.button(v,'upvote','Upvote'),this.button(v,'answer','Answer'),this.button(v,'decline','Decline'));if(v.kind==='suggest')buttons.push(this.button(v,'status','Update Status'));}if(v.kind==='giveaway'&&v.status==='FULFILLMENT_PENDING')buttons.push(this.button(v,'fulfill','Mark Reward Fulfilled'));buttons.push(this.button(v,'details','Details'));const rows:Row[]=[];for(let n=0;n<buttons.length;n+=5)rows.push(new ActionRowBuilder<ButtonBuilder>().addComponents(...buttons.slice(n,n+5)));const description=communityTranscript(v).slice(0,1800)+(v.expiresAt&&v.state==='OPEN'?`\nCloses <t:${Math.floor(v.expiresAt.getTime()/1000)}:R>.`:'');return{embeds:[new EmbedBuilder().setAuthor({name:'Angrier Jordan'}).setTitle(COMMUNITY_TITLES[v.kind]).setDescription(description).setColor(0x0ea5a6).setImage('attachment://community.png').setFooter({text:'community:'+v.id})],files:[new AttachmentBuilder(await rasterizeSvg(renderCommunity(v)),{name:'community.png'})],components:rows,attachments:[],allowedMentions:{parse:[] as never[]}};}
 async publish(client:Client,jobId:string){const p=await this.repo.deliveryJob(jobId),v=await this.repo.publicView(p.sessionId);if(v.messageId){await this.refresh(client,v.id);return;}const channel=await client.channels.fetch(p.channelId);if(!channel?.isSendable()||!('messages'in channel))throw new Error('Community destination unavailable.');const marker='community:'+v.id,messageId=await new DeliveryEngine(this.repo.delivery((await this.repo.initialPublication(v.id)).id)).deliver(marker,{find:async marker=>{const messages=await channel.messages.fetch({limit:100});return messages.find(m=>m.author.id===client.user?.id&&m.embeds.some(e=>e.footer?.text===marker))?.id??null;},send:async()=>{const message=await channel.send(await this.payload(await this.repo.publicView(p.sessionId)));return message.id;}});await this.repo.linkMessage(p.sessionId,p.guildId,messageId);}
 async refresh(client:Client,id:string){const before=this.refreshes.get(id)??Promise.resolve(),current=before.catch(()=>{}).then(async()=>{const v=await this.repo.publicView(id);if(!v.messageId)return;const channel=await client.channels.fetch(v.channelId);if(!channel?.isTextBased()||!('messages'in channel))throw new Error('Community channel unavailable.');const message=await channel.messages.fetch(v.messageId);if(message.author.id!==client.user?.id)throw new Error('Community message author mismatch.');await message.edit(await this.payload(v));});this.refreshes.set(id,current);try{await current;}finally{if(this.refreshes.get(id)===current)this.refreshes.delete(id);}}
 async advance(client:Client,guildId:string,id:string,round:number){await this.repo.advance(guildId,id,round);await this.refresh(client,id);}
 async sweep(client:Client){if(this.sweeping)return;this.sweeping=true;try{for(const s of await this.repo.active()){if(s.expiresAt&&s.expiresAt<=new Date())await this.advance(client,s.guildId,s.id,(s.data as {round:number}).round);}}finally{this.sweeping=false;}}
}
