import {createHash} from 'node:crypto';
import {ActionRowBuilder,AttachmentBuilder,ButtonBuilder,ButtonStyle,EmbedBuilder,ModalBuilder,PermissionFlagsBits,StringSelectMenuBuilder,TextInputBuilder,TextInputStyle,UserSelectMenuBuilder,type ButtonInteraction,type ChatInputCommandInteraction,type Client,type Guild,type ModalSubmitInteraction,type StringSelectMenuInteraction,type UserSelectMenuInteraction} from 'discord.js';
import {DeliveryEngine,DomainError,PermissionEngine,type ConfigService,type StaffRole} from '../../../../packages/core/src/index.js';
import {CAPABILITY_MATRIX} from '../../../../packages/contracts/src/generated/capabilities.js';
import {PrismaCommunityRepository,type CommunityContext,type CommunityStart,type CommunityView} from '../../../../packages/features-community/src/prisma-repository.js';
import {COMMUNITY_KINDS,SUGGESTION_STATUSES,type CommunityKind} from '../../../../packages/features-community/src/domain.js';
import {COMMUNITY_TITLES,communityTranscript,renderCommunity,renderCommunityNotice} from '../../../../packages/features-community/src/render.js';
import {rasterizeSvg} from '../../../../packages/renderer/src/raster.js';
import {memberArt} from './member-art.js';
import {createDisplay,wideDisplay} from './wide-display.js';
async function notice(title:string,message:string){return [new AttachmentBuilder(await rasterizeSvg(renderCommunityNotice(title,message)),{name:'community-window.png'})];}
type Interaction=ChatInputCommandInteraction|ButtonInteraction|ModalSubmitInteraction|StringSelectMenuInteraction|UserSelectMenuInteraction;
type Row=ActionRowBuilder<ButtonBuilder>|ActionRowBuilder<StringSelectMenuBuilder>|ActionRowBuilder<UserSelectMenuBuilder>;
export const COMMUNITY_COMMANDS=new Set<string>(COMMUNITY_KINDS);
export class DiscordCommunityCoordinator {
 private published=new Map<string,string>();private refreshes=new Map<string,Promise<void>>();private sweeping=false;
 constructor(private repo:PrismaCommunityRepository,private config:ConfigService,private eligible:(g:string,u:string)=>Promise<boolean>){}
 private async member(guild:Guild,id:string,channelId:string){const m=await guild.members.fetch({user:id,force:true});if(m.user.bot||m.isCommunicationDisabled()||!m.permissionsIn(channelId).has(PermissionFlagsBits.ViewChannel|PermissionFlagsBits.SendMessages)||!await this.eligible(guild.id,id))throw new DomainError('COMMUNITY_RESTRICTED','Choose a current eligible member with access to this channel.');return m;}
 private async context(i:Interaction,allowSuggestionPanel=false,allowSuggestionRedirect=false):Promise<CommunityContext>{if(!i.guildId||!i.guild||!i.channelId)throw new DomainError('SERVER_ONLY','Use community tools in the server.');if(await this.config.get(i.guildId,'features.community')!==true)throw new DomainError('COMMUNITY_DISABLED','Community tools are not enabled yet.');const [botChannel,suggestionsChannel]=await Promise.all([this.config.get(i.guildId,'channels.bot_channel'),this.config.get(i.guildId,'channels.suggestions_channel')]);if(i.channelId!==botChannel&&!(allowSuggestionPanel&&i.channelId===suggestionsChannel)&&!allowSuggestionRedirect)throw new DomainError('COMMUNITY_CHANNEL','Use the configured bot channel.');const member=await this.member(i.guild,i.user.id,i.channelId);let role:StaffRole='member';for(const candidate of ['recliner','chaise_lounge','throne'] as const){const id=await this.config.get(i.guildId,'roles.'+candidate);if(typeof id==='string'&&member.roles.cache.has(id))role=candidate;}if(i.guild.ownerId===i.user.id)role='throne';return{guildId:i.guildId,channelId:i.channelId,userId:i.user.id,requestKey:i.id,manage:new PermissionEngine(CAPABILITY_MATRIX.capabilities).can(role,'community.manage')};}
 private async enabled(guildId:string){if(await this.config.get(guildId,'features.community')!==true)throw new DomainError('COMMUNITY_DISABLED','Community tools are not enabled yet.');}
 private admin(c:CommunityContext){if(!c.manage)throw new DomainError('COMMUNITY_ADMIN','This action requires Chaise Lounge or Throne.');}
 private modal(id:string,action:string,title:string,label:string,max:number){return new ModalBuilder().setCustomId(`community:${action}:${id}`).setTitle(title).addComponents(new ActionRowBuilder<TextInputBuilder>().addComponents(new TextInputBuilder().setCustomId('value').setLabel(label).setStyle(TextInputStyle.Paragraph).setRequired(true).setMaxLength(max)));}
 private button(v:CommunityView,action:string,label:string,arg?:string){return new ButtonBuilder().setCustomId(`community:${action}:${v.id}${arg?':'+arg:''}`).setLabel(label).setStyle(['vote','nominate','seasonvote','enter','answer','confirm_entry'].includes(action)?ButtonStyle.Primary:['decline','close'].includes(action)?ButtonStyle.Danger:ButtonStyle.Secondary);}
 async handle(i:Interaction){let updateAck=false;try{
 const actionHint=i.isChatInputCommand()?'':i.customId.split(':')[1];
 const modalLaunch=i.isButton()&&['vote','answer','suggest_submit'].includes(actionHint??'');
 if(!modalLaunch){if(!i.isChatInputCommand()&&!i.isModalSubmit()&&(i.isStringSelectMenu()||i.isUserSelectMenu()||['upvote','close','decline','fulfill','confirm_entry'].includes(actionHint??''))){await i.deferUpdate();updateAck=true;}else await i.deferReply({ephemeral:true});}
const c=await this.context(i,['suggest_submit','suggest_submit_modal'].includes(actionHint??''),i.isChatInputCommand()&&i.commandName==='suggest');if(i.isChatInputCommand()){await this.command(i,c);return;}const[prefix,action,id,arg,owner]=i.customId.split(':');if(prefix!=='community'||!action||!id)throw new DomainError('COMMUNITY_CONTROL','Use the current community controls.');
  if(action==='suggest_submit'&&i.isButton()){await i.showModal(new ModalBuilder().setCustomId('community:suggest_submit_modal:panel').setTitle('Submit a Suggestion').addComponents(new ActionRowBuilder<TextInputBuilder>().addComponents(new TextInputBuilder().setCustomId('title').setLabel('Suggestion Title').setStyle(TextInputStyle.Short).setRequired(true).setMaxLength(100)),new ActionRowBuilder<TextInputBuilder>().addComponents(new TextInputBuilder().setCustomId('change').setLabel('What should we change or add?').setStyle(TextInputStyle.Paragraph).setRequired(true).setMaxLength(1000)),new ActionRowBuilder<TextInputBuilder>().addComponents(new TextInputBuilder().setCustomId('why').setLabel('Why would this be useful or fun?').setStyle(TextInputStyle.Paragraph).setRequired(false).setMaxLength(600))));return;}
  if(action==='suggest_submit_modal'&&i.isModalSubmit()){const title=i.fields.getTextInputValue('title').trim(),change=i.fields.getTextInputValue('change').trim(),why=i.fields.getTextInputValue('why').trim(),destination=await this.config.get(c.guildId,'channels.suggestions_channel');if(typeof destination!=='string'||!destination)throw new DomainError('SUGGESTIONS_CHANNEL','The Suggestions channel is not configured.');const member=await this.member(i.guild!,c.userId,destination),result=await this.repo.start({...c,channelId:destination},{kind:'suggest',text:[title,change,why].filter(Boolean).join('\n\n'),name:member.displayName});await this.publish(i.client,result.jobId);await i.editReply({content:`Your suggestion is live in <#${destination}> for the community to vote on.`,allowedMentions:{parse:[]}});return;}
  if(action==='archive'){if(id!==i.user.id||!i.isStringSelectMenu())throw new DomainError('COMMUNITY_OWNER','Open your own archive.');const v=await this.repo.publicView(i.values[0]!);if(v.guildId!==c.guildId)throw new DomainError('COMMUNITY_MISSING','This post is unavailable.');const rows:Row[]=c.manage&&v.kind==='suggest'?[this.statusPicker(v)]:c.manage&&v.kind==='ama'&&v.state==='OPEN'?[new ActionRowBuilder<ButtonBuilder>().addComponents(this.button(v,'answer','Answer'),this.button(v,'decline','Decline'))]:[];await this.respond(i,{ephemeral:true,content:'',files:(await this.payload(v,i.client)).files,components:rows,allowedMentions:{parse:[]}});return;}
  const v=await this.repo.publicView(id);if(v.guildId!==c.guildId||v.channelId!==c.channelId)throw new DomainError('COMMUNITY_MISSING','Use the post’s original server and channel.');const privateActions=['ranked_submit','vote_pick','category_nom','nominee','category_vote','season_vote','confirm_entry','status_pick','answer','answer_submit','decline','fulfill','status'].includes(action);if(!i.isModalSubmit()&&!privateActions&&i.message.id!==v.messageId)throw new DomainError('COMMUNITY_CONTROL','Use the original community post.');if(['nominee','season_vote'].includes(action)&&owner!==i.user.id||action==='confirm_entry'&&owner!==i.user.id)throw new DomainError('COMMUNITY_OWNER','Open your own choices.');
  if(action==='details'){await this.respond(i,{ephemeral:true,files:[new AttachmentBuilder(Buffer.from(await this.readableTranscript(v,i.client)),{name:'community-post.txt'})],allowedMentions:{parse:[]}});return;}
  if(action==='vote'&&i.isButton()){if(v.ranked){await i.showModal(this.modal(id,'ranked_submit','Rank this poll','Choice numbers, best first (for example 2,1,3)',100));return;}await this.respond(i,{ephemeral:true,content:'',files:await notice('Your ballot','Choose one option below. You may revise your ballot until close.'),components:[new ActionRowBuilder<StringSelectMenuBuilder>().addComponents(new StringSelectMenuBuilder().setCustomId('community:vote_pick:'+id).setPlaceholder('Your ballot').addOptions(v.choices.map(x=>({label:x.label,value:x.id}))))]});return;}
  if((action==='nominate'||action==='seasonvote')&&i.isButton()){await this.respond(i,{ephemeral:true,content:'',files:await notice('Superlatives','Choose a category.'),components:[new ActionRowBuilder<StringSelectMenuBuilder>().addComponents(new StringSelectMenuBuilder().setCustomId(`community:${action==='nominate'?'category_nom':'category_vote'}:${id}`).setPlaceholder('Category').addOptions(v.categories.map(x=>({label:x.name,value:x.id}))))]});return;}
  if(action==='category_nom'&&i.isStringSelectMenu()){if(v.phase!=='nominations')throw new DomainError('SUPERLATIVE_PHASE','Nominations are closed.');await this.respond(i,{ephemeral:true,content:'',files:await notice('Your nomination','Nominate one other member. This choice cannot be changed.'),components:[new ActionRowBuilder<UserSelectMenuBuilder>().addComponents(new UserSelectMenuBuilder().setCustomId(`community:nominee:${id}:${i.values[0]}:${c.userId}`).setPlaceholder('Nominee'))]});return;}
  if(action==='category_vote'&&i.isStringSelectMenu()){const cat=v.categories.find(x=>x.id===i.values[0]);if(!cat?.finalists.length)throw new DomainError('SUPERLATIVE_FINALISTS','No finalists were nominated in this category.');await this.respond(i,{ephemeral:true,content:'',files:await notice('Choose a finalist',cat.name),components:[new ActionRowBuilder<StringSelectMenuBuilder>().addComponents(new StringSelectMenuBuilder().setCustomId(`community:season_vote:${id}:${cat.id}:${c.userId}`).setPlaceholder('Choose a finalist').addOptions(cat.finalists.map(x=>({label:x.name,value:x.id}))))]});return;}
  if(action==='enter'&&i.isButton()){await this.respond(i,{ephemeral:true,content:v.fee==='0'?'Confirm your free entry?':`Enter for **${v.fee} Ottomans**? The entry fee is removed from circulation. One entry per member.`,files:await notice('Confirm entry',v.fee==='0'?'Confirm your free entry?':`Enter for ${v.fee} Ottomans? The entry fee is removed from circulation. One entry per member.`),components:[new ActionRowBuilder<ButtonBuilder>().addComponents(this.button(v,'confirm_entry','Confirm Entry',`${v.fee}:${c.userId}`))],allowedMentions:{parse:[]}});return;}
  if(action==='status'&&i.isButton()){this.admin(c);await this.respond(i,{ephemeral:true,content:'',files:await notice('Suggestion status','Update the suggestion status.'),components:[this.statusPicker(v)]});return;}
  if(action==='answer'&&i.isButton()){this.admin(c);await i.showModal(this.modal(id,'answer_submit','Answer AMA','Your public answer',1500));return;}
  if(!i.deferred&&!i.replied)await i.deferReply({ephemeral:true});if(action==='vote_pick'&&i.isStringSelectMenu())await this.repo.vote(c,id,i.values);else if(action==='ranked_submit'&&i.isModalSubmit())await this.repo.vote(c,id,i.fields.getTextInputValue('value').split(',').map(x=>x.trim()));else if(action==='season_vote'&&i.isStringSelectMenu())await this.repo.vote(c,id,i.values,arg);else if(action==='nominee'&&i.isUserSelectMenu()){const m=await this.member(i.guild!,i.values[0]!,c.channelId);await this.repo.nominate(c,id,arg!,{id:m.id,name:m.displayName});}else if(action==='confirm_entry'){const m=await this.member(i.guild!,c.userId,c.channelId);await this.repo.enter(c,id,m.displayName,arg!);}else if(action==='upvote')await this.repo.vote(c,id,['up']);else if(action==='close')await this.repo.closePoll(c,id);else if(action==='status_pick'&&i.isStringSelectMenu())await this.repo.moderate(c,id,i.values[0]!);else if(action==='answer_submit'&&i.isModalSubmit())await this.repo.moderate(c,id,'ANSWERED',i.fields.getTextInputValue('value'));else if(action==='decline')await this.repo.moderate(c,id,'DECLINED');else if(action==='fulfill')await this.repo.fulfill(c,id);else throw new DomainError('COMMUNITY_CONTROL','That control is unavailable.');if(updateAck){if('message'in i&&i.message?.flags.has('Ephemeral'))await i.editReply({content:'Saved. You may return to the community post.',embeds:[],files:[],attachments:[],components:[],allowedMentions:{parse:[]}});}else await i.deleteReply();try{await this.refresh(i.client,id);}catch{await i.followUp({ephemeral:true,content:'The saved post update is queued for delivery.',allowedMentions:{parse:[]}});}
 }catch(e){const content=e instanceof DomainError?e.message:'The community action could not be completed or displayed. Saved entries and rewards remain recorded; check the post before retrying.';if(updateAck||i.replied)await i.followUp({ephemeral:true,content,files:await notice('Community notice',content)});else if(i.deferred)await i.editReply({content,files:await notice('Community notice',content)});else await this.respond(i,{ephemeral:true,content,files:await notice('Community notice',content)});}}
 private async readableTranscript(v:CommunityView,client:Client){let value=communityTranscript(v);for(const id of new Set((v.ballots??[]).map(b=>b.memberId))){const art=await memberArt(client,v.guildId,id);value=value.replaceAll(id,art?.name??'Member');}return value;}
 private async respond(i:Interaction,payload:any){if(i.deferred||i.replied){const {ephemeral,...rest}=payload;await i.editReply({...rest,attachments:[]});}else await i.reply(payload);}
 private async command(i:ChatInputCommandInteraction,c:CommunityContext){const kind=i.commandName as CommunityKind;if(!i.deferred&&!i.replied)await i.deferReply({ephemeral:true});if(kind==='suggest'){const destination=await this.config.get(c.guildId,'channels.suggestions_channel');if(typeof destination!=='string'||!destination)throw new DomainError('SUGGESTIONS_CHANNEL','The Suggestions channel is not configured.');await i.editReply({content:`Suggestions are collected in <#${destination}>. Open the panel there to submit an idea; new suggestions publish in that channel for community voting.`,files:await notice('EAJ Suggestions','Open the Suggestions panel in Empty Seats to submit an idea.'),components:[new ActionRowBuilder<ButtonBuilder>().addComponents(new ButtonBuilder().setLabel('Open Empty Seats').setStyle(ButtonStyle.Link).setURL(`https://discord.com/channels/${c.guildId}/${destination}`))],allowedMentions:{parse:[]}});return;}if(kind==='superlatives'&&!i.options.getString('categories')){const rows=(await this.repo.active(c.guildId)).filter(x=>(x.data as {kind:string}).kind==='superlatives');await i.editReply({content:rows.length?rows.map(x=>`Active season: https://discord.com/channels/${c.guildId}/${x.channelId}/${x.messageId??''}`).join('\n'):'No season is active. Community admins can start one with category names.',files:await notice('Superlatives',rows.length?'A season is active. Use the link to open it.':'No season is active. Use the panel in this channel to create one.')});return;}
  if(kind==='ama'&&!i.options.getString('question')){const sort=i.options.getString('sort')??'newest';if(sort==='upvotes')this.admin(c);const rows=await this.repo.archive(c.guildId,'ama',c.userId,Boolean(c.manage),'',sort,(i.options.getInteger('page')??1)-1);await i.editReply({content:'',files:await notice(COMMUNITY_TITLES[kind],rows.length?rows.map(x=>`${x.status} · ${x.text.slice(0,70)}`).join('\n'):'No matching posts yet.'),components:rows.length?[new ActionRowBuilder<StringSelectMenuBuilder>().addComponents(new StringSelectMenuBuilder().setCustomId('community:archive:'+c.userId).setPlaceholder('Open a post').addOptions(rows.map(x=>({label:x.text.slice(0,100),value:x.id,description:x.status}))))]:[],allowedMentions:{parse:[]}});return;}
  const o:CommunityStart={kind,text:kind==='poll'?i.options.getString('question',true):kind==='superlatives'?i.options.getString('categories',true):kind==='ama'?i.options.getString('question',true):i.options.getString('prize',true),name:(await this.member(i.guild!,c.userId,c.channelId)).displayName};if(['poll','ama'].includes(kind))o.anonymous=i.options.getBoolean('anonymous')??false;if(kind==='poll'){o.choices=i.options.getString('choices',true);o.maxChoices=Number(await this.config.get(c.guildId,'poll.max_choices'));o.hidden=i.options.getString('results')!=='live';o.ranked=i.options.getBoolean('ranked')??false;const minutes=i.options.getInteger('minutes');if(minutes!==null)o.minutes=minutes;}if(kind==='giveaway'){this.admin(c);o.minutes=i.options.getInteger('hours',true)*60;o.winnerCount=i.options.getInteger('winners',true);o.fee=i.options.getInteger('fee')??0;o.maxFee=Number(await this.config.get(c.guildId,'giveaway.max_entry_fee'));const min=Number(await this.config.get(c.guildId,'giveaway.min_duration_minutes')),max=Number(await this.config.get(c.guildId,'giveaway.max_duration_minutes')),winners=Number(await this.config.get(c.guildId,'giveaway.max_winners'));if(o.minutes<Math.max(60,min)||o.minutes>Math.min(10080,max)||o.winnerCount>Math.min(5,winners))throw new DomainError('GIVEAWAY_LIMITS','This giveaway exceeds the configured limits.');}const result=await this.repo.start(c,o);await this.publish(i.client,result.jobId);await i.deleteReply();}
 private statusPicker(v:CommunityView){return new ActionRowBuilder<StringSelectMenuBuilder>().addComponents(new StringSelectMenuBuilder().setCustomId('community:status_pick:'+v.id).setPlaceholder('Suggestion status').addOptions(SUGGESTION_STATUSES.map(x=>({label:x,value:x}))));}
 async payload(v:CommunityView,client?:Client,fixtureAvatars:Record<string,string>={}){const avatars={...fixtureAvatars};if(client){const ids=new Set<string>([...(v.kind==='superlatives'?v.categories.flatMap(c=>c.winner?[c.winner.id]:c.finalists.map(m=>m.id)):[]),...(v.winners??[]).map(m=>m.id),...(!v.anonymous&&v.submitterName&&v.ownerId&&v.status!=='DECLINED'?[v.ownerId]:[])]);await Promise.all([...ids].map(async id=>{const art=await memberArt(client,v.guildId,id);if(art)avatars[id]=art.avatarData;}));}const buttons:ButtonBuilder[]=[];if(v.state==='OPEN'){if(v.kind==='poll'||v.kind==='suggest')buttons.push(this.button(v,'vote','Vote'));if(v.kind==='poll')buttons.push(this.button(v,'close','Close Poll'));if(v.kind==='superlatives')buttons.push(this.button(v,v.phase==='nominations'?'nominate':'seasonvote',v.phase==='nominations'?'Nominate':'Vote'));if(v.kind==='giveaway')buttons.push(this.button(v,'enter',v.fee==='0'?'Enter Giveaway':'Enter · '+v.fee+' Ottomans'));if(v.kind==='ama')buttons.push(this.button(v,'upvote','Upvote'),this.button(v,'answer','Answer'),this.button(v,'decline','Decline'));if(v.kind==='suggest')buttons.push(this.button(v,'status','Update Status'));}if(v.kind==='giveaway'&&v.status==='FULFILLMENT_PENDING')buttons.push(this.button(v,'fulfill','Mark Reward Fulfilled'));buttons.push(this.button(v,'details','Details'));const rows:Row[]=[];for(let n=0;n<buttons.length;n+=5)rows.push(new ActionRowBuilder<ButtonBuilder>().addComponents(...buttons.slice(n,n+5)));const filename='community-'+createHash('sha256').update(v.id).digest('hex').slice(0,24)+'.png',svg=renderCommunity(v,avatars);return wideDisplay([{name:filename,data:await rasterizeSvg(svg),width:1200,height:Number(/<svg[^>]*height="([\d.]+)"/.exec(svg)?.[1]??0),description:(COMMUNITY_TITLES[v.kind]+' · '+v.title).slice(0,1024)}],rows as ActionRowBuilder<ButtonBuilder>[],v.expiresAt&&v.state==='OPEN'?`Closes <t:${Math.floor(v.expiresAt.getTime()/1000)}:R>.`:undefined);}

 async publish(client:Client,jobId:string){const p=await this.repo.deliveryJob(jobId);await this.enabled(p.guildId);const v=await this.repo.publicView(p.sessionId);if(v.messageId){await this.refresh(client,v.id);return;}const channel=await client.channels.fetch(p.channelId);if(!channel?.isSendable()||!('messages'in channel))throw new Error('Community destination unavailable.');const marker='community:'+v.id,messageId=await new DeliveryEngine(this.repo.delivery((await this.repo.initialPublication(v.id)).id)).deliver(marker,{find:async marker=>{const messages=await channel.messages.fetch({limit:100});return messages.find(m=>m.author.id===client.user?.id&&(m.embeds.some(e=>e.footer?.text===marker)||m.attachments?.some(a=>a.name==='community-'+createHash('sha256').update(v.id).digest('hex').slice(0,24)+'.png')))?.id??null;},send:async()=>{const message=await channel.send(createDisplay(await this.payload(await this.repo.publicView(p.sessionId),client)));return message.id;}});await this.repo.linkMessage(p.sessionId,p.guildId,messageId);}
 async refresh(client:Client,id:string){const before=this.refreshes.get(id)??Promise.resolve(),current=before.catch(()=>{}).then(async()=>{const v=await this.repo.publicView(id);await this.enabled(v.guildId);if(!v.messageId)return;const {version,...visible}=v,signature=JSON.stringify(visible);if(this.published.get(id)===signature)return;const channel=await client.channels.fetch(v.channelId);if(!channel?.isTextBased()||!('messages'in channel))throw new Error('Community channel unavailable.');const message=await channel.messages.fetch(v.messageId);if(message.author.id!==client.user?.id)throw new Error('Community message author mismatch.');await message.edit(await this.payload(v,client));this.published.delete(id);this.published.set(id,signature);if(this.published.size>256)this.published.delete(this.published.keys().next().value!);});this.refreshes.set(id,current);try{await current;}finally{if(this.refreshes.get(id)===current)this.refreshes.delete(id);}}
 async advance(client:Client,guildId:string,id:string,round:number){await this.enabled(guildId);await this.repo.advance(guildId,id,round);await this.refresh(client,id);}
 async ensureSuggestionPanel(client:Client,guildId:string){const channelId=await this.config.get(guildId,'channels.suggestions_channel');if(typeof channelId!=='string'||!channelId)return;const saved=await this.repo.suggestionPanel(guildId),channel=await client.channels.fetch(channelId);if(!channel?.isTextBased()||!('send'in channel))throw new Error('Suggestions channel unavailable.');if(saved?.channelId===channelId&&saved.messageId){const existing=await channel.messages.fetch(saved.messageId).catch(()=>null);if(existing?.author.id===client.user?.id)return;}
  const image=await notice('EAJ Suggestions','Share an idea for Chairs. Members can support or oppose it; staff will keep its status current.');const message=await channel.send({content:'',embeds:[new EmbedBuilder().setColor(0xA469E2).setImage('attachment://community-window.png')],files:image,components:[new ActionRowBuilder<ButtonBuilder>().addComponents(new ButtonBuilder().setCustomId('community:suggest_submit:panel').setLabel('Submit Suggestion').setStyle(ButtonStyle.Primary))],allowedMentions:{parse:[]}});await this.repo.rememberSuggestionPanel(guildId,channelId,message.id);}
 async sweep(client:Client){if(this.sweeping)return;this.sweeping=true;try{for(const guild of (client.guilds?.cache??new Map()).values()){if(await this.config.get(guild.id,'features.community')===true)await this.ensureSuggestionPanel(client,guild.id);}for(const s of await this.repo.active()){if(await this.config.get(s.guildId,'features.community')!==true)continue;if(s.expiresAt&&s.expiresAt<=new Date())await this.advance(client,s.guildId,s.id,(s.data as {round:number}).round);}}finally{this.sweeping=false;}}
}
