import {PermissionFlagsBits,ActionRowBuilder,AttachmentBuilder,ButtonBuilder,ButtonStyle,EmbedBuilder,StringSelectMenuBuilder,UserSelectMenuBuilder,type Client,type Guild,type ButtonInteraction,type ChatInputCommandInteraction,type StringSelectMenuInteraction,type UserSelectMenuInteraction} from 'discord.js';
import {DeliveryEngine,DomainError,PermissionEngine,type CapabilityMap,type ConfigService} from '../../../../packages/core/src/index.js';
import {CAPABILITY_MATRIX} from '../../../../packages/contracts/src/generated/capabilities.js';
import {PrismaCrimeRepository,type CrimeContext,type CrimeView} from '../../../../packages/features-crime/src/prisma-repository.js';
import {DEFAULT_CRIME_POLICY,validateCrimePolicy,isCrimeBailRequest,type CrimePolicy} from '../../../../packages/features-crime/src/domain.js';
import {renderCrime,crimeDescription,CRIME_RULES} from '../../../../packages/features-crime/src/render.js';
import {rasterizeSvg} from '../../../../packages/renderer/src/raster.js';
type Interaction=ChatInputCommandInteraction|ButtonInteraction|StringSelectMenuInteraction|UserSelectMenuInteraction;
export const CRIME_POLICY_SETTINGS:Record<keyof CrimePolicy,string>={successBp:'success_bp',theftMinBp:'theft_min_bp',theftMaxBp:'theft_max_bp',fightBackBp:'fight_back_bp',catchBaseBp:'catch_base_bp',reportBp:'report_bp',catchCapBp:'catch_cap_bp',fightBackRiskBp:'fight_back_risk_bp',attemptHeat:'attempt_heat',successHeat:'success_heat',decayPerHour:'decay_per_hour',bailBase:'bail_base',bailPerHeat:'bail_per_heat',bailRandomMax:'bail_random_max'};
export class DiscordCrimeCoordinator {
 private readonly refreshes=new Map<string,Promise<void>>();
 private sweeping=false;
 constructor(private readonly repo:PrismaCrimeRepository,private readonly config:ConfigService,private readonly eligible:(g:string,u:string)=>Promise<boolean>){}
 async policy(guildId:string):Promise<CrimePolicy>{const p={...DEFAULT_CRIME_POLICY};for(const key of Object.keys(CRIME_POLICY_SETTINGS) as (keyof CrimePolicy)[])p[key]=Number(await this.config.get(guildId,'crime.'+CRIME_POLICY_SETTINGS[key]));return validateCrimePolicy(p);}
 private async member(guild:Guild,userId:string,channelId:string){const m=await guild.members.fetch({user:userId,force:true});if(m.user.bot||m.isCommunicationDisabled()||!m.permissionsIn(channelId).has(PermissionFlagsBits.ViewChannel|PermissionFlagsBits.SendMessages)||!await this.eligible(guild.id,userId))throw new DomainError('CRIME_RESTRICTED','Crime controls require an eligible member with access to this channel.');return m;}
 private async guard(i:Interaction,bail:boolean){if(!i.guildId||!i.guild||!i.channelId)throw new DomainError('SERVER_ONLY','Use Crime in the server.');if(!bail&&await this.config.get(i.guildId,'features.crime')!==true)throw new DomainError('CRIME_DISABLED','Crime is not enabled yet.');if(i.channelId!==await this.config.get(i.guildId,'channels.bot_channel'))throw new DomainError('CRIME_CHANNEL','Use Crime in the configured bot channel.');const capabilities:CapabilityMap=CAPABILITY_MATRIX.capabilities;if(!new PermissionEngine({'crime.use':capabilities['crime.use']??[]}).can('member','crime.use'))throw new DomainError('CRIME_RESTRICTED','Crime controls are unavailable.');await this.member(i.guild,i.user.id,i.channelId);if(!bail&&await this.repo.isJailed(i.guildId,i.user.id))throw new DomainError('CRIME_JAILED','You are in crime jail. You may pay bail, or another member can pay it for you.');}
 async handle(i:Interaction){try{const parts=i.isChatInputCommand()?[]:i.customId.split(':'),action=i.isChatInputCommand()?i.options.getSubcommand():parts[1],bail=isCrimeBailRequest(i.isChatInputCommand()?i.commandName:undefined,i.isChatInputCommand()?action:undefined,i.isChatInputCommand()?undefined:i.customId);await this.guard(i,bail);const c:CrimeContext={guildId:i.guildId!,channelId:i.channelId!,userId:i.user.id,requestKey:i.id};
  if(i.isChatInputCommand()&&action==='rob'){
   const target=i.options.getUser('member',true);if(target.id===i.user.id)throw new DomainError('CRIME_TARGET','Choose another member.');await i.deferReply({ephemeral:true});const [robber,victim]=await Promise.all([this.member(i.guild!,i.user.id,c.channelId),this.member(i.guild!,target.id,c.channelId)]),person=(m:typeof robber)=>({userId:m.id,name:m.displayName,avatarUrl:m.displayAvatarURL({size:128,extension:'png'})});const result=await this.repo.rob(c,person(robber),person(victim),await this.policy(c.guildId));await this.deliver(i.client,result.jobId);await i.editReply({content:'The robbery incident has been posted in this channel.'});return;
  }
  if(i.isChatInputCommand()&&action==='wanted'){await i.deferReply({ephemeral:true});const state=await this.repo.wanted(c.guildId,c.userId,await this.policy(c.guildId),i.id);await i.editReply({content:`Wanted: **${state.level.replaceAll('_',' ')}**\nHeat: ${state.heat}/100 · Successful robberies: ${state.successfulRobs} · Failed attempts: ${state.failedRobs}\nWanted decays automatically; arrest resets it to Clean.`,allowedMentions:{parse:[]}});return;}
  if(i.isChatInputCommand()&&action==='bail'){await i.reply({ephemeral:true,content:'Choose a crime-jailed member. The exact bail quote requires confirmation before payment.',components:[new ActionRowBuilder<UserSelectMenuBuilder>().addComponents(new UserSelectMenuBuilder().setCustomId('crime:bailpick:'+i.user.id).setPlaceholder('Choose a member for bail').setMinValues(1).setMaxValues(1)),new ActionRowBuilder<ButtonBuilder>().addComponents(new ButtonBuilder().setCustomId('crime:bailself:'+i.user.id).setLabel('My Bail').setStyle(ButtonStyle.Secondary))],allowedMentions:{parse:[]}});return;}
  if((i.isUserSelectMenu()&&action==='bailpick')||(i.isButton()&&action==='bailself')){if(parts[2]!==i.user.id)throw new DomainError('CRIME_OWNER','Open your own bail selector.');await i.deferReply({ephemeral:true});const quote=await this.repo.bailQuote(c.guildId,i.isUserSelectMenu()?i.values[0]!:i.user.id);await i.editReply({content:`Pay **${quote.amount} Ottomans** to release <@${quote.userId}> from crime jail? Any moderation Hotseat sentence remains active.`,components:[new ActionRowBuilder<ButtonBuilder>().addComponents(new ButtonBuilder().setCustomId(`crime:bailconfirm:${quote.sentenceId}:${i.user.id}:${quote.amount}`).setLabel('Confirm Bail Payment').setStyle(ButtonStyle.Primary))],allowedMentions:{parse:[]}});return;}
  if(i.isButton()&&action==='bailconfirm'){if(parts[3]!==i.user.id)throw new DomainError('CRIME_OWNER','Open your own bail quote.');await i.deferReply({ephemeral:true});const paid=await this.repo.bail(c,parts[2]!,parts[4]!);await i.editReply({content:`Paid ${paid.paid} Ottomans. <@${paid.userId}> is released from crime jail. Any moderation Hotseat remains active.`,components:[],allowedMentions:{parse:[]}});try{await this.refresh(i.client,paid.sessionId);}catch{/* Release is saved; scheduler/public refresh may retry. */}return;}
  if(i.isChatInputCommand()&&action==='911'||i.isButton()&&action==='reports'){
   if(i.isButton()&&parts[2]!==i.user.id)throw new DomainError('CRIME_OWNER','Open your own witness selector.');const page=i.isButton()?Number(parts[3]):0;if(!Number.isInteger(page)||page<0)throw new DomainError('CRIME_CONTROL','Open the witness selector again.');await i.deferReply({ephemeral:true});const rows=(await this.repo.active(c.guildId,c.channelId)).filter(s=>s.expiresAt&&s.expiresAt>new Date()),eligible=[];for(const row of rows){const v=await this.repo.publicView(row.id);if(v.success&&![v.robber.userId,v.victim.userId].includes(c.userId))eligible.push(v);}const slice=eligible.slice(page*25,page*25+25);if(!slice.length){await i.editReply({content:'There are no eligible incidents in the current witness window.'});return;}const components:(ActionRowBuilder<StringSelectMenuBuilder>|ActionRowBuilder<ButtonBuilder>)[]=[new ActionRowBuilder<StringSelectMenuBuilder>().addComponents(new StringSelectMenuBuilder().setCustomId('crime:reportpick:'+i.user.id).setPlaceholder('Choose the incident you witnessed').addOptions(slice.map(v=>({label:(v.robber.name+' → '+v.victim.name).slice(0,100),description:v.stolen+' Ottomans · '+v.id.slice(0,8),value:v.id}))))];if(eligible.length>(page+1)*25)components.push(new ActionRowBuilder<ButtonBuilder>().addComponents(new ButtonBuilder().setCustomId(`crime:reports:${i.user.id}:${page+1}`).setLabel('More incidents').setStyle(ButtonStyle.Secondary)));await i.editReply({content:'A witness may report once per incident. Victims and robbers cannot report their own incident.',components,allowedMentions:{parse:[]}});return;
  }
  let id=parts[2];if(i.isStringSelectMenu()&&action==='reportpick'){if(parts[2]!==i.user.id)throw new DomainError('CRIME_OWNER','Open your own witness selector.');id=i.values[0];}if(!id)throw new DomainError('CRIME_CONTROL','Use the current incident controls.');const v=await this.repo.publicView(id);if(v.guildId!==c.guildId||v.channelId!==c.channelId)throw new DomainError('CRIME_MISSING','Use this incident in its original channel.');if(i.isButton()&&action==='rules'){await i.reply({ephemeral:true,content:CRIME_RULES});return;}await i.deferReply({ephemeral:true});if(i.isButton()&&action==='fightback'){const result=await this.repo.fightBack(c,id);await i.editReply({content:result.result==='won'?'You recovered all stolen Ottomans. The robber’s catch risk increased.':'Fight Back failed. You pay no additional penalty.'});}else if(i.isButton()&&action==='report'||i.isStringSelectMenu()&&action==='reportpick'){await this.repo.report(c,id);await i.editReply({content:'Your witness report is saved. Catch risk is capped.'});}else throw new DomainError('CRIME_CONTROL','Use the current incident controls.');try{await this.refresh(i.client,id);}catch{await i.followUp({ephemeral:true,content:'Your action is saved. The public incident refresh is pending.'});}
 }catch(error){const content=error instanceof DomainError?error.message:'The crime action could not be displayed. A committed incident or payment remains saved; check its state before retrying.';if(i.replied)await i.followUp({ephemeral:true,content});else if(i.deferred)await i.editReply({content});else await i.reply({ephemeral:true,content});}}
 private async avatarData(url?:string){if(!url)return;try{const parsed=new URL(url);if(parsed.protocol!=='https:'||!['cdn.discordapp.com','media.discordapp.net'].includes(parsed.hostname))return;const response=await fetch(parsed,{signal:AbortSignal.timeout(3000)});if(!response.ok)return;const buffer=Buffer.from(await response.arrayBuffer());if(buffer.length>1024*1024)return;const type=response.headers.get('content-type')?.split(';')[0];if(!['image/png','image/jpeg','image/webp'].includes(type??''))return;return`data:${type};base64,`+buffer.toString('base64');}catch{return;}}
 async deliver(client:Client,jobId:string){const p=await this.repo.publication(jobId),channel=await client.channels.fetch(p.channelId);if(!channel?.isSendable()||!('messages' in channel))throw new Error('Crime publication channel unavailable.');const marker='crime:incident:'+p.sessionId,messageId=await new DeliveryEngine(this.repo.delivery(jobId)).deliver(marker,{find:async marker=>{const messages=await channel.messages.fetch({limit:100});return messages.find(m=>m.author.id===client.user?.id&&m.embeds.some(e=>e.footer?.text===marker))?.id??null;},send:async marker=>{const payload=await this.payload(await this.repo.publicView(p.sessionId));payload.embeds[0]!.setFooter({text:marker});return(await channel.send(payload)).id;}});await this.repo.linkMessage(p.sessionId,p.guildId,messageId);return messageId;}
 async payload(v:CrimeView){const row=new ActionRowBuilder<ButtonBuilder>(),button=(action:string,label:string)=>new ButtonBuilder().setCustomId(`crime:${action}:${v.id}`).setLabel(label).setStyle(ButtonStyle.Secondary);if(v.state==='OPEN'&&v.success){row.addComponents(button('fightback','Fight Back').setDisabled(Boolean(v.fightBack)||new Date(v.fightBackEndsAt)<=new Date()),button('report','911').setDisabled(new Date(v.reportEndsAt)<=new Date()));}row.addComponents(button('rules','Rules'));const description=crimeDescription(v)+(v.state==='OPEN'?`\nFight Back ends <t:${Math.floor(new Date(v.fightBackEndsAt).getTime()/1000)}:R>; witnesses close <t:${Math.floor(new Date(v.reportEndsAt).getTime()/1000)}:R>.`:'');return{embeds:[new EmbedBuilder().setAuthor({name:'Angrier Jordan'}).setTitle(v.caught?(v.jailActive===false?'Crime Sentence Closed':'Under Arrest'):v.success?'Robbery Incident':'Robbery Attempt Failed').setDescription(description).setFooter({text:'crime:incident:'+v.id}).setColor(v.caught?0xC7A451:0x10B981).setImage('attachment://crime.png')],files:[new AttachmentBuilder(await rasterizeSvg(renderCrime(v,v.caught?await this.avatarData(v.robber.avatarUrl):undefined)),{name:'crime.png',description:crimeDescription(v).slice(0,1024)})],attachments:[],components:[row],allowedMentions:{parse:[] as never[]}};}
 async refresh(client:Client,id:string){const previous=this.refreshes.get(id)??Promise.resolve(),current=previous.catch(()=>{}).then(async()=>{const v=await this.repo.publicView(id);if(!v.messageId)return;const channel=await client.channels.fetch(v.channelId);if(!channel?.isTextBased()||!('messages' in channel))throw new Error('Crime channel unavailable.');const message=await channel.messages.fetch(v.messageId);if(message.author.id!==client.user?.id)throw new Error('Crime message owner mismatch.');await message.edit(await this.payload(v));});this.refreshes.set(id,current);try{await current;}finally{if(this.refreshes.get(id)===current)this.refreshes.delete(id);}}
 async advance(client:Client,guildId:string,id:string){await this.repo.close(guildId,id);await this.refresh(client,id);}
 async sweep(client:Client){if(this.sweeping)return;this.sweeping=true;try{const active=await this.repo.active();await this.repo.recover(g=>this.policy(g));for(const s of active)await this.refresh(client,s.id);}finally{this.sweeping=false;}}
}
