import {renderStatement} from '../../../../packages/features-economy/src/statement-render.js';
import {rasterizeSvg} from '../../../../packages/renderer/src/raster.js';
import {economyPresentation} from './economy-presentation.js';
import {DisposableCardLifecycle} from './card-lifecycle.js';
import {
  AttachmentBuilder,
  ActionRowBuilder,
  ButtonBuilder,
  ButtonStyle,
  EmbedBuilder,
  ModalBuilder,
  TextInputBuilder,
  TextInputStyle,
  type ButtonInteraction,
  type ChatInputCommandInteraction,
  type GuildMember,
  type ModalSubmitInteraction,
  type Message,
} from 'discord.js';
import type {ConfigService} from '../../../../packages/core/src/index.js';
import {DomainError} from '../../../../packages/core/src/index.js';
import {type BankTierRule,type DailyHubState,type EconomyService,type GrindActivity,type GrindOutcomeRule,type GrindPolicy,type SpinReward} from '../../../../packages/features-economy/src/index.js';
import {qualifyMessage} from '../../../../packages/features-profiles/src/domain.js';

const C={teal:0x14B8A6,gold:0xF5C542,emerald:0x22C55E,purple:0x8B5CF6,blue:0x22D3EE,red:0xEF4444,navy:0x0F1E3A};
const fmt=(n:bigint)=>n.toLocaleString('en-US');
const time=(d:Date)=>`<t:${Math.floor(d.getTime()/1000)}:R>`;
const asNumber=(v:unknown,fallback:number)=>typeof v==='number'&&Number.isFinite(v)?v:fallback;
const asBig=(v:unknown,fallback=0n)=>typeof v==='number'&&Number.isSafeInteger(v)?BigInt(v):typeof v==='string'&&/^\d+$/.test(v)?BigInt(v):fallback;
const range=(center:bigint,spread:bigint,min:bigint,max:bigint):[bigint,bigint]=>[center-spread<min?min:center-spread,center+spread>max?max:center+spread];

export class DiscordEconomyCoordinator {
  private readonly disposable=new DisposableCardLifecycle();
  private readonly adaptiveApplication:(guildId:string)=>Promise<boolean>;
  constructor(private readonly service:EconomyService,private readonly config:ConfigService,adaptiveApplication:boolean|((guildId:string)=>Promise<boolean>)=false){this.adaptiveApplication=typeof adaptiveApplication==='function'?adaptiveApplication:async()=>adaptiveApplication;}

  async handleMemberAdd(member:GuildMember){await this.service.bootstrapFromBenchmark(member.guild.id,member.id,'member-add');}
  async handleActivityMessage(message:Message){
    if(!message.guildId||message.author.bot||await this.config.get(message.guildId,'features.activity')!==true)return;
    const exclusions=[['channels.bot_channel','activity.exclude_bot_channel'],['channels.games_channel','activity.exclude_games_channel'],['channels.staff_log','activity.exclude_staff_channel']] as const;
    const excluded=await Promise.all(exclusions.map(async([channel,toggle])=>await this.config.get(message.guildId!,toggle)===true?this.config.get(message.guildId!,channel):null));
    excluded.push(await this.config.get(message.guildId,'channels.hotseat_channel'));
    if(!qualifyMessage({content:message.content,bot:message.author.bot,command:/^\s*[!/]/.test(message.content),excludedChannel:excluded.includes(message.channelId)}))return;
    const policy=await this.service.runtimePolicy(message.guildId,await this.adaptiveApplication(message.guildId)),rewards=range(policy.chatWindowReward,5n,15n,25n);await this.service.awardQualifiedChat({guildId:message.guildId,userId:message.author.id,idempotencyKey:`activity:chat:${message.id}`,minReward:rewards[0],maxReward:rewards[1],dailyCap:policy.chatDailyCap});
  }
  async handleQualifiedVoiceAccruals(guildId:string,at:Date,accruals:readonly {userId:string;seconds:number}[]){const policy=await this.service.runtimePolicy(guildId,await this.adaptiveApplication(guildId)),full=range(policy.voiceEarlyReward,20n,80n,120n),half=range(policy.voiceThirdHourReward,10n,40n,60n);for(const accrual of accruals)await this.service.awardQualifiedVoice({guildId,userId:accrual.userId,idempotencyKey:`activity:voice:${accrual.userId}:${at.toISOString()}`,qualifiedSeconds:accrual.seconds,fullRange:full,halfRange:half});}

  async handleCommand(i:ChatInputCommandInteraction){if(!i.guildId||!i.guild){await this.present(i,{ephemeral:true,content:'This command is only available in the server.'});return;}try{await i.deferReply({ephemeral:['daily','statement','bank'].includes(i.commandName)});await this.ensureStarter(i.guildId,i.user.id,i.id);switch(i.commandName){case'daily':return await this.daily(i);case'weekly':return await this.weekly(i);case'work':return await this.grind(i,'work');case'fish':return await this.grind(i,'fish');case'dig':return await this.grind(i,'dig');case'scavenge':return await this.grind(i,'scavenge');case'statement':return await this.statement(i);case'inventory':return await this.inventory(i);case'bank':return await this.bank(i);case'transfer':return await this.transfer(i);default:await this.present(i,{ephemeral:true,content:'That economy command is not implemented in this runtime yet.'});}}catch(e){await this.replyError(i,e);}}

  async handleButton(i:ButtonInteraction){if(!i.guildId){await this.present(i,{ephemeral:true,content:'This control is only available in the server.'});return;}try{if(i.customId.startsWith('economy:statement:')){const parts=i.customId.split(':'),page=Number(parts[3]);if(parts[2]!==i.user.id||!Number.isInteger(page)||page<0||page>2)throw new DomainError('STATEMENT_CONTROL','Open your own /statement to view its pages.');await i.deferUpdate();return await this.statement(i,page);}if(i.customId.startsWith('economy:daily:')||i.customId==='economy:bank:upgrade'){if(!i.deferred)await i.deferUpdate();}await this.ensureStarter(i.guildId,i.user.id,i.id);if(i.customId.startsWith('economy:daily:'))return await this.dailyButton(i);if(i.customId==='economy:bank:deposit'||i.customId==='economy:bank:withdraw')return await this.bankAmountModal(i);if(i.customId==='economy:bank:upgrade')return await this.bankUpgrade(i);await this.present(i,{ephemeral:true,content:'That economy control is no longer active.'});}catch(e){await this.replyError(i,e);}}
  async handleModal(i:ModalSubmitInteraction){if(!i.guildId){await this.present(i,{ephemeral:true,content:'This control is only available in the server.'});return;}try{await i.deferReply({ephemeral:true});await this.ensureStarter(i.guildId,i.user.id,i.id);if(i.customId.startsWith('economy:bank_modal:'))return await this.bankAmountSubmit(i);await this.present(i,{ephemeral:true,content:'That economy form is no longer active.'});}catch(e){await this.replyError(i,e);}}

  async handleInterestJob(payload:unknown){if(!payload||typeof payload!=='object')return;const p=payload as Record<string,unknown>;if(typeof p.guildId!=='string'||typeof p.cycleKey!=='string')return;const policy=await this.service.runtimePolicy(p.guildId,await this.adaptiveApplication(p.guildId));const result=await this.service.applyTier5Interest({guildId:p.guildId,cycleKey:p.cycleKey,interestBps:Number(policy.tier5WeeklyRateBps),capBps:Number(policy.tier5WeeklyCapBps)});await this.service.scheduleNextBankInterest(p.guildId);console.log(`Tier 5 bank interest ${p.guildId}/${p.cycleKey}: members=${result.members} credited=${result.credited} duplicates=${result.duplicates}`);}
  async reconcileInterestSchedule(guildId:string){return this.service.scheduleNextBankInterest(guildId);}
  async reconcileEconomySnapshotSchedule(guildId:string){return this.service.scheduleNextEconomySnapshot(guildId);}
  async reconcileEconomyPolicySchedule(guildId:string){return this.service.scheduleNextEconomyPolicy(guildId);}
  async handleSnapshotJob(payload:unknown){if(!payload||typeof payload!=='object')throw new Error('Invalid economy snapshot job.');const p=payload as Record<string,unknown>;if(typeof p.guildId!=='string'||typeof p.cycleKey!=='string')throw new Error('Invalid economy snapshot payload.');await this.service.captureEconomySnapshot(p.guildId,p.cycleKey);}
  async handlePolicyJob(payload:unknown){if(!payload||typeof payload!=='object')throw new Error('Invalid economy policy job.');const p=payload as Record<string,unknown>;if(typeof p.guildId!=='string'||typeof p.cycleKey!=='string')throw new Error('Invalid economy policy payload.');const result=await this.service.publishShadowEconomyPolicy(p.guildId,p.cycleKey);if(!result.frozen)await this.service.activateShadowPolicy(p.guildId,p.cycleKey,result.adjustments,await this.adaptiveApplication(p.guildId));}
  async handleStreakInstallmentJob(payload:unknown){if(!payload||typeof payload!=='object')throw new Error('Invalid streak installment job.');const id=(payload as Record<string,unknown>).installmentId;if(typeof id!=='string')throw new Error('Invalid streak installment payload.');await this.service.settleStreakInstallment(id);}

  private async ensureStarter(g:string,u:string,request:string){return this.service.bootstrapFromBenchmark(g,u,request);}
  private async resetHour(g:string){return asNumber(await this.config.get(g,'server.daily_reset_hour'),4);}
  private async weeklyReset(g:string){return{day:String(await this.config.get(g,'server.weekly_reset_day')??'MONDAY'),hour:asNumber(await this.config.get(g,'server.weekly_reset_hour'),4)};}
  private async bankTiers(g:string):Promise<BankTierRule[]>{const raw=await this.config.get(g,'economy.bank_tiers');if(!Array.isArray(raw))throw new DomainError('INVALID_BANK_TIERS','Bank tier configuration is invalid.');return raw.map((v:any)=>({tier:Number(v?.tier),cap:v?.cap===null?null:asBig(v?.cap),upgradeCost:asBig(v?.upgrade_cost)}));}
  private async milestones(g:string){const raw=await this.config.get(g,'economy.daily_milestones');const out:Record<number,bigint>={};if(raw&&typeof raw==='object'&&!Array.isArray(raw))for(const [k,v] of Object.entries(raw as Record<string,unknown>)){const n=Number(k);if(Number.isInteger(n)&&n>0)out[n]=asBig(v);}return out;}
  private async spinTable(g:string):Promise<SpinReward[]>{const raw=await this.config.get(g,'economy.daily_spin_table');if(!Array.isArray(raw))throw new DomainError('INVALID_SPIN_REWARD','Daily Spin table is invalid.');return raw.map((v:any)=>({kind:v?.kind==='item'?'item':'ottomans',weight:Number(v?.weight??0),...(v?.amount!==undefined?{amount:asBig(v.amount)}:{}),...(typeof v?.item_id==='string'?{itemId:v.item_id}:{}),...(v?.quantity!==undefined?{quantity:Number(v.quantity)}:{}),...(typeof v?.label==='string'?{label:v.label}:{})}));}
  private async guardedSpinTable(g:string):Promise<SpinReward[]>{return this.spinTable(g);}
  private async grindPolicy(g:string,activity:GrindActivity):Promise<GrindPolicy>{const throttle=asNumber(await this.config.get(g,'economy.grind_technical_throttle_ms'),1500);const raw=await this.config.get(g,'economy.grind_tables');const table=raw&&typeof raw==='object'&&!Array.isArray(raw)?(raw as Record<string,unknown>)[activity]:undefined;if(!Array.isArray(table))throw new DomainError('INVALID_GRIND_POLICY',`/${activity} outcome table is missing.`);const outcomes:GrindOutcomeRule[]=table.map((v:any)=>({outcome:String(v?.outcome??'zero') as GrindOutcomeRule['outcome'],weight:Number(v?.weight??0),...(v?.min!==undefined?{minOttomans:asBig(v.min)}:{}),...(v?.max!==undefined?{maxOttomans:asBig(v.max)}:{}),...(typeof v?.item_id==='string'?{itemId:v.item_id}:{}),...(v?.quantity!==undefined?{quantity:Number(v.quantity)}:{}),...(v?.tool_damage!==undefined?{toolDamage:Number(v.tool_damage)}:{})}));return{technicalThrottleMs:throttle,outcomes};}
  private async guardedGrindPolicy(g:string,activity:GrindActivity):Promise<GrindPolicy>{return this.grindPolicy(g,activity);}

  private dailyRow(h:DailyHubState){return new ActionRowBuilder<ButtonBuilder>().addComponents(new ButtonBuilder().setCustomId('economy:daily:claim').setLabel('Claim Daily').setStyle(ButtonStyle.Success).setDisabled(!h.dailyReady),new ButtonBuilder().setCustomId('economy:daily:spin').setLabel('Daily Spin').setStyle(ButtonStyle.Primary).setDisabled(!h.spinReady),new ButtonBuilder().setCustomId('economy:daily:fortune').setLabel('Fortune').setStyle(ButtonStyle.Secondary).setDisabled(!h.fortuneReady));}
  private async dailyPayload(g:string,u:string,notice?:string){
    const hub=await this.service.dailyHub(g,u,await this.resetHour(g));
    const reset=new Intl.DateTimeFormat('en-US',{timeZone:'America/Denver',month:'short',day:'numeric',hour:'numeric',minute:'2-digit',timeZoneName:'short'}).format(hub.resetAt);
    const sections=[{name:'Claim Daily',value:hub.dailyReady?'Your daily Ottomans await.':'Daily reward already claimed.',state:hub.dailyReady?'READY':'USED',accent:C.emerald},{name:'Daily Spin',value:hub.spinReady?'One spin. A new reward.':'Spin reward already claimed.',state:hub.spinReady?'READY':'USED',accent:C.gold},{name:'Fortune',value:hub.fortuneReady?'A word from the Chairs.':'Fortune already revealed.',state:hub.fortuneReady?'READY':'USED',accent:C.purple}];
    const payload=await economyPresentation({title:'Daily Hub',description:notice??'Three daily rituals. One seat in the lounge.',sections,footer:'Streak '+hub.streak+' · Resets '+reset,fields:sections.map(s=>({name:s.name,value:s.state,inline:true})).concat([{name:'Next reset',value:time(hub.resetAt),inline:false}])});
    return{hub,...payload,components:[this.dailyRow(hub)]};
  }
  private async daily(i:ChatInputCommandInteraction){const {hub,...payload}=await this.dailyPayload(i.guildId!,i.user.id);await i.editReply(payload);}
  private async dailyButton(i:ButtonInteraction){const action=i.customId.split(':')[2];const g=i.guildId!,policy=await this.service.runtimePolicy(g,await this.adaptiveApplication(g)),rewards=range(policy.dailyClaim,50n,200n,300n);const resetHour=await this.resetHour(g);let notice='';if(action==='claim'){const r=await this.service.claimDaily({guildId:g,userId:i.user.id,idempotencyKey:i.id,minReward:rewards[0],maxReward:rewards[1],milestones:await this.milestones(g),resetHour});notice=r.status==='applied'?`**Claimed ${fmt(r.reward)} Ottomans.**${r.bonus?` Milestone bonus: ${fmt(r.bonus)}.`:''} Streak: ${r.streak}.`:'Claim Daily is already used for this cycle.';}else if(action==='spin'){const r=await this.service.spinDaily({guildId:g,userId:i.user.id,idempotencyKey:i.id,table:await this.guardedSpinTable(g),resetHour});notice=r.status==='applied'?`**Daily Spin:** ${r.reward?.label??(r.reward?.kind==='ottomans'?`${fmt(r.reward.amount??0n)} Ottomans`:'Item reward')}.`:'Daily Spin is already used for this cycle.';}else if(action==='fortune'){const r=await this.service.fortuneDaily({guildId:g,userId:i.user.id,idempotencyKey:i.id,resetHour});notice=r.status==='applied'?`**Fortune:** ${r.fortune?.text??'The chair spirits declined to elaborate.'}`:'Fortune is already used for this cycle.';}else throw new DomainError('UNKNOWN_DAILY_ACTION','That daily action no longer exists.');const {hub,...payload}=await this.dailyPayload(g,i.user.id,notice);await i.editReply(payload);}

  private async weekly(i:ChatInputCommandInteraction){const g=i.guildId!,reset=await this.weeklyReset(g),policy=await this.service.runtimePolicy(g,await this.adaptiveApplication(g)),rewards=range(policy.weeklyClaim,250n,1000n,1500n);const r=await this.service.weekly({guildId:g,userId:i.user.id,idempotencyKey:i.id,minReward:rewards[0],maxReward:rewards[1],resetDay:reset.day,resetHour:reset.hour});if(r.status==='applied')await this.present(i,{content:`<@${i.user.id}> claimed the weekly reward: **${fmt(r.reward)} Ottomans**.`});else await this.present(i,{ephemeral:true,content:'You already claimed this week’s reward.'});}
  private async grind(i:ChatInputCommandInteraction,activity:GrindActivity){const r=await this.service.grind({guildId:i.guildId!,userId:i.user.id,activity,idempotencyKey:i.id,policy:await this.guardedGrindPolicy(i.guildId!,activity)});if(r.status==='throttled'){await this.present(i,{ephemeral:true,content:'Angrier Jordan saw that double-click. Try again in a moment.'});return;}if(r.status==='duplicate'){await this.present(i,{ephemeral:true,content:'That result was already processed.'});return;}const e=r.event!;const finds=await Promise.all(e.itemGrants.map(async x=>{const item=await this.service.inventory(i.guildId!,i.user.id).then(all=>all.find(y=>y.itemId===x.itemId));return `${x.quantity}× ${item?.item?.name??x.itemId}`;}));const reward=e.ottomansDelta>0n?`+${fmt(e.ottomansDelta)} Ottomans`:e.ottomansDelta<0n?`−${fmt(-e.ottomansDelta)} Ottomans`:'No Ottomans';const tool=e.toolDamage>0&&r.tool?`${r.tool.durability}/${r.tool.maxDurability}${r.fallbackTool?` · Switched to ${r.fallbackTool.catalogItemId}`:''}`:'No wear';const accent=activity==='work'?C.gold:activity==='fish'?C.blue:activity==='dig'?C.emerald:C.purple;const sent=await this.present(i,{imagePrimary:true,embeds:[new EmbedBuilder().setColor(accent).setTitle(`/${activity}`).setDescription(`${i.member?.user?.username??i.user.username} · ${reward}${finds.length?' · '+finds.join(', '):''} · Tool ${tool}`).setFooter({text:`Outcome: ${e.outcome.replace(/_/g,' ')}`})],sections:[{name:'Ottomans',value:reward,accent},{name:'Finds',value:finds.join(', ')||'No item found',accent:C.gold},{name:'Tool durability',value:tool,accent:C.teal}]});if(sent&&i.channelId)await this.disposable.track(`${i.guildId}:${i.channelId}:${i.user.id}`,sent);}

  private async statement(i:ChatInputCommandInteraction|ButtonInteraction,page=0){const full=await this.service.statement(i.guildId!,i.user.id,10),pages=Math.max(1,Math.ceil(full.entries.length/4));page=Math.min(page,pages-1);const s={...full,entries:full.entries.slice(page*4,page*4+4)},controls=pages>1?[new ActionRowBuilder<ButtonBuilder>().addComponents(new ButtonBuilder().setCustomId(`economy:statement:${i.user.id}:${Math.max(0,page-1)}`).setLabel('Previous').setStyle(ButtonStyle.Secondary).setDisabled(page===0),new ButtonBuilder().setCustomId(`economy:statement:${i.user.id}:${Math.min(pages-1,page+1)}`).setLabel('Next').setStyle(ButtonStyle.Secondary).setDisabled(page===pages-1))]:[];await i.editReply({content:null,embeds:[new EmbedBuilder().setColor(C.gold).setImage('attachment://statement.png')],files:[new AttachmentBuilder(await rasterizeSvg(renderStatement(s,page,pages)),{name:'statement.png',description:('Ottoman Statement. Wallet '+fmt(s.account.wallet)+', bank '+fmt(s.account.bank)+', liquid net worth '+fmt(s.liquidNetWorth)+'. Bank tier '+s.account.bankTier+'. Recent transactions: '+s.entries.map(e=>(e.amount>0n?'+':'')+fmt(e.amount)+' '+e.reason).join('; ')).slice(0,1024)})],attachments:[],components:controls,allowedMentions:{parse:[]}});}
  private async inventory(i:ChatInputCommandInteraction){const items=await this.service.inventory(i.guildId!,i.user.id);const lines=items.slice(0,20).map(x=>`**${x.item?.name??x.itemId}** ×${x.quantity} • ${x.item?.rarity??'Unknown'}${x.locked?' • 🔒':''}${x.item?.sellValue!==undefined?` • sell ${fmt(x.item.sellValue)}`:''}`).join('\n')||'Your inventory is empty.';const extra=items.length>20?`\n…and ${items.length-20} more stack${items.length-20===1?'':'s'}.`:'';await this.present(i,{embeds:[new EmbedBuilder().setColor(C.purple).setTitle('Inventory').setDescription((lines+extra).slice(0,3900)).setFooter({text:'Selling stays inside /inventory; there is no standalone /sell.'})]});}

  private async bank(i:ChatInputCommandInteraction|ButtonInteraction|ModalSubmitInteraction,notice?:string){const tiers=await this.bankTiers(i.guildId!),a=await this.service.account(i.guildId!,i.user.id),v=this.service.bankView(a,tiers);const cap=v.rule.cap===null?'Unlimited':fmt(v.rule.cap);const next=v.nextRule?`Tier ${v.nextRule.tier} • upgrade cost ${fmt(v.rule.upgradeCost)} • current tier must be full`:'Maximum tier reached';const embed=new EmbedBuilder().setColor(C.emerald).setTitle('Ottoman Bank').setDescription([notice??'Banked Ottomans are protected from robbery. Spending automatically uses wallet first, then bank.','',`**Wallet:** ${fmt(a.wallet)}`,`**Bank:** ${fmt(a.bank)} / ${cap}`,`**Tier:** ${a.bankTier} of 5`,`**Next:** ${next}`].join('\n'));const row=new ActionRowBuilder<ButtonBuilder>().addComponents(new ButtonBuilder().setCustomId('economy:bank:deposit').setLabel('Deposit').setStyle(ButtonStyle.Success),new ButtonBuilder().setCustomId('economy:bank:withdraw').setLabel('Withdraw').setStyle(ButtonStyle.Primary),new ButtonBuilder().setCustomId('economy:bank:upgrade').setLabel(a.bankTier>=5?'Tier 5':'Upgrade Bank').setStyle(ButtonStyle.Secondary).setDisabled(a.bankTier>=5));const payload={embeds:[embed],components:[row],imagePrimary:true,sections:[{name:'Wallet',value:fmt(a.wallet)+' Ottomans',accent:C.gold},{name:'Bank · Tier '+a.bankTier,value:fmt(a.bank)+' / '+cap,accent:C.emerald},{name:'Next upgrade',value:next,accent:C.purple}]};if(i.isChatInputCommand())await this.present(i,payload);else if(i.isButton())await this.present(i,payload);else await this.present(i,{...payload,ephemeral:true});}
  private async bankAmountModal(i:ButtonInteraction){const kind=i.customId.endsWith('deposit')?'deposit':'withdraw';const modal=new ModalBuilder().setCustomId(`economy:bank_modal:${kind}`).setTitle(kind==='deposit'?'Deposit Ottomans':'Withdraw Ottomans');const amount=new TextInputBuilder().setCustomId('amount').setLabel('Amount').setPlaceholder('Enter a whole number').setStyle(TextInputStyle.Short).setRequired(true).setMinLength(1).setMaxLength(12);modal.addComponents(new ActionRowBuilder<TextInputBuilder>().addComponents(amount));await i.showModal(modal);}
  private async bankAmountSubmit(i:ModalSubmitInteraction){const kind=i.customId.split(':')[2],raw=i.fields.getTextInputValue('amount').trim();if(!/^\d{1,12}$/.test(raw)||BigInt(raw)<=0n)throw new DomainError('INVALID_BANK_AMOUNT','Enter a positive whole number of Ottomans.');const tiers=await this.bankTiers(i.guildId!);const amount=BigInt(raw);const a=kind==='deposit'?await this.service.deposit({guildId:i.guildId!,userId:i.user.id,amount,idempotencyKey:i.id,tiers}):await this.service.withdraw({guildId:i.guildId!,userId:i.user.id,amount,idempotencyKey:i.id});await this.present(i,{ephemeral:true,content:`${kind==='deposit'?'Deposited':'Withdrew'} **${fmt(amount)} Ottomans**. Wallet: ${fmt(a.wallet)} • Bank: ${fmt(a.bank)}.`});}
  private async bankUpgrade(i:ButtonInteraction){const before=await this.service.account(i.guildId!,i.user.id);const a=await this.service.upgradeBank({guildId:i.guildId!,userId:i.user.id,idempotencyKey:i.id,tiers:await this.bankTiers(i.guildId!)});await this.bank(i,a.bankTier===before.bankTier?'That bank upgrade was already processed.':`**Bank upgraded to Tier ${a.bankTier}.**`);}
  private async transfer(i:ChatInputCommandInteraction){const target=i.options.getUser('member',true),n=i.options.getInteger('amount',true);if(!Number.isSafeInteger(n)||n<=0)throw new DomainError('INVALID_TRANSFER','Transfer amount must be a positive whole number.');const r=await this.service.transfer({guildId:i.guildId!,fromUserId:i.user.id,toUserId:target.id,amount:BigInt(n),idempotencyKey:i.id});await this.present(i,{content:`<@${i.user.id}> sent <@${target.id}> **${fmt(BigInt(n))} Ottomans**. No transfer fee.`});}

  private async present(i:ChatInputCommandInteraction|ButtonInteraction|ModalSubmitInteraction,payload:any){
    const raw=payload.embeds?.[0]?.toJSON?.()??payload.embeds?.[0];
    const frame=await economyPresentation({title:raw?.title??'Ottoman Lounge',description:raw?.description??payload.content??'',fields:raw?.fields,footer:raw?.footer?.text,accent:raw?.color,...(payload.sections?{sections:payload.sections}:{}),imagePrimary:payload.imagePrimary});
    const output={...frame,...(payload.components?{components:payload.components}:{}),allowedMentions:{parse:[] as never[]}};
    if(i.deferred){if(payload.ephemeral&&!i.ephemeral&&i.isChatInputCommand()){await i.deleteReply();return i.followUp({...output,ephemeral:true});}return i.editReply(output);}
    if(i.isButton()&&!payload.ephemeral)return i.update(output);
    return i.reply({...output,...(payload.ephemeral?{ephemeral:true}:{})});
  }
  private async replyError(i:ChatInputCommandInteraction|ButtonInteraction|ModalSubmitInteraction,e:unknown){const content=e instanceof DomainError?e.message:'That economy action could not be completed. Angrier Jordan logged the failure.';if(i.deferred||i.replied)await i.followUp({ephemeral:true,content}).catch(()=>undefined);else await i.reply({ephemeral:true,content}).catch(()=>undefined);}
}
