import {
  ActionRowBuilder,
  ButtonBuilder,
  ButtonStyle,
  EmbedBuilder,
  ModalBuilder,
  TextInputBuilder,
  TextInputStyle,
  type ButtonInteraction,
  type ChatInputCommandInteraction,
  type GuildMember,
  type ModalSubmitInteraction,
} from 'discord.js';
import type {ConfigService} from '../../../../packages/core/src/index.js';
import {DomainError} from '../../../../packages/core/src/index.js';
import type {BankTierRule,DailyHubState,EconomyService,GrindActivity,GrindOutcomeRule,GrindPolicy,SpinReward} from '../../../../packages/features-economy/src/index.js';

const C={teal:0x14B8A6,gold:0xF5C542,emerald:0x22C55E,purple:0x8B5CF6,blue:0x22D3EE,red:0xEF4444,navy:0x0F1E3A};
const fmt=(n:bigint)=>n.toLocaleString('en-US');
const time=(d:Date)=>`<t:${Math.floor(d.getTime()/1000)}:R>`;
const asNumber=(v:unknown,fallback:number)=>typeof v==='number'&&Number.isFinite(v)?v:fallback;
const asBig=(v:unknown,fallback=0n)=>typeof v==='number'&&Number.isSafeInteger(v)?BigInt(v):typeof v==='string'&&/^\d+$/.test(v)?BigInt(v):fallback;

export class DiscordEconomyCoordinator {
  constructor(private readonly service:EconomyService,private readonly config:ConfigService){}

  async handleMemberAdd(member:GuildMember){const starter=BigInt(asNumber(await this.config.get(member.guild.id,'economy.starter_ottomans'),500));await this.service.bootstrap(member.guild.id,member.id,starter,'member-add');}

  async handleCommand(i:ChatInputCommandInteraction){if(!i.guildId||!i.guild){await i.reply({ephemeral:true,content:'This command is only available in the server.'});return;}try{await this.ensureStarter(i.guildId,i.user.id,i.id);switch(i.commandName){case'daily':return this.daily(i);case'weekly':return this.weekly(i);case'work':return this.grind(i,'work');case'fish':return this.grind(i,'fish');case'dig':return this.grind(i,'dig');case'scavenge':return this.grind(i,'scavenge');case'statement':return this.statement(i);case'inventory':return this.inventory(i);case'bank':return this.bank(i);case'transfer':return this.transfer(i);default:await i.reply({ephemeral:true,content:'That economy command is not implemented in this runtime yet.'});}}catch(e){await this.replyError(i,e);}}

  async handleButton(i:ButtonInteraction){if(!i.guildId){await i.reply({ephemeral:true,content:'This control is only available in the server.'});return;}try{await this.ensureStarter(i.guildId,i.user.id,i.id);if(i.customId.startsWith('economy:daily:'))return this.dailyButton(i);if(i.customId==='economy:bank:deposit'||i.customId==='economy:bank:withdraw')return this.bankAmountModal(i);if(i.customId==='economy:bank:upgrade')return this.bankUpgrade(i);await i.reply({ephemeral:true,content:'That economy control is no longer active.'});}catch(e){await this.replyError(i,e);}}
  async handleModal(i:ModalSubmitInteraction){if(!i.guildId){await i.reply({ephemeral:true,content:'This control is only available in the server.'});return;}try{await this.ensureStarter(i.guildId,i.user.id,i.id);if(i.customId.startsWith('economy:bank_modal:'))return this.bankAmountSubmit(i);await i.reply({ephemeral:true,content:'That economy form is no longer active.'});}catch(e){await this.replyError(i,e);}}

  async handleInterestJob(payload:unknown){if(!payload||typeof payload!=='object')return;const p=payload as Record<string,unknown>;if(typeof p.guildId!=='string'||typeof p.cycleKey!=='string')return;const bps=asNumber(await this.config.get(p.guildId,'economy.bank_tier5_interest_bps'),100);const cap=BigInt(asNumber(await this.config.get(p.guildId,'economy.bank_tier5_interest_cap'),100000));const result=await this.service.applyTier5Interest({guildId:p.guildId,cycleKey:p.cycleKey,interestBps:bps,maxPerMember:cap});await this.service.scheduleNextBankInterest(p.guildId);console.log(`Tier 5 bank interest ${p.guildId}/${p.cycleKey}: members=${result.members} credited=${result.credited} duplicates=${result.duplicates}`);}
  async reconcileInterestSchedule(guildId:string){return this.service.scheduleNextBankInterest(guildId);}

  private async ensureStarter(g:string,u:string,request:string){const starter=BigInt(asNumber(await this.config.get(g,'economy.starter_ottomans'),500));return this.service.bootstrap(g,u,starter,request);}
  private async resetHour(g:string){return asNumber(await this.config.get(g,'server.daily_reset_hour'),4);}
  private async weeklyReset(g:string){return{day:String(await this.config.get(g,'server.weekly_reset_day')??'MONDAY'),hour:asNumber(await this.config.get(g,'server.weekly_reset_hour'),4)};}
  private async bankTiers(g:string):Promise<BankTierRule[]>{const raw=await this.config.get(g,'economy.bank_tiers');if(!Array.isArray(raw))throw new DomainError('INVALID_BANK_TIERS','Bank tier configuration is invalid.');return raw.map((v:any)=>({tier:Number(v?.tier),cap:v?.cap===null?null:asBig(v?.cap),upgradeCost:asBig(v?.upgrade_cost)}));}
  private async milestones(g:string){const raw=await this.config.get(g,'economy.daily_milestones');const out:Record<number,bigint>={};if(raw&&typeof raw==='object'&&!Array.isArray(raw))for(const [k,v] of Object.entries(raw as Record<string,unknown>)){const n=Number(k);if(Number.isInteger(n)&&n>0)out[n]=asBig(v);}return out;}
  private async spinTable(g:string):Promise<SpinReward[]>{const raw=await this.config.get(g,'economy.daily_spin_table');if(!Array.isArray(raw))throw new DomainError('INVALID_SPIN_REWARD','Daily Spin table is invalid.');return raw.map((v:any)=>({kind:v?.kind==='item'?'item':'ottomans',weight:Number(v?.weight??0),...(v?.amount!==undefined?{amount:asBig(v.amount)}:{}),...(typeof v?.item_id==='string'?{itemId:v.item_id}:{}),...(v?.quantity!==undefined?{quantity:Number(v.quantity)}:{}),...(typeof v?.label==='string'?{label:v.label}:{})}));}
  private async grindPolicy(g:string,activity:GrindActivity):Promise<GrindPolicy>{const throttle=asNumber(await this.config.get(g,'economy.grind_technical_throttle_ms'),1500);const raw=await this.config.get(g,'economy.grind_tables');const table=raw&&typeof raw==='object'&&!Array.isArray(raw)?(raw as Record<string,unknown>)[activity]:undefined;if(!Array.isArray(table))throw new DomainError('INVALID_GRIND_POLICY',`/${activity} outcome table is missing.`);const outcomes:GrindOutcomeRule[]=table.map((v:any)=>({outcome:String(v?.outcome??'zero') as GrindOutcomeRule['outcome'],weight:Number(v?.weight??0),...(v?.min!==undefined?{minOttomans:asBig(v.min)}:{}),...(v?.max!==undefined?{maxOttomans:asBig(v.max)}:{}),...(typeof v?.item_id==='string'?{itemId:v.item_id}:{}),...(v?.quantity!==undefined?{quantity:Number(v.quantity)}:{}),...(v?.tool_damage!==undefined?{toolDamage:Number(v.tool_damage)}:{})}));return{technicalThrottleMs:throttle,outcomes};}

  private dailyRow(h:DailyHubState){return new ActionRowBuilder<ButtonBuilder>().addComponents(new ButtonBuilder().setCustomId('economy:daily:claim').setLabel('Claim Daily').setStyle(ButtonStyle.Success).setDisabled(!h.dailyReady),new ButtonBuilder().setCustomId('economy:daily:spin').setLabel('Daily Spin').setStyle(ButtonStyle.Primary).setDisabled(!h.spinReady),new ButtonBuilder().setCustomId('economy:daily:fortune').setLabel('Fortune').setStyle(ButtonStyle.Secondary).setDisabled(!h.fortuneReady));}
  private async dailyPayload(g:string,u:string,notice?:string){const hub=await this.service.dailyHub(g,u,await this.resetHour(g));const embed=new EmbedBuilder().setColor(C.teal).setTitle('Daily Hub').setDescription([notice??'Three daily actions. Each resets at **4:00 AM Mountain Time**.','',`**Claim Daily:** ${hub.dailyReady?'Ready':`Used • resets ${time(hub.resetAt)}`}`,`**Daily Spin:** ${hub.spinReady?'Ready':`Used • resets ${time(hub.resetAt)}`}`,`**Fortune:** ${hub.fortuneReady?'Ready':`Used • resets ${time(hub.resetAt)}`}`,`**Claim streak:** ${hub.streak} day${hub.streak===1?'':'s'}`].join('\n')).setFooter({text:'Angrier Jordan • Ottomans'});return{hub,embeds:[embed],components:[this.dailyRow(hub)]};}
  private async daily(i:ChatInputCommandInteraction){const p=await this.dailyPayload(i.guildId!,i.user.id);await i.reply({ephemeral:true,embeds:p.embeds,components:p.components});}
  private async dailyButton(i:ButtonInteraction){const action=i.customId.split(':')[2];const g=i.guildId!;const resetHour=await this.resetHour(g);let notice='';if(action==='claim'){const base=BigInt(asNumber(await this.config.get(g,'economy.daily_base'),250));const r=await this.service.claimDaily({guildId:g,userId:i.user.id,idempotencyKey:i.id,baseReward:base,milestones:await this.milestones(g),resetHour});notice=r.status==='applied'?`**Claimed ${fmt(r.reward)} Ottomans.**${r.bonus?` Milestone bonus: ${fmt(r.bonus)}.`:''} Streak: ${r.streak}.`:'Claim Daily is already used for this cycle.';}else if(action==='spin'){const r=await this.service.spinDaily({guildId:g,userId:i.user.id,idempotencyKey:i.id,table:await this.spinTable(g),resetHour});notice=r.status==='applied'?`**Daily Spin:** ${r.reward?.label??(r.reward?.kind==='ottomans'?`${fmt(r.reward.amount??0n)} Ottomans`:'Item reward')}.`:'Daily Spin is already used for this cycle.';}else if(action==='fortune'){const r=await this.service.fortuneDaily({guildId:g,userId:i.user.id,idempotencyKey:i.id,resetHour});notice=r.status==='applied'?`**Fortune:** ${r.fortune?.text??'The chair spirits declined to elaborate.'}`:'Fortune is already used for this cycle.';}else throw new DomainError('UNKNOWN_DAILY_ACTION','That daily action no longer exists.');const p=await this.dailyPayload(g,i.user.id,notice);await i.update({embeds:p.embeds,components:p.components});}

  private async weekly(i:ChatInputCommandInteraction){const g=i.guildId!,reward=BigInt(asNumber(await this.config.get(g,'economy.weekly_base'),1500)),reset=await this.weeklyReset(g);const r=await this.service.weekly({guildId:g,userId:i.user.id,idempotencyKey:i.id,reward,resetDay:reset.day,resetHour:reset.hour});if(r.status==='applied')await i.reply({content:`<@${i.user.id}> claimed the weekly reward: **${fmt(r.reward)} Ottomans**.`});else await i.reply({ephemeral:true,content:'You already claimed this week’s reward.'});}
  private async grind(i:ChatInputCommandInteraction,activity:GrindActivity){const r=await this.service.grind({guildId:i.guildId!,userId:i.user.id,activity,idempotencyKey:i.id,policy:await this.grindPolicy(i.guildId!,activity)});if(r.status==='throttled'){await i.reply({ephemeral:true,content:'Angrier Jordan saw that double-click. Try again in a moment.'});return;}if(r.status==='duplicate'){await i.reply({ephemeral:true,content:'That result was already processed.'});return;}const e=r.event!;const pieces:string[]=[];if(e.ottomansDelta>0n)pieces.push(`earned **${fmt(e.ottomansDelta)} Ottomans**`);if(e.ottomansDelta<0n)pieces.push(`lost **${fmt(-e.ottomansDelta)} Ottomans**`);for(const x of e.itemGrants){const item=await this.service.inventory(i.guildId!,i.user.id).then(all=>all.find(y=>y.itemId===x.itemId));pieces.push(`found **${x.quantity}× ${item?.item?.name??x.itemId}**`);}if(!pieces.length)pieces.push('came back with absolutely nothing');if(e.toolDamage>0&&r.tool)pieces.push(`tool durability **${r.tool.durability}/${r.tool.maxDurability}**${r.fallbackTool?` • switched to ${r.fallbackTool.catalogItemId}`:''}`);const accent=activity==='work'?C.gold:activity==='fish'?C.blue:activity==='dig'?C.emerald:C.purple;await i.reply({embeds:[new EmbedBuilder().setColor(accent).setTitle(`/${activity}`).setDescription(`<@${i.user.id}> ${pieces.join(' • ')}.`).setFooter({text:`Outcome: ${e.outcome.replace(/_/g,' ')}`})]});}

  private async statement(i:ChatInputCommandInteraction){const s=await this.service.statement(i.guildId!,i.user.id,10);const rows=s.entries.map(x=>`${x.amount>0n?'+':''}${fmt(x.amount)} • ${x.reason} • ${time(x.createdAt)}`).join('\n')||'No transactions yet.';await i.reply({embeds:[new EmbedBuilder().setColor(C.gold).setTitle('Ottoman Statement').addFields({name:'Wallet',value:fmt(s.account.wallet),inline:true},{name:'Bank',value:fmt(s.account.bank),inline:true},{name:'Liquid net worth',value:fmt(s.liquidNetWorth),inline:true},{name:'Recent transactions',value:rows.slice(0,1000)}).setFooter({text:`Bank Tier ${s.account.bankTier}`})]});}
  private async inventory(i:ChatInputCommandInteraction){const items=await this.service.inventory(i.guildId!,i.user.id);const lines=items.slice(0,20).map(x=>`**${x.item?.name??x.itemId}** ×${x.quantity} • ${x.item?.rarity??'Unknown'}${x.locked?' • 🔒':''}${x.item?.sellValue!==undefined?` • sell ${fmt(x.item.sellValue)}`:''}`).join('\n')||'Your inventory is empty.';const extra=items.length>20?`\n…and ${items.length-20} more stack${items.length-20===1?'':'s'}.`:'';await i.reply({embeds:[new EmbedBuilder().setColor(C.purple).setTitle('Inventory').setDescription((lines+extra).slice(0,3900)).setFooter({text:'Selling stays inside /inventory; there is no standalone /sell.'})]});}

  private async bank(i:ChatInputCommandInteraction|ButtonInteraction|ModalSubmitInteraction,notice?:string){const tiers=await this.bankTiers(i.guildId!),a=await this.service.account(i.guildId!,i.user.id),v=this.service.bankView(a,tiers);const cap=v.rule.cap===null?'Unlimited':fmt(v.rule.cap);const next=v.nextRule?`Tier ${v.nextRule.tier} • upgrade cost ${fmt(v.rule.upgradeCost)} • current tier must be full`:'Maximum tier reached';const embed=new EmbedBuilder().setColor(C.emerald).setTitle('Ottoman Bank').setDescription([notice??'Banked Ottomans are protected from robbery. Spending automatically uses wallet first, then bank.','',`**Wallet:** ${fmt(a.wallet)}`,`**Bank:** ${fmt(a.bank)} / ${cap}`,`**Tier:** ${a.bankTier} of 5`,`**Next:** ${next}`].join('\n'));const row=new ActionRowBuilder<ButtonBuilder>().addComponents(new ButtonBuilder().setCustomId('economy:bank:deposit').setLabel('Deposit').setStyle(ButtonStyle.Success),new ButtonBuilder().setCustomId('economy:bank:withdraw').setLabel('Withdraw').setStyle(ButtonStyle.Primary),new ButtonBuilder().setCustomId('economy:bank:upgrade').setLabel(a.bankTier>=5?'Tier 5':'Upgrade Bank').setStyle(ButtonStyle.Secondary).setDisabled(a.bankTier>=5));const payload={embeds:[embed],components:[row]};if(i.isChatInputCommand())await i.reply(payload);else if(i.isButton())await i.update(payload);else await i.reply({...payload,ephemeral:true});}
  private async bankAmountModal(i:ButtonInteraction){const kind=i.customId.endsWith('deposit')?'deposit':'withdraw';const modal=new ModalBuilder().setCustomId(`economy:bank_modal:${kind}`).setTitle(kind==='deposit'?'Deposit Ottomans':'Withdraw Ottomans');const amount=new TextInputBuilder().setCustomId('amount').setLabel('Amount').setPlaceholder('Enter a whole number').setStyle(TextInputStyle.Short).setRequired(true).setMinLength(1).setMaxLength(12);modal.addComponents(new ActionRowBuilder<TextInputBuilder>().addComponents(amount));await i.showModal(modal);}
  private async bankAmountSubmit(i:ModalSubmitInteraction){const kind=i.customId.split(':')[2],raw=i.fields.getTextInputValue('amount').trim();if(!/^\d{1,12}$/.test(raw)||BigInt(raw)<=0n)throw new DomainError('INVALID_BANK_AMOUNT','Enter a positive whole number of Ottomans.');const tiers=await this.bankTiers(i.guildId!);const amount=BigInt(raw);const a=kind==='deposit'?await this.service.deposit({guildId:i.guildId!,userId:i.user.id,amount,idempotencyKey:i.id,tiers}):await this.service.withdraw({guildId:i.guildId!,userId:i.user.id,amount,idempotencyKey:i.id});await i.reply({ephemeral:true,content:`${kind==='deposit'?'Deposited':'Withdrew'} **${fmt(amount)} Ottomans**. Wallet: ${fmt(a.wallet)} • Bank: ${fmt(a.bank)}.`});}
  private async bankUpgrade(i:ButtonInteraction){const before=await this.service.account(i.guildId!,i.user.id);const a=await this.service.upgradeBank({guildId:i.guildId!,userId:i.user.id,idempotencyKey:i.id,tiers:await this.bankTiers(i.guildId!)});await this.bank(i,a.bankTier===before.bankTier?'That bank upgrade was already processed.':`**Bank upgraded to Tier ${a.bankTier}.**`);}
  private async transfer(i:ChatInputCommandInteraction){const target=i.options.getUser('member',true),n=i.options.getInteger('amount',true);if(!Number.isSafeInteger(n)||n<=0)throw new DomainError('INVALID_TRANSFER','Transfer amount must be a positive whole number.');const r=await this.service.transfer({guildId:i.guildId!,fromUserId:i.user.id,toUserId:target.id,amount:BigInt(n),idempotencyKey:i.id});await i.reply({content:`<@${i.user.id}> sent <@${target.id}> **${fmt(BigInt(n))} Ottomans**. No transfer fee.`});}

  private async replyError(i:ChatInputCommandInteraction|ButtonInteraction|ModalSubmitInteraction,e:unknown){const content=e instanceof DomainError?e.message:'That economy action could not be completed. Angrier Jordan logged the failure.';if(i.deferred||i.replied)await i.followUp({ephemeral:true,content}).catch(()=>undefined);else await i.reply({ephemeral:true,content}).catch(()=>undefined);}
}
