import {DomainError,type AuditService} from '../../../../packages/core/src/index.js';
import {ActionRowBuilder,ModalBuilder,StringSelectMenuBuilder,TextInputBuilder,TextInputStyle,type ChatInputCommandInteraction,type MessageContextMenuCommandInteraction,type ModalSubmitInteraction,type StringSelectMenuInteraction} from 'discord.js';

export const EMOJI_STEAL_COMMANDS=new Set(['steal']);
export const EMOJI_STEAL_CONTEXT_COMMANDS=new Set(['Steal Emoji']);
export const EMOJI_STEAL_COMPONENT_PREFIX='emoji-steal:';
const MAX_EMOJI_BYTES=256*1024;
const markupPattern=/^<(a?):([A-Za-z0-9_]{2,32}):(\d{17,20})>$/;
const inlinePattern=/<(a?):([A-Za-z0-9_]{2,32}):(\d{17,20})>/g;
const idPattern=/^\d{17,20}$/;
const cdnPattern=/^https:\/\/cdn\.discordapp\.com\/emojis\/(\d{17,20})\.(png|gif|webp)(?:[?#].*)?$/i;
type FetchLike=(input:string,init?:RequestInit)=>Promise<{ok:boolean;status:number;headers:{get(name:string):string|null};arrayBuffer():Promise<ArrayBuffer>}>;
type StealInteraction=ChatInputCommandInteraction|MessageContextMenuCommandInteraction|StringSelectMenuInteraction|ModalSubmitInteraction;
type EmojiSource={id:string;name?:string;animated?:boolean};

function validImage(data:Buffer,animated:boolean){const png=data.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10]));const head=data.subarray(0,6).toString('ascii');return animated?head==='GIF87a'||head==='GIF89a':png;}
function emojiName(raw:string){const value=raw.trim().toLowerCase().replace(/[^a-z0-9_]/g,'_').replace(/_+/g,'_').replace(/^_+|_+$/g,'');if(value.length<2||value.length>32)throw new DomainError('EMOJI_NAME','Emoji names must contain 2–32 letters, numbers, or underscores.');return value;}
function parseSource(raw:string):EmojiSource|undefined{const value=raw.trim(),markup=markupPattern.exec(value);if(markup)return{id:markup[3]!,name:markup[2]!,animated:markup[1]==='a'};if(idPattern.test(value))return{id:value};const url=cdnPattern.exec(value);if(url)return{id:url[1]!,animated:url[2]!.toLowerCase()==='gif'};return undefined;}
function sourceFromMessage(message:any):EmojiSource[]{const found=new Map<string,EmojiSource>();for(const match of message.content?.matchAll(inlinePattern)??[])found.set(match[3]!,{id:match[3]!,name:match[2],animated:match[1]==='a'});for(const reaction of message.reactions?.cache?.values?.()??[]){const emoji=reaction.emoji,name=emoji?.name;if(emoji?.id&&typeof name==='string')found.set(emoji.id,{id:emoji.id,name,animated:Boolean(emoji.animated)});}return [...found.values()];}

export class DiscordEmojiStealCoordinator {
 constructor(private readonly audit:AuditService,private readonly request:FetchLike=fetch){}
 private nameModal(userId:string,source:EmojiSource){return new ModalBuilder().setCustomId(`${EMOJI_STEAL_COMPONENT_PREFIX}name:${userId}:${source.id}:${source.animated?'a':'s'}`).setTitle('Name the copied emoji').addComponents(new ActionRowBuilder<TextInputBuilder>().addComponents(new TextInputBuilder().setCustomId('name').setLabel('Emoji name').setPlaceholder(`For example: chair_${source.id.slice(-4)}`).setStyle(TextInputStyle.Short).setMinLength(2).setMaxLength(32).setRequired(true)));}
 private async download(source:EmojiSource):Promise<{data:Buffer;animated:boolean}>{const formats=source.animated===undefined?[true,false]:[source.animated];let downloaded=false;for(const animated of formats){const response=await this.request(`https://cdn.discordapp.com/emojis/${source.id}.${animated?'gif':'png'}?quality=lossless`,{signal:AbortSignal.timeout(10_000)});if(!response.ok)continue;downloaded=true;if(Number(response.headers.get('content-length')??'0')>MAX_EMOJI_BYTES)throw new DomainError('EMOJI_SIZE','That emoji is larger than Discord’s 256 KB upload limit.');const data=Buffer.from(await response.arrayBuffer());if(data.length&&data.length<=MAX_EMOJI_BYTES&&validImage(data,animated))return{data,animated};}if(downloaded)throw new DomainError('EMOJI_FILE','That emoji is not a valid Discord PNG or GIF within the 256 KB limit.');throw new DomainError('EMOJI_DOWNLOAD','That emoji could not be downloaded from Discord.');}
 private async copy(interaction:StealInteraction,source:EmojiSource,requestedName:string){try{const name=emojiName(requestedName),emojis=await interaction.guild!.emojis.fetch();if([...emojis.values()].some(emoji=>emoji.name?.toLowerCase()===name))throw new DomainError('EMOJI_DUPLICATE',`An emoji named **${name}** already exists in this server.`);const slotLimit=interaction.guild!.premiumTier===3?250:interaction.guild!.premiumTier===2?150:interaction.guild!.premiumTier===1?100:50;if(emojis.size>=slotLimit)throw new DomainError('EMOJI_SLOTS','The server has no open custom-emoji slots.');const downloaded=await this.download(source),created=await interaction.guild!.emojis.create({attachment:downloaded.data,name,reason:`Copied by ${interaction.user.tag} with /steal`});await this.audit.record({guildId:interaction.guildId!,actorUserId:interaction.user.id,source:'discord',action:'emoji.steal',targetType:'emoji',targetId:created.id,before:{sourceEmojiId:source.id},after:{name:created.name,animated:downloaded.animated,sizeBytes:downloaded.data.length},requestId:interaction.id,createdAt:new Date()});await interaction.editReply({content:`Added ${created} as **${created.name}**.`,allowedMentions:{parse:[]}});}catch(error){await interaction.editReply({content:error instanceof DomainError?error.message:'That emoji could not be copied. Nothing was added.',allowedMentions:{parse:[]}}).catch(()=>undefined);}}
 private async choose(interaction:MessageContextMenuCommandInteraction,sources:EmojiSource[]){if(!sources.length){await interaction.reply({ephemeral:true,content:'That message has no custom Discord emoji in its text or reactions.'});return;}if(sources.length===1){await interaction.deferReply({ephemeral:true});await this.copy(interaction,sources[0]!,sources[0]!.name!);return;}await interaction.reply({ephemeral:true,content:'Choose the custom emoji to copy from this message.',components:[new ActionRowBuilder<StringSelectMenuBuilder>().addComponents(new StringSelectMenuBuilder().setCustomId(`${EMOJI_STEAL_COMPONENT_PREFIX}pick:${interaction.user.id}`).setPlaceholder('Choose an emoji').addOptions(sources.slice(0,25).map(source=>({label:source.name!.slice(0,100),description:source.animated?'Animated emoji':'Custom emoji',value:`${source.id}|${source.animated?'a':'s'}|${source.name}`}))))]});}
 async handle(interaction:StealInteraction):Promise<void>{
  if(!interaction.guild){await interaction.reply({ephemeral:true,content:'Use this command in Chairs.'});return;}
  if(interaction.isStringSelectMenu()){const [,action,owner]=interaction.customId.split(':');if(action!=='pick'||owner!==interaction.user.id)throw new DomainError('EMOJI_STEAL_OWNER','Open your own emoji picker.');const [id,flag,name]=interaction.values[0]!.split('|');if(!idPattern.test(id!)||!name)throw new DomainError('EMOJI_STEAL_SOURCE','Choose the emoji again.');await interaction.deferUpdate();await this.copy(interaction,{id:id!,name,animated:flag==='a'},name);return;}
  if(interaction.isModalSubmit()){const [,action,owner,id,flag]=interaction.customId.split(':');if(action!=='name'||owner!==interaction.user.id||!idPattern.test(id??''))throw new DomainError('EMOJI_STEAL_OWNER','Open your own emoji naming form.');await interaction.deferReply({ephemeral:true});await this.copy(interaction,{id:id!,animated:flag==='a'},interaction.fields.getTextInputValue('name'));return;}
  if(interaction.isMessageContextMenuCommand()){await this.choose(interaction,sourceFromMessage(interaction.targetMessage));return;}
  const source=parseSource(interaction.options.getString('source',true));if(!source){await interaction.reply({ephemeral:true,content:'Paste a custom emoji, its numeric ID, or its Discord CDN link. A bare `:name:` does not include the ID Discord needs.'});return;}const requestedName=interaction.options.getString('name')??source.name;if(!requestedName){await interaction.showModal(this.nameModal(interaction.user.id,source));return;}await interaction.deferReply({ephemeral:true});await this.copy(interaction,source,requestedName);
 }
}
