import {ActionRowBuilder,AttachmentBuilder,ButtonBuilder,ButtonStyle,EmbedBuilder,ModalBuilder,TextInputBuilder,TextInputStyle,type ButtonInteraction,type ChatInputCommandInteraction,type Client,type Guild,type ModalSubmitInteraction} from 'discord.js';
import {DeliveryEngine,DomainError,PermissionEngine,type ConfigService} from '../../../../packages/core/src/index.js';
import {CAPABILITY_MATRIX} from '../../../../packages/contracts/src/generated/capabilities.js';
import {PrismaFamilyRepository,type FamilyView} from '../../../../packages/features-family/src/prisma-repository.js';
import type {FamilyContext,FamilyMember} from '../../../../packages/features-family/src/domain.js';
import {renderPremiumFamily,renderFamilyNotice,renderFamilyTree,familyBranches} from '../../../../packages/features-family/src/premium-render.js';
import {rasterizeSvg} from '../../../../packages/renderer/src/raster.js';
import {avatarData,memberArt} from './member-art.js';
type Interaction=ChatInputCommandInteraction|ButtonInteraction|ModalSubmitInteraction;

export class DiscordFamilyCoordinator {
 private updates=new Map<string,Promise<void>>();
 constructor(private repo:PrismaFamilyRepository,private config:ConfigService,private eligible:(guildId:string,userId:string)=>Promise<boolean>,private departedName:(guildId:string,userId:string)=>Promise<string|undefined>=async()=>undefined){}
 private async guard(guildId:string,userId:string,channelId:string){if(await this.config.get(guildId,'features.family')!==true)throw new DomainError('FAMILY_DISABLED','Family features are not enabled yet.');if(await this.config.get(guildId,'channels.bot_channel')!==channelId)throw new DomainError('FAMILY_CHANNEL','Use the configured bot channel.');if(!new PermissionEngine({'family.use':CAPABILITY_MATRIX.capabilities['family.use']}).can('member','family.use')||!await this.eligible(guildId,userId))throw new DomainError('FAMILY_RESTRICTED','Family actions are unavailable while restricted.');}
 private async member(guild:Guild,userId:string,passive=false):Promise<FamilyMember>{const member=await guild.members.fetch({user:userId,force:true});if(member.user.bot||!passive&&!await this.eligible(guild.id,userId))throw new DomainError('FAMILY_MEMBER','Choose a current eligible human member.');return{userId,name:member.displayName,avatar:member.displayAvatarURL({extension:'png',size:128})};}
 async handle(i:Interaction){try{if(!i.guildId||!i.guild||!i.channelId)throw new DomainError('SERVER_ONLY','Use family features in the server.');await this.guard(i.guildId,i.user.id,i.channelId);const c:FamilyContext={guildId:i.guildId,channelId:i.channelId,userId:i.user.id,requestKey:i.id};
  if(i.isChatInputCommand()){await i.deferReply({ephemeral:true});const action=i.options.getSubcommand(),target=i.options.getUser('member');let result:{sessionId:string;jobId?:string}|undefined;
   if(action==='marry'){if(!target)throw new DomainError('FAMILY_MEMBER','Choose a member to propose to.');result=await this.repo.propose(c,await this.member(i.guild,target.id),await this.member(i.guild,i.user.id),i.options.getString('item')==='sack'?'sack':'ring');}
   else if(action==='divorce'){if(!target)throw new DomainError('FAMILY_MEMBER','Choose your spouse.');result=await this.repo.divorce(c,target.id);}
   else if(action==='adopt'){if(!target)throw new DomainError('FAMILY_MEMBER','Choose a proposed child.');result=await this.repo.adopt(c,await this.member(i.guild,target.id),await this.member(i.guild,i.user.id));}
   else if(action==='disown'){if(!target)throw new DomainError('FAMILY_MEMBER','Choose your child.');result=await this.repo.endAdoption(c,'disown',target.id);}
   else if(action==='emancipate')result=await this.repo.endAdoption(c,'emancipate');
   else if(action==='will'){if(!target)throw new DomainError('FAMILY_MEMBER','Choose an eligible beneficiary.');const beneficiary=await this.member(i.guild,target.id,true);await this.repo.setWill(c,target.id);await i.editReply(await this.notice('Your Will Is Saved','Beneficiary: '+beneficiary.name+'. Your one-beneficiary will is saved. No assets transfer until estate execution.',beneficiary));return;}
   else if(action==='familytree'){await i.editReply(await this.treePayload(i.guild,target?.id??i.user.id,i.user.id));return;}
   else if(action==='familyauction')result=await this.repo.createAuction(c,await this.member(i.guild,i.user.id),i.options.getString('type') as 'spouse'|'child',i.options.getInteger('hours')??24,BigInt(i.options.getInteger('reserve')??0));
   else throw new DomainError('FAMILY_COMMAND','That family command is unavailable.');if(result?.jobId)await this.publish(i.client,result.jobId);await i.editReply(await this.notice('Family Event Saved','The public family presentation is ready in this channel.'));return;
  }
  if(i.isButton()&&i.customId.startsWith('family:treepage:')){const parts=i.customId.split(':'),page=Number(parts[4]);if(parts.length!==5||parts[2]!==i.user.id||!/^\d{17,20}$/.test(parts[3]??'')||!Number.isSafeInteger(page)||page<0)throw new DomainError('FAMILY_TREE_CONTROL','Open your own family tree to browse its branches.');await i.deferUpdate();await i.editReply(await this.treePayload(i.guild,parts[3]!,i.user.id,page));return;}
  const[prefix,action,id,arg]=i.customId.split(':');if(prefix!=='family'||!id)throw new DomainError('FAMILY_CONTROL','Use the original family event.');const v=await this.repo.publicView(id);if(v.guildId!==i.guildId||v.channelId!==i.channelId||!i.isModalSubmit()&&i.message.id!==v.messageId)throw new DomainError('FAMILY_CONTROL','Use this event’s original server, channel and message.');
  if(action==='bid'&&i.isButton()){await i.showModal(new ModalBuilder().setCustomId('family:bid_modal:'+id).setTitle('Your Sealed Bid').addComponents(new ActionRowBuilder<TextInputBuilder>().addComponents(new TextInputBuilder().setCustomId('amount').setLabel('Your new total bid in Ottomans').setStyle(TextInputStyle.Short).setRequired(true).setMaxLength(20))));return;}
  await i.deferReply({ephemeral:true});if(action==='tree'){await i.editReply(await this.treePayload(i.guild,v.data.members?.[0]?.userId??v.ownerId??i.user.id,i.user.id));return;}
  if(action==='accept'||action==='reject'){if(v.type==='family_marriage')await this.repo.decideProposal(c,id,action==='accept');else if(v.type==='family_adoption')await this.repo.decideAdoption(c,id,action==='accept');else throw new DomainError('FAMILY_CONTROL','That event has no pending decision.');}
  else if(action==='vote'&&(arg==='up'||arg==='down'))await this.repo.marriageVote(c,id,arg);
  else if(action==='bid_modal'&&i.isModalSubmit()){const raw=i.fields.getTextInputValue('amount').trim();if(!/^\d{1,20}$/.test(raw))throw new DomainError('FAMILY_BID','Enter a whole positive Ottoman amount.');const saved=await this.repo.bid(c,id,await this.member(i.guild,i.user.id),BigInt(raw));await i.editReply(await this.notice('Your Sealed Bid',`Your sealed total bid is ${saved.amount} Ottomans. Other members cannot see it. Bids may only increase and cannot be withdrawn.`));return;}
  else throw new DomainError('FAMILY_CONTROL','That family control is unavailable.');await i.editReply(await this.notice('Family Action Saved','Your response is saved. The public family presentation will update.'));await this.refresh(i.client,id);
 }catch(error){const content=error instanceof DomainError?error.message:'The family action could not be completed. Saved events remain available for recovery.';if(!i.deferred&&!i.replied)await i.deferReply({ephemeral:true});let feedback;try{feedback=await this.notice('Family · Please Review',content);}catch{feedback={content,allowedMentions:{parse:[] as never[]}};}if(i.replied)await i.followUp({...feedback,ephemeral:true});else await i.editReply(feedback);}}
 async payload(v:FamilyView,client?:Client){const members=await Promise.all((v.data.members??[]).map(async m=>{const art=client?await memberArt(client,v.guildId,m.userId):undefined;return{...m,name:art?.name??m.name,avatar:art?.avatarData||await avatarData(m.avatar)};}));
  if(v.data.executed&&v.data.heirId&&!members.some(m=>m.userId===v.data.heirId)){const art=client?await memberArt(client,v.guildId,v.data.heirId):undefined;members.push({userId:v.data.heirId,name:art?.name??'Beneficiary',avatar:art?.avatarData??''});}
  const departedId=v.type==='family_estate'&&v.data.executed?(v.data.departedId??v.ownerId):undefined,directoryName=departedId?await this.departedName(v.guildId,departedId).catch(()=>undefined):undefined,departedName=directoryName?.trim()||v.data.departedName?.trim(),data={...v.data,...(departedName?{departedName}:{}),...(members.length?{members}:{})},buttons:ButtonBuilder[]=[],button=(action:string,label:string,arg?:string)=>new ButtonBuilder().setCustomId(`family:${action}:${v.id}${arg?':'+arg:''}`).setLabel(label).setStyle(ButtonStyle.Secondary);
  if(v.state==='DRAFT'&&['family_marriage','family_adoption'].includes(v.type))buttons.push(button('accept','Accept').setStyle(ButtonStyle.Success),button('reject','Decline').setStyle(ButtonStyle.Danger));
  if(v.type==='family_marriage'&&v.state!=='DRAFT'&&data.compatibility!==undefined)buttons.push(button('vote','👍','up').setDisabled(v.state!=='OPEN'),button('vote','👎','down').setDisabled(v.state!=='OPEN'),button('tree','View Family'));
  if(v.type==='family_auction'&&v.state==='OPEN')buttons.push(button('bid','Place / Increase Sealed Bid'));
  if(v.type==='family_adoption'&&v.state==='CLOSED')buttons.push(button('tree','View Family'));
  if(!buttons.some(b=>'custom_id' in b.data&&b.data.custom_id==='family:tree:'+v.id))buttons.push(button('tree','View Family'));
  const view={...v,data};return{content:'',embeds:[new EmbedBuilder().setColor(0xBC9CEB).setImage('attachment://family.png')],files:[new AttachmentBuilder(await rasterizeSvg(renderPremiumFamily(view)),{name:'family.png',description:[data.result??'Family event',...(data.departedName?[`In memory of ${data.departedName}`]:[]),...members.map(m=>m.name),data.compatibility!==undefined?'Compatibility '+data.compatibility+'%':'',data.amount?data.amount+' Ottomans':''].filter(Boolean).join('. ').slice(0,1024)})],components:[new ActionRowBuilder<ButtonBuilder>().addComponents(...buttons)],attachments:[],allowedMentions:{parse:[] as never[]}};
 }
 private async notice(title:string,message:string,member?:FamilyMember){const portraitMember=member?{...member,avatar:await avatarData(member.avatar)}:undefined;return{content:'',embeds:[new EmbedBuilder().setImage('attachment://family-window.png').setColor(0xBC9CEB)],files:[new AttachmentBuilder(await rasterizeSvg(renderFamilyNotice(title,message,portraitMember)),{name:'family-window.png',description:message.slice(0,1024)})],attachments:[],components:[],allowedMentions:{parse:[] as never[]}};}
 private async treePayload(guild:Guild,userId:string,actorId=userId,page=0){
  const tree=await this.repo.tree(guild.id,userId),branches=familyBranches(tree,userId);page=Math.min(page,branches.length-1);const branch=branches[page]!,visible=[...new Set([...branch.parents,...branch.children])];
  const members=await Promise.all(visible.map(async id=>{try{const m=await guild.members.fetch(id);return{userId:id,name:m.displayName,avatar:await avatarData(m.displayAvatarURL?.({extension:'png',size:128}))};}catch{return{userId:id,name:'Unavailable member',avatar:''};}}));
  const record=tree.record?.value as {members?:string[];perk?:string}|undefined,perk=record?.members?.includes(userId)?record.perk:undefined,svg=renderFamilyTree({branch,members,focus:userId,page,pages:branches.length,total:tree.members.length,...(perk?{perk}:{})});
  const button=(p:number,label:string,disabled:boolean)=>new ButtonBuilder().setCustomId('family:treepage:'+actorId+':'+userId+':'+p).setLabel(label).setStyle(ButtonStyle.Secondary).setDisabled(disabled);
  return{content:'',embeds:[new EmbedBuilder().setImage('attachment://family-tree.png').setColor(0xBC9CEB)],files:[new AttachmentBuilder(await rasterizeSvg(svg),{name:'family-tree.png',description:('Family tree branch '+(page+1)+' of '+branches.length+'. '+(branch.married?'Spouses: ':'Parents: ')+branch.parents.map(id=>members.find(m=>m.userId===id)?.name).join(' and ')+'. Children: '+(branch.children.map(id=>members.find(m=>m.userId===id)?.name).join(', ')||'none')+(perk?'. '+perk:'')).slice(0,1024)})],attachments:[],components:branches.length>1?[new ActionRowBuilder<ButtonBuilder>().addComponents(button(Math.max(0,page-1),'Previous Branch',page===0),button(Math.min(branches.length-1,page+1),'Next Branch',page===branches.length-1))]:[],allowedMentions:{parse:[] as never[]}};
 }
 async publish(client:Client,jobId:string){const p=await this.repo.publication(jobId),channel=await client.channels.fetch(p.channelId);if(!channel?.isSendable()||!('messages' in channel))throw new Error('Family destination unavailable.');const marker='family:'+p.sessionId,id=await new DeliveryEngine(this.repo.delivery(jobId)).deliver(marker,{find:async()=>{const messages=await channel.messages.fetch({limit:100});return messages.find(m=>m.author.id===client.user?.id&&(m.components?.some(row=>'components' in row&&row.components.some(c=>'customId' in c&&c.customId==='family:tree:'+p.sessionId))||m.embeds.some(e=>e.footer?.text===marker)))?.id??null;},send:async()=>{return(await channel.send(await this.payload(await this.repo.publicView(p.sessionId),client))).id;}});await this.repo.linkMessage(p.guildId,p.sessionId,id);}
 async refresh(client:Client,id:string){const prior=this.updates.get(id)??Promise.resolve(),pending=prior.catch(()=>{}).then(async()=>{const v=await this.repo.publicView(id);if(!v.messageId)return;const channel=await client.channels.fetch(v.channelId);if(!channel?.isTextBased()||!('messages' in channel))throw new Error('Family destination unavailable.');const message=await channel.messages.fetch(v.messageId);if(message.author.id!==client.user?.id)throw new Error('Family message author mismatch.');await message.edit(await this.payload(v,client));});this.updates.set(id,pending);try{await pending;}finally{if(this.updates.get(id)===pending)this.updates.delete(id);}}
 async advance(client:Client,kind:string,guildId:string,id:string){let result:{sessionId:string;jobId?:string};if(kind==='proposal_expire')result=await this.repo.expireProposal(guildId,id);else if(kind==='marriage_close')result=await this.repo.closeMarriageVote(guildId,id);else if(kind==='adoption_expire')result=await this.repo.expireAdoption(guildId,id);else if(kind==='auction_close')result=await this.repo.closeAuction(guildId,id);else if(kind==='estate_execute')result=await this.repo.executeEstate(guildId,id);else throw new DomainError('FAMILY_JOB','Unknown family job.');if(result.jobId)await this.publish(client,result.jobId);await this.refresh(client,id);}
}
