import {ActionRowBuilder,AttachmentBuilder,ButtonBuilder,ButtonStyle,EmbedBuilder,ModalBuilder,TextInputBuilder,TextInputStyle,type ButtonInteraction,type ChatInputCommandInteraction,type Client,type Guild,type ModalSubmitInteraction} from 'discord.js';
import {DeliveryEngine,DomainError,PermissionEngine,type ConfigService} from '../../../../packages/core/src/index.js';
import {CAPABILITY_MATRIX} from '../../../../packages/contracts/src/generated/capabilities.js';
import {PrismaFamilyRepository,type FamilyView} from '../../../../packages/features-family/src/prisma-repository.js';
import type {FamilyContext,FamilyMember} from '../../../../packages/features-family/src/domain.js';
import {renderFamily,familyDescription,familyTitle} from '../../../../packages/features-family/src/render.js';
import {rasterizeSvg} from '../../../../packages/renderer/src/raster.js';
import {shell,heading,panel,text,ink,lines} from '../../../../packages/features-events/src/visual.js';
type Interaction=ChatInputCommandInteraction|ButtonInteraction|ModalSubmitInteraction;

export class DiscordFamilyCoordinator {
 private updates=new Map<string,Promise<void>>();
 private avatarCache=new Map<string,string>();
 constructor(private repo:PrismaFamilyRepository,private config:ConfigService,private eligible:(guildId:string,userId:string)=>Promise<boolean>){}
 private async guard(guildId:string,userId:string,channelId:string){if(await this.config.get(guildId,'features.family')!==true)throw new DomainError('FAMILY_DISABLED','Family features are not enabled yet.');if(await this.config.get(guildId,'channels.bot_channel')!==channelId)throw new DomainError('FAMILY_CHANNEL','Use the configured bot channel.');if(!new PermissionEngine({'events.use':CAPABILITY_MATRIX.capabilities['events.use']}).can('member','events.use')||!await this.eligible(guildId,userId))throw new DomainError('FAMILY_RESTRICTED','Family actions are unavailable while restricted.');}
 private async member(guild:Guild,userId:string,passive=false):Promise<FamilyMember>{const member=await guild.members.fetch({user:userId,force:true});if(member.user.bot||!passive&&!await this.eligible(guild.id,userId))throw new DomainError('FAMILY_MEMBER','Choose a current eligible human member.');return{userId,name:member.displayName,avatar:member.displayAvatarURL({extension:'png',size:128})};}
 private async avatar(value:string){if(value.startsWith('data:image/'))return value;if(this.avatarCache.has(value))return this.avatarCache.get(value)!;try{const url=new URL(value);if(url.protocol!=='https:'||!['cdn.discordapp.com','media.discordapp.net'].includes(url.hostname))return'';const response=await fetch(url,{signal:AbortSignal.timeout(5000),redirect:'error'});if(!response.ok||Number(response.headers.get('content-length')??0)>262144)return'';const bytes=Buffer.from(await response.arrayBuffer());if(bytes.length>262144)return'';const type=response.headers.get('content-type')?.split(';')[0];if(!['image/png','image/jpeg','image/webp'].includes(type??''))return'';const data=`data:${type};base64,${bytes.toString('base64')}`;if(this.avatarCache.size>=512)this.avatarCache.delete(this.avatarCache.keys().next().value!);this.avatarCache.set(value,data);return data;}catch{return'';}}
 async handle(i:Interaction){try{if(!i.guildId||!i.guild||!i.channelId)throw new DomainError('SERVER_ONLY','Use family features in the server.');await this.guard(i.guildId,i.user.id,i.channelId);const c:FamilyContext={guildId:i.guildId,channelId:i.channelId,userId:i.user.id,requestKey:i.id};
  if(i.isChatInputCommand()){await i.deferReply({ephemeral:true});const action=i.options.getSubcommand(),target=i.options.getUser('member');let result:{sessionId:string;jobId?:string}|undefined;
   if(action==='marry'){if(!target)throw new DomainError('FAMILY_MEMBER','Choose a member to propose to.');result=await this.repo.propose(c,await this.member(i.guild,target.id),await this.member(i.guild,i.user.id),i.options.getString('item')==='sack'?'sack':'ring');}
   else if(action==='divorce'){if(!target)throw new DomainError('FAMILY_MEMBER','Choose your spouse.');result=await this.repo.divorce(c,target.id);}
   else if(action==='adopt'){if(!target)throw new DomainError('FAMILY_MEMBER','Choose a proposed child.');result=await this.repo.adopt(c,await this.member(i.guild,target.id),await this.member(i.guild,i.user.id));}
   else if(action==='disown'){if(!target)throw new DomainError('FAMILY_MEMBER','Choose your child.');result=await this.repo.endAdoption(c,'disown',target.id);}
   else if(action==='emancipate')result=await this.repo.endAdoption(c,'emancipate');
   else if(action==='will'){if(!target)throw new DomainError('FAMILY_MEMBER','Choose an eligible beneficiary.');await this.member(i.guild,target.id,true);await this.repo.setWill(c,target.id);await i.editReply({content:'Your one-beneficiary will is saved.',allowedMentions:{parse:[]}});return;}
   else if(action==='familytree'){await i.editReply(await this.treePayload(i.guild,target?.id??i.user.id));return;}
   else if(action==='familyauction')result=await this.repo.createAuction(c,await this.member(i.guild,i.user.id),i.options.getString('type') as 'spouse'|'child',i.options.getInteger('hours')??24,BigInt(i.options.getInteger('reserve')??0));
   else throw new DomainError('FAMILY_COMMAND','That family command is unavailable.');if(result?.jobId)await this.publish(i.client,result.jobId);await i.editReply({content:'The family event is saved in this channel.'});return;
  }
  const[prefix,action,id,arg]=i.customId.split(':');if(prefix!=='family'||!id)throw new DomainError('FAMILY_CONTROL','Use the original family event.');const v=await this.repo.publicView(id);if(v.guildId!==i.guildId||v.channelId!==i.channelId||!i.isModalSubmit()&&i.message.id!==v.messageId)throw new DomainError('FAMILY_CONTROL','Use this event’s original server, channel and message.');
  if(action==='bid'&&i.isButton()){await i.showModal(new ModalBuilder().setCustomId('family:bid_modal:'+id).setTitle('Your Sealed Bid').addComponents(new ActionRowBuilder<TextInputBuilder>().addComponents(new TextInputBuilder().setCustomId('amount').setLabel('Your new total bid in Ottomans').setStyle(TextInputStyle.Short).setRequired(true).setMaxLength(20))));return;}
  await i.deferReply({ephemeral:true});if(action==='tree'){await i.editReply(await this.treePayload(i.guild,v.data.members?.[0]?.userId??v.ownerId??i.user.id));return;}
  if(action==='accept'||action==='reject'){if(v.type==='family_marriage')await this.repo.decideProposal(c,id,action==='accept');else if(v.type==='family_adoption')await this.repo.decideAdoption(c,id,action==='accept');else throw new DomainError('FAMILY_CONTROL','That event has no pending decision.');}
  else if(action==='vote'&&(arg==='up'||arg==='down'))await this.repo.marriageVote(c,id,arg);
  else if(action==='bid_modal'&&i.isModalSubmit()){const raw=i.fields.getTextInputValue('amount').trim();if(!/^\d{1,20}$/.test(raw))throw new DomainError('FAMILY_BID','Enter a whole positive Ottoman amount.');const saved=await this.repo.bid(c,id,await this.member(i.guild,i.user.id),BigInt(raw));await i.editReply({content:`Your sealed total bid is ${saved.amount} Ottomans. Other members cannot see it.`});return;}
  else throw new DomainError('FAMILY_CONTROL','That family control is unavailable.');await i.editReply({content:'Your family action is saved.'});await this.refresh(i.client,id);
 }catch(error){const content=error instanceof DomainError?error.message:'The family action could not be completed. Saved events remain available for recovery.';if(i.deferred&&!i.replied)await i.editReply({content});else if(i.replied||i.deferred)await i.followUp({ephemeral:true,content});else await i.reply({ephemeral:true,content});}}
 async payload(v:FamilyView){const data={...v.data,...(v.data.members?{members:await Promise.all(v.data.members.map(async m=>({...m,avatar:await this.avatar(m.avatar)})))}:{})},buttons:ButtonBuilder[]=[],button=(action:string,label:string,arg?:string)=>new ButtonBuilder().setCustomId(`family:${action}:${v.id}${arg?':'+arg:''}`).setLabel(label).setStyle(ButtonStyle.Secondary);
  if(v.state==='DRAFT'&&['family_marriage','family_adoption'].includes(v.type))buttons.push(button('accept','Accept'),button('reject','Decline'));
  if(v.type==='family_marriage'&&v.state!=='DRAFT'&&data.compatibility!==undefined)buttons.push(button('vote','👍','up').setDisabled(v.state!=='OPEN'),button('vote','👎','down').setDisabled(v.state!=='OPEN'),button('tree','View Family'));
  if(v.type==='family_auction'&&v.state==='OPEN')buttons.push(button('bid','Place / Increase Sealed Bid'));
  if(v.type==='family_adoption'&&v.state==='CLOSED')buttons.push(button('tree','View Family'));
  return{embeds:[new EmbedBuilder().setAuthor({name:'Angrier Jordan'}).setTitle(familyTitle(v)).setDescription(familyDescription(v)).setColor(0x0ea5a6).setImage('attachment://family.png').setFooter({text:'family:'+v.id})],files:[new AttachmentBuilder(await rasterizeSvg(renderFamily({...v,data})),{name:'family.png'})],components:buttons.length?[new ActionRowBuilder<ButtonBuilder>().addComponents(...buttons)]:[],attachments:[],allowedMentions:{parse:[] as never[]}};
 }
 private async treePayload(guild:Guild,userId:string){const tree=await this.repo.tree(guild.id,userId),names=new Map<string,string>();for(const id of tree.members){try{names.set(id,(await guild.members.fetch(id)).displayName);}catch{names.set(id,'Unavailable member');}}const textLines=[...tree.marriages.map(m=>`${names.get(m.userA)} + ${names.get(m.userB)}`),...tree.adoptions.map(a=>`${names.get(a.parents[0])} + ${names.get(a.parents[1])} → ${names.get(a.childUserId)}`)];if(!textLines.length)textLines.push('No active family links.');const record=tree.record?.value as {members?:string[];perk?:string}|undefined,perk=record?.members?.includes(userId)?record.perk:undefined;let body=heading('ANGRIER JORDAN · FAMILY','The Active Family Tree',`${tree.members.length} member${tree.members.length===1?'':'s'}`)+panel(18,137,404,520,perk?.startsWith('Brass')?ink.gold:perk?.startsWith('Emerald')?ink.emerald:ink.slate),y=170;for(const line of textLines.flatMap(line=>lines(line,42)).slice(0,17)){body+=text(32,y,line,16,ink.white);y+=27;}if(perk)body+=text(32,628,perk,16,ink.gold);const full=[...textLines,...(perk?['Current record perk: '+perk]:[])].join('\n');return{content:'Current active relationships.',files:[new AttachmentBuilder(await rasterizeSvg(shell(680,body)),{name:'family-tree.png'}),new AttachmentBuilder(Buffer.from(full),{name:'active-family.txt'})],allowedMentions:{parse:[] as never[]}};}
 async publish(client:Client,jobId:string){const p=await this.repo.publication(jobId),channel=await client.channels.fetch(p.channelId);if(!channel?.isSendable()||!('messages' in channel))throw new Error('Family destination unavailable.');const marker='family:'+p.sessionId,id=await new DeliveryEngine(this.repo.delivery(jobId)).deliver(marker,{find:async()=>{const messages=await channel.messages.fetch({limit:100});return messages.find(m=>m.author.id===client.user?.id&&m.embeds.some(e=>e.footer?.text===marker))?.id??null;},send:async()=>{return(await channel.send(await this.payload(await this.repo.publicView(p.sessionId)))).id;}});await this.repo.linkMessage(p.guildId,p.sessionId,id);}
 async refresh(client:Client,id:string){const prior=this.updates.get(id)??Promise.resolve(),pending=prior.catch(()=>{}).then(async()=>{const v=await this.repo.publicView(id);if(!v.messageId)return;const channel=await client.channels.fetch(v.channelId);if(!channel?.isTextBased()||!('messages' in channel))throw new Error('Family destination unavailable.');const message=await channel.messages.fetch(v.messageId);if(message.author.id!==client.user?.id)throw new Error('Family message author mismatch.');await message.edit(await this.payload(v));});this.updates.set(id,pending);try{await pending;}finally{if(this.updates.get(id)===pending)this.updates.delete(id);}}
 async advance(client:Client,kind:string,guildId:string,id:string){let result:{sessionId:string;jobId?:string};if(kind==='proposal_expire')result=await this.repo.expireProposal(guildId,id);else if(kind==='marriage_close')result=await this.repo.closeMarriageVote(guildId,id);else if(kind==='adoption_expire')result=await this.repo.expireAdoption(guildId,id);else if(kind==='auction_close')result=await this.repo.closeAuction(guildId,id);else if(kind==='estate_execute')result=await this.repo.executeEstate(guildId,id);else throw new DomainError('FAMILY_JOB','Unknown family job.');if(result.jobId)await this.publish(client,result.jobId);await this.refresh(client,id);}
}
