import {createHash} from 'node:crypto';
import {ActionRowBuilder,AttachmentBuilder,ButtonBuilder,ButtonStyle,TextDisplayBuilder,ModalBuilder,PermissionFlagsBits,TextInputBuilder,TextInputStyle,type ButtonInteraction,type ChatInputCommandInteraction,type Client,type ModalSubmitInteraction} from 'discord.js';
import {DeliveryEngine,DomainError,type ConfigService} from '../../../../packages/core/src/index.js';
import {PrismaIntroductionsRepository,type PublishedIntroSettings,type IntroJob} from '../../../../packages/features-introductions/src/prisma-repository.js';
import {activePrompts,promptPages,type IntroContext,type IntroDraft} from '../../../../packages/features-introductions/src/domain.js';
import {renderIntroductionFields,renderIntroductionHub} from '../../../../packages/features-introductions/src/render.js';
import {displayFrames,wideDisplay,displayNotice,createDisplay} from './wide-display.js';
import {memberArt} from './member-art.js';
type Interaction=ChatInputCommandInteraction|ButtonInteraction|ModalSubmitInteraction;
export const INTRODUCTION_COMMANDS=new Set(['introduce','intro-config']);
const missing=(error:unknown)=>typeof error==='object'&&error!==null&&'code'in error&&error.code===10008;
async function notice(text:string,fields:string[]=[],identity='introduction-window'){const svg=renderIntroductionHub(text,fields);return displayFrames(svg,identity+'-'+createHash('sha256').update(svg).digest('hex').slice(0,12),text);}
// Keep recognizing old hidden embed URLs; new V2 cards recover via opaque attachment identity.
export const introductionDeliveryUrl=(marker:string)=>'https://discord.com/#'+createHash('sha256').update(marker).digest('hex');
export const introductionDeliveryKey=(marker:string)=>'introduction-'+createHash('sha256').update(marker).digest('hex').slice(0,32);
const hasDelivery=(message:{embeds:readonly {url?:string|null;footer?:{text:string}|null}[];attachments?:{values:()=>IterableIterator<{name:string}>}},marker:string)=>message.embeds.some(e=>e.url===introductionDeliveryUrl(marker)||e.footer?.text===marker)||[...message.attachments?.values()??[]].some(a=>a.name.startsWith(introductionDeliveryKey(marker)+'-'));
export function isIntroductionPanel(message:{components:readonly {toJSON:()=>unknown}[]}){
 const hasControl=(value:unknown):boolean=>{if(!value||typeof value!=='object')return false;const c=value as {custom_id?:string;components?:unknown[]};return c.custom_id==='intro:panel:create'||c.custom_id==='intro:panel:edit'||Boolean(c.components?.some(hasControl));};
 return message.components.some(c=>hasControl(c.toJSON()));
}
export class DiscordIntroductionsCoordinator {
 private sweeping=false;
 constructor(private repo:PrismaIntroductionsRepository,private config:ConfigService,private eligible:(guildId:string,userId:string)=>Promise<boolean>,private canManage:(guildId:string,userId:string)=>Promise<boolean>,private onPublished?:(guildId:string,userId:string,publicationId:string)=>Promise<void>){ }
 private async enabled(guildId:string){if(await this.config.get(guildId,'features.introductions')!==true)throw new DomainError('INTRO_DISABLED','Introductions are not enabled yet.');}
 private async setup(guildId:string){await this.enabled(guildId);const channel=await this.config.get(guildId,'channels.introduction_channel');if(typeof channel!=='string')throw new DomainError('INTRO_CHANNEL','The introductions channel is not configured.');const value=await this.config.get(guildId,'introductions.form');if(value!==null&&(typeof value!=='object'||Array.isArray(value)))throw new DomainError('INTRO_CONFIG','The introduction form configuration is invalid.');await this.repo.configure(guildId,channel,value as PublishedIntroSettings|null);return this.repo.configuration(guildId);}
 private async context(i:Interaction):Promise<IntroContext>{if(!i.guildId||!i.guild||!i.channelId)throw new DomainError('SERVER_ONLY','Use introductions in the server.');const {config}=await this.setup(i.guildId);if(config.introductionChannelId!==i.channelId)throw new DomainError('INTRO_CHANNEL',`Open introductions: https://discord.com/channels/${i.guildId}/${config.introductionChannelId}`);const member=await i.guild.members.fetch({user:i.user.id,force:true});if(member.user.bot||member.isCommunicationDisabled()||!member.permissionsIn(i.channelId).has(PermissionFlagsBits.ViewChannel)||!await this.eligible(i.guildId,i.user.id))throw new DomainError('INTRO_RESTRICTED','Introductions are unavailable to you here.');return{guildId:i.guildId,channelId:i.channelId,userId:i.user.id,requestKey:i.id};}
 async handle(i:Interaction){try{
  // A modal must be the initial response; every other action is acknowledged before reads.
  const opensModal=i.isButton()&&['page','create','edit'].includes(i.customId.split(':')[1]??'');
  if(!opensModal){if(i.isButton()&&i.customId.split(':')[1]!=='panel')await i.deferUpdate();else if(i.isModalSubmit()&&i.isFromMessage())await i.deferUpdate();else await i.deferReply({ephemeral:true});}
  const c=await this.context(i);
  if(i.isChatInputCommand()){
   if(i.commandName==='intro-config'){if(!await this.canManage(c.guildId,c.userId))throw new DomainError('INTRO_ADMIN','Introduction configuration requires authorized admin access.');const configured=await this.repo.configuration(c.guildId);await i.editReply({content:'Edit introductions.form in the admin dashboard using Draft → Preview → Publish. Stable prompt IDs preserve saved answers. Deleted prompts remain recoverable.',files:[new AttachmentBuilder(Buffer.from(JSON.stringify(configured,null,2)),{name:'introduction-configuration.json'})],allowedMentions:{parse:[]}});return;}
   const {id}=await this.repo.start(c);await this.hub(i,c,id);return;
  }
  const [prefix,action,id,versionArg,pageArg,layoutArg]=i.customId.split(':');if(prefix!=='intro'||!action||!id)throw new DomainError('INTRO_CONTROL','Open your introduction again.');
  if(action==='panel'){if(!i.isButton())throw new DomainError('INTRO_CONTROL','Use the introduction panel.');const {config}=await this.repo.configuration(c.guildId);if(i.message.id!==config.panelMessageId)throw new DomainError('INTRO_PANEL','Use the current introduction panel.');const draft=await this.repo.start(c);await this.hub(i,c,draft.id);return;}
  const row=await this.repo.view(c,id);
  if(['page','create','edit'].includes(action)&&i.isButton()){
   const prompts=promptPages(row.data.form,5)[0];if(!prompts||prompts.length>5)throw new DomainError('INTRO_PAGE','Open the current introduction form again.');
   const fields=prompts.map(prompt=>{const label=prompt.label.length>45?prompt.label.slice(0,44)+'…':prompt.label,placeholder=prompt.placeholder??(label===prompt.label?null:prompt.label);const input=new TextInputBuilder().setCustomId(prompt.id).setLabel(label).setStyle(prompt.inputStyle==='paragraph'?TextInputStyle.Paragraph:TextInputStyle.Short).setRequired(prompt.required).setMaxLength(prompt.maxLength);if(prompt.minLength!==null)input.setMinLength(prompt.minLength);if(placeholder)input.setPlaceholder(placeholder);const saved=row.data.answers[prompt.id];if(saved)input.setValue(saved);return new ActionRowBuilder<TextInputBuilder>().addComponents(input);});
   const modal=new ModalBuilder().setCustomId(`intro:save:${id}:${row.version}:0:fields`).setTitle('Your introduction').addComponents(...fields);
   await i.showModal(modal);return;
  }
  if(action==='save'&&i.isModalSubmit()){
   const pageSize=5,page=Number(pageArg),prompts=promptPages(row.data.form,pageSize)[page];if(!prompts)throw new DomainError('INTRO_PAGE','Open a current form page.');await this.repo.save(c,id,Number(versionArg),page,Object.fromEntries(prompts.map(p=>[p.id,i.fields.getTextInputValue(p.id)])),pageSize);
   await this.hub(i,c,id);return;
  }
  if(action==='preview'&&i.isButton()){await this.repo.preview(c,id);const updated=await this.repo.view(c,id),data=updated.data;const payload=await this.cardPayload(i.client,c.guildId,c.userId,data,'intro-preview:'+id);await i.editReply({...payload,components:[...payload.components,new TextDisplayBuilder().setContent('Private preview. Nothing is published until you choose Publish.'),new ActionRowBuilder<ButtonBuilder>().addComponents(this.button('publish',id,updated.version,0,'Publish',ButtonStyle.Primary),this.button('back',id,updated.version,0,'Go Back'))]});return;}
  if(action==='publish'&&i.isButton()){const job=await this.repo.enqueue(c,id,Number(versionArg));await this.publish(i.client,job.jobId);const published=await this.repo.submission(c.guildId,c.userId);await i.editReply(displayNotice(`Your introduction is published: https://discord.com/channels/${c.guildId}/${published!.outputChannelId}/${published!.outputMessageId}`));return;}
  if(action==='back'&&i.isButton()){await this.hub(i,c,id,Number(pageArg));return;}
  throw new DomainError('INTRO_CONTROL','Open the current introduction controls.');
 }catch(error){const text=error instanceof DomainError?error.message:'This introduction could not be completed. A submitted publication may still be awaiting confirmation; do not create another post.';const payload={content:text,files:[],attachments:[],embeds:[],components:[],allowedMentions:{parse:[] as never[]}};if(i.deferred)await i.editReply(displayNotice(text));else if(i.replied)await i.followUp({...payload,ephemeral:true});else await i.reply({...payload,ephemeral:true});}}
 private button(action:string,id:string,version:number,page:number,label:string,style=ButtonStyle.Secondary){return new ButtonBuilder().setCustomId(`intro:${action}:${id}:${version}:${page}`).setLabel(label).setStyle(style);}
 private async hub(i:Interaction,c:IntroContext,id:string,_page?:number){
  const row=await this.repo.view(c,id),saved=await this.repo.submission(c.guildId,c.userId);
  const controls=new ActionRowBuilder<ButtonBuilder>().addComponents(this.button('create',id,row.version,0,'Create Introduction',ButtonStyle.Primary),this.button('edit',id,row.version,0,'Edit My Introduction'),this.button('preview',id,row.version,0,'Preview'));
  const text='Private form. Answer the five fields in your own words; leave optional answers blank. Answers stay private until you choose Publish.';
  await i.editReply(wideDisplay(await notice(saved?'Your saved introduction is ready to edit. Changes update your existing post.':'Welcome to Chairs. Tell us a little about yourself.',activePrompts(row.data.form).map(p=>p.label)),[controls],text,!i.isChatInputCommand()?i.message?.attachments?.values():undefined));
 }
 async cardPayload(client:Client,guildId:string,userId:string,draft:IntroDraft,marker:string){
  const guild=await client.guilds.fetch(guildId),member=await guild.members.fetch({user:userId,force:true}),name=member.displayName,art=draft.config.showAvatar?await memberArt(client,guildId,userId):undefined;
  const fields=activePrompts(draft.form).filter(p=>p.showOnCard).map(p=>({label:p.cardLabel,answer:draft.answers[p.id]??''}));
  const svg=renderIntroductionFields(fields,draft.config.showDisplayName?name:'',art?.avatarData,draft.config.showAvatar,draft.config.footerText,{headerText:draft.config.headerText,...(draft.config.showJoinDate&&member.joinedAt?{joinedAt:member.joinedAt.toISOString().slice(0,10)}:{})});
  return wideDisplay(await displayFrames(svg,introductionDeliveryKey(marker)+'-card','Introduction � '+name,1));
 }
 async publish(client:Client,id:string){const row=await this.repo.job(id),p=row.payload;await this.enabled(row.guildId);if(!await this.eligible(row.guildId,p.userId))throw new DomainError('INTRO_RESTRICTED','This member is not currently eligible to publish.');const guild=await client.guilds.fetch(row.guildId),member=await guild.members.fetch({user:p.userId,force:true});if(member.isCommunicationDisabled()||!member.permissionsIn(p.channelId).has(PermissionFlagsBits.ViewChannel))throw new DomainError('INTRO_RESTRICTED','This member cannot access the introductions channel.');const channel=await client.channels.fetch(p.channelId);if(!channel?.isSendable()||!('messages'in channel))throw new DomainError('INTRO_CHANNEL','The introduction destination is unavailable.');
  const marker='intro:'+id,find=async()=>{if(p.priorMessageId){try{const old=await channel.messages.fetch(p.priorMessageId);if(old.author.id===client.user?.id&&hasDelivery(old,marker))return old.id;}catch(error){if(!missing(error))throw error;}}const messages=await channel.messages.fetch({limit:100});return messages.find(m=>m.author.id===client.user?.id&&hasDelivery(m,marker))?.id??null;};
  await new DeliveryEngine(this.repo.delivery(id)).deliver(marker,{find,send:async()=>{const payload=await this.cardPayload(client,row.guildId,p.userId,p.draft,marker);if(p.priorMessageId){let previous;try{previous=await channel.messages.fetch(p.priorMessageId);}catch(error){if(!missing(error))throw error;}if(previous){if(previous.author.id!==client.user?.id)throw new DomainError('INTRO_AUTHOR','The existing introduction is not bot-authored.');await previous.edit(payload);return previous.id;}}return(await channel.send(createDisplay(payload))).id;}});const result=await this.repo.finalize(id);await this.onPublished?.(row.guildId,p.userId,id);await this.sweep(client);return result;
 }
 async publishPanel(client:Client,id:string){const row=await this.repo.panelDeliveryJob(id);await this.enabled(row.guildId);const channel=await client.channels.fetch(row.payload.channelId);if(!channel?.isSendable()||!('messages'in channel))throw new DomainError('INTRO_CHANNEL','The introduction panel destination is unavailable.');// The durable job records the old panel; remove it before sending to avoid duplicates.
  const oldId=row.payload.oldPanelMessageId;
  if(oldId&&oldId!==row.payload.deliveryMessageId){try{const old=await channel.messages.fetch(oldId);if(old.author.id!==client.user?.id||!isIntroductionPanel(old))throw new DomainError('INTRO_PANEL_AUTHOR','The saved message is not an introduction control panel.');await old.delete();}catch(error){if(!missing(error))throw error;}}
  const marker='intro-panel:'+id;await new DeliveryEngine(this.repo.delivery(id)).deliver(marker,{find:async()=>{const messages=await channel.messages.fetch({limit:100});return messages.find(m=>m.author.id===client.user?.id&&hasDelivery(m,marker))?.id??null;},send:async()=>{return(await channel.send(createDisplay(wideDisplay(await notice('New here? Pull up a chair and introduce yourself.',[],introductionDeliveryKey(marker)),[new ActionRowBuilder<ButtonBuilder>().addComponents(new ButtonBuilder().setCustomId('intro:panel:create').setLabel('Create Introduction').setStyle(ButtonStyle.Primary),new ButtonBuilder().setCustomId('intro:panel:edit').setLabel('Edit My Introduction').setStyle(ButtonStyle.Secondary))])))).id;}});await this.repo.finalizePanel(id);}
 async sweep(client:Client){if(this.sweeping)return;this.sweeping=true;try{for(const guild of client.guilds.cache.values()){if(await this.config.get(guild.id,'features.introductions')===true)await this.setup(guild.id);}await this.repo.expireDrafts();for(const row of await this.repo.configuredServers()){if(await this.config.get(row.guildId,'features.introductions')!==true)continue;const channel=await client.channels.fetch(row.introductionChannelId!);if(!channel?.isTextBased()||!('messages'in channel))continue;if(row.panelMessageId){try{const message=await channel.messages.fetch(row.panelMessageId);if(message.author.id!==client.user?.id||!isIntroductionPanel(message))throw new DomainError('INTRO_PANEL_AUTHOR','The saved message is not an introduction control panel.');const latest=await channel.messages.fetch({limit:1});if(latest.first()?.id===message.id)continue;}catch(error){if(!missing(error))throw error;}}const job=await this.repo.panelJob(row.guildId,row.panelMessageId);await this.publishPanel(client,job.jobId);}}finally{this.sweeping=false;}}
}
