import {lessonCopy} from '../../../../packages/features-learning/src/tutorial-content.js';
import {ActionRowBuilder,AttachmentBuilder,ButtonBuilder,ButtonStyle,EmbedBuilder,PermissionFlagsBits,StringSelectMenuBuilder,type AutocompleteInteraction,type ButtonInteraction,type ChatInputCommandInteraction,type StringSelectMenuInteraction} from 'discord.js';
import {COMMANDS} from '../../../../packages/contracts/src/generated/commands.js';
import type {CommandContract} from '../../../../packages/contracts/src/types.js';
import {DomainError,PermissionEngine,type ConfigService} from '../../../../packages/core/src/index.js';
import {PrismaLearningRepository} from '../../../../packages/features-learning/src/prisma-repository.js';
import {LORE_CHAPTERS,validateReadingPage,TUTORIAL_PATHS,conversationSnapshot,tldrDuration} from '../../../../packages/features-learning/src/domain.js';
import {brandedNotice} from '../../../../packages/features-events/src/gate-b-visual.js';
import {rasterizeSvg} from '../../../../packages/renderer/src/raster.js';
type Interaction=ChatInputCommandInteraction|ButtonInteraction|StringSelectMenuInteraction;
const buttons=(rows:{id:string;label:string;disabled?:boolean}[])=>new ActionRowBuilder<ButtonBuilder>().addComponents(rows.map(r=>new ButtonBuilder().setCustomId(r.id).setLabel(r.label).setStyle(ButtonStyle.Secondary).setDisabled(r.disabled??false)));
const pathModules:Record<string,string[]>={discord:['core'],start:['onboarding','roles','lore','introductions'],identity:['profile','roles'],economy:['economy','items'],games:['casino','race','fight','line','party_games','pvp','solo_games','special_commands'],family:['crime','family'],music:['music'],community:['community','chairisms','introductions','social'],safety:['privacy','jail','moderation','security'],staff:['moderation','security','jail'],admin:['dashboard','custom_commands']};
const flagKeys:Record<string,string>={profile:'features.profiles',economy:'features.learning',roles:'roles_panel.enabled',jail:'features.learning',moderation:'features.learning',security:'features.learning',music:'music.enabled',tutorial:'features.learning',lore:'features.lore',core:'features.learning'};
export class DiscordLearningCoordinator {
 constructor(private repo:PrismaLearningRepository,private config:ConfigService,private eligible:(g:string,u:string)=>Promise<boolean>,private runtimeEnabled:(flag:string)=>boolean=()=>true){}
 private async allowed(i:Interaction|AutocompleteInteraction){
  const member=await i.guild!.members.fetch({user:i.user.id,force:true}),owner=i.guild!.ownerId===i.user.id,admin=member.permissions.has(PermissionFlagsBits.Administrator);
  const roles=await Promise.all(['roles.recliner','roles.chaise_lounge','roles.throne'].map(k=>this.config.get(i.guildId!,k)));
  const labels=new Set(['member',...(owner?['throne','guild_owner']:[]),...(admin?['discord_administrator']:[])]);roles.forEach((r,n)=>{if(typeof r==='string'&&member.roles.cache.has(r))labels.add(['recliner','chaise_lounge','throne'][n]!);});
  const result:CommandContract[]=[];for(const c of COMMANDS as readonly CommandContract[]){if(c.type!=='slash'||!this.runtimeEnabled(c.featureFlag)||![...labels].filter(p=>['member','recliner','chaise_lounge','throne'].includes(p)).some(p=>new PermissionEngine({command:c.permissions as ('member'|'recliner'|'chaise_lounge'|'throne')[]}).can(p as 'member','command')))continue;if(c.module==='dashboard'&&!owner&&!admin)continue;if(c.id==='notmad'&&!owner)continue;const key=flagKeys[c.featureFlag]??'features.'+c.featureFlag;if(!this.config.definition(key)||await this.config.get(i.guildId!,key)!==true)continue;result.push(c);}return result;
 }
 async autocomplete(i:AutocompleteInteraction){if(!i.guildId||!i.guild||await this.config.get(i.guildId,'features.learning')!==true||!await this.eligible(i.guildId,i.user.id)){await i.respond([]);return;}const query=String(i.options.getFocused()).toLowerCase();const commands=await this.allowed(i);await i.respond(commands.filter(c=>(c.registered+' '+c.id).toLowerCase().includes(query)).slice(0,25).map(c=>({name:c.registered.slice(0,100),value:c.id})));}
 private async window(i:Interaction,title:string,copy:string,components:(ActionRowBuilder<ButtonBuilder>|ActionRowBuilder<StringSelectMenuBuilder>)[]=[]){const png=await rasterizeSvg(brandedNotice(title,copy,'ANGRIER JORDAN · LEARN & BELONG'));await i.editReply({embeds:[new EmbedBuilder().setAuthor({name:'Angrier Jordan'}).setTitle(title).setDescription(copy.slice(0,4000)).setImage('attachment://learning-window.png')],files:[new AttachmentBuilder(png,{name:'learning-window.png'})],components,allowedMentions:{parse:[]}});}
 async handle(i:Interaction){try{
  if(!i.guildId||!i.guild)throw new DomainError('SERVER_ONLY','Use this in the server.');if(!await this.eligible(i.guildId,i.user.id))throw new DomainError('LEARNING_RESTRICTED','This interaction is unavailable while restricted.');
  const parts=i.isChatInputCommand()?[]:i.customId.split(':'),kind=i.isChatInputCommand()?i.commandName:parts[1];if(parts.length&&parts[2]!==i.user.id)throw new DomainError('LEARNING_OWNER','Open your own private window.');
  const key=kind==='lore'?'features.lore':kind==='tldr'?'features.tldr':'features.learning';if(await this.config.get(i.guildId,key)!==true)throw new DomainError('LEARNING_DISABLED','This feature is not enabled yet.');await i.deferReply({ephemeral:true});
  if(parts[3]==='exit'){await this.window(i,'Window dismissed','You can return whenever you like.');return;}
  if(kind==='lore'){
   const chapters=await this.repo.chapters(),progress=await this.repo.loreProgress(i.guildId,i.user.id);
   const selected=i.isStringSelectMenu()?i.values[0]:parts[3];
   if(!selected||selected==='toc'){const ready=chapters.map(c=>({label:c.title,value:c.id,description:progress.some(p=>p.chapterId===c.id&&p.contentVersion===c.version&&p.completedAt)?'Read · open again':'Read or resume'}));await this.window(i,'The Story So Far',ready.length?'Choose a chapter. Your reading progress is private and saved.':'The approved chapters have not been published yet. No reading credit has been awarded.',ready.length?[new ActionRowBuilder<StringSelectMenuBuilder>().addComponents(new StringSelectMenuBuilder().setCustomId('learn:lore:'+i.user.id+':select').setPlaceholder('Read the lore').addOptions(ready))]:[]);return;}
   const chapter=chapters.find(c=>c.id===selected);if(!chapter)throw new DomainError('LORE_MISSING','That chapter is unavailable.');const old=progress.find(p=>p.chapterId===chapter.id&&p.contentVersion===chapter.version);const page=i.isStringSelectMenu()?old?.currentPage??0:Number(parts[4]??0);const version=i.isStringSelectMenu()?chapter.version:Number(parts[5]);validateReadingPage(page,chapter,old?.currentPage??-1);if(version!==chapter.version)throw new DomainError('LORE_VERSION','This chapter changed. Reopen Lore.');
   await this.window(i,chapter.title,chapter.pages[page]+'\n\nPage '+(page+1)+' of '+chapter.pages.length,[buttons([{id:`learn:lore:${i.user.id}:${chapter.id}:${page-1}:${chapter.version}`,label:'Previous',disabled:page===0},{id:`learn:lore:${i.user.id}:${chapter.id}:${page+1}:${chapter.version}`,label:'Next',disabled:page===chapter.pages.length-1},{id:`learn:lore:${i.user.id}:toc`,label:'Contents'},{id:`learn:lore:${i.user.id}:exit`,label:'Dismiss'}])]);const result=await this.repo.read(i.guildId,i.user.id,chapter.id,page,version,i.id);if(result.newlyAwarded)await i.followUp({ephemeral:true,content:'Chair Historian · earned. Your reading progress is saved.',allowedMentions:{parse:[]}});return;
  }
  if(kind==='tldr'){const sub=i.isChatInputCommand()?i.options.getSubcommand():'',time=i.isChatInputCommand()?i.options.getString('time',true):'',duration=tldrDuration(sub,time),channel=await this.config.get(i.guildId,sub==='chat'?'channels.main_chat':'channels.bot_channel');if(i.channelId!==channel)throw new DomainError('TLDR_CHANNEL',typeof channel==='string'?`Use this recap in <#${channel}>.`:'The recap channel is not configured.');const until=new Date(),since=new Date(until.getTime()-duration);
   if(sub==='events'){const events=await this.repo.notableEvents(i.guildId,since,until),labels:Record<string,string>={'record.announce':'record announcements','spotlight.announce':'Weekly Spotlight announcements','casino.jackpot_announce':'Chair Pot announcements','lottery.announce':'lottery announcements','family.announce':'Family announcements'},counts=new Map<string,number>();for(const e of events)counts.set(e.jobType,(counts.get(e.jobType)??0)+1);await this.window(i,'Event activity snapshot','Limited deterministic snapshot of completed notable announcements; routine ledger entries are excluded.\n'+([...counts].map(([k,n])=>n+' '+labels[k]).join('\n')||'No matching completed announcements in this window.')+(events.length===100?'\nLimited to the latest 100.':''));return;}
   const member=await i.guild.members.fetch({user:i.user.id,force:true});const channelObject=await i.guild.channels.fetch(i.channelId,{force:true});if(!channelObject?.isTextBased()||!('messages' in channelObject)||!channelObject.permissionsFor(member)?.has([PermissionFlagsBits.ViewChannel,PermissionFlagsBits.ReadMessageHistory]))throw new DomainError('TLDR_ACCESS','Chat history is unavailable.');
   const rows:{bot:boolean;system:boolean;content:string;createdAt:Date}[]=[];let before:string|undefined,limited=false;for(let n=0;n<10;n++){const batch=await channelObject.messages.fetch({limit:100,...(before?{before}: {})});for(const m of batch.values())rows.push({bot:m.author.bot,system:m.system,content:m.content,createdAt:m.createdAt});const last=batch.last();if(!last||batch.size<100||last.createdAt<since)break;before=last.id;if(n===9)limited=true;}
   const refreshed=await i.guild.channels.fetch(i.channelId,{force:true});if(!refreshed?.permissionsFor(await i.guild.members.fetch({user:i.user.id,force:true}))?.has([PermissionFlagsBits.ViewChannel,PermissionFlagsBits.ReadMessageHistory]))throw new DomainError('TLDR_ACCESS','Chat history access changed.');const snapshot=conversationSnapshot(rows,since,until);await this.window(i,'Chat activity snapshot',`No conversation-summary provider is configured. This is a limited activity snapshot, not a summary of what members said.\n${snapshot.messages} human messages · ${snapshot.words} words in ${time}.`+(limited?'\nHistory capped at the latest 1,000 messages.':''));return;
  }
  const commands=await this.allowed(i);
  if(kind==='help'){const id=i.isChatInputCommand()?i.options.getString('command'):parts[3],command=commands.find(c=>c.id===id||c.registered===id);if(!command){await this.window(i,'Quick Help',commands.length?commands.slice(0,20).map(c=>c.registered).join('\n')+'\nUse /help command to search.':'No enabled commands are available in this view.');return;}await this.repo.tutorialStep(i.guildId,i.user.id,command.id,0,i.id);await this.lesson(i,command,0,true);return;}
  const action=parts[3];
  if(!action||action==='home'){await this.window(i,'Show Me Around','Choose a learning path. Lessons are private; practice never spends Ottomans or changes protected server state.',[new ActionRowBuilder<StringSelectMenuBuilder>().addComponents(new StringSelectMenuBuilder().setCustomId('learn:tutorial:'+i.user.id+':path').setPlaceholder('Choose a path').addOptions(TUTORIAL_PATHS.filter(([key])=>!['staff','admin'].includes(key)||commands.some(c=>pathModules[key]?.includes(c.module))).map(([value,label])=>({value,label})))),buttons([{id:'learn:tutorial:'+i.user.id+':progress',label:'Progress'},{id:'learn:tutorial:'+i.user.id+':continue',label:'Continue'},{id:'learn:tutorial:'+i.user.id+':exit',label:'Exit Tutorial'}])]);return;}
  if(action==='progress'||action==='continue'){const progress=await this.repo.tutorialProgress(i.guildId,i.user.id),visible=progress.filter(p=>commands.some(c=>c.id===p.lessonId));if(action==='continue'){const last=visible.sort((a,b)=>b.lastActivityAt.getTime()-a.lastActivityAt.getTime())[0],cmd=commands.find(c=>c.id===last?.lessonId);if(cmd&&last){await this.lesson(i,cmd,last.currentStep);return;}}await this.window(i,'Your Learning Progress',visible.map(p=>p.lessonId+': '+(p.completedAt?'complete':'step '+(p.currentStep+1))).join('\n')||'No lessons completed yet.');return;}
  if(action==='path'||action==='pathpage'){
   const path=i.isStringSelectMenu()?i.values[0]!:parts[4]!,visible=commands.filter(c=>path==='finder'||pathModules[path]?.includes(c.module));
   if(!TUTORIAL_PATHS.some(p=>p[0]===path))throw new DomainError('TUTORIAL_PATH','Choose an available learning path.');
   const requested=action==='pathpage'?Number(parts[5]):0,pages=Math.max(1,Math.ceil(visible.length/25));
   if(!Number.isInteger(requested)||requested<0||requested>=pages)throw new DomainError('TUTORIAL_PAGE','Reopen this learning path.');
   const controls:(ActionRowBuilder<ButtonBuilder>|ActionRowBuilder<StringSelectMenuBuilder>)[]=[];
   if(visible.length)controls.push(new ActionRowBuilder<StringSelectMenuBuilder>().addComponents(new StringSelectMenuBuilder().setCustomId('learn:tutorial:'+i.user.id+':lesson').setPlaceholder('Choose a command').addOptions(visible.slice(requested*25,(requested+1)*25).map(c=>({label:c.registered.slice(0,100),value:c.id})))));
   controls.push(buttons([{id:'learn:tutorial:'+i.user.id+':pathpage:'+path+':'+(requested-1),label:'Previous',disabled:requested===0},{id:'learn:tutorial:'+i.user.id+':pathpage:'+path+':'+(requested+1),label:'Next',disabled:requested===pages-1},{id:'learn:tutorial:'+i.user.id+':home',label:'Learning paths'}]));
   await this.window(i,TUTORIAL_PATHS.find(p=>p[0]===path)![1],visible.length?'Choose an enabled command to learn. Page '+(requested+1)+' of '+pages+'.':'No enabled lessons in this path yet.',controls);return;
  }
  const id=i.isStringSelectMenu()?i.values[0]:parts[4],command=commands.find(c=>c.id===id);if(!command)throw new DomainError('TUTORIAL_COMMAND','This command is unavailable.');const step=action==='lesson'?0:Number(parts[5]??0);if(action!=='practice')await this.repo.tutorialStep(i.guildId,i.user.id,command.id,step,i.id,action==='restart');await this.lesson(i,command,step,false,action==='practice');
 }catch(error){const content=error instanceof DomainError?error.message:'This private window could not be completed. Saved progress remains available.';if(i.deferred)await i.editReply({content,components:[],allowedMentions:{parse:[]}});else await i.reply({content,ephemeral:true,allowedMentions:{parse:[]}});}}
 private async lesson(i:Interaction,c:CommandContract,step:number,help=false,practice=false){const authored=lessonCopy(c);const fields=c.options.map(o=>`${o.name} (${o.required?'required':'optional'}): ${o.description||o.type}${o.choices?' · '+o.choices.join(' / '):''}`).join('\n');const example=c.registered+c.options.filter(o=>o.required).map(o=>' '+o.name+':'+(o.choices?.[0]??(o.type==='user'?'@member':o.type==='integer'?'10':o.name==='action'?'compliment':'example'))).join('');const pages=[c.registered+'\n'+authored.purpose,authored.fields,authored.steps.map((line,n)=>(n+1)+'. '+line).join('\n')+'\nExample: '+authored.example,'Lesson complete. No rewards or server changes were made.'];const text=practice?'Practice simulation only. Review the example and its fields; no command is executed.\n'+example:help?pages[0]+'\n'+fields+'\n'+example:pages[step]??pages[0]!;await this.window(i,help?'Quick Help':'Walk Me Through It',text!,[buttons([{id:`learn:tutorial:${i.user.id}:step:${c.id}:${Math.max(0,step-1)}`,label:'Back',disabled:step===0},{id:`learn:tutorial:${i.user.id}:step:${c.id}:${Math.min(3,step+1)}`,label:'Next',disabled:step===3},{id:`learn:tutorial:${i.user.id}:practice:${c.id}:${step}`,label:'Practice'},{id:`learn:tutorial:${i.user.id}:restart:${c.id}:0`,label:'Restart'},{id:`learn:tutorial:${i.user.id}:exit`,label:'Exit Tutorial'}])]);}
}
