import {lessonCopy,hasAuthoredLesson} from '../../../../packages/features-learning/src/tutorial-content.js';
import {ActionRowBuilder,ButtonBuilder,ButtonStyle,PermissionFlagsBits,StringSelectMenuBuilder,type AutocompleteInteraction,type ButtonInteraction,type ChatInputCommandInteraction,type StringSelectMenuInteraction} from 'discord.js';
import {COMMANDS} from '../../../../packages/contracts/src/generated/commands.js';
import type {CommandContract} from '../../../../packages/contracts/src/types.js';
import {DomainError,PermissionEngine,type ConfigService} from '../../../../packages/core/src/index.js';
import {PrismaLearningRepository} from '../../../../packages/features-learning/src/prisma-repository.js';
import {LORE_CHAPTERS,validateReadingPage,TUTORIAL_PATHS,conversationSnapshot,tldrDuration} from '../../../../packages/features-learning/src/domain.js';
import {learningWindow} from '../../../../packages/features-learning/src/visual.js';
import {createHash} from 'node:crypto';
import {displayFrames,wideDisplay,displayNotice,type DisplayFrame} from './wide-display.js';
type Interaction=ChatInputCommandInteraction|ButtonInteraction|StringSelectMenuInteraction;
const buttons=(rows:{id:string;label:string;disabled?:boolean;reset?:boolean;primary?:boolean}[])=>new ActionRowBuilder<ButtonBuilder>().addComponents(rows.map(r=>new ButtonBuilder().setCustomId(r.id).setLabel(r.label).setStyle(r.reset?ButtonStyle.Danger:r.primary?ButtonStyle.Primary:ButtonStyle.Secondary).setDisabled(r.disabled??false)));
const pathModules:Record<string,string[]>={discord:['core'],start:['onboarding','roles','lore','introductions'],identity:['profile','roles'],economy:['economy','items'],games:['casino','race','fight','line','party_games','pvp','solo_games','special_commands'],family:['crime','family'],community:['community','chairisms','introductions','social'],safety:['privacy','jail','moderation','security'],staff:['moderation','security','jail'],admin:['dashboard','custom_commands']};
const flagKeys:Record<string,string>={profile:'features.profiles',economy:'features.learning',roles:'roles_panel.enabled',jail:'features.learning',moderation:'features.learning',security:'features.learning',tutorial:'features.learning',lore:'features.lore',core:'features.learning'};
export interface HelpDirectoryCategory {label:string;commands:CommandContract[]}
/** Whole categories remain together after existing authority/feature filtering. Empty topic pages disappear. */
export function helpDirectoryPages(commands:readonly CommandContract[]):HelpDirectoryCategory[][]{
 const topics=[['core','community','chairisms','introductions','roles','lore'],['economy','items','crime','family','collections'],['casino','solo_games','party_games','pvp','fight','race','line'],['profile','records','social','special_commands','tutorial','privacy','moderation','jail','security','custom_commands','bootstrap','dashboard']];
 const labels:Record<string,string>={core:'Core',community:'Community',chairisms:'Chairisms',introductions:'Introductions',roles:'Roles',lore:'Lore',economy:'Economy',items:'Items',crime:'Crime',family:'Family',collections:'Collections',casino:'Casino',solo_games:'Solo games',party_games:'Party games',pvp:'PvP games',fight:'Fight',profile:'Profile',records:'Records',social:'Social',special_commands:'Special Commands',tutorial:'Tutorial',privacy:'Privacy',moderation:'Staff moderation',jail:'Jail & restrictions',security:'Staff safety',custom_commands:'Custom Commands',bootstrap:'Server setup',dashboard:'Server management'};
 const known=new Set(topics.flat());topics[4]!.push(...[...new Set(commands.map(c=>c.module))].filter(m=>!known.has(m)).sort());
 const pages=topics.map(modules=>modules.flatMap(module=>{const rows=commands.filter(c=>c.module===module).sort((a,b)=>a.registered.localeCompare(b.registered));return rows.length?[{label:labels[module]??module.replaceAll('_',' '),commands:rows}]:[];})).filter(page=>page.length);
 return pages.length?pages:[[]];
}
export class DiscordLearningCoordinator {
 constructor(private repo:PrismaLearningRepository,private config:ConfigService,private eligible:(g:string,u:string)=>Promise<boolean>,private runtimeEnabled:(flag:string)=>boolean=()=>true,private specialCommands:(g:string,u:string,roles:ReadonlySet<string>)=>Promise<{trigger:string}[]>=async()=>[],private onLoreChapter?:(guildId:string,userId:string,chapterId:string)=>Promise<void>){}
 private async allowed(i:Interaction|AutocompleteInteraction){
  const member=await i.guild!.members.fetch({user:i.user.id,force:true}),owner=i.guild!.ownerId===i.user.id,admin=member.permissions.has(PermissionFlagsBits.Administrator);
  const roles=await Promise.all(['roles.recliner','roles.chaise_lounge','roles.throne'].map(k=>this.config.get(i.guildId!,k)));
  const labels=new Set(['member',...(owner?['throne','guild_owner']:[]),...(admin?['discord_administrator']:[])]);roles.forEach((r,n)=>{if(typeof r==='string'&&member.roles.cache.has(r))labels.add(['recliner','chaise_lounge','throne'][n]!);});
  const specials=await this.specialCommands(i.guildId!,i.user.id,new Set(member.roles.cache.keys()));
  const flags=new Map<string,Promise<unknown>>();const flag=(key:string)=>{let value=flags.get(key);if(!value){value=this.config.get(i.guildId!,key);flags.set(key,value);}return value;};
  const result:CommandContract[]=[];for(const c of COMMANDS as readonly CommandContract[]){if((c.type!=='slash'&&!c.registered.startsWith('!'))||(c.module==='special_commands'||c.featureFlag==='line')&&!specials.some(s=>s.trigger===c.registered)||!this.runtimeEnabled(c.featureFlag)||![...labels].filter(p=>['member','recliner','chaise_lounge','throne'].includes(p)).some(p=>new PermissionEngine({command:c.permissions as ('member'|'recliner'|'chaise_lounge'|'throne')[]}).can(p as 'member','command')))continue;if(c.module==='dashboard'&&!owner&&!admin)continue;if(c.id==='notmad'&&!owner)continue;const key=flagKeys[c.featureFlag]??'features.'+c.featureFlag;if(!this.config.definition(key)||await flag(key)!==true)continue;result.push(c);}
  for(const special of specials){if(result.some(c=>c.registered===special.trigger))continue;result.push({id:'special_custom_'+special.trigger.slice(1),preferred:special.trigger,registered:special.trigger,type:'special_text',module:'special_commands',handler:'special.custom',featureFlag:'special_commands',permissions:['member'],channels:['main_chat'],options:[],ephemeralDefault:false,helpId:'special',tutorialId:'special_commands'});}
  return result.map(c=>c.id==='special_vc'?{...c,registered:'!VC'}:c.id==='special_chess'?{...c,registered:'!Chess'}:c);
 }
 async autocomplete(i:AutocompleteInteraction){if(!i.guildId||!i.guild||await this.config.get(i.guildId,'features.learning')!==true||!await this.eligible(i.guildId,i.user.id)){await i.respond([]);return;}const query=String(i.options.getFocused()).toLowerCase();const commands=await this.allowed(i);await i.respond(commands.filter(c=>(c.registered+' '+c.id).toLowerCase().includes(query)).slice(0,25).map(c=>({name:c.registered.slice(0,100),value:c.id})));}
 private readonly artwork=new Map<string,Promise<DisplayFrame[]>>();
 private async window(i:Interaction,title:string,copy:string,components:(ActionRowBuilder<ButtonBuilder>|ActionRowBuilder<StringSelectMenuBuilder>)[]=[]){
  if(!components.length&&copy.length<240&&!title.includes('snapshot')){await i.editReply(displayNotice(copy));return;}
  const svg=learningWindow(title,copy),name='learning-'+createHash('sha256').update(svg).digest('hex').slice(0,16);
  let art=this.artwork.get(name);if(!art){art=displayFrames(svg,name,title+'. '+copy).catch(error=>{this.artwork.delete(name);throw error;});this.artwork.set(name,art);if(this.artwork.size>32)this.artwork.delete(this.artwork.keys().next().value!);}
  await i.editReply(wideDisplay(await art,components,undefined,!i.isChatInputCommand()?i.message?.attachments?.values():undefined));
 }
 async handle(i:Interaction){try{
  if(!i.guildId||!i.guild)throw new DomainError('SERVER_ONLY','Use this in the server.');
  const parts=i.isChatInputCommand()?[]:i.customId.split(':'),kind=i.isChatInputCommand()?i.commandName:parts[1];if(parts.length&&parts[2]!==i.user.id)throw new DomainError('LEARNING_OWNER','Open your own private window.');
  if(i.isChatInputCommand())await i.deferReply({ephemeral:true});else await i.deferUpdate();
  if(!await this.eligible(i.guildId,i.user.id))throw new DomainError('LEARNING_RESTRICTED','This interaction is unavailable while restricted.');
  const key=kind==='lore'?'features.lore':kind==='tldr'?'features.tldr':'features.learning';if(await this.config.get(i.guildId,key)!==true)throw new DomainError('LEARNING_DISABLED','This feature is not enabled yet.');
  if(parts[3]==='exit'){await this.window(i,'Window dismissed','You can return whenever you like.');return;}
  if(kind==='lore'){
   const chapters=await this.repo.chapters(),progress=await this.repo.loreProgress(i.guildId,i.user.id);
   const selected=i.isStringSelectMenu()?i.values[0]:parts[3];
   if(!selected||selected==='toc'){const ready=chapters.map(c=>({label:c.title,value:c.id,description:progress.some(p=>p.chapterId===c.id&&p.contentVersion===c.version&&p.completedAt)?'Read · open again':'Read or resume'}));await this.window(i,'The Story So Far',ready.length?'Choose a chapter. Your reading progress is private and saved.':'The approved chapters have not been published yet. No reading credit has been awarded.',ready.length?[new ActionRowBuilder<StringSelectMenuBuilder>().addComponents(new StringSelectMenuBuilder().setCustomId('learn:lore:'+i.user.id+':select').setPlaceholder('Read the lore').addOptions(ready))]:[]);return;}
   const chapter=chapters.find(c=>c.id===selected);if(!chapter)throw new DomainError('LORE_MISSING','That chapter is unavailable.');const old=progress.find(p=>p.chapterId===chapter.id&&p.contentVersion===chapter.version);const page=i.isStringSelectMenu()?old?.currentPage??0:Number(parts[4]??0);const version=i.isStringSelectMenu()?chapter.version:Number(parts[5]);validateReadingPage(page,chapter,old?.currentPage??-1);if(version!==chapter.version)throw new DomainError('LORE_VERSION','This chapter changed. Reopen Lore.');
   await this.window(i,chapter.title,chapter.pages[page]+'\n\nPage '+(page+1)+' of '+chapter.pages.length,[buttons([{id:`learn:lore:${i.user.id}:${chapter.id}:${page-1}:${chapter.version}`,label:'Previous',disabled:page===0},{id:`learn:lore:${i.user.id}:${chapter.id}:${page+1}:${chapter.version}`,label:'Next',disabled:page===chapter.pages.length-1},{id:`learn:lore:${i.user.id}:toc`,label:'Contents'},{id:`learn:lore:${i.user.id}:exit`,label:'Dismiss'}])]);const result=await this.repo.read(i.guildId,i.user.id,chapter.id,page,version,i.id);if(page===chapter.pages.length-1)await this.onLoreChapter?.(i.guildId,i.user.id,chapter.id);if(result.newlyAwarded)await i.followUp({ephemeral:true,content:'Chair Historian · earned. Your reading progress is saved.',allowedMentions:{parse:[]}});return;
  }
  if(kind==='tldr'){const sub=i.isChatInputCommand()?i.options.getSubcommand():'',time=i.isChatInputCommand()?i.options.getString('time',true):'',duration=tldrDuration(sub,time),channel=await this.config.get(i.guildId,sub==='chat'?'channels.main_chat':'channels.bot_channel');if(i.channelId!==channel)throw new DomainError('TLDR_CHANNEL',typeof channel==='string'?`Use this recap in <#${channel}>.`:'The recap channel is not configured.');const until=new Date(),since=new Date(until.getTime()-duration);
   if(sub==='events'){const events=await this.repo.notableEvents(i.guildId,since,until),labels:Record<string,string>={'record.announce':'record announcements','spotlight.announce':'Weekly Spotlight announcements','casino.jackpot_announce':'Chair Pot announcements','lottery.announce':'lottery announcements','family.publish':'Family announcements'},counts=new Map<string,number>();for(const e of events)counts.set(e.jobType,(counts.get(e.jobType)??0)+1);await this.window(i,'Event activity snapshot','EVENT COUNTS · '+time+'\nConfirmed server announcements in this window.\n\n'+([...counts].map(([k,n])=>n+' '+labels[k]).join('\n')||'No announcements in this window.')+(events.length===100?'\nLimited to the latest 100.':''));return;}
   const member=await i.guild.members.fetch({user:i.user.id,force:true});const channelObject=await i.guild.channels.fetch(i.channelId,{force:true});if(!channelObject?.isTextBased()||!('messages' in channelObject)||!channelObject.permissionsFor(member)?.has([PermissionFlagsBits.ViewChannel,PermissionFlagsBits.ReadMessageHistory]))throw new DomainError('TLDR_ACCESS','Chat history is unavailable.');
   const rows:{bot:boolean;system:boolean;content:string;createdAt:Date}[]=[];let before:string|undefined,limited=false;for(let n=0;n<10;n++){const batch=await channelObject.messages.fetch({limit:100,...(before?{before}: {})});for(const m of batch.values())rows.push({bot:m.author.bot,system:m.system,content:m.content,createdAt:m.createdAt});const last=batch.last();if(!last||batch.size<100||last.createdAt<since)break;before=last.id;if(n===9)limited=true;}
   const refreshed=await i.guild.channels.fetch(i.channelId,{force:true});if(!refreshed?.permissionsFor(await i.guild.members.fetch({user:i.user.id,force:true}))?.has([PermissionFlagsBits.ViewChannel,PermissionFlagsBits.ReadMessageHistory]))throw new DomainError('TLDR_ACCESS','Chat history access changed.');const snapshot=conversationSnapshot(rows,since,until);await this.window(i,'Chat activity snapshot',`CHAT COUNTS · ${time}\n\n${snapshot.messages} member messages\n${snapshot.words} words\n\nActivity totals only; this does not summarize the conversation.`+(limited?'\nHistory capped at the latest 1,000 messages.':''));return;
  }
  const commands=await this.allowed(i);
  if(kind==='help'){
   const id=i.isChatInputCommand()?i.options.getString('command'):parts[3],command=commands.find(c=>c.id===id||c.registered===id);
   if(command){await this.repo.tutorialStep(i.guildId,i.user.id,command.id,0,i.id);await this.lesson(i,command,0,true);return;}
   const page=id==='directory'?Number(parts[4]):0,directory=helpDirectoryPages(commands),pages=directory.length;
   if(!Number.isInteger(page)||page<0||page>=pages)throw new DomainError('HELP_PAGE','Reopen Help to browse available commands.');
   const groups=new Map(directory[page]!.map(group=>[group.label.toUpperCase(),group.commands.map(c=>c.registered)]));
   await this.window(i,'Your command directory',[...groups].map(([label,names])=>label+'\n'+names.join('  ·  ')).join('\n\n')+'\n\nSearch with /help command. Page '+(page+1)+' of '+pages,[buttons([{id:'learn:help:'+i.user.id+':directory:'+(page-1),label:'Previous',disabled:page===0},{id:'learn:help:'+i.user.id+':directory:'+(page+1),label:'Next',disabled:page===pages-1}])]);return;
  }
  const lessonCommands=commands.filter(hasAuthoredLesson);
  const action=parts[3];
  if((!action||action==='home')&&!lessonCommands.length){await i.editReply(displayNotice('No lessons are available to you yet. Your saved progress is safe; check back when a learning path is available.',[buttons([{id:'learn:tutorial:'+i.user.id+':exit',label:'Exit Tutorial'}])]));return;}
  if(!action||action==='home'){await this.window(i,'Show Me Around','LEARNING PATHS\nChoose a subject using the menu below.\n\nYOUR JOURNEY\nLearning path → Lesson → Practice → Progress\n\nPRIVATE & SAFE\nLessons save your place. Practice never spends Ottomans or changes protected server state.',[new ActionRowBuilder<StringSelectMenuBuilder>().addComponents(new StringSelectMenuBuilder().setCustomId('learn:tutorial:'+i.user.id+':path').setPlaceholder('Choose a path').addOptions(TUTORIAL_PATHS.filter(([key])=>lessonCommands.some(c=>key==='finder'||pathModules[key]?.includes(c.module))).map(([value,label])=>({value,label})))),buttons([{id:'learn:tutorial:'+i.user.id+':progress',label:'Progress'},{id:'learn:tutorial:'+i.user.id+':continue',label:'Continue'},{id:'learn:tutorial:'+i.user.id+':exit',label:'Exit Tutorial'}])]);return;}
  if(action==='progress'||action==='continue'){const progress=await this.repo.tutorialProgress(i.guildId,i.user.id),visible=progress.filter(p=>lessonCommands.some(c=>c.id===p.lessonId));if(action==='continue'){const last=visible.sort((a,b)=>b.lastActivityAt.getTime()-a.lastActivityAt.getTime())[0],cmd=commands.find(c=>c.id===last?.lessonId);if(cmd&&last){await this.lesson(i,cmd,last.currentStep);return;}}await this.window(i,'Your Learning Progress',visible.map(p=>commands.find(c=>c.id===p.lessonId)!.registered+': '+(p.completedAt?'complete':'step '+(p.currentStep+1))).join('\n')||'No lessons completed yet.',[buttons([{id:'learn:tutorial:'+i.user.id+':home',label:'Learning Paths'},{id:'learn:tutorial:'+i.user.id+':continue',label:'Continue',primary:true},{id:'learn:tutorial:'+i.user.id+':exit',label:'Exit Tutorial'}])]);return;}
  if(action==='restartpathconfirm'){await this.window(i,'Restart this path?','This resets saved progress for the available lessons in this path. Your server state and Ottomans are unchanged.',[buttons([{id:'learn:tutorial:'+i.user.id+':restartpath:'+parts[4],label:'Restart path',reset:true},{id:'learn:tutorial:'+i.user.id+':pathpage:'+parts[4]+':0',label:'Go back'}])]);return;}
  if(action==='path'||action==='pathpage'||action==='restartpath'){
   const path=i.isStringSelectMenu()?i.values[0]!:parts[4]!,visible=lessonCommands.filter(c=>path==='finder'||pathModules[path]?.includes(c.module));
   if(!TUTORIAL_PATHS.some(p=>p[0]===path))throw new DomainError('TUTORIAL_PATH','Choose an available learning path.');
   if(action==='restartpath'&&visible.length)await this.repo.restartTutorialPath(i.guildId,i.user.id,visible.map(c=>c.id),i.id);
   const requested=action==='pathpage'?Number(parts[5]):0,pages=Math.max(1,Math.ceil(visible.length/25));
   if(!Number.isInteger(requested)||requested<0||requested>=pages)throw new DomainError('TUTORIAL_PAGE','Reopen this learning path.');
   const controls:(ActionRowBuilder<ButtonBuilder>|ActionRowBuilder<StringSelectMenuBuilder>)[]=[];
   if(visible.length)controls.push(new ActionRowBuilder<StringSelectMenuBuilder>().addComponents(new StringSelectMenuBuilder().setCustomId('learn:tutorial:'+i.user.id+':lesson').setPlaceholder('Choose a command').addOptions(visible.slice(requested*25,(requested+1)*25).map(c=>({label:c.registered.slice(0,100),value:c.id})))));
   controls.push(buttons([{id:'learn:tutorial:'+i.user.id+':pathpage:'+path+':'+(requested-1),label:'Previous',disabled:requested===0},{id:'learn:tutorial:'+i.user.id+':pathpage:'+path+':'+(requested+1),label:'Next',disabled:requested===pages-1},{id:'learn:tutorial:'+i.user.id+':home',label:'Learning Paths'}]),buttons([{id:'learn:tutorial:'+i.user.id+':restartpathconfirm:'+path,label:'Restart Path',reset:true,disabled:visible.length===0},{id:'learn:tutorial:'+i.user.id+':exit',label:'Exit Tutorial'}]));
   await this.window(i,TUTORIAL_PATHS.find(p=>p[0]===path)![1],visible.length?'CHOOSE YOUR LESSON\nExplore an available command using the menu below. Page '+(requested+1)+' of '+pages+'.':'No enabled lessons in this path yet.',controls);return;
  }
  if(action==='restartconfirm'){const command=lessonCommands.find(c=>c.id===parts[4]);if(!command)throw new DomainError('TUTORIAL_COMMAND','This command is unavailable.');await this.window(i,'Restart this lesson?','Your saved lesson will return to its first step.',[buttons([{id:'learn:tutorial:'+i.user.id+':restart:'+command.id+':0',label:'Restart',reset:true},{id:'learn:tutorial:'+i.user.id+':step:'+command.id+':'+(parts[5]??0),label:'Go back'}])]);return;}
  const id=i.isStringSelectMenu()?i.values[0]:parts[4],command=lessonCommands.find(c=>c.id===id);if(!command)throw new DomainError('TUTORIAL_COMMAND','This command is unavailable.');const step=action==='lesson'?0:Number(parts[5]??0);if(action!=='practice')await this.repo.tutorialStep(i.guildId,i.user.id,command.id,step,i.id,action==='restart');await this.lesson(i,command,step,false,action==='practice');
 }catch(error){const content=error instanceof DomainError?error.message:'This private window could not be completed. Saved progress remains available.';if(i.deferred)await i.editReply(displayNotice(content));else await i.reply({content,ephemeral:true,allowedMentions:{parse:[]}});}}
 private async lesson(i:Interaction,c:CommandContract,step:number,help=false,practice=false){
  const authored=lessonCopy(c),required=c.options.filter(o=>o.required).map(o=>o.name).join(', ')||'None',optional=c.options.filter(o=>!o.required).map(o=>o.name).join(', ')||'None';
  const pages=['PURPOSE\n'+authored.purpose,'FIELDS\n'+authored.fields,'HOW TO USE IT\n'+authored.steps.map((line,n)=>(n+1)+'. '+line).join('\n')+'\n\nEXAMPLE\n'+authored.example,'LESSON COMPLETE\n'+authored.completion+'\n\nPROGRESS\n'+c.registered+' · 4 of 4 pages complete. Your lesson progress is saved. Other lessons in the path are tracked separately.'];
  const text=practice?'PRACTICE · EXAMPLE REVIEW\n'+authored.example+'\n\n'+authored.fields+'\n\nNothing is executed. No Ottomans are spent.':help?'PURPOSE\n'+authored.purpose+'\n\nREQUIRED FIELDS\n'+required+'\nOPTIONAL FIELDS\n'+optional+'\n\nUSAGE\n'+authored.fields+'\n\nEXAMPLE · DOES NOT EXECUTE\n'+authored.example:'LESSON '+(step+1)+' OF 4\n\n'+(pages[step]??pages[0]);
  await this.window(i,c.registered+(help?' · Help':practice?' · Practice':' · Your lesson'),text,help&&!hasAuthoredLesson(c)?[]:[buttons([{id:`learn:tutorial:${i.user.id}:step:${c.id}:${Math.max(0,step-1)}`,label:'Back',disabled:step===0},{id:`learn:tutorial:${i.user.id}:step:${c.id}:${Math.min(3,step+1)}`,label:'Next',disabled:step===3},{id:`learn:tutorial:${i.user.id}:practice:${c.id}:${step}`,label:'Practice',primary:true},{id:`learn:tutorial:${i.user.id}:home`,label:'Learning Paths'}]),buttons([{id:`learn:tutorial:${i.user.id}:progress`,label:'Progress'},{id:`learn:tutorial:${i.user.id}:restartconfirm:${c.id}:${step}`,label:'Restart',reset:true},{id:`learn:tutorial:${i.user.id}:exit`,label:'Exit Tutorial'}])]);
 }
}
