import {createHash} from 'node:crypto';
import {ActionRowBuilder,AttachmentBuilder,ButtonBuilder,ButtonStyle,ChannelType,EmbedBuilder,MessageFlags,PermissionFlagsBits,StringSelectMenuBuilder,type AutocompleteInteraction,type ButtonInteraction,type ChatInputCommandInteraction,type Guild,type GuildMember,type StringSelectMenuInteraction} from 'discord.js';
import {DomainError,type ConfigService} from '../../../../packages/core/src/index.js';
import {PrismaMusicRepository,type MusicRequest,type MusicSelectionResult,type MusicResolvedOutcome,type MusicResolutionContext} from '../../../../packages/features-music/src/prisma-repository.js';
import {AuthorizedMusicCatalog} from '../../../../packages/features-music/src/catalog.js';
import {MusicResolutionService} from '../../../../packages/features-music/src/resolution.js';
import {normalizeMusicReference} from '../../../../packages/features-music/src/provider-references.js';
import {assertMusicActor,musicPolicy,type MusicControl} from '../../../../packages/features-music/src/domain.js';
import type {MusicActor,MusicPolicy,MusicState} from '../../../../packages/features-music/src/interfaces.js';
import {renderMusicController,renderMusicStrip,renderMusicNotice,renderMusicList} from '../../../../packages/features-music/src/render.js';
import {memberArt} from './member-art.js';
import {rasterizeSvg} from '../../../../packages/renderer/src/raster.js';
import {musicDiagnostic,musicTrace,type MusicTraceStage} from '../music/music-diagnostics.js';

type Interaction=ChatInputCommandInteraction|ButtonInteraction|StringSelectMenuInteraction;
type AnyInteraction=Interaction|AutocompleteInteraction;
export type MusicAccessResolver=(guild:Guild,member:GuildMember)=>Promise<{eligible:boolean;isDj:boolean}>;
export const MUSIC_COMMANDS=new Set(['play','music','playlist']);
export type MusicAutocompleteTimer=(callback:()=>void,delayMs:number)=>()=>void;
const autocompleteTimer:MusicAutocompleteTimer=(callback,delayMs)=>{const timer=setTimeout(callback,delayMs);return()=>clearTimeout(timer);};
type Rows=(ActionRowBuilder<ButtonBuilder>|ActionRowBuilder<StringSelectMenuBuilder>)[];
const whole=(value:string,label:string)=>{if(!/^\d+$/.test(value)||!Number.isSafeInteger(Number(value)))throw new DomainError('MUSIC_VALUE',`Enter a whole ${label}.`);return Number(value);};
function seekPosition(value:string){if(!/^\d+(?::[0-5]\d){0,2}$/.test(value))throw new DomainError('MUSIC_SEEK','Use seconds, minutes:seconds or hours:minutes:seconds.');const seconds=value.split(':').reduce((total,part)=>total*60+Number(part),0);if(!Number.isSafeInteger(seconds*1000))throw new DomainError('MUSIC_SEEK','Choose a valid playback position.');return seconds*1000;}
/** Saves intents and renders actual persisted state. It never connects to a music provider or claims an intent played audio. */
export class DiscordMusicCoordinator {
 constructor(private repo:PrismaMusicRepository,private config:ConfigService,private loadCatalog:(()=>Promise<AuthorizedMusicCatalog>)|null,private resolveActor:MusicAccessResolver,private now=()=>Date.now(),private resolutionService?:MusicResolutionService,private scheduleAutocomplete:MusicAutocompleteTimer=autocompleteTimer,private prepareVoice?: (request:MusicRequest,policy:MusicPolicy)=>Promise<void>,private presentPlayer?: (guildId:string,refreshOnly?:boolean)=>Promise<void>){}
 private silentUpdates=new WeakSet<Interaction>();
 private catalog(){return this.loadCatalog?this.loadCatalog():Promise.resolve(new AuthorizedMusicCatalog([]));}
 private resolution(){if(!this.resolutionService)throw new DomainError('MUSIC_UNAVAILABLE','Music source resolution is unavailable.');return this.resolutionService;}
 private async context(i:AnyInteraction):Promise<MusicActor>{
  if(!i.guildId||!i.guild||!i.channelId)throw new DomainError('SERVER_ONLY','Use music in a server voice channel’s text chat.');
  if(await this.config.get(i.guildId,'music.enabled')!==true)throw new DomainError('MUSIC_DISABLED','Music is not enabled yet.');
  const [channel,member,voice]=await Promise.all([i.guild.channels.fetch(i.channelId,{force:true}),i.guild.members.fetch({user:i.user.id,force:true}),i.guild.voiceStates.fetch(i.user.id,{force:true}).catch(error=>{if(error&&typeof error==='object'&&'code' in error&&error.code===10065)throw new DomainError('MUSIC_LOCATION','Join this voice channel and open its text chat before using music.');throw error;})]);if(!channel||![ChannelType.GuildVoice,ChannelType.GuildStageVoice].includes(channel.type))throw new DomainError('MUSIC_LOCATION','Join a voice or Stage channel and open its embedded text chat to use music.');

  if(member.user.bot||member.isCommunicationDisabled()||voice.channelId!==channel.id||!member.permissionsIn(channel).has(PermissionFlagsBits.ViewChannel|PermissionFlagsBits.Connect))throw new DomainError('MUSIC_LOCATION','Join this voice channel with current access before using its music controls.');
  const access=await this.resolveActor(i.guild,member);if(!access.eligible)throw new DomainError('MUSIC_RESTRICTED','Music is unavailable to you here.');
  return{guildId:i.guildId,userId:i.user.id,voiceChannelId:voice.channelId,textChannelId:channel.id,eligible:true,isDj:access.isDj};
 }
 private async policy(guildId:string):Promise<MusicPolicy>{return musicPolicy({queueMaxTracks:Number(await this.config.get(guildId,'music.queue_max_tracks')),defaultVolume:Number(await this.config.get(guildId,'music.default_volume')),defaultLoop:await this.config.get(guildId,'music.loop_default') as MusicPolicy['defaultLoop'],defaultAutoplay:await this.config.get(guildId,'music.autoplay_default')===true});}
 async autocomplete(i:AutocompleteInteraction){
  if(i.responded)return;
  const controller=new AbortController();let finished=false;
  // One budget includes fresh access checks and any lazy provider startup. Allow
  // cancellation a short turn to return safe partial results before the hard cutoff.
  const cancelResults=this.scheduleAutocomplete(()=>controller.abort(new DOMException('Autocomplete deadline','TimeoutError')),2200);
  let cancelCutoff=()=>{};
  const cutoff=new Promise<{name:string;value:string}[]>(resolve=>{cancelCutoff=this.scheduleAutocomplete(()=>resolve([]),2250);});
  const work=(async()=>{
   if(i.commandName!=='play')return[];
   await this.context(i);if(finished||controller.signal.aborted)return[];
   const query=String(i.options.getFocused()).trim();
   const reference=normalizeMusicReference(query);
   // A pasted URL is an explicit recording/collection, never a text-search hint.
   if(reference)return reference.reference.length<=100?[{name:'Open '+reference.provider+' '+reference.kind,value:reference.reference}]:[];
   if(/^(?:[a-z][a-z0-9+.-]*:|https?\b|www\.|\/\/)/i.test(query))return[];
   if(this.resolutionService){
    const tracks=await this.resolutionService.search(query,25,controller.signal);
    return tracks.filter(track=>track.reference.length<=100).map(track=>({name:`${track.title} — ${track.artist}`.slice(0,100),value:track.reference}));
   }
   const catalog=await this.catalog();return finished||controller.signal.aborted?[]:catalog.autocomplete(query);
  })().catch(error=>{if(!controller.signal.aborted&&!(error instanceof DomainError))console.warn('Music autocomplete diagnostic: '+musicDiagnostic(error));return[];});
  const choices=await Promise.race([work,cutoff]);for(const choice of choices)musicTrace('autocomplete.choice',{reference:choice.value});finished=true;cancelResults();cancelCutoff();
  // A failed response can be ambiguous. Never retry it or let late work respond.
  if(!i.responded)try{await i.respond(choices);}catch{/* Interaction expired or response delivery is uncertain. */}
 }
 private async notice(i:Interaction,title:string,message:string,components:Rows=[],list?:{title:string;detail?:string;badge?:string}[],subtitle=''){await (this.silentUpdates.has(i)?(payload:object)=>i.followUp({...payload,ephemeral:true}):i.editReply.bind(i))({content:message,embeds:[],files:[new AttachmentBuilder(await rasterizeSvg(list?.length?renderMusicList(title,subtitle,list.slice(0,2).map(row=>({...row,title:row.title.slice(0,90),detail:row.detail?.slice(0,70)??''})),list.length>2?'First 2 previewed; all entries in the message or menu.':'Use the controls below.'):renderMusicNotice(title,message.length>180?message.slice(0,177)+'…':message)),{name:'music-notice.png',description:[title,subtitle,message].filter(Boolean).join(' · ').slice(0,1024)})],components,allowedMentions:{parse:[]}});}
 private async player(actor:MusicActor,allowOtherVoice=false){const saved=await this.repo.read(actor.guildId);if(!saved)throw new DomainError('MUSIC_EMPTY','The jukebox is empty. Use /play and choose a recording.');assertMusicActor(saved.state,actor,allowOtherVoice);return saved;}
 private async listeners(i:Interaction,actor:MusicActor):Promise<string[]>{
  const candidates=[...i.guild!.voiceStates.cache.values()].filter(v=>v.channelId===actor.voiceChannelId).map(v=>v.id);if(!candidates.includes(actor.userId))candidates.push(actor.userId);
  const eligible=await Promise.all([...new Set(candidates)].map(async id=>{try{const member=await i.guild!.members.fetch({user:id,force:true}),voice=await i.guild!.voiceStates.fetch(id,{force:true});if(member.user.bot||member.isCommunicationDisabled()||voice.channelId!==actor.voiceChannelId||voice.selfDeaf||voice.serverDeaf||!member.permissionsIn(actor.textChannelId).has(PermissionFlagsBits.ViewChannel|PermissionFlagsBits.Connect))return null;return(await this.resolveActor(i.guild!,member)).eligible?id:null;}catch{return null;}}));return eligible.filter((id):id is string=>id!==null);
 }
 async handle(i:Interaction){let phase:MusicTraceStage='interaction.received';musicTrace(phase,{guildId:i.guildId??undefined});try{
  const quiet=i.isButton()&&(i.customId.startsWith('music:resolveconfirm:')||i.customId.startsWith('music:confirm:')||i.customId.startsWith('music:control:')&&!['queue','volume'].includes(i.customId.split(':')[5]??''));
  if(quiet&&i.isButton()){await i.deferUpdate();this.silentUpdates.add(i);}else await i.deferReply({ephemeral:!(i.isChatInputCommand()&&i.commandName==='play')});phase='context.read';const actor=await this.context(i),request:MusicRequest={actor,requestKey:i.id};musicTrace('member.voice.detected',{guildId:actor.guildId,channelId:actor.voiceChannelId});phase='selection.read';
  if(i.isStringSelectMenu()){
   if(i.customId.startsWith('music:resolvepick:')){phase='resolution.request';const [, ,owner,id,version]=i.customId.split(':');this.privateInteraction(i,actor,owner);if(!id||i.values.length!==1)throw new DomainError('MUSIC_SELECTION','Choose one exact recording.');await this.resolvedResult(i,actor,await this.repo.chooseResolvedTrack(request,id,whole(version??'','selection version'),whole(i.values[0]??'','selection index'),this.resolution(),await this.policy(actor.guildId)));return;}
   const [prefix,action,owner,playlistId,revision]=i.customId.split(':');if(prefix!=='music'||!['pick','addpick'].includes(action??'')||owner!==actor.userId||i.values.length!==1||i.message.author.id!==i.client.user.id||(action==='addpick'&&!i.message.flags.has(MessageFlags.Ephemeral)))throw new DomainError('MUSIC_OWNER','Open your own current music search.');if(action==='addpick'){if(!playlistId)throw new DomainError('MUSIC_PLAYLIST','Open the playlist again.');await this.addSelection(i,request,playlistId,whole(revision??'','playlist revision'),i.values[0]!);}else await this.enqueueSelection(i,request,i.values[0]!);return;
  }
  if(i.isButton()){
   if(i.customId.startsWith('music:resolveconfirm:')||i.customId.startsWith('music:resolvecancel:')){const [,action,owner,id,version]=i.customId.split(':');this.privateInteraction(i,actor,owner);if(!id)throw new DomainError('MUSIC_SELECTION','Open a current selection.');const result=action==='resolvecancel'?await this.repo.cancelResolvedSelection(request,id):await this.repo.confirmResolvedSelection(request,id,whole(version??'','selection version'),this.resolution(),await this.policy(actor.guildId));await this.resolvedResult(i,actor,result);return;}
   const parts=i.customId.split(':');if(parts[0]==='music'&&['confirm','cancel','page'].includes(parts[1]??'')){if(parts[2]!==actor.userId||i.message.author.id!==i.client.user.id||(parts[1]==='page'&&!i.message.flags.has(MessageFlags.Ephemeral)))throw new DomainError('MUSIC_OWNER','Open your own private music controls.');if(parts[1]==='confirm'||parts[1]==='cancel'){if(!parts[3])throw new DomainError('MUSIC_CONFIRMATION','Open a current confirmation.');const outcome=parts[1]==='confirm'?await this.repo.confirmSelection(request,parts[3],await this.catalog(),await this.policy(actor.guildId)):await this.repo.cancelConfirmation(request,parts[3]);await this.selectionResult(i,actor,outcome);return;}const kind=parts[3],page=parts[4]??'0';if(kind==='queue'){await this.queue(i,(await this.player(actor)).state,whole(page,'page'));return;}if(kind==='playlists'){await this.playlistList(i,request,whole(page,'page'));return;}if(kind==='tracks'){if(!parts[5])throw new DomainError('MUSIC_PLAYLIST','Open your playlist again.');await this.playlistTracks(i,request,parts[5],whole(page,'page'));return;}if(kind==='history'){if(!['older','newer','latest'].includes(page))throw new DomainError('MUSIC_HISTORY','Open the latest history.');await this.history(i,request,page==='latest'?null:parts[5]??null,page==='newer'?'newer':'older');return;}throw new DomainError('MUSIC_PAGE','Open a supported music page.');}
   const [prefix,action,guildId,revisionText,generationText,control,owner]=i.customId.split(':');if(prefix!=='music'||action!=='control'||guildId!==actor.guildId||!control||!owner)throw new DomainError('MUSIC_CONTROL','Open the current music controls.');
   if(owner!=='public'&&owner!==actor.userId)throw new DomainError('MUSIC_OWNER','Open your own private music controls.');const saved=await this.player(actor,['stop','leave'].includes(control));
   if(i.message.author.id!==i.client.user.id||owner==='public'&&(i.message.id!==saved.controllerMessageId||i.message.flags.has(MessageFlags.Ephemeral)))throw new DomainError('MUSIC_CONTROLLER','Use the current authoritative music controller.');
   if(owner!=='public'&&(!/^volume_\d+$/.test(control)||!i.message.flags.has(MessageFlags.Ephemeral)||!saved.controllerMessageId||!i.customId.endsWith(':m='+saved.controllerMessageId)))throw new DomainError('MUSIC_CONTROLLER','Use the current authoritative music controller.');
   const revision=whole(revisionText??'','player revision'),generation=whole(generationText??'','track generation');
   if(saved.state.generation!==generation||(!['nowplaying','skip'].includes(control)&&saved.state.revision!==revision))throw new DomainError('MUSIC_STALE','The player changed. Open its current controls.');
   if(control==='queue'){await this.queue(i,saved.state);return;}if(control==='nowplaying'){await this.presentPlayer?.(actor.guildId,true);return;}
   if(control==='skip'){const result=await this.repo.skip(request,generation,await this.listeners(i,actor));await this.controlResult(i,actor,result.skipped?undefined:`Vote Skip: ${result.votes}/${result.needed} current listeners.`);return;}
   if(saved.state.revision!==revision||saved.state.generation!==generation)throw new DomainError('MUSIC_STALE','The player changed. Open its current controls.');
   if(control==='volume'){await this.volumeChoices(i,actor,saved.state,saved.controllerMessageId!);return;}
   const operation=control==='shuffle'?this.shuffle(saved.state,i.id):this.buttonControl(control,saved.state);await this.repo.control(request,revision,operation);await this.controlResult(i,actor);return;
  }
  if(i.commandName==='play'){
   await this.prepareVoice?.(request,await this.policy(actor.guildId));
   const value=i.options.getString('query',true).trim();musicTrace('selection.received',{guildId:actor.guildId,channelId:actor.voiceChannelId,reference:value,selectionKind:/^[a-z][a-z0-9+.-]*:/i.test(value)?'reference':'text'});phase='resolution.request';if(this.resolutionService){await this.resolveQuery(i,request,value);return;}if(value.startsWith('catalog:')||/^[a-z][a-z0-9+.-]*:/i.test(value)||value.startsWith('//')){await this.enqueueSelection(i,request,value);return;}
   const catalog=await this.catalog(),matches=catalog.search(value);if(!matches.length){await this.notice(i,'Track unavailable','No available authorized catalog tracks match this search. Try another title or artist.');return;}
   const picker=new StringSelectMenuBuilder().setCustomId('music:pick:'+actor.userId).setPlaceholder('Choose the exact recording').addOptions(matches.map(track=>({label:track.metadata.title.slice(0,100),description:track.metadata.artist.slice(0,100),value:'catalog:'+track.id})));
   await this.notice(i,'Choose a recording','Choose the exact authorized recording to add. Search results do not start playback automatically.',[new ActionRowBuilder<StringSelectMenuBuilder>().addComponents(picker)],matches.slice(0,2).map((track,index)=>({title:track.metadata.title,detail:track.metadata.artist,badge:String(index+1)})),`${matches.length} results · ${matches.length>2?'First 2 shown; all results in menu':'Select below'} · No automatic playback`);return;
  }
  if(i.commandName==='playlist'){
   const command=i.options.getSubcommand(),name=i.options.getString('name');if(command==='view'&&!name){await this.playlistList(i,request);return;}if(command==='create'){await this.repo.createPlaylist(request,'music-list-'+i.id,name??'');await this.notice(i,'Playlist created',`Saved playlist: ${name}`);return;}const playlist=await this.repo.playlistByName(request,name??'');
   if(command==='view'){await this.playlistTracks(i,request,playlist.id);return;}if(command==='add'){const query=i.options.getString('query',true).trim();if(this.resolutionService){await this.resolveQuery(i,request,query,{action:'playlist-add',playlistId:playlist.id,playlistRevision:playlist.revision});return;}if(query.startsWith('catalog:')||/^[a-z][a-z0-9+.-]*:/i.test(query)||query.startsWith('//'))await this.addSelection(i,request,playlist.id,playlist.revision,query);else await this.search(i,actor,query,`music:addpick:${actor.userId}:${playlist.id}:${playlist.revision}`);return;}
   if(command==='play'){if(this.resolutionService){await this.resolvedResult(i,actor,await this.repo.requestResolvedTracks(request,playlist.tracks,this.resolutionService,await this.policy(actor.guildId),{action:'playlist-play',playlistId:playlist.id,playlistRevision:playlist.revision}));return;}await this.selectionResult(i,actor,await this.repo.requestPlaylistPlay(request,playlist.id,playlist.revision,await this.catalog(),await this.policy(actor.guildId)));return;}if(command==='delete'){await this.selectionResult(i,actor,await this.repo.requestPlaylistDelete(request,playlist.id,playlist.revision));return;}
   if(command==='rename')await this.repo.editPlaylist(request,playlist.id,playlist.revision,{kind:'rename',name:i.options.getString('new_name',true)});else if(command==='remove')await this.repo.editPlaylist(request,playlist.id,playlist.revision,{kind:'remove',position:i.options.getInteger('position',true)});else throw new DomainError('MUSIC_PLAYLIST','Choose a supported playlist action.');await this.playlistTracks(i,request,playlist.id);return;
  }
  if(i.commandName!=='music')throw new DomainError('MUSIC_CONTROL','Choose a supported music command.');const command=i.options.getSubcommand();
  if(command==='help'){await this.notice(i,'Music help','Use /play in your voice channel’s text chat. Search or paste a supported recording or playlist link. Spotify and Apple Music references require a confident playable match or your explicit choice. Requesters can skip their own track; other listeners vote; DJs can force skip. Previous, Replay and Seek require the requester or a DJ.');return;}
  if(command==='join'){await this.repo.join(request,await this.policy(actor.guildId));await this.showPlayer(i,actor,'Voice connection requested; waiting for transport confirmation.');return;}
  const saved=await this.player(actor,['stop','leave'].includes(command));if(command==='nowplaying'){await this.openPlayer(i,actor);return;}if(command==='queue'){await this.queue(i,saved.state);return;}
  if(command==='history'){await this.history(i,request);return;}
  if(command==='skip'){const result=await this.repo.skip(request,saved.state.generation,await this.listeners(i,actor));await this.controlResult(i,actor,result.skipped?undefined:`Vote Skip: ${result.votes}/${result.needed} current listeners.`);return;}
  let control:MusicControl;
  if(command==='seek')control={kind:'seek',positionMs:seekPosition(i.options.getString('time',true))};
  else if(command==='volume')control={kind:'volume',percent:i.options.getInteger('percent',true)};
  else if(command==='remove'||command==='jump')control={kind:command,entryId:this.entryAt(saved.state,String(i.options.getInteger('position',true)))};
  else if(command==='move')control={kind:'move',entryId:this.entryAt(saved.state,String(i.options.getInteger('position',true))),position:i.options.getInteger('to',true)};
  else if(command==='loop')control={kind:'loop',mode:i.options.getString('mode',true) as 'off'|'track'|'queue'};
  else if(command==='autoplay')control={kind:'autoplay',enabled:i.options.getBoolean('enabled',true)};
  else if(command==='shuffle')control=this.shuffle(saved.state,i.id);
  else control=this.buttonControl(command,saved.state);
  await this.repo.control(request,saved.state.revision,control);await this.controlResult(i,actor);
 }catch(error){musicTrace('interaction.failure',{guildId:i.guildId??undefined,phase,error});if(!(error instanceof DomainError))console.warn('Music interaction diagnostic: '+musicDiagnostic(error));const message=error instanceof DomainError?error.message:'Music could not be completed. No playback success has been assumed.';try{if(i.deferred||i.replied)await this.notice(i,'Music unavailable',message);else await i.reply({ephemeral:true,content:message,allowedMentions:{parse:[]}});}catch{/* Discord may have expired the interaction; never log private source data. */}}}
 private buttonControl(control:string,state:MusicState):MusicControl {if(['pause','resume','previous','replay','stop','leave','clear'].includes(control))return{kind:control as 'pause'|'resume'|'previous'|'replay'|'stop'|'leave'|'clear'};if(control==='loop')return{kind:'loop',mode:state.loop==='off'?'track':state.loop==='track'?'queue':'off'};if(control==='autoplay')return{kind:'autoplay',enabled:!state.autoplay};if(/^volume_\d+$/.test(control))return{kind:'volume',percent:whole(control.slice(7),'volume')};throw new DomainError('MUSIC_CONTROL','Use a supported music control.');}
 private shuffle(state:MusicState,seed:string):MusicControl{return{kind:'shuffle',entryIds:[...state.queue].sort((a,b)=>createHash('sha256').update(seed+':'+a.id).digest('hex').localeCompare(createHash('sha256').update(seed+':'+b.id).digest('hex'))).map(entry=>entry.id)};}
 private entryAt(state:MusicState,value:string){const position=whole(value,'queue position');const entry=state.queue[position-1];if(position<1||!entry)throw new DomainError('MUSIC_POSITION','Choose a current queue track number.');return entry.id;}
 private privateInteraction(i:ButtonInteraction|StringSelectMenuInteraction,actor:MusicActor,owner:string|undefined){if(owner!==actor.userId||i.message.author.id!==i.client.user.id)throw new DomainError('MUSIC_OWNER','Open your own music selection.');}
 private async resolveQuery(i:Interaction,request:MusicRequest,query:string,context:MusicResolutionContext={}){const service=this.resolution(),policy=await this.policy(request.actor.guildId),signal=AbortSignal.timeout(30000);if(/^[a-z][a-z0-9+.-]*:/i.test(query)||query.startsWith('//')){const resolved=await service.resolveReference(query,context.action==='playlist-add'?1000:policy.queueMaxTracks,signal);if(resolved.truncated)throw new DomainError('MUSIC_SELECTION_LIMIT','This collection exceeds the selection limit. Choose a smaller collection; no tracks were added.');if(!resolved.tracks.length)throw new DomainError('MUSIC_UNAVAILABLE','This music reference has no available recordings.');musicTrace('resolution.ready',{guildId:request.actor.guildId,channelId:request.actor.voiceChannelId});await this.resolvedResult(i,request.actor,await this.repo.requestResolvedTracks(request,resolved.tracks,service,policy,context,signal));return;}const matches=await service.search(query,25,signal);if(!matches.length)throw new DomainError('MUSIC_UNAVAILABLE','No recordings were found. Try another song or artist.');await this.resolvedResult(i,request.actor,await this.repo.openMusicSearch(request,matches,context));}
 private async resolvedResult(i:Interaction,actor:MusicActor,result:MusicResolvedOutcome){if(result.kind==='resolution-choice'){const picker=new StringSelectMenuBuilder().setCustomId(`music:resolvepick:${actor.userId}:${result.sessionId}:${result.version}`).setPlaceholder('Choose the exact recording').addOptions(result.choices.map((track,index)=>({label:track.title.slice(0,100),description:`${track.artist} · ${track.provider}`.slice(0,100),value:String(index)})));const cancel=new ActionRowBuilder<ButtonBuilder>().addComponents(new ButtonBuilder().setCustomId(`music:resolvecancel:${actor.userId}:${result.sessionId}:${result.version}`).setLabel('Cancel').setStyle(ButtonStyle.Secondary));await this.notice(i,result.title,'Choose the exact recording. No track from this selection has been added yet. This selection expires in five minutes.',[new ActionRowBuilder<StringSelectMenuBuilder>().addComponents(picker),cancel ],result.choices.slice(0,2).map((track,index)=>({title:track.title,detail:track.artist+' · '+track.provider,badge:String(index+1)})),`${result.choices.length} choices · ${result.choices.length>2?'First 2 shown; all choices in menu':'Select below'} · expires in 5 minutes`);return;}if(result.kind==='resolved-confirmation'){const row=new ActionRowBuilder<ButtonBuilder>().addComponents(new ButtonBuilder().setCustomId(`music:resolveconfirm:${actor.userId}:${result.sessionId}:${result.version}`).setLabel(result.reason==='duplicates'?'Add duplicates':'Add selection').setStyle(ButtonStyle.Primary),new ButtonBuilder().setCustomId(`music:resolvecancel:${actor.userId}:${result.sessionId}:${result.version}`).setLabel('Cancel').setStyle(ButtonStyle.Secondary));await this.notice(i,'Confirm music selection',`Add all ${result.count} selected recording(s)${result.reason==='duplicates'?', including duplicates':''}?${result.skippedCount?` ${result.skippedCount} unavailable recording(s) will be skipped.`:''} Nothing is added until confirmation. This selection expires in five minutes.`,[row]);return;}if(result.kind==='applied'&&!('playlistId' in result.result)){musicTrace('queue.persisted',{guildId:actor.guildId,channelId:actor.voiceChannelId});await this.added(i,actor,result.skippedCount);return;}await this.selectionResult(i,actor,result);}
 private async enqueueSelection(i:Interaction,request:MusicRequest,reference:string){const catalog=await this.catalog(),match=catalog.resolve(reference);if(match.status!=='available'){await this.notice(i,match.notice.title,match.notice.message);return;}await this.selectionResult(i,request.actor,await this.repo.requestCatalogEnqueue(request,['catalog:'+match.track.id],catalog,await this.policy(request.actor.guildId)));}
 private async addSelection(i:Interaction,request:MusicRequest,id:string,revision:number,reference:string){const catalog=await this.catalog(),match=catalog.resolve(reference);if(match.status!=='available'){await this.notice(i,match.notice.title,match.notice.message);return;}await this.selectionResult(i,request.actor,await this.repo.requestPlaylistAdd(request,id,revision,['catalog:'+match.track.id],catalog));}
 private async search(i:Interaction,actor:MusicActor,query:string,customId:string){const matches=(await this.catalog()).search(query);if(!matches.length){await this.notice(i,'Track unavailable','No available authorized catalog tracks match this search.');return;}const picker=new StringSelectMenuBuilder().setCustomId(customId).setPlaceholder('Choose the exact recording').addOptions(matches.map(track=>({label:track.metadata.title.slice(0,100),description:track.metadata.artist.slice(0,100),value:'catalog:'+track.id})));await this.notice(i,'Choose a recording','Choose the exact authorized recording to add. Search results do not start playback automatically.',[new ActionRowBuilder<StringSelectMenuBuilder>().addComponents(picker) ],matches.slice(0,2).map((track,index)=>({title:track.metadata.title,detail:track.metadata.artist,badge:String(index+1)})),`${matches.length} results · ${matches.length>2?'First 2 shown; all results in menu':'Select below'} · No automatic playback`);}
 private async selectionResult(i:Interaction,actor:MusicActor,result:MusicSelectionResult){if(result.kind==='confirmation'){const deleting=result.action==='playlist-delete',row=new ActionRowBuilder<ButtonBuilder>().addComponents(new ButtonBuilder().setCustomId(`music:confirm:${actor.userId}:${result.sessionId}`).setLabel(deleting?'Delete playlist':'Add duplicates').setStyle(ButtonStyle.Danger),new ButtonBuilder().setCustomId(`music:cancel:${actor.userId}:${result.sessionId}`).setLabel('Cancel').setStyle(ButtonStyle.Secondary));await this.notice(i,deleting?'Delete saved playlist?':'Confirm duplicate recordings',deleting?'Delete this saved playlist? Tracks already queued remain queued. This confirmation expires in five minutes.':`Add all ${result.count} selected recording(s), including duplicates? ${result.skippedCount?`${result.skippedCount} unavailable recording(s) were excluded. `:''}This confirmation expires in five minutes.`,[row]);return;}if(result.kind==='cancelled'||result.kind==='expired'){await this.notice(i,'Music confirmation',result.kind==='expired'?'This confirmation expired. Start a fresh selection.':'This selection was cancelled.');return;}const extra=result.skippedCount?` ${result.skippedCount} unavailable recording(s) were skipped.`:'';if('playlistId' in result.result){await this.notice(i,'Playlist saved',result.result.deleted?'The saved playlist was deleted. Tracks already queued remain queued.':`Added ${result.count} recording(s) to your saved playlist.${extra}`);return;}await this.added(i,actor,result.skippedCount);}
 private pageButtons(owner:string,kind:string,page:number,pages:number,id?:string):Rows {if(pages<=1)return[];const make=(n:number,label:string,disabled:boolean)=>new ButtonBuilder().setCustomId(`music:page:${owner}:${kind}:${n}${id?':'+id:''}`).setLabel(label).setDisabled(disabled).setStyle(ButtonStyle.Secondary);return[new ActionRowBuilder<ButtonBuilder>().addComponents(make(Math.max(0,page-1),'Previous page',page===0),make(Math.min(pages-1,page+1),'Next page',page>=pages-1))];}
 private trackLine(title:string,artist:string,n:number){return`${n}. ${title.slice(0,70)} · ${artist.slice(0,40)}`;}
 private async queue(i:Interaction,state:MusicState,page=0){const pages=Math.max(1,Math.ceil(state.queue.length/10)),current=Math.min(page,pages-1);await this.notice(i,'Music queue',state.queue.length?`Page ${current+1}/${pages} · ${state.queue.length} queued\n`+state.queue.slice(current*10,current*10+10).map((entry,n)=>this.trackLine(entry.track.title,entry.track.artist,current*10+n+1)).join('\n'):'The queue is empty. Use /play to choose a recording.',this.pageButtons(i.user.id,'queue',current,pages),state.queue.slice(current*10,current*10+10).map((entry,n)=>({title:entry.track.title,detail:entry.track.artist,badge:String(current*10+n+1)})),`UP NEXT · ${state.queue.length} queued · Page ${current+1}/${pages}`);}
 private async playlistList(i:Interaction,request:MusicRequest,page=0){const result=await this.repo.playlistPage(request,page);await this.notice(i,'Your playlists',result.total?`Page ${result.page+1}/${result.pages} · ${result.total} saved\n`+result.items.map((p,n)=>`${result.page*10+n+1}. ${p.name}`).join('\n'):'You have no saved playlists.',this.pageButtons(request.actor.userId,'playlists',result.page,result.pages),result.items.map((p,n)=>({title:p.name,badge:String(result.page*10+n+1)})),`${result.total} saved · Page ${result.page+1}/${result.pages}`);}
 private async playlistTracks(i:Interaction,request:MusicRequest,id:string,page=0){const playlist=await this.repo.readPlaylist(request,id),pages=Math.max(1,Math.ceil(playlist.tracks.length/10)),current=Math.min(page,pages-1);await this.notice(i,playlist.name,playlist.tracks.length?`Page ${current+1}/${pages}\n`+playlist.tracks.slice(current*10,current*10+10).map((track,n)=>this.trackLine(track.title,track.artist,current*10+n+1)).join('\n'):'This playlist is empty.',this.pageButtons(request.actor.userId,'tracks',current,pages,id),playlist.tracks.slice(current*10,current*10+10).map((track,n)=>({title:track.title,detail:track.artist,badge:String(current*10+n+1)})),`SAVED RECORDINGS · Page ${current+1}/${pages}`);}
 private async history(i:Interaction,request:MusicRequest,anchor:string|null=null,direction:'older'|'newer'='older'){const result=await this.repo.historyPage(request,anchor,direction),buttons:ButtonBuilder[]=[],button=(direction:string,label:string,id='')=>new ButtonBuilder().setCustomId(`music:page:${request.actor.userId}:history:${direction}${id?':'+id:''}`).setLabel(label).setStyle(ButtonStyle.Secondary);if(result.hasNewer&&result.items.length)buttons.push(button('newer','Newer',result.items[0]!.id));if(result.hasOlder&&result.items.length)buttons.push(button('older','Older',result.items.at(-1)!.id));if(anchor)buttons.push(button('latest','Latest'));await this.notice(i,'Played history',result.items.length?result.items.map((row,n)=>{const metadata=row.metadata as {title?:string;artist?:string};return this.trackLine(metadata.title??'Track',metadata.artist??'Artist',n+1);}).join('\n'):'No playback has been confirmed yet.',buttons.length?[new ActionRowBuilder<ButtonBuilder>().addComponents(buttons)]:[],result.items.map((row,n)=>{const metadata=row.metadata as {title?:string;artist?:string};return{title:metadata.title??'Track',detail:metadata.artist??'Artist',badge:String(n+1)};}),'CONFIRMED PLAYBACK');}
 private async controlResult(i:Interaction,actor:MusicActor,message?:string){await this.presentPlayer?.(actor.guildId);if(this.silentUpdates.has(i)){if(message)await this.notice(i,'Vote Skip',message);return;}if(message){await this.notice(i,'Vote Skip',message);return;}await i.deleteReply();}
 private async added(i:Interaction,actor:MusicActor,skipped:number){await this.presentPlayer?.(actor.guildId);if(skipped){await this.notice(i,'Some recordings unavailable',`${skipped} unavailable recording(s) were skipped. Available selections are reflected in the Jukebox.`);return;}await i.deleteReply();}
 private async openPlayer(i:Interaction,actor:MusicActor){const saved=await this.repo.read(actor.guildId);if(!saved?.controllerMessageId)throw new DomainError('MUSIC_EMPTY','The shared Jukebox is not available yet. Use /play to choose a recording.');await i.editReply({content:'',embeds:[],files:[],attachments:[],components:[new ActionRowBuilder<ButtonBuilder>().addComponents(new ButtonBuilder().setLabel('Open the Jukebox').setStyle(ButtonStyle.Link).setURL(`https://discord.com/channels/${actor.guildId}/${saved.state.textChannelId}/${saved.controllerMessageId}`))],allowedMentions:{parse:[]}});}
 private async showPlayer(i:Interaction,actor:MusicActor,message?:string){await this.presentPlayer?.(actor.guildId);const saved=await this.repo.read(actor.guildId);if(!saved)throw new DomainError('MUSIC_EMPTY','The jukebox is empty. Use /play to choose a recording.');const link=saved.controllerMessageId?`[Open the Jukebox](https://discord.com/channels/${actor.guildId}/${saved.state.textChannelId}/${saved.controllerMessageId})`:'The shared Jukebox is being prepared.';await i.editReply({content:[message??'Jukebox status refreshed.',link].join('\n'),embeds:[],files:[],attachments:[],components:[],allowedMentions:{parse:[]}});}
 private async volumeChoices(i:Interaction,actor:MusicActor,state:MusicState,messageId:string){if(!actor.isDj)throw new DomainError('MUSIC_DJ','Volume requires DJ authority.');await this.notice(i,'Player volume','Choose a volume level.',[new ActionRowBuilder<ButtonBuilder>().addComponents([25,50,65,80,100].map(percent=>this.button(state,'volume_'+percent,percent+'%',actor.userId).setCustomId(`music:control:${state.guildId}:${state.revision}:${state.generation}:volume_${percent}:${actor.userId}:m=${messageId}`)))]);}
 private button(state:MusicState,action:string,label:string,ownerId:string){return new ButtonBuilder().setCustomId(`music:control:${state.guildId}:${state.revision}:${state.generation}:${action}:${ownerId}`).setLabel(label).setStyle(action==='pause'||action==='resume'?ButtonStyle.Primary:action==='stop'?ButtonStyle.Danger:ButtonStyle.Secondary);}
 async payload(state:MusicState,options:{ownerId?:string;requesterName?:string;voiceChannelName?:string;requesterAvatarData?:string;artworkData?:string;compact?:boolean}={}){const owner=options.ownerId??'public',paused=state.desiredStatus==='PAUSED',controlGroups=[[['previous','Previous'],[paused?'resume':'pause',paused?'Resume':'Pause'],['skip','Skip'],['stop','Stop']],[['queue','Queue'],['shuffle','Shuffle'],['loop','Loop']],[['volume','Volume'],['autoplay','Autoplay'],['nowplaying','Refresh']]];const rows=controlGroups.map(group=>new ActionRowBuilder<ButtonBuilder>().addComponents(group.map(([action,label])=>this.button(state,action!,label!,owner))));return{embeds:[new EmbedBuilder().setAuthor({name:'Angrier Jordan'}).setTitle('The Jukebox').setColor(0x10b981).setImage('attachment://music-controller.png')],files:[new AttachmentBuilder(await rasterizeSvg((options.compact!==false?renderMusicStrip:renderMusicController)(state,this.now(),options.requesterName??'Member',options.artworkData,options.voiceChannelName,options.requesterAvatarData)),{name:'music-controller.png'})],components:rows,attachments:[],allowedMentions:{parse:[] as never[]}};}
}
