import {frameGallery} from './wide-display.js';
import {MessageFlags,TextDisplayBuilder,ActionRowBuilder,AttachmentBuilder,ButtonBuilder,ButtonStyle,EmbedBuilder,ModalBuilder,StringSelectMenuBuilder,TextInputBuilder,TextInputStyle,type ButtonInteraction,type ChatInputCommandInteraction,type Client,type Guild,type ModalSubmitInteraction,type StringSelectMenuInteraction} from 'discord.js';
import {DomainError,DeliveryEngine,PermissionEngine,type ConfigService} from '../../../../packages/core/src/index.js';
import {CAPABILITY_MATRIX} from '../../../../packages/contracts/src/generated/capabilities.js';
import {PrismaPartyRepository,type PartyContext,type PartyStart,type PartyView} from '../../../../packages/features-party/src/prisma-repository.js';
import {PARTY_GAMES,type PartyGame,type PartyMember} from '../../../../packages/features-party/src/domain.js';
import {renderParty,renderPartyDraft,partyTranscript,PARTY_TITLES} from '../../../../packages/features-party/src/render.js';
import {rasterizeSvg} from '../../../../packages/renderer/src/raster.js';
import {avatarData,memberArt} from './member-art.js';
import {funChannelAllowed} from './fun-channels.js';
import {interactiveGameChannelAllowed} from './interactive-game-channels.js';
import type {PartyArt} from '../../../../packages/features-party/src/render.js';
type Interaction=ChatInputCommandInteraction|ButtonInteraction|ModalSubmitInteraction|StringSelectMenuInteraction;
export const PARTY_COMMANDS=new Set<string>(PARTY_GAMES);
export class DiscordPartyCoordinator {
 private refreshes=new Map<string,Promise<void>>();
 private sweeping=false;
 private presented=new Map<string,{art:string;ui:string}>();
 constructor(private repo:PrismaPartyRepository,private config:ConfigService,private eligible:(g:string,u:string)=>Promise<boolean>){}
 private async guard(guildId:string,userId:string,channelId:string,game:PartyGame){if(await this.config.get(guildId,'features.party_games')!==true)throw new DomainError('PARTY_DISABLED','Party games are not enabled yet.');const interactive=await interactiveGameChannelAllowed(this.config,guildId,channelId),dedicated=game==='onewordstory'&&channelId===await this.config.get(guildId,'channels.one_word_story_channel'),allowed=['fmk','wwyd','truthordare'].includes(game)?await funChannelAllowed(this.config,guildId,channelId,'party'):interactive||dedicated;if(!allowed)throw new DomainError('PARTY_CHANNEL','Use an approved games channel.');if(!new PermissionEngine({'events.use':CAPABILITY_MATRIX.capabilities['events.use']}).can('member','events.use')||!await this.eligible(guildId,userId))throw new DomainError('PARTY_RESTRICTED','Party games are unavailable while restricted.');}
 private async target(guild:Guild,userId:string):Promise<PartyMember>{const member=await guild.members.fetch({user:userId,force:true});if(member.user.bot||!await this.eligible(guild.id,userId))throw new DomainError('PARTY_TARGET','Choose a current eligible human member.');return{userId,name:member.displayName};}
 private async candidates(guild:Guild){const members=await guild.members.fetch(),eligible:PartyMember[]=[];for(const member of members.values())if(!member.user.bot&&await this.eligible(guild.id,member.id))eligible.push({userId:member.id,name:member.displayName});return eligible;}
 private modal(action:string,id:string,title:string,label:string,max=1000){return new ModalBuilder().setCustomId(`party:${action}:${id}`).setTitle(title).addComponents(new ActionRowBuilder<TextInputBuilder>().addComponents(new TextInputBuilder().setCustomId('value').setLabel(label).setStyle(max<=40?TextInputStyle.Short:TextInputStyle.Paragraph).setRequired(true).setMaxLength(max)));}
 private modePicker(userId:string,game:'truthordare'|'wwyd',targetId?:string){const target=targetId??'';return{content:'Choose how to play this round.',components:[new ActionRowBuilder<ButtonBuilder>().addComponents(new ButtonBuilder().setCustomId(`party:mode:${userId}:${game}:private:${target}`).setLabel('Private').setStyle(ButtonStyle.Primary),new ButtonBuilder().setCustomId(`party:mode:${userId}:${game}:public:${target}`).setLabel('Multiplayer').setStyle(ButtonStyle.Secondary))],allowedMentions:{parse:[] as never[]}};}
 private async start(i:ChatInputCommandInteraction|ButtonInteraction,game:PartyGame,visibility:'private'|'public',targetId?:string){
  const c:PartyContext={guildId:i.guildId!,channelId:i.channelId!,userId:i.user.id,requestKey:i.id},options:PartyStart={game,visibility};
  if(game==='truthordare')options.target=await this.target(i.guild!,i.isChatInputCommand()?i.options.getUser('member')?.id??i.user.id:targetId||i.user.id);
  if(game==='wwyd')options.category=i.isChatInputCommand()?i.options.getString('category')??'Random':'Random';
  const started=await this.repo.start(c,options);
  if(visibility==='private'){await i.editReply(await this.payload(await this.repo.publicView(started.sessionId),i.client));return;}
  if(started.jobId)await this.publish(i.client,started.jobId);await i.editReply({content:'The party round is ready in this channel.'});
 }
 async handle(i:Interaction){try{
  if(!i.guildId||!i.guild||!i.channelId)throw new DomainError('SERVER_ONLY','Use party games in the server.');
  if(i.isButton()&&i.customId.startsWith('party:mode:')){const[,action,owner,rawGame,rawVisibility,targetId]=i.customId.split(':');if(action!=='mode'||owner!==i.user.id||!['truthordare','wwyd'].includes(rawGame??'')||!['private','public'].includes(rawVisibility??''))throw new DomainError('PARTY_MODE','Open your own party-game mode selector.');await i.deferUpdate();const game=rawGame as 'truthordare'|'wwyd',visibility=rawVisibility as 'private'|'public';await this.guard(i.guildId,i.user.id,i.channelId,game);await this.start(i,game,visibility,targetId);return;}
  if(!i.isChatInputCommand()&&(i.isButton()||i.isStringSelectMenu())&&['truth','dare','random','skip','vote','extend','fmk_submit','vote_pick'].includes(i.customId.split(':')[1]??''))await i.deferReply({ephemeral:true});
  const previous=i.isChatInputCommand()?undefined:await this.repo.publicView(i.customId.split(':')[2]??'');await this.guard(i.guildId,i.user.id,i.channelId,i.isChatInputCommand()?i.commandName as PartyGame:previous!.game);const c:PartyContext={guildId:i.guildId,channelId:i.channelId,userId:i.user.id,requestKey:i.id};
  if(i.isChatInputCommand()){await i.deferReply({ephemeral:true});const game=i.commandName as PartyGame;if(game==='truthordare'||game==='wwyd'){await i.editReply(this.modePicker(i.user.id,game,game==='truthordare'?i.options.getUser('member')?.id:undefined));return;}const options:PartyStart={game};if(game==='onewordstory')options.length=i.options.getInteger('length')??50;if(game==='fmk')options.members=await this.candidates(i.guild);const started=await this.repo.start(c,options);if(game==='fmk'){await i.editReply(await this.privatePayload(c,started.sessionId,i.client));return;}if(started.jobId)await this.publish(i.client,started.jobId);await i.editReply({content:'The party round is ready in this channel.'});return;}
  const[prefix,action,id,arg]=i.customId.split(':');if(prefix!=='party'||!id)throw new DomainError('PARTY_CONTROL','Open the current party round.');const v=previous!;if(v.guildId!==i.guildId||v.channelId!==i.channelId)throw new DomainError('PARTY_CHANNEL','Use this round’s original server and channel.');
  const privateAction=['fmk_fuck','fmk_marry','fmk_submit','vote_pick','vote_page'].includes(action??'');if(v.visibility==='private'&&i.user.id!==v.ownerId)throw new DomainError('OWNER_ONLY','Open your own private party round.');if(!i.isModalSubmit()&&!privateAction&&v.messageId&&i.message.id!==v.messageId)throw new DomainError('PARTY_CONTROL','Use this round’s original message.');
  if(i.isButton()&&action==='details'){await i.reply({ephemeral:true,files:[new AttachmentBuilder(Buffer.from(partyTranscript(v),'utf8'),{name:'party-round.txt'})],allowedMentions:{parse:[]}});return;}
  if(i.isButton()&&['answer','submit','word','custom','again_custom'].includes(action??'')){await i.showModal(this.modal(action+'_modal',id,PARTY_TITLES[v.game],action==='word'?'One word':action==='custom'||action==='again_custom'?'Your new sentence prompt':'Your response',action==='word'?40:action==='custom'||action==='again_custom'?500:1000));return;}
  if(i.isButton()&&(action==='vote_open'||action==='vote_page')){await i.reply({ephemeral:true,...this.votePicker(v,Number(arg)||0)});return;}
  if(i.isStringSelectMenu()&&(action==='fmk_fuck'||action==='fmk_marry')){await i.deferUpdate();await this.repo.draftFmk(c,id,action==='fmk_fuck'?'fuck':'marry',i.values[0]!);await i.editReply(await this.privatePayload(c,id,i.client));return;}
  if(i.isButton()&&action==='again'&&v.game==='finishsentence'&&v.mode==='custom'){await i.showModal(this.modal('again_custom_modal',id,'Finish the Sentence','Your new sentence prompt',500));return;}
  if(!i.deferred)await i.deferReply({ephemeral:true});
  if(action==='again'||action==='again_custom_modal'){
   const options:PartyStart={game:v.game,sourceId:id,category:v.category};if(v.game==='truthordare'){try{options.target=await this.target(i.guild,v.target?.userId??i.user.id);}catch{options.target=await this.target(i.guild,i.user.id);}}if(v.game==='onewordstory')options.length=v.targetLength??50;if(v.game==='finishsentence'){options.mode=v.mode==='custom'?'custom':'random';if(i.isModalSubmit())options.customPrompt=i.fields.getTextInputValue('value');}if(v.game==='fmk')options.members=await this.candidates(i.guild);const started=await this.repo.start(c,options);if(v.game==='fmk'){await i.editReply(await this.privatePayload(c,started.sessionId,i.client));return;}if(started.jobId)await this.publish(i.client,started.jobId);await i.editReply({content:'A fresh round is ready. The old result stays intact.'});return;
  }
  if(action==='truth'||action==='dare'||action==='random')await this.repo.choosePrompt(c,id,action);
  else if(action==='custom_modal'&&i.isModalSubmit())await this.repo.choosePrompt(c,id,'custom',i.fields.getTextInputValue('value'));
  else if(action==='answer_modal'&&i.isModalSubmit())await this.repo.answer(c,id,i.fields.getTextInputValue('value'));
  else if(action==='skip')await this.repo.answer(c,id,'',true);
  else if(action==='submit_modal'&&i.isModalSubmit()){const member=await this.target(i.guild,i.user.id);await this.repo.submit(c,id,member.name,i.fields.getTextInputValue('value'));}
  else if(action==='word_modal'&&i.isModalSubmit()){const member=await this.target(i.guild,i.user.id);await this.repo.addWord(c,id,member.name,i.fields.getTextInputValue('value'));}
  else if(action==='vote'||action==='vote_pick'){const choice=i.isStringSelectMenu()?i.values[0]!:arg!;if(v.visibility==='private'&&v.game==='wwyd')await this.repo.choosePrivateWwyd(c,id,choice);else await this.repo.vote(c,id,choice);}
  else if(action==='extend')await this.repo.extend(c,id);
  else if(action==='fmk_submit'){const current=await this.candidates(i.guild),submitted=await this.repo.submitFmk(c,id,current.map(m=>m.userId));await this.publish(i.client,submitted.jobId);try{await i.deleteReply();}catch{await i.editReply({content:null,embeds:[],attachments:[],components:[new TextDisplayBuilder().setContent('Your FMK is public. Its audience vote is now open.')]});}return;}
  else throw new DomainError('PARTY_CONTROL','That control is unavailable.');
  if(v.visibility==='private'){await i.editReply(await this.payload(await this.repo.publicView(id),i.client));return;}
  await i.editReply({content:action==='vote'||action==='vote_pick'?'Your anonymous vote is saved. You may change it until close.':'Your action is saved.'});await this.refresh(i.client,id);
 }catch(error){const content=error instanceof DomainError?error.message:'The party update could not be completed. Saved actions and publication recovery remain pending.';if(i.deferred&&!i.replied)await i.editReply('message'in i&&i.message?.flags?.has(MessageFlags.IsComponentsV2)?{content:null,components:[new TextDisplayBuilder().setContent(content)],attachments:[],embeds:[]}:{content});else if(i.replied||i.deferred)await i.followUp({ephemeral:true,content});else await i.reply({ephemeral:true,content});}}
 private async privatePayload(c:PartyContext,id:string,client?:Client){const v=await this.repo.privateFmk(c,id),rows:ActionRowBuilder<StringSelectMenuBuilder|ButtonBuilder>[]=[];if(v.state==='DRAFT'){rows.push(new ActionRowBuilder<StringSelectMenuBuilder>().addComponents(new StringSelectMenuBuilder().setCustomId('party:fmk_fuck:'+id).setPlaceholder('Assign Fuck').addOptions(v.trio.map(m=>({label:m.name.slice(0,100),value:m.userId,default:m.userId===v.fuck})))));if(v.fuck)rows.push(new ActionRowBuilder<StringSelectMenuBuilder>().addComponents(new StringSelectMenuBuilder().setCustomId('party:fmk_marry:'+id).setPlaceholder('Assign Marry').addOptions(v.trio.filter(m=>m.userId!==v.fuck).map(m=>({label:m.name.slice(0,100),value:m.userId,default:m.userId===v.marry})))));rows.push(new ActionRowBuilder<ButtonBuilder>().addComponents(new ButtonBuilder().setCustomId('party:fmk_submit:'+id).setLabel('Submit Choices').setStyle(ButtonStyle.Primary).setDisabled(!v.fuck||!v.marry)));}const art:Record<string,PartyArt>={};await Promise.all(v.trio.map(async m=>{art[m.userId]=(client?await memberArt(client,c.guildId,m.userId):undefined)??{name:m.name,avatarData:await avatarData((m as {avatar?:string}).avatar)};}));const chooser=client?await memberArt(client,c.guildId,c.userId):undefined;return{flags:MessageFlags.IsComponentsV2 as const,content:null,embeds:[],files:[new AttachmentBuilder(await rasterizeSvg(renderPartyDraft(v,art,chooser?.name)),{name:'party-private.png'})],attachments:[],components:[frameGallery('party-private.png','Private FMK choices'),...rows],allowedMentions:{parse:[] as never[]}};}

 private votePicker(v:PartyView,page:number){if(!['vote','runoff'].includes(v.phase)||v.state!=='OPEN')throw new DomainError('PARTY_PHASE','Voting is closed.');const p=Math.max(0,Math.min(Math.floor((v.options.length-1)/25),Math.floor(page))),options=v.options.slice(p*25,p*25+25),rows:ActionRowBuilder<StringSelectMenuBuilder|ButtonBuilder>[]=[new ActionRowBuilder<StringSelectMenuBuilder>().addComponents(new StringSelectMenuBuilder().setCustomId('party:vote_pick:'+v.id).setPlaceholder('Choose another member’s contribution').addOptions(options.map((o,n)=>({label:`${p*25+n+1}. ${o.text}`.slice(0,100),value:o.id}))))];if(v.options.length>25)rows.push(new ActionRowBuilder<ButtonBuilder>().addComponents(new ButtonBuilder().setCustomId(`party:vote_page:${v.id}:${Math.max(0,p-1)}`).setLabel('Previous').setStyle(ButtonStyle.Secondary).setDisabled(p===0),new ButtonBuilder().setCustomId(`party:vote_page:${v.id}:${p+1}`).setLabel('Next').setStyle(ButtonStyle.Secondary).setDisabled((p+1)*25>=v.options.length)));return{content:options.map((o,n)=>`${p*25+n+1}. ${o.text.slice(0,500)}`).join('\n\n').slice(0,1900),components:rows,allowedMentions:{parse:[] as never[]}};}
 async payload(v:PartyView,client?:Client,includeArtwork=true){const buttons:ButtonBuilder[]=[],button=(action:string,label:string,arg?:string)=>new ButtonBuilder().setCustomId(`party:${action}:${v.id}${arg?':'+arg:''}`).setLabel(label).setStyle(ButtonStyle.Secondary);
  if(v.state==='OPEN'){if(v.phase==='choose')buttons.push(...(v.game==='truthordare'?[button('truth','Truth'),button('dare','Dare'),button('skip','Skip')]:[button('random','Random Prompt'),button('custom','Write My Own')]));if(v.phase==='answer')buttons.push(button('answer','Reply'),button('skip','Skip'));if(v.phase==='submissions')buttons.push(button('submit','Reply / Revise'));if(v.phase==='story')buttons.push(button('word','Reply with Word'));if(['vote','runoff'].includes(v.phase)){if(v.game==='fmk'||v.game==='wwyd')buttons.push(...v.options.map(o=>button('vote',o.text.slice(0,80),o.id)));else buttons.push(button('vote_open','Vote'));}if(!v.extensionUsed&&(v.game==='wwyd'||v.game==='fmk'||v.game==='finishsentence'&&v.phase==='submissions'))buttons.push(button('extend','+30 Seconds'));}
  if(v.state==='CLOSED'||v.game==='fmk'&&v.assignments)buttons.push(button('again','Play Again'));if(v.state!=='DRAFT')buttons.push(button('details','Details'));const rows:ActionRowBuilder<ButtonBuilder>[]=[];for(let n=0;n<buttons.length;n+=5)rows.push(new ActionRowBuilder<ButtonBuilder>().addComponents(...buttons.slice(n,n+5)));
  const art:Record<string,PartyArt>={},people=[...(v.target?[v.target]:[]),...(v.trio??[]),...(v.game==='fmk'&&v.ownerId?[{userId:v.ownerId,name:'The chooser'}]:[]),...(v.result?.winnerId?[{userId:v.result.winnerId,name:v.submissions[v.result.winnerId]?.name??'Winning member'}]:[])];if(includeArtwork)await Promise.all(people.map(async person=>{const current=client?await memberArt(client,v.guildId,person.userId):undefined;art[person.userId]=current??{name:person.name,avatarData:await avatarData((person as {avatar?:string}).avatar)};}));
  if(v.game==='fmk')return{flags:MessageFlags.IsComponentsV2 as const,content:null,embeds:[],...(includeArtwork?{files:[new AttachmentBuilder(await rasterizeSvg(renderParty(v,art)),{name:'party.png'})],attachments:[]}:{}),components:[frameGallery('party.png','FMK · member choices and audience verdict'),...(v.expiresAt&&v.state==='OPEN'?[new TextDisplayBuilder().setContent('Voting closes <t:'+Math.floor(v.expiresAt.getTime()/1000)+':R>.')]:[]),...rows],allowedMentions:{parse:[] as never[]}};
  return{content:v.expiresAt&&v.state==='OPEN'?`Closes <t:${Math.floor(v.expiresAt.getTime()/1000)}:R>.`:'',embeds:[new EmbedBuilder().setColor(0x3b82f6).setImage('attachment://party.png')],...(includeArtwork?{files:[new AttachmentBuilder(await rasterizeSvg(renderParty(v,art)),{name:'party.png'})],attachments:[]}:{}),components:rows,allowedMentions:{parse:[] as never[]}};
 }
 async publish(client:Client,jobId:string){const p=await this.repo.deliveryJob(jobId),channel=await client.channels.fetch(p.channelId);if(!channel?.isSendable()||!('messages' in channel))throw new Error('Party destination unavailable.');const marker='party:'+p.sessionId,messageId=await new DeliveryEngine(this.repo.delivery(jobId)).deliver(marker,{find:async marker=>{const messages=await channel.messages.fetch({limit:100});return messages.find(m=>m.author.id===client.user?.id&&(m.embeds.some(e=>e.footer?.text===marker)||m.components?.some(row=>('components'in row)&&row.components.some(c=>'customId'in c&&c.customId?.split(':')[0]==='party'&&c.customId.split(':')[2]===p.sessionId))))?.id??null;},send:async()=>{const v=await this.repo.publicView(p.sessionId),payload=await this.payload(v,client),{content,attachments,...created}=payload,sent=await channel.send({...created,...(content?{content}:{})});this.remember(v.id,this.keys({...v,messageId:sent.id}));return sent.id;}});await this.repo.linkMessage(p.sessionId,p.guildId,messageId);}
 private remember(id:string,key:{art:string;ui:string}){this.presented.delete(id);this.presented.set(id,key);while(this.presented.size>256)this.presented.delete(this.presented.keys().next().value!);}
 private keys(v:PartyView){const {version,expiresAt,extensionUsed,messageId,...visual}=v;return{art:JSON.stringify(visual),ui:JSON.stringify([v.state,v.phase,expiresAt,extensionUsed,messageId,v.result,v.options])};}
 async refresh(client:Client,id:string){const before=this.refreshes.get(id)??Promise.resolve(),current=before.catch(()=>{}).then(async()=>{const v=await this.repo.publicView(id);if(!v.messageId||v.state==='DRAFT')return;const key=this.keys(v),previous=this.presented.get(id);if(previous?.art===key.art&&previous.ui===key.ui)return;try{const channel=await client.channels.fetch(v.channelId);if(!channel?.isTextBased()||!('messages' in channel))throw new Error('Party channel unavailable.');const message=await channel.messages.fetch(v.messageId);if(message.author.id!==client.user?.id)throw new Error('Party message author mismatch.');await message.edit(await this.payload(v,client,previous?.art!==key.art));this.remember(id,key);}catch(error){if(typeof error==='object'&&error!==null&&'code'in error&&error.code===10008){await this.repo.cancelMissingMessage(v.guildId,id);this.presented.delete(id);return;}throw error;}});this.refreshes.set(id,current);try{await current;}finally{if(this.refreshes.get(id)===current)this.refreshes.delete(id);}}
 async advance(client:Client,guildId:string,id:string,round:number){await this.repo.advance(guildId,id,round);await this.refresh(client,id);}
 async sweep(client:Client){if(this.sweeping)return;this.sweeping=true;try{for(const row of await this.repo.active()){if(row.expiresAt&&row.expiresAt<=new Date())await this.advance(client,row.guildId,row.id,(row.data as {round:number}).round);else if(row.messageId)await this.refresh(client,row.id);}}finally{this.sweeping=false;}}
}
