import {ActionRowBuilder,ButtonBuilder,ButtonStyle,ModalBuilder,TextInputBuilder,TextInputStyle,type ButtonInteraction,type ChatInputCommandInteraction, type ModalSubmitInteraction} from 'discord.js';
import {DomainError} from '../../../../packages/core/src/index.js';
import {PrismaPokerRepository,type PokerContext} from '../../../../packages/features-casino/src/poker-repository.js';
import {pokerCardLabel,type PokerPrivateView,type PokerPublicView} from '../../../../packages/features-casino/src/poker.js';
export const POKER_CHANNEL_ID='1557660895813963908';
type PokerInteraction=ChatInputCommandInteraction|ButtonInteraction|ModalSubmitInteraction;
export class DiscordPokerCoordinator {
 constructor(private readonly repo:PrismaPokerRepository,private readonly mainChannel:(guildId:string)=>Promise<string|undefined>){ }
 private async context(i:PokerInteraction):Promise<PokerContext>{if(!i.guildId||!i.channelId)throw new DomainError('SERVER_ONLY','Use Poker in the server.');const channel=POKER_CHANNEL_ID;if(i.channelId!==channel)throw new DomainError('POKER_CHANNEL',`Use the Poker room: <#${channel}>.`);return{guildId:i.guildId,channelId:i.channelId,userId:i.user.id,requestKey:i.id};}
 private publicText(view:PokerPublicView){return `Poker hand ${view.handId.slice(0,8)} · ${view.variant==='holdem'?'Hold’em':'Omaha'}\nStreet: **${view.street}** · Pot: **${view.pot} chips** · Turn: <@${view.toAct}>\nBoard: ${view.board.length?view.board.map(pokerCardLabel).join(' '):'—'}\n${view.settled?`Hand settled: ${view.winnerIds?.map(id=>`<@${id}>`).join(', ')??'no eligible winner'}`:'Hole cards and legal actions are private.'}`;}
 private privateText(view:PokerPrivateView){return `Your private Poker view\nHole cards: **${view.holeCardLabels.join(' · ')}**\nStack: **${view.stack} chips** · Pot: **${view.pot} chips** · Call: **${view.callAmount} chips**\nStreet: **${view.street}**${view.canAct?`\nIt is your turn. Raise minimum: **${view.minimumRaise} chips**.`:'\nWait for your turn.'}`;}
 async handle(i:PokerInteraction){try{const c=await this.context(i);if(i.isChatInputCommand()){const variant=i.commandName==='holdem'?'holdem':i.commandName==='omaha'?'omaha':null;if(!variant)throw new DomainError('POKER_COMMAND','Choose Hold’em or Omaha.');const result=await this.repo.start(c,variant,i.user.username,BigInt(i.options.getInteger('buy_in',true)));await i.reply({content:`${variant==='holdem'?'Texas Hold’em':'Omaha'} table opened. Buy-in reserved; use the controls to join.`,components:this.controls(result.sessionId),allowedMentions:{parse:[]}});return;}
 const [,action,id,argument]=i.customId.split(':');if(!id)throw new DomainError('POKER_CONTROL','Use the current Poker controls.');
 if(action==='private'){await i.deferReply({ephemeral:true});const view=await this.repo.privateView(id,c.userId);await i.editReply({content:this.privateText(view),components:this.actionControls(id,view),allowedMentions:{parse:[]}});return;}
 if(action==='raise'){if(i.isButton()){const modal=new ModalBuilder().setCustomId(`poker:raise_submit:${id}`).setTitle('Raise');modal.addComponents(new ActionRowBuilder<TextInputBuilder>().addComponents(new TextInputBuilder().setCustomId('amount').setLabel('Total committed chips').setStyle(TextInputStyle.Short).setRequired(true).setMaxLength(12)));await i.showModal(modal);return;}const amount=BigInt(i.fields.getTextInputValue('amount'));await i.deferUpdate();await this.repo.act(c,id,'raise',amount);await i.followUp({ephemeral:true,content:'Raise saved. Use **View Private Hand** on the table for your updated legal actions.'});return;}
 if(action==='fold'||action==='check'||action==='call'){await i.deferUpdate();await this.repo.act(c,id,action);await i.followUp({ephemeral:true,content:'Action saved. Use **View Private Hand** on the table for the current private state.'});return;}
 await i.deferUpdate();if(action==='join'||action==='bot'){await this.repo.join(c,id,action==='bot'?'Dealer Bot':i.user.username,BigInt(argument??'500'),action==='bot');await i.editReply({content:action==='bot'?'Bot seat added. Bots use virtual chips only.':'Seat joined. Your cards and actions remain private.',components:this.controls(id)});return;}if(action==='cancel'){await this.repo.cancel(c,id);await i.editReply({content:'Poker table cancelled. Human buy-ins refunded.',components:[]});return;}if(action==='start'){await this.repo.startPlaying(c,id);const view=await this.repo.publicView(id);await i.editReply({content:this.publicText(view),components:this.playingControls(id)});return;}throw new DomainError('POKER_CONTROL','That Poker control is unavailable.');
 }catch(error){const content=error instanceof DomainError?error.message:'Poker could not complete that action. The saved table state was not changed.';if(i.deferred||i.replied)await i.followUp({ephemeral:true,content}).catch(()=>undefined);else await i.reply({ephemeral:true,content}).catch(()=>undefined);}}
 private controls(id:string){return [new ActionRowBuilder<ButtonBuilder>().addComponents(new ButtonBuilder().setCustomId(`poker:join:${id}:500`).setLabel('Join · 500').setStyle(ButtonStyle.Primary),new ButtonBuilder().setCustomId(`poker:bot:${id}:500`).setLabel('Add Bot · 500').setStyle(ButtonStyle.Secondary),new ButtonBuilder().setCustomId(`poker:start:${id}`).setLabel('Start Table').setStyle(ButtonStyle.Success),new ButtonBuilder().setCustomId(`poker:cancel:${id}`).setLabel('Cancel & Refund').setStyle(ButtonStyle.Danger))];}
 private playingControls(id:string){return [new ActionRowBuilder<ButtonBuilder>().addComponents(new ButtonBuilder().setCustomId(`poker:private:${id}`).setLabel('View Private Hand').setStyle(ButtonStyle.Primary))];}
 private actionControls(id:string,view:PokerPrivateView){if(!view.canAct)return[];return [new ActionRowBuilder<ButtonBuilder>().addComponents(...view.availableActions.map(action=>{const label=action==='call'?`Call · ${view.callAmount}`:action==='raise'?`Raise · min ${view.minimumRaise}`:action==='allin'?`All-in · ${view.stack}`:action[0]!.toUpperCase()+action.slice(1);return new ButtonBuilder().setCustomId(`poker:${action}:${id}`).setLabel(label.slice(0,80)).setStyle(action==='fold'?ButtonStyle.Danger:action==='raise'||action==='allin'?ButtonStyle.Primary:ButtonStyle.Secondary);}))];}
}
