import {ActionRowBuilder,ButtonBuilder,ButtonStyle,type ButtonInteraction,type ChatInputCommandInteraction} from 'discord.js';
import {DomainError} from '../../../../packages/core/src/index.js';
import {PrismaPokerRepository,type PokerContext} from '../../../../packages/features-casino/src/poker-repository.js';
import {privatePokerView,publicPokerView} from '../../../../packages/features-casino/src/poker.js';
export const POKER_CHANNEL_ID='1557660895813963908';
export class DiscordPokerCoordinator {
 constructor(private readonly repo:PrismaPokerRepository,private readonly mainChannel: (guildId:string)=>Promise<string|undefined>){ }
 private async context(i:ChatInputCommandInteraction|ButtonInteraction):Promise<PokerContext>{if(!i.guildId||!i.channelId)throw new DomainError('SERVER_ONLY','Use Poker in the server.');const configured=await this.mainChannel(i.guildId);const channel=configured??POKER_CHANNEL_ID;if(i.channelId!==channel)throw new DomainError('POKER_CHANNEL',`Use the configured poker room: <#${channel}>.`);return{guildId:i.guildId,channelId:i.channelId,userId:i.user.id,requestKey:i.id};}
 async handle(i:ChatInputCommandInteraction|ButtonInteraction){const c=await this.context(i);if(i.isChatInputCommand()){const variant=i.commandName==='holdem'?'holdem':i.commandName==='omaha'?'omaha':null;if(!variant)throw new DomainError('POKER_COMMAND','Choose Hold’em or Omaha.');const buyIn=BigInt(i.options.getInteger('buy_in',true));const result=await this.repo.start(c,variant,i.user.username,buyIn);await i.reply({content:`${variant==='holdem'?'Texas Hold’em':'Omaha'} table opened. Buy-in reserved; use the private controls to join.`,components:this.controls(result.sessionId,true),allowedMentions:{parse:[]}});return;}const [,action,id]=i.customId.split(':');await i.deferUpdate();if(action==='join'){await this.repo.join(c,id!,i.user.username,BigInt((i.customId.split(':')[3]??'500')),false);await i.editReply({content:'Seat joined. Your cards and actions remain private.',components:this.controls(id!,false)});return;}if(action==='cancel'){await this.repo.cancel(c,id!);await i.editReply({content:'Poker table cancelled. Buy-ins refunded.',components:[]});return;}if(action==='start'){await this.repo.startPlaying(c,id!);await i.editReply({content:'Poker hand started. Shared board state is public; hole cards are private.',components:this.controls(id!,false)});return;}throw new DomainError('POKER_CONTROL','That Poker control is unavailable.');}
 private controls(id:string,host:boolean){const row=new ActionRowBuilder<ButtonBuilder>();row.addComponents(new ButtonBuilder().setCustomId(`poker:join:${id}:500`).setLabel('Join · 500').setStyle(ButtonStyle.Primary));if(host)row.addComponents(new ButtonBuilder().setCustomId(`poker:start:${id}`).setLabel('Start Table').setStyle(ButtonStyle.Success));row.addComponents(new ButtonBuilder().setCustomId(`poker:cancel:${id}`).setLabel('Cancel & Refund').setStyle(ButtonStyle.Danger));return[row];}
 publicView(handId:string){return publicPokerView as unknown as (hand:unknown)=>unknown;}
 privateView(hand:unknown,userId:string){return privatePokerView(hand as never,userId);}
}
