import {createCipheriv,createHash,randomBytes} from 'node:crypto';
import {
  ActionRowBuilder,AuditLogEvent,ButtonBuilder,ButtonStyle,PermissionFlagsBits,
  type ButtonInteraction,type ChatInputCommandInteraction,type Client,type Guild,type GuildAuditLogsEntry,type GuildMember,type Message,
} from 'discord.js';
import type {ConfigService} from '../../../../packages/core/src/index.js';
import {DomainError} from '../../../../packages/core/src/index.js';
import type {ModerationService,ModerationCaseRecord} from '../../../../packages/features-moderation/src/index.js';
import type {SecurityService,HeatPolicy,JoinPolicy,RaidPolicy,AntiNukePolicy,SecurityMode} from '../../../../packages/features-security/src/index.js';

const asBool=(v:unknown,d:boolean)=>typeof v==='boolean'?v:d;
const asInt=(v:unknown,d:number)=>typeof v==='number'&&Number.isFinite(v)?Math.trunc(v):d;
const csv=(v:unknown)=>typeof v==='string'?v.split(',').map(x=>x.trim()).filter(Boolean):[];
const roleId=async(c:ConfigService,g:string,k:string)=>{const v=await c.get(g,k);return typeof v==='string'&&v?v:null;};
const dangerous=PermissionFlagsBits.Administrator|PermissionFlagsBits.ManageGuild|PermissionFlagsBits.ManageRoles|PermissionFlagsBits.ManageChannels|PermissionFlagsBits.KickMembers|PermissionFlagsBits.BanMembers|PermissionFlagsBits.ManageWebhooks;
const sendState=(channel:any,everyoneId:string):'allow'|'deny'|'inherit'=>{const ow=channel.permissionOverwrites?.cache?.get(everyoneId);return ow?.allow?.has(PermissionFlagsBits.SendMessages)?'allow':ow?.deny?.has(PermissionFlagsBits.SendMessages)?'deny':'inherit';};
const restoreValue=(v:unknown)=>v==='allow'?true:v==='deny'?false:null;

interface RecentMessage {at:number;fingerprint:string;attachments:number;}

export class DiscordSecurityCoordinator {
  private readonly recent=new Map<string,RecentMessage[]>();
  constructor(private readonly service:SecurityService,private readonly moderation:ModerationService,private readonly config:ConfigService){}

  async handleMessage(message:Message):Promise<void>{
    if(!message.guild||message.system||message.author.id===message.client.user.id)return;
    if(!asBool(await this.config.get(message.guild.id,'moderation.automod_enabled'),true))return;
    const trustedBots=new Set(csv(await this.config.get(message.guild.id,'security.trusted_bots_csv')));if(message.author.bot&&trustedBots.has(message.author.id))return;
    const member=message.member;const ordinaryExempt=member?await this.isStaff(member):false;
    const key=`${message.guild.id}:${message.author.id}`;const now=Date.now();const fingerprint=message.content.trim().toLowerCase().replace(/\s+/g,' ').slice(0,500);const prior=(this.recent.get(key)??[]).filter(x=>now-x.at<=15_000);const recentSame=prior.filter(x=>fingerprint&&x.fingerprint===fingerprint).length;const attachmentTotal=prior.reduce((n,x)=>n+x.attachments,0)+message.attachments.size;prior.push({at:now,fingerprint,attachments:message.attachments.size});this.recent.set(key,prior.slice(-30));
    const policy=await this.heatPolicy(message.guild.id);const decision=await this.service.evaluateMessage({guildId:message.guild.id,userId:message.author.id,content:message.content,mentionCount:message.mentions.users.size+message.mentions.roles.size,attachmentCount:message.attachments.size,stickerCount:message.stickers.size,recentMessageCount:prior.length,recentSameCount:recentSame,recentAttachmentCount:attachmentTotal,trustedDomains:csv(await this.config.get(message.guild.id,'security.trusted_domains_csv')),bannedPhrases:csv(await this.config.get(message.guild.id,'moderation.banned_phrases_csv')),ordinaryExempt},policy);
    if(decision.action==='ALLOW')return;
    if(decision.action==='LOG'){if(decision.signals.some(s=>s.severity>=2))await this.staffLog(message.guild,`**AutoMod observed** • ${message.author}\n${decision.reason}\nHeat: ${decision.heat?.score??0}`).catch(()=>undefined);await this.raidAfterSignal(message.guild);return;}
    const reason=`AutoMod: ${decision.reason??'Configured message rule triggered.'}`;const primary=decision.signals[0]?.category??'automod';
    let c:ModerationCaseRecord|undefined;
    try{
      if(decision.action==='TIMEOUT'&&member){c=await this.moderation.prepare({guildId:message.guild.id,subjectUserId:message.author.id,actorType:'SYSTEM',actionType:'TIMEOUT',reason,category:primary,policyId:`automod.${primary}`,sourceChannelId:message.channelId,sourceMessageId:message.id,...(decision.timeoutSeconds===undefined?{}:{durationSeconds:decision.timeoutSeconds}),metadata:{automod:true,heat:decision.heat?.score,signals:decision.signals.map(s=>s.category)}});if(message.deletable)await message.delete();if(!member.moderatable)throw new DomainError('AUTOMOD_TARGET_UNMANAGEABLE','AutoMod cannot timeout this member because of server hierarchy.');await member.timeout((decision.timeoutSeconds??600)*1000,`${reason} — case #${c.id}`);await this.moderation.finalize(c.id,'ACTIVE',{eventKind:'AUTOMOD_TIMEOUT_APPLIED',metadata:{heat:decision.heat?.score,automod:true}});await this.moderation.scheduleTemporaryCase(c,message.author.id,decision.timeoutSeconds??600,'moderation.timeout_expire');await this.memberNotice(member,c,'Automatic timeout',reason).catch(()=>undefined);}
      else if(decision.action==='QUARANTINE'||decision.action==='REVIEW'){c=await this.moderation.prepare({guildId:message.guild.id,subjectUserId:message.author.id,actorType:'SYSTEM',actionType:'QUARANTINE',reason,category:primary,policyId:`automod.${primary}`,sourceChannelId:message.channelId,sourceMessageId:message.id,metadata:{automod:true,heat:decision.heat?.score,reviewRequired:decision.action==='REVIEW'}});const secret=process.env.EVIDENCE_ENCRYPTION_KEY??'';if(secret.length>=16){const encrypted=this.encrypt([{id:message.id,authorId:message.author.id,createdAt:message.createdAt.toISOString(),content:message.content,attachments:[...message.attachments.values()].map(a=>({name:a.name,url:a.url,contentType:a.contentType}))}],secret);const retention=asInt(await this.config.get(message.guild.id,'moderation.evidence_retention_days'),30);await this.moderation.storeEvidence({caseRecord:c,contentCiphertext:encrypted,context:{channelId:message.channelId,messageId:message.id,automod:true},retentionDays:retention});}if(message.deletable)await message.delete();await this.moderation.finalize(c.id,'OPEN',{eventKind:'AUTOMOD_QUARANTINED',metadata:{heat:decision.heat?.score,reviewRequired:decision.action==='REVIEW'}});if(member)await this.memberNotice(member,c,'Message removed for review',reason).catch(()=>undefined);}
      else if(decision.action==='WARN'){c=await this.moderation.prepare({guildId:message.guild.id,subjectUserId:message.author.id,actorType:'SYSTEM',actionType:'WARN',reason,category:primary,policyId:`automod.${primary}`,sourceChannelId:message.channelId,sourceMessageId:message.id,metadata:{automod:true,heat:decision.heat?.score}});if(message.deletable)await message.delete();await this.moderation.finalize(c.id,'OPEN',{eventKind:'AUTOMOD_WARNING_ISSUED'});if(member)await this.memberNotice(member,c,'Automatic warning',reason).catch(()=>undefined);}
      else {c=await this.moderation.prepare({guildId:message.guild.id,subjectUserId:message.author.id,actorType:'SYSTEM',actionType:'AUTOMOD',reason,category:primary,policyId:`automod.${primary}`,sourceChannelId:message.channelId,sourceMessageId:message.id,metadata:{automod:true,heat:decision.heat?.score,action:decision.action}});if(message.deletable)await message.delete();await this.moderation.finalize(c.id,'OPEN',{eventKind:'AUTOMOD_MESSAGE_DELETED'});}
      await this.staffLog(message.guild,`**AutoMod — case #${c?.id??'?'}**\nMember: ${message.author}\nAction: **${decision.action}**\nReason: ${decision.reason}\nHeat: **${decision.heat?.score??0}**`).catch(()=>undefined);
    }catch(error){if(c)await this.moderation.enforcementFailed(c.id,undefined,reason,error).catch(()=>undefined);throw error;}finally{await this.raidAfterSignal(message.guild).catch(()=>undefined);}
  }

  async handleMemberAdd(member:GuildMember):Promise<void>{
    const guildId=member.guild.id;const state=await this.service.state(guildId);const history=await this.moderation.history(guildId,member.id,10).catch(()=>({cases:[],notes:[]}));const policy=await this.joinPolicy(guildId);const decision=await this.service.joinGate({guildId,userId:member.id,createdAt:member.user.createdAt,isBot:member.user.bot,username:member.user.username,priorCaseCount:history.cases.length,currentMode:state.mode},policy);
    if(decision.action==='KICK'){const c=await this.moderation.prepare({guildId,subjectUserId:member.id,actorType:'SYSTEM',actionType:'ANTI_RAID',reason:decision.reasons.join('; ')||'Unauthorized bot addition.',category:'join_gate',policyId:'security.join_gate',metadata:{riskScore:decision.riskScore,action:decision.action}});try{if(member.kickable)await member.kick(`Join Gate — case #${c.id}`);else throw new DomainError('JOIN_GATE_CANNOT_KICK','Join Gate flagged a high-confidence rejection but Angrier Jordan cannot kick this member.');await this.moderation.finalize(c.id,'OPEN',{eventKind:'JOIN_GATE_REJECTED'});}catch(error){await this.moderation.enforcementFailed(c.id,undefined,c.reason,error);}await this.staffLog(member.guild,`**Join Gate rejected** ${member.user.tag}\nRisk: ${decision.riskScore}\n${decision.reasons.join('\n')}`).catch(()=>undefined);}
    else if(decision.action==='VERIFY'||decision.action==='RESTRICT'){await this.removeMemberAccess(member,`Join Gate: ${decision.action}`);await this.staffLog(member.guild,`**Join Gate ${decision.action.toLowerCase()}** ${member}\nRisk: ${decision.riskScore}\n${decision.reasons.join('\n')}`).catch(()=>undefined);}
    else if(decision.action==='FLAG')await this.staffLog(member.guild,`**Suspicious join flagged** ${member}\nRisk: ${decision.riskScore}\n${decision.reasons.join('\n')}`).catch(()=>undefined);
    const raid=await this.service.evaluateRaid(guildId,await this.raidPolicy(guildId));if(raid.changed)await this.staffLog(member.guild,`**Anti-raid state changed → ${raid.mode}**\n${raid.reason}`).catch(()=>undefined);
  }

  async enforceAfterRulesAck(member:GuildMember,interaction:ButtonInteraction):Promise<boolean>{const v=await this.service.verification(member.guild.id,member.id);if(v?.status!=='REQUIRED')return false;await this.removeMemberAccess(member,'Verification required by Join Gate.');const row=new ActionRowBuilder<ButtonBuilder>().addComponents(new ButtonBuilder().setCustomId('security:verify').setLabel('Verify').setStyle(ButtonStyle.Success));await interaction.followUp({ephemeral:true,content:`Join Gate requires a quick verification before normal access is restored.${v.reason?`\nReason: ${v.reason}`:''}`,components:[row]});return true;}
  async handleVerifyButton(interaction:ButtonInteraction):Promise<void>{if(!interaction.guild)throw new DomainError('SERVER_ONLY','Verification must be completed inside the server.');const current=await this.service.verification(interaction.guild.id,interaction.user.id);if(!current||current.status!=='REQUIRED'){await interaction.reply({ephemeral:true,content:'No Join Gate verification is currently required.'});return;}await this.service.verify(interaction.guild.id,interaction.user.id);await interaction.reply({ephemeral:true,content:'Verification complete. Your normal access can now be restored.'});}
  async isRestricted(guildId:string,userId:string){const v=await this.service.verification(guildId,userId);return v?.status==='REQUIRED';}

  async handleAuditEntry(entry:GuildAuditLogsEntry,guild:Guild):Promise<void>{
    if(!asBool(await this.config.get(guild.id,'security.anti_nuke_enabled'),true))return;const mapped=this.auditKind(entry.action);if(!mapped)return;const actor=entry.executorId??undefined;if(actor===guild.client.user.id)return;const policy=await this.antiNukePolicy(guild.id);const decision=await this.service.observePrivileged({guildId:guild.id,...(actor?{actorUserId:actor}:{}),kind:mapped.kind,targetId:entry.targetId??undefined,severity:mapped.severity,metadata:{action:entry.action}},policy);if(decision.action==='LOG')return;
    let removed:string[]=[];if((decision.action==='CONTAIN'||decision.action==='LOCKDOWN')&&actor&&actor!==guild.ownerId){const m=await guild.members.fetch(actor).catch(()=>null);if(m&&m.manageable){for(const role of m.roles.cache.values()){if(role.id===guild.id||role.managed||!role.editable)continue;if((role.permissions.bitfield&dangerous)!==0n){await m.roles.remove(role,`Anti-nuke containment: ${decision.reason}`).then(()=>removed.push(role.id)).catch(()=>undefined);}}}}
    const c=await this.moderation.prepare({guildId:guild.id,...(actor?{subjectUserId:actor}:{}),actorType:'SYSTEM',actionType:'ANTI_NUKE',reason:decision.reason,category:'anti_nuke',policyId:'security.anti_nuke',metadata:{action:decision.action,auditKind:mapped.kind,removedRoleIds:removed,trusted:decision.trusted,score:decision.score,count:decision.count}});await this.moderation.finalize(c.id,'OPEN',{eventKind:`ANTI_NUKE_${decision.action}`,metadata:{removedRoleIds:removed}});
    if(decision.action==='LOCKDOWN'){const state=await this.service.setMode(guild.id,'LOCKDOWN',decision.reason,'anti_nuke',asInt(await this.config.get(guild.id,'security.restricted_mode_auto_deescalate_minutes'),30));await this.staffLog(guild,`**ANTI-NUKE LOCKDOWN — case #${c.id}**\nActor: ${actor?`<@${actor}>`:'Unknown'}\n${decision.reason}\nDangerous roles removed: ${removed.length}\nMode: ${state.mode}`).catch(()=>undefined);}else await this.staffLog(guild,`**Anti-nuke ${decision.action.toLowerCase()} — case #${c.id}**\nActor: ${actor?`<@${actor}>`:'Unknown'}\n${decision.reason}\nDangerous roles removed: ${removed.length}`).catch(()=>undefined);
  }

  async handlePanicCommand(i:ChatInputCommandInteraction):Promise<void>{if(!i.guild)throw new DomainError('SERVER_ONLY','Panic Mode is server-only.');await this.requireThrone(await i.guild.members.fetch(i.user.id));const sub=i.options.getSubcommand();if(sub==='status'){const s=await this.service.state(i.guild.id);await i.reply({ephemeral:true,content:`**Panic / security status**\nMode: **${s.mode}**\nPanic active: **${s.panicActive?'YES':'NO'}**\nSource: ${s.source}${s.reason?`\nReason: ${s.reason}`:''}${s.expiresAt?`\nAuto-expiry: <t:${Math.floor(s.expiresAt.getTime()/1000)}:R>`:''}`});return;}if(sub==='activate'){const enabled=asBool(await this.config.get(i.guild.id,'security.panic_mode_enabled'),true);if(!enabled)throw new DomainError('PANIC_DISABLED','Panic Mode is disabled in server settings.');const reason=i.options.getString('reason',true);const snapshot=await this.applyPanicChannels(i.guild,reason);const c=await this.moderation.prepare({guildId:i.guild.id,actorUserId:i.user.id,actionType:'PANIC',reason,category:'panic',policyId:'security.panic',metadata:{channelCount:(snapshot.channels as any[])?.length??0}});try{await this.service.activatePanic(i.guild.id,i.user.id,reason,snapshot);await this.moderation.finalize(c.id,'ACTIVE',{actorUserId:i.user.id,eventKind:'PANIC_ACTIVATED'});await this.staffLog(i.guild,`**PANIC MODE ACTIVATED — case #${c.id}**\nBy: ${i.user}\nReason: ${reason}\nPublic-channel send restrictions were snapshotted and applied.`).catch(()=>undefined);await i.reply({ephemeral:true,content:`Panic Mode is active. Security mode is **LOCKDOWN**. Case #${c.id}.`});}catch(error){await this.restorePanicChannels(i.guild,snapshot).catch(()=>undefined);await this.moderation.enforcementFailed(c.id,i.user.id,reason,error);throw error;}return;}if(sub==='deactivate'){const row=new ActionRowBuilder<ButtonBuilder>().addComponents(new ButtonBuilder().setCustomId('security:panic_deactivate_confirm').setLabel('Confirm Restore').setStyle(ButtonStyle.Danger));await i.reply({ephemeral:true,content:'Deactivate Panic Mode and restore the saved pre-panic channel state?',components:[row]});return;}}
  async handlePanicDeactivateConfirm(i:ButtonInteraction):Promise<void>{if(!i.guild)throw new DomainError('SERVER_ONLY','Panic Mode is server-only.');await this.requireThrone(await i.guild.members.fetch(i.user.id));const current=await this.service.state(i.guild.id);if(!current.panicActive){await i.reply({ephemeral:true,content:'Panic Mode is not active.'});return;}await this.restorePanicChannels(i.guild,current.snapshot??{});const out=await this.service.deactivatePanic(i.guild.id,i.user.id);await this.staffLog(i.guild,`**Panic Mode deactivated** by ${i.user}. Restored saved pre-panic channel state. Security mode: **${out.state.mode}**.`).catch(()=>undefined);await i.update({content:`Panic Mode deactivated. Saved channel state restored. Security mode: **${out.state.mode}**.`,components:[]});}
  async handleExpiryJob(payload:unknown){const d=payload&&typeof payload==='object'?payload as Record<string,unknown>:{};const guildId=typeof d.guildId==='string'?d.guildId:'';if(guildId)await this.service.expireSecurityState(guildId);}

  private async heatPolicy(g:string):Promise<HeatPolicy>{return{decayHours:asInt(await this.config.get(g,'moderation.heat_decay_hours'),72),warningThreshold:asInt(await this.config.get(g,'moderation.heat.warning_threshold'),20),shortTimeoutThreshold:asInt(await this.config.get(g,'moderation.heat.short_timeout_threshold'),40),longTimeoutThreshold:asInt(await this.config.get(g,'moderation.heat.long_timeout_threshold'),70),reviewThreshold:asInt(await this.config.get(g,'moderation.heat.review_threshold'),100),shortTimeoutSeconds:asInt(await this.config.get(g,'moderation.heat.short_timeout_minutes'),10)*60,longTimeoutSeconds:asInt(await this.config.get(g,'moderation.heat.long_timeout_minutes'),60)*60};}
  private async joinPolicy(g:string):Promise<JoinPolicy>{return{enabled:asBool(await this.config.get(g,'security.join_gate_enabled'),true),verificationEnabled:asBool(await this.config.get(g,'security.verification_enabled'),true),minimumAccountAgeHours:asInt(await this.config.get(g,'security.join.minimum_account_age_hours'),72),joinVelocityPerMinute:asInt(await this.config.get(g,'security.raid.join_velocity_per_minute'),10),restrictedModeAutoDeescalateMinutes:asInt(await this.config.get(g,'security.restricted_mode_auto_deescalate_minutes'),30),trustedBotIds:csv(await this.config.get(g,'security.trusted_bots_csv'))};}
  private async raidPolicy(g:string):Promise<RaidPolicy>{return{enabled:asBool(await this.config.get(g,'security.anti_raid_enabled'),true),joinVelocityPerMinute:asInt(await this.config.get(g,'security.raid.join_velocity_per_minute'),10),autoDeescalateMinutes:asInt(await this.config.get(g,'security.restricted_mode_auto_deescalate_minutes'),30)};}
  private async antiNukePolicy(g:string):Promise<AntiNukePolicy>{return{enabled:asBool(await this.config.get(g,'security.anti_nuke_enabled'),true),eventsPerMinute:asInt(await this.config.get(g,'security.anti_nuke.events_per_minute'),4),lockdownEventsPerMinute:asInt(await this.config.get(g,'security.anti_nuke.lockdown_events_per_minute'),7),trustedUserIds:csv(await this.config.get(g,'security.trusted_users_csv'))};}
  private async raidAfterSignal(guild:Guild){const raid=await this.service.evaluateRaid(guild.id,await this.raidPolicy(guild.id));if(raid.changed)await this.staffLog(guild,`**Anti-raid state changed → ${raid.mode}**\n${raid.reason}`);}
  private async isStaff(m:GuildMember){if(m.id===m.guild.ownerId)return true;const ids=await Promise.all(['roles.recliner','roles.chaise_lounge','roles.throne'].map(k=>roleId(this.config,m.guild.id,k)));return ids.some(id=>id&&m.roles.cache.has(id));}
  private async requireThrone(m:GuildMember){if(m.id===m.guild.ownerId)return;const throne=await roleId(this.config,m.guild.id,'roles.throne');if(!throne||!m.roles.cache.has(throne))throw new DomainError('THRONE_REQUIRED','Panic Mode requires Throne authority.');}
  private async removeMemberAccess(m:GuildMember,reason:string){const access=await roleId(this.config,m.guild.id,'roles.member_access');if(access&&m.roles.cache.has(access))await m.roles.remove(access,reason).catch(()=>undefined);}
  private async memberNotice(m:GuildMember,c:ModerationCaseRecord,label:string,detail:string){const row=new ActionRowBuilder<ButtonBuilder>().addComponents(new ButtonBuilder().setCustomId(`moderation:review:${c.id}`).setLabel('Request Review').setStyle(ButtonStyle.Secondary));await m.send({content:`**Angrier Jordan — ${label}**\n${detail}\nCase #${c.id}`,components:[row]});}
  private async staffLog(g:Guild,content:string){const id=await roleId(this.config,g.id,'channels.staff_log');if(!id)return;const ch:any=await g.channels.fetch(id).catch(()=>null);if(ch?.isTextBased())await ch.send({content:content.slice(0,1900)});}
  private encrypt(payload:unknown,secret:string){const key=createHash('sha256').update(secret).digest();const iv=randomBytes(12);const cipher=createCipheriv('aes-256-gcm',key,iv);const encrypted=Buffer.concat([cipher.update(Buffer.from(JSON.stringify(payload),'utf8')),cipher.final()]);return`v1.${iv.toString('base64url')}.${cipher.getAuthTag().toString('base64url')}.${encrypted.toString('base64url')}`;}
  private async applyPanicChannels(g:Guild,reason:string){const exclusions=new Set((await Promise.all(['channels.staff_log','channels.hotseat_channel'].map(k=>roleId(this.config,g.id,k)))).filter((x):x is string=>Boolean(x)));const channels:any[]=[];for(const ch of g.channels.cache.values()){const any:any=ch;if(exclusions.has(ch.id)||!any.permissionOverwrites||!any.isTextBased?.())continue;const state=sendState(any,g.roles.everyone.id);channels.push({channelId:ch.id,sendMessages:state});await any.permissionOverwrites.edit(g.roles.everyone,{SendMessages:false},{reason:`Panic Mode: ${reason}`});}return{channels,featureLocks:['wagers','transfers','custom_command_creation','interactive_games'],inviteSuspension:'not-applied-without-restorable-discord-state'};}
  private async restorePanicChannels(g:Guild,snapshot:Record<string,unknown>){const rows=Array.isArray(snapshot.channels)?snapshot.channels as Array<{channelId:string;sendMessages:string}>:[];for(const row of rows){const ch:any=await g.channels.fetch(row.channelId).catch(()=>null);if(!ch?.permissionOverwrites)continue;await ch.permissionOverwrites.edit(g.roles.everyone,{SendMessages:restoreValue(row.sendMessages)},{reason:'Restoring exact pre-Panic Send Messages state.'});}}
  private auditKind(action:AuditLogEvent|number){const map=new Map<any,{kind:string;severity:1|2|3|4}>([[AuditLogEvent.ChannelCreate,{kind:'CHANNEL_CREATE',severity:2}],[AuditLogEvent.ChannelDelete,{kind:'CHANNEL_DELETE',severity:4}],[AuditLogEvent.ChannelUpdate,{kind:'CHANNEL_UPDATE',severity:2}],[AuditLogEvent.RoleCreate,{kind:'ROLE_CREATE',severity:2}],[AuditLogEvent.RoleDelete,{kind:'ROLE_DELETE',severity:4}],[AuditLogEvent.RoleUpdate,{kind:'ROLE_UPDATE',severity:3}],[AuditLogEvent.MemberKick,{kind:'MEMBER_KICK',severity:3}],[AuditLogEvent.MemberBanAdd,{kind:'MEMBER_BAN',severity:3}],[AuditLogEvent.MemberRoleUpdate,{kind:'MEMBER_ROLE_UPDATE',severity:3}],[AuditLogEvent.BotAdd,{kind:'BOT_ADD',severity:4}],[AuditLogEvent.WebhookCreate,{kind:'WEBHOOK_CREATE',severity:3}],[AuditLogEvent.WebhookDelete,{kind:'WEBHOOK_DELETE',severity:3}],[AuditLogEvent.GuildUpdate,{kind:'GUILD_UPDATE',severity:3}],[AuditLogEvent.ChannelOverwriteCreate,{kind:'CHANNEL_OVERWRITE_CREATE',severity:3}],[AuditLogEvent.ChannelOverwriteUpdate,{kind:'CHANNEL_OVERWRITE_UPDATE',severity:3}],[AuditLogEvent.ChannelOverwriteDelete,{kind:'CHANNEL_OVERWRITE_DELETE',severity:3}]]);return map.get(action);}
}
