'use client';
import { useEffect, useMemo, useState } from 'react';
import type { ContentGroup } from '../../lib/content';

type Entry={id:string;game:string;category:string|null;enabled:boolean;useCount:number;lastUsedAt:string|null;tags:string[];text:string};

export default function ContentBrowser({groups,csrf,writesEnabled}:{groups:ContentGroup[];csrf:string;writesEnabled:boolean}){
  const [game,setGame]=useState(groups[0]?.game??''),[entries,setEntries]=useState<Entry[]>([]),[query,setQuery]=useState(''),[state,setState]=useState<'idle'|'loading'|'error'>('idle'),[updating,setUpdating]=useState<string|null>(null),[message,setMessage]=useState('');
  useEffect(()=>{if(!game)return;let active=true;setState('loading');setQuery('');fetch(`/api/content?game=${encodeURIComponent(game)}`,{cache:'no-store'}).then(async response=>({response,body:await response.json()})).then(({response,body})=>{if(!active)return;if(!response.ok)throw new Error();setEntries(body.entries);setState('idle');}).catch(()=>{if(active){setEntries([]);setState('error');}});return()=>{active=false;};},[game]);
  const filtered=useMemo(()=>{const term=query.trim().toLowerCase();return term?entries.filter(entry=>[entry.text,entry.category,...entry.tags].filter((value):value is string=>typeof value==='string').some(value=>value.toLowerCase().includes(term))):entries;},[entries,query]);
  async function updateEnabled(entry:Entry){
    setUpdating(entry.id);setMessage('');
    try{const response=await fetch('/api/content',{method:'POST',headers:{'Content-Type':'application/json','x-csrf-token':csrf},body:JSON.stringify({id:entry.id,enabled:!entry.enabled})});const body=await response.json();if(!response.ok){setMessage(body.error??'The content entry could not be updated.');return;}setEntries(current=>current.map(item=>item.id===entry.id?{...item,enabled:body.enabled}:item));setMessage(`${body.enabled?'Enabled':'Disabled'} this content entry.`);}
    catch{setMessage('The content entry could not be updated. Please try again.');}finally{setUpdating(null);}
  }
  if(!groups.length)return <p className="description">No authored content pools are available.</p>;
  return <><div className="content-controls"><label htmlFor="content-pool"><span>Content pool</span><select id="content-pool" value={game} onChange={event=>setGame(event.target.value)}>{groups.map(group=><option key={group.game} value={group.game}>{group.game.replaceAll('_',' ')} · {group.enabled} live</option>)}</select></label><label htmlFor="content-search"><span>Filter loaded entries</span><input id="content-search" type="search" value={query} placeholder="Search this pool" onChange={event=>setQuery(event.target.value)}/></label></div><p className="description">Showing up to 60 existing entries from the selected canonical pool. Enable or disable is audited; text edits and reseeding remain unavailable.</p>{message&&<p className="lookup-message" role="status">{message}</p>}{state==='loading'?<p className="lookup-message" role="status">Loading content…</p>:state==='error'?<p className="lookup-message" role="status">The content library could not be loaded.</p>:<ol className="content-list">{filtered.map(entry=><li key={entry.id}><div><p>{entry.text}</p><span>{entry.category??'Uncategorized'} · used {entry.useCount} times{entry.tags.length?` · ${entry.tags.join(', ')}`:''}</span></div><div className="content-actions"><b className={entry.enabled?'content-live':'content-disabled'}>{entry.enabled?'Live':'Disabled'}</b><button className="quiet" disabled={!writesEnabled||updating===entry.id} onClick={()=>updateEnabled(entry)}>{updating===entry.id?'Saving…':entry.enabled?'Disable':'Enable'}</button></div></li>)}</ol>}</>;
}
