'use client';
import { useEffect, useMemo, useState } from 'react';
import type { ContentGroup } from '../../lib/content';

type Entry={id:string;game:string;category:string|null;enabled:boolean;useCount:number;lastUsedAt:string|null;tags:string[];text:string;editable:boolean};

export default function ContentBrowser({groups,csrf,writesEnabled}:{groups:ContentGroup[];csrf:string;writesEnabled:boolean}){
  const [game,setGame]=useState(groups[0]?.game??''),[entries,setEntries]=useState<Entry[]>([]),[query,setQuery]=useState(''),[state,setState]=useState<'idle'|'loading'|'error'>('idle'),[updating,setUpdating]=useState<string|null>(null),[message,setMessage]=useState(''),[editing,setEditing]=useState<string|null>(null),[draftText,setDraftText]=useState('');
  useEffect(()=>{if(!game)return;let active=true;setState('loading');setQuery('');fetch(`/api/content?game=${encodeURIComponent(game)}`,{cache:'no-store'}).then(async response=>({response,body:await response.json()})).then(({response,body})=>{if(!active)return;if(!response.ok)throw new Error();setEntries(body.entries);setState('idle');}).catch(()=>{if(active){setEntries([]);setState('error');}});return()=>{active=false;};},[game]);
  const filtered=useMemo(()=>{const term=query.trim().toLowerCase();return term?entries.filter(entry=>[entry.text,entry.category,...entry.tags].filter((value):value is string=>typeof value==='string').some(value=>value.toLowerCase().includes(term))):entries;},[entries,query]);
  async function save(entry:Entry,payload:Record<string,unknown>,success:string){
    setUpdating(entry.id);setMessage('');
    try{const response=await fetch('/api/content',{method:'POST',headers:{'Content-Type':'application/json','x-csrf-token':csrf},body:JSON.stringify(payload)}),body=await response.json();if(!response.ok){setMessage(body.error??'The content entry could not be updated.');return;}setEntries(current=>current.map(item=>item.id===entry.id?{...item,enabled:body.enabled,text:body.text??item.text,editable:body.editable!==false}:item));setEditing(null);setMessage(success);}
    catch{setMessage('The content entry could not be updated. Please try again.');}finally{setUpdating(null);}
  }
  if(!groups.length)return <p className="description">No authored content pools are available.</p>;
  return <><div className="content-controls"><label htmlFor="content-pool"><span>Content pool</span><select id="content-pool" value={game} onChange={event=>setGame(event.target.value)}>{groups.map(group=><option key={group.game} value={group.game}>{group.game.replaceAll('_',' ')} · {group.enabled} live</option>)}</select></label><label htmlFor="content-search"><span>Filter loaded entries</span><input id="content-search" type="search" value={query} placeholder="Search this pool" onChange={event=>setQuery(event.target.value)}/></label></div><p className="description">Showing up to 60 existing entries from the selected canonical pool. Every change is audited; structured entries remain read-only.</p>{message&&<p className="lookup-message" role="status">{message}</p>}{state==='loading'?<p className="lookup-message" role="status">Loading content…</p>:state==='error'?<p className="lookup-message" role="status">The content library could not be loaded.</p>:<ol className="content-list">{filtered.map(entry=><li key={entry.id}><div className="content-copy">{editing===entry.id?<textarea value={draftText} maxLength={1800} rows={4} onChange={event=>setDraftText(event.target.value)}/>:<p>{entry.text}</p>}<span>{entry.category??'Uncategorized'} · used {entry.useCount} times{entry.tags.length?` · ${entry.tags.join(', ')}`:''}</span></div><div className="content-actions"><b className={entry.enabled?'content-live':'content-disabled'}>{entry.enabled?'Live':'Disabled'}</b>{editing===entry.id?<><button className="quiet" disabled={updating===entry.id||!draftText.trim()} onClick={()=>save(entry,{action:'text',id:entry.id,text:draftText},'Updated this content entry.')}>{updating===entry.id?'Saving…':'Save text'}</button><button className="quiet" disabled={updating===entry.id} onClick={()=>setEditing(null)}>Cancel</button></>:<><button className="quiet" disabled={!writesEnabled||updating===entry.id} onClick={()=>save(entry,{action:'enabled',id:entry.id,enabled:!entry.enabled},`${entry.enabled?'Disabled':'Enabled'} this content entry.`)}>{updating===entry.id?'Saving…':entry.enabled?'Disable':'Enable'}</button>{entry.editable&&<button className="quiet" disabled={!writesEnabled||updating===entry.id} onClick={()=>{setDraftText(entry.text);setEditing(entry.id)}}>Edit text</button>}</>}</div></li>)}</ol>}</>;
}
