import {draftService} from '../../lib/drafts';
import {readDashboardHomeSummary} from '../../lib/settings';
import {settingsWritesEnabled} from '../../lib/security.mjs';
import DatabaseHealth from './database-health';
import MemberLookup from './member-lookup';
import DashboardShell from './dashboard-shell';
import type {DashboardActor} from '../../../../packages/core/src/config-draft';

type HomeAccess={isGuildOwner:boolean};
export default async function HomePage({guildId,csrf,access,actor}:{guildId:string;csrf:string;access:HomeAccess;actor:DashboardActor}){
  const [summary,draft]=await Promise.all([readDashboardHomeSummary(guildId),draftService().view(guildId,actor)]);
  return <DashboardShell csrf={csrf}><main className="content"><section className="window intro"><p className="eyebrow">{access.isGuildOwner?'Server owner':'Administrator'} · Verified with Discord</p><h1>Your server, at a glance.</h1><p>Review the settings that shape Chairs.</p><div className="notice" role="status">{settingsWritesEnabled()?'Low-risk settings may save live. Broader changes require a reviewed shared draft.':'Read-only preview. Changes remain disabled until dashboard acceptance.'}</div><nav className="quick-links" aria-label="Dashboard shortcuts"><a href="/admin?page=workspace&group=people#members"><span>Find</span><strong>Member lookup</strong></a><a href="/admin?page=workspace&group=economy#economy"><span>Review</span><strong>Economy status</strong></a><a href="/admin?page=workspace&group=community#content"><span>Browse</span><strong>Content library</strong></a><a href="/admin?page=workspace&group=settings#settings-browser"><span>Configure</span><strong>Settings browser</strong></a></nav></section><section id="overview" className="overview-grid" aria-label="Dashboard overview"><DatabaseHealth/><article className="window overview-card"><span>Access</span><strong>{access.isGuildOwner?'Server owner':'Administrator'}</strong><p>Verified through your current Discord permissions.</p></article><article className="window overview-card"><span>Shared draft</span><strong>{Object.keys(draft.changes).length} staged</strong><p>{draft.editorId?'An Administrator currently holds the edit lock.':'No active editor lock.'}</p></article><article className="window overview-card"><span>Feature switches</span><strong>{summary.enabledFeatures} enabled</strong><p>Live feature settings currently enabled for this server.</p></article><article className="window overview-card"><span>Safeguards</span><strong>{summary.reviewed} reviewed</strong><p>{summary.restarts} settings also require a worker restart after publishing.</p></article></section><section id="members" className="window member-section"><div className="section-title"><div><h2>Member lookup</h2><p className="description">Read a member’s current bot record without touching balances, inventory, roles, or cases.</p></div><span className="badge">Read-only</span></div><MemberLookup/></section></main></DashboardShell>;
}
