'use client';
import { FormEvent, useState } from 'react';

type Member={userId:string;nickname:string|null;displayName:string;username:string;lastSyncedAt:string;wallet:string;bank:string;bankTier:number;inventoryEntries:number;inventoryQuantity:number;selfRoleCategories:string[];needsRulesAck:boolean;activeJail:{endsAt:string;indefinite:boolean}|null};
const number=(value:string)=>new Intl.NumberFormat('en-US').format(BigInt(value));

export default function MemberLookup(){
  const [query,setQuery]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[members,setMembers]=useState<Member[]>([]);
  async function search(event:FormEvent){
    event.preventDefault();setBusy(true);setMessage('');setMembers([]);
    try{const response=await fetch(`/api/members?q=${encodeURIComponent(query)}`,{cache:'no-store'});const body=await response.json();if(!response.ok){setMessage(body.error??'Member lookup is unavailable.');return;}setMembers(body.members);if(!body.members.length)setMessage('No current server members match that search.');else if(body.disambiguation)setMessage('Multiple current members match. Choose by Discord ID.');}
    catch{setMessage('Member lookup is unavailable. Please try again.');}finally{setBusy(false);}
  }
  return <><form className="member-search" onSubmit={search}><label htmlFor="member-query"><span>Discord ID, nickname, display name, or username</span><input id="member-query" value={query} maxLength={64} placeholder="Search a current member" onChange={event=>setQuery(event.target.value)}/></label><button disabled={busy||query.trim().length<2}>{busy?'Searching…':'Search members'}</button></form><p className="description">Reads only current guild-directory and bot-owned records. Member corrections remain intentionally unavailable here.</p>{message&&<p className="lookup-message" role="status">{message}</p>}{members.length>0&&<div className="member-results">{members.map(member=><article key={member.userId} className="member-card"><div className="member-heading"><div><span className="member-alias">{member.displayName}</span><small>{member.nickname&&member.nickname!==member.displayName?`Nickname: ${member.nickname} · `:''}@{member.username}</small><code>{member.userId}</code></div>{member.activeJail?<span className="member-alert">Jailed</span>:<span className="feature-on">Active</span>}</div><dl><div><dt>Wallet</dt><dd>{number(member.wallet)} Ottomans</dd></div><div><dt>Bank</dt><dd>{number(member.bank)} · Tier {member.bankTier}</dd></div><div><dt>Inventory</dt><dd>{member.inventoryQuantity} items · {member.inventoryEntries} entries</dd></div><div><dt>Onboarding</dt><dd>{member.needsRulesAck?'Pending rules':'Complete'}</dd></div><div><dt>Self-roles</dt><dd>{member.selfRoleCategories.length?member.selfRoleCategories.join(', '):'None selected'}</dd></div><div><dt>Directory sync</dt><dd>{member.lastSyncedAt.replace('T',' ').replace('.000Z',' UTC')}</dd></div><div><dt>Jail</dt><dd>{member.activeJail?(member.activeJail.indefinite?'Active · indefinite':`Active · until ${member.activeJail.endsAt.replace('T',' ').replace('.000Z',' UTC')}`):'No active sentence'}</dd></div></dl></article>)}</div>}</>;
}
