import type {DashboardActor,ConfigDraft} from '../../../../packages/core/src/config-draft';
import type {ReactNode} from 'react';
import {draftService} from '../../lib/drafts';
import {readSettings,readDashboardHomeSummary} from '../../lib/settings';
import {settingsWritesEnabled} from '../../lib/security.mjs';
import {readEconomyOverview} from '../../lib/economy';
import {readContentGroups} from '../../lib/content';
import {readModerationOverview} from '../../lib/moderation';
import {readRecentAudit} from '../../lib/audit';
import DashboardShell from './dashboard-shell';
import SettingsControls from './controls';
import DatabaseHealth from './database-health';
import MemberLookup from './member-lookup';
import ContentBrowser from './content-browser';
import ActivityList from './activity-list';

type Access={isGuildOwner:boolean;administrator:boolean};
type Props={page:string;guildId:string;csrf:string;userId:string;access:Access};
const settingsPages=new Set(['server','core','channels_roles','games','shop','crafting','casino','lottery','crime','family','community','chairisms','social','haiku','custom_commands','events','spotlight','security','special_commands','tutorial','dashboard','roles_panel','introductions','onboarding','activity']);
const pageWindow=(title:string,copy:string,body:ReactNode)=><section className="window settings-section"><div className="section-title"><div><h1 className="workspace-heading">{title}</h1><p className="description">{copy}</p></div></div>{body}</section>;

export default async function WorkspacePage({page,guildId,csrf,userId,access}:Props){
  const actor:DashboardActor={...access,userId};
  if(page==='overview'){const [summary,draft]=await Promise.all([readDashboardHomeSummary(guildId),draftService().view(guildId,actor)]);return <DashboardShell csrf={csrf}><main className="content"><section className="workspace-title"><p className="eyebrow">Dashboard</p><h1>Overview</h1><p>Current server controls at a glance.</p></section><section className="overview-grid"><DatabaseHealth/><article className="window overview-card"><span>Access</span><strong>{access.isGuildOwner?'Server owner':'Administrator'}</strong><p>Verified through Discord.</p></article><article className="window overview-card"><span>Shared draft</span><strong>{Object.keys(draft.changes).length} staged</strong><p>{draft.editorId?'An Administrator holds the edit lock.':'No active editor lock.'}</p></article><article className="window overview-card"><span>Feature switches</span><strong>{summary.enabledFeatures} enabled</strong><p>Live feature settings for this server.</p></article><article className="window overview-card"><span>Safeguards</span><strong>{summary.reviewed} reviewed</strong><p>{summary.restarts} settings require a worker restart after publishing.</p></article></section></main></DashboardShell>;}
  if(page==='members')return <DashboardShell csrf={csrf}><main className="content">{pageWindow('Members','Read a member’s current bot record without touching balances, inventory, roles, or cases.',<MemberLookup/>)}</main></DashboardShell>;
  if(page==='economy-status'){const economy=await readEconomyOverview(guildId);return <DashboardShell csrf={csrf}><main className="content">{pageWindow('Economy status','Read-only ledger-backed totals and economy policy state.',<div className="economy-grid"><article><span>Member accounts</span><strong>{economy.accounts}</strong><p>Wallet and bank records.</p></article><article><span>Wallet total</span><strong>{economy.wallet.toLocaleString()}</strong><p>Ottomans currently held in wallets.</p></article><article><span>Bank total</span><strong>{economy.bank.toLocaleString()}</strong><p>Ottomans currently held in banks.</p></article><article><span>Median balance</span><strong>{economy.medianBalance.toLocaleString()}</strong><p>Member wallet plus bank balance.</p></article><article><span>Policy state</span><strong>{economy.policy?.mode??'Not published'}</strong><p>{economy.policy?`Cycle ${economy.policy.cycleKey}${economy.policy.pausedAt?' · paused':''}`:'No daily policy yet.'}</p></article><article><span>Latest benchmark</span><strong>{economy.snapshot?.rawMedianWealth.toLocaleString()??'—'}</strong><p>{economy.snapshot?`${economy.snapshot.eligibleMemberCount} eligible members · ${economy.snapshot.snapshotDate.toISOString().slice(0,10)}`:'No daily snapshot yet.'}</p></article></div>)}</main></DashboardShell>;}
  if(page==='content-library'){const groups=await readContentGroups();return <DashboardShell csrf={csrf}><main className="content">{pageWindow('Content library','Browse and maintain approved source pools.',<ContentBrowser groups={groups} csrf={csrf} writesEnabled={settingsWritesEnabled()}/>)}</main></DashboardShell>;}
  if(page==='moderation-status'){const moderation=await readModerationOverview(guildId);return <DashboardShell csrf={csrf}><main className="content">{pageWindow('Moderation status','Read-only view of active jail sentences and current case activity.',<div className="moderation-grid"><article><h3>Active jail</h3>{moderation.activeJails.length?<ul>{moderation.activeJails.map(row=><li key={row.id}><strong>{row.userId}</strong><span>{row.indefinite?'Indefinite sentence':`Until ${row.endsAt.toISOString().replace('T',' ').replace('.000Z',' UTC')}`}</span></li>)}</ul>:<p className="description">No active jail sentences.</p>}</article><article><h3>Recent cases</h3>{moderation.recentCases.length?<ul>{moderation.recentCases.map(row=><li key={row.id}><strong>#{row.id} · {row.actionType}</strong><span>{row.status} · {row.subjectUserId??'No member'}</span></li>)}</ul>:<p className="description">No moderation cases recorded.</p>}</article></div>)}</main></DashboardShell>;}
  if(page==='recent-activity'){const activity=await readRecentAudit(guildId);return <DashboardShell csrf={csrf}><main className="content">{pageWindow('Recent activity','The latest audited server actions.',activity.length?<ActivityList activity={activity.map(({createdAt,...entry})=>({...entry,createdAt:createdAt.toISOString()}))}/>:<p className="description">No audited activity has been recorded yet.</p>)}</main></DashboardShell>;}
  const section=page==='features-status'?'features':settingsPages.has(page)?page:undefined;
  const [settings,draft]=await Promise.all([readSettings(guildId),draftService().view(guildId,actor)]);
  if(page==='draft')return <DashboardShell csrf={csrf}><main className="content"><SettingsControls settings={settings.map(({updatedAt,...control})=>control)} draft={draft as ConfigDraft} csrf={csrf} memberId={userId} isOwner={access.isGuildOwner} writesEnabled={settingsWritesEnabled()} showBrowser={false} showSections={false}/></main></DashboardShell>;
  if(page==='settings-browser')return <DashboardShell csrf={csrf}><main className="content"><SettingsControls settings={settings.map(({updatedAt,...control})=>control)} draft={draft as ConfigDraft} csrf={csrf} memberId={userId} isOwner={access.isGuildOwner} writesEnabled={settingsWritesEnabled()} showDraft={false} showSections={false}/></main></DashboardShell>;
  if(section)return <DashboardShell csrf={csrf}><main className="content"><SettingsControls settings={settings.map(({updatedAt,...control})=>control)} draft={draft as ConfigDraft} csrf={csrf} memberId={userId} isOwner={access.isGuildOwner} writesEnabled={settingsWritesEnabled()} section={section} showDraft={false} showBrowser={false}/></main></DashboardShell>;
  return <DashboardShell csrf={csrf}><main className="content">{pageWindow('Unavailable page','This dashboard section is not available in the current control set.',<a className="button" href="/admin">Return Home</a>)}</main></DashboardShell>;
}
