import type {AuditService,Clock} from '../../core/src/index.js';
import {DomainError} from '../../core/src/index.js';
import type {SecurityRepository} from './repository.js';
import type {AntiNukeDecision,AntiNukePolicy,AutoModDecision,AutoModSignal,HeatPolicy,HeatSnapshot,JoinGateDecision,JoinObservation,JoinPolicy,MessageObservation,PrivilegedObservation,RaidDecision,RaidPolicy,SecurityMode,SecurityStateRecord} from './types.js';

const HOUR=3600_000;const MINUTE=60_000;
const domainOf=(url:string)=>{try{return new URL(url).hostname.toLowerCase().replace(/^www\./,'');}catch{return'';}};
const urls=(text:string)=>[...text.matchAll(/https?:\/\/[^\s<>]+/gi)].map(m=>m[0]);
const emojiCount=(text:string)=>(text.match(/\p{Extended_Pictographic}/gu)??[]).length;
const combiningCount=(text:string)=>(text.match(/[\u0300-\u036f\u1ab0-\u1aff\u1dc0-\u1dff\u20d0-\u20ff\ufe20-\ufe2f]/g)??[]).length;
const shorteners=new Set(['bit.ly','tinyurl.com','t.co','goo.gl','rb.gy','cutt.ly','is.gd','buff.ly','ow.ly']);
const suspiciousUser=/\b(discord|steam|nitro|support|admin|moderator)\b.*\b(free|gift|verify|claim|official)\b/i;
const weights=(signals:AutoModSignal[])=>signals.reduce((n,s)=>n+s.weight,0);

export class SecurityService {
  constructor(private readonly repository:SecurityRepository,private readonly audit:AuditService,private readonly clock:Clock){}

  detectMessageSignals(o:MessageObservation):AutoModSignal[]{
    const s:AutoModSignal[]=[];const text=o.content;const trimmed=text.trim();
    if(!o.ordinaryExempt){
      if(o.recentMessageCount>=7)s.push({category:'rapid_flood',weight:12,severity:2,reason:'Rapid message flooding'});
      if(trimmed.length>=4&&o.recentSameCount>=2)s.push({category:'duplicate_text',weight:14,severity:2,reason:'Repeated duplicate text'});
      const letters=[...text].filter(c=>/[a-z]/i.test(c));const caps=letters.filter(c=>/[A-Z]/.test(c));if(letters.length>=20&&caps.length/letters.length>=0.85)s.push({category:'excessive_caps',weight:5,severity:1,reason:'Excessive caps'});
      if((text.match(/\n/g)??[]).length>=12)s.push({category:'excessive_newlines',weight:5,severity:1,reason:'Excessive newlines'});
      if(emojiCount(text)>=18)s.push({category:'excessive_emoji',weight:6,severity:1,reason:'Excessive emoji'});
      if(o.stickerCount>=4)s.push({category:'sticker_spam',weight:8,severity:2,reason:'Sticker spam'});
      if(o.recentAttachmentCount>=6)s.push({category:'attachment_flood',weight:10,severity:2,reason:'Attachment flooding'});
      if(o.mentionCount>=8)s.push({category:'mass_mentions',weight:24,severity:3,reason:'Mass mentions'});
    }
    if(/discord(?:\.gg|\.com\/invite)\/[A-Za-z0-9-]+/i.test(text))s.push({category:'invite_link',weight:5,severity:1,reason:'Invite link'});
    const found=urls(text),trusted=new Set((o.trustedDomains??[]).map(x=>x.toLowerCase()));
    for(const u of found){const d=domainOf(u);if(shorteners.has(d))s.push({category:'url_shortener',weight:12,severity:2,reason:`Suspicious URL shortener (${d})`});if(/(?:login|verify|gift|nitro|steam|wallet|airdrop)/i.test(u)&&!trusted.has(d))s.push({category:'suspected_phishing',weight:40,severity:4,reason:`Possible phishing/scam URL (${d||'unknown domain'})`});}
    const lower=text.toLowerCase();for(const phrase of o.bannedPhrases??[]){if(phrase.trim()&&lower.includes(phrase.trim().toLowerCase())){s.push({category:'banned_phrase',weight:28,severity:3,reason:'Configured banned phrase'});break;}}
    if(combiningCount(text)>=20)s.push({category:'unicode_obfuscation',weight:12,severity:2,reason:'Unicode/Zalgo obfuscation'});
    if(text.length>=1850)s.push({category:'very_long_message',weight:5,severity:1,reason:'Very long message'});
    return s;
  }

  async heat(guildId:string,userId:string,policy:HeatPolicy,category?:string):Promise<HeatSnapshot>{
    const now=this.clock.now();const since=new Date(now.getTime()-Math.max(policy.decayHours*6,24)*HOUR);const events=await this.repository.listBehaviorEvents(guildId,userId,since);let score=0,raw=0,similar=0;const categories:Record<string,number>={};
    for(const e of events){const age=Math.max(0,now.getTime()-e.createdAt.getTime());const factor=Math.pow(0.5,age/(policy.decayHours*HOUR));score+=e.weight*factor;raw+=e.weight;categories[e.category]=(categories[e.category]??0)+1;if(category&&e.category===category&&age<=24*HOUR)similar++;}
    return{score:Number(score.toFixed(2)),rawWeight:raw,similarRecent:similar,events:events.length,categories};
  }

  async evaluateMessage(o:MessageObservation,policy:HeatPolicy):Promise<AutoModDecision>{
    const signals=this.detectMessageSignals(o);if(!signals.length)return{action:'ALLOW',signals:[]};const primary=[...signals].sort((a,b)=>b.severity-a.severity||b.weight-a.weight)[0]!;const before=await this.heat(o.guildId,o.userId,policy,primary.category);const repeatMultiplier=1+Math.min(1,before.similarRecent*0.25);const eventWeight=Math.max(1,Math.round(weights(signals)*repeatMultiplier));const now=this.clock.now();await this.repository.createBehaviorEvent({guildId:o.guildId,userId:o.userId,category:primary.category,weight:eventWeight,expiresAt:new Date(now.getTime()+policy.decayHours*6*HOUR),now});const after=await this.heat(o.guildId,o.userId,policy,primary.category);
    let action:AutoModDecision['action']='LOG',timeoutSeconds:number|undefined;
    if(primary.severity>=4)action='QUARANTINE';else if(after.score>=policy.reviewThreshold)action='REVIEW';else if(after.score>=policy.longTimeoutThreshold){action='TIMEOUT';timeoutSeconds=policy.longTimeoutSeconds;}else if(after.score>=policy.shortTimeoutThreshold){action='TIMEOUT';timeoutSeconds=policy.shortTimeoutSeconds;}else if(after.score>=policy.warningThreshold)action='WARN';else if(primary.severity>=3)action='DELETE';
    await this.repository.createSecurityEvent({guildId:o.guildId,userId:o.userId,kind:'AUTOMOD_TRIGGER',severity:primary.severity,metadata:{action,categories:signals.map(x=>x.category),heat:after.score},now});
    return{action,reason:signals.map(x=>x.reason).join('; '),signals,heat:after,...(timeoutSeconds?{timeoutSeconds}:{})};
  }

  async adjustHeat(guildId:string,userId:string,actorUserId:string,weight:number,reason:string){if(!Number.isInteger(weight)||weight===0||Math.abs(weight)>200)throw new DomainError('INVALID_HEAT_ADJUSTMENT','Behavior heat adjustment must be a non-zero integer between -200 and 200.');if(!reason.trim())throw new DomainError('HEAT_REASON_REQUIRED','A reason is required.');const now=this.clock.now();const r=await this.repository.createBehaviorEvent({guildId,userId,category:'staff_adjustment',weight,now});await this.audit.record({guildId,actorUserId,source:'discord',action:'security.heat_adjust',targetType:'member',targetId:userId,after:{weight},reason:reason.trim(),requestId:`heat:${guildId}:${userId}:${now.getTime()}`,createdAt:now});return r;}

  async joinGate(o:JoinObservation,policy:JoinPolicy):Promise<JoinGateDecision>{
    const now=this.clock.now();await this.repository.createSecurityEvent({guildId:o.guildId,userId:o.userId,kind:'MEMBER_JOIN',severity:1,metadata:{createdAt:o.createdAt.toISOString(),isBot:o.isBot},now});const recent=(await this.repository.listSecurityEvents(o.guildId,new Date(now.getTime()-MINUTE),'MEMBER_JOIN')).length;if(!policy.enabled)return{action:'ALLOW',riskScore:0,reasons:[],recentJoinCount:recent};
    const reasons:string[]=[];let risk=0;const ageHours=Math.max(0,(now.getTime()-o.createdAt.getTime())/HOUR);if(ageHours<policy.minimumAccountAgeHours){risk+=25;reasons.push(`Account age ${Math.floor(ageHours)}h is below ${policy.minimumAccountAgeHours}h screening threshold`);}if(recent>=policy.joinVelocityPerMinute){risk+=35;reasons.push(`Join velocity ${recent}/min reached raid threshold`);}if(suspiciousUser.test(o.username)){risk+=20;reasons.push('Username/display pattern warrants review');}if(o.priorCaseCount>=2){risk+=15;reasons.push('Prior server moderation history');}if(o.currentMode==='RESTRICTED'){risk+=45;reasons.push('Server is in Restricted security mode');}if(o.currentMode==='LOCKDOWN'){risk+=60;reasons.push('Server is in Lockdown security mode');}
    if(o.isBot&&!new Set(policy.trustedBotIds??[]).has(o.userId)){risk=100;reasons.push('Unauthorized bot addition');return{action:'KICK',riskScore:risk,reasons,recentJoinCount:recent};}
    const action:JoinGateDecision['action']=risk>=70?'RESTRICT':risk>=40&&policy.verificationEnabled?'VERIFY':risk>=25?'FLAG':'ALLOW';if(action==='VERIFY'||action==='RESTRICT')await this.repository.upsertVerification({guildId:o.guildId,userId:o.userId,status:'REQUIRED',reason:reasons.join('; '),now});
    if(action!=='ALLOW')await this.repository.createSecurityEvent({guildId:o.guildId,userId:o.userId,kind:'SUSPICIOUS_JOIN',severity:action==='RESTRICT'?3:2,metadata:{risk,reasons,action},now});
    return{action,riskScore:risk,reasons,recentJoinCount:recent};
  }

  async verification(guildId:string,userId:string){return this.repository.getVerification(guildId,userId);}async verify(guildId:string,userId:string){const now=this.clock.now();const r=await this.repository.upsertVerification({guildId,userId,status:'VERIFIED',now});await this.audit.record({guildId,actorUserId:userId,source:'discord',action:'security.verification_completed',targetType:'member',targetId:userId,after:{status:'VERIFIED'},requestId:`verify:${guildId}:${userId}:${now.getTime()}`,createdAt:now});return r;}
  async requireVerification(guildId:string,userId:string,reason:string){return this.repository.upsertVerification({guildId,userId,status:'REQUIRED',reason,now:this.clock.now()});}

  async state(guildId:string):Promise<SecurityStateRecord>{return await this.repository.getSecurityState(guildId)??{guildId,mode:'NORMAL',source:'default',panicActive:false,updatedAt:this.clock.now()};}
  async setMode(guildId:string,mode:SecurityMode,reason:string,source:string,policyMinutes:number,updatedBy?:string){const now=this.clock.now();const current=await this.state(guildId);if(current.panicActive&&source!=='panic')return current;const expiresAt=mode==='NORMAL'?undefined:new Date(now.getTime()+policyMinutes*MINUTE);const next=await this.repository.upsertSecurityState({guildId,mode,reason,source,...(updatedBy?{updatedBy}:{}),panicActive:false,...(expiresAt?{expiresAt}:{}),now});if(expiresAt)await this.repository.upsertSecurityExpiryJob({guildId,dueAt:expiresAt,mode});else await this.repository.cancelSecurityExpiryJob(guildId);if(current.mode!==mode)await this.audit.record({guildId,...(updatedBy?{actorUserId:updatedBy}:{}),source:'discord',action:'security.mode_changed',targetType:'server',targetId:guildId,before:{mode:current.mode},after:{mode},reason,requestId:`security-mode:${guildId}:${now.getTime()}`,createdAt:now});return next;}
  async evaluateRaid(guildId:string,policy:RaidPolicy):Promise<RaidDecision>{const now=this.clock.now();const current=await this.state(guildId);if(!policy.enabled||current.panicActive)return{mode:current.mode,changed:false,reason:current.reason??'No automatic raid change.',recentJoins:0,recentSeriousEvents:0};const since=new Date(now.getTime()-MINUTE);const joins=(await this.repository.listSecurityEvents(guildId,since,'MEMBER_JOIN')).length;const serious=(await this.repository.listSecurityEvents(guildId,since,'AUTOMOD_TRIGGER')).filter(x=>x.severity>=3).length;let mode:SecurityMode='NORMAL';if(joins>=policy.joinVelocityPerMinute*2||serious>=6)mode='LOCKDOWN';else if(joins>=policy.joinVelocityPerMinute||serious>=3)mode='RESTRICTED';else if(joins>=Math.max(2,Math.ceil(policy.joinVelocityPerMinute*0.6))||serious>=1)mode='ALERT';const changed=mode!==current.mode;if(changed)await this.setMode(guildId,mode,`Automatic raid evaluation: ${joins} joins/min, ${serious} serious triggers/min.`,'anti_raid',policy.autoDeescalateMinutes);return{mode,changed,reason:`${joins} joins/min; ${serious} serious AutoMod trigger(s)/min.`,recentJoins:joins,recentSeriousEvents:serious};}
  async expireSecurityState(guildId:string){const current=await this.state(guildId);if(current.panicActive)return current;if(!current.expiresAt||current.expiresAt>this.clock.now())return current;return this.setMode(guildId,'NORMAL','Automatic security-state expiration.','scheduler',0);}

  async observePrivileged(o:PrivilegedObservation,policy:AntiNukePolicy):Promise<AntiNukeDecision>{const now=this.clock.now();await this.repository.createSecurityEvent({...o,kind:`NUKE_${o.kind}`,now});const trusted=new Set(policy.trustedUserIds??[]).has(o.actorUserId??'');if(!policy.enabled||!o.actorUserId)return{action:'LOG',count:1,score:o.severity,reason:'Anti-nuke monitoring/logging only.',trusted};const recent=await this.repository.listSecurityEvents(o.guildId,new Date(now.getTime()-MINUTE),undefined,o.actorUserId);const destructive=recent.filter(x=>x.kind.startsWith('NUKE_'));const score=destructive.reduce((n,x)=>n+x.severity,0);const threshold=policy.eventsPerMinute+(trusted?2:0),lockdown=policy.lockdownEventsPerMinute+(trusted?3:0);let action:AntiNukeDecision['action']='LOG';if(destructive.length>=lockdown||score>=lockdown*3)action='LOCKDOWN';else if(destructive.length>=threshold||score>=threshold*2)action='CONTAIN';else if(destructive.length>=Math.max(2,threshold-1)||score>=threshold)action='ALERT';return{action,count:destructive.length,score,reason:`${destructive.length} destructive audit event(s), weighted score ${score}, in 60 seconds.`,trusted};}

  async activatePanic(guildId:string,actorUserId:string,reason:string,snapshot:Record<string,unknown>){if(!reason.trim())throw new DomainError('PANIC_REASON_REQUIRED','A reason is required to activate Panic Mode.');const current=await this.state(guildId);if(current.panicActive)throw new DomainError('PANIC_ALREADY_ACTIVE','Panic Mode is already active.');const now=this.clock.now();const next=await this.repository.upsertSecurityState({guildId,mode:'LOCKDOWN',reason:reason.trim(),source:'panic',updatedBy:actorUserId,panicActive:true,snapshot:{...snapshot,previousMode:current.mode,previousReason:current.reason??null},now});await this.repository.cancelSecurityExpiryJob(guildId);await this.repository.createSecurityEvent({guildId,actorUserId,kind:'PANIC_ACTIVATED',severity:4,metadata:{reason:reason.trim()},now});await this.audit.record({guildId,actorUserId,source:'discord',action:'security.panic_activate',targetType:'server',targetId:guildId,before:{mode:current.mode,panicActive:current.panicActive},after:{mode:'LOCKDOWN',panicActive:true},reason:reason.trim(),requestId:`panic-on:${guildId}:${now.getTime()}`,createdAt:now});return next;}
  async deactivatePanic(guildId:string,actorUserId:string,reason='Panic Mode deactivated.'){const current=await this.state(guildId);if(!current.panicActive)throw new DomainError('PANIC_NOT_ACTIVE','Panic Mode is not active.');const previous=(current.snapshot?.previousMode as SecurityMode|undefined)??'NORMAL';const now=this.clock.now();const next=await this.repository.upsertSecurityState({guildId,mode:previous,reason,source:'panic_restore',updatedBy:actorUserId,panicActive:false,now});await this.repository.createSecurityEvent({guildId,actorUserId,kind:'PANIC_DEACTIVATED',severity:2,metadata:{restoredMode:previous},now});await this.audit.record({guildId,actorUserId,source:'discord',action:'security.panic_deactivate',targetType:'server',targetId:guildId,before:{mode:current.mode,panicActive:true},after:{mode:previous,panicActive:false},reason,requestId:`panic-off:${guildId}:${now.getTime()}`,createdAt:now});return{state:next,snapshot:current.snapshot??{}};}
}
