import {Prisma,type PrismaClient} from '@prisma/client';
import {AuditService,DomainError,SessionEngine} from '../../core/src/index.js';
import {PrismaAtomicOperations,requestFingerprint} from '../../database/src/atomic-operations.js';
import {PrismaTransactionSessions} from '../../database/src/transaction-sessions.js';
import {PrismaJobDeliveryRepository} from '../../database/src/job-delivery.js';
import {INTRO_DEFAULTS,promptPages,saveAnswers,validateAnswers,validateIntroForm,type IntroConfig,type IntroContext,type IntroDraft,type IntroForm,type IntroPrompt} from './domain.js';
const json=(x:unknown)=>JSON.parse(JSON.stringify(x)) as Prisma.InputJsonObject;
export interface IntroJob {userId:string;sessionId:string;channelId:string;revision:number;draft:IntroDraft;priorMessageId:string|null;priorChannelId:string|null;deliveryState:'PENDING'|'SENDING'|'SENT';deliveryMessageId?:string;}
export interface PublishedIntroSettings {title:string;prompts:IntroPrompt[];headerText:string;footerText:string;showAvatar:boolean;showDisplayName:boolean;showJoinDate:boolean;allowAdminIntroConfig:boolean;}
export class PrismaIntroductionsRepository {
 private atomic:PrismaAtomicOperations;
 constructor(private db:PrismaClient,private clock=()=>new Date()){this.atomic=new PrismaAtomicOperations(db);}
 /** Input must come from the already-published shared ConfigService; this is a materialized runtime form. */
 async configure(guildId:string,channelId:string,settings:PublishedIntroSettings|null){
  if(!/^\d{17,20}$/.test(channelId))throw new DomainError('INTRO_CHANNEL','The introductions channel is not configured.');
  const fingerprint=requestFingerprint({channelId,settings,questionRevision:2}),previous=await this.db.introductionFormConfig.findUnique({where:{guildId}});if(previous?.sourceFingerprint===fingerprint)return;
  const key='intro:configuration:'+fingerprint+':'+(previous?.version??0);
  await this.atomic.run(guildId,key,requestFingerprint({channelId,settings,questionRevision:2}),async tx=>{
   const config=await tx.introductionFormConfig.upsert({where:{guildId},update:{},create:{guildId,introductionChannelId:channelId}});
   if(config.sourceFingerprint===fingerprint)return{applied:true};
   let form=await tx.introductionForm.findFirst({where:{guildId,enabled:true},include:{prompts:true},orderBy:[{version:'desc'},{id:'asc'}]});
   if(!form){form=await tx.introductionForm.create({data:{guildId,title:'Your introduction',prompts:{create:INTRO_DEFAULTS.map((p,n)=>({...p,id:guildId+'_'+p.id,sortOrder:n,placeholder:null,minLength:null,showOnCard:true}))}},include:{prompts:true}});}
   // Stable IDs and stored answers survive; retired answers are never reinterpreted.
   const originalPrompts=form.prompts;
   if(!settings&&originalPrompts.filter(p=>p.enabled&&!p.deletedAt).length===5&&['name','age','from','about','why'].every(id=>originalPrompts.some(p=>p.id===guildId+'_'+id&&p.enabled&&!p.deletedAt))){
    const currentIds=new Set(INTRO_DEFAULTS.map(p=>guildId+'_'+p.id));
    for(const p of form.prompts)if(!currentIds.has(p.id))await tx.introductionPrompt.update({where:{id:p.id},data:{enabled:false,deletedAt:this.clock()}});
    for(const [n,p] of INTRO_DEFAULTS.entries()){const id=guildId+'_'+p.id,fields={...p,id,sortOrder:n,placeholder:null,minLength:null,showOnCard:true,enabled:true,deletedAt:null};await tx.introductionPrompt.upsert({where:{id},create:{...fields,formId:form.id},update:fields});}
    form=await tx.introductionForm.update({where:{id:form.id},data:{version:{increment:1}},include:{prompts:true}});
   }
   const nextConfig={...config,introductionChannelId:channelId,...(settings?{headerText:settings.headerText,footerText:settings.footerText,showAvatar:settings.showAvatar,showDisplayName:settings.showDisplayName,showJoinDate:settings.showJoinDate,allowAdminIntroConfig:settings.allowAdminIntroConfig}:{})};
   const nextForm:IntroForm=settings?{id:form.id,version:form.version,title:settings.title,prompts:settings.prompts}:form;
   validateIntroForm(nextForm,nextConfig);
   if(settings){const supplied=new Set(settings.prompts.map(p=>p.id));for(const p of form.prompts)if(!supplied.has(p.id))await tx.introductionPrompt.update({where:{id:p.id},data:{deletedAt:this.clock(),enabled:false}});
    for(const p of settings.prompts){const existing=await tx.introductionPrompt.findUnique({where:{id:p.id}});if(existing&&existing.formId!==form.id)throw new DomainError('INTRO_PROMPT_OWNER','Prompt IDs must belong to this server’s form.');const {id,deletedAt}=p,fields={sortOrder:p.sortOrder,label:p.label,cardLabel:p.cardLabel,placeholder:p.placeholder,required:p.required,minLength:p.minLength,maxLength:p.maxLength,inputStyle:p.inputStyle,enabled:p.enabled,showOnCard:p.showOnCard,deletedAt:deletedAt?new Date(deletedAt):null};await tx.introductionPrompt.upsert({where:{id},create:{id,formId:form.id,...fields},update:fields});}
    await tx.introductionForm.update({where:{id:form.id},data:{title:settings.title,version:{increment:1}}});
   }
   await tx.introductionFormConfig.update({where:{guildId},data:{sourceFingerprint:fingerprint,introductionChannelId:channelId,headerText:nextConfig.headerText,footerText:nextConfig.footerText,showAvatar:nextConfig.showAvatar,showDisplayName:nextConfig.showDisplayName,showJoinDate:nextConfig.showJoinDate,allowAdminIntroConfig:nextConfig.allowAdminIntroConfig,...(config.introductionChannelId!==channelId?{panelMessageId:null}:{}),version:{increment:1}}});
   await this.audit(tx,guildId,undefined,'intro.configuration.applied',key,{formId:form.id,channelId});return{applied:true};
  });
 }
 async configuration(guildId:string){const config=await this.db.introductionFormConfig.findUnique({where:{guildId}}),form=await this.db.introductionForm.findFirst({where:{guildId,enabled:true},include:{prompts:true},orderBy:[{version:'desc'},{id:'asc'}]});if(!config?.introductionChannelId||!form)throw new DomainError('INTRO_CONFIG','Introductions are not configured yet.');return{config,form};}
 async submission(guildId:string,userId:string){return this.db.introductionSubmission.findUnique({where:{guildId_userId:{guildId,userId}}});}
 async start(c:IntroContext){return this.atomic.run(c.guildId,'intro:start:'+c.requestKey,requestFingerprint(c),async tx=>{
  const config=await tx.introductionFormConfig.findUniqueOrThrow({where:{guildId:c.guildId}});if(config.introductionChannelId!==c.channelId)throw new DomainError('INTRO_CHANNEL','Use the configured introductions channel.');
  const prior=await tx.introductionSubmission.findUnique({where:{guildId_userId:{guildId:c.guildId,userId:c.userId}}});
  const active=await tx.gameSession.findFirst({where:{guildId:c.guildId,type:'introduction',ownerUserId:c.userId,state:'DRAFT',expiresAt:{gt:this.clock()}},orderBy:{updatedAt:'desc'}});if(active&&(active.data as unknown as IntroDraft).config.version===config.version&&(active.data as unknown as IntroDraft).baseRevision===(prior?.publishedRevision??0))return{id:active.id};
  if(active)await new SessionEngine(new PrismaTransactionSessions(tx)).transition(active.id,['DRAFT'],'CANCELLED');
  const form=await tx.introductionForm.findFirst({where:{guildId:c.guildId,enabled:true},include:{prompts:true},orderBy:[{version:'desc'},{id:'asc'}]});if(!form)throw new DomainError('INTRO_FORM','The introduction form is unavailable.');validateIntroForm(form,config);
  const data:IntroDraft={form,config,answers:active&&(active.data as unknown as IntroDraft).baseRevision===(prior?.publishedRevision??0)?(active.data as unknown as IntroDraft).answers:(prior?.answers??{}) as Record<string,string>,baseRevision:prior?.publishedRevision??0,page:0,previewedVersion:null};
  const created=await tx.gameSession.create({data:{guildId:c.guildId,type:'introduction',channelId:c.channelId,ownerUserId:c.userId,state:'DRAFT',data:json(data),expiresAt:new Date(this.clock().getTime()+86400000)}});return{id:created.id};
 });}
 async view(c:IntroContext,id:string){return this.checked(this.db,c,id);}
 private async checked(tx:Prisma.TransactionClient,c:IntroContext,id:string){const row=await tx.gameSession.findUnique({where:{id}});if(!row||row.type!=='introduction'||row.guildId!==c.guildId||row.ownerUserId!==c.userId||row.channelId!==c.channelId)throw new DomainError('INTRO_OWNER','Open your own introduction in the introductions channel.');if(row.state!=='DRAFT'||!row.expiresAt||row.expiresAt<=this.clock())throw new DomainError('INTRO_EXPIRED','This draft has expired or was submitted. Open /introduce again.');return{...row,data:row.data as unknown as IntroDraft};}
 async save(c:IntroContext,id:string,version:number,page:number,values:Record<string,string>){return this.atomic.run(c.guildId,'intro:save:'+c.requestKey,requestFingerprint({c,id,version,page,values}),async tx=>{const row=await this.checked(tx,c,id);if(row.version!==version)throw new DomainError('INTRO_STALE','This form changed. Open the current page again.');const data=saveAnswers(row.data,page,values);await new SessionEngine(new PrismaTransactionSessions(tx)).transition<IntroDraft>(id,['DRAFT'],'DRAFT',s=>({...s,data}));return{id};});}
 async preview(c:IntroContext,id:string){return this.atomic.run(c.guildId,'intro:preview:'+c.requestKey,requestFingerprint({c,id}),async tx=>{const row=await this.checked(tx,c,id);validateAnswers(row.data);await new SessionEngine(new PrismaTransactionSessions(tx)).transition<IntroDraft>(id,['DRAFT'],'DRAFT',s=>({...s,data:{...row.data,previewedVersion:s.version}}));return{id};});}
 async enqueue(c:IntroContext,id:string,version:number){return this.atomic.run(c.guildId,'intro:publish:'+c.requestKey,requestFingerprint({c,id,version}),async tx=>{
  const row=await this.checked(tx,c,id);if(row.version!==version||row.data.previewedVersion!==version)throw new DomainError('INTRO_PREVIEW','Preview your current answers before choosing Publish.');validateAnswers(row.data);
  const config=await tx.introductionFormConfig.findUniqueOrThrow({where:{guildId:c.guildId}}),form=await tx.introductionForm.findUniqueOrThrow({where:{id:row.data.form.id}});if(config.version!==row.data.config.version||form.version!==row.data.form.version)throw new DomainError('INTRO_FORM_CHANGED','The introduction form changed. Start a fresh draft before publishing.');
  const prior=await tx.introductionSubmission.findUnique({where:{guildId_userId:{guildId:c.guildId,userId:c.userId}}});if((prior?.publishedRevision??0)!==row.data.baseRevision)throw new DomainError('INTRO_REVISION','Your introduction changed. Reopen it before editing.');
  if(prior?.outputChannelId&&prior.outputChannelId!==c.channelId)throw new DomainError('INTRO_MOVED_CHANNEL','Your existing introduction is in the previous channel. An admin must resolve that post before it can move.');
  if(await tx.scheduledJob.findFirst({where:{guildId:c.guildId,jobType:'intro.publish',payload:{path:['userId'],equals:c.userId},status:{not:'COMPLETED'}}}))throw new DomainError('INTRO_PENDING','Your previous publication is still being confirmed.');
  const payload:IntroJob={userId:c.userId,sessionId:id,channelId:c.channelId,revision:row.data.baseRevision+1,draft:row.data,priorMessageId:prior?.outputMessageId??null,priorChannelId:prior?.outputChannelId??(prior?.outputMessageId?c.channelId:null),deliveryState:'PENDING'};
  const job=await tx.scheduledJob.create({data:{guildId:c.guildId,jobType:'intro.publish',executionKey:'intro:publish:'+id,dueAt:this.clock(),payload:json(payload)}});await new SessionEngine(new PrismaTransactionSessions(tx)).transition(id,['DRAFT'],'LOCKED');return{jobId:job.id};
 });}
 async job(id:string){const row=await this.db.scheduledJob.findUniqueOrThrow({where:{id}});if(row.jobType!=='intro.publish')throw new DomainError('INTRO_JOB','Invalid introduction publication.');return{...row,payload:row.payload as unknown as IntroJob};}
 delivery(id:string){return new PrismaJobDeliveryRepository(this.db,id);}
 async finalize(id:string){const row=await this.job(id),p=row.payload;if(p.deliveryState!=='SENT'||!p.deliveryMessageId)throw new DomainError('INTRO_UNCONFIRMED','The introduction has not been confirmed by Discord.');return this.atomic.run(row.guildId,'intro:finalize:'+id,requestFingerprint({id,messageId:p.deliveryMessageId}),async tx=>{
  const fresh=await tx.scheduledJob.findUniqueOrThrow({where:{id}}),saved=fresh.payload as unknown as IntroJob;if(saved.deliveryState!=='SENT'||saved.deliveryMessageId!==p.deliveryMessageId)throw new DomainError('INTRO_UNCONFIRMED','The introduction has not been confirmed by Discord.');
  const prior=await tx.introductionSubmission.findUnique({where:{guildId_userId:{guildId:row.guildId,userId:p.userId}}});if((prior?.publishedRevision??0)!==p.revision-1)throw new DomainError('INTRO_REVISION','A different introduction revision is already published.');
  const fields={formVersion:p.draft.form.version,answers:json(p.draft.answers),outputChannelId:p.channelId,outputMessageId:p.deliveryMessageId!,publishedRevision:p.revision};await tx.introductionSubmission.upsert({where:{guildId_userId:{guildId:row.guildId,userId:p.userId}},create:{guildId:row.guildId,userId:p.userId,...fields},update:fields});
  await new SessionEngine(new PrismaTransactionSessions(tx)).transition(p.sessionId,['LOCKED'],'CLOSED');await tx.scheduledJob.update({where:{id},data:{status:'COMPLETED',completedAt:this.clock()}});await this.audit(tx,row.guildId,p.userId,'intro.published',id,{revision:p.revision,messageId:p.deliveryMessageId});return{messageId:p.deliveryMessageId!,channelId:p.channelId};
 });}
 async panelJob(guildId:string,missingMessageId:string|null){return this.atomic.run(guildId,'intro:panel:'+requestFingerprint({missingMessageId,config:(await this.configuration(guildId)).config}),requestFingerprint({missingMessageId}),async tx=>{const config=await tx.introductionFormConfig.findUniqueOrThrow({where:{guildId}});const pending=await tx.scheduledJob.findFirst({where:{guildId,jobType:'intro.panel',status:{not:'COMPLETED'},payload:{path:['channelId'],equals:config.introductionChannelId!}}});if(pending)return{jobId:pending.id};const job=await tx.scheduledJob.create({data:{guildId,jobType:'intro.panel',executionKey:'intro:panel:'+guildId+':'+config.version+':'+(missingMessageId??'initial'),dueAt:this.clock(),payload:{channelId:config.introductionChannelId!,deliveryState:'PENDING'}}});return{jobId:job.id};});}
 async panelDeliveryJob(id:string){const row=await this.db.scheduledJob.findUniqueOrThrow({where:{id}});if(row.jobType!=='intro.panel')throw new DomainError('INTRO_JOB','Invalid introduction panel.');return{...row,payload:row.payload as {channelId:string;deliveryState:string;deliveryMessageId?:string}};}
 async finalizePanel(id:string){const row=await this.panelDeliveryJob(id),p=row.payload;if(p.deliveryState!=='SENT'||!p.deliveryMessageId)throw new DomainError('INTRO_UNCONFIRMED','The panel has not been confirmed.');await this.atomic.run(row.guildId,'intro:panel-finalize:'+id,requestFingerprint({id,messageId:p.deliveryMessageId}),async tx=>{await tx.introductionFormConfig.updateMany({where:{guildId:row.guildId,introductionChannelId:p.channelId},data:{panelMessageId:p.deliveryMessageId!}});await tx.scheduledJob.update({where:{id},data:{status:'COMPLETED',completedAt:this.clock()}});return{messageId:p.deliveryMessageId!};});}
 async configuredServers(){return this.db.introductionFormConfig.findMany({where:{introductionChannelId:{not:null}}});}
 async expireDrafts(){await this.db.gameSession.updateMany({where:{type:'introduction',state:'DRAFT',expiresAt:{lte:this.clock()}},data:{state:'CANCELLED',version:{increment:1}}});}
 private async audit(tx:Prisma.TransactionClient,guildId:string,userId:string|undefined,action:string,requestId:string,after:unknown){await new AuditService({write:async e=>{await tx.auditEvent.create({data:{guildId,actorUserId:userId??null,source:e.source,action,requestId,after:json(after)}});}}).record({guildId,...(userId?{actorUserId:userId}:{}),source:'discord',action,requestId,after,createdAt:this.clock()});}
}
