import {DomainError,VotingEngine} from '../../core/src/index.js';
import type {MusicActor,MusicEffect,MusicEntry,MusicMetadata,MusicPolicy,MusicState,MusicTransition,ObservedMusicStatus} from './interfaces.js';
const fail=(code:string,message:string):never=>{throw new DomainError(code,message);};
const bounded=(value:number,min:number,max:number,code='MUSIC_VALUE')=>{if(!Number.isSafeInteger(value)||value<min||value>max)fail(code,`Choose a whole number from ${min} to ${max}.`);return value;};
export function musicPolicy(value:MusicPolicy):MusicPolicy {bounded(value.queueMaxTracks,10,1000,'MUSIC_CONFIG');bounded(value.defaultVolume,1,100,'MUSIC_CONFIG');if(!['off','track','queue'].includes(value.defaultLoop)||typeof value.defaultAutoplay!=='boolean')fail('MUSIC_CONFIG','The music defaults are invalid.');return{...value};}
export function validateMusicMetadata(track:MusicMetadata):MusicMetadata {
 for(const [field,max]of [['provider',80],['reference',2048],['title',300],['artist',300]] as const){if(typeof track[field]!=='string'||!track[field].trim()||track[field].length>max||/[\u0000-\u001f]/.test(track[field]))fail('MUSIC_METADATA','A resolved track has invalid metadata.');}
 if(track.album!==null&&(typeof track.album!=='string'||track.album.length>300)||typeof track.seekable!=='boolean')fail('MUSIC_METADATA','A resolved track has invalid album or seek metadata.');
 if(track.durationMs!==null)bounded(track.durationMs,1,604800000,'MUSIC_DURATION');
 if(track.isrc!==undefined&&track.isrc!==null&&!/^[A-Z]{2}[A-Z0-9]{3}\d{7}$/.test(track.isrc))fail('MUSIC_METADATA','Invalid recording identifier.');
 if(track.explicit!==undefined&&track.explicit!==null&&typeof track.explicit!=='boolean')fail('MUSIC_METADATA','Invalid recording version metadata.');
 if(track.artworkUrl!==null){try{const url=new URL(track.artworkUrl);if(url.protocol!=='https:'||url.username||url.password||track.artworkUrl.length>2048)throw Error();}catch{fail('MUSIC_ARTWORK','Artwork must be a validated HTTPS provider URL.');}}
 // Explicit projection prevents a provider from smuggling a stream URL/token into persisted public metadata.
 return{provider:track.provider,reference:track.reference,title:track.title,artist:track.artist,album:track.album,durationMs:track.durationMs,artworkUrl:track.artworkUrl,seekable:track.seekable,...(track.isrc===undefined?{}:{isrc:track.isrc}),...(track.explicit===undefined?{}:{explicit:track.explicit})};
}
export function musicEntry(id:string,requesterUserId:string|null,track:MusicMetadata,requestedTrack?:MusicMetadata,resolutionMethod?:MusicEntry['resolutionMethod']):MusicEntry {if(!id||id.length>100||requesterUserId!==null&&(!requesterUserId||requesterUserId.length>100))fail('MUSIC_ENTRY','A queue entry needs a stable ID and requester.');if(resolutionMethod!==undefined&&!['direct','isrc','metadata','selected'].includes(resolutionMethod))fail('MUSIC_METADATA','Invalid recording resolution method.');return{id,requesterUserId,track:validateMusicMetadata(track),...(requestedTrack?{requestedTrack:validateMusicMetadata(requestedTrack)}:{}),...(resolutionMethod?{resolutionMethod}:{})};}
export function trackIdentity(track:MusicMetadata){return JSON.stringify([track.provider,track.reference]);}
export function assertMusicLocation(actor:MusicActor){if(!actor.eligible||!actor.voiceChannelId||actor.voiceChannelId!==actor.textChannelId)fail('MUSIC_LOCATION','Join a voice channel and use its embedded text chat.');}
export function assertMusicActor(state:MusicState,actor:MusicActor,allowOtherVoice=false){assertMusicLocation(actor);if(actor.guildId!==state.guildId)fail('MUSIC_SERVER','This player belongs to another server.');if(actor.voiceChannelId!==state.voiceChannelId&&!(allowOtherVoice&&actor.isDj))fail('MUSIC_CHANNEL',`Music is active in voice channel ${state.voiceChannelId}. A DJ can explicitly move or release it.`);}
function dj(actor:MusicActor){if(!actor.isDj)fail('MUSIC_DJ','This control requires DJ authority.');}
function owned(actor:MusicActor,entries:readonly MusicEntry[]){if(!actor.isDj&&entries.some(e=>e.requesterUserId!==actor.userId))fail('MUSIC_QUEUE_OWNER','You may change only your own queue entries.');}
/** Owner-approved 2026-09-25: Previous, Replay and Seek require the current requester or a DJ. */
function playbackOwner(actor:MusicActor,entry:MusicEntry){if(!actor.isDj&&entry.requesterUserId!==actor.userId)fail('MUSIC_TRACK_OWNER','Changing this track’s playback position requires its requester or a DJ.');}
function next(state:MusicState):MusicState {return{...state,revision:state.revision+1,queue:state.queue.map(e=>({...e,track:{...e.track}})),history:state.history.map(e=>({...e,track:{...e.track}})),current:state.current?{...state.current,track:{...state.current.track}}:null,skipVotes:{...state.skipVotes,voterIds:[...state.skipVotes.voterIds]}};}
function freshPlayback(state:MusicState,entry:MusicEntry|null,positionMs=0){state.generation++;state.current=entry;state.positionMs=positionMs;state.observedAt=null;state.desiredStatus=entry?'PLAYING':'IDLE';state.skipVotes={generation:state.generation,voterIds:[]};state.lastError=null;}
function current(state:MusicState){return state.current??fail('MUSIC_EMPTY','The jukebox is empty. Use /play to add a track.');}
function archive(state:MusicState,entry:MusicEntry){state.history.push(entry);state.history=state.history.slice(-100);}
export function createMusicState(guildId:string,actor:MusicActor,policyInput:MusicPolicy):MusicTransition {assertMusicLocation(actor);if(actor.guildId!==guildId)fail('MUSIC_SERVER','Use the player in its server.');const policy=musicPolicy(policyInput);return{state:{guildId,voiceChannelId:actor.voiceChannelId!,textChannelId:actor.textChannelId,revision:0,generation:0,current:null,queue:[],history:[],desiredStatus:'IDLE',observedStatus:'DISCONNECTED',observedGeneration:0,positionMs:0,observedAt:null,volume:policy.defaultVolume,loop:policy.defaultLoop,autoplay:policy.defaultAutoplay,queueMaxTracks:policy.queueMaxTracks,skipVotes:{generation:0,voterIds:[]},lastError:null},effects:[{kind:'connect',voiceChannelId:actor.voiceChannelId!},{kind:'volume',percent:policy.defaultVolume}]};}
export function duplicateTracks(state:MusicState,entries:readonly MusicEntry[]){const existing=new Set([...(state.current?[state.current]:[]),...state.queue].map(e=>trackIdentity(e.track))),duplicates:MusicEntry[]=[];for(const entry of entries){const key=trackIdentity(entry.track);if(existing.has(key))duplicates.push(entry);existing.add(key);}return duplicates;}
export function enqueueMusic(state:MusicState,actor:MusicActor,entriesInput:readonly MusicEntry[],policyInput:MusicPolicy,confirmDuplicates=false):MusicTransition {
 assertMusicActor(state,actor);const policy=musicPolicy(policyInput);if(!entriesInput.length)fail('MUSIC_UNAVAILABLE','No available track references were resolved.');if(entriesInput.length>policy.queueMaxTracks)fail('MUSIC_QUEUE_LIMIT','This selection exceeds the queue limit.');
 const entries=entriesInput.map(e=>musicEntry(e.id,e.requesterUserId,e.track,e.requestedTrack,e.resolutionMethod));if(entries.some(e=>e.requesterUserId!==actor.userId))fail('MUSIC_REQUESTER','New queue entries must identify the requesting member.');
 const ids=[...(state.current?[state.current.id]:[]),...state.queue.map(e=>e.id),...entries.map(e=>e.id)];if(new Set(ids).size!==ids.length)fail('MUSIC_ENTRY_ID','Queue entries require unique IDs, including confirmed duplicate tracks.');
 const historicalIds=new Set(state.history.map(entry=>entry.id));if(entries.some(entry=>historicalIds.has(entry.id)))fail('MUSIC_ENTRY_ID','New queue entries cannot reuse a historical entry ID.');
 if(state.queue.length+entries.length+(state.current?1:0)>policy.queueMaxTracks)fail('MUSIC_QUEUE_LIMIT','The player has reached its track limit.');if(!confirmDuplicates&&duplicateTracks(state,entries).length)fail('MUSIC_DUPLICATE','This selection contains a duplicate. Confirm before adding it.');
 const result=next(state),effects:MusicEffect[]=[];result.queueMaxTracks=policy.queueMaxTracks;result.queue.push(...entries);if(!result.current){freshPlayback(result,result.queue.shift()!);effects.push({kind:'connect',voiceChannelId:result.voiceChannelId},{kind:'play',entry:result.current!,positionMs:0},{kind:'volume',percent:result.volume});}return{state:result,effects};
}
function advance(state:MusicState,reason:'ended'|'skip'|'failed'):MusicTransition {
 const old=current(state),result=next(state),effects:MusicEffect[]=[];
 if(reason==='ended'&&result.loop==='track'){freshPlayback(result,old);effects.push({kind:'play',entry:old,positionMs:0});return{state:result,effects};}
 archive(result,old);if(reason==='ended'&&result.loop==='queue')result.queue.push(old);
 freshPlayback(result,result.queue.shift()??null);if(result.current)effects.push({kind:'play',entry:result.current,positionMs:0});else{effects.push({kind:'stop'});if(result.autoplay&&reason==='ended')effects.push({kind:'recommend',after:old.track});}return{state:result,effects};
}
/** Track events are fenced independently of queue/config revisions. Duplicate/late callbacks are no-ops. */
export function finishMusicTrack(state:MusicState,generation:number,reason:'ended'|'failed'):MusicTransition {if(generation!==state.generation||!state.current)return{state,effects:[]};return advance(state,reason);}
/** Delayed recommendations cannot restart a stopped player or displace a newer member request. */
export function applyMusicRecommendation(state:MusicState,generation:number,entryInput:MusicEntry):MusicTransition {if(generation!==state.generation||!state.autoplay||state.current||state.queue.length||state.desiredStatus!=='IDLE')return{state,effects:[]};if(entryInput.requesterUserId!==null)fail('MUSIC_REQUESTER','Automatic recommendations must be identified as autoplay.');const entry=musicEntry(entryInput.id,null,entryInput.track,entryInput.requestedTrack,entryInput.resolutionMethod);if(state.history.at(-1)&&trackIdentity(state.history.at(-1)!.track)===trackIdentity(entry.track))fail('MUSIC_DUPLICATE','Autoplay cannot immediately repeat the finished track.');const result=next(state);freshPlayback(result,entry);return{state:result,effects:[{kind:'play',entry,positionMs:0},{kind:'volume',percent:result.volume}]};}
export function voteMusicSkip(state:MusicState,actor:MusicActor,eligibleListenerIds:readonly string[]):MusicTransition & {votes:number;needed:number;skipped:boolean} {
 assertMusicActor(state,actor);const entry=current(state),eligible=new Set(eligibleListenerIds.filter(Boolean));if(!eligible.has(actor.userId))fail('MUSIC_LISTENER','Only current eligible listeners can vote to skip.');const needed=Math.floor(eligible.size/2)+1;
 if(actor.isDj||entry.requesterUserId===actor.userId)return{...advance(state,'skip'),votes:0,needed,skipped:true};
 const engine=new VotingEngine({anonymous:false,editable:true,hiddenUntilClose:false,eligibleChoices:['skip']});if(state.skipVotes.generation===state.generation)for(const id of new Set(state.skipVotes.voterIds))if(eligible.has(id))engine.cast(id,'skip',new Date(0));engine.cast(actor.userId,'skip',new Date(0));const votes=engine.results().skip??0;
 if(votes>=needed)return{...advance(state,'skip'),votes,needed,skipped:true};const result=next(state);result.skipVotes={generation:state.generation,voterIds:engine.snapshotForPersistence().map(b=>b.voterUserId).sort()};return{state:result,effects:[],votes,needed,skipped:false};
}
export type MusicControl=
 |{kind:'pause'|'resume'|'previous'|'replay'|'stop'|'leave'|'clear'|'join'}
 |{kind:'seek';positionMs:number}|{kind:'volume';percent:number}|{kind:'loop';mode:'off'|'track'|'queue'}|{kind:'autoplay';enabled:boolean}
 |{kind:'remove';entryId:string}|{kind:'move';entryId:string;position:number}|{kind:'jump';entryId:string}|{kind:'shuffle';entryIds:readonly string[]}|{kind:'relocate';voiceChannelId:string};
export function controlMusic(state:MusicState,actor:MusicActor,control:MusicControl):MusicTransition {
 assertMusicActor(state,actor,['stop','leave','relocate'].includes(control.kind));const result=next(state),effects:MusicEffect[]=[];
 switch(control.kind){
 case 'pause':current(result);if(result.desiredStatus!=='PAUSED'){result.desiredStatus='PAUSED';effects.push({kind:'pause'});}break;
 case 'resume':current(result);if(result.desiredStatus!=='PLAYING'){result.desiredStatus='PLAYING';effects.push({kind:'resume'});}break;
 case 'seek':{const entry=current(result);playbackOwner(actor,entry);if(!entry.track.seekable||entry.track.durationMs===null)fail('MUSIC_SEEK','This source cannot seek.');bounded(control.positionMs,0,(entry.track.durationMs??fail('MUSIC_SEEK','This source cannot seek.'))-1,'MUSIC_SEEK');const desired=result.desiredStatus;freshPlayback(result,entry,control.positionMs);result.desiredStatus=desired;effects.push({kind:'play',entry,positionMs:control.positionMs});if(desired==='PAUSED')effects.push({kind:'pause'});break;}
 case 'replay':{const entry=current(result);playbackOwner(actor,entry);freshPlayback(result,entry);effects.push({kind:'play',entry,positionMs:0});break;}
 case 'previous':{const previous=result.history.pop()??fail('MUSIC_HISTORY','There is no previous track.');playbackOwner(actor,result.current??previous);result.queue=result.queue.filter(entry=>entry.id!==previous.id);if(result.current&&result.current.id!==previous.id)result.queue.unshift(result.current);if(result.queue.length+1>result.queueMaxTracks)fail('MUSIC_QUEUE_LIMIT','Make room in the queue before playing the previous track.');freshPlayback(result,previous);effects.push({kind:'play',entry:previous,positionMs:0});break;}
 case 'volume':dj(actor);result.volume=bounded(control.percent,1,100,'MUSIC_VOLUME');effects.push({kind:'volume',percent:result.volume});break;
 case 'loop':dj(actor);if(!['off','track','queue'].includes(control.mode))fail('MUSIC_LOOP','Choose off, track or queue loop.');result.loop=control.mode;break;
 case 'autoplay':dj(actor);if(typeof control.enabled!=='boolean')fail('MUSIC_AUTOPLAY','Choose whether autoplay is enabled.');result.autoplay=control.enabled;break;
 case 'clear':dj(actor);result.queue=[];break;
 case 'stop':case 'leave':dj(actor);if(result.current)archive(result,result.current);result.queue=[];freshPlayback(result,null);effects.push({kind:'stop'});if(control.kind==='leave'){result.desiredStatus='DISCONNECTED';effects.push({kind:'disconnect'});}break;
 case 'join':effects.push({kind:'connect',voiceChannelId:result.voiceChannelId});if(!result.current)result.desiredStatus='IDLE';break;
 case 'remove':{const at=result.queue.findIndex(e=>e.id===control.entryId);if(at<0)fail('MUSIC_ENTRY','That queued track is no longer available.');owned(actor,[result.queue[at]!]);result.queue.splice(at,1);break;}
 case 'move':{const at=result.queue.findIndex(e=>e.id===control.entryId);if(at<0)fail('MUSIC_ENTRY','That queued track is no longer available.');owned(actor,[result.queue[at]!]);bounded(control.position,1,result.queue.length,'MUSIC_POSITION');const entry=result.queue.splice(at,1)[0]!;result.queue.splice(control.position-1,0,entry);break;}
 case 'jump':{const at=result.queue.findIndex(e=>e.id===control.entryId);if(at<0)fail('MUSIC_ENTRY','That queued track is no longer available.');owned(actor,[...(result.current?[result.current]:[]),...result.queue.slice(0,at)]);if(result.current)archive(result,result.current);const entry=result.queue[at]!;result.queue=result.queue.slice(at+1);freshPlayback(result,entry);effects.push({kind:'play',entry,positionMs:0});break;}
 case 'shuffle':{owned(actor,result.queue);if(control.entryIds.length!==result.queue.length||new Set(control.entryIds).size!==result.queue.length)fail('MUSIC_SHUFFLE','Shuffle must contain every queued entry exactly once.');const byId=new Map(result.queue.map(e=>[e.id,e]));result.queue=control.entryIds.map(id=>byId.get(id)??fail('MUSIC_SHUFFLE','Shuffle contains an unknown entry.'));break;}
 case 'relocate':dj(actor);if(!control.voiceChannelId||control.voiceChannelId!==actor.voiceChannelId)fail('MUSIC_LOCATION','Join the destination voice channel before moving the player.');result.voiceChannelId=control.voiceChannelId;result.textChannelId=control.voiceChannelId;const desired=result.desiredStatus;freshPlayback(result,result.current,result.positionMs);result.desiredStatus=desired;effects.push({kind:'stop'},{kind:'connect',voiceChannelId:control.voiceChannelId},{kind:'volume',percent:result.volume});if(result.current){effects.push({kind:'play',entry:result.current,positionMs:result.positionMs});if(desired==='PAUSED')effects.push({kind:'pause'});}break;
 default:fail('MUSIC_CONTROL','Choose a supported music control.');
 }return{state:result,effects};
}
/** Call only with transport observations, never merely because a command/job was accepted. */
export function observeMusic(state:MusicState,event:{generation:number;status:ObservedMusicStatus;positionMs:number;at:number;error?:string}):MusicTransition {
 if(event.generation!==state.generation||state.observedAt!==null&&event.at<state.observedAt)return{state,effects:[]};bounded(event.at,0,Number.MAX_SAFE_INTEGER,'MUSIC_TIME');bounded(event.positionMs,0,state.current?.track.durationMs??604800000,'MUSIC_POSITION');if(!['IDLE','PLAYING','PAUSED','DISCONNECTED','RECOVERING','FAILED'].includes(event.status))fail('MUSIC_OBSERVATION','Invalid playback observation.');if(['PLAYING','PAUSED'].includes(event.status)&&!state.current)fail('MUSIC_OBSERVATION','No track is selected for this playback event.');const result=next(state);result.observedStatus=event.status;result.observedGeneration=event.generation;result.positionMs=event.positionMs;result.observedAt=event.at;result.lastError=event.status==='FAILED'?'The playable source or voice connection failed.':null;return{state:result,effects:[]};
}
/** Restart never claims that audio resumed. A worker must resolve/reconnect and report observations. */
export function recoverMusic(state:MusicState):MusicTransition {const result=next(state);result.generation++;result.observedStatus='RECOVERING';result.observedGeneration=result.generation;result.observedAt=null;result.skipVotes={generation:result.generation,voterIds:[]};if(result.desiredStatus==='DISCONNECTED')return{state:result,effects:[{kind:'disconnect'}]};const effects:MusicEffect[]=[{kind:'connect',voiceChannelId:result.voiceChannelId},{kind:'volume',percent:result.volume}];if(result.current){const position=result.current.track.seekable?result.positionMs:0;result.positionMs=position;effects.push({kind:'play',entry:result.current,positionMs:position});if(result.desiredStatus==='PAUSED')effects.push({kind:'pause'});}return{state:result,effects};}
export function musicController(state:MusicState,now:number){const confirmed=state.observedGeneration===state.generation,status=confirmed&&state.observedStatus===state.desiredStatus?state.observedStatus:confirmed&&state.observedStatus==='FAILED'?'FAILED':confirmed&&state.observedStatus==='RECOVERING'?'RECOVERING':'PENDING';const display=state.current?.requestedTrack??state.current?.track;const elapsed=status==='PLAYING'&&state.observedAt!==null?Math.max(0,now-state.observedAt):0;return{title:display?.title??'THE JUKEBOX IS EMPTY',artist:display?.artist??null,album:display?.album??null,artworkUrl:display?.artworkUrl??null,provider:state.current?.track.provider??null,requestedProvider:display?.provider??null,requesterUserId:state.current?.requesterUserId??null,durationMs:state.current?.track.durationMs??null,positionMs:state.current?Math.min(state.positionMs+elapsed,state.current.track.durationMs??Number.MAX_SAFE_INTEGER):0,status,desiredStatus:state.desiredStatus,voiceChannelId:state.voiceChannelId,queueCount:state.queue.length,volume:state.volume,loop:state.loop,autoplay:state.autoplay,prompt:state.current?null:'Use /play and type something worth listening to.'};}
