import {DomainError} from '../../core/src/errors.js';
import {assertMusicLocation,musicEntry,trackIdentity,validateMusicMetadata} from './domain.js';
import type {MusicActor,MusicEntry,MusicMetadata,MusicPlaylist} from './interfaces.js';
function playlistName(value:string){const name=value.trim();if(!name||name.length>80||/[\u0000-\u001f]/.test(name))throw new DomainError('MUSIC_PLAYLIST_NAME','Use a playlist name of 1–80 characters.');return name;}
export function assertPlaylistOwner(playlist:MusicPlaylist,actor:MusicActor){assertMusicLocation(actor);if(playlist.guildId!==actor.guildId||playlist.ownerUserId!==actor.userId)throw new DomainError('MUSIC_PLAYLIST_OWNER','Open your own playlist in this server.');}
export function createMusicPlaylist(id:string,actor:MusicActor,name:string):MusicPlaylist {assertMusicLocation(actor);if(!id||id.length>100)throw new DomainError('MUSIC_PLAYLIST','The playlist needs a stable ID.');return{id,guildId:actor.guildId,ownerUserId:actor.userId,name:playlistName(name),revision:0,tracks:[]};}
export function renameMusicPlaylist(playlist:MusicPlaylist,actor:MusicActor,name:string):MusicPlaylist {assertPlaylistOwner(playlist,actor);return{...playlist,name:playlistName(name),revision:playlist.revision+1};}
export function addPlaylistTracks(playlist:MusicPlaylist,actor:MusicActor,input:readonly MusicMetadata[],maxTracks:number,confirmDuplicates=false):MusicPlaylist {
 assertPlaylistOwner(playlist,actor);if(!Number.isSafeInteger(maxTracks)||maxTracks<1||maxTracks>1000||!input.length||playlist.tracks.length+input.length>maxTracks)throw new DomainError('MUSIC_PLAYLIST_LIMIT','This selection exceeds the playlist limit.');
 const tracks=input.map(validateMusicMetadata),seen=new Set(playlist.tracks.map(trackIdentity));for(const track of tracks){const key=trackIdentity(track);if(seen.has(key)&&!confirmDuplicates)throw new DomainError('MUSIC_DUPLICATE','This playlist already contains a selected track. Confirm before adding duplicates.');seen.add(key);}return{...playlist,revision:playlist.revision+1,tracks:[...playlist.tracks.map(t=>({...t})),...tracks]};
}
export function removePlaylistTrack(playlist:MusicPlaylist,actor:MusicActor,position:number):MusicPlaylist {assertPlaylistOwner(playlist,actor);if(!Number.isSafeInteger(position)||position<1||position>playlist.tracks.length)throw new DomainError('MUSIC_PLAYLIST_POSITION','Choose a current playlist track number.');return{...playlist,revision:playlist.revision+1,tracks:playlist.tracks.filter((_,n)=>n!==position-1).map(t=>({...t}))};}
/** New queue-entry IDs and copies isolate subsequent playlist edits/deletion from playback. */
export function playlistQueueEntries(playlist:MusicPlaylist,actor:MusicActor,entryIds:readonly string[]):MusicEntry[] {assertPlaylistOwner(playlist,actor);if(entryIds.length!==playlist.tracks.length||new Set(entryIds).size!==entryIds.length)throw new DomainError('MUSIC_ENTRY_ID','Each playlist track needs a fresh queue-entry ID.');return playlist.tracks.map((track,n)=>musicEntry(entryIds[n]!,actor.userId,track));}
/** Deletion authorization returns an intent only; it never changes an existing queue. */
export function deleteMusicPlaylist(playlist:MusicPlaylist,actor:MusicActor,confirmed:boolean){assertPlaylistOwner(playlist,actor);if(!confirmed)throw new DomainError('MUSIC_PLAYLIST_CONFIRM','Confirm deletion of this saved playlist.');return{playlistId:playlist.id,expectedRevision:playlist.revision};}
