import {Prisma,type PrismaClient,type MusicSession} from '@prisma/client';
import {AuditService,DomainError} from '../../core/src/index.js';
import {PrismaAtomicOperations,requestFingerprint} from '../../database/src/atomic-operations.js';
import {applyMusicRecommendation,controlMusic,createMusicState,enqueueMusic,finishMusicTrack,musicController,musicEntry,observeMusic,recoverMusic,voteMusicSkip,type MusicControl} from './domain.js';
import {addPlaylistTracks,createMusicPlaylist,deleteMusicPlaylist,removePlaylistTrack,renameMusicPlaylist} from './playlists.js';
import type {MusicActor,MusicEffect,MusicEntry,MusicMetadata,MusicPlaylist,MusicPolicy,MusicState,MusicTransition,ObservedMusicStatus} from './interfaces.js';
const json=(value:unknown)=>JSON.parse(JSON.stringify(value)) as Prisma.InputJsonObject;
export interface MusicRequest {actor:MusicActor;requestKey:string;}
export interface MusicIntent {revision:number;generation:number;effects:MusicEffect[];}
/** Durable state and intents only. This repository never reports that a provider played audio. */
export class PrismaMusicRepository {
 private atomic:PrismaAtomicOperations;
 constructor(private db:PrismaClient,private clock=()=>new Date()){this.atomic=new PrismaAtomicOperations(db);}
 private map(row:MusicSession):MusicState {
  const entry=(value:unknown):MusicEntry=>{if(!value||typeof value!=='object')throw new DomainError('MUSIC_LEGACY_STATE','This saved player needs an explicit migration/recovery before playback.');const item=value as MusicEntry;return musicEntry(item.id,item.requesterUserId,item.track);};
  if(!Array.isArray(row.queue)||!Array.isArray(row.history))throw new DomainError('MUSIC_LEGACY_STATE','This saved player needs an explicit migration/recovery before playback.');
  const votes=row.skipVotes as {generation?:number;voterIds?:string[]};
  return{guildId:row.guildId,voiceChannelId:row.voiceChannelId,textChannelId:row.textChannelId,revision:row.revision,generation:row.generation,current:row.currentTrack?entry(row.currentTrack):null,queue:row.queue.map(entry),history:row.history.map(entry),desiredStatus:row.desiredStatus as MusicState['desiredStatus'],observedStatus:row.observedStatus as MusicState['observedStatus'],observedGeneration:row.observedGeneration,positionMs:row.positionMs,observedAt:row.observedAt?.getTime()??null,volume:row.volume,loop:row.loopMode.toLowerCase() as MusicState['loop'],autoplay:row.autoplay,queueMaxTracks:row.queueMaxTracks,skipVotes:{generation:votes.generation??row.generation,voterIds:Array.isArray(votes.voterIds)?votes.voterIds.filter(id=>typeof id==='string'):[]},lastError:row.lastError};
 }
 async read(guildId:string){const row=await this.db.musicSession.findUnique({where:{guildId}});return row?{state:this.map(row),controllerMessageId:row.controllerMessageId}:null;}
 private async required(tx:Prisma.TransactionClient,guildId:string){const row=await tx.musicSession.findUnique({where:{guildId}});if(!row)throw new DomainError('MUSIC_SESSION','Use /play or /music join to open the player.');return this.map(row);}
 private fields(state:MusicState){return{voiceChannelId:state.voiceChannelId,textChannelId:state.textChannelId,revision:state.revision,generation:state.generation,state:musicController(state,this.clock().getTime()).status,desiredStatus:state.desiredStatus,observedStatus:state.observedStatus,observedGeneration:state.observedGeneration,currentTrack:state.current?json(state.current):Prisma.DbNull,queue:json(state.queue),history:json(state.history),skipVotes:json(state.skipVotes),positionMs:state.positionMs,observedAt:state.observedAt===null?null:new Date(state.observedAt),lastError:state.lastError,volume:state.volume,loopMode:state.loop,autoplay:state.autoplay,queueMaxTracks:state.queueMaxTracks};}
 private async persist(tx:Prisma.TransactionClient,before:MusicState|null,transition:MusicTransition){const state=transition.state;if(before){const updated=await tx.musicSession.updateMany({where:{guildId:state.guildId,revision:before.revision},data:{...this.fields(state),...(before.textChannelId!==state.textChannelId?{controllerMessageId:null}:{})}});if(updated.count!==1)throw new DomainError('SESSION_CONFLICT','The music player changed concurrently.');}else await tx.musicSession.create({data:{guildId:state.guildId,...this.fields(state)}});
  // Every state revision gets a reconciliation intent, including queue-only changes. A worker
  // reconciles the latest desired state; effects are hints, never authority to replay stale audio.
  const intent:MusicIntent={revision:state.revision,generation:state.generation,effects:transition.effects};const job=await tx.scheduledJob.create({data:{guildId:state.guildId,jobType:'music.reconcile',executionKey:`music:reconcile:${state.guildId}:${state.revision}`,dueAt:this.clock(),payload:json(intent)}});return{guildId:state.guildId,revision:state.revision,generation:state.generation,jobId:job.id};
 }
 async enqueue(request:MusicRequest,entries:readonly MusicEntry[],policy:MusicPolicy,confirmedDuplicates=false){return this.atomic.run(request.actor.guildId,'music:enqueue:'+request.requestKey,requestFingerprint({request,entries,policy,confirmedDuplicates}),async tx=>{
  const row=await tx.musicSession.findUnique({where:{guildId:request.actor.guildId}}),before=row?this.map(row):null;let base=before??createMusicState(request.actor.guildId,request.actor,policy).state;
  if(before&&before.voiceChannelId!==request.actor.voiceChannelId&&before.desiredStatus==='DISCONNECTED'&&before.observedStatus==='DISCONNECTED'&&before.observedGeneration===before.generation&&!before.current&&!before.queue.length){const opened=createMusicState(request.actor.guildId,request.actor,policy).state;base={...opened,revision:before.revision,generation:before.generation,history:before.history};}
  return this.persist(tx,before,enqueueMusic(base,request.actor,entries,policy,confirmedDuplicates));
 });}
 async join(request:MusicRequest,policy:MusicPolicy){return this.atomic.run(request.actor.guildId,'music:join:'+request.requestKey,requestFingerprint({request,policy}),async tx=>{const row=await tx.musicSession.findUnique({where:{guildId:request.actor.guildId}});if(!row){const created=createMusicState(request.actor.guildId,request.actor,policy);created.state.revision=1;return this.persist(tx,null,created);}const before=this.map(row);if(before.voiceChannelId!==request.actor.voiceChannelId&&before.desiredStatus==='DISCONNECTED'&&before.observedStatus==='DISCONNECTED'&&before.observedGeneration===before.generation&&!before.current&&!before.queue.length){const reopened=createMusicState(request.actor.guildId,request.actor,policy);reopened.state={...reopened.state,revision:before.revision+1,generation:before.generation+1,history:before.history};return this.persist(tx,before,reopened);}return this.persist(tx,before,controlMusic(before,request.actor,{kind:'join'}));});}
 async control(request:MusicRequest,expectedRevision:number,control:MusicControl){return this.atomic.run(request.actor.guildId,'music:control:'+request.requestKey,requestFingerprint({request,expectedRevision,control}),async tx=>{const before=await this.required(tx,request.actor.guildId);if(before.revision!==expectedRevision)throw new DomainError('MUSIC_STALE','The player changed. Use its current controls.');const result=await this.persist(tx,before,controlMusic(before,request.actor,control));if(['stop','leave','clear','relocate','volume','loop','autoplay'].includes(control.kind))await this.audit(tx,request.actor.guildId,request.actor.userId,'music.control.'+control.kind,request.requestKey,{revision:result.revision});return result;});}
 async skip(request:MusicRequest,expectedGeneration:number,eligibleListenerIds:readonly string[]){return this.atomic.run(request.actor.guildId,'music:skip:'+request.requestKey,requestFingerprint({request,expectedGeneration,eligibleListenerIds:[...new Set(eligibleListenerIds)].sort()}),async tx=>{const before=await this.required(tx,request.actor.guildId);if(before.generation!==expectedGeneration)throw new DomainError('MUSIC_STALE','The current track changed. Open Vote Skip again.');const transition=voteMusicSkip(before,request.actor,eligibleListenerIds),result=await this.persist(tx,before,transition);return{...result,votes:transition.votes,needed:transition.needed,skipped:transition.skipped};});}
 /** Trusted transport boundary only. PLAYING observations alone append confirmed history. */
 async observe(guildId:string,requestKey:string,event:{generation:number;status:ObservedMusicStatus;positionMs:number;at:number;error?:string}){return this.atomic.run(guildId,'music:observe:'+requestKey,requestFingerprint({guildId,event}),async tx=>{const before=await this.required(tx,guildId),transition=observeMusic(before,event);if(transition.state===before)return{ignored:true};
  if(event.status==='PLAYING'&&before.current){const key='music:played:'+event.generation,prior=await tx.operationReceipt.findUnique({where:{guildId_key:{guildId,key}}});if(!prior){const track=before.current.track;await tx.musicHistory.create({data:{guildId,requesterUserId:before.current.requesterUserId,provider:track.provider,reference:track.reference,metadata:json(track),playedAt:new Date(event.at)}});await tx.operationReceipt.create({data:{guildId,key,fingerprint:requestFingerprint({generation:event.generation,entryId:before.current.id}),result:{recorded:true}}});}}
  return{ignored:false,...await this.persist(tx,before,transition)};
 });}
 async trackEnded(guildId:string,requestKey:string,generation:number,reason:'ended'|'failed'){return this.atomic.run(guildId,'music:ended:'+requestKey,requestFingerprint({guildId,generation,reason}),async tx=>{const before=await this.required(tx,guildId),transition=finishMusicTrack(before,generation,reason);return transition.state===before?{ignored:true}:{ignored:false,...await this.persist(tx,before,transition)};});}
 async recommendation(guildId:string,requestKey:string,generation:number,entry:MusicEntry){return this.atomic.run(guildId,'music:recommendation:'+requestKey,requestFingerprint({guildId,generation,entry}),async tx=>{const before=await this.required(tx,guildId),transition=applyMusicRecommendation(before,generation,entry);return transition.state===before?{ignored:true}:{ignored:false,...await this.persist(tx,before,transition)};});}
 async recover(guildId:string,requestKey:string){return this.atomic.run(guildId,'music:recover:'+requestKey,requestFingerprint({guildId,requestKey}),async tx=>{const before=await this.required(tx,guildId);return this.persist(tx,before,recoverMusic(before));});}
 async intent(id:string){const row=await this.db.scheduledJob.findUniqueOrThrow({where:{id}});if(row.jobType!=='music.reconcile')throw new DomainError('MUSIC_JOB','Invalid music reconciliation intent.');const payload=row.payload as unknown as MusicIntent,current=await this.read(row.guildId);if(!current)throw new DomainError('MUSIC_SESSION','The music player is unavailable.');return{...row,payload,state:current.state,controllerMessageId:current.controllerMessageId,obsolete:payload.revision!==current.state.revision||payload.generation!==current.state.generation};}
 /** Completing an intent never changes observed playback status. The worker supplies actual observations separately. */
 async completeIntent(id:string){const job=await this.intent(id);await this.db.scheduledJob.update({where:{id},data:{status:'COMPLETED',completedAt:this.clock(),lastError:null}});return{obsolete:job.obsolete};}
 async linkController(guildId:string,channelId:string,messageId:string,expectedMessageId:string|null){if(!/^\d{17,20}$/.test(messageId))throw new DomainError('MUSIC_MESSAGE','A confirmed Discord message is required.');const saved=await this.db.musicSession.updateMany({where:{guildId,textChannelId:channelId,controllerMessageId:expectedMessageId},data:{controllerMessageId:messageId}});if(saved.count!==1)throw new DomainError('MUSIC_CHANNEL','The player moved before the controller was confirmed.');}
 async confirmedHistory(guildId:string,limit=20){if(!Number.isSafeInteger(limit)||limit<1||limit>100)throw new DomainError('MUSIC_HISTORY_LIMIT','Choose a history page of 1–100 entries.');return this.db.musicHistory.findMany({where:{guildId},orderBy:[{playedAt:'desc'},{id:'desc'}],take:limit});}
 private async playlist(tx:Prisma.TransactionClient,id:string):Promise<MusicPlaylist>{const row=await tx.playlist.findUnique({where:{id},include:{tracks:{orderBy:{position:'asc'}}}});if(!row)throw new DomainError('MUSIC_PLAYLIST','This playlist is unavailable.');return{id:row.id,guildId:row.guildId,ownerUserId:row.userId,name:row.name,revision:row.revision,tracks:row.tracks.map(t=>t.metadata as unknown as MusicMetadata)};}
 async playlists(guildId:string,userId:string){return this.db.playlist.findMany({where:{guildId,userId},select:{id:true,name:true,revision:true},orderBy:{name:'asc'},take:100});}
 async readPlaylist(request:MusicRequest,id:string){const playlist=await this.playlist(this.db,id);deleteMusicPlaylist(playlist,request.actor,true);return playlist;}
 async createPlaylist(request:MusicRequest,id:string,name:string){return this.atomic.run(request.actor.guildId,'music:playlist-create:'+request.requestKey,requestFingerprint({request,id,name}),async tx=>{const playlist=createMusicPlaylist(id,request.actor,name);if(await tx.playlist.findUnique({where:{guildId_userId_name:{guildId:playlist.guildId,userId:playlist.ownerUserId,name:playlist.name}}}))throw new DomainError('MUSIC_PLAYLIST_NAME','You already have a playlist with that name.');await tx.playlist.create({data:{id:playlist.id,guildId:playlist.guildId,userId:playlist.ownerUserId,name:playlist.name}});return{playlistId:playlist.id,revision:0};});}
 async editPlaylist(request:MusicRequest,id:string,expectedRevision:number,change:{kind:'rename';name:string}|{kind:'add';tracks:MusicMetadata[];maxTracks:number;confirmedDuplicates:boolean}|{kind:'remove';position:number}|{kind:'delete';confirmed:boolean}){return this.atomic.run(request.actor.guildId,'music:playlist-edit:'+request.requestKey,requestFingerprint({request,id,expectedRevision,change}),async tx=>{const before=await this.playlist(tx,id);if(before.revision!==expectedRevision)throw new DomainError('MUSIC_PLAYLIST_STALE','The playlist changed. Open it again before editing.');if(change.kind==='delete'){deleteMusicPlaylist(before,request.actor,change.confirmed);await tx.playlist.delete({where:{id}});await this.audit(tx,request.actor.guildId,request.actor.userId,'music.playlist.deleted',request.requestKey,{playlistId:id});return{playlistId:id,revision:expectedRevision+1,deleted:true};}
  const after=change.kind==='rename'?renameMusicPlaylist(before,request.actor,change.name):change.kind==='add'?addPlaylistTracks(before,request.actor,change.tracks,change.maxTracks,change.confirmedDuplicates):removePlaylistTrack(before,request.actor,change.position);
  if(change.kind==='rename'&&await tx.playlist.findFirst({where:{guildId:after.guildId,userId:after.ownerUserId,name:after.name,id:{not:id}}}))throw new DomainError('MUSIC_PLAYLIST_NAME','You already have a playlist with that name.');const updated=await tx.playlist.updateMany({where:{id,revision:expectedRevision},data:{name:after.name,revision:after.revision}});if(updated.count!==1)throw new DomainError('SESSION_CONFLICT','The playlist changed concurrently.');
  // Replace positions inside the transaction to avoid temporary unique-position collisions.
  await tx.playlistTrack.deleteMany({where:{playlistId:id}});if(after.tracks.length)await tx.playlistTrack.createMany({data:after.tracks.map((track,position)=>({playlistId:id,position,provider:track.provider,reference:track.reference,metadata:json(track)}))});return{playlistId:id,revision:after.revision,deleted:false};
 });}
 private async audit(tx:Prisma.TransactionClient,guildId:string,userId:string,action:string,requestId:string,after:unknown){await new AuditService({write:async e=>{await tx.auditEvent.create({data:{guildId,actorUserId:userId,source:e.source,action,requestId,after:json(after)}});}}).record({guildId,actorUserId:userId,source:'discord',action,requestId,after,createdAt:this.clock()});}
}
