import {Prisma,type PrismaClient,type MusicSession} from '@prisma/client';
import {randomUUID} from 'node:crypto';
import {AuditService,DomainError,SessionEngine,TimerEngine,type Session} from '../../core/src/index.js';
import {PrismaAtomicOperations,requestFingerprint} from '../../database/src/atomic-operations.js';
import {PrismaTransactionSessions} from '../../database/src/transaction-sessions.js';
import {applyMusicRecommendation,assertMusicActor,assertMusicLocation,controlMusic,createMusicState,enqueueMusic,finishMusicTrack,musicController,musicEntry,observeMusic,recoverMusic,voteMusicSkip,type MusicControl} from './domain.js';
import {addPlaylistTracks,assertPlaylistOwner,createMusicPlaylist,deleteMusicPlaylist,removePlaylistTrack,renameMusicPlaylist} from './playlists.js';
import type {AuthorizedMusicCatalog} from './catalog.js';
import {publicMusicMetadata,MusicResolutionService} from './resolution.js';
import type {MusicActor,MusicEffect,MusicEntry,MusicMetadata,MusicPlaylist,MusicPolicy,MusicState,MusicTransition,ObservedMusicStatus} from './interfaces.js';
const json=(value:unknown)=>JSON.parse(JSON.stringify(value)) as Prisma.InputJsonObject;
export interface MusicRequest {actor:MusicActor;requestKey:string;}
export interface MusicIntent {revision:number;generation:number;effects:MusicEffect[];}
export type MusicPlaylistChange={kind:'rename';name:string}|{kind:'add';tracks:MusicMetadata[];maxTracks:number;confirmedDuplicates:boolean}|{kind:'remove';position:number}|{kind:'delete';confirmed:boolean};
export interface MusicConfirmationData {schemaVersion:1;action:'enqueue'|'playlist-add'|'playlist-play'|'playlist-delete';catalogIds:string[];selectionFingerprint:string;playlistId?:string;playlistRevision?:number;maxTracks?:number;skippedCount:number;result?:Prisma.InputJsonObject;}
export type MusicSelectionResult={kind:'applied';count:number;skippedCount:number;result:Prisma.InputJsonObject}|{kind:'confirmation';sessionId:string;action:MusicConfirmationData['action'];count:number;skippedCount:number;expiresAt:string}|{kind:'cancelled'}|{kind:'expired'};
export interface MusicEventRequest {guildId:string;socketEpoch:string;sequence:number;expectedRevision:number;generation:number;entryId:string|null;}
export type MusicTransportEvent={kind:'track-start';at:number;positionMs:number}|{kind:'observation';status:ObservedMusicStatus;at:number;positionMs:number}|{kind:'track-end';reason:'finished'|'loadFailed'|'stopped'|'replaced'|'cleanup'};
export interface MusicControllerPublication {channelId:string;expectedMessageId:string|null;superseded:boolean;deliveryState:'PENDING'|'SENDING'|'SENT';deliveryMessageId?:string;}
export interface MusicResolutionContext {action?:'enqueue'|'playlist-add'|'playlist-play';playlistId?:string;playlistRevision?:number;maxTracks?:number;}
interface ResolvedItem {requested:MusicMetadata;playable?:MusicMetadata;method?:MusicEntry['resolutionMethod'];choices?:MusicMetadata[];unavailable?:boolean;}
interface MusicResolutionData {schemaVersion:2;context:MusicResolutionContext;inputHash:string;stage:'search'|'matching'|'confirm';items:ResolvedItem[];searchChoices?:MusicMetadata[];reason?:'duplicates'|'batch';result?:MusicResolvedOutcome;}
export type MusicResolvedOutcome=MusicSelectionResult|{kind:'resolution-choice';sessionId:string;version:number;title:string;choices:MusicMetadata[]}|{kind:'resolved-confirmation';sessionId:string;version:number;count:number;skippedCount:number;reason:'duplicates'|'batch'};
/** Durable state and intents only. This repository never reports that a provider played audio. */
export class PrismaMusicRepository {
 private atomic:PrismaAtomicOperations;
 constructor(private db:PrismaClient,private clock=()=>new Date()){this.atomic=new PrismaAtomicOperations(db);}
 private map(row:MusicSession):MusicState {
  const entry=(value:unknown):MusicEntry=>{if(!value||typeof value!=='object')throw new DomainError('MUSIC_LEGACY_STATE','This saved player needs an explicit migration/recovery before playback.');const item=value as MusicEntry;return musicEntry(item.id,item.requesterUserId,item.track,item.requestedTrack,item.resolutionMethod);};
  if(!Array.isArray(row.queue)||!Array.isArray(row.history))throw new DomainError('MUSIC_LEGACY_STATE','This saved player needs an explicit migration/recovery before playback.');
  const votes=row.skipVotes as {generation?:number;voterIds?:string[]};
  return{guildId:row.guildId,voiceChannelId:row.voiceChannelId,textChannelId:row.textChannelId,revision:row.revision,generation:row.generation,current:row.currentTrack?entry(row.currentTrack):null,queue:row.queue.map(entry),history:row.history.map(entry),desiredStatus:row.desiredStatus as MusicState['desiredStatus'],observedStatus:row.observedStatus as MusicState['observedStatus'],observedGeneration:row.observedGeneration,positionMs:row.positionMs,observedAt:row.observedAt?.getTime()??null,volume:row.volume,loop:row.loopMode.toLowerCase() as MusicState['loop'],autoplay:row.autoplay,queueMaxTracks:row.queueMaxTracks,skipVotes:{generation:votes.generation??row.generation,voterIds:Array.isArray(votes.voterIds)?votes.voterIds.filter(id=>typeof id==='string'):[]},lastError:row.lastError};
 }
 async read(guildId:string){const row=await this.db.musicSession.findUnique({where:{guildId}});return row?{state:this.map(row),controllerMessageId:row.controllerMessageId}:null;}
 private async required(tx:Prisma.TransactionClient,guildId:string){const row=await tx.musicSession.findUnique({where:{guildId}});if(!row)throw new DomainError('MUSIC_SESSION','Use /play or /music join to open the player.');return this.map(row);}
 private fields(state:MusicState){return{voiceChannelId:state.voiceChannelId,textChannelId:state.textChannelId,revision:state.revision,generation:state.generation,state:musicController(state,this.clock().getTime()).status,desiredStatus:state.desiredStatus,observedStatus:state.observedStatus,observedGeneration:state.observedGeneration,currentTrack:state.current?json(state.current):Prisma.DbNull,queue:json(state.queue),history:json(state.history),skipVotes:json(state.skipVotes),positionMs:state.positionMs,observedAt:state.observedAt===null?null:new Date(state.observedAt),lastError:state.lastError,volume:state.volume,loopMode:state.loop,autoplay:state.autoplay,queueMaxTracks:state.queueMaxTracks};}
 private async persist(tx:Prisma.TransactionClient,before:MusicState|null,transition:MusicTransition){const state=transition.state;if(before){if(before.textChannelId!==state.textChannelId){const prior=await tx.musicSession.findUniqueOrThrow({where:{guildId:state.guildId}});await this.supersedeControllers(tx,state.guildId);if(prior.controllerMessageId)await this.controllerCleanup(tx,state.guildId,before.textChannelId,prior.controllerMessageId);}const updated=await tx.musicSession.updateMany({where:{guildId:state.guildId,revision:before.revision},data:{...this.fields(state),...(before.textChannelId!==state.textChannelId?{controllerMessageId:null}:{})}});if(updated.count!==1)throw new DomainError('SESSION_CONFLICT','The music player changed concurrently.');}else await tx.musicSession.create({data:{guildId:state.guildId,...this.fields(state)}});
  // Desired-state mutations get a reconciliation intent, including queue-only changes. A worker
  // reconciles the latest desired state; effects are hints, never authority to replay stale audio.
  const intent:MusicIntent={revision:state.revision,generation:state.generation,effects:transition.effects};const job=await tx.scheduledJob.create({data:{guildId:state.guildId,jobType:'music.reconcile',executionKey:`music:reconcile:${state.guildId}:${state.revision}`,dueAt:this.clock(),payload:json(intent)}});return{guildId:state.guildId,revision:state.revision,generation:state.generation,jobId:job.id};
 }
 private async enqueueTx(tx:Prisma.TransactionClient,request:MusicRequest,entries:readonly MusicEntry[],policy:MusicPolicy,confirmedDuplicates=false){
  const row=await tx.musicSession.findUnique({where:{guildId:request.actor.guildId}}),before=row?this.map(row):null;let base=before??createMusicState(request.actor.guildId,request.actor,policy).state;
  if(before&&before.voiceChannelId!==request.actor.voiceChannelId&&before.desiredStatus==='DISCONNECTED'&&before.observedStatus==='DISCONNECTED'&&before.observedGeneration===before.generation&&!before.current&&!before.queue.length){const opened=createMusicState(request.actor.guildId,request.actor,policy).state;base={...opened,revision:before.revision,generation:before.generation,history:before.history};}
  return this.persist(tx,before,enqueueMusic(base,request.actor,entries,policy,confirmedDuplicates));
 }
 async enqueue(request:MusicRequest,entries:readonly MusicEntry[],policy:MusicPolicy,confirmedDuplicates=false){return this.atomic.run(request.actor.guildId,'music:enqueue:'+request.requestKey,requestFingerprint({request,entries,policy,confirmedDuplicates}),tx=>this.enqueueTx(tx,request,entries,policy,confirmedDuplicates));}
 async join(request:MusicRequest,policy:MusicPolicy){return this.atomic.run(request.actor.guildId,'music:join:'+request.requestKey,requestFingerprint({request,policy}),async tx=>{const row=await tx.musicSession.findUnique({where:{guildId:request.actor.guildId}});if(!row){const created=createMusicState(request.actor.guildId,request.actor,policy);created.state.revision=1;return this.persist(tx,null,created);}const before=this.map(row);if(before.voiceChannelId!==request.actor.voiceChannelId&&before.desiredStatus==='DISCONNECTED'&&before.observedStatus==='DISCONNECTED'&&before.observedGeneration===before.generation&&!before.current&&!before.queue.length){const reopened=createMusicState(request.actor.guildId,request.actor,policy);reopened.state={...reopened.state,revision:before.revision+1,generation:before.generation+1,history:before.history};return this.persist(tx,before,reopened);}return this.persist(tx,before,controlMusic(before,request.actor,{kind:'join'}));});}
 async control(request:MusicRequest,expectedRevision:number,control:MusicControl){return this.atomic.run(request.actor.guildId,'music:control:'+request.requestKey,requestFingerprint({request,expectedRevision,control}),async tx=>{const before=await this.required(tx,request.actor.guildId);if(before.revision!==expectedRevision)throw new DomainError('MUSIC_STALE','The player changed. Use its current controls.');const result=await this.persist(tx,before,controlMusic(before,request.actor,control));if(['stop','leave','clear','relocate','volume','loop','autoplay'].includes(control.kind))await this.audit(tx,request.actor.guildId,request.actor.userId,'music.control.'+control.kind,request.requestKey,{revision:result.revision});return result;});}
 async skip(request:MusicRequest,expectedGeneration:number,eligibleListenerIds:readonly string[]){return this.atomic.run(request.actor.guildId,'music:skip:'+request.requestKey,requestFingerprint({request,expectedGeneration,eligibleListenerIds:[...new Set(eligibleListenerIds)].sort()}),async tx=>{const before=await this.required(tx,request.actor.guildId);if(before.generation!==expectedGeneration)throw new DomainError('MUSIC_STALE','The current track changed. Open Vote Skip again.');const transition=voteMusicSkip(before,request.actor,eligibleListenerIds),result=await this.persist(tx,before,transition);return{...result,votes:transition.votes,needed:transition.needed,skipped:transition.skipped};});}
 /** Trusted transport boundary only. PLAYING observations alone append confirmed history. */
 async observe(guildId:string,requestKey:string,event:{generation:number;status:ObservedMusicStatus;positionMs:number;at:number;error?:string}){return this.atomic.run(guildId,'music:observe:'+requestKey,requestFingerprint({guildId,event}),async tx=>{const before=await this.required(tx,guildId),transition=observeMusic(before,event);if(transition.state===before)return{ignored:true};
  if(event.status==='PLAYING'&&before.current){const key='music:played:'+event.generation,prior=await tx.operationReceipt.findUnique({where:{guildId_key:{guildId,key}}});if(!prior){const track=before.current.track;await tx.musicHistory.create({data:{guildId,requesterUserId:before.current.requesterUserId,provider:track.provider,reference:track.reference,metadata:json(track),playedAt:new Date(event.at)}});await tx.operationReceipt.create({data:{guildId,key,fingerprint:requestFingerprint({generation:event.generation,entryId:before.current.id}),result:{recorded:true}}});}}
  return{ignored:false,...await this.persist(tx,before,transition)};
 });}
 async trackEnded(guildId:string,requestKey:string,generation:number,reason:'ended'|'failed'){return this.atomic.run(guildId,'music:ended:'+requestKey,requestFingerprint({guildId,generation,reason}),async tx=>{const before=await this.required(tx,guildId),transition=finishMusicTrack(before,generation,reason);return transition.state===before?{ignored:true}:{ignored:false,...await this.persist(tx,before,transition)};});}
 async recommendation(guildId:string,requestKey:string,generation:number,entry:MusicEntry){return this.atomic.run(guildId,'music:recommendation:'+requestKey,requestFingerprint({guildId,generation,entry}),async tx=>{const before=await this.required(tx,guildId),transition=applyMusicRecommendation(before,generation,entry);return transition.state===before?{ignored:true}:{ignored:false,...await this.persist(tx,before,transition)};});}
 async recover(guildId:string,requestKey:string){return this.atomic.run(guildId,'music:recover:'+requestKey,requestFingerprint({guildId,requestKey}),async tx=>{const before=await this.required(tx,guildId);return this.persist(tx,before,recoverMusic(before));});}
 /**
  * Trusted driver boundary: retire old socket epochs before calling. Revision conflicts
  * consume no receipt: re-project the same event against fresh state, never discard a
  * valid TrackStart solely because a queue-only revision changed. Replays exclude the
  * optimistic revision from their identity, but retain epoch/sequence/entry/generation.
  * Observations retain the desired-state revision and create no transport job. Otherwise
  * telemetry could obsolete a pending pause/volume intent without replacing it. The
  * serializable transaction plus expected revision/generation preserves command changes;
  * observedAt rejects stale telemetry. The driver coalesces presentation-only refreshes.
  */
 async applyTransportEvent(request:MusicEventRequest,event:MusicTransportEvent){
  if(!/^[A-Za-z0-9_-]{1,128}$/.test(request.socketEpoch)||!Number.isSafeInteger(request.sequence)||request.sequence<0||!Number.isSafeInteger(request.expectedRevision)||request.expectedRevision<0||!Number.isSafeInteger(request.generation)||request.generation<0)throw new DomainError('MUSIC_EVENT','Invalid transport event correlation.');
  const {expectedRevision,...identity}=request;
  return this.atomic.run(request.guildId,`music:event:${request.socketEpoch}:${request.sequence}`,requestFingerprint({identity,event}),async tx=>{
   const before=await this.required(tx,request.guildId);if(before.generation!==request.generation||(before.current?.id??null)!==request.entryId)return{ignored:true,needsControllerRefresh:false};
   if(before.revision!==expectedRevision)throw new DomainError('MUSIC_STALE','Re-project this transport event against the current player revision.');
   if(event.kind==='track-end'){
    if(!request.entryId||!['finished','loadFailed','stopped','replaced','cleanup'].includes(event.reason))throw new DomainError('MUSIC_EVENT','Invalid track completion.');
    if(event.reason!=='finished'&&event.reason!=='loadFailed')return{ignored:true,needsControllerRefresh:false};
    const transition=finishMusicTrack(before,request.generation,event.reason==='finished'?'ended':'failed');return{ignored:false,needsControllerRefresh:true,...await this.persist(tx,before,transition)};
   }
   if(event.kind==='track-start'&&!before.current)throw new DomainError('MUSIC_EVENT','A track start must identify the selected recording.');
   // PLAYING/PAUSED telemetry requires an independently confirmed start for this generation.
   // A caller cannot manufacture playback history from connected=true or a REST ack.
   if(event.kind==='observation'&&['PLAYING','PAUSED'].includes(event.status)&&!await tx.operationReceipt.findUnique({where:{guildId_key:{guildId:request.guildId,key:'music:played:'+request.generation}}}))throw new DomainError('MUSIC_UNCONFIRMED_TRACK','A correlated track start is required before playback telemetry.');
   const observation={generation:request.generation,status:event.kind==='track-start'?'PLAYING' as const:event.status,positionMs:event.positionMs,at:event.at};
   const transition=observeMusic(before,observation);if(transition.state===before)return{ignored:true,needsControllerRefresh:false};
   if(event.kind==='track-start')await this.recordPlayed(tx,before,event.at);
   const observed={...transition.state,revision:before.revision};const changed=await tx.musicSession.updateMany({where:{guildId:request.guildId,revision:expectedRevision,generation:request.generation},data:{state:musicController(observed,this.clock().getTime()).status,observedStatus:observed.observedStatus,observedGeneration:observed.observedGeneration,positionMs:observed.positionMs,observedAt:new Date(event.at),lastError:observed.lastError}});if(changed.count!==1)throw new DomainError('SESSION_CONFLICT','The player changed during a transport observation.');
   return{ignored:false,needsControllerRefresh:true,guildId:request.guildId,revision:before.revision,generation:before.generation};
  });
 }
 private async recordPlayed(tx:Prisma.TransactionClient,state:MusicState,at:number){if(!state.current)return;const key='music:played:'+state.generation;if(await tx.operationReceipt.findUnique({where:{guildId_key:{guildId:state.guildId,key}}}))return;const track=state.current.track;await tx.musicHistory.create({data:{guildId:state.guildId,requesterUserId:state.current.requesterUserId,provider:track.provider,reference:track.reference,metadata:json(track),playedAt:new Date(at)}});await tx.operationReceipt.create({data:{guildId:state.guildId,key,fingerprint:requestFingerprint({generation:state.generation,entryId:state.current.id}),result:{recorded:true}}});}
 async intent(id:string){const row=await this.db.scheduledJob.findUniqueOrThrow({where:{id}});if(row.jobType!=='music.reconcile')throw new DomainError('MUSIC_JOB','Invalid music reconciliation intent.');const payload=row.payload as unknown as MusicIntent,current=await this.read(row.guildId);if(!current)throw new DomainError('MUSIC_SESSION','The music player is unavailable.');return{...row,payload,state:current.state,controllerMessageId:current.controllerMessageId,obsolete:payload.revision!==current.state.revision||payload.generation!==current.state.generation};}
 /** Check immediately before each external operation; never grants authority beyond its lease. */
 async ownsIntentLease(id:string,leaseToken:string,fence:{guildId:string;revision:number;generation:number}){const job=await this.db.scheduledJob.findFirst({where:{id,guildId:fence.guildId,jobType:'music.reconcile',status:'RUNNING',leaseToken,leaseUntil:{gt:this.clock()}}});if(!job)return false;const player=await this.db.musicSession.findUnique({where:{guildId:fence.guildId}});return player?.revision===fence.revision&&player.generation===fence.generation;}
 /** Completing an intent never changes observed playback status. The worker supplies actual observations separately. */
 async completeIntent(id:string){const job=await this.intent(id);await this.db.scheduledJob.update({where:{id},data:{status:'COMPLETED',completedAt:this.clock(),lastError:null}});return{obsolete:job.obsolete};}
 async linkController(guildId:string,channelId:string,messageId:string,expectedMessageId:string|null){if(!/^\d{17,20}$/.test(messageId))throw new DomainError('MUSIC_MESSAGE','A confirmed Discord message is required.');const saved=await this.db.musicSession.updateMany({where:{guildId,textChannelId:channelId,controllerMessageId:expectedMessageId},data:{controllerMessageId:messageId}});if(saved.count!==1)throw new DomainError('MUSIC_CHANNEL','The player moved before the controller was confirmed.');}
 private async controllerCleanup(tx:Prisma.TransactionClient,guildId:string,channelId:string,messageId:string){return tx.scheduledJob.upsert({where:{executionKey:`music:controller-cleanup:${guildId}:${channelId}:${messageId}`},update:{},create:{guildId,jobType:'music.controller.cleanup',executionKey:`music:controller-cleanup:${guildId}:${channelId}:${messageId}`,dueAt:this.clock(),payload:{channelId,messageId}}});}
 private async supersedeControllers(tx:Prisma.TransactionClient,guildId:string){const active=await tx.scheduledJob.findMany({where:{guildId,jobType:'music.controller.publish',payload:{path:['superseded'],equals:false}}});for(const job of active){const payload=job.payload as unknown as MusicControllerPublication;await tx.scheduledJob.update({where:{id:job.id},data:{payload:json({...payload,superseded:true})}});if(payload.deliveryMessageId)await this.controllerCleanup(tx,guildId,payload.channelId,payload.deliveryMessageId);}}
 /**
  * Reserve one durable publication before Discord send. All player revisions share the
  * active reservation. expectedMessageId is null for ensure, or a positively identified
  * missing/retired authoritative post for explicit replacement. Only the trusted driver
  * calls this method; members never supply channel/message IDs to this boundary.
  */
 async reserveController(guildId:string,expectedRevision:number,expectedMessageId:string|null=null){return this.atomic.run(guildId,`music:controller-reserve:${expectedRevision}:${expectedMessageId??'initial'}`,requestFingerprint({guildId,expectedRevision,expectedMessageId}),async tx=>{
  const row=await tx.musicSession.findUniqueOrThrow({where:{guildId}});if(row.revision!==expectedRevision)throw new DomainError('MUSIC_STALE','The controller reservation needs the current player revision.');
  if(expectedMessageId!==null){if(row.controllerMessageId!==expectedMessageId)throw new DomainError('MUSIC_CONTROLLER_STALE','The authoritative controller already changed.');await this.supersedeControllers(tx,guildId);await this.controllerCleanup(tx,guildId,row.textChannelId,expectedMessageId);const reset=await tx.musicSession.updateMany({where:{guildId,revision:expectedRevision,controllerMessageId:expectedMessageId},data:{controllerMessageId:null}});if(reset.count!==1)throw new DomainError('SESSION_CONFLICT','The authoritative controller changed concurrently.');}
  else if(row.controllerMessageId)return{kind:'linked' as const,channelId:row.textChannelId,messageId:row.controllerMessageId};
  const active=await tx.scheduledJob.findFirst({where:{guildId,jobType:'music.controller.publish',payload:{path:['superseded'],equals:false}},orderBy:{dueAt:'asc'}});if(active){const payload=active.payload as unknown as MusicControllerPublication;if(payload.channelId!==row.textChannelId)throw new DomainError('MUSIC_CONTROLLER_STALE','The controller destination needs reconciliation.');return{kind:'publication' as const,jobId:active.id,channelId:payload.channelId,marker:'music-controller:'+active.id};}
  const payload:MusicControllerPublication={channelId:row.textChannelId,expectedMessageId:null,superseded:false,deliveryState:'PENDING'};const job=await tx.scheduledJob.create({data:{guildId,jobType:'music.controller.publish',executionKey:`music:controller-publish:${guildId}:${expectedRevision}:${expectedMessageId??'initial'}`,dueAt:this.clock(),payload:json(payload)}});return{kind:'publication' as const,jobId:job.id,channelId:row.textChannelId,marker:'music-controller:'+job.id};
 });}
 async controllerPublication(jobId:string){const job=await this.db.scheduledJob.findUniqueOrThrow({where:{id:jobId}});if(job.jobType!=='music.controller.publish')throw new DomainError('MUSIC_JOB','Invalid controller publication.');const payload=job.payload as unknown as MusicControllerPublication,saved=await this.read(job.guildId);return{job,payload,state:saved?.state??null,marker:'music-controller:'+job.id,obsolete:payload.superseded||!saved||saved.state.textChannelId!==payload.channelId||(saved.controllerMessageId!==null&&saved.controllerMessageId!==payload.deliveryMessageId)};}
 /** Shared DeliveryEngine must have durably reconciled this exact message before linking. */
 async finalizeController(jobId:string,messageId:string){if(!/^\d{17,20}$/.test(messageId))throw new DomainError('MUSIC_MESSAGE','A confirmed Discord controller message is required.');const job=await this.db.scheduledJob.findUniqueOrThrow({where:{id:jobId}});const result=await this.atomic.run(job.guildId,'music:controller-finalize:'+jobId,requestFingerprint({jobId,messageId}),async tx=>{const current=await tx.scheduledJob.findUniqueOrThrow({where:{id:jobId}});if(current.jobType!=='music.controller.publish')throw new DomainError('MUSIC_JOB','Invalid controller publication.');const payload=current.payload as unknown as MusicControllerPublication;if(payload.deliveryState!=='SENT'||payload.deliveryMessageId!==messageId)throw new DomainError('MUSIC_CONTROLLER_UNCONFIRMED','Reconcile the controller delivery before linking it.');const row=await tx.musicSession.findUnique({where:{guildId:job.guildId}});if(payload.superseded||!row||row.textChannelId!==payload.channelId||(row.controllerMessageId!==null&&row.controllerMessageId!==messageId)){await tx.scheduledJob.update({where:{id:jobId},data:{payload:json({...payload,superseded:true})}});await this.controllerCleanup(tx,job.guildId,payload.channelId,messageId);return{linked:false,channelId:payload.channelId,messageId};}if(row.controllerMessageId===null){const updated=await tx.musicSession.updateMany({where:{guildId:job.guildId,textChannelId:payload.channelId,controllerMessageId:null},data:{controllerMessageId:messageId}});if(updated.count!==1)throw new DomainError('SESSION_CONFLICT','The controller changed concurrently.');}return{linked:true,channelId:payload.channelId,messageId};});const latest=await this.db.musicSession.findUnique({where:{guildId:job.guildId}});return{...result,linked:result.linked&&latest?.textChannelId===result.channelId&&latest.controllerMessageId===result.messageId};}
 async controllerCleanupIntent(jobId:string){const job=await this.db.scheduledJob.findUniqueOrThrow({where:{id:jobId}});if(job.jobType!=='music.controller.cleanup')throw new DomainError('MUSIC_JOB','Invalid controller cleanup.');const payload=job.payload as {channelId:string;messageId:string},current=await this.db.musicSession.findUnique({where:{guildId:job.guildId}});return{job,payload,obsolete:current?.textChannelId===payload.channelId&&current.controllerMessageId===payload.messageId};}
 async confirmedHistory(guildId:string,limit=20){if(!Number.isSafeInteger(limit)||limit<1||limit>100)throw new DomainError('MUSIC_HISTORY_LIMIT','Choose a history page of 1–100 entries.');return this.db.musicHistory.findMany({where:{guildId},orderBy:[{playedAt:'desc'},{id:'desc'}],take:limit});}
 private async playlist(tx:Prisma.TransactionClient,id:string):Promise<MusicPlaylist>{const row=await tx.playlist.findUnique({where:{id},include:{tracks:{orderBy:{position:'asc'}}}});if(!row)throw new DomainError('MUSIC_PLAYLIST','This playlist is unavailable.');return{id:row.id,guildId:row.guildId,ownerUserId:row.userId,name:row.name,revision:row.revision,tracks:row.tracks.map(t=>t.metadata as unknown as MusicMetadata)};}
 async playlists(guildId:string,userId:string){return this.db.playlist.findMany({where:{guildId,userId},select:{id:true,name:true,revision:true},orderBy:{name:'asc'},take:100});}
 async readPlaylist(request:MusicRequest,id:string){const playlist=await this.playlist(this.db,id);deleteMusicPlaylist(playlist,request.actor,true);return playlist;}
 async createPlaylist(request:MusicRequest,id:string,name:string){return this.atomic.run(request.actor.guildId,'music:playlist-create:'+request.requestKey,requestFingerprint({request,id,name}),async tx=>{const playlist=createMusicPlaylist(id,request.actor,name);if(await tx.playlist.findUnique({where:{guildId_userId_name:{guildId:playlist.guildId,userId:playlist.ownerUserId,name:playlist.name}}}))throw new DomainError('MUSIC_PLAYLIST_NAME','You already have a playlist with that name.');await tx.playlist.create({data:{id:playlist.id,guildId:playlist.guildId,userId:playlist.ownerUserId,name:playlist.name}});return{playlistId:playlist.id,revision:0};});}
 private async editPlaylistTx(tx:Prisma.TransactionClient,request:MusicRequest,id:string,expectedRevision:number,change:MusicPlaylistChange){const before=await this.playlist(tx,id);if(before.revision!==expectedRevision)throw new DomainError('MUSIC_PLAYLIST_STALE','The playlist changed. Open it again before editing.');if(change.kind==='delete'){deleteMusicPlaylist(before,request.actor,change.confirmed);await tx.playlist.delete({where:{id}});await this.audit(tx,request.actor.guildId,request.actor.userId,'music.playlist.deleted',request.requestKey,{playlistId:id});return{playlistId:id,revision:expectedRevision+1,deleted:true};}
  const after=change.kind==='rename'?renameMusicPlaylist(before,request.actor,change.name):change.kind==='add'?addPlaylistTracks(before,request.actor,change.tracks,change.maxTracks,change.confirmedDuplicates):removePlaylistTrack(before,request.actor,change.position);
  if(change.kind==='rename'&&await tx.playlist.findFirst({where:{guildId:after.guildId,userId:after.ownerUserId,name:after.name,id:{not:id}}}))throw new DomainError('MUSIC_PLAYLIST_NAME','You already have a playlist with that name.');const updated=await tx.playlist.updateMany({where:{id,revision:expectedRevision},data:{name:after.name,revision:after.revision}});if(updated.count!==1)throw new DomainError('SESSION_CONFLICT','The playlist changed concurrently.');
  // Replace positions inside the transaction to avoid temporary unique-position collisions.
  await tx.playlistTrack.deleteMany({where:{playlistId:id}});if(after.tracks.length)await tx.playlistTrack.createMany({data:after.tracks.map((track,position)=>({playlistId:id,position,provider:track.provider,reference:track.reference,metadata:json(track)}))});return{playlistId:id,revision:after.revision,deleted:false};
 }
 async editPlaylist(request:MusicRequest,id:string,expectedRevision:number,change:MusicPlaylistChange){return this.atomic.run(request.actor.guildId,'music:playlist-edit:'+request.requestKey,requestFingerprint({request,id,expectedRevision,change}),tx=>this.editPlaylistTx(tx,request,id,expectedRevision,change));}
 private selection(ids:readonly string[],catalog:AuthorizedMusicCatalog){if(!ids.length)throw new DomainError('MUSIC_UNAVAILABLE','No available authorized catalog recordings remain in this selection.');if(ids.length>1000||ids.some(id=>!/^catalog:[A-Za-z0-9_-]{1,80}$/.test(id)))throw new DomainError('MUSIC_SELECTION','Choose a bounded selection of authorized catalog recordings.');return ids.map(id=>{const resolved=catalog.resolve(id);if(resolved.status!=='available')throw new DomainError('MUSIC_UNAVAILABLE',resolved.notice.message);return resolved.track.metadata;});}
 private selectionHash(tracks:readonly MusicMetadata[]){return requestFingerprint(tracks.map(({provider,reference,title,artist,album,durationMs,isrc,explicit})=>({provider,reference,title,artist,album,durationMs,isrc:isrc??null,explicit:explicit??null})));}
 private async openConfirmation(tx:Prisma.TransactionClient,request:MusicRequest,data:MusicConfirmationData):Promise<MusicSelectionResult>{const now=this.clock(),timer=TimerEngine.create(now,300),id=randomUUID();await new PrismaTransactionSessions(tx).create({id,guildId:request.actor.guildId,channelId:request.actor.textChannelId,ownerUserId:request.actor.userId,type:'music.confirmation',state:'OPEN',data,expiresAt:timer.expiresAt,extensionUsed:false,version:0,createdAt:now,updatedAt:now});return{kind:'confirmation',sessionId:id,action:data.action,count:data.catalogIds.length,skippedCount:data.skippedCount,expiresAt:timer.expiresAt.toISOString()};}
 private async selectedMutation(tx:Prisma.TransactionClient,request:MusicRequest,data:MusicConfirmationData,tracks:MusicMetadata[],policy:MusicPolicy,confirmed:boolean):Promise<MusicSelectionResult>{
  if(data.playlistId){const playlist=await this.playlist(tx,data.playlistId);assertPlaylistOwner(playlist,request.actor);if(playlist.revision!==data.playlistRevision)throw new DomainError('MUSIC_PLAYLIST_STALE','The playlist changed. Open it again before confirming.');}
  const result=data.action==='playlist-delete'?await this.editPlaylistTx(tx,request,data.playlistId!,data.playlistRevision!,{kind:'delete',confirmed}):data.action==='playlist-add'?await this.editPlaylistTx(tx,request,data.playlistId!,data.playlistRevision!,{kind:'add',tracks,maxTracks:data.maxTracks!,confirmedDuplicates:confirmed}):await this.enqueueTx(tx,request,tracks.map((track,n)=>musicEntry('music-'+request.requestKey+'-'+n,request.actor.userId,track)),policy,confirmed);
  return{kind:'applied',count:tracks.length,skippedCount:data.skippedCount,result};
 }
 async requestCatalogEnqueue(request:MusicRequest,ids:readonly string[],catalog:AuthorizedMusicCatalog,policy:MusicPolicy):Promise<MusicSelectionResult>{assertMusicLocation(request.actor);return this.atomic.run(request.actor.guildId,'music:catalog:'+request.requestKey,requestFingerprint({request,ids,policy}),async tx=>{const tracks=this.selection(ids,catalog),data:MusicConfirmationData={schemaVersion:1,action:'enqueue',catalogIds:[...ids],selectionFingerprint:this.selectionHash(tracks),skippedCount:0};try{return await this.selectedMutation(tx,request,data,tracks,policy,false);}catch(error){if(!(error instanceof DomainError)||error.code!=='MUSIC_DUPLICATE')throw error;return this.openConfirmation(tx,request,data);}});}
 async requestPlaylistAdd(request:MusicRequest,id:string,revision:number,ids:readonly string[],catalog:AuthorizedMusicCatalog,maxTracks=1000):Promise<MusicSelectionResult>{assertMusicLocation(request.actor);return this.atomic.run(request.actor.guildId,'music:playlist-selection:'+request.requestKey,requestFingerprint({request,id,revision,ids,maxTracks}),async tx=>{const tracks=this.selection(ids,catalog),data:MusicConfirmationData={schemaVersion:1,action:'playlist-add',catalogIds:[...ids],selectionFingerprint:this.selectionHash(tracks),playlistId:id,playlistRevision:revision,maxTracks,skippedCount:0};try{return await this.selectedMutation(tx,request,data,tracks,{} as MusicPolicy,false);}catch(error){if(!(error instanceof DomainError)||error.code!=='MUSIC_DUPLICATE')throw error;return this.openConfirmation(tx,request,data);}});}
 async requestPlaylistPlay(request:MusicRequest,id:string,revision:number,catalog:AuthorizedMusicCatalog,policy:MusicPolicy):Promise<MusicSelectionResult>{assertMusicLocation(request.actor);return this.atomic.run(request.actor.guildId,'music:playlist-play:'+request.requestKey,requestFingerprint({request,id,revision,policy}),async tx=>{const playlist=await this.playlist(tx,id);assertPlaylistOwner(playlist,request.actor);if(playlist.revision!==revision)throw new DomainError('MUSIC_PLAYLIST_STALE','The playlist changed. Open it again.');const ids=playlist.tracks.filter(track=>track.provider==='authorized_catalog'&&catalog.resolve(track.reference).status==='available').map(track=>track.reference),tracks=this.selection(ids,catalog),data:MusicConfirmationData={schemaVersion:1,action:'playlist-play',catalogIds:ids,selectionFingerprint:this.selectionHash(tracks),playlistId:id,playlistRevision:revision,skippedCount:playlist.tracks.length-ids.length};try{return await this.selectedMutation(tx,request,data,tracks,policy,false);}catch(error){if(!(error instanceof DomainError)||error.code!=='MUSIC_DUPLICATE')throw error;return this.openConfirmation(tx,request,data);}});}
 async requestPlaylistDelete(request:MusicRequest,id:string,revision:number):Promise<MusicSelectionResult>{assertMusicLocation(request.actor);return this.atomic.run(request.actor.guildId,'music:playlist-delete-preview:'+request.requestKey,requestFingerprint({request,id,revision}),async tx=>{const playlist=await this.playlist(tx,id);assertPlaylistOwner(playlist,request.actor);if(playlist.revision!==revision)throw new DomainError('MUSIC_PLAYLIST_STALE','The playlist changed. Open it again.');return this.openConfirmation(tx,request,{schemaVersion:1,action:'playlist-delete',catalogIds:[],selectionFingerprint:this.selectionHash([]),playlistId:id,playlistRevision:revision,skippedCount:0});});}
 private async scopedConfirmation(tx:Prisma.TransactionClient,request:MusicRequest,id:string){assertMusicLocation(request.actor);const session=await new PrismaTransactionSessions(tx).get<MusicConfirmationData>(id);if(!session||session.type!=='music.confirmation'||session.guildId!==request.actor.guildId||session.ownerUserId!==request.actor.userId||session.channelId!==request.actor.textChannelId)throw new DomainError('MUSIC_CONFIRMATION_OWNER','Open your own music confirmation in its original voice chat.');return session;}
 async confirmSelection(request:MusicRequest,id:string,catalog:AuthorizedMusicCatalog,policy:MusicPolicy):Promise<MusicSelectionResult>{assertMusicLocation(request.actor);return this.atomic.run(request.actor.guildId,'music:confirm:'+id,requestFingerprint({id,actor:{guildId:request.actor.guildId,userId:request.actor.userId,channelId:request.actor.textChannelId}}),async tx=>{const session=await this.scopedConfirmation(tx,request,id),engine=new SessionEngine(new PrismaTransactionSessions(tx));if(session.state==='CANCELLED')return{kind:'cancelled'};if(session.state!=='OPEN')throw new DomainError('MUSIC_CONFIRMATION_CLOSED','This music confirmation has already finished.');if(!session.expiresAt||TimerEngine.isExpired({openedAt:session.createdAt,expiresAt:session.expiresAt,extensionUsed:false},this.clock())){await engine.transition(id,['OPEN'],'CANCELLED');return{kind:'expired'};}const data=session.data,tracks=data.action==='playlist-delete'?[]:this.selection(data.catalogIds,catalog);if(this.selectionHash(tracks)!==data.selectionFingerprint)throw new DomainError('MUSIC_SELECTION_CHANGED','The catalog recording details changed. Start a fresh selection.');const result=await this.selectedMutation(tx,{...request,requestKey:id},data,tracks,policy,true);await engine.transition<MusicConfirmationData>(id,['OPEN'],'CLOSED',next=>({...next,data:{...data,result:json(result)}}));return result;});}
 async cancelConfirmation(request:MusicRequest,id:string):Promise<MusicSelectionResult>{assertMusicLocation(request.actor);return this.atomic.run(request.actor.guildId,'music:cancel:'+id,requestFingerprint({id,actor:{guildId:request.actor.guildId,userId:request.actor.userId,channelId:request.actor.textChannelId}}),async tx=>{const session=await this.scopedConfirmation(tx,request,id);if(session.state==='CLOSED')throw new DomainError('MUSIC_CONFIRMATION_CLOSED','This music selection has already been applied.');if(session.state==='OPEN')await new SessionEngine(new PrismaTransactionSessions(tx)).transition(id,['OPEN'],'CANCELLED');return{kind:'cancelled'};});}
 private publicTracks(input:readonly MusicMetadata[],limit=1000){if(!input.length||input.length>limit)throw new DomainError('MUSIC_SELECTION','Choose a bounded music selection.');return input.map(publicMusicMetadata);}
 private async resolutionAtomic(guildId:string,key:string,fingerprint:string,work:(tx:Prisma.TransactionClient)=>Promise<MusicResolvedOutcome>):Promise<MusicResolvedOutcome>{return await this.atomic.run(guildId,key,fingerprint,async tx=>json(await work(tx))) as unknown as MusicResolvedOutcome;}
 private identityHash(tracks:readonly MusicMetadata[]){return requestFingerprint(tracks.map(t=>({provider:t.provider,reference:t.reference,title:t.title,artist:t.artist,album:t.album,durationMs:t.durationMs,isrc:t.isrc??null,explicit:t.explicit??null})));}
 private async resolutionDuplicates(tx:Prisma.TransactionClient,request:MusicRequest,context:MusicResolutionContext,items:ResolvedItem[]){let existing:MusicMetadata[]=[];if(context.action==='playlist-add'){const playlist=await this.playlist(tx,context.playlistId!);assertPlaylistOwner(playlist,request.actor);if(playlist.revision!==context.playlistRevision)throw new DomainError('MUSIC_PLAYLIST_STALE','The playlist changed. Open it again.');existing=playlist.tracks;}else{const row=await tx.musicSession.findUnique({where:{guildId:request.actor.guildId}});if(row){const state=this.map(row);assertMusicActor(state,request.actor);existing=[...(state.current?[state.current.track]:[]),...state.queue.map(entry=>entry.track)];}}const identity=(track:MusicMetadata)=>JSON.stringify([track.provider,track.reference]),seen=new Set(existing.map(identity));let duplicate=false;for(const item of items){const key=identity(context.action==='playlist-add'?item.requested:item.playable!);if(seen.has(key))duplicate=true;seen.add(key);}return duplicate;}
 private resolutionExpired(session:Session<MusicResolutionData>){return!session.expiresAt||TimerEngine.isExpired({openedAt:session.createdAt,expiresAt:session.expiresAt,extensionUsed:false},this.clock());}
 private async scopedResolution(tx:Prisma.TransactionClient,request:MusicRequest,id:string){assertMusicLocation(request.actor);const session=await new PrismaTransactionSessions(tx).get<MusicResolutionData>(id);if(!session||session.type!=='music.resolution'||session.guildId!==request.actor.guildId||session.ownerUserId!==request.actor.userId||session.channelId!==request.actor.textChannelId)throw new DomainError('MUSIC_CONFIRMATION_OWNER','Open your own music selection in its original voice chat.');return session;}
 private resolutionOutcome(session:Session<MusicResolutionData>):MusicResolvedOutcome {if(session.state==='CANCELLED')return{kind:'cancelled'};if(session.state==='CLOSED'&&session.data.result)return session.data.result;const data=session.data;if(data.stage==='search')return{kind:'resolution-choice',sessionId:session.id,version:session.version,title:'Choose the exact recording',choices:data.searchChoices??[]};const pending=data.items.find(item=>item.choices?.length);if(pending)return{kind:'resolution-choice',sessionId:session.id,version:session.version,title:`Choose a playable match for ${pending.requested.title}`,choices:pending.choices!};return{kind:'resolved-confirmation',sessionId:session.id,version:session.version,count:data.items.filter(item=>!item.unavailable).length,skippedCount:data.items.filter(item=>item.unavailable).length,reason:data.reason??'batch'};}
 private async createResolution(tx:Prisma.TransactionClient,request:MusicRequest,data:MusicResolutionData){const now=this.clock(),timer=TimerEngine.create(now,300);return new PrismaTransactionSessions(tx).create({id:randomUUID(),guildId:request.actor.guildId,channelId:request.actor.textChannelId,ownerUserId:request.actor.userId,type:'music.resolution',state:'OPEN',data,expiresAt:timer.expiresAt,extensionUsed:false,version:0,createdAt:now,updatedAt:now});}
 private async prepareItems(tracks:readonly MusicMetadata[],service:MusicResolutionService,context:MusicResolutionContext,signal:AbortSignal):Promise<ResolvedItem[]>{const input=this.publicTracks(tracks);if(context.action==='playlist-add')return input.map(requested=>({requested,playable:requested,method:'direct'}));const items:ResolvedItem[]=[];for(let n=0;n<input.length;n+=5){items.push(...await Promise.all(input.slice(n,n+5).map(async requested=>{if(context.action==='playlist-play'){try{requested=await this.exactFresh(requested,service,signal);}catch(error){if(signal.aborted)throw error;return{requested,unavailable:true};}}const result=await service.resolvePlayback(requested,signal);if(result.kind==='unavailable')return{requested,unavailable:true};if(result.kind==='choices')return{requested,choices:this.publicTracks(result.choices.map(choice=>choice.track),25)};return{requested,playable:publicMusicMetadata(result.playable),method:result.method};})));}return items;}
 private async exactFresh(track:MusicMetadata,service:MusicResolutionService,signal:AbortSignal){const rows=await service.resolveReference(track.reference,1,signal),fresh=rows.tracks.find(row=>row.provider===track.provider&&row.reference===track.reference);if(!fresh||this.identityHash([publicMusicMetadata(fresh)])!==this.identityHash([track]))throw new DomainError('MUSIC_SELECTION_CHANGED','The recording changed or is unavailable. Start a fresh music selection.');return publicMusicMetadata(fresh);}
 private async refreshItems(data:MusicResolutionData,service:MusicResolutionService,signal:AbortSignal){const items:ResolvedItem[]=[];for(let n=0;n<data.items.length;n+=5){items.push(...await Promise.all(data.items.slice(n,n+5).map(async item=>{if(item.unavailable)return item;if(!item.playable)throw new DomainError('MUSIC_SELECTION','Choose every unresolved recording before confirming.');const requested=await this.exactFresh(item.requested,service,signal),playable=item.playable.provider===requested.provider&&item.playable.reference===requested.reference?requested:await this.exactFresh(item.playable,service,signal);if(item.method==='isrc'||item.method==='metadata'){const fresh=await service.resolvePlayback(requested,signal);if(fresh.kind!=='matched'||this.identityHash([publicMusicMetadata(fresh.playable)])!==this.identityHash([playable]))throw new DomainError('MUSIC_SELECTION_CHANGED','The playable match changed. Start a fresh selection rather than substituting a recording.');}return{requested,playable,method:item.method};})));}return{...data,items};}
 private async applyResolved(tx:Prisma.TransactionClient,request:MusicRequest,session:Session<MusicResolutionData>,data:MusicResolutionData,policy:MusicPolicy,confirmed=false):Promise<MusicResolvedOutcome>{const engine=new SessionEngine(new PrismaTransactionSessions(tx));if(data.items.some(item=>item.choices?.length)){const next=await engine.transition<MusicResolutionData>(session.id,['OPEN'],'OPEN',s=>({...s,data:{...data,stage:'matching'}}));return this.resolutionOutcome(next);}const selected=data.items.filter(item=>!item.unavailable);if(!selected.length)throw new DomainError('MUSIC_UNAVAILABLE','No playable recordings remain in this selection.');if(data.items.length>1&&!confirmed){const duplicate=await this.resolutionDuplicates(tx,request,data.context,selected);const next=await engine.transition<MusicResolutionData>(session.id,['OPEN'],'OPEN',s=>({...s,data:{...data,stage:'confirm',reason:duplicate?'duplicates':'batch'}}));return this.resolutionOutcome(next);}const context=data.context;if(context.playlistId){const playlist=await this.playlist(tx,context.playlistId);assertPlaylistOwner(playlist,request.actor);if(playlist.revision!==context.playlistRevision)throw new DomainError('MUSIC_PLAYLIST_STALE','The playlist changed. Open it again.');}
  let result:Prisma.InputJsonObject;try{result=context.action==='playlist-add'?await this.editPlaylistTx(tx,request,context.playlistId!,context.playlistRevision!,{kind:'add',tracks:selected.map(item=>item.requested),maxTracks:context.maxTracks??1000,confirmedDuplicates:confirmed}):await this.enqueueTx(tx,{...request,requestKey:session.id},selected.map((item,n)=>musicEntry(`music-${session.id}-${n}`,request.actor.userId,item.playable!,item.requested,item.method)),policy,confirmed);}catch(error){if(confirmed||!(error instanceof DomainError)||error.code!=='MUSIC_DUPLICATE')throw error;const next=await engine.transition<MusicResolutionData>(session.id,['OPEN'],'OPEN',s=>({...s,data:{...data,stage:'confirm',reason:'duplicates'}}));return this.resolutionOutcome(next);}
  const outcome:MusicResolvedOutcome={kind:'applied',count:selected.length,skippedCount:data.items.length-selected.length,result};await engine.transition<MusicResolutionData>(session.id,['OPEN'],'CLOSED',s=>({...s,data:{...data,result:outcome}}));return outcome;
 }
 /** Search choices are durable, owner-bound public metadata snapshots, never process-local tokens. */
 async openMusicSearch(request:MusicRequest,tracks:readonly MusicMetadata[],context:MusicResolutionContext={}):Promise<MusicResolvedOutcome>{assertMusicLocation(request.actor);const choices=this.publicTracks(tracks,25),data:MusicResolutionData={schemaVersion:2,context,inputHash:requestFingerprint({context,identity:this.identityHash(choices)}),stage:'search',items:[],searchChoices:choices};return this.resolutionAtomic(request.actor.guildId,'music:search:'+request.requestKey,requestFingerprint({request,data}),async tx=>this.resolutionOutcome(await this.createResolution(tx,request,data)));}
 async requestResolvedTracks(request:MusicRequest,tracks:readonly MusicMetadata[],service:MusicResolutionService,policy:MusicPolicy,context:MusicResolutionContext={},signal=AbortSignal.timeout(30000)):Promise<MusicResolvedOutcome>{assertMusicLocation(request.actor);const input=this.publicTracks(tracks),items=await this.prepareItems(input,service,context,signal),data:MusicResolutionData={schemaVersion:2,context,inputHash:requestFingerprint({context,identity:this.identityHash(input)}),stage:'matching',items};return this.resolutionAtomic(request.actor.guildId,'music:resolved:'+request.requestKey,requestFingerprint({request,inputHash:data.inputHash}),async tx=>this.applyResolved(tx,request,await this.createResolution(tx,request,data),data,policy));}
 /** All network resolution finishes before the serializable transaction begins. */
 async chooseResolvedTrack(request:MusicRequest,id:string,version:number,index:number,service:MusicResolutionService,policy:MusicPolicy,signal=AbortSignal.timeout(30000)):Promise<MusicResolvedOutcome>{const snapshot=await this.scopedResolution(this.db,request,id);if(snapshot.state!=='OPEN')return this.resolutionOutcome(snapshot);if(snapshot.version!==version)throw new DomainError('MUSIC_STALE','Use the latest music selection.');if(this.resolutionExpired(snapshot))return this.cancelResolvedSelection(request,id,true);const choices=snapshot.data.stage==='search'?snapshot.data.searchChoices:snapshot.data.items.find(item=>item.choices?.length)?.choices;if(!Number.isSafeInteger(index)||index<0||!choices||index>=choices.length)throw new DomainError('MUSIC_SELECTION','Choose one of these exact recordings.');const chosen=await this.exactFresh(choices[index]!,service,signal);let data:MusicResolutionData;if(snapshot.data.stage==='search')data={...snapshot.data,stage:'matching',items:await this.prepareItems([chosen],service,snapshot.data.context,signal)};else{let replaced=false;data={...snapshot.data,items:snapshot.data.items.map(item=>{if(replaced||!item.choices?.length)return item;replaced=true;return{requested:item.requested,playable:chosen,method:'selected'};})};}if(!data.items.some(item=>item.choices?.length))data=await this.refreshItems(data,service,signal);return this.resolutionAtomic(request.actor.guildId,`music:resolve-pick:${id}:${version}`,requestFingerprint({actor:request.actor.userId,channel:request.actor.textChannelId,id,version,index,inputHash:snapshot.data.inputHash}),async tx=>{const current=await this.scopedResolution(tx,request,id);if(current.version!==version||current.data.inputHash!==snapshot.data.inputHash)throw new DomainError('MUSIC_STALE','The music selection changed.');if(this.resolutionExpired(current)){await new SessionEngine(new PrismaTransactionSessions(tx)).transition(id,['OPEN'],'CANCELLED');return{kind:'expired'};}return this.applyResolved(tx,request,current,data,policy);});}
 async confirmResolvedSelection(request:MusicRequest,id:string,version:number,service:MusicResolutionService,policy:MusicPolicy,signal=AbortSignal.timeout(30000)):Promise<MusicResolvedOutcome>{const snapshot=await this.scopedResolution(this.db,request,id);if(snapshot.state!=='OPEN')return this.resolutionOutcome(snapshot);if(snapshot.version!==version||snapshot.data.stage!=='confirm')throw new DomainError('MUSIC_STALE','Use the latest music confirmation.');if(this.resolutionExpired(snapshot))return this.cancelResolvedSelection(request,id,true);const data=await this.refreshItems(snapshot.data,service,signal);return this.resolutionAtomic(request.actor.guildId,'music:resolved-confirm:'+id,requestFingerprint({actor:request.actor.userId,channel:request.actor.textChannelId,id,inputHash:snapshot.data.inputHash}),async tx=>{const current=await this.scopedResolution(tx,request,id);if(current.version!==version||current.data.inputHash!==snapshot.data.inputHash)throw new DomainError('MUSIC_STALE','The music selection changed.');if(this.resolutionExpired(current)){await new SessionEngine(new PrismaTransactionSessions(tx)).transition(id,['OPEN'],'CANCELLED');return{kind:'expired'};}return this.applyResolved(tx,request,current,data,policy,true);});}
 async cancelResolvedSelection(request:MusicRequest,id:string,expired=false):Promise<MusicResolvedOutcome>{return this.resolutionAtomic(request.actor.guildId,'music:resolved-cancel:'+id,requestFingerprint({actor:request.actor.userId,channel:request.actor.textChannelId,id}),async tx=>{const current=await this.scopedResolution(tx,request,id);if(current.state==='CLOSED')throw new DomainError('MUSIC_CONFIRMATION_CLOSED','This music selection has already been applied.');if(current.state==='OPEN')await new SessionEngine(new PrismaTransactionSessions(tx)).transition(id,['OPEN'],'CANCELLED');return{kind:expired&&this.resolutionExpired(current)?'expired' as const:'cancelled' as const};});}
 async playlistByName(request:MusicRequest,name:string){assertMusicLocation(request.actor);const row=await this.db.playlist.findUnique({where:{guildId_userId_name:{guildId:request.actor.guildId,userId:request.actor.userId,name:name.trim()}}});if(!row)throw new DomainError('MUSIC_PLAYLIST','This saved playlist is unavailable.');return this.readPlaylist(request,row.id);}
 async playlistPage(request:MusicRequest,page=0){assertMusicLocation(request.actor);if(!Number.isSafeInteger(page)||page<0)throw new DomainError('MUSIC_PAGE','Choose a valid playlist page.');const where={guildId:request.actor.guildId,userId:request.actor.userId},total=await this.db.playlist.count({where}),last=Math.max(0,Math.ceil(total/10)-1),current=Math.min(page,last),items=await this.db.playlist.findMany({where,select:{id:true,name:true,revision:true},orderBy:[{name:'asc'},{id:'asc'}],skip:current*10,take:10});return{items,page:current,pages:last+1,total};}
 async historyPage(request:MusicRequest,anchorId:string|null=null,direction:'older'|'newer'='older'){assertMusicLocation(request.actor);const state=await this.read(request.actor.guildId);if(state)assertMusicActor(state.state,request.actor);let range:Prisma.MusicHistoryWhereInput={};if(anchorId){const anchor=await this.db.musicHistory.findFirst({where:{id:anchorId,guildId:request.actor.guildId}});if(!anchor)throw new DomainError('MUSIC_HISTORY','This history page is unavailable. Open the latest history.');const op=direction==='older'?'lt':'gt';range={OR:[{playedAt:{[op]:anchor.playedAt}},{playedAt:anchor.playedAt,id:{[op]:anchor.id}}]};}const order=direction==='newer'?'asc':'desc';const rows=await this.db.musicHistory.findMany({where:{guildId:request.actor.guildId,...range},orderBy:[{playedAt:order},{id:order}],take:11});const items=rows.slice(0,10);if(direction==='newer')items.reverse();return{items,hasOlder:direction==='older'?rows.length>10:Boolean(anchorId),hasNewer:direction==='newer'?rows.length>10:Boolean(anchorId)};}
 private async audit(tx:Prisma.TransactionClient,guildId:string,userId:string,action:string,requestId:string,after:unknown){await new AuditService({write:async e=>{await tx.auditEvent.create({data:{guildId,actorUserId:userId,source:e.source,action,requestId,after:json(after)}});}}).record({guildId,actorUserId:userId,source:'discord',action,requestId,after,createdAt:this.clock()});}
}
