import type {SoloGame} from './domain.js';
import type {SoloView} from './prisma-repository.js';
import {shell,heading,panel,text,ink} from '../../features-events/src/visual.js';
export const SOLO_TITLES:Record<SoloGame,string>={hangman:'Hangman',wordscramble:'Word Scramble',mastermind:'Mastermind',minesweeper:'Minesweeper'};
export const SOLO_RULES:Record<SoloGame,string>={hangman:'Guess one letter at a time. Six incorrect letters ends the round. Repeated guesses do not cost a turn.',wordscramble:'Unscramble the lounge word in six guesses. Submit the whole word. Repeated guesses do not cost a turn.',mastermind:'Find a four-digit code using 1–6. Repeats are allowed. Exact means the correct digit and place; misplaced means a correct digit in another place. Ten guesses.',minesweeper:'Reveal every safe cell. A 4×4 board has 3 mines; 5×5 has 5. The first reveal is safe. Numbers count neighboring mines. Flags toggle and protect cells from reveal; clear a flag to reveal it.'};
export function soloDescription(v:SoloView){const p=v.puzzle,lines=[SOLO_TITLES[p.game],p.outcome==='playing'?'Your puzzle is active.':`Result: ${p.outcome}.${v.reward==='0'?' No payout.':` ${v.paid} Ottomans awarded.`}`];if(p.word)lines.push('Word: '+p.word);if(p.scrambled)lines.push('Scrambled: '+p.scrambled);if(p.game==='hangman')lines.push(`Incorrect: ${p.mistakes}/6. Guessed: ${p.letters.join(', ')||'none'}.`);if(p.game==='mastermind')lines.push(...p.guesses.map((g,n)=>`${g}: ${p.feedback[n]!.exact} exact, ${p.feedback[n]!.misplaced} misplaced.`));if(p.code)lines.push('Code: '+p.code.join(''));if(p.board){const size=p.options.boardSize!;for(let r=0;r<size;r++)lines.push(p.board.slice(r*size,(r+1)*size).map((c,n)=>`${r*size+n+1}:${c}`).join(' '));}return lines.join('\n');}
export function renderSolo(v:SoloView){const p=v.puzzle,closed=p.outcome!=='playing';let body=heading('ANGRIER JORDAN · SOLO',SOLO_TITLES[p.game],closed?p.outcome.toUpperCase():'A quiet challenge in the lounge');body+=panel(18,136,404,380);
 if(p.game==='minesweeper'){const size=p.options.boardSize!,side=54,gap=8,start=(440-size*(side+gap)+gap)/2;for(const[n,cell]of p.board!.entries()){const x=start+n%size*(side+gap),y=162+Math.floor(n/size)*(side+gap);body+=panel(x,y,side,side,cell==='hidden'?ink.teal:ink.slate)+text(x+side/2,y+34,cell==='hidden'?String(n+1):cell==='flag'?'F':cell==='mine'?'X':String(cell),19,cell==='mine'?'#E09C88':ink.gold,'text-anchor="middle"');}}
 else if(p.game==='mastermind'){for(const[g,n]of p.guesses.map((g,n)=>[g,n] as const))body+=text(32,169+n*29,g.split('').join(' '),20)+text(180,169+n*29,`${p.feedback[n]!.exact} exact · ${p.feedback[n]!.misplaced} misplaced`,13,ink.muted);if(!p.guesses.length)body+=text(32,175,'Four digits · six choices · ten guesses',17);if(p.code)body+=text(32,492,'Code: '+p.code.join(' '),20,ink.gold);}
 else{if(p.scrambled)body+=text(32,188,p.scrambled.toUpperCase(),25,ink.gold,'font-family="Space Grotesk"');body+=text(32,p.scrambled?238:198,p.word!.split('').join(' '),p.word!.length>10?17:25,ink.white,'font-family="Space Grotesk"');body+=text(32,295,p.game==='hangman'?`${p.mistakes} / 6 incorrect letters`:`${p.guesses.length} / 6 guesses`,17,ink.muted);if(p.game==='hangman'){body+=text(32,340,p.letters.slice(0,13).join(' · ').toUpperCase(),15)+text(32,373,p.letters.slice(13).join(' · ').toUpperCase(),15);}else for(const[n,g]of p.guesses.entries())body+=text(32,329+n*27,g,16);}
 body+=panel(18,536,404,87,ink.gold)+text(32,566,closed?v.reward==='0'?'Round complete · just for fun':`${v.paid} Ottomans awarded`:'Use the controls below to play',20,closed?ink.emerald:ink.white,'font-family="Space Grotesk"')+text(32,598,closed?'Play Again creates a new puzzle.':v.reward==='0'?'No entry fee · no payout':'No entry fee · small rewards · shared daily cap',13,ink.muted);return shell(643,body);
}
