import {randomUUID} from 'node:crypto';
import {DomainError,TimerEngine,type Session} from '../../core/src/index.js';
import {PrismaWagerEscrow} from '../../database/src/wager-escrow.js';
import {PrismaAuditSink} from '../../database/src/prisma-adapters.js';
import {PrismaTransactionSessions} from '../../database/src/transaction-sessions.js';
import {FamilyRelationships} from './relationships.js';
import {json,type Tx} from './store.js';
import {FAMILY_ITEMS,validateAuctionHours,positiveMoney,type FamilyContext,type FamilyMember,type FamilyData,type EstateAsset} from './domain.js';

export class FamilyAuctions extends FamilyRelationships {
 async createAuction(c:FamilyContext,seller:FamilyMember,type:'spouse'|'child',hours:number,reserve=0n){return this.run(c,'auction_create',{type,hours,reserve},async tx=>{if(!['spouse','child'].includes(type)||seller.userId!==c.userId)throw new DomainError('FAMILY_AUCTION_TYPE','Only self-auctions as a spouse or child are available.');await this.allowed(c.guildId,c.userId);await this.cooldown(tx,c.guildId,c.userId);validateAuctionHours(hours,this.policy);if(reserve<0n)throw new DomainError('FAMILY_RESERVE','A reserve cannot be negative.');if(await tx.familyAuction.findFirst({where:{guildId:c.guildId,sellerUserId:c.userId,status:'OPEN',auctionType:{in:['spouse','child']}}}))throw new DomainError('FAMILY_AUCTION_ACTIVE','Your self-auction is already open.');if(type==='child'&&await tx.adoption.findFirst({where:{guildId:c.guildId,childUserId:c.userId,status:{in:['ACTIVE','PENDING']}}}))throw new DomainError('FAMILY_CHILD_PAIR','An existing or pending parent pair must resolve first.');const due=TimerEngine.create(this.clock(),hours*3600).expiresAt,s=await this.createSession(tx,c,'auction',{kind:'auction',auctionType:type,members:[seller],reserve:reserve.toString(),result:'Sealed bidding open'},due);await tx.familyAuction.create({data:{id:s.id,guildId:c.guildId,sellerUserId:c.userId,auctionType:type,reserveAmount:reserve,status:'OPEN',endsAt:due,createdAt:this.clock()}});await this.schedule(tx,s,'auction_close',due);return{sessionId:s.id,jobId:await this.publishIntent(tx,s)};});}
 private async availableItem(tx:Tx,guildId:string,userId:string,itemId:string){const item=await tx.catalogItem.findUnique({where:{id:itemId}}),row=await tx.inventoryEntry.findUnique({where:{guildId_userId_itemId:{guildId,userId,itemId}}});return Boolean(item?.enabled&&row&&!row.locked&&row.quantity>0&&!await tx.inventoryCategoryLock.findUnique({where:{guildId_userId_category:{guildId,userId,category:item.type}}}));}
 protected async validBid(tx:Tx,s:Session<FamilyData>,userId:string){if(userId===s.ownerUserId)throw new DomainError('FAMILY_SELF_BID','You cannot bid on your own auction.');await this.allowed(s.guildId,userId);if(s.data.auctionType==='estate')return;await this.allowed(s.guildId,s.ownerUserId!);await this.cooldown(tx,s.guildId,userId,s.ownerUserId!);if(s.data.auctionType==='spouse'){const e=await this.marriageEligibility(tx,s.guildId,userId,s.ownerUserId!);if(!await this.availableItem(tx,s.guildId,userId,FAMILY_ITEMS.ring)||e.needsBlessing&&!await this.availableItem(tx,s.guildId,userId,FAMILY_ITEMS.blessing))throw new DomainError('FAMILY_ITEM','A Ring and any required Blessing must remain available for auction finalization.');}else await this.adoptionPair(tx,s.guildId,userId,s.ownerUserId!);}
 async bid(c:FamilyContext,id:string,bidder:FamilyMember,amount:bigint){positiveMoney(amount);return this.run(c,'auction_bid',{id,amount},async(tx,ledger)=>{const s=await this.session(tx,c,id);if(s.type!=='family_auction'||s.state!=='OPEN'||!s.expiresAt||s.expiresAt<=this.clock())throw new DomainError('FAMILY_AUCTION_CLOSED','This auction has closed.');if(bidder.userId!==c.userId)throw new DomainError('FAMILY_ACTOR','Bid belongs to its invoker.');await this.validBid(tx,s,c.userId);const old=await tx.familyAuctionBid.findFirst({where:{auctionId:id,bidderUserId:c.userId}});if(old&&amount<=old.amount)throw new DomainError('FAMILY_BID_INCREASE','A sealed bid may only increase; it cannot be withdrawn.');const escrow=await new PrismaWagerEscrow(tx,ledger).reserve({guildId:c.guildId,userId:c.userId,amount:amount-(old?.amount??0n),referenceType:'family_bid',referenceId:id+':'+c.userId,key:'family:bid:'+c.requestKey});if(old)await tx.familyAuctionBid.update({where:{id:old.id},data:{amount,escrowId:escrow.id,createdAt:this.clock()}});else await tx.familyAuctionBid.create({data:{auctionId:id,bidderUserId:c.userId,amount,escrowId:escrow.id,createdAt:this.clock()}});await tx.gameParticipant.upsert({where:{sessionId_userId:{sessionId:id,userId:c.userId}},create:{sessionId:id,userId:c.userId,role:'bidder',data:json(bidder)},update:{data:json(bidder)}});await this.save(tx,s,s.data);return{sessionId:id,amount:amount.toString()};});}
 protected async auctionRelationship(tx:Tx,s:Session<FamilyData>,winnerId:string){const p=await tx.gameParticipant.findUniqueOrThrow({where:{sessionId_userId:{sessionId:s.id,userId:winnerId}}}),member=p.data as unknown as FamilyMember,c:FamilyContext={guildId:s.guildId,channelId:s.channelId,userId:winnerId,requestKey:'auction:'+s.id};if(s.data.auctionType==='spouse'){const id=randomUUID(),target=s.data.members![0]!;await tx.marriage.create({data:{id,guildId:s.guildId,userA:winnerId,userB:s.ownerUserId!,status:'PENDING',proposedAt:this.clock()}});await this.reserveItem(tx,s.guildId,winnerId,FAMILY_ITEMS.ring,id);const draft=await this.createSession(tx,c,'marriage',{kind:'marriage',members:[member,target],targetId:target.userId,proposalItem:FAMILY_ITEMS.ring,result:'Auction marriage'},undefined,'DRAFT',id),saved=await this.activateMarriage(tx,draft);await this.publishIntent(tx,saved);}else if(s.data.auctionType==='child'){const pair=await this.adoptionPair(tx,s.guildId,winnerId,s.ownerUserId!),id=randomUUID();await tx.adoption.create({data:{id,guildId:s.guildId,parentPairKey:pair.id,childUserId:s.ownerUserId!,status:'ACTIVE',createdAt:this.clock()}});await this.event(tx,s.guildId,winnerId,s.ownerUserId!);await this.largest(tx,s.guildId);}}
 protected async grantEstateAsset(tx:Tx,guildId:string,winnerId:string,asset:EstateAsset){await tx.member.upsert({where:{guildId_userId:{guildId,userId:winnerId}},create:{guildId,userId:winnerId},update:{}});if(asset.kind==='stack'){await tx.inventoryEntry.upsert({where:{guildId_userId_itemId:{guildId,userId:winnerId,itemId:asset.itemId}},create:{guildId,userId:winnerId,itemId:asset.itemId,quantity:asset.quantity,locked:asset.locked},update:{quantity:{increment:asset.quantity}}});await tx.collectionDiscovery.upsert({where:{guildId_userId_itemId:{guildId,userId:winnerId,itemId:asset.itemId}},create:{guildId,userId:winnerId,itemId:asset.itemId},update:{}});}else if(asset.kind==='tool')await tx.toolInstance.update({where:{id:asset.id},data:{userId:winnerId,equipped:false}});else await tx.craftedChair.update({where:{id:asset.id},data:{userId:winnerId}});}
 async closeAuction(guildId:string,id:string){return this.atomic.run(guildId,'family:auction_close:'+id,id,async(tx,ledger)=>{const s=await new PrismaTransactionSessions(tx).get<FamilyData>(id);if(!s||s.guildId!==guildId||s.type!=='family_auction')throw new DomainError('FAMILY_SESSION','Auction unavailable.');if(s.state!=='OPEN')return{sessionId:id};if(!s.expiresAt||s.expiresAt>this.clock())throw new DomainError('NOT_DUE','Auction remains open.');const bids=await tx.familyAuctionBid.findMany({where:{auctionId:id},orderBy:[{amount:'desc'},{createdAt:'asc'},{id:'asc'}]}),reserve=BigInt(s.data.reserve??'0');let winner:typeof bids[number]|undefined;for(const candidate of bids){if(candidate.amount<reserve)continue;try{await this.validBid(tx,s,candidate.bidderUserId);winner=candidate;break;}catch(error){if(!(error instanceof DomainError))throw error;}}
  const escrow=new PrismaWagerEscrow(tx,ledger);for(const row of bids){const referenceId=id+':'+row.bidderUserId;if(row.id===winner?.id){if(s.data.auctionType==='estate'){if(!s.data.asset)throw new DomainError('ESTATE_ASSET','Auction asset is missing.');await this.grantEstateAsset(tx,guildId,row.bidderUserId,s.data.asset);await escrow.settle(guildId,'family_bid',referenceId,new Map(),'family:auction:'+id+':winner');}else{await this.auctionRelationship(tx,s,row.bidderUserId);await escrow.settle(guildId,'family_bid',referenceId,new Map([[s.ownerUserId!,row.amount]]),'family:auction:'+id+':winner');}}else await escrow.refund(guildId,'family_bid',referenceId,'family:auction:'+id+':refund:'+row.bidderUserId);}
  await tx.familyAuction.update({where:{id},data:{status:winner?'SETTLED':'CLOSED'}});await this.save(tx,s,{...s.data,...(winner?{winnerId:winner.bidderUserId,amount:winner.amount.toString()}:{}),result:winner?'Auction finalized':'No valid reserve-meeting bid; funds refunded.'},'CLOSED');await new PrismaAuditSink({auditEvent:tx.auditEvent}).write({guildId,source:'scheduler',action:'family.auction_closed',targetType:'family_auction',targetId:id,after:{winnerId:winner?.bidderUserId??null,amount:winner?.amount.toString()??null},requestId:'family:auction:'+id,createdAt:this.clock()});return{sessionId:id};
 });}
 protected async estateAuction(tx:Tx,c:FamilyContext,asset:EstateAsset,estateId:string){const due=TimerEngine.create(this.clock(),24*3600).expiresAt,s=await this.createSession(tx,c,'auction',{kind:'auction',auctionType:'estate',asset,reserve:'0',departedId:c.userId,result:'Sealed estate-item bidding open'},due);await tx.familyAuction.create({data:{id:s.id,guildId:c.guildId,sellerUserId:c.userId,auctionType:'estate',reserveAmount:0n,status:'OPEN',endsAt:due,createdAt:this.clock()}});if(asset.kind==='tool')await tx.toolInstance.update({where:{id:asset.id},data:{userId:'estate:'+estateId,equipped:false}});if(asset.kind==='chair')await tx.craftedChair.update({where:{id:asset.id},data:{userId:'estate:'+estateId}});await this.schedule(tx,s,'auction_close',due);await this.publishIntent(tx,s);return s.id;}
}
