import {readFileSync} from 'node:fs';
import {wrapText} from '../../renderer/src/text-layout.js';
import type {FamilyView} from './prisma-repository.js';
import type {ActiveMarriage,ActiveAdoption,FamilyMember} from './domain.js';
const C={gold:'#F3D49B',plum:'#BC9CEB',rose:'#E7A9BF',mint:'#87D8CB',white:'#F1EEF5',muted:'#CDC6DB'};
const esc=(s:string)=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const assets=new Map<string,string>();
function asset(path:string){if(!assets.has(path))assets.set(path,'data:image/png;base64,'+readFileSync(new URL('../../../production/'+path,import.meta.url)).toString('base64'));return assets.get(path)!;}
const text=(x:number,y:number,s:string,size=28,color:string=C.white,heading=false)=>`<text x="${x}" y="${y}" text-anchor="middle" font-family="${heading?'Space Grotesk':'Inter'}" font-size="${size}" font-weight="700" fill="${color}">${esc(s)}</text>`;
function block(s:string,x:number,y:number,width=1020,size=28,color:string=C.white,heading=false){const lines=wrapText(s,width,size),step=Math.ceil(size*1.4);return{svg:lines.map((line,n)=>text(x,y+n*step,line,size,color,heading)).join(''),height:lines.length*step};}
const panel=(x:number,y:number,w:number,h:number,color:string=C.plum)=>`<rect x="${x}" y="${y}" width="${w}" height="${h}" rx="24" fill="url(#glass)" stroke="${color}" stroke-width="2"/><rect x="${x+8}" y="${y+8}" width="${w-16}" height="${h-16}" rx="18" fill="none" stroke="${color}" opacity=".22"/><path d="M${x+18} ${y+54}V${y+18}H${x+65}M${x+w-65} ${y+h-18}H${x+w-18}V${y+h-54}" fill="none" stroke="url(#brass)" stroke-width="3"/>`;
function flourish(x:number,y:number){return `<g transform="translate(${x} ${y})" stroke="url(#brass)" fill="none" stroke-width="2"><path d="M-170 0H-35Q-6-35 0 0Q6-35 35 0H170M-70 0Q-50-30-30-10M70 0Q50-30 30-10M-35 0Q-10 24 0 0Q10 24 35 0"/><path d="M0-12 10 0 0 12-10 0Z" fill="${C.plum}"/></g>`;}
function frame(body:string,bottom:number){const height=bottom+76;return `<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="${height}" viewBox="0 0 1200 ${height}"><defs><linearGradient id="glass" x2="0" y2="1"><stop stop-color="#302943" stop-opacity=".97"/><stop offset="1" stop-color="#0C1C29" stop-opacity=".98"/></linearGradient><linearGradient id="brass"><stop stop-color="#8B633F"/><stop offset=".45" stop-color="#FFE4B2"/><stop offset="1" stop-color="#B47C86"/></linearGradient><radialGradient id="glow"><stop stop-color="#C2A1E8" stop-opacity=".28"/><stop offset="1" stop-color="#071320" stop-opacity="0"/></radialGradient></defs><image href="${asset('event_art/v5/lounge-stage-runtime.png')}" width="1200" height="${height}" preserveAspectRatio="xMidYMid slice"/><rect width="1200" height="${height}" fill="#100E21" opacity=".58"/><ellipse cx="600" cy="300" rx="590" ry="380" fill="url(#glow)"/>${body}${flourish(600,bottom+8)}${text(600,bottom+53,'SIT. PLAY. BELONG.',21,C.gold)}<rect x="5" y="5" width="1190" height="${height-10}" rx="28" stroke="${C.plum}" stroke-width="3" fill="none"/><rect x="16" y="16" width="1168" height="${height-32}" rx="20" stroke="url(#brass)" stroke-width="3" fill="none"/></svg>`;}
function header(title:string,sub:string){const a=block(title,600,102,1080,44,C.gold,true),b=block(sub,600,112+a.height,1060,25,C.rose);return{svg:text(600,45,'ANGRIER JORDAN · THE FAMILY LOUNGE',22,C.plum)+a.svg+b.svg,height:132+a.height+b.height};}
function portrait(m:FamilyMember,x:number,y:number,size:number,key:string){const safe=/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/.test(m.avatar)&&m.avatar.length<1_400_000;return `<defs><clipPath id="p${key}"><rect x="${x-size/2+7}" y="${y+7}" width="${size-14}" height="${size-14}" rx="25"/></clipPath></defs><rect x="${x-size/2-6}" y="${y-6}" width="${size+12}" height="${size+12}" rx="34" fill="#0A1524" stroke="${C.plum}" stroke-width="2"/><rect x="${x-size/2}" y="${y}" width="${size}" height="${size}" rx="30" fill="#252137" stroke="url(#brass)" stroke-width="4"/><image href="${safe?m.avatar:asset('event_art/v3/race_chair_1.png')}" x="${x-size/2+7}" y="${y+7}" width="${size-14}" height="${size-14}" preserveAspectRatio="${safe?'xMidYMid slice':'xMidYMid meet'}" clip-path="url(#p${key})"/>`;}
const rings=(x:number,y:number)=>`<g transform="translate(${x} ${y})" fill="none" stroke="url(#brass)" stroke-width="9"><ellipse cx="-18" cy="10" rx="32" ry="42" transform="rotate(-25)"/><ellipse cx="18" cy="10" rx="32" ry="42" transform="rotate(25)"/><path d="M-20-49 0-65 20-49 0-29Z" fill="${C.plum}" stroke-width="3"/></g>`;
const money=(n:string|undefined)=>{try{return BigInt(n??'0').toLocaleString('en-US');}catch{return'0';}};
const itemName=(id:string)=>({'family.ring':'Ring','family.wedding_sack':'Wedding Sack','family.blessing':'Blessing of Angrier Jordan'}[id]??'Estate item');
const displayName=(v:FamilyView,id?:string)=>v.data.members?.find(m=>m.userId===id)?.name??'Member';
function info(body:string,y:number,label:string,copy:string,color:string=C.plum){const h=block(label,600,y+43,1020,27,color,true),b=block(copy,600,y+54+h.height,1020,27);return{body:body+panel(35,y,1130,h.height+b.height+85,color)+h.svg+b.svg,y:y+h.height+b.height+105};}
export function renderFamilyNotice(title:string,message:string,member?:FamilyMember){const h=header(title,'YOUR PRIVATE FAMILY WINDOW');let body=h.svg,y=h.height;if(member){const name=block(member.name,600,y+203,1000,32),height=235+name.height;body+=panel(35,y,1130,height)+portrait(member,600,y+22,145,'notice')+name.svg;y+=height+20;}const b=info(body,y,'Family record',message);return frame(b.body,b.y);}
export function renderPremiumFamily(v:FamilyView){const d=v.data,married=v.type==='family_marriage'&&d.compatibility!==undefined,pending=v.state==='DRAFT',title=married?'Just Married':v.type==='family_marriage'?'A Seat Beside You':v.type==='family_adoption'?'A New Family Branch':v.type==='family_divorce'?'Separate Seats':v.type==='family_auction'?'The Sealed Auction':v.type==='family_estate'?(d.executed?'A Legacy Passed On':v.state==='CANCELLED'?'Welcome Home':'An Estate on Hold'):'The Family Story',subtitle=v.type==='family_estate'&&d.executed&&d.departedName?`In memory of ${d.departedName}`:d.result??'A family event in the Chairs';
 const head=header(title,subtitle);let body=head.svg,y=head.height;
 const members=d.members??[];
 for(let start=0;start<members.length;start+=2){const row=members.slice(start,start+2),xs=row.length===1?[600]:[300,900],names=row.map((m,n)=>block(m.name,xs[n]!,y+242,row.length===1?940:460,33,C.white)),h=Math.max(290,...names.map(n=>n.height+264));body+=panel(35,y,1130,h,married?C.gold:C.plum);if(married&&start===0){body+=`<path d="M58 ${y+h-25}V${y+85}Q600 ${y-65}1142 ${y+85}V${y+h-25}" stroke="url(#brass)" stroke-width="4" fill="none"/><path d="M76 ${y+h-30}V${y+97}Q600 ${y-40}1124 ${y+97}V${y+h-30}" stroke="${C.rose}" opacity=".5" stroke-width="2" fill="none"/><ellipse cx="600" cy="${y+120}" rx="165" ry="120" fill="url(#glow)"/>`+rings(600,y+130)+flourish(600,y+h-35);for(let n=0;n<12;n++){const x=95+n*92,cy=y+28+Math.abs(5.5-n)*5;body+=`<circle cx="${x}" cy="${cy}" r="4" fill="${C.gold}" opacity=".8"/><path d="M${x} ${cy-14}V${cy+14}M${x-9} ${cy}H${x+9}" stroke="${C.gold}" opacity=".28"/>`;}}row.forEach((m,n)=>body+=portrait(m,xs[n]!,y+27,178,String(start+n))+names[n]!.svg);y+=h+22;}
 const section=(label:string,copy:string,color?:string)=>{const next=info(body,y,label,copy,color);body=next.body;y=next.y;};
 if(v.type==='family_marriage'){
  if(married){body+=panel(35,y,1130,145,C.rose)+text(300,y+50,'Compatibility '+d.compatibility+'%',33,C.gold)+text(900,y+50,'Success chance '+d.success+'%',33,C.rose)+text(600,y+105,'Married '+new Date(d.marriedAt??v.createdAt).toISOString().slice(0,10)+(d.spouseCounts?' · Active spouses: '+Object.values(d.spouseCounts).join(' / '):''),26);y+=165;
   const votes=d.voteResult??{up:0,down:0,total:0,approval:0};body+=panel(35,y,1130,205,C.mint)+text(600,y+40,v.state==='OPEN'?'COMMUNITY BLESSING · VOTING OPEN':'COMMUNITY BLESSING · FINAL',27,C.mint,true)+text(300,y+94,'Approve '+votes.up,33)+text(900,y+94,'Disapprove '+votes.down,33)+`<rect x="110" y="${y+116}" width="980" height="15" rx="7" fill="#101321"/><rect x="110" y="${y+116}" width="${980*Math.max(0,Math.min(100,votes.approval))/100}" height="15" rx="7" fill="${C.mint}"/>`+text(600,y+174,'Approval '+votes.approval+'% · '+votes.total+' votes',27,C.gold);y+=225;
   body+=text(600,y+15,v.state==='OPEN'?'Anonymous · Editable · Spouses cannot vote':'Voting closed · Relationship saved',24,C.mint);y+=40;
   if(d.firstChildBonus)section('First child slot unlocked','Community approval unlocked the first child slot.',C.gold);
  }
  section(itemName(d.proposalItem??'family.ring'),(d.itemEscrow?.map(i=>i.quantity+' × '+itemName(i.itemId)+': '+(i.state==='RESERVED'?'reserved until the proposal resolves':i.state==='REFUNDED'?'returned to inventory':i.state==='SETTLED'?'consumed by the marriage':'settlement pending')).join('\n')||'Required item state is recorded with this event.')+(pending?'\nOnly the proposed member may Accept or Decline.':married?'\n'+(d.blessingConsumed?'The Blessing of Angrier Jordan was consumed.':'No Blessing was required.'):'\nNo marriage was created.'),C.gold);
 }else if(v.type==='family_adoption')section(pending?'Accept your new family seat':v.state==='CLOSED'?'Adoption accepted':'Adoption not completed',pending?'Only the proposed child may accept. Both married parents will be linked.':v.state==='CLOSED'?'Both parent links are active. Open View Family to explore the branch.':'No adoption link was created.',C.mint);
 else if(v.type==='family_divorce')section(money(d.amount)+' Ottomans transferred',displayName(v,d.payerId)+' paid '+displayName(v,d.receiverId)+'.\nItems remain with their owners. The same pair must observe the remarriage waiting period.',C.rose);
 else if(v.type==='family_auction'){
  const open=v.state==='OPEN';section(d.auctionType==='estate'?'Estate item auction':d.auctionType==='child'?'Adopted-child self-auction':'Spouse self-auction',open?'Reserve: '+money(d.reserve)+' Ottomans\nBids are sealed. Place or increase your TOTAL bid below.\nBids cannot decrease or be withdrawn.':d.winnerId?'Winner: '+displayName(v,d.winnerId)+'\nWinning bid: '+money(d.amount)+' Ottomans\n'+(d.auctionType==='estate'?'The winner received the item.':'Proceeds went to the member auctioned.')+' Other bids refunded.':'No valid winning bid. Reserved funds refunded.',C.gold);
  if(d.asset)section('Estate asset',d.asset.kind==='stack'?d.asset.quantity+' × '+itemName(d.asset.itemId):'Individual '+d.asset.kind);
 }else if(v.type==='family_estate')section(d.executed?'Estate execution is final':'No estate transfer executed',!d.executed?v.state==='CANCELLED'?'The member returned; the pending estate was canceled.':'The departure grace and existing reserved-asset settlements must finish first.':(d.heirId?'Beneficiary: '+displayName(v,d.heirId):'No eligible heir remained.')+'\n'+money(d.amount)+' Ottomans '+(d.heirId?'transferred.':'removed from circulation.')+'\n'+(d.assetsTransferred??0)+' eligible inventory entries '+(d.heirId?'transferred.':'assigned to estate auctions.')+(d.auctionIds?.length?'\n'+d.auctionIds.length+' estate-item auctions opened.':'')+'\nA later return does not restore this estate.',C.gold);
 else section('Active family updated',d.result??'The active family tree has changed.',C.rose);
 if(v.expiresAt&&['DRAFT','OPEN'].includes(v.state)){body+=text(600,y+20,'Window closes · '+new Date(v.expiresAt).toISOString().slice(0,16).replace('T',' ')+' UTC',24,C.muted);y+=48;}
 return frame(body,y);
}
export interface FamilyTreeInput {members:string[];marriages:ActiveMarriage[];adoptions:ActiveAdoption[];}
export interface FamilyBranch {parents:string[];children:string[];married:boolean;}
/** A page per parent/spouse pair preserves multi-spouse and multi-generation links without crossing edges. */
export function familyBranches(tree:FamilyTreeInput,focus:string):FamilyBranch[]{const groups=new Map<string,FamilyBranch>();for(const m of tree.marriages)groups.set(m.id,{parents:[m.userA,m.userB],children:[],married:true});for(const a of tree.adoptions){if(!groups.has(a.parentPairKey))groups.set(a.parentPairKey,{parents:[...a.parents],children:[],married:false});groups.get(a.parentPairKey)!.children.push(a.childUserId);}const branches=[...groups.values()].sort((a,b)=>Number(b.parents.includes(focus)||b.children.includes(focus))-Number(a.parents.includes(focus)||a.children.includes(focus)));return branches.length?branches.flatMap(b=>b.children.length>3?Array.from({length:Math.ceil(b.children.length/3)},(_,n)=>({...b,children:b.children.slice(n*3,n*3+3)})):[b]):[{parents:[focus],children:[],married:false}];}
export function renderFamilyTree(input:{branch:FamilyBranch;members:FamilyMember[];focus:string;page:number;pages:number;total:number;perk?:string}){
 const lookup=(id:string)=>input.members.find(m=>m.userId===id)??{userId:id,name:'Unavailable member',avatar:''},head=header('The Family Tree',input.total+' members · Branch '+(input.page+1)+' / '+input.pages),b=input.branch;let body=head.svg,y=head.height;
 if(input.perk){const p=info(body,y,'Largest Family · '+input.perk,'A current family record distinction.',input.perk.startsWith('Emerald')?C.mint:input.perk.startsWith('Brass')?C.gold:C.plum);body=p.body;y=p.y;}
 const node=(id:string,x:number,top:number,width:number,key:string)=>{const m=lookup(id),name=block(m.name,x,top+188,width-35,29),height=name.height+238;return{svg:panel(x-width/2,top,width,height,id===input.focus?C.gold:C.plum)+portrait(m,x,top+22,132,key)+name.svg+text(x,top+height-23,id===input.focus?'YOU ARE VIEWING':'FAMILY MEMBER',20,id===input.focus?C.gold:C.muted),height};};
 const parents=b.parents.map((id,n)=>node(id,b.parents.length===1?600:300+n*600,y,420,'parent'+n)),parentH=Math.max(...parents.map(p=>p.height));
 if(b.parents.length===2){body+=`<path d="M510 ${y+125}H690" stroke="${b.married?C.rose:C.mint}" stroke-width="5" ${b.married?'':'stroke-dasharray="9 7"'}/>`+text(600,y+98,b.married?'SPOUSES':'PARENTS',23,b.married?C.rose:C.mint);}
 body+=parents.map(p=>p.svg).join('');y+=parentH;
 if(b.children.length){body+=`<path d="M600 ${y-parentH+125}V${y+120}" stroke="${C.mint}" stroke-width="4" fill="none"/>`+`<rect x="370" y="${y+62}" width="460" height="45" rx="14" fill="#161D2F"/>`+text(600,y+92,'CHILDREN SHOWN · '+b.children.length,27,C.mint,true);y+=120;
  for(let start=0;start<b.children.length;start+=3){const row=b.children.slice(start,start+3),xs=row.map((_,n)=>600+(n-(row.length-1)/2)*380),nodes=row.map((id,n)=>node(id,xs[n]!,y+30,350,'child'+(start+n)));body+=`<path d="M${xs[0]} ${y}H${xs.at(-1)}${xs.map(x=>'M'+x+' '+y+'V'+(y+30)).join('')}" fill="none" stroke="${C.mint}" stroke-width="4"/>`+nodes.map(n=>n.svg).join('');y+=Math.max(...nodes.map(n=>n.height))+65;}
 }else{y+=28;const p=info(body,y,b.parents.length===1?'Your story starts here':'Your shared branch',b.parents.length===1?'No active family links yet. Your portrait is ready for the next chapter.':'No active children in this branch.',C.rose);body=p.body;y=p.y;}
 const legend=info(body,y+12,'Reading the tree','Rose link: active spouses · Mint link: parents to child\n'+(input.pages>1?'Browse branches below to see every active relationship.':'Only active family relationships are shown.'),C.plum);return frame(legend.body,legend.y);
}
