import {DomainError,TimerEngine,spendableWallet} from '../../core/src/index.js';
import {PrismaTransactionSessions} from '../../database/src/transaction-sessions.js';
import {assertItemEscrow} from '../../database/src/escrow-contract.js';
import {PrismaWagerEscrow} from '../../database/src/wager-escrow.js';
import {PrismaAuditSink} from '../../database/src/prisma-adapters.js';
import {FamilyAuctions} from './auctions.js';
import {marriageVoting,type FamilyContext,type FamilyData,type EstateAsset} from './domain.js';
import type {Tx} from './store.js';

export class PrismaFamilyRepository extends FamilyAuctions {
 async setWill(c:FamilyContext,beneficiaryId:string){return this.run(c,'will',{beneficiaryId},async tx=>{if(beneficiaryId===c.userId)throw new DomainError('FAMILY_SELF','Choose another eligible beneficiary.');await this.allowed(c.guildId,c.userId);if(!await this.eligible(c.guildId,beneficiaryId))throw new DomainError('FAMILY_BENEFICIARY','Choose an eligible current beneficiary.');await tx.will.upsert({where:{guildId_userId:{guildId:c.guildId,userId:c.userId}},create:{guildId:c.guildId,userId:c.userId,beneficiaryUserId:beneficiaryId},update:{beneficiaryUserId:beneficiaryId}});return{beneficiaryId};});}
 async depart(c:FamilyContext,reason:'leave'|'kick'|'ban'|'unavailable',departedName?:string){return this.run(c,'depart',{reason},async tx=>{const prior=await tx.gameSession.findFirst({where:{guildId:c.guildId,ownerUserId:c.userId,type:'family_estate',state:{in:['OPEN','LOCKED','SETTLING']}}});if(prior)return{sessionId:prior.id};await tx.member.upsert({where:{guildId_userId:{guildId:c.guildId,userId:c.userId}},create:{guildId:c.guildId,userId:c.userId},update:{}});const due=TimerEngine.create(this.clock(),this.policy.graceHours*3600).expiresAt,name=departedName?.trim().slice(0,100),s=await this.createSession(tx,c,'estate',{kind:'estate',departedId:c.userId,...(name?{departedName:name}:{}),departedAt:this.clock().toISOString(),graceEndsAt:due.toISOString(),reason,result:'Estate grace period'},due);await this.schedule(tx,s,'estate_execute',due);return{sessionId:s.id};});}
 async rejoin(c:FamilyContext,joinedAt?:Date,currentPresence=false){
  if(joinedAt&&!Number.isFinite(joinedAt.getTime()))throw new DomainError('FAMILY_JOIN_TIME','A trusted membership join timestamp is required.');
  return this.run(c,'rejoin',joinedAt?{joinedAt:joinedAt.toISOString(),currentPresence}:{},async tx=>{
   const executed=await tx.gameSession.findFirst({where:{guildId:c.guildId,ownerUserId:c.userId,type:'family_estate',state:'CLOSED',data:{path:['executed'],equals:true}}});
   if(joinedAt){
    const prior=await tx.memberPresenceState.findUnique({where:{guildId_userId:{guildId:c.guildId,userId:c.userId}}});
    // A replayed prior membership cannot clear a later departure. New authoritative
    // membership epochs remain valid even when an older leave was processed late.
    if(prior?.joinedAt&&(joinedAt<prior.joinedAt||(!currentPresence&&joinedAt.getTime()===prior.joinedAt.getTime()&&prior.leftAt&&prior.leftAt>=joinedAt)))return{canceled:0,executedPreviously:Boolean(executed),staleReturn:true};
    await tx.member.upsert({where:{guildId_userId:{guildId:c.guildId,userId:c.userId}},create:{guildId:c.guildId,userId:c.userId},update:{}});
    await tx.memberPresenceState.upsert({where:{guildId_userId:{guildId:c.guildId,userId:c.userId}},create:{guildId:c.guildId,userId:c.userId,joinedAt},update:{joinedAt,leftAt:null}});
   }
   const rows=await tx.gameSession.findMany({where:{guildId:c.guildId,ownerUserId:c.userId,type:'family_estate',state:{in:['OPEN','LOCKED','SETTLING']},...(joinedAt&&!currentPresence?{createdAt:{lte:joinedAt}}:{})}});
   for(const row of rows){const session=await new PrismaTransactionSessions(tx).get<FamilyData>(row.id);if(session)await this.save(tx,session,{...session.data,result:'Estate canceled after return'},'CANCELLED');}
   return{canceled:rows.length,executedPreviously:Boolean(executed),...(joinedAt?{staleReturn:false}:{})};
  });
 }
 protected async heir(tx:Tx,guildId:string,userId:string){const will=await tx.will.findUnique({where:{guildId_userId:{guildId,userId}}});if(will&&will.beneficiaryUserId!==userId&&await this.eligible(guildId,will.beneficiaryUserId))return will.beneficiaryUserId;const spouses=await tx.marriage.findMany({where:{guildId,status:'ACTIVE',OR:[{userA:userId},{userB:userId}]}}),parents=await tx.marriage.findMany({where:{guildId,OR:[{userA:userId},{userB:userId}]}}),children=await tx.adoption.findMany({where:{guildId,status:'ACTIVE',parentPairKey:{in:parents.map(m=>m.id)}}}),pool=[...new Set([...spouses.map(m=>m.userA===userId?m.userB:m.userA),...children.map(a=>a.childUserId)])].filter(id=>id!==userId),eligible=[];for(const candidate of pool)if(await this.eligible(guildId,candidate))eligible.push(candidate);return eligible.length?eligible[this.rng(eligible.length)]!:null;}
 protected async assets(tx:Tx,guildId:string,userId:string){const[stacks,tools,chairs,catalog]=await Promise.all([tx.inventoryEntry.findMany({where:{guildId,userId,quantity:{gt:0}}}),tx.toolInstance.findMany({where:{guildId,userId}}),tx.craftedChair.findMany({where:{guildId,userId}}),tx.catalogItem.findMany()]);const inheritable=(itemId:string)=>{const item=catalog.find(i=>i.id===itemId);return Boolean(item?.enabled&&item.giftable&&(item.metadata as {inheritable?:boolean}|null)?.inheritable!==false);};const assets:EstateAsset[]=[...stacks.filter(s=>inheritable(s.itemId)).map(s=>({kind:'stack' as const,itemId:s.itemId,quantity:s.quantity,locked:s.locked})),...tools.filter(t=>inheritable(t.catalogItemId)).map(t=>({kind:'tool' as const,id:t.id})),...chairs.filter(c=>(c.metadata as {inheritable?:boolean}|null)?.inheritable!==false).map(c=>({kind:'chair' as const,id:c.id}))];return{assets,tools,chairs};}
 async executeEstate(guildId:string,id:string){const current=await this.get(id);if(current.guildId!==guildId||current.type!=='family_estate')throw new DomainError('FAMILY_ESTATE','Estate unavailable.');let membershipRevision:number|undefined;const beforeCommit=()=>{if(membershipRevision!==undefined&&this.membershipRevision()!==membershipRevision)throw new DomainError('FAMILY_MEMBERSHIP_CHANGED','Membership changed during estate execution; retry after reconciliation.');};return this.atomic.run(guildId,`family:estate_execute:${id}:${current.version}`,id,async(tx,ledger)=>{membershipRevision=this.membershipRevision();const s=await new PrismaTransactionSessions(tx).get<FamilyData>(id);if(!s||s.guildId!==guildId||s.type!=='family_estate')throw new DomainError('FAMILY_ESTATE','Estate unavailable.');if(s.state==='CLOSED'||s.state==='CANCELLED')return{sessionId:id};if(!s.expiresAt||s.expiresAt>this.clock())throw new DomainError('NOT_DUE','Estate grace or settlement waiting period remains open.');const userId=s.ownerUserId!,presence=await tx.memberPresenceState.findUnique({where:{guildId_userId:{guildId,userId}}});if(presence?.joinedAt&&s.data.departedAt&&presence.joinedAt>new Date(s.data.departedAt)){await this.save(tx,s,{...s.data,result:'Estate canceled after return'},'CANCELLED');return{sessionId:id};}
  // Recheck passive membership inside the transaction. Unknown Discord state must
  // throw through the injected resolver, so an outage never authorizes an estate.
  if(await this.eligible(guildId,userId)){await this.save(tx,s,{...s.data,result:'Estate canceled after return'},'CANCELLED');return{sessionId:id};}
  const account=await tx.economyAccount.findUnique({where:{guildId_userId:{guildId,userId}}}),reserved=await tx.escrow.count({where:{guildId,ownerUserId:userId,state:'RESERVED'}});if(reserved||account&&spendableWallet(account)!==account.wallet){const due=TimerEngine.create(this.clock(),300).expiresAt,saved=await this.save(tx,s,{...s.data,result:'Awaiting existing reserved-asset settlement'},'OPEN',due);await tx.scheduledJob.create({data:{guildId,jobType:'family.estate_execute',executionKey:`family:estate_execute:${id}:wait:${saved.version}`,dueAt:due,payload:{guildId,channelId:s.channelId,sessionId:id}}});return{sessionId:id,deferred:true};}
  const selfAuctions=await tx.familyAuction.findMany({where:{guildId,sellerUserId:userId,status:'OPEN',auctionType:{in:['spouse','child']}}});for(const auction of selfAuctions){const bids=await tx.familyAuctionBid.findMany({where:{auctionId:auction.id}});for(const bid of bids)await new PrismaWagerEscrow(tx,ledger).refund(guildId,'family_bid',auction.id+':'+bid.bidderUserId,'family:estate:'+id+':auction:'+auction.id+':'+bid.bidderUserId);await tx.familyAuction.update({where:{id:auction.id},data:{status:'CLOSED'}});const open=await new PrismaTransactionSessions(tx).get<FamilyData>(auction.id);if(open)await this.save(tx,open,{...open.data,result:'Auction canceled when the estate executed; bids refunded.'},'CANCELLED');await tx.scheduledJob.updateMany({where:{executionKey:'family:auction_close:'+auction.id,status:'PENDING'},data:{dueAt:this.clock()}});}
  const beneficiary=await this.heir(tx,guildId,userId),inventory=await this.assets(tx,guildId,userId),amount=(account?.wallet??0n)+(account?.bank??0n);if(amount)await ledger.apply({guildId,idempotencyKey:'family:estate:money:'+id,lines:[{userId,bucket:'wallet',amount:-(account?.wallet??0n),reason:'Estate execution'},{userId,bucket:'bank',amount:-(account?.bank??0n),reason:'Estate execution'},beneficiary?{userId:beneficiary,bucket:'wallet',amount,reason:'Inheritance'}:{bucket:'system',amount,reason:'Estate removed from circulation'}]});await tx.economyAccount.upsert({where:{guildId_userId:{guildId,userId}},create:{guildId,userId,starterGrantedAt:this.clock()},update:{bankTier:1,...(!account?.starterGrantedAt?{starterGrantedAt:this.clock()}:{})}});const auctions:string[]=[],c:FamilyContext={guildId,channelId:s.channelId,userId,requestKey:'estate:'+id};for(const asset of inventory.assets){if(beneficiary)await this.grantEstateAsset(tx,guildId,beneficiary,asset);else auctions.push(await this.estateAuction(tx,c,asset,id));}
  await tx.inventoryEntry.updateMany({where:{guildId,userId},data:{quantity:0}});const transferredTools=new Set(inventory.assets.filter(a=>a.kind==='tool').map(a=>a.id)),transferredChairs=new Set(inventory.assets.filter(a=>a.kind==='chair').map(a=>a.id));for(const tool of inventory.tools)if(!transferredTools.has(tool.id))await tx.toolInstance.update({where:{id:tool.id},data:{userId:'estate:'+id,equipped:false}});for(const chair of inventory.chairs)if(!transferredChairs.has(chair.id))await tx.craftedChair.update({where:{id:chair.id},data:{userId:'estate:'+id}});
  const formerPairs=await tx.marriage.findMany({where:{guildId,OR:[{userA:userId},{userB:userId}]},select:{id:true}});await tx.marriage.updateMany({where:{guildId,status:'ACTIVE',OR:[{userA:userId},{userB:userId}]},data:{status:'ENDED',endedAt:this.clock()}});await tx.adoption.updateMany({where:{guildId,status:'ACTIVE',OR:[{childUserId:userId},{parentPairKey:{in:formerPairs.map(pair=>pair.id)}}]},data:{status:'ENDED',endedAt:this.clock()}});await this.largest(tx,guildId);const saved=await this.save(tx,s,{...s.data,executed:true,...(beneficiary?{heirId:beneficiary}:{}),amount:amount.toString(),assetsTransferred:inventory.assets.length,auctionIds:auctions,result:beneficiary?'Inheritance executed':'Estate funds removed; eligible items auctioned.'},'CLOSED');await new PrismaAuditSink({auditEvent:tx.auditEvent}).write({guildId,source:'scheduler',action:'family.estate_executed',targetType:'member',targetId:userId,after:{sessionId:id,heirId:beneficiary,amount:amount.toString(),assets:inventory.assets.length},requestId:'family:estate:'+id,createdAt:this.clock()});const jobId=await this.publishIntent(tx,saved);
  return{sessionId:id,jobId};
 // The shared runner checks synchronously after receipt insertion. A gateway
 // event during any awaited write therefore rolls back the receipt and assets.
 },beforeCommit);}
 /** Session, typed assets and winning identity must represent one committed snapshot. */
 async publicView(id:string){return this.db.$transaction(async tx=>{
  const row=await tx.gameSession.findUnique({where:{id},include:{votes:true}});
  if(!row||!row.type.startsWith('family_'))throw new DomainError('FAMILY_SESSION','That family event is unavailable.');
  const data={...row.data as unknown as FamilyData};
  if(row.type==='family_auction'&&data.winnerId&&!data.members?.some(m=>m.userId===data.winnerId)){
   const winner=await tx.gameParticipant.findUnique({where:{sessionId_userId:{sessionId:id,userId:data.winnerId}}});
   if(winner?.data){const member=winner.data as unknown as import('./domain.js').FamilyMember;data.members=[...(data.members??[]),member];}
  }
  const itemEscrow=row.type==='family_marriage'?(await tx.escrow.findMany({where:{guildId:row.guildId,referenceType:'family_proposal',referenceId:row.id},orderBy:{id:'asc'}})).map(item=>{assertItemEscrow(item);return{itemId:item.itemRef,quantity:item.itemQuantity,state:item.state};}):undefined;
  const vote=row.type==='family_marriage'&&row.state==='OPEN'?marriageVoting(row.votes):null;
  return{id:row.id,guildId:row.guildId,channelId:row.channelId,messageId:row.messageId,ownerId:row.ownerUserId,state:row.state,type:row.type,createdAt:row.createdAt,expiresAt:row.expiresAt,data:{...data,...(itemEscrow?{itemEscrow}:{}),...(vote?{voteResult:{up:vote.totals.up??0,down:vote.totals.down??0,total:vote.total,approval:vote.approval}}:{})}};
 },{isolationLevel:'RepeatableRead'});}

}
export type FamilyView=Awaited<ReturnType<PrismaFamilyRepository['publicView']>>;
