import {shell,heading,panel,text,ink,esc} from '../../features-events/src/visual.js';
import {wrapText,truncateText,textWidth} from '../../renderer/src/text-layout.js';
import type {FamilyView} from './prisma-repository.js';
const money=(value:string|undefined)=>{try{return BigInt(value??'0').toLocaleString('en-US');}catch{return'0';}};
const TITLES={family_marriage:'A Marriage in the Chairs',family_divorce:'Separate Seats',family_adoption:'A New Family Seat',family_auction:'The Sealed Auction',family_estate:'An Estate, Settled',family_ended:'A Family Change'} as Record<string,string>;
export function familyTitle(v:FamilyView){return v.type==='family_estate'&&!v.data.executed?(v.state==='CANCELLED'?'Estate Canceled':'Estate on Hold'):TITLES[v.type]??'The Family Lounge';}
const itemName=(id:string)=>({'family.ring':'Ring','family.wedding_sack':'Wedding Sack','family.blessing':'Blessing of Angrier Jordan'}[id]??id);
function details(v:FamilyView){const d=v.data,out:string[]=[],name=(id:string)=>d.members?.find(m=>m.userId===id)?.name??'Member '+id;
 if(v.type==='family_marriage'){
  out.push('Proposal: '+itemName(d.proposalItem??'family.ring'));
  for(const item of d.itemEscrow??[])out.push(`${item.quantity} × ${itemName(item.itemId)}: ${item.state==='RESERVED'?'reserved until the proposal resolves':item.state==='REFUNDED'?'returned to inventory':item.state==='SETTLED'?'consumed by the marriage':'settlement pending'}.`);
  if(v.state==='DRAFT')out.push('The proposed member may accept or decline.');
  else if(d.compatibility!==undefined){out.push('Married '+new Date(d.marriedAt??v.createdAt).toISOString().slice(0,10),`Compatibility ${d.compatibility}% · Success chance ${d.success}%`,d.blessingConsumed?'The Blessing of Angrier Jordan was consumed.':'No Blessing was required.');if(d.spouseCounts)out.push('Active spouses: '+Object.values(d.spouseCounts).join(' / '));if(d.voteResult)out.push(`Approve ${d.voteResult.up} · Disapprove ${d.voteResult.down} · Approval ${d.voteResult.approval}%`);if(d.firstChildBonus)out.push('First child slot unlocked by community approval.');}
 }else if(v.type==='family_divorce'){out.push(`${money(d.amount)} Ottomans transferred.`,...(d.payerId&&d.receiverId?[name(d.payerId)+' paid '+name(d.receiverId)+'.']:[]),'Items remain with their owners.','This pair may remarry after the waiting period.');}
 else if(v.type==='family_auction'){out.push(d.auctionType==='estate'?'System estate item auction':d.auctionType==='spouse'?'Self-auction · spouse roleplay':'Self-auction · adopted-child roleplay');if(v.state==='OPEN')out.push('Bids are sealed until close.','You may increase your own bid.','Bids cannot decrease or be withdrawn.',`Reserve: ${money(d.reserve)} Ottomans`);else if(d.winnerId)out.push('Winning member: '+name(d.winnerId),`Winning bid: ${money(d.amount)} Ottomans`,d.auctionType==='estate'?'The winning member received the item.':'Proceeds went directly to the member auctioned.','Other reserved bids have been returned.');else out.push('No winning member. Reserved bids have been returned.');if(d.asset)out.push(d.asset.kind==='stack'?`${d.asset.quantity} × ${itemName(d.asset.itemId)}`:'Individual '+d.asset.kind);}
 else if(v.type==='family_estate'){
  if(!d.executed)out.push(v.state==='CANCELLED'?'The member returned. This estate was not executed.':'No estate transfer has been executed. Existing reservations must settle before execution.');
  else{out.push(d.heirId?(d.members?.some(m=>m.userId===d.heirId)?'Beneficiary: '+name(d.heirId):'One beneficiary received the eligible estate.'):'No eligible heir remained.',`${money(d.amount)} Ottomans ${d.heirId?'transferred':'removed from circulation'}.`,`${d.assetsTransferred??0} eligible inventory entries ${d.heirId?'transferred':'assigned to estate auctions'}.`);if(d.auctionIds?.length)out.push(`${d.auctionIds.length} separate estate-item auctions opened.`);out.push('Execution is final. A later return does not restore this estate.');}
 }else if(v.type==='family_adoption')out.push(v.state==='DRAFT'?'The proposed child must accept. Both married parents will be linked.':v.state==='CLOSED'?'The active family tree has been updated.':'No adoption link was created.');
 else out.push(d.result??'The active family tree has changed.');
 return out;
}
/** The approved event shell is unchanged; content height grows instead of hiding financial details. */
export function renderFamily(v:FamilyView){const d=v.data,title=familyTitle(v),subtitle=d.result??'A family event in the Chairs';let body=heading('ANGRIER JORDAN · FAMILY',title,'').replace(`font-size="32"`, `font-size="32" textLength="${Math.min(396,textWidth(title,32))}" lengthAdjust="spacingAndGlyphs"`);const sub=wrapText(subtitle,396,14);for(const[n,line]of sub.entries())body+=text(22,111+n*19,line,14,ink.white);const top=Math.max(137,128+(sub.length-1)*19);let y=top+31,content='';
 const add=(value:string,color=ink.white,size=17)=>{for(const line of wrapText(value,376,size)){content+=text(32,y,line,size,color);y+=Math.max(24,size+5);}y+=10;};
 if(d.members?.length){for(const[index,member]of d.members.slice(0,2).entries()){const x=32+index*196,clip='avatar'+index;content+=`<defs><clipPath id="${clip}"><circle cx="${x+32}" cy="${y+24}" r="31"/></clipPath></defs><circle cx="${x+32}" cy="${y+24}" r="33" fill="#0C2830" stroke="${ink.gold}"/>`;if(member.avatar.startsWith('data:image/'))content+=`<image href="${esc(member.avatar)}" x="${x+1}" y="${y-7}" width="62" height="62" clip-path="url(#${clip})"/>`;else content+=text(x+32,y+32,member.name.slice(0,2).toUpperCase(),22,ink.warm,'text-anchor="middle"');const nameLines=wrapText(member.name,174,15);for(const[n,line]of nameLines.slice(0,2).entries())content+=text(x,y+80+n*20,n===1&&nameLines.length>2?truncateText(line+'…',174,15):line,15,ink.white);}y+=136;}
 for(const value of details(v)){const monetary=/^(?:Winning bid: )?[\d,]+ Ottomans/.test(value),size=monetary?(v.type==='family_estate'?26:23):value.startsWith('Compatibility')?18:17;add(value,monetary&&v.type==='family_divorce'?ink.warm:/Ottomans|Approval|Compatibility|child slot/.test(value)?ink.emerald:ink.white,size);}
 const bottom=Math.max(702,y+8);body+=panel(18,top,404,bottom-top)+content;const footer=v.type==='family_marriage'&&v.state==='OPEN'?'Live community approval · one editable vote':v.type==='family_auction'&&v.state==='OPEN'?'Escrow protected · eligibility checked at close':v.type==='family_estate'&&!d.executed?'Estate not executed.':'The family record is saved.';body+=panel(18,bottom+19,404,69,ink.gold);for(const[n,line]of wrapText(footer,376,14).entries())body+=text(32,bottom+46+n*21,line,14,ink.warm);return shell(bottom+108,body);
}
export function familyDescription(v:FamilyView){const d=v.data,out=[d.result??''];if(d.members)out.push(d.members.map(m=>m.name).join(' + '));out.push(...details(v));if(d.heirId)out.push(`Beneficiary: <@${d.heirId}>.`);if(d.winnerId)out.push(`Winning member: <@${d.winnerId}>.`);if(d.payerId&&d.receiverId)out.push(`<@${d.payerId}> paid <@${d.receiverId}>.`);if(v.expiresAt&&['DRAFT','OPEN'].includes(v.state))out.push(`Closes <t:${Math.floor(v.expiresAt.getTime()/1000)}:R>.`);return out.filter(Boolean).join('\n');}
