import {shell,heading,panel,text,ink,lines,esc} from '../../features-events/src/visual.js';
import type {FamilyView} from './prisma-repository.js';
const money=(value:string|undefined)=>{try{return BigInt(value??'0').toLocaleString('en-US');}catch{return'0';}};
const TITLES={family_marriage:'A Marriage in the Chairs',family_divorce:'Separate Seats',family_adoption:'A New Family Seat',family_auction:'The Sealed Auction',family_estate:'An Estate, Settled',family_ended:'A Family Change'} as Record<string,string>;
export function familyTitle(v:FamilyView){return TITLES[v.type]??'The Family Lounge';}
/** Uses only the approved event frame and the supplied current-state projection. */
export function renderFamily(v:FamilyView){const d=v.data;let body=heading('ANGRIER JORDAN · FAMILY',familyTitle(v),d.result??'A family event in the Chairs');body+=panel(18,137,404,565);let y=168,clipped=false;const add=(value:string,color=ink.white,size=17)=>{for(const line of lines(value,41)){if(y>674){clipped=true;return;}body+=text(32,y,line,size,color);y+=24;}y+=10;};
 if(d.members?.length){for(const[index,member]of d.members.slice(0,2).entries()){const x=32+index*196,clip='avatar'+index;body+=`<defs><clipPath id="${clip}"><circle cx="${x+32}" cy="${y+24}" r="31"/></clipPath></defs><circle cx="${x+32}" cy="${y+24}" r="33" fill="#0C2830" stroke="${ink.gold}"/>`;if(member.avatar.startsWith('data:image/'))body+=`<image href="${esc(member.avatar)}" x="${x+1}" y="${y-7}" width="62" height="62" clip-path="url(#${clip})"/>`;else body+=text(x+32,y+32,member.name.slice(0,2).toUpperCase(),22,ink.warm,'text-anchor="middle"');for(const[n,line]of lines(member.name,19).slice(0,2).entries())body+=text(x,y+80+n*20,line,15,ink.white);}y+=136;}
 if(v.type==='family_marriage'){
  add('Proposal: '+(d.proposalItem==='family.wedding_sack'?'Wedding Sack':'Ring'),ink.warm);
  if(v.state==='DRAFT')add('The proposed member may accept or decline.');else if(d.compatibility!==undefined){add('Married '+new Date(d.marriedAt??v.createdAt).toISOString().slice(0,10));add(`Compatibility ${d.compatibility}% · Success chance ${d.success}%`,ink.emerald,18);add(d.blessingConsumed?'The Blessing of Angrier Jordan was consumed.':'No Blessing was required.',ink.muted,14);if(d.spouseCounts)add('Active spouses: '+Object.values(d.spouseCounts).join(' / '),ink.muted,14);if(d.voteResult)add(`Approve ${d.voteResult.up} · Disapprove ${d.voteResult.down} · Approval ${d.voteResult.approval}%`,ink.warm);if(d.firstChildBonus)add('First child slot unlocked by community approval.',ink.emerald,15);}
 }else if(v.type==='family_divorce'){add(`${money(d.amount)} Ottomans transferred.`,ink.warm,23);add('Items remain with their owners.');add('This pair may remarry after the waiting period.',ink.muted,15);}
 else if(v.type==='family_auction'){add(d.auctionType==='estate'?'System estate item auction':d.auctionType==='spouse'?'Self-auction · spouse roleplay':'Self-auction · adopted-child roleplay',ink.warm);if(v.state==='OPEN'){add('Bids are sealed until close.');add('You may increase your own bid.');add('Bids cannot decrease or be withdrawn.');add(`Reserve: ${money(d.reserve)} Ottomans`,ink.emerald);}else if(d.winnerId){add(`Winning bid: ${money(d.amount)} Ottomans`,ink.emerald,23);add(d.auctionType==='estate'?'The winning member received the item.':'Proceeds went directly to the member auctioned.');}else add('Reserved bids have been returned.');if(d.asset)add(d.asset.kind==='stack'?`${d.asset.quantity} × ${d.asset.itemId}`:'Individual '+d.asset.kind,ink.muted,15);}
 else if(v.type==='family_estate'){add(d.heirId?'One beneficiary received the eligible estate.':'No eligible heir remained.',ink.warm);add(`${money(d.amount)} Ottomans`,ink.emerald,26);add(`${d.assetsTransferred??0} eligible inventory entries`);if(d.auctionIds?.length)add(`${d.auctionIds.length} separate estate-item auctions opened.`);add('Execution is final. A later return does not restore this estate.',ink.muted,15);}
 else if(v.type==='family_adoption')add(v.state==='DRAFT'?'The proposed child must accept. Both married parents will be linked.':'The active family tree has been updated.');else add(d.result??'The active family tree has changed.');
 if(clipped)body+=text(32,691,'Full event details are included below the card.',12,ink.muted);body+=panel(18,721,404,69,ink.gold);const footer=v.type==='family_marriage'&&v.state==='OPEN'?'Live community approval · one editable vote':v.type==='family_auction'&&v.state==='OPEN'?'Escrow protected · eligibility checked at close':'The family record is saved.';for(const[n,line]of lines(footer,43).slice(0,2).entries())body+=text(32,748+n*21,line,14,ink.warm);return shell(810,body);
}
export function familyDescription(v:FamilyView){const d=v.data,out=[d.result??''];if(d.members)out.push(d.members.map(m=>m.name).join(' + '));if(d.voteResult)out.push(`👍 ${d.voteResult.up} · 👎 ${d.voteResult.down} · Approval ${d.voteResult.approval}%`);if(d.payerId)out.push(`<@${d.payerId}> paid <@${d.receiverId}> ${d.amount} Ottomans.`);if(d.winnerId)out.push(`Winning member: <@${d.winnerId}> · ${d.amount} Ottomans.`);if(d.heirId)out.push(`Beneficiary: <@${d.heirId}>.`);if(v.expiresAt&&['DRAFT','OPEN'].includes(v.state))out.push(`Closes <t:${Math.floor(v.expiresAt.getTime()/1000)}:R>.`);return out.filter(Boolean).join('\n');}
