import {randomInt,randomUUID} from 'node:crypto';
import {Prisma,type PrismaClient} from '@prisma/client';
import {DomainError,SessionEngine,type LedgerEngine,type Session} from '../../core/src/index.js';
import {PrismaItemEscrow} from '../../database/src/item-escrow.js';
import {PrismaAtomicOperations,requestFingerprint} from '../../database/src/atomic-operations.js';
import {PrismaTransactionSessions} from '../../database/src/transaction-sessions.js';
import {PrismaJobDeliveryRepository} from '../../database/src/job-delivery.js';
import {PrismaAuditSink} from '../../database/src/prisma-adapters.js';
import {cooldownUntil,FAMILY_PERKS,familyComponents,type FamilyContext,type FamilyData,type FamilyPolicy,type ActiveMarriage,type ActiveAdoption,DEFAULT_FAMILY_POLICY} from './domain.js';

export const json=(value:unknown)=>JSON.parse(JSON.stringify(value,(_k,v)=>typeof v==='bigint'?v.toString():v)) as Prisma.InputJsonObject;
export type Tx=Prisma.TransactionClient;
export class FamilyStore {
 protected atomic:PrismaAtomicOperations;
 protected canAct:(guildId:string,userId:string)=>Promise<boolean>;
 constructor(protected db:PrismaClient,protected secret:string,protected eligible:(guildId:string,userId:string)=>Promise<boolean>,protected policy:FamilyPolicy=DEFAULT_FAMILY_POLICY,protected clock:()=>Date=()=>new Date(),protected rng:(max:number)=>number=randomInt,canAct?:(guildId:string,userId:string)=>Promise<boolean>,protected membershipRevision:()=>number=()=>0){this.atomic=new PrismaAtomicOperations(db);this.canAct=canAct??eligible;}
 protected run<T extends Prisma.InputJsonObject>(c:FamilyContext,action:string,args:unknown,fn:(tx:Tx,ledger:LedgerEngine)=>Promise<T>){return this.atomic.run(c.guildId,'family:'+action+':'+c.requestKey,requestFingerprint({actor:c.userId,channel:c.channelId,args}),async(tx,ledger)=>{const result=await fn(tx,ledger);await new PrismaAuditSink({auditEvent:tx.auditEvent}).write({guildId:c.guildId,actorUserId:c.userId,source:'family',action:'family.'+action,targetType:'family',...(typeof result.sessionId==='string'?{targetId:result.sessionId}:{}),after:result,requestId:c.requestKey,createdAt:this.clock()});return result;});}
 protected async allowed(guildId:string,...users:string[]){for(const userId of new Set(users))if(!await this.canAct(guildId,userId))throw new DomainError('FAMILY_INELIGIBLE','Every member involved must currently be eligible.');}
 protected async cooldown(tx:Tx,guildId:string,...users:string[]){for(const userId of new Set(users)){const row=await tx.memberGameStats.findUnique({where:{guildId_userId_gameKey:{guildId,userId,gameKey:'family_events'}}}),events=((row?.metadata??{}) as {events?:string[]}).events??[],until=cooldownUntil(events,this.clock(),this.policy);if(until>this.clock())throw new DomainError('FAMILY_COOLDOWN',`The next family change is available at ${until.toISOString()}.`);}}
 protected async event(tx:Tx,guildId:string,...users:string[]){for(const userId of new Set(users)){const row=await tx.memberGameStats.findUnique({where:{guildId_userId_gameKey:{guildId,userId,gameKey:'family_events'}}}),events=((row?.metadata??{}) as {events?:string[]}).events??[],recent=events.filter(value=>this.clock().getTime()-new Date(value).getTime()<this.policy.cooldownQuietHours*3_600_000);await tx.memberGameStats.upsert({where:{guildId_userId_gameKey:{guildId,userId,gameKey:'family_events'}},create:{guildId,userId,gameKey:'family_events',metadata:{events:[...recent,this.clock().toISOString()]}},update:{metadata:{events:[...recent,this.clock().toISOString()]}}});}}
 protected async createSession(tx:Tx,c:FamilyContext,type:string,data:FamilyData,expiresAt?:Date,state:Session['state']='OPEN',id=randomUUID()){const now=this.clock(),session:Session<FamilyData>={id,guildId:c.guildId,channelId:c.channelId,ownerUserId:c.userId,type:'family_'+type,state,data,version:0,extensionUsed:false,createdAt:now,updatedAt:now,...(expiresAt?{expiresAt}:{})};await new PrismaTransactionSessions(tx).create({...session,data:json(data)});return session;}
 protected async session(tx:Tx,c:Pick<FamilyContext,'guildId'|'channelId'>,id:string){const row=await new PrismaTransactionSessions(tx).get<FamilyData>(id);if(!row||!row.type.startsWith('family_')||row.guildId!==c.guildId||row.channelId!==c.channelId)throw new DomainError('FAMILY_SESSION','Use this family event’s original server and channel.');return row;}
 protected async save(tx:Tx,s:Session<FamilyData>,data:FamilyData,state=s.state,expiresAt=s.expiresAt){return new SessionEngine(new PrismaTransactionSessions(tx)).transition<FamilyData>(s.id,[s.state],state,row=>({...row,data,...(expiresAt?{expiresAt}:{})}));}
 protected async schedule(tx:Tx,s:Session<FamilyData>,kind:string,dueAt:Date){return tx.scheduledJob.create({data:{guildId:s.guildId,jobType:'family.'+kind,executionKey:`family:${kind}:${s.id}`,dueAt,payload:{guildId:s.guildId,channelId:s.channelId,sessionId:s.id,...(kind==='publish'?{deliveryState:'PENDING'}:{})}}});}
 protected async publishIntent(tx:Tx,s:Session<FamilyData>){return(await this.schedule(tx,s,'publish',this.clock())).id;}
 async get(id:string){const s=await this.db.gameSession.findUnique({where:{id},include:{votes:true}});if(!s||!s.type.startsWith('family_'))throw new DomainError('FAMILY_SESSION','That family event is unavailable.');return{...s,data:s.data as unknown as FamilyData};}
 async active(){return this.db.gameSession.findMany({where:{type:{startsWith:'family_'},state:{in:['DRAFT','OPEN','LOCKED','SETTLING']}}});}
 async linkMessage(guildId:string,id:string,messageId:string){await this.db.gameSession.updateMany({where:{id,guildId,messageId:null,type:{startsWith:'family_'}},data:{messageId}});}
 delivery(id:string){return new PrismaJobDeliveryRepository(this.db,id);}
 async publication(id:string){const job=await this.db.scheduledJob.findUniqueOrThrow({where:{id}});if(job.jobType!=='family.publish')throw new DomainError('FAMILY_JOB','Invalid family publication job.');return job.payload as {guildId:string;channelId:string;sessionId:string};}
 protected async reserveItem(tx:Tx,guildId:string,userId:string,itemId:string,referenceId:string){
  try{return await new PrismaItemEscrow(tx,this.clock).reserve({guildId,userId,itemId,quantity:1,referenceType:'family_proposal',referenceId,key:'family:item:'+referenceId+':'+userId+':'+itemId});}
  catch(error){if(error instanceof DomainError&&['ITEM_ESCROW_UNAVAILABLE','ITEM_ESCROW_INVENTORY'].includes(error.code))throw new DomainError('FAMILY_ITEM','The required unlocked family item is unavailable.');throw error;}
 }
 protected async finishItems(tx:Tx,guildId:string,referenceId:string,consume:Set<string>){await new PrismaItemEscrow(tx,this.clock).finishReference(guildId,'family_proposal',referenceId,consume);}
 protected async treeRows(tx:Tx,guildId:string){const rows=await tx.marriage.findMany({where:{guildId,status:'ACTIVE'}}),adopted=await tx.adoption.findMany({where:{guildId,status:'ACTIVE'}}),parents=await tx.marriage.findMany({where:{guildId,id:{in:adopted.map(a=>a.parentPairKey)}}});const marriages:ActiveMarriage[]=rows.filter(row=>row.startedAt).map(row=>({id:row.id,userA:row.userA,userB:row.userB,startedAt:row.startedAt!})),adoptions:ActiveAdoption[]=adopted.flatMap(row=>{const p=parents.find(p=>p.id===row.parentPairKey);return p?[{id:row.id,parentPairKey:row.parentPairKey,childUserId:row.childUserId,parents:[p.userA,p.userB] as [string,string]}]:[];});return{marriages,adoptions};}
 async tree(guildId:string,userId:string){const rows=await this.db.$transaction(tx=>this.treeRows(tx,guildId)),members=familyComponents(rows.marriages,rows.adoptions).find(group=>group.includes(userId))??[userId];return{members,marriages:rows.marriages.filter(m=>members.includes(m.userA)),adoptions:rows.adoptions.filter(a=>members.includes(a.childUserId)),record:await this.db.recordValue.findUnique({where:{guildId_recordKey_scopeKey:{guildId,recordKey:'largest_family',scopeKey:'current'}}})};}
 protected async largest(tx:Tx,guildId:string){const rows=await this.treeRows(tx,guildId),groups=familyComponents(rows.marriages,rows.adoptions),where={guildId_recordKey_scopeKey:{guildId,recordKey:'largest_family',scopeKey:'current'}},old=await tx.recordValue.findUnique({where}),previous=old?.value as {members?:string[];perk?:string}|undefined;let members=groups[0]??[];const retained=groups.find(group=>group.length===members.length&&group.join(':')===previous?.members?.join(':'));if(retained)members=retained;if(members.join(':')===previous?.members?.join(':'))return;const value={members,count:members.length,perk:members.length?FAMILY_PERKS[this.rng(FAMILY_PERKS.length)]!:null};await tx.recordValue.upsert({where,create:{guildId,recordKey:'largest_family',scopeKey:'current',value,achievedAt:this.clock()},update:{value,achievedAt:this.clock()}});}
}
