import {shell,heading,panel,text,ink} from '../../features-events/src/visual.js';
import {gameNames,coordinateLabel} from './domain.js';
import type {PvpView,PvpPrivateView} from './prisma-repository.js';
export const PVP_RULES='Challenge another member for free or show an optional Ottoman wager. The opponent has 2 minutes to accept. Acceptance revalidates and escrows both matching stakes. Each turn has 5 minutes; timeout forfeits. The winner receives the full pot with no rake; draws refund both stakes. Cancel before acceptance, or confirm Forfeit Match afterward. One active skill-game challenge or match per member. Play Again creates a new challenge against the same opponent and requires fresh acceptance.';
export function pvpDescription(v:PvpView){const names=v.players.map(p=>p.name).join(' vs ');if(v.phase==='challenge')return`${names}. ${v.wager==='0'?'Free game':v.wager+' Ottomans each; '+BigInt(v.wager)*2n+' total pot'}. Waiting for the opponent to accept.`;if(v.phase==='finished')return`${names}. ${v.result}${v.winnerId?'; winner: '+v.players.find(p=>p.userId===v.winnerId)!.name:''}. ${v.paid??'0'} Ottomans paid.`;return`${names}. ${v.players[v.turn].name}'s turn${v.phase==='placement'?' to place a fleet':''}.`;}
export function renderPvp(v:PvpView){let body=heading('CHAIRS • SKILL GAMES',gameNames[v.game],v.phase==='challenge'?'A fresh challenge':v.phase==='finished'?'Match complete':v.phase==='placement'?'Place your fleets privately':'Make your move');body+=panel(18,130,404,74,ink.gold)+text(32,157,v.players[0].name.slice(0,23)+'  vs  '+v.players[1].name.slice(0,23),15)+text(32,185,v.wager==='0'?'FREE MATCH':`${v.wager} OTTOMANS EACH • NO RAKE`,12,ink.warm);
 let bottom=230;
 if(v.game!=='battleship'&&v.phase!=='challenge'){
  const cols=v.game==='tictactoe'?3:7,rows=v.game==='tictactoe'?3:6,size=v.game==='tictactoe'?95:49,left=(440-cols*size)/2;body+=panel(18,220,404,rows*size+45);for(let y=0;y<rows;y++)for(let x=0;x<cols;x++){const mark=v.cells[y*cols+x]??0,cx=left+x*size+size/2,cy=244+y*size+size/2;body+=`<rect x="${cx-size/2+3}" y="${cy-size/2+3}" width="${size-6}" height="${size-6}" rx="7" fill="#031923" stroke="#547474"/>`+text(cx,cy+9,mark?(mark===1?'X':'O'):(v.game==='tictactoe'?String(y*cols+x+1):'·'),mark?28:15,mark===1?ink.teal:mark===2?ink.gold:ink.muted,'text-anchor="middle" font-weight="600"');}bottom=rows*size+290;
 }else if(v.game==='battleship'&&v.phase!=='challenge'){body+=panel(18,220,404,100)+text(32,248,'Fleets stay private',19,ink.warm)+text(32,276,`Ready: ${Number(v.ready[0])+Number(v.ready[1])}/2 • Shots: ${v.shots[0].length} / ${v.shots[1].length}`,15)+text(32,302,'Open Your Board to place ships or fire.',14,ink.muted);bottom=346;}
 body+=panel(18,bottom,404,80,ink.gold);const status=v.phase==='finished'?(v.winnerId?`${v.players.find(p=>p.userId===v.winnerId)!.name} wins`:v.result??'Finished'):v.phase==='challenge'?'Waiting for acceptance':`${v.players[v.turn].name}'s turn`;body+=text(32,bottom+29,status.slice(0,38),19,ink.warm)+text(32,bottom+57,v.phase==='finished'?`${v.paid??0} Ottomans paid`:v.phase==='challenge'?'Challenge expires in 2 minutes':'5-minute turn • timeout is a forfeit',13,ink.muted);return shell(bottom+98,body);
}
export function renderPrivatePvp(v:PvpPrivateView){let body=heading('BATTLESHIP • PRIVATE','Your fleet & targets','Only your own ships are shown.');const grid=(y:number,title:string,own:boolean)=>{let svg=panel(18,y,404,365)+text(32,y+27,title,19,ink.warm);for(let col=0;col<10;col++)svg+=text(70+col*33,y+51,String(col+1),10,ink.muted,'text-anchor="middle"');for(let row=0;row<10;row++){svg+=text(37,y+76+row*29,String.fromCharCode(65+row),10,ink.muted);for(let col=0;col<10;col++){const cell=row*10+col,ship=own&&v.fleet.some(s=>s.includes(cell)),shot=(own?v.incomingShots:v.ownShots).find(s=>s.cell===cell),fill=shot?.hit?ink.gold:ship?ink.teal:'#061923',label=shot?(shot.hit?'X':'·'):'';svg+=`<rect x="${55+col*33}" y="${y+59+row*29}" width="29" height="25" rx="3" fill="${fill}" stroke="#49616B"/>`+text(70+col*33,y+77+row*29,label,15,shot?.hit?'#07151D':ink.white,'text-anchor="middle"');}}return svg;};body+=grid(130,'Your fleet',true)+grid(510,'Your shots',false);const last=v.ownShots.at(-1);body+=text(22,902,last?`Last shot: ${coordinateLabel(last.cell)} · ${last.sunk?'SUNK':last.hit?'HIT':'MISS'}`:'Choose Auto Place or Place Manually when it is your turn.',12,ink.muted);return shell(922,body);}
