import {readFileSync} from 'node:fs';
import {wrapText} from '../../renderer/src/text-layout.js';
import {gameNames,coordinateLabel} from './domain.js';
import type {PvpView,PvpPrivateView} from './prisma-repository.js';
export const PVP_RULES='Challenge another member for free or show an optional Ottoman wager. The opponent has 2 minutes to accept. Acceptance revalidates and escrows both matching stakes. Each turn has 5 minutes; timeout forfeits. The winner receives the full pot with no rake; draws refund both stakes. Cancel before acceptance, or confirm Forfeit Match afterward. One active skill-game challenge or match per member. Play Again creates a new challenge against the same opponent and requires fresh acceptance.';
export interface PvpPortrait {name:string;avatarData?:string|undefined;}
export type PvpPortraits=Readonly<Record<string,PvpPortrait>>;
const C={blue:'#3B82F6',gold:'#F4C542',white:'#E6EAF0',muted:'#B9CADA',emerald:'#10B981',red:'#EF4444'};
const esc=(s:string)=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const assets=new Map<string,string>();
function asset(path:string){if(!assets.has(path))assets.set(path,'data:image/png;base64,'+readFileSync(new URL('../../../production/'+path,import.meta.url)).toString('base64'));return assets.get(path)!;}
const text=(x:number,y:number,s:string,size=30,color:string=C.white,title=false)=>`<text x="${x}" y="${y}" text-anchor="middle" font-family="${title?'Space Grotesk':'Inter'}" font-size="${size}" font-weight="700" fill="${color}">${esc(s)}</text>`;
function lines(s:string,x:number,y:number,width:number,size=30,color:string=C.white){return wrapText(s,width,size).map((s,n)=>text(x,y+n*size*1.3,s,size,color)).join('');}
const panel=(x:number,y:number,w:number,h:number,color:string=C.blue)=>`<rect x="${x}" y="${y}" width="${w}" height="${h}" rx="20" fill="url(#glass)" stroke="${color}" stroke-width="2"/><rect x="${x+7}" y="${y+7}" width="${w-14}" height="${h-14}" rx="15" fill="none" stroke="${color}" opacity=".23"/><path d="M${x+28} ${y+11}H${x+w-28}" stroke="#E6EAF0" stroke-opacity=".2" stroke-width="2"/><path d="M${x+18} ${y+48}V${y+18}H${x+60}M${x+w-60} ${y+h-18}H${x+w-18}V${y+h-48}" stroke="url(#brass)" stroke-width="3" fill="none"/>`;
function frame(body:string,height:number){return `<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="${height}" viewBox="0 0 1200 ${height}"><defs><linearGradient id="glass" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#26313B" stop-opacity=".94"/><stop offset=".32" stop-color="#18232D" stop-opacity=".97"/><stop offset=".65" stop-color="#101C26" stop-opacity=".96"/><stop offset="1" stop-color="#071521" stop-opacity=".98"/></linearGradient><linearGradient id="brass"><stop stop-color="#80612B"/><stop offset=".5" stop-color="#FFE29B"/><stop offset="1" stop-color="#B38C42"/></linearGradient><radialGradient id="blueglow"><stop stop-color="${C.blue}" stop-opacity=".12"/><stop offset="1" stop-color="#081220" stop-opacity="0"/></radialGradient></defs><image href="${asset('event_art/v5/lounge-stage-runtime.png')}" width="1200" height="${height}" preserveAspectRatio="xMidYMid slice"/><rect width="1200" height="${height}" fill="#071323" opacity=".67"/><ellipse cx="600" cy="330" rx="590" ry="410" fill="url(#blueglow)"/>${body}${text(600,height-30,'SIT. PLAY. BELONG.',21,C.gold)}<rect x="5" y="5" width="1190" height="${height-10}" rx="28" stroke="${C.blue}" stroke-width="3" fill="none"/><rect x="16" y="16" width="1168" height="${height-32}" rx="21" stroke="url(#brass)" stroke-width="3" fill="none"/></svg>`;}
function heading(title:string,sub:string){return text(600,49,'ANGRIER JORDAN · THE GAMES LOUNGE',23,C.blue)+text(600,109,title,46,C.gold,true)+text(600,151,sub,25,C.muted);}
function portrait(p:PvpPortrait,x:number,y:number,key:string,color:string){const uri=p.avatarData??'',safe=uri.length<1_400_000&&/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/.test(uri);return `<defs><clipPath id="portrait${key}"><rect x="${x-59}" y="${y+5}" width="118" height="118" rx="20"/></clipPath></defs><rect x="${x-65}" y="${y-1}" width="130" height="130" rx="25" fill="#081321" stroke="${color}" stroke-width="3"/><image href="${safe?uri:asset('event_art/v3/race_chair_1.png')}" x="${x-59}" y="${y+5}" width="118" height="118" preserveAspectRatio="${safe?'xMidYMid slice':'xMidYMid meet'}" clip-path="url(#portrait${key})"/>`;}
const money=(n:string)=>{try{return BigInt(n).toLocaleString('en-US');}catch{return'0';}};
export function pvpDescription(v:PvpView){const names=v.players.map(p=>p.name).join(' vs ');if(v.phase==='challenge')return`${names}. ${v.wager==='0'?'Free game':v.wager+' Ottomans each; '+BigInt(v.wager)*2n+' total pot'}. Waiting for the opponent to accept.`;if(v.phase==='finished')return`${names}. ${v.result}${v.winnerId?'; winner: '+v.players.find(p=>p.userId===v.winnerId)!.name:''}. ${v.paid??'0'} Ottomans paid.`;return`${names}. ${v.players[v.turn].name}'s turn${v.phase==='placement'?' to place a fleet':''}.`;}
export function renderPvp(v:PvpView,portraits:PvpPortraits={}){
 const name=(n:number)=>portraits[v.players[n]!.userId]?.name??v.players[n]!.name,finished=v.phase==='finished';
 const nameRows=Math.max(...[0,1].map(n=>wrapText(name(n),485,31).length)),playerHeight=222+(nameRows-1)*41;
 let body=heading(gameNames[v.game],finished?'THE FINAL VERDICT':v.phase==='challenge'?'TWO SEATS. ONE CHALLENGE.':v.phase==='placement'?'PRIVATE FLEET PLACEMENT':'YOUR NEXT MOVE MATTERS');
 for(let n=0;n<2;n++){const x=n===0?310:890,color=n===0?C.blue:C.gold,p={name:name(n),avatarData:portraits[v.players[n]!.userId]?.avatarData};body+=panel(n===0?40:620,179,540,playerHeight,color)+portrait(p,x,195,String(n),color)+lines(name(n),x,353,485,31)+text(x,179+playerHeight-20,n===0?'CHALLENGER · '+(v.game==='connectfour'?'BLUE':v.game==='tictactoe'?'X':'FLEET ONE'):'OPPONENT · '+(v.game==='connectfour'?'GOLD':v.game==='tictactoe'?'O':'FLEET TWO'),21,color);}
 let y=179+playerHeight+23;
 if(v.game!=='battleship'&&v.phase!=='challenge'){
  const cols=v.game==='tictactoe'?3:7,rows=v.game==='tictactoe'?3:6,size=v.game==='tictactoe'?113:66,left=(1200-cols*size)/2,top=y+47;body+=panel(40,y,1120,rows*size+78);
  body+=text(208,y+72,v.game==='tictactoe'?'THREE IN A ROW':'FOUR TO WIN',23,C.gold)+text(208,y+111,'BLUE vs GOLD',22,C.muted);
  if(cols===7)for(let x=0;x<7;x++)body+=text(left+x*size+size/2,y+29,String(x+1),21,C.muted);
  for(let row=0;row<rows;row++)for(let col=0;col<cols;col++){const mark=v.cells[row*cols+col]??0,cx=left+col*size+size/2,cy=top+row*size+size/2,color=mark===1?C.blue:C.gold;if(cols===7)body+=`<circle cx="${cx}" cy="${cy}" r="${size/2-6}" fill="${mark?color:'#07111D'}" stroke="${mark?color:'#466080'}" stroke-width="3"/>`+(mark?text(cx,cy+9,mark===1?'1':'2',23,'#071321'):'');else body+=`<rect x="${cx-size/2+5}" y="${cy-size/2+5}" width="${size-10}" height="${size-10}" rx="16" fill="#071521" stroke="${mark?color:'#466080'}" stroke-width="3"/>`+text(cx,cy+18,mark===1?'X':mark===2?'O':String(row*3+col+1),mark?56:34,mark?color:C.muted);}
  body+=text(1025,y+73,'THE BOARD',22,C.blue)+text(1025,y+113,finished?'FINAL POSITION':'LIVE MATCH',21,C.muted);y+=rows*size+100;
 }else if(v.game==='battleship'&&!finished){body+=panel(40,y,1120,145)+text(600,y+45,'FLEETS STAY PRIVATE',29,C.gold)+text(600,y+86,`Ready ${Number(v.ready[0])+Number(v.ready[1])}/2 · Shots fired ${v.shots[0].length} / ${v.shots[1].length}`,29)+text(600,y+122,'Open Your Board for private placement and targeting.',23,C.muted);y+=166;}
 const status=finished?(v.winnerId?`${name(v.players.findIndex(p=>p.userId===v.winnerId))} wins`:v.result==='draw'?'Honors even · Draw':`Challenge ${v.result??'finished'}`):v.phase==='challenge'?`${name(1)} · Accept or Decline`:`${name(v.turn)} · ${v.phase==='placement'?'Place your fleet':'Your turn'}`;
 const statusLines=wrapText(status,1000,36),h=(finished?70:107)+statusLines.length*47;body+=panel(40,y,1120,h,finished?C.gold:C.blue)+lines(status,600,y+53,1000,36,finished?C.gold:C.white)+text(600,y+h-(finished?24:61),finished?`${money(v.paid??'0')} Ottomans paid${v.result==='draw'?' · Stakes returned':''}`:v.phase==='challenge'?'2-minute acceptance window':'5-minute turn · Timeout forfeits',24,C.muted);if(!finished&&v.expiresAt)body+=text(600,y+h-24,'DEADLINE · '+new Date(v.expiresAt).toISOString().slice(11,19)+' UTC',22,C.blue);y+=h+20;
 body+=panel(40,y,1120,72,C.gold)+text(600,y+45,v.wager==='0'?'FREE MATCH · NO CURRENCY AT RISK':`${money(v.wager)} EACH · ${money((BigInt(v.wager)*2n).toString())} TOTAL POT · NO RAKE`,27,C.gold);return frame(body,y+132);
}
export function renderPrivatePvp(v:PvpPrivateView,owner?:PvpPortrait){
 let body=heading('Battleship · Private Board',v.phase==='finished'?'MATCH COMPLETE':v.turn===v.seat?'YOUR TURN':'WAITING FOR YOUR OPPONENT');
 if(owner)body+=portrait(owner,99,178,'owner',C.blue)+lines(owner.name,675,218,880,31)+text(675,260,'Only you can see your fleet. Opponent ships remain hidden.',23,C.muted);
 const start=owner?334:183;
 function grid(x:number,title:string,own:boolean){let s=panel(x,start,550,563,own?C.blue:C.gold)+text(x+275,start+43,title,29,own?C.blue:C.gold);for(let c=0;c<10;c++)s+=text(x+72+c*46,start+86,String(c+1),22,C.muted);for(let r=0;r<10;r++){s+=text(x+29,start+122+r*44,String.fromCharCode(65+r),22,C.muted);for(let c=0;c<10;c++){const cell=r*10+c,ship=own&&v.fleet.some(s=>s.includes(cell)),shot=(own?v.incomingShots:v.ownShots).find(s=>s.cell===cell),fill=shot?.hit?C.red:ship?C.blue:'#071521';s+=`<rect x="${x+50+c*46}" y="${start+94+r*44}" width="41" height="39" rx="6" fill="${fill}" stroke="#58708B" stroke-width="1.5"/>`+text(x+71+c*46,start+122+r*44,shot?(shot.hit?'X':'·'):'',29,C.white);}}return s;}
 body+=grid(40,'Your fleet',true)+grid(610,'Your shots',false);
 const last=v.ownShots.at(-1);body+=text(600,start+601,'BLUE · YOUR SHIP     RED X · HIT     DOT · MISS',23,C.muted)+lines(last?`Last shot · ${coordinateLabel(last.cell)} · ${last.sunk?'SUNK':last.hit?'HIT':'MISS'}`:v.phase==='placement'?'Choose Auto Place or Place Manually on your turn.':'No shots fired yet.',600,start+648,1080,29,C.gold);return frame(body,start+712);
}
export function renderPvpNotice(title:string,message:string){const copy=wrapText(message,1030,30),height=copy.length*42+80;return frame(heading(title,'THE SKILL GAMES LOUNGE')+panel(40,183,1120,height)+lines(message,600,234,1030,30),height+260);}
