import test from 'node:test';
import assert from 'node:assert/strict';
import {countingTurn,initialCounting,initialLetter,letterTurn,restoreCounting} from '../../.test-build/packages/features-channel-games/src/domain.js';
import {recognizedWord} from '../../.test-build/packages/features-channel-games/src/lexicon.js';
test('Counting continues at milestones, rejects consecutive turns, and restoration preserves prior awards',()=>{let s={count:'99',lastUserId:'a',awardedThrough:'0'};const win=countingTurn(s,'b','100');assert.equal(win.milestone,true);s=win.state;const broken=countingTurn(s,'b','101');assert.equal(broken.valid,false);assert.equal(broken.previous,'100');assert.equal(broken.state.count,'0');const restored=restoreCounting(broken.state);assert.equal(restored.awardedThrough,'100');assert.equal(countingTurn(restored,'a','101').milestone,false);assert.equal(countingTurn(restored,'b','101').valid,false);assert.equal(countingTurn(s,'a','hello'),null);});
test('Counting supports integers beyond Number precision without losing the next count',()=>{const s={count:'9007199254740992',lastUserId:'a',awardedThrough:'0'};assert.equal(countingTurn(s,'b','9007199254740993').state.count,'9007199254740993');assert.equal(countingTurn(initialCounting(),'a','-1').valid,false);});
test('Last Letter penalties retain chain, allow negative scores and reject duplicates/consecutive valid turns',()=>{let s=letterTurn(initialLetter(),'a','chair',recognizedWord).state;let r=letterTurn(s,'a','river',recognizedWord);assert.equal(r.points,-1);assert.equal(r.state.lastWord,'chair');r=letterTurn(s,'b','nope',recognizedWord);assert.equal(r.score,-1);assert.equal(r.state.lastUserId,'a');s=letterTurn(s,'b','radar',recognizedWord).state;assert.equal(s.scores.b,2);assert.equal(letterTurn(s,'a','radar',recognizedWord).valid,false);});
test('Last Letter dictionary admits ordinary/slang/adult words and rejects names, abbreviations and inventions',()=>{for(const word of ['chair','emerald','fuck','shit','bruh','yeet'])assert.equal(recognizedWord(word),true,word);for(const word of ['london','bartholomew','xyzblargle','lol','kg'])assert.equal(recognizedWord(word),false,word);for(const word of ['<@123>','two words','@someone'])assert.equal(letterTurn(initialLetter(),'a',word,recognizedWord).valid,false);});
test('Last Letter winner is awarded at 50 and a fresh automatic round has no old words or scores',()=>{const s={...initialLetter(4),scores:{a:49}},r=letterTurn(s,'a','chair',recognizedWord);assert.equal(r.won,true);assert.equal(r.score,50);assert.deepEqual(r.state,initialLetter(5));});
