import test from 'node:test';
import assert from 'node:assert/strict';
import {INTRO_DEFAULTS,activePrompts,promptPages,saveAnswers,validateAnswers,validateIntroForm,introTranscript,introCardPages} from '../../.test-build/packages/features-introductions/src/domain.js';
const prompts=INTRO_DEFAULTS.map((p,n)=>({...p,sortOrder:n,placeholder:null,minLength:null,enabled:true,showOnCard:true,deletedAt:null}));
const config={guildId:'g',introductionChannelId:'c',panelMessageId:null,headerText:'PULL UP A CHAIR',footerText:'Welcome to Chairs.',showAvatar:true,showDisplayName:true,showJoinDate:false,allowAdminIntroConfig:false,version:1};
function draft(){return{form:{id:'f',title:'Your introduction',version:1,prompts:structuredClone(prompts)},config,answers:{historic:'Preserve me'},baseRevision:0,page:0,previewedVersion:null};}
test('Introductions preserve historical answers and allow blank optional answers',()=>{const d=draft();validateAnswers(d);const saved=saveAnswers(d,0,{name:'Jordan',from:'',doc:'',discovery:'',fun_fact:'A chair enthusiast.'});assert.equal(saved.answers.historic,'Preserve me');validateAnswers(saved);assert.equal(d.answers.name,undefined);assert.equal(saved.previewedVersion,null);});
test('Introduction paging scales beyond a modal without letting a page overwrite other or hidden fields',()=>{const d=draft();d.form.prompts=[...d.form.prompts.slice(0,5),{...prompts[0],id:'extra',sortOrder:9}];assert.deepEqual(promptPages(d.form).map(p=>p.length),[5,1]);assert.throws(()=>saveAnswers(d,1,{name:'Cannot overwrite'}),{code:'INTRO_FIELD'});const updated=saveAnswers(d,1,{extra:'New page'});assert.equal(updated.answers.historic,'Preserve me');assert.equal(updated.answers.extra,'New page');assert.throws(()=>saveAnswers(d,2,{}),{code:'INTRO_PAGE'});});
test('Hidden, disabled and soft-deleted prompts retain answers but never appear on published cards',()=>{const d=draft();d.answers={name:'Visible',from:'secret from',doc:'secret doc',discovery:'secret discovery',about:'secret about'};d.form.prompts[1].showOnCard=false;d.form.prompts[2].deletedAt='2026-09-25T12:00:00Z';d.form.prompts[3].enabled=false;const text=introTranscript(d,'Display name','2026-09-25');assert.match(text,/Visible/);assert.doesNotMatch(text,/secret|Joined/);assert.equal(activePrompts(d.form).length,4);assert.equal(d.answers.about,'secret about');});
test('Introduction form validates limits, stable IDs and Discord attachment budget',()=>{const d=draft();validateIntroForm(d.form,d.config);for(const patch of [{id:'__proto__'},{id:'constructor'},{minLength:81},{maxLength:4001},{inputStyle:'html'},{placeholder:'x'.repeat(101)}]){const f=structuredClone(d.form);Object.assign(f.prompts[0],patch);assert.throws(()=>validateIntroForm(f,d.config),{code:'INTRO_PROMPT'});}d.form.prompts.push({...prompts[0]});assert.throws(()=>validateIntroForm(d.form,d.config),{code:'INTRO_PROMPT'});const f=draft().form;f.prompts=f.prompts.map(p=>({...p,maxLength:3000}));assert.throws(()=>validateIntroForm(f,config),{code:'INTRO_CARD_LIMIT'});});
test('Introduction card pagination preserves Unicode and text; metadata requires an explicit display setting',()=>{const text='🪑'.repeat(2000)+' end';assert.equal(introCardPages(text).join(''),text);const d=draft();d.config={...config,showDisplayName:false,showJoinDate:true};assert.match(introTranscript(d,'Hidden name','2026-09-25'),/Joined 2026-09-25/);assert.doesNotMatch(introTranscript(d,'Hidden name'),/Hidden name/);assert.throws(()=>introCardPages('x'.repeat(13000)),{code:'INTRO_CARD_LIMIT'});});

test('The six owner questions are exact and blank answers never become card rows',()=>{const d=draft();assert.deepEqual(d.form.prompts.map(p=>p.label),['Name','Location','DOC',"How'd you find the server",'Fun fact about you?','Favorite type of chair?']);d.answers={name:'Jordan',from:'   ',doc:'',discovery:'',fun_fact:'',chair:''};const result=introTranscript(d,'Member');assert.match(result,/Name\nJordan/);assert.doesNotMatch(result,/Location|DOC|How.d you find|Fun fact|Favorite type|N\/A|None/);});
