import test from 'node:test';
import assert from 'node:assert/strict';
import {INTRO_DEFAULTS,activePrompts,promptPages,saveAnswers,validateAnswers,validateIntroForm,introTranscript,introductionAnswerSheet,parseIntroductionAnswerSheet} from '../../.test-build/packages/features-introductions/src/domain.js';
const prompts=INTRO_DEFAULTS.map((p,n)=>({...p,sortOrder:n,placeholder:null,minLength:null,enabled:true,showOnCard:true,deletedAt:null}));
const config={guildId:'g',introductionChannelId:'c',panelMessageId:null,headerText:'PULL UP A CHAIR',footerText:'Welcome to Chairs.',showAvatar:true,showDisplayName:true,showJoinDate:false,allowAdminIntroConfig:false,version:1};
function draft(){return{form:{id:'f',title:'Your introduction',version:1,prompts:structuredClone(prompts)},config,answers:{historic:'Preserve me'},baseRevision:0,page:0,previewedVersion:null};}
test('exact five owner questions, in order, fit together with maximum answers in a native text area',()=>{const d=draft();assert.deepEqual(prompts.map(p=>p.label),['What should we call you?','What is your drug of choice?','What is your most controversial opinion?','If on death row, what would your last meal be?','What is your favorite type of chair?']);for(const p of prompts)d.answers[p.id]='x'.repeat(p.maxLength);assert.ok(introductionAnswerSheet(d).length<=4000);validateIntroForm(d.form,d.config);});
test('one sheet saves all five together, preserves history and multiline answers through recovery and editing',()=>{let d=draft();const answers=Object.fromEntries(prompts.map((p,n)=>[p.id,`Answer ${n+1}\n\nSecond paragraph.`]));d=saveAnswers(d,0,parseIntroductionAnswerSheet(d.form,introductionAnswerSheet({...d,answers})),100);validateAnswers(d);assert.equal(d.answers.historic,'Preserve me');for(const p of prompts)assert.equal(d.answers[p.id],answers[p.id]);const recovered=JSON.parse(JSON.stringify(d));assert.deepEqual(parseIntroductionAnswerSheet(recovered.form,introductionAnswerSheet(recovered)),answers);assert.equal(d.previewedVersion,null);});
test('all optional answers may be blank without losing any question headings',()=>{const d=draft(),values=parseIntroductionAnswerSheet(d.form,introductionAnswerSheet(d));assert.equal(Object.keys(values).length,5);validateAnswers(saveAnswers(d,0,values,100));});
test('missing, duplicate, reordered or renamed headings reject the entire sheet',()=>{const d=draft(),sheet=introductionAnswerSheet(d);for(const bad of [sheet.replace('2. What is your drug of choice?',''),sheet+'\n1. What should we call you?',sheet.replace('1. What should we call you?','1. Changed'),sheet.replace('2. What is your drug of choice?','3. What is your most controversial opinion?')])assert.throws(()=>parseIntroductionAnswerSheet(d.form,bad),{code:'INTRO_SHEET_FORMAT'});assert.equal(d.answers.name,undefined);});
test('individual answer limits and stale/hidden field protection still apply to single-sheet saves',()=>{const d=draft();assert.throws(()=>saveAnswers(d,0,{name:'x'.repeat(81)},100),{code:'INTRO_ANSWER'});assert.throws(()=>saveAnswers(d,0,{historic:'overwrite'},100),{code:'INTRO_FIELD'});assert.throws(()=>parseIntroductionAnswerSheet(d.form,'x'.repeat(4001)),{code:'INTRO_SHEET_LIMIT'});});
test('hidden, retired and disabled prompts never appear in sheet or transcript; answers survive',()=>{const d=draft();d.answers={name:'Visible',doc:'secret doc',character:'secret character',opinion:'secret opinion',historic:'Old'};d.form.prompts[1].showOnCard=false;d.form.prompts[2].deletedAt='2026-09-25T12:00:00Z';d.form.prompts[3].enabled=false;const text=introTranscript(d,'Display');assert.match(text,/Visible/);assert.doesNotMatch(text,/secret/);assert.doesNotMatch(introductionAnswerSheet(d),/secret character|secret opinion/);assert.equal(activePrompts(d.form).length,3);assert.equal(d.answers.historic,'Old');});
test('legacy three/five field submissions remain valid without overwriting other answers',()=>{const d=draft();d.answers.chair='Saved chair';const first=promptPages(d.form,3)[0];const saved=saveAnswers(d,0,Object.fromEntries(first.map(p=>[p.id,'Updated'])),3);assert.equal(saved.answers.chair,'Saved chair');assert.equal(saved.answers.historic,'Preserve me');const all=saveAnswers(d,0,Object.fromEntries(promptPages(d.form,5)[0].map(p=>[p.id,'Updated'])),5);assert.equal(all.answers.chair,'Updated');assert.throws(()=>saveAnswers(d,1,{name:'No'}),{code:'INTRO_FIELD'});});
test('form configuration enforces stable IDs, validation and bounded public content',()=>{const d=draft();for(const patch of [{id:'__proto__'},{minLength:81},{maxLength:4001},{inputStyle:'html'}]){const f=structuredClone(d.form);Object.assign(f.prompts[0],patch);assert.throws(()=>validateIntroForm(f,d.config),{code:'INTRO_PROMPT'});}const f=draft().form;f.prompts=f.prompts.map(p=>({...p,maxLength:3000}));assert.throws(()=>validateIntroForm(f,config),{code:'INTRO_CARD_LIMIT'});});
