import test from 'node:test';
import assert from 'node:assert/strict';
import { AuditService,FixedClock,InMemoryAuditSink,DomainError } from '../../.test-build/packages/core/src/index.js';
import { InMemoryJailRepository,JailService,parseJailDuration } from '../../.test-build/packages/features-jail/src/index.js';

const make=()=>{const clock=new FixedClock(new Date('2026-09-21T12:00:00Z'));const repo=new InMemoryJailRepository();const sink=new InMemoryAuditSink();const service=new JailService(repo,new AuditService(sink),clock);return{clock,repo,sink,service};};

test('Hotseat duration accepts human-readable bounded values and indefinite',()=>{assert.equal(parseJailDuration('12h').seconds,43200);assert.equal(parseJailDuration('1 day 6 hours').seconds,108000);assert.equal(parseJailDuration('indefinite').indefinite,true);assert.throws(()=>parseJailDuration('2m'),e=>e instanceof DomainError&&e.code==='INVALID_JAIL_DURATION');assert.throws(()=>parseJailDuration('31d'),e=>e instanceof DomainError&&e.code==='INVALID_JAIL_DURATION');});

test('sending to moderation Hotseat creates numbered case, sentence, expiry job and audit',async()=>{const {repo,sink,service}=make();const out=await service.send({guildId:'g',userId:'u',actorUserId:'mod',duration:'12h',reason:'Repeated targeted harassment',suspendedRoleIds:['admin-role']});assert.equal(out.caseRecord.id,1);assert.equal(out.sentence.type,'MODERATION');assert.equal(out.sentence.restoration.suspendedRoleIds[0],'admin-role');assert.equal(repo.expiryJobs.get(out.sentence.id).status,'PENDING');assert.equal(sink.events.at(-1).action,'jail.send');});

test('only one active moderation Hotseat sentence exists per member',async()=>{const {service}=make();await service.send({guildId:'g',userId:'u',actorUserId:'mod',duration:'1h',reason:'one'});await assert.rejects(()=>service.send({guildId:'g',userId:'u',actorUserId:'mod',duration:'1h',reason:'two'}),e=>e instanceof DomainError&&e.code==='JAIL_ALREADY_ACTIVE');});

test('extend and reduce create linked cases and reschedule expiration',async()=>{const {repo,service}=make();const first=await service.send({guildId:'g',userId:'u',actorUserId:'mod',duration:'2h',reason:'initial'});const extended=await service.extend({guildId:'g',userId:'u',actorUserId:'mod',duration:'1h',reason:'new violation'});assert.equal(extended.sentence.endsAt.toISOString(),'2026-09-21T15:00:00.000Z');const reduced=await service.reduce({guildId:'g',userId:'u',actorUserId:'mod',duration:'30m',reason:'review'});assert.equal(reduced.sentence.endsAt.toISOString(),'2026-09-21T14:30:00.000Z');assert.equal((await service.history('g','u'))[0].cases.length,3);assert.equal(repo.expiryJobs.get(first.sentence.id).dueAt.toISOString(),'2026-09-21T14:30:00.000Z');});

test('reduce cannot silently act as release',async()=>{const {service}=make();await service.send({guildId:'g',userId:'u',actorUserId:'mod',duration:'20m',reason:'initial'});await assert.rejects(()=>service.reduce({guildId:'g',userId:'u',actorUserId:'mod',duration:'20m',reason:'too much'}),e=>e instanceof DomainError&&e.code==='JAIL_REDUCTION_TOO_LARGE');});

test('manual release closes only moderation sentence and cancels its expiry job',async()=>{const {repo,service}=make();const sent=await service.send({guildId:'g',userId:'u',actorUserId:'mod',duration:'1h',reason:'initial'});repo.sentences.set('crime',{id:'crime',guildId:'g',userId:'u',type:'CRIME',reason:'robbery',startedAt:new Date('2026-09-21T11:00:00Z'),endsAt:new Date('2026-09-21T13:00:00Z'),active:true,indefinite:false,restoration:{suspendedRoleIds:[]}});await service.release({guildId:'g',userId:'u',actorUserId:'mod',reason:'review approved'});assert.equal((await repo.getSentence(sent.sentence.id)).active,false);assert.equal((await repo.getSentence('crime')).active,true);assert.equal(await service.hasOtherActivePunishment('g','u',sent.sentence.id),true);assert.equal(repo.expiryJobs.has(sent.sentence.id),false);});

test('expiry is restart-safe, idempotent, and ignores paused sentences',async()=>{const {clock,repo,service}=make();const sent=await service.send({guildId:'g',userId:'u',actorUserId:'mod',duration:'5m',reason:'initial'});const raw=repo.sentences.get(sent.sentence.id);raw.pausedAt=new Date(clock.now());raw.pausedRemainingSeconds=300;clock.advanceMs(10*60*1000);assert.equal(await service.expireSentence(sent.sentence.id),null);raw.pausedAt=undefined;raw.pausedRemainingSeconds=undefined;raw.endsAt=new Date(clock.now().getTime()-1);const expired=await service.expireSentence(sent.sentence.id);assert.equal(expired.sentence.active,false);assert.equal(await service.expireSentence(sent.sentence.id),null);});

test('request review attaches to the original numbered case and only the jailed member may request it',async()=>{const {service}=make();const sent=await service.send({guildId:'g',userId:'u',actorUserId:'mod',duration:'1h',reason:'initial'});const review=await service.requestReview(sent.sentence.id,'u');assert.equal(review.caseId,sent.caseRecord.id);await assert.rejects(()=>service.requestReview(sent.sentence.id,'other'),e=>e instanceof DomainError&&e.code==='REVIEW_NOT_ALLOWED');});
