import test from 'node:test';
import assert from 'node:assert/strict';
import {chapterContent,validateReadingPage,validateTutorialStep,LORE_PARAGRAPH_MAX,conversationSnapshot,tldrDuration} from '../../.test-build/packages/features-learning/src/domain.js';
test('Lore preserves natural paragraphs and rejects empty/unapproved content',()=>{const long='A'.repeat(1400),chapter=chapterContent('not',1,{paragraphs:[long,'Second paragraph.']});assert.deepEqual(chapter.pages,[long,'Second paragraph.']);for(const payload of [{},{paragraphs:[]},{paragraphs:[' ']},{paragraphs:[false]}])assert.throws(()=>chapterContent('not',1,payload));assert.throws(()=>chapterContent('invented',1,{paragraphs:['No']}));});
test('Lore prevents forged final-page completion and allows sequential reading',()=>{const c=chapterContent('chairs',1,{paragraphs:['A'.repeat(1200),'B']});assert.throws(()=>validateReadingPage(1,c));validateReadingPage(0,c);validateReadingPage(1,c,0);assert.throws(()=>validateReadingPage(-1,c));assert.throws(()=>validateReadingPage(2,c,1));});
test('Oversized lore paragraphs are rejected explicitly rather than cut or silently truncated',()=>{assert.equal(chapterContent('not',1,{paragraphs:['A'.repeat(LORE_PARAGRAPH_MAX)]}).pages[0].length,LORE_PARAGRAPH_MAX);for(const text of ['A'.repeat(LORE_PARAGRAPH_MAX+1),'A'.repeat(10000)])assert.throws(()=>chapterContent('not',1,{paragraphs:[text]}),{code:'LORE_CONTENT',message:/authored paragraph break/});});
test('Long input with authored blank-line boundaries retains every paragraph across bounded pages',()=>{const paragraphs=['First paragraph. '+ 'A'.repeat(2000),'Second paragraph. '+'B'.repeat(2000),'Last paragraph.'],chapter=chapterContent('chairs',1,{paragraphs:[paragraphs.join('\r\n\r\n')]});assert.equal(chapter.pages.join('\n\n'),paragraphs.join('\n\n'));assert.ok(chapter.pages.every(p=>p.length<=LORE_PARAGRAPH_MAX));assert.equal(chapter.pages.length,3);assert.throws(()=>validateReadingPage(2,chapter,0),{code:'LORE_PAGE'});});
test('Tutorial stable dotted IDs are accepted, but reset never bypasses the first step',()=>{validateTutorialStep('community.profiles',0,true);validateTutorialStep('staff.case_review-v2',3);for(const step of [1,2,3])assert.throws(()=>validateTutorialStep('community.profiles',step,true),{code:'TUTORIAL_STEP'});for(const id of ['', '.hidden','../admin','private lesson','x'.repeat(81)])assert.throws(()=>validateTutorialStep(id,0),{code:'TUTORIAL_STEP'});});
test('TLDR snapshots exclude bot/system/command/out-of-window messages and retain no message text',()=>{const now=new Date('2026-09-25T12:00Z'),since=new Date('2026-09-25T11:00Z'),base={bot:false,system:false,createdAt:now,content:'Hello lounge'};const result=conversationSnapshot([base,{...base,bot:true},{...base,system:true},{...base,content:'/private command'},{...base,createdAt:new Date('2026-09-24')}],since,now);assert.deepEqual(result,{messages:1,words:2});assert.throws(()=>tldrDuration('events','8h'));assert.equal(tldrDuration('chat','8h'),28800000);});
