import test from 'node:test';import assert from 'node:assert/strict';
import {MusicResolutionService,scoreMusicMatch} from '../../.test-build/packages/features-music/src/resolution.js';
const signal=()=>new AbortController().signal;
const track=(changes={})=>({provider:'spotify',reference:'https://open.spotify.com/track/1234567890123456789012',title:'A Quiet Room',artist:'Fixture Artist',album:'Lounge',durationMs:180000,artworkUrl:null,seekable:true,isrc:'USAAA2600001',...changes});
const candidate=(changes={})=>track({provider:'youtube',reference:changes.provider==='soundcloud'?'https://soundcloud.com/artist/track':'https://www.youtube.com/watch?v=aaaaaaaaaaa',...changes});
test('autoplay filters unrelated artists, variants, repeats and missing durations before selecting',async()=>{const good=candidate({reference:'https://www.youtube.com/watch?v=bbbbbbbbbbb',title:'Next Room'});const service=new MusicResolutionService({search:async()=>[candidate(),candidate({title:'Next Room Live'}),candidate({title:'Next Room',artist:'Other Artist'}),candidate({title:'Next Room',durationMs:null}),good],resolve:async()=>({tracks:[],truncated:false})});const results=await service.recommendations(candidate(),[],signal());assert.deepEqual(results,[good]);assert.deepEqual(await service.recommendations(candidate(),[good.reference],signal()),[]);});
test('plain text search respects music-first priority, falls back on failures and never chooses a result',async()=>{const calls=[];const service=new MusicResolutionService({search:async(source,query)=>{calls.push([source,query.text]);if(source==='youtube_music')throw Error('private provider diagnostic');return[candidate({provider:source,reference:source==='soundcloud'?'https://soundcloud.com/artist/track':'https://www.youtube.com/watch?v=aaaaaaaaaaa'})];},resolve:async()=>({tracks:[],truncated:false})});const rows=await service.search('song artist',2,signal());assert.deepEqual(calls.map(c=>c[0]),['youtube_music','youtube','soundcloud']);assert.equal(rows.length,2);});
test('ISRC query precedes title/artist and an exact recording preserves requested identity',async()=>{const calls=[];const service=new MusicResolutionService({search:async(source,query)=>{calls.push({source,query});return source==='youtube_music'?[candidate()]:[];},resolve:async()=>({tracks:[],truncated:false})});const result=await service.resolvePlayback(track(),signal());assert.equal(result.kind,'matched');assert.equal(result.method,'isrc');assert.equal(result.requested.provider,'spotify');assert.equal(result.playable.provider,'youtube');assert.deepEqual(calls.slice(0,3).map(c=>c.query.isrc),Array(3).fill('USAAA2600001'));assert.equal(calls[3].query.text,'A Quiet Room Fixture Artist');});
test('Apple metadata uses the same provider-neutral resolution and fallback',async()=>{const calls=[];const service=new MusicResolutionService({search:async(source)=>{calls.push(source);if(source!=='soundcloud')throw Error('unavailable');return[candidate({provider:'soundcloud'})];},resolve:async()=>({tracks:[],truncated:false})});const result=await service.resolvePlayback(track({provider:'applemusic',reference:'https://music.apple.com/us/song/123456'}),signal());assert.equal(result.kind,'matched');assert.equal(result.playable.provider,'soundcloud');assert.ok(calls.includes('youtube_music'));});
test('different ISRC, duration and explicit versions are rejected even with identical titles',()=>{for(const changes of [{isrc:'USAAA2600002'},{durationMs:240000},{explicit:false}])assert.equal(scoreMusicMatch(track({explicit:true}),candidate(changes)).score,0);});
test('covers, karaoke, speed, remix, live and instrumental substitutes are rejected',()=>{for(const suffix of ['Cover','Karaoke','Sped Up','Slowed','Remix','Live','Instrumental','Acoustic'])assert.equal(scoreMusicMatch(track(),candidate({title:'A Quiet Room '+suffix})).score,0);assert.equal(scoreMusicMatch(track({title:'A Quiet Room Live'}),candidate({title:'A Quiet Room Live'})).automatic,true);});
test('equal-confidence different recordings produce explicit choices rather than first-result playback',async()=>{const service=new MusicResolutionService({search:async()=>[candidate({reference:'https://www.youtube.com/watch?v=aaaaaaaaaaa'}),candidate({reference:'https://www.youtube.com/watch?v=bbbbbbbbbbb'})],resolve:async()=>({tracks:[],truncated:false})});const result=await service.resolvePlayback(track(),signal());assert.equal(result.kind,'choices');assert.equal(result.choices.length,2);});
test('missing duration or inconsistent artist requires choices, while missing ISRC permits exact metadata matching',async()=>{for(const changes of [{durationMs:null},{artist:'Different Artist'}]){const service=new MusicResolutionService({search:async()=>[candidate(changes)],resolve:async()=>({tracks:[],truncated:false})});assert.equal((await service.resolvePlayback(track(),signal())).kind,'choices');}assert.equal(scoreMusicMatch(track({isrc:null}),candidate({isrc:null})).automatic,true);});
test('no playable candidate returns unavailable and unknown sources never become audio implicitly',async()=>{const service=new MusicResolutionService({search:async()=>[],resolve:async()=>({tracks:[],truncated:false})});assert.equal((await service.resolvePlayback(track(),signal())).kind,'unavailable');await assert.rejects(service.resolvePlayback(track({provider:'unknown'}),signal()),{code:'MUSIC_METADATA'});});
test('restart resolution asks providers again and never persists or reuses encoded capabilities',async()=>{let calls=0;const service=new MusicResolutionService({search:async()=>{calls++;return[{...candidate(),encoded:'secret',streamUrl:'secret'}];},resolve:async()=>({tracks:[],truncated:false})});const first=await service.resolvePlayback(track(),signal()),count=calls;const second=await service.resolvePlayback(JSON.parse(JSON.stringify(first.requested)),signal());assert.ok(calls>count);assert.ok(!JSON.stringify(second).includes('secret'));});
test('cancelled provider requests stop fallback and keep provider errors private',async()=>{const controller=new AbortController(),service=new MusicResolutionService({search:async()=>{controller.abort();throw Error('provider token');},resolve:async()=>({tracks:[],truncated:false})});await assert.rejects(service.resolvePlayback(track(),controller.signal),e=>e.code==='MUSIC_CANCELLED'&&!e.message.includes('token'));});

test('search retains validated earlier choices when a later provider exhausts the deadline',async()=>{
 const controller=new AbortController(),calls=[],good=candidate(),service=new MusicResolutionService({search:async source=>{calls.push(source);if(source==='youtube_music')return[{...good,encoded:'PRIVATE_CAPABILITY'},candidate({reference:'https://private.invalid/track'}),good];controller.abort(new DOMException('Provider deadline','TimeoutError'));throw Error('PRIVATE_PROVIDER_TOKEN');},resolve:async()=>({tracks:[],truncated:false})});
 const rows=await service.search('song artist',25,controller.signal);assert.deepEqual(rows,[good]);assert.deepEqual(calls,['youtube_music','youtube']);assert.ok(!JSON.stringify(rows).includes('PRIVATE'));
});
test('search returns prior choices when deadline expires before the next provider starts',async()=>{
 const controller=new AbortController(),calls=[],good=candidate(),service=new MusicResolutionService({search:async source=>{calls.push(source);controller.abort(new DOMException('Deadline','TimeoutError'));return[good];},resolve:async()=>({tracks:[],truncated:false})});
 assert.deepEqual(await service.search('song',25,controller.signal),[good]);assert.deepEqual(calls,['youtube_music']);
});
test('search timeout with no validated choices still cancels and does not try later providers',async()=>{
 for(const invalidFirst of [false,true]){const controller=new AbortController(),calls=[],service=new MusicResolutionService({search:async source=>{calls.push(source);if(invalidFirst&&source==='youtube_music')return[candidate({reference:'https://private.invalid/track'})];controller.abort(new DOMException('Deadline','TimeoutError'));throw Error('PRIVATE_PROVIDER_TOKEN');},resolve:async()=>({tracks:[],truncated:false})});await assert.rejects(service.search('song',25,controller.signal),e=>e.code==='MUSIC_CANCELLED'&&!e.message.includes('PRIVATE'));assert.deepEqual(calls,invalidFirst?['youtube_music','youtube']:['youtube_music']);}
});
test('explicit cancellation still rejects a search even after valid partial choices',async()=>{
 const controller=new AbortController(),calls=[],service=new MusicResolutionService({search:async source=>{calls.push(source);if(source==='youtube_music')return[candidate()];controller.abort();throw Error('PRIVATE_PROVIDER_TOKEN');},resolve:async()=>({tracks:[],truncated:false})});await assert.rejects(service.search('song',25,controller.signal),{code:'MUSIC_CANCELLED'});assert.deepEqual(calls,['youtube_music','youtube']);
});
test('empty results and ordinary initial provider errors continue through SoundCloud fallback',async()=>{
 const calls=[],good=candidate({provider:'soundcloud'}),service=new MusicResolutionService({search:async source=>{calls.push(source);if(source==='youtube_music')return[];if(source==='youtube')throw Error('Unavailable');return[good];},resolve:async()=>({tracks:[],truncated:false})});assert.deepEqual(await service.search('song',25,signal()),[good]);assert.deepEqual(calls,['youtube_music','youtube','soundcloud']);
});
