import test from 'node:test';
import assert from 'node:assert/strict';
import {createBoard,boardMove,autoFleet,validateFleet,parseFleet,coordinate,coordinateLabel,fire} from '../../.test-build/packages/features-pvp/src/domain.js';
import {validatePvpPolicy} from '../../.test-build/packages/features-pvp/src/prisma-repository.js';
test('Tic-Tac-Toe turn, occupancy, win and draw rules',()=>{let b=createBoard('tictactoe');assert.throws(()=>boardMove(b,1,0),{code:'PVP_TURN'});b=boardMove(b,0,0).board;assert.throws(()=>boardMove(b,1,0),{code:'PVP_OCCUPIED'});for(const cell of [3,1,4])b=boardMove(b,b.turn,cell).board;assert.equal(boardMove(b,0,2).winner,0);b=createBoard('tictactoe');let result;for(const cell of [0,1,2,4,3,5,7,6,8]){result=boardMove(b,b.turn,cell);b=result.board;}assert.equal(result.draw,true);assert.equal(result.winner,undefined);});
test('Connect Four gravity, vertical/horizontal/diagonal wins and full-column rejection',()=>{let b=createBoard('connectfour');for(const c of [0,1,0,1,0,1])b=boardMove(b,b.turn,c).board;assert.equal(boardMove(b,0,0).winner,0);b=createBoard('connectfour');for(const c of [0,0,1,1,2,2])b=boardMove(b,b.turn,c).board;assert.equal(boardMove(b,0,3).winner,0);b=createBoard('connectfour');for(let i=0;i<6;i++)b=boardMove(b,b.turn,0).board;assert.throws(()=>boardMove(b,0,0),{code:'PVP_OCCUPIED'});const cells=Array(42).fill(0);for(const cell of [35,29,23])cells[cell]=1;for(const cell of [38,31,24])cells[cell]=2;assert.equal(boardMove({...createBoard('connectfour'),cells},0,3).winner,0);assert.throws(()=>boardMove(b,0,7),{code:'PVP_MOVE'});});
test('Battleship validates manual geometry and generates complete private fleets',()=>{const f=parseFleet(['A1-A5','B1-B4','C1-C3','D1-D3','E1-E2']);assert.equal(new Set(f.flat()).size,17);assert.deepEqual(coordinateLabel(coordinate('j10')),'J10');for(const s of ['A0','K1','A11','A1B'])assert.throws(()=>coordinate(s));assert.throws(()=>parseFleet(['A1-B5','B1-B4','C1-C3','D1-D3','E1-E2']));assert.throws(()=>validateFleet([f[0],f[1],f[2],f[3],[0,1]]),{code:'PVP_FLEET'});for(let i=0;i<100;i++)assert.equal(new Set(autoFleet().flat()).size,17);});
test('Battleship alternates after hits, rejects repeats and reports sinking/winner only after hits',()=>{const fleet=autoFleet(()=>0);let b=createBoard('battleship');b=fire(b,0,fleet[0][0],fleet).board;assert.equal(b.turn,1);assert.equal(b.shots[0][0].hit,true);assert.throws(()=>fire(b,0,fleet[0][1],fleet),{code:'PVP_TURN'});b={...b,turn:0};assert.throws(()=>fire(b,0,fleet[0][0],fleet),{code:'PVP_FIRED'});let last;for(const cell of fleet.flat().slice(1)){last=fire({...b,turn:0},0,cell,fleet);b=last.board;}assert.equal(last.winner,0);assert.equal(b.shots[0].filter(s=>s.sunk).length,5);});
test('PvP policy fails closed and permits free matches independently of minimum stake',()=>{const p={enabled:true,minWager:10n,maxWager:100n};validatePvpPolicy(p,0n);validatePvpPolicy(p,10n);for(const value of [-1n,1n,101n])assert.throws(()=>validatePvpPolicy(p,value),{code:'PVP_WAGER'});assert.throws(()=>validatePvpPolicy({...p,enabled:false},0n),{code:'PVP_DISABLED'});});
