import type {ModerationRepository} from './repository.js';
import type {AppealRecord,ChannelModerationStateRecord,ModNoteRecord,ModerationCaseEventRecord,ModerationCaseRecord,ModerationEvidenceRecord,ModerationStats,StaffAlertRecord} from './types.js';

const cc=(c:ModerationCaseRecord):ModerationCaseRecord=>({...c,createdAt:new Date(c.createdAt),updatedAt:new Date(c.updatedAt),...(c.metadata?{metadata:structuredClone(c.metadata)}:{})});
const ce=(e:ModerationCaseEventRecord):ModerationCaseEventRecord=>({...e,createdAt:new Date(e.createdAt),...(e.before===undefined?{}:{before:structuredClone(e.before)}),...(e.after===undefined?{}:{after:structuredClone(e.after)})});
const cn=(n:ModNoteRecord)=>({...n,createdAt:new Date(n.createdAt)});
const ca=(a:AppealRecord):AppealRecord=>({...a,createdAt:new Date(a.createdAt),...(a.resolvedAt?{resolvedAt:new Date(a.resolvedAt)}:{})});
const cv=(e:ModerationEvidenceRecord):ModerationEvidenceRecord=>({...e,createdAt:new Date(e.createdAt),...(e.expiresAt?{expiresAt:new Date(e.expiresAt)}:{}),...(e.context?{context:structuredClone(e.context)}:{})});

export class InMemoryModerationRepository implements ModerationRepository {
  readonly cases=new Map<number,ModerationCaseRecord>();readonly events:ModerationCaseEventRecord[]=[];readonly notes:ModNoteRecord[]=[];readonly expiryJobs=new Map<number,{guildId:string;jobType:string;dueAt:Date;userId:string;status:string}>();readonly evidenceJobs=new Map<string,{guildId:string;caseId:number;dueAt:Date;status:string}>();readonly appeals:AppealRecord[]=[];readonly evidence:ModerationEvidenceRecord[]=[];readonly alerts:StaffAlertRecord[]=[];readonly channelStates=new Map<string,ChannelModerationStateRecord>();
  private caseSeq=0;private eventSeq=0;private noteSeq=0;private appealSeq=0;private evidenceSeq=0;private alertSeq=0;private stateSeq=0;
  async createPreparedCase(input:any){const id=++this.caseSeq;const c:ModerationCaseRecord={id,guildId:input.guildId,...(input.subjectUserId?{subjectUserId:input.subjectUserId}:{}),actionType:input.actionType,reason:input.reason,...(input.category?{category:input.category}:{}),...(input.policyId?{policyId:input.policyId}:{}),...(input.actorUserId?{actorUserId:input.actorUserId}:{}),actorType:input.actorType??(input.actorUserId?'STAFF':'SYSTEM'),...(input.sourceChannelId?{sourceChannelId:input.sourceChannelId}:{}),...(input.sourceMessageId?{sourceMessageId:input.sourceMessageId}:{}),...(input.durationSeconds===undefined?{}:{durationSeconds:input.durationSeconds}),status:'OPEN',metadata:{...(input.metadata??{}),pending:true},createdAt:new Date(input.now),updatedAt:new Date(input.now)};this.cases.set(id,c);this.push(id,'PREPARED',input.actorUserId,undefined,{actionType:input.actionType},input.reason,input.now);return cc(c);}
  async finalizeCase(input:any){const c=this.must(input.caseId),before=cc(c);c.status=input.status;c.metadata={...(c.metadata??{}),...(input.metadata??{}),pending:false};c.updatedAt=new Date(input.now);this.push(c.id,input.eventKind,input.actorUserId,before,{status:c.status,metadata:c.metadata},input.reason,input.now);return cc(c);}
  async failPreparedCase(input:any){const c=this.must(input.caseId),before=cc(c);c.status='REVERSED';c.metadata={...(c.metadata??{}),pending:false,enforcementFailed:true,error:input.error};c.updatedAt=new Date(input.now);this.push(c.id,'ENFORCEMENT_FAILED',input.actorUserId,before,{status:c.status,error:input.error},input.reason,input.now);return cc(c);}
  async getCase(id:number){const c=this.cases.get(id);return c?cc(c):null;} async listCaseEvents(id:number){return this.events.filter(e=>e.caseId===id).map(ce);}
  async editCaseReason(input:any){const c=this.must(input.caseId),before={reason:c.reason,status:c.status};c.reason=input.reason;c.status='MODIFIED';c.updatedAt=new Date(input.now);this.push(c.id,'REASON_EDITED',input.actorUserId,before,{reason:c.reason,status:c.status},input.reason,input.now);return cc(c);}
  async reverseCase(input:any){const c=this.must(input.caseId),before=cc(c);c.status='REVERSED';c.metadata={...(c.metadata??{}),...(input.metadata??{}),reversedAt:input.now.toISOString(),reversedBy:input.actorUserId};c.updatedAt=new Date(input.now);this.push(c.id,'REVERSED',input.actorUserId,before,{status:c.status},input.reason,input.now);this.expiryJobs.delete(c.id);return cc(c);}
  async modifyCase(input:any){const c=this.must(input.caseId),before=cc(c);c.status='MODIFIED';c.reason=input.reason||c.reason;if(input.durationSeconds!==undefined){if(input.durationSeconds===null)delete c.durationSeconds;else c.durationSeconds=input.durationSeconds;}c.metadata={...(c.metadata??{}),...(input.metadata??{})};c.updatedAt=new Date(input.now);this.push(c.id,'MODIFIED',input.actorUserId,before,{status:c.status,durationSeconds:c.durationSeconds,metadata:c.metadata},input.reason,input.now);return cc(c);}
  async getTemporaryBanExpiry(caseId:number){const job=this.expiryJobs.get(caseId);return job?.jobType==='moderation.temp_ban_expire'?{...job,dueAt:new Date(job.dueAt)}:null;}
  async expireCase(input:any){const c=this.cases.get(input.caseId);if(!c||!(c.actionType==='BAN'?(c.durationSeconds??0)>0&&['ACTIVE','APPEALED','UPHELD','MODIFIED'].includes(c.status):['ACTIVE','APPEALED'].includes(c.status)))return null;const before=cc(c);c.status='EXPIRED';c.metadata={...(c.metadata??{}),...(input.metadata??{}),expiredAt:input.now.toISOString()};c.updatedAt=new Date(input.now);this.push(c.id,'EXPIRED',undefined,before,{status:c.status},input.reason,input.now);this.expiryJobs.delete(c.id);return cc(c);}
  async listHistory(g:string,u:string,l:number){return [...this.cases.values()].filter(c=>c.guildId===g&&c.subjectUserId===u).sort((a,b)=>b.createdAt.getTime()-a.createdAt.getTime()).slice(0,l).map(cc);} async createNote(i:any){const n:ModNoteRecord={id:`note-${++this.noteSeq}`,guildId:i.guildId,subjectUserId:i.subjectUserId,authorUserId:i.authorUserId,text:i.text,createdAt:new Date(i.now)};this.notes.push(n);return cn(n);} async listNotes(g:string,u:string,l:number){return this.notes.filter(n=>n.guildId===g&&n.subjectUserId===u).slice(-l).reverse().map(cn);}
  async findActiveCases(g:string,u:string,t:readonly string[]){return [...this.cases.values()].filter(c=>c.guildId===g&&c.subjectUserId===u&&['ACTIVE','APPEALED'].includes(c.status)&&t.includes(c.actionType)).map(cc);} async upsertExpiryJob(i:any){this.expiryJobs.set(i.caseId,{guildId:i.guildId,jobType:i.jobType,dueAt:new Date(i.dueAt),userId:i.userId,status:'PENDING'});} async cancelExpiryJobs(id:number){this.expiryJobs.delete(id);}
  async requestReview(i:any){const c=this.must(i.caseId);const existing=this.appeals.find(a=>a.caseId===i.caseId&&a.status==='PENDING');if(existing)return{appealId:existing.id,caseId:c.id,existing:true};const a:AppealRecord={id:`appeal-${++this.appealSeq}`,caseId:c.id,requesterUserId:i.userId,status:'PENDING',...(i.text?{text:i.text}:{}),createdAt:new Date(i.now)};this.appeals.push(a);const before=c.status;c.status='APPEALED';c.updatedAt=new Date(i.now);this.push(c.id,'APPEAL_REQUESTED',i.userId,{status:before},{status:'APPEALED'},i.text,i.now);return{appealId:a.id,caseId:c.id,existing:false};}
  async getAppeal(id:string){const a=this.appeals.find(x=>x.id===id);return a?ca(a):null;} async listAppealsForCase(id:number){return this.appeals.filter(a=>a.caseId===id).map(ca);} async resolveAppeal(i:any){const a=this.appeals.find(x=>x.id===i.appealId);if(!a)throw new Error('Appeal not found.');a.status=i.outcome;a.reviewerUserId=i.reviewerUserId;a.outcomeReason=i.reason;a.resolvedAt=new Date(i.now);const c=this.must(a.caseId);const before=cc(c);c.status=i.caseStatus;if(i.durationSeconds!==undefined){if(i.durationSeconds===null)delete c.durationSeconds;else c.durationSeconds=i.durationSeconds;}c.metadata={...(c.metadata??{}),...(i.caseMetadata??{})};c.updatedAt=new Date(i.now);this.push(c.id,`APPEAL_${i.outcome}`,i.reviewerUserId,before,{status:c.status},i.reason,i.now);return{appeal:ca(a),caseRecord:cc(c)};}
  async createEvidence(i:any){const e:ModerationEvidenceRecord={id:`evidence-${++this.evidenceSeq}`,caseId:i.caseId,contentCiphertext:i.contentCiphertext,context:structuredClone(i.context),expiresAt:new Date(i.expiresAt),createdAt:new Date(i.now)};this.evidence.push(e);return cv(e);} async listEvidence(id:number){return this.evidence.filter(e=>e.caseId===id).map(cv);} async purgeEvidenceContent(id:string,now:Date){const e=this.evidence.find(x=>x.id===id);if(!e)return false;delete e.contentCiphertext;e.context={...(e.context??{}),contentPurgedAt:now.toISOString()};return true;} async upsertEvidenceExpiryJob(i:any){this.evidenceJobs.set(i.evidenceId,{guildId:i.guildId,caseId:i.caseId,dueAt:new Date(i.dueAt),status:'PENDING'});}
  async saveChannelLockState(i:any){const key=`${i.guildId}:${i.channelId}`;const s:ChannelModerationStateRecord={id:`state-${++this.stateSeq}`,guildId:i.guildId,channelId:i.channelId,kind:'LOCK',active:true,snapshot:{sendMessages:i.sendMessages,hadOverwrite:i.hadOverwrite},createdBy:i.createdBy,createdAt:new Date(i.now),updatedAt:new Date(i.now)};this.channelStates.set(key,s);return structuredClone(s);} async getActiveChannelLockState(g:string,c:string){const s=this.channelStates.get(`${g}:${c}`);return s?.active?structuredClone(s):null;} async clearChannelLockState(g:string,c:string,now:Date){const s=this.channelStates.get(`${g}:${c}`);if(s){s.active=false;s.updatedAt=new Date(now);}}
  async createStaffAlert(i:any){const a:StaffAlertRecord={id:`alert-${++this.alertSeq}`,guildId:i.guildId,subjectUserId:i.subjectUserId,actorUserId:i.actorUserId,reason:i.reason,createdAt:new Date(i.now)};this.alerts.push(a);return{...a,createdAt:new Date(a.createdAt)};}
  async getStats(guildId:string,since?:Date):Promise<ModerationStats>{const cases=[...this.cases.values()].filter(c=>c.guildId===guildId&&(!since||c.createdAt>=since));const appeals=this.appeals.filter(a=>{const c=this.cases.get(a.caseId);return c?.guildId===guildId&&(!since||a.createdAt>=since)});const alerts=this.alerts.filter(a=>a.guildId===guildId&&(!since||a.createdAt>=since));const actionCounts:Record<string,number>={},statusCounts:Record<string,number>={},appealOutcomes:Record<string,number>={};for(const c of cases){actionCounts[c.actionType]=(actionCounts[c.actionType]??0)+1;statusCounts[c.status]=(statusCounts[c.status]??0)+1;}for(const a of appeals)appealOutcomes[a.status]=(appealOutcomes[a.status]??0)+1;return{...(since?{since:new Date(since)}:{}),totalCases:cases.length,activeCases:cases.filter(c=>c.status==='ACTIVE').length,appealedCases:cases.filter(c=>c.status==='APPEALED').length,quarantines:actionCounts.QUARANTINE??0,staffAlerts:alerts.length,actionCounts,statusCounts,appealOutcomes};}
  private must(id:number){const c=this.cases.get(id);if(!c)throw new Error('Moderation case not found.');return c;} private push(caseId:number,kind:string,actorUserId:string|undefined,before:unknown,after:unknown,reason:string|undefined,now:Date){this.events.push({id:`event-${++this.eventSeq}`,caseId,kind,...(actorUserId?{actorUserId}:{}),...(before===undefined?{}:{before}),...(after===undefined?{}:{after}),...(reason?{reason}:{}),createdAt:new Date(now)});}
}
