import type {ModerationRepository} from './repository.js';
import type {AppealRecord,ChannelModerationStateRecord,ModNoteRecord,ModerationCaseEventRecord,ModerationCaseRecord,ModerationEvidenceRecord,ModerationStats,StaffAlertRecord} from './types.js';

type Row={id:number;guildId:string;subjectUserId:string|null;actionType:string;reason:string;category:string|null;policyId:string|null;actorUserId:string|null;actorType:string;sourceChannelId:string|null;sourceMessageId:string|null;durationSeconds:number|null;status:string;metadata:unknown;createdAt:Date;updatedAt:Date};
type EventRow={id:string;caseId:number;kind:string;actorUserId:string|null;before:unknown;after:unknown;reason:string|null;createdAt:Date};
type NoteRow={id:string;guildId:string;subjectUserId:string;authorUserId:string;text:string;createdAt:Date};
type AppealRow={id:string;caseId:number;requesterUserId:string;reviewerUserId:string|null;status:string;text:string|null;outcomeReason:string|null;createdAt:Date;resolvedAt:Date|null};
type EvidenceRow={id:string;caseId:number;contentCiphertext:string|null;context:unknown;expiresAt:Date|null;createdAt:Date};
type AlertRow={id:string;guildId:string;subjectUserId:string;actorUserId:string;reason:string;createdAt:Date};
type StateRow={id:string;guildId:string;channelId:string;kind:string;active:boolean;snapshot:unknown;createdBy:string|null;createdAt:Date;updatedAt:Date};
interface DbLike {
  moderationCase:{create(args:any):Promise<Row>;findUnique(args:any):Promise<Row|null>;findMany(args:any):Promise<Row[]>;update(args:any):Promise<Row>;updateMany(args:any):Promise<{count:number}>;count(args:any):Promise<number>};
  moderationCaseEvent:{create(args:any):Promise<EventRow>;findMany(args:any):Promise<EventRow[]>};
  moderationEvidence:{create(args:any):Promise<EvidenceRow>;findMany(args:any):Promise<EvidenceRow[]>;updateMany(args:any):Promise<{count:number}>};
  modNote:{create(args:any):Promise<NoteRow>;findMany(args:any):Promise<NoteRow[]>};
  scheduledJob:{upsert(args:any):Promise<any>;updateMany(args:any):Promise<{count:number}>};
  appeal:{create(args:any):Promise<AppealRow>;findUnique(args:any):Promise<AppealRow|null>;findFirst(args:any):Promise<AppealRow|null>;findMany(args:any):Promise<AppealRow[]>;update(args:any):Promise<AppealRow>};
  staffAlert:{create(args:any):Promise<AlertRow>;count(args:any):Promise<number>};
  channelModerationState:{upsert(args:any):Promise<StateRow>;findFirst(args:any):Promise<StateRow|null>;updateMany(args:any):Promise<{count:number}>};
  $transaction<T>(fn:(tx:Omit<DbLike,'$transaction'>)=>Promise<T>):Promise<T>;
}
const record=(r:Row):ModerationCaseRecord=>({id:r.id,guildId:r.guildId,...(r.subjectUserId?{subjectUserId:r.subjectUserId}:{}),actionType:r.actionType,reason:r.reason,...(r.category?{category:r.category}:{}),...(r.policyId?{policyId:r.policyId}:{}),...(r.actorUserId?{actorUserId:r.actorUserId}:{}),actorType:r.actorType,...(r.sourceChannelId?{sourceChannelId:r.sourceChannelId}:{}),...(r.sourceMessageId?{sourceMessageId:r.sourceMessageId}:{}),...(r.durationSeconds===null?{}:{durationSeconds:r.durationSeconds}),status:r.status as ModerationCaseRecord['status'],...(r.metadata&&typeof r.metadata==='object'?{metadata:r.metadata as Record<string,unknown>} : {}),createdAt:r.createdAt,updatedAt:r.updatedAt});
const event=(r:EventRow):ModerationCaseEventRecord=>({id:r.id,caseId:r.caseId,kind:r.kind,...(r.actorUserId?{actorUserId:r.actorUserId}:{}),...(r.before===null?{}:{before:r.before}),...(r.after===null?{}:{after:r.after}),...(r.reason?{reason:r.reason}:{}),createdAt:r.createdAt});
const note=(r:NoteRow):ModNoteRecord=>({...r});
const appeal=(r:AppealRow):AppealRecord=>({id:r.id,caseId:r.caseId,requesterUserId:r.requesterUserId,...(r.reviewerUserId?{reviewerUserId:r.reviewerUserId}:{}),status:r.status as AppealRecord['status'],...(r.text?{text:r.text}:{}),...(r.outcomeReason?{outcomeReason:r.outcomeReason}:{}),createdAt:r.createdAt,...(r.resolvedAt?{resolvedAt:r.resolvedAt}:{})});
const evidence=(r:EvidenceRow):ModerationEvidenceRecord=>({id:r.id,caseId:r.caseId,...(r.contentCiphertext?{contentCiphertext:r.contentCiphertext}:{}),...(r.context&&typeof r.context==='object'?{context:r.context as Record<string,unknown>} : {}),...(r.expiresAt?{expiresAt:r.expiresAt}:{}),createdAt:r.createdAt});
const state=(r:StateRow):ChannelModerationStateRecord=>({id:r.id,guildId:r.guildId,channelId:r.channelId,kind:'LOCK',active:r.active,snapshot:r.snapshot as ChannelModerationStateRecord['snapshot'],...(r.createdBy?{createdBy:r.createdBy}:{}),createdAt:r.createdAt,updatedAt:r.updatedAt});

export class PrismaModerationRepository implements ModerationRepository {
  constructor(private readonly db:DbLike){}
  async createPreparedCase(input:any){return this.db.$transaction(async tx=>{const c=await tx.moderationCase.create({data:{guildId:input.guildId,subjectUserId:input.subjectUserId??null,actionType:input.actionType,reason:input.reason,category:input.category??null,policyId:input.policyId??null,actorUserId:input.actorUserId??null,actorType:input.actorType??(input.actorUserId?'STAFF':'SYSTEM'),sourceChannelId:input.sourceChannelId??null,sourceMessageId:input.sourceMessageId??null,durationSeconds:input.durationSeconds??null,status:'OPEN',metadata:{...(input.metadata??{}),pending:true},createdAt:input.now}});await tx.moderationCaseEvent.create({data:{caseId:c.id,kind:'PREPARED',actorUserId:input.actorUserId??null,after:{actionType:input.actionType,actorType:input.actorType??(input.actorUserId?'STAFF':'SYSTEM')},reason:input.reason,createdAt:input.now}});return record(c);});}
  async finalizeCase(input:any){return this.db.$transaction(async tx=>{const cur=await tx.moderationCase.findUnique({where:{id:input.caseId}});if(!cur)throw new Error('Moderation case not found.');const meta=cur.metadata&&typeof cur.metadata==='object'?cur.metadata as Record<string,unknown>:{};const c=await tx.moderationCase.update({where:{id:input.caseId},data:{status:input.status,metadata:{...meta,...(input.metadata??{}),pending:false}}});await tx.moderationCaseEvent.create({data:{caseId:c.id,kind:input.eventKind,actorUserId:input.actorUserId??null,before:{status:cur.status,metadata:cur.metadata},after:{status:c.status,metadata:c.metadata},reason:input.reason??null,createdAt:input.now}});return record(c);});}
  async failPreparedCase(input:any){return this.db.$transaction(async tx=>{const cur=await tx.moderationCase.findUnique({where:{id:input.caseId}});if(!cur)throw new Error('Moderation case not found.');const meta=cur.metadata&&typeof cur.metadata==='object'?cur.metadata as Record<string,unknown>:{};const c=await tx.moderationCase.update({where:{id:input.caseId},data:{status:'REVERSED',metadata:{...meta,pending:false,enforcementFailed:true,error:input.error}}});await tx.moderationCaseEvent.create({data:{caseId:c.id,kind:'ENFORCEMENT_FAILED',actorUserId:input.actorUserId??null,before:{status:cur.status},after:{status:c.status,error:input.error},reason:input.reason,createdAt:input.now}});return record(c);});}
  async getCase(id:number){const r=await this.db.moderationCase.findUnique({where:{id}});return r?record(r):null;} async listCaseEvents(caseId:number){return (await this.db.moderationCaseEvent.findMany({where:{caseId},orderBy:{createdAt:'asc'}})).map(event);}
  async editCaseReason(input:any){return this.db.$transaction(async tx=>{const cur=await tx.moderationCase.findUnique({where:{id:input.caseId}});if(!cur)throw new Error('Moderation case not found.');const c=await tx.moderationCase.update({where:{id:input.caseId},data:{reason:input.reason,status:'MODIFIED'}});await tx.moderationCaseEvent.create({data:{caseId:c.id,kind:'REASON_EDITED',actorUserId:input.actorUserId,before:{reason:cur.reason,status:cur.status},after:{reason:c.reason,status:c.status},reason:input.reason,createdAt:input.now}});return record(c);});}
  async reverseCase(input:any){return this.db.$transaction(async tx=>{const cur=await tx.moderationCase.findUnique({where:{id:input.caseId}});if(!cur)throw new Error('Moderation case not found.');const meta=cur.metadata&&typeof cur.metadata==='object'?cur.metadata as Record<string,unknown>:{};const c=await tx.moderationCase.update({where:{id:input.caseId},data:{status:'REVERSED',metadata:{...meta,...(input.metadata??{}),reversedAt:input.now.toISOString(),reversedBy:input.actorUserId}}});await tx.moderationCaseEvent.create({data:{caseId:c.id,kind:'REVERSED',actorUserId:input.actorUserId,before:{status:cur.status},after:{status:c.status},reason:input.reason,createdAt:input.now}});return record(c);});}
  async modifyCase(input:any){return this.db.$transaction(async tx=>{const cur=await tx.moderationCase.findUnique({where:{id:input.caseId}});if(!cur)throw new Error('Moderation case not found.');const meta=cur.metadata&&typeof cur.metadata==='object'?cur.metadata as Record<string,unknown>:{};const data:any={status:'MODIFIED',reason:input.reason||cur.reason,metadata:{...meta,...(input.metadata??{})}};if(input.durationSeconds!==undefined)data.durationSeconds=input.durationSeconds;const c=await tx.moderationCase.update({where:{id:input.caseId},data});await tx.moderationCaseEvent.create({data:{caseId:c.id,kind:'MODIFIED',actorUserId:input.actorUserId,before:{status:cur.status,durationSeconds:cur.durationSeconds},after:{status:c.status,durationSeconds:c.durationSeconds},reason:input.reason,createdAt:input.now}});return record(c);});}
  async expireCase(input:any){return this.db.$transaction(async tx=>{const cur=await tx.moderationCase.findUnique({where:{id:input.caseId}});if(!cur||!['ACTIVE','APPEALED'].includes(cur.status))return null;const meta=cur.metadata&&typeof cur.metadata==='object'?cur.metadata as Record<string,unknown>:{};const c=await tx.moderationCase.update({where:{id:input.caseId},data:{status:'EXPIRED',metadata:{...meta,...(input.metadata??{}),expiredAt:input.now.toISOString()}}});await tx.moderationCaseEvent.create({data:{caseId:c.id,kind:'EXPIRED',actorUserId:null,before:{status:cur.status},after:{status:c.status},reason:input.reason,createdAt:input.now}});return record(c);});}
  async listHistory(g:string,u:string,l:number){return (await this.db.moderationCase.findMany({where:{guildId:g,subjectUserId:u},orderBy:{createdAt:'desc'},take:l})).map(record);} async createNote(i:any){return note(await this.db.modNote.create({data:{guildId:i.guildId,subjectUserId:i.subjectUserId,authorUserId:i.authorUserId,text:i.text,createdAt:i.now}}));} async listNotes(g:string,u:string,l:number){return (await this.db.modNote.findMany({where:{guildId:g,subjectUserId:u},orderBy:{createdAt:'desc'},take:l})).map(note);} async findActiveCases(g:string,u:string,t:readonly string[]){return (await this.db.moderationCase.findMany({where:{guildId:g,subjectUserId:u,status:{in:['ACTIVE','APPEALED']},actionType:{in:[...t]}}})).map(record);}
  async upsertExpiryJob(i:any){const executionKey=`${i.jobType}:${i.caseId}`;await this.db.scheduledJob.upsert({where:{executionKey},create:{guildId:i.guildId,jobType:i.jobType,executionKey,dueAt:i.dueAt,status:'PENDING',payload:{caseId:i.caseId,userId:i.userId}},update:{dueAt:i.dueAt,status:'PENDING',payload:{caseId:i.caseId,userId:i.userId},lastError:null,completedAt:null}});} async cancelExpiryJobs(caseId:number){await this.db.scheduledJob.updateMany({where:{executionKey:{in:[`moderation.timeout_expire:${caseId}`,`moderation.temp_ban_expire:${caseId}`]},status:{in:['PENDING','FAILED','RUNNING']}},data:{status:'CANCELLED'}});}
  async requestReview(i:any){return this.db.$transaction(async tx=>{const cur=await tx.moderationCase.findUnique({where:{id:i.caseId}});if(!cur||cur.subjectUserId!==i.userId)throw new Error('Review requester is not case subject.');const existing=await tx.appeal.findFirst({where:{caseId:i.caseId,status:'PENDING'},orderBy:{createdAt:'desc'}});if(existing)return{appealId:existing.id,caseId:i.caseId,existing:true};const a=await tx.appeal.create({data:{caseId:i.caseId,requesterUserId:i.userId,status:'PENDING',text:i.text??null,createdAt:i.now}});await tx.moderationCase.update({where:{id:i.caseId},data:{status:'APPEALED'}});await tx.moderationCaseEvent.create({data:{caseId:i.caseId,kind:'APPEAL_REQUESTED',actorUserId:i.userId,before:{status:cur.status},after:{status:'APPEALED'},reason:i.text??null,createdAt:i.now}});return{appealId:a.id,caseId:a.caseId,existing:false};});}
  async getAppeal(id:string){const r=await this.db.appeal.findUnique({where:{id}});return r?appeal(r):null;} async listAppealsForCase(caseId:number){return (await this.db.appeal.findMany({where:{caseId},orderBy:{createdAt:'asc'}})).map(appeal);}
  async resolveAppeal(i:any){return this.db.$transaction(async tx=>{const a=await tx.appeal.findUnique({where:{id:i.appealId}});if(!a)throw new Error('Appeal not found.');const cur=await tx.moderationCase.findUnique({where:{id:a.caseId}});if(!cur)throw new Error('Moderation case not found.');const meta=cur.metadata&&typeof cur.metadata==='object'?cur.metadata as Record<string,unknown>:{};const data:any={status:i.caseStatus,metadata:{...meta,...(i.caseMetadata??{})}};if(i.durationSeconds!==undefined)data.durationSeconds=i.durationSeconds;const c=await tx.moderationCase.update({where:{id:a.caseId},data});const ar=await tx.appeal.update({where:{id:i.appealId},data:{reviewerUserId:i.reviewerUserId,status:i.outcome,outcomeReason:i.reason,resolvedAt:i.now}});await tx.moderationCaseEvent.create({data:{caseId:c.id,kind:`APPEAL_${i.outcome}`,actorUserId:i.reviewerUserId,before:{status:cur.status},after:{status:c.status},reason:i.reason,createdAt:i.now}});return{appeal:appeal(ar),caseRecord:record(c)};});}
  async createEvidence(i:any){return evidence(await this.db.moderationEvidence.create({data:{caseId:i.caseId,contentCiphertext:i.contentCiphertext,context:i.context,expiresAt:i.expiresAt,createdAt:i.now}}));} async listEvidence(caseId:number){return (await this.db.moderationEvidence.findMany({where:{caseId},orderBy:{createdAt:'asc'}})).map(evidence);} async purgeEvidenceContent(id:string,now:Date){const r=await this.db.moderationEvidence.updateMany({where:{id,contentCiphertext:{not:null}},data:{contentCiphertext:null,context:{contentPurgedAt:now.toISOString()}}});return r.count>0;} async upsertEvidenceExpiryJob(i:any){const executionKey=`moderation.evidence_expire:${i.evidenceId}`;await this.db.scheduledJob.upsert({where:{executionKey},create:{guildId:i.guildId,jobType:'moderation.evidence_expire',executionKey,dueAt:i.dueAt,status:'PENDING',payload:{caseId:i.caseId,evidenceId:i.evidenceId}},update:{dueAt:i.dueAt,status:'PENDING',payload:{caseId:i.caseId,evidenceId:i.evidenceId},lastError:null,completedAt:null}});}
  async saveChannelLockState(i:any){const r=await this.db.channelModerationState.upsert({where:{guildId_channelId_kind:{guildId:i.guildId,channelId:i.channelId,kind:'LOCK'}},create:{guildId:i.guildId,channelId:i.channelId,kind:'LOCK',active:true,snapshot:{sendMessages:i.sendMessages,hadOverwrite:i.hadOverwrite},createdBy:i.createdBy,createdAt:i.now},update:{active:true,snapshot:{sendMessages:i.sendMessages,hadOverwrite:i.hadOverwrite},createdBy:i.createdBy,updatedAt:i.now}});return state(r);} async getActiveChannelLockState(g:string,c:string){const r=await this.db.channelModerationState.findFirst({where:{guildId:g,channelId:c,kind:'LOCK',active:true}});return r?state(r):null;} async clearChannelLockState(g:string,c:string,now:Date){await this.db.channelModerationState.updateMany({where:{guildId:g,channelId:c,kind:'LOCK',active:true},data:{active:false,updatedAt:now}});}
  async createStaffAlert(i:any){const r=await this.db.staffAlert.create({data:{guildId:i.guildId,subjectUserId:i.subjectUserId,actorUserId:i.actorUserId,reason:i.reason,createdAt:i.now}});return{...r};}
  async getStats(guildId:string,since?:Date):Promise<ModerationStats>{const where:any={guildId,...(since?{createdAt:{gte:since}}:{})};const cases=await this.db.moderationCase.findMany({where,orderBy:{createdAt:'desc'}});const actionCounts:Record<string,number>={},statusCounts:Record<string,number>={};for(const c of cases){actionCounts[c.actionType]=(actionCounts[c.actionType]??0)+1;statusCounts[c.status]=(statusCounts[c.status]??0)+1;}const appeals=await this.db.appeal.findMany({where:{case:{guildId},...(since?{createdAt:{gte:since}}:{})}});const appealOutcomes:Record<string,number>={};for(const a of appeals)appealOutcomes[a.status]=(appealOutcomes[a.status]??0)+1;const staffAlerts=await this.db.staffAlert.count({where:{guildId,...(since?{createdAt:{gte:since}}:{})}});return{...(since?{since}:{}),totalCases:cases.length,activeCases:cases.filter(c=>c.status==='ACTIVE').length,appealedCases:cases.filter(c=>c.status==='APPEALED').length,quarantines:actionCounts.QUARANTINE??0,staffAlerts,actionCounts,statusCounts,appealOutcomes};}
}
