import type {AuditService,Clock} from '../../core/src/index.js';
import {DomainError} from '../../core/src/index.js';
import type {ModerationRepository} from './repository.js';
import type {AppealOutcome,CasePreparationInput,ModerationCaseRecord,ModerationHistory,ModerationStats,ParsedModerationDuration} from './types.js';

const MIN_TIMEOUT_SECONDS=10;
const MAX_TIMEOUT_SECONDS=28*24*60*60;
const MAX_TEMP_BAN_SECONDS=365*24*60*60;
const MAX_SLOWMODE_SECONDS=6*60*60;
const DEFAULT_EVIDENCE_RETENTION_DAYS=30;
const units:Record<string,number>={s:1,sec:1,secs:1,second:1,seconds:1,m:60,min:60,mins:60,minute:60,minutes:60,h:3600,hr:3600,hrs:3600,hour:3600,hours:3600,d:86400,day:86400,days:86400,w:604800,week:604800,weeks:604800};

const parseSeconds=(raw:string)=>{const value=raw.trim().toLowerCase().replace(/,/g,' ');let total=0;let hits=0;for(const m of value.matchAll(/(\d+)\s*(seconds?|secs?|s|minutes?|mins?|m|hours?|hrs?|h|days?|d|weeks?|w)\b/g)){total+=Number(m[1])*(units[m[2]??'']??0);hits++;}if(!hits){const simple=/^(\d+)\s*([smhdw])$/.exec(value);if(simple)total=Number(simple[1])*(units[simple[2]??'']??0);}return total;};
const format=(seconds:number)=>{let r=seconds;const parts:string[]=[];for(const [label,size] of [['d',86400],['h',3600],['m',60],['s',1]] as const){const n=Math.floor(r/size);if(n){parts.push(`${n}${label}`);r-=n*size;}if(parts.length===2)break;}return parts.join(' ')||'0s';};
export const parseTimeoutDuration=(raw:string):ParsedModerationDuration=>{const seconds=parseSeconds(raw);if(seconds<MIN_TIMEOUT_SECONDS||seconds>MAX_TIMEOUT_SECONDS)throw new DomainError('INVALID_TIMEOUT_DURATION','Timeout duration must be between 10 seconds and 28 days.');return{permanent:false,seconds,label:format(seconds)};};
export const parseBanDuration=(raw?:string|null):ParsedModerationDuration=>{const value=(raw??'permanent').trim().toLowerCase();if(!value||value==='permanent'||value==='perm'||value==='forever')return{permanent:true,label:'Permanent'};const seconds=parseSeconds(value);if(seconds<60||seconds>MAX_TEMP_BAN_SECONDS)throw new DomainError('INVALID_BAN_DURATION','Temporary ban duration must be between 1 minute and 365 days, or `permanent`.');return{permanent:false,seconds,label:format(seconds)};};
export const parseSlowmodeDuration=(raw:string):ParsedModerationDuration=>{const value=raw.trim().toLowerCase();if(['off','none','0','0s'].includes(value))return{permanent:false,seconds:0,label:'Off'};const seconds=parseSeconds(value);if(seconds<0||seconds>MAX_SLOWMODE_SECONDS)throw new DomainError('INVALID_SLOWMODE_DURATION','Slowmode must be between 0 seconds and 6 hours.');if(!seconds)throw new DomainError('INVALID_SLOWMODE_DURATION','Use `off` or a duration between 1 second and 6 hours.');return{permanent:false,seconds,label:format(seconds)};};
export const parseStatsPeriod=(raw?:string|null):{label:string;since?:Date;seconds?:number}=>{const value=(raw??'7d').trim().toLowerCase();if(value==='all'||value==='all-time'||value==='alltime')return{label:'All time'};const seconds=parseSeconds(value);if(!seconds||seconds>365*24*60*60)throw new DomainError('INVALID_MODSTATS_PERIOD','Modstats period must be a duration up to 365 days or `all`.');return{label:format(seconds),seconds};};

const reversible=new Set(['WARN','TIMEOUT','BAN']);
export class ModerationService {
  constructor(private readonly repository:ModerationRepository,private readonly audit:AuditService,private readonly clock:Clock){}
  async prepare(input:CasePreparationInput){if(!input.reason.trim())throw new DomainError('MOD_REASON_REQUIRED','A moderation reason is required.');const now=this.clock.now();const c=await this.repository.createPreparedCase({...input,reason:input.reason.trim(),now});await this.audit.record({guildId:input.guildId,...(input.actorUserId?{actorUserId:input.actorUserId}:{}),source:'discord',action:'moderation.prepare',targetType:'case',targetId:String(c.id),after:{actionType:c.actionType,subjectUserId:c.subjectUserId,actorType:c.actorType},reason:c.reason,requestId:`mod-prepare:${c.id}`,createdAt:now});return c;}
  async finalize(caseId:number,status:ModerationCaseRecord['status'],input:{actorUserId?:string;metadata?:Record<string,unknown>;reason?:string;eventKind?:string}={}){const now=this.clock.now();const c=await this.repository.finalizeCase({caseId,status,...input,eventKind:input.eventKind??'ENFORCED',now});await this.audit.record({guildId:c.guildId,...(input.actorUserId?{actorUserId:input.actorUserId}:{}),source:'discord',action:'moderation.finalize',targetType:'case',targetId:String(c.id),after:{status:c.status,metadata:c.metadata},reason:input.reason??c.reason,requestId:`mod-finalize:${c.id}:${now.getTime()}`,createdAt:now});return c;}
  async enforcementFailed(caseId:number,actorUserId:string|undefined,reason:string,error:unknown){const now=this.clock.now();const message=error instanceof Error?error.message:String(error);const c=await this.repository.failPreparedCase({caseId,...(actorUserId?{actorUserId}:{}),reason,error:message,now});await this.audit.record({guildId:c.guildId,...(actorUserId?{actorUserId}:{}),source:'discord',action:'moderation.enforcement_failed',targetType:'case',targetId:String(c.id),after:{error:message},reason,requestId:`mod-failed:${c.id}:${now.getTime()}`,createdAt:now});return c;}
  async scheduleTemporaryCase(c:ModerationCaseRecord,userId:string,seconds:number,jobType:'moderation.timeout_expire'|'moderation.temp_ban_expire'){const dueAt=new Date(this.clock.now().getTime()+seconds*1000);await this.repository.upsertExpiryJob({guildId:c.guildId,caseId:c.id,jobType,dueAt,userId});return dueAt;}
  async expire(caseId:number,reason:string,metadata?:Record<string,unknown>){const now=this.clock.now();const c=await this.repository.expireCase({caseId,reason,now,...(metadata?{metadata}:{})});if(!c)return null;await this.audit.record({guildId:c.guildId,source:'scheduler',action:'moderation.expire',targetType:'case',targetId:String(c.id),after:{status:c.status},reason,requestId:`mod-expire:${c.id}`,createdAt:now});return c;}
  async editReason(caseId:number,actorUserId:string,reason:string){if(!reason.trim())throw new DomainError('MOD_REASON_REQUIRED','A corrected reason is required.');const now=this.clock.now();const c=await this.repository.editCaseReason({caseId,actorUserId,reason:reason.trim(),now});await this.audit.record({guildId:c.guildId,actorUserId,source:'discord',action:'moderation.case_edit',targetType:'case',targetId:String(caseId),after:{reason:c.reason,status:c.status},reason:c.reason,requestId:`mod-case-edit:${caseId}:${now.getTime()}`,createdAt:now});return c;}
  async reverse(caseId:number,actorUserId:string,reason:string,metadata?:Record<string,unknown>){const current=await this.requireCase(caseId);if(!reversible.has(current.actionType))throw new DomainError('CASE_NOT_REVERSIBLE',`${current.actionType} cannot be safely reversed automatically.`);if(current.status==='REVERSED')throw new DomainError('CASE_ALREADY_REVERSED','That case has already been reversed.');const now=this.clock.now();const c=await this.repository.reverseCase({caseId,actorUserId,reason:reason.trim()||'Reversed by staff.',now,...(metadata?{metadata}:{})});await this.repository.cancelExpiryJobs(caseId);await this.audit.record({guildId:c.guildId,actorUserId,source:'discord',action:'moderation.case_reverse',targetType:'case',targetId:String(caseId),before:{status:current.status},after:{status:c.status},reason,requestId:`mod-case-reverse:${caseId}:${now.getTime()}`,createdAt:now});return c;}
  async closeActiveCases(guildId:string,userId:string,types:readonly string[],actorUserId:string,reason:string){const rows=await this.repository.findActiveCases(guildId,userId,types);const out:ModerationCaseRecord[]=[];for(const row of rows){const now=this.clock.now();const closed=await this.repository.reverseCase({caseId:row.id,actorUserId,reason,now,metadata:{closedByAction:true}});await this.repository.cancelExpiryJobs(row.id);await this.audit.record({guildId,actorUserId,source:'discord',action:'moderation.close_active_case',targetType:'case',targetId:String(row.id),before:{status:row.status},after:{status:closed.status},reason,requestId:`mod-close-active:${row.id}:${now.getTime()}`,createdAt:now});out.push(closed);}return out;}
  async note(guildId:string,userId:string,authorUserId:string,text:string){if(!text.trim())throw new DomainError('NOTE_REQUIRED','A staff note cannot be empty.');const now=this.clock.now();const note=await this.repository.createNote({guildId,subjectUserId:userId,authorUserId,text:text.trim(),now});await this.audit.record({guildId,actorUserId:authorUserId,source:'discord',action:'moderation.note',targetType:'member',targetId:userId,after:{noteId:note.id},reason:'Staff note added.',requestId:`mod-note:${note.id}`,createdAt:now});return note;}
  async history(guildId:string,userId:string,limit=20):Promise<ModerationHistory>{return{cases:await this.repository.listHistory(guildId,userId,limit),notes:await this.repository.listNotes(guildId,userId,limit)};}
  async caseView(caseId:number){const c=await this.requireCase(caseId);return{caseRecord:c,events:await this.repository.listCaseEvents(caseId),evidence:await this.repository.listEvidence(caseId),appeals:await this.repository.listAppealsForCase(caseId)};}
  async requestReview(caseId:number,userId:string,text?:string){const c=await this.requireCase(caseId);if(c.subjectUserId!==userId)throw new DomainError('REVIEW_NOT_ALLOWED','You can only request review of a moderation action taken against you.');const now=this.clock.now();const result=await this.repository.requestReview({caseId,userId,...(text?{text}:{}),now});if(!result.existing)await this.audit.record({guildId:c.guildId,actorUserId:userId,source:'discord',action:'moderation.review_request',targetType:'case',targetId:String(caseId),after:{appealId:result.appealId},reason:text??'Review requested.',requestId:`mod-review:${caseId}:${result.appealId}`,createdAt:now});return result;}
  async requireAppeal(appealId:string){const a=await this.repository.getAppeal(appealId);if(!a)throw new DomainError('APPEAL_NOT_FOUND','That review request was not found.');return a;}
  /** Read-only preflight, shared by Discord before enforcement and resolution before persistence. */
  async validateAppealReview(appealId:string,reviewerUserId:string,guildId?:string){
    const appeal=await this.requireAppeal(appealId);
    const caseRecord=await this.requireCase(appeal.caseId);
    if(guildId!==undefined&&caseRecord.guildId!==guildId)throw new DomainError('CASE_WRONG_SERVER','That case belongs to another server.');
    if(appeal.status!=='PENDING')throw new DomainError('APPEAL_ALREADY_RESOLVED','That review request has already been resolved.');
    if(caseRecord.actorUserId===reviewerUserId)throw new DomainError('APPEAL_REVIEWER_CONFLICT','The moderator who issued the action cannot be the sole reviewer of their own case.');
    return{appeal,caseRecord};
  }
  async resolveAppeal(input:{appealId:string;reviewerUserId:string;outcome:AppealOutcome;reason:string;durationSeconds?:number|null;metadata?:Record<string,unknown>}){if(!input.reason.trim())throw new DomainError('APPEAL_REASON_REQUIRED','A review outcome requires a rationale.');const {appeal,caseRecord:current}=await this.validateAppealReview(input.appealId,input.reviewerUserId);let status:ModerationCaseRecord['status']=input.outcome;if(current.status==='EXPIRED'&&input.outcome!=='REVERSED')status='EXPIRED';const now=this.clock.now();const result=await this.repository.resolveAppeal({appealId:input.appealId,reviewerUserId:input.reviewerUserId,outcome:input.outcome,reason:input.reason.trim(),now,caseStatus:status,...(input.durationSeconds===undefined?{}:{durationSeconds:input.durationSeconds}),caseMetadata:{...(input.metadata??{}),appealOutcome:input.outcome,appealReviewerUserId:input.reviewerUserId}});if(input.outcome==='REVERSED')await this.repository.cancelExpiryJobs(current.id);await this.audit.record({guildId:current.guildId,actorUserId:input.reviewerUserId,source:'discord',action:`moderation.appeal_${input.outcome.toLowerCase()}`,targetType:'case',targetId:String(current.id),before:{status:current.status},after:{status:result.caseRecord.status,appealId:appeal.id},reason:input.reason.trim(),requestId:`mod-appeal:${appeal.id}:${now.getTime()}`,createdAt:now});return result;}
  async modifyCaseFromAppeal(caseId:number,reviewerUserId:string,reason:string,durationSeconds?:number|null,metadata?:Record<string,unknown>){const now=this.clock.now();const c=await this.repository.modifyCase({caseId,actorUserId:reviewerUserId,reason:reason.trim(),now,...(durationSeconds===undefined?{}:{durationSeconds}),...(metadata?{metadata}:{})});await this.audit.record({guildId:c.guildId,actorUserId:reviewerUserId,source:'discord',action:'moderation.case_modified_from_appeal',targetType:'case',targetId:String(caseId),after:{durationSeconds:c.durationSeconds,metadata:c.metadata},reason,requestId:`mod-appeal-modify-case:${caseId}:${now.getTime()}`,createdAt:now});return c;}
  async storeEvidence(input:{caseRecord:ModerationCaseRecord;contentCiphertext:string;context:Record<string,unknown>;retentionDays?:number}){const days=input.retentionDays??DEFAULT_EVIDENCE_RETENTION_DAYS;if(!Number.isInteger(days)||days<1||days>365)throw new DomainError('INVALID_EVIDENCE_RETENTION','Evidence retention must be between 1 and 365 days.');const now=this.clock.now();const expiresAt=new Date(now.getTime()+days*86400_000);const e=await this.repository.createEvidence({caseId:input.caseRecord.id,contentCiphertext:input.contentCiphertext,context:input.context,expiresAt,now});await this.repository.upsertEvidenceExpiryJob({guildId:input.caseRecord.guildId,caseId:input.caseRecord.id,evidenceId:e.id,dueAt:expiresAt});await this.audit.record({guildId:input.caseRecord.guildId,source:'discord',action:'moderation.evidence_store',targetType:'evidence',targetId:e.id,after:{caseId:e.caseId,expiresAt},reason:'Restricted moderation evidence retained.',requestId:`mod-evidence:${e.id}`,createdAt:now});return e;}
  async purgeEvidence(evidenceId:string){const now=this.clock.now();const purged=await this.repository.purgeEvidenceContent(evidenceId,now);return purged;}
  async saveChannelLock(guildId:string,channelId:string,sendMessages:'allow'|'deny'|'inherit',hadOverwrite:boolean,actorUserId:string){const now=this.clock.now();const existing=await this.repository.getActiveChannelLockState(guildId,channelId);if(existing)throw new DomainError('CHANNEL_ALREADY_LOCKED','That channel is already locked by Angrier Jordan.');const state=await this.repository.saveChannelLockState({guildId,channelId,sendMessages,hadOverwrite,createdBy:actorUserId,now});await this.audit.record({guildId,actorUserId,source:'discord',action:'moderation.channel_lock_snapshot',targetType:'channel',targetId:channelId,after:{sendMessages,hadOverwrite},reason:'Pre-lock channel state captured.',requestId:`mod-lock-snapshot:${guildId}:${channelId}:${now.getTime()}`,createdAt:now});return state;}
  async getChannelLock(guildId:string,channelId:string){const state=await this.repository.getActiveChannelLockState(guildId,channelId);if(!state)throw new DomainError('CHANNEL_NOT_LOCKED','That channel does not have an active Angrier Jordan lock snapshot.');return state;}
  async clearChannelLock(guildId:string,channelId:string,actorUserId:string){const now=this.clock.now();await this.repository.clearChannelLockState(guildId,channelId,now);await this.audit.record({guildId,actorUserId,source:'discord',action:'moderation.channel_lock_restored',targetType:'channel',targetId:channelId,after:{active:false},reason:'Tracked pre-lock channel state restored.',requestId:`mod-unlock:${guildId}:${channelId}:${now.getTime()}`,createdAt:now});}
  async staffAlert(guildId:string,userId:string,actorUserId:string,reason:string){if(!reason.trim())throw new DomainError('MOD_REASON_REQUIRED','A staff-alert reason is required.');const now=this.clock.now();const alert=await this.repository.createStaffAlert({guildId,subjectUserId:userId,actorUserId,reason:reason.trim(),now});await this.audit.record({guildId,actorUserId,source:'discord',action:'moderation.staff_alert',targetType:'member',targetId:userId,after:{alertId:alert.id},reason:alert.reason,requestId:`mod-staff-alert:${alert.id}`,createdAt:now});return alert;}
  async stats(guildId:string,period?:string|null):Promise<{label:string;stats:ModerationStats}>{const parsed=parseStatsPeriod(period);const since=parsed.seconds?new Date(this.clock.now().getTime()-parsed.seconds*1000):undefined;return{label:parsed.label,stats:await this.repository.getStats(guildId,since)};}
  async cancelExpiryForCase(caseId:number){await this.repository.cancelExpiryJobs(caseId);}
  async requireCase(caseId:number){const c=await this.repository.getCase(caseId);if(!c)throw new DomainError('CASE_NOT_FOUND',`Moderation case #${caseId} was not found.`);return c;}
}
